- orchagent/qosorch.cpp
**What I did**
- For DOT1P QOS map, the map list in api that coverts \<field, value\> to attributes was not initialized correctly. So "color" field in the key was sending garbage. Because of this, orchagent serialization function is unable to translate and serialize the attribute
value properly and returns warning. During subsequent operation which comes with a different garbage, this was treated as a different "color" and syncd/SAI returns error saying "modification not implemented". This is fixed by initializing the dotp1 map list attribute.
- Because of the initialization issue described above, we we unable to configure dot1p map. So this fix was done.
- Used dot1p configuration (in DSCP_TO_TC_MAP table) and observed that there are no …
> [qosorch] Dot1p map list initialization fix

- orchagent/request_parser.cpp
- orchagent/request_parser.h
**What I did**
Add an option for request parser to parse strings that contains multiple IP address, MAC address, or unsigned int. Return the values in a vector.
To enable overlay ECMP, the request may contain values with multiple nexthops. This PR aims to properly parse the request in such a scenario.
> [request parser] Allow request parser to parse multiple values

- orchagent/muxorch.cpp
- orchagent/muxorch.h
- orchagent/orchdaemon.cpp
- tests/test_mux.py
**What I did**
Log mux state change events to State DB (required for bookkeeping) 
```
127.0.0.1:6379[6]> HGETALL "MUX_METRICS_TABLE|Ethernet4"
1) "orch_switch_standby_start"
2) "2021-May-25 14:43:57.85633"
3) "orch_switch_standby_end"
4) "2021-May-25 14:43:57.93600"
```
Part of the overall mux metric changes by linkmgrd, xcvrd ([PR](https://github.com/Azure/sonic-platform-daemons/pull/185))
Execute mux state change and verify the State DB tables. 
> [Mux] Add support for mux metrics to State DB

- .azure-pipelines/test-docker-sonic-vs-template.yml
- tests/test_port_dpb_system.py
- tests/test_portchannel.py
**What I did**
1. Skip flaky tests - DPB ARP flush, LAG TPID
Issue details - https://github.com/Azure/sonic-swss/issues/1778, https://github.com/Azure/sonic-swss/issues/1779
2. Abort test if VRF cannot be configured. Example failure
```
Linux fv-az234-728 5.8.0-1033-azure #35~20.04.1-Ubuntu SMP Wed May 19 06:46:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
+ sudo /sbin/ip link add Vrf1 type vrf table
Command line is not complete. Try option "help"
+ echo 'vrf command failed'
+ exit 1
vrf command failed
```
Unblock PRs.
By - https://github.com/Azure/sonic-swss/pull/1775
> [VS Test Stability] Temporarily skip flaky tests

- orchagent/vxlanorch.cpp
- orchagent/vxlanorch.h
- tests/test_vnet.py
Changes provide functionality to configure different types of mappers for the same VxLAN tunnel.
In order to be able to use 1 tunnel with both VLAN and VRF mappers instead of creaing 2 tunnels.
**What I did**
Added functionality to configure different types of mappers for the same VxLAN tunnel.
In order to be able to use 1 tunnel with both VLAN and VRF mappers instead of creating 2 tunnels.
***Manual tests***
* Run "VNET" test (it configures tunnel with VRF mappers)
* Run "wr_arp" test (it configures tunnel map with VLAN mapper)
* Verify that test passed
* Verify configuration in ASIC DB
***VS tests***
```
sudo pytest -v test_vnet.py
===================================== test session starts …
```
> [vnet/vxlan] Add support of multiple mappers for the VxLAN tunnel

- tests/request_parser_ut.cpp
**What I did**
Add unit tests for request parser to parse multiple values.
Add unit tests for the feature added in PR https://github.com/Azure/sonic-swss/pull/1758.
Run unit tests locally and confirm the tests passes with the given conditions and constraints.
> [request parser] Add unit tests for request parser to parse multiple values

- orchagent/macsecorch.cpp
**What I did**
ACL entry Id should be used as first parameter of setMACsecFlowActive. 
> [macsec] Fix acl entry id in updateMACsecPort

- orchagent/bufferorch.cpp
- orchagent/bufferorch.h
- orchagent/qosorch.cpp
**What I did**
Changes done to allow orchagent accepting "both" type for buffer pool
configuration.
Currently sonic supports only 'ingress' and 'egress' types of buffer pools.
Since some devices like DNX based switches only support buffer pool
type 'both', we are unable to create buffer pools for these devices.
This patch fixes this problem by enhancing buffer pool configuration to
accept "both" type. 
In a switch that uses DNX arch based chips (like VOQ chassis using line cards with Jerico family of switches), the following configuration is applied
```
"BUFFER_POOL": {
"lossless_pool": {
"size": "12766208",
"type": "both",
"mode": "dynamic"
}
}
```
when the switch became operational, it was observed, there are no error logs indicating invalid …
> [bufferpool] Support for buffer pool type both

- tests/test_portchannel.py
Frequent failure seen on `test_portchannel.py::TestPortchannel::test_Portchannel_tpid` from https://github.com/Azure/sonic-swss/pull/1642 vs pipeline, apart from https://github.com/Azure/sonic-buildimage/issues/7791
Looks like preceding test `test_Portchannel_oper_down` end-of-test cleanup is not clear. Lag removal retry is left over in `doTask` to the subsequent test
```
227829 Jun  3 18:11:18.929051 9faa323d761d ERR #orchagent: :- removeLag: Failed to remove ref count 1 LAG PortChannel001
227830 Jun  3 18:11:18.929057 9faa323d761d ERR #orchagent: :- removeLag: Failed to remove ref count 1 LAG PortChannel002
227831 Jun  3 18:11:18.929061 9faa323d761d ERR #orchagent: :- removeLag: Failed to remove ref count 1 LAG PortChannel003 …
```
> [vs] Stablize test portchannel: test_Portchannel_oper_down end-of-test cleanup fix

- orchagent/nexthopgroupkey.h
Reset m_overlay_nexthops to false for NHG key with weights
**What I did**
Reset NHG key with m_overlay_nexthops to false
NHG key with weights are only called in non_overlay nexthop, in the constructor, we have to explicitly set it to false.
Checking the logic.
> Fix NHG key with weight overlay flag.

- orchagent/nexthopgroupkey.h
- orchagent/routeorch.cpp
**What I did**
1. Remove default prefix in non-default VRF instead of setting it to blackhole
2. Initialize `m_overlay_nexthops` in overloaded constructor. 
To fix https://github.com/Azure/sonic-buildimage/issues/6504
1. To remove default routes in non default VRF
2. To avoid garbage in `m_overlay_nexthops`. 
1. Add t0 topology
2. Load config generated by this test vrf/test_vrf.py::TestVrfDeletion::test_vrf1_neigh_after_restore
3. `sudo config vrf del Vrf1`
4. `redis-cli -n 6 keys "*VRF*"`
5. check that there is entries only for Vrf2. e.g:
```
1) "VRF_OBJECT_TABLE|Vrf2"
2) "VRF_TABLE|Vrf2"
```
> [orchagent] Remove default prefix in non default vrf

- .azure-pipelines/build-docker-sonic-vs-template.yml
- .azure-pipelines/build-template.yml
- .azure-pipelines/build_and_install_module.sh
- .azure-pipelines/docker-sonic-vs/Dockerfile
- .azure-pipelines/test-docker-sonic-vs-template.yml
- azure-pipelines.yml
**What I did**
Merge azure pipelines from master to 202012 branch
> [ci]: Merge azure pipelines from master to 202012 branch

- orchagent/macsecorch.cpp
- orchagent/port.h
- orchagent/portsorch.cpp
**What I did**
To support MACsec on Arista 7280cr3, which uses external gearbox chips, the switch Id and port Id used in MACsec SAI APIs have to be coming from the context of the gearbox chips. This change implements it by saving the Ids in initGearboxPort() and used them in MACsecOrchContext.
> [MACsec]: Support switchId and portId for gearbox

- .github/CODEOWNERS
**What I did**
Add ownership file for swss repo
> [doc]: Add github ownership file

- fpmsyncd/routesync.cpp
- fpmsyncd/routesync.h
- orchagent/nexthopgroupkey.h
- orchagent/nexthopkey.h
- orchagent/routeorch.cpp
- tests/test_nhg.py
This reverts commit a44e6513556cfed7de1b70690db90cc09fcef666.
**What I did**
This PR is to revert the changes made in #1752 
Proper weight initialization is needed when weights are not provided:
https://github.com/Azure/sonic-swss/blob/a44e6513556cfed7de1b70690db90cc09fcef666/orchagent/routeorch.cpp#L638
Warmboot is failing on various platforms: https://github.com/Azure/sonic-buildimage/issues/7919
The original PR needs some negative unit testcases when the weight is not present for the nexthop group.
> Revert "[nhg]: Add support for weight in nexthop group member. (#1752)"

- .azure-pipelines/build_and_install_module.sh
**What I did**
When run "make modules_prepare", it prompts an ask as below:
Microsoft Network Devices (NET_VENDOR_MICROSOFT) [Y/n/?] (NEW) 
It should be caused by the new version of the kernel config mis-match with existing one.
To fix it, add the CONFIG_NET_VENDOR_MICROSOFT and CONFIG_MICROSOFT_MANA settings in the .config file.
It works fine on ubuntu-18.04 and ubuntu-20.04, Microsoft hosted agents.
See https://dev.azure.com/mssonic/build/_build/results?buildId=21055&view=logs&j=657b12aa-b45f-5386-f4c1-26b2b4a76d61&t=68eb240e-e28b-5b11-f4d4-8655b80fc194
> [ci] Fix config prompt question issue

- tests/test_port_dpb_system.py
- tests/test_virtual_chassis.py
**What I did**
DPB tests are consistently failing.
Logs at: https://dev.azure.com/mssonic/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/build/builds/21324/logs/58
Unblock PRs
> [VS test stability] Skip flaky test for DPB

- cfgmgr/buffermgrdyn.cpp
- cfgmgr/buffermgrdyn.h
- orchagent/bufferorch.cpp
- orchagent/bufferorch.h
- orchagent/portsorch.cpp
- tests/test_buffer_dynamic.py
**What I did**
- Avoid creating lossy PGs for admin down ports during system initialization
- Make ADMIN_DOWN the default state of a port in dynamic buffer manager.
- Explicitly remove configured PGs from an admin down port during initialization
This is to make sure the items will be added to m_ready_list.
- Use APPL_DB as the source of initial PGs and queues for port ready deducting for warm reboot
Lossy PGs for admin down ports should not be applied to `APPL_DB`.
Originally, we had the logic to remove lossy/lossless PGs when shutting a port. The same logic should be applied when the system is starting. Allocating lossy PG for an admin down port doesn't affect the system negatively except for wasting buffer. So we would …
> [Dynamic Buffer Calc] Avoid creating lossy PG for admin down ports during initialization

- cfgmgr/intfmgr.cpp
- cfgmgr/intfmgr.h
- orchagent/Makefile.am
- orchagent/bulker.h
- orchagent/crmorch.cpp
- orchagent/crmorch.h
- orchagent/intfsorch.cpp
- orchagent/intfsorch.h
- orchagent/label.h
- orchagent/mplsrouteorch.cpp
- orchagent/neighorch.cpp
- orchagent/neighorch.h
- orchagent/nexthopkey.h
- orchagent/orchdaemon.cpp
- orchagent/port.h
- orchagent/routeorch.cpp
- orchagent/routeorch.h
- orchagent/saihelper.cpp
- tests/mock_tests/Makefile.am
- tests/mock_tests/aclorch_ut.cpp
- tests/test_mpls.py
What I did
SONiC swss support for MPLS:
1) RouteOrch support for SAI MPLS inseg
2) NeighOrch support for MPLS NHs.
3) CrmOrch support for MPLS inseg and NH accounting.
4) New sonic-swss/tests/test_mpls.py for verification.
Why I did it
SONiC swss support for MPLS
Unit-tests in sonic-swss/tests/test_mpls.py and sonic-utilities/tests
System tests in sonic-mgmt
Details if related
Refer to HLD: Azure/SONiC#706
> sonic-swss changes for MPLS

- cfgmgr/buffer_check_headroom_mellanox.lua
- cfgmgr/buffer_headroom_mellanox.lua
- cfgmgr/buffer_pool_mellanox.lua
- cfgmgr/buffermgrdyn.cpp
- cfgmgr/buffermgrdyn.h
- tests/test_buffer_dynamic.py
**What I did**
Bug fixes for buffer pool calculation and headroom checking on Mellanox platforms.
- Test the number of lanes instead of the speed when determining whether special handling is required for a port.
For speeds other than 400G, eg 100G, it's possible that some 100G ports have 8 lanes and others have 4 lanes,
which means they can not share the same buffer profile.
A suffix `_8lane` is introduced to indicate it, like `pg_lossless_100000_5m_8lane_profile`
- Take the private headroom into account when calculating the buffer pool size
- Take deviation into account when checking the headroom against the per-port limit to avoid the inaccurate result in a rare case
- Use hashtable to record the reference count of a profile in lug plugin …
> [Dynamic Buffer Calc][Mellanox] Bug fixes and enhancements for the lua plugins for buffer pool calculation and headroom checking

- orchagent/bufferorch.cpp
**What I did**
Don't call SAI API for BUFFER_POOL/PROFILE handling in case the op is DEL and the SAI OID is NULL in order to avoid orchagent from exiting.
We need it only in 202106 or above. In 202012 the orchagent won't exit in such case.
Handle rare cases which cause SAI error eventually makes orchagent to exit.
Manually test.
There is an optimization on orch: the SET event will be replaced by a DEL event if it is still pending in m_toSync when the DEL event is coming.
This is reasonable but can cause the SAI OID to be NULL in rare case:
- The application creates an object and then destroy it after a very short period
- The create notification is eliminated and replaced by destroying the notification
- The SAI object hasn't …
> [BufferOrch] Don't call SAI API for BUFFER_POOL/PROFILE handling in case the op is DEL and the SAI OID is NULL

- orchagent/flexcounterorch.cpp
- orchagent/flexcounterorch.h
- orchagent/orchdaemon.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/mock_tests/mock_orchagent_main.h
- tests/mock_tests/portsorch_ut.cpp
- tests/test_flex_counters.py
- tests/test_pg_drop_counter.py
**What I did**
Update flex counters DB with counters stats only when counters are enabled.
As long as the polling counters are not enabled, flex counters information will stored internally on PortsOrch.
Creating flex counters objects on the DB will trigger 'SYNCD' to access the HW for query statistics capabilities.
This HW access takes time and will be better to finish boot before doing this (mainly for fast-reboot but good to have in general).
The flex counters are not crucial at boot time, we can delay it to the end of the boot process.
Reboot a switch and observer the flex counters DB populated after counters are enabled.
> [flex-counters] [202012] Delay flex counters stats init for faster boot time

- cfgmgr/buffermgrd.cpp
- cfgmgr/buffermgrdyn.cpp
- cfgmgr/buffermgrdyn.h
- tests/test_buffer_dynamic.py
**What I did**
Update the speed used for headroom calculating according to port auto-negotiation change.
The speed taken into the calculation is now called `effective speed` in the code.
Run regression test and vs test.
One logic was to take the configured speed into account when calculating the headroom because it's the maximum possible speed at which a port runs.
As port auto-negotiation supported, this logic needs to be updated accordingly:
The maximum possible speed is no longer the configured one with auto-negotiation enabled.
So the speed taken into account should be:
- If port auto-negotiation is enabled:
maximum speed in adv_speeds if it is configured
maximum speed in …
> [Dynamic Buffer Calc] Support dynamic buffer calculation on top of port auto negotiation

- orchagent/neighorch.cpp
- orchagent/neighorch.h
**What I did**
For the remote neighbors in the VOQ systems when there is change in the
encap index (due to syncd restart), the previously programmed remote
neighs should be re-written with the new changed encap index. The
current voq system neigh handling api in neighorch only checks for the
change of mac address. Because of this the change in the encap index is
ignored. This causes mismatch of encap index in the neighbor records in
owner asic and the remote asics after syncd restart situations like
config reload or failure recovery. This results in packet forwarding
failures for the packets forwarded across fabric and egressing in
different asics than ingress asics. The encap index that was previously
allocated by SAI and synced to the CHASSIS_APP_DB may change for the
same neighbor when …
> [neighorch] VOQ encap index change handling

- orchagent/neighorch.cpp
**What I did**
This patch is to make VOQ chassis with port type inband interface work
in VS platform based setups such as setups with KVMs
Currently with port type inband interface, kernel static neighbors for voq
neighbors are programmed with mac = local asic's mac. Because of this,
packets generated by host destined to voq neighbors will have both src and
dst mac same. This is fine for forwarding by hardware where recycle port is
used for inband interface. However, for VS platforms, since src mac = dst
mac, host's ip stack drops the packet. To fix this problem, for VS
platforms, if the inband interface is port type, staic neibhbors for voq
neighbors are programmed with mac = neighbors's owner asic's mac. With
this change, since src mac and dst mac are different and since we also
program …
> Mac for kernel static neigh programmed for voq neighs in VOQ chassis with port type inband interface in VS platforms

- orchagent/aclorch.cpp
- tests/test_mirror.py
Retry logic was introduced to ACL rule mirror action in https://github.com/Azure/sonic-swss/pull/1486
This assumes that mirror session may not be ready when the associated ACL rule is processed.
If mirror entry exists (CONFIG_DB processed) but mirror session is not created in sai/asic, `AclRuleMirror::create()` is called twice, one at processing CONFIG_DB ACL rule config, and one at later mirror session activation notify (i.e., mirror session creation event in sai/asic). In this case, mirror session reference count is incremented twice for the same rule, and mirror session removal will fail due to non-zero ref count even if ACL rule is removed.
**What I did**
This PR fixes the above scenario. 
Fix is validated by developing vs test, which is …
> [acl mirror action] Mirror session ref count fix at acl rule attachment

- .gitignore
- orchagent/countercheckorch.cpp
- orchagent/main.cpp
- orchagent/mirrororch.cpp
- orchagent/natorch.cpp
- orchagent/pfcactionhandler.cpp
**What I did**
Update gitignore, remove unused variables, fix commandline help message, remove explicit move
Keep code clean
Local run
> Cleanup code

- orchagent/portsorch.cpp
- orchagent/portsorch.h
**What I did**
Revert the special handling for recirc port.
Recirc port support has been added to recent versions of DNX SAI. The earlier special handling for recirc port is not required anymore and thus reverted.
I tested the PR with SAI 5.0.0.5 and verified inband port came up and functioned correctly.
> Revert recirc port change

- orchagent/portsorch.cpp
- portsyncd/portsyncd.cpp
**What I did**
Before puting port related configuration to APPL_DB, check autoneg mode first. If autoneg mode is enabled, "speed" and "interface_type" will not be put into APPL_DB; if autoneg mode is disabled, "adv_speeds" and "adv_interface_types" will not be put into APPL_DB; else all configuration will be put to APPL_DB for backward compatible.
The field "speed" in PORT_TABLE of APPL_DB has two meanings:
1. The configured port speed
2. The actual port speed
This is all right when SONiC has no auto negotiation feature because the actual speed must equal to the configured speed or the operational status is down. However, with port auto negotiation feature, if autoneg mode is enabled, the actual speed could be a value of adv_speeds which might not equal to field "speed". …
> [orchagent] Put port configuration to APPL_DB according to autoneg mode

- orchagent/orch.cpp
**What I did**
Ignore ALREADY_EXIST error in FDB creation.
Fix: https://github.com/Azure/sonic-buildimage/issues/7798
In FDB creation, there are scenarios where the hardware learns an FDB entry before orchagent. In such cases, the FDB SAI creation would report the status of SAI_STATUS_ITEM_ALREADY_EXISTS, and orchagent should ignore the error and treat it as entry was explicitly created.
> Ignore ALREADY_EXIST error in FDB creation

- orchagent/macsecorch.cpp
**What I did**
Rename XPN attributes from `SAI_MACSEC_SA_ATTR_MINIMUM_XPN` and `SAI_MACSEC_SA_ATTR_XPN` to `SAI_MACSEC_SA_ATTR_CURRENT_XPN`
Due to https://github.com/opencomputeproject/SAI/pull/1169 that refactors the attributes about XPN,  a new attributes `SAI_MACSEC_SA_ATTR_CURRENT_XPN` for both ingress and egress was introduced for reading the Packet number. So move the original attributes to the new one.
> Update MACsec SA PN counter to support SAI API 1.8

- portsyncd/portsyncd.cpp
**What I did**
Remove Portsyncd error exit if there are no ports in config DB.
Allow system with no ports in config db run without errors
This is needed for modular system which should boot properly without line cards.
Remove ports from config DB and verify proper init flow. 
> [swss]: Allow portsyncd to run on system without ports

- configure.ac
**What I did**
Add the option of passing custmol built libnl path to configure script
MPLS feature in sonic-buildimage requires a libnl patch to be applied before building libnl. Since this build is not installed in usual locations (/usr/lib/..) LGTM analysis fails. This change gives the option of passing libnl library location to 'configure' script and generate libraries to be linked.
In case the options are not passed, the configure script defaults to earlier behavior where it checks for LIBNL in usual locations
```
root@samaddik-vm-01:/var/sonic/src/sonic-swss# ./configure --prefix=/usr --with-extra-inc=/lgtm/usr/include --with-extra-lib=/lgtm/lib/x86_64-linux-gnu    --with-extra-usr-lib=/lgtm/usr/lib/x86_64-linux-gnu …
```
> [configure.ac] Add the option of passing libnl path to configure script

- orchagent/portsorch.cpp
- tests/mock_tests/portsorch_ut.cpp
In scenario that is executed in sonic-mgmt in test_po_update.py a portchannel member is deleted from one portchannel and added to another portchannel.
It is possible that requests from teamsynd will arrive in different order
This reordering happens because teamsyncd has single event handler/selectable TeamSync::TeamPortSync::onChange() per team device so when two of them are ready it is swss::Select implementation detail in which order they are going to be returned.
This is a fundamental issue of Producer/ConsumerStateTable, thus orchagent must be aware of this and treat it as normal situation and figure out the right order and not crash or print an errors.
Original PR https://github.com/Azure/sonic-swss/pull/1797
Signed-off-by: Stepan Blyschak stepanb@nvidia.com
**What I did**
Check if …
> [202012][portsorch] fix errors when moving port from one lag to another.

- cfgmgr/buffermgr.cpp
- cfgmgr/buffermgr.h
- tests/test_buffer_traditional.py
By default, lossless profiles are attached to PGs 3, 4 of all ports which results in a lot of buffer wastage when most of those ports are unused (not associated with a DEVICE_NEIGHBOR). In TD2, ingress pool size comprises of the reserved space as well.  Hence making use of  a special cable length of '0m' to identify unused ports and skip reserving space for those ports
**What I did**
* In buffermgr, if port with cable len '0m' is identified, return immediately without creating pg lossless profile or attaching profile to the lossless pgs of that port
* Listen to 'admin_status' update as well from the PORT table and update port-speed mapping. This is to handle add-rack scenario where a port is added later
- The port starts of with cable length 0m
- Configlet to add a port is applied. The …
> Td2: Reclaim buffer from unused ports

- gearsyncd/gearboxparser.cpp
- lib/gearboxutils.cpp
- lib/gearboxutils.h
- orchagent/saihelper.cpp
**What I did**
SAI_REDIS_SWITCH_ATTR_CONTEXT was set according to the phy_id in gearbox_config.json. This change will set it based on the
context_id provided in that json file. 
The reason behind it is to support the case of multiple phys sharing the same context, or simply, using one syncd process and context to support multiple phys. 
This change is depended by https://github.com/Azure/sonic-buildimage/pull/8146
An example of gearbox_config.json after the change, is as below
"phys": [
{
"phy_id": 1,
"name": "phy1",
"address": "1",
"lib_name": "",
"firmware_path": "/usr/share/phy_fw.bin",
"config_file": "/usr/share/sonic/hwsku/phy1_config_1.json",
"sai_init_config_file": "",
"phy_access": "mdio", …
> [gearbox] Set context for phys based on context_id

- cfgmgr/buffermgrdyn.cpp
**What I did**
Bugfix: Don't create lossless buffer profiles for active ports without speed configured
Root cause:
- In `handlePortTableUpdate`, `refreshPgsFromPort` is called if admin status is updated even if the speed is not configured.
This is reasonable because the port can be configured as headroom override and the profile should be applied in that case.
- However, as a side-effect, the port's state is set to `PORT_READY` in `refreshPgsForPort` regardless of whether the speed is configured, which is not correct.
This should be avoided and `PORT_READY` should be set by the caller if necessary
Fix:
- Don't set the port's state to `PORT_READY` in `refreshPgsForPort` and check the port's state before calling it.
- Explicitly set port's state to `PORT_READY` in `handlePortStateTable`. …
> [Dynamic Buffer Calc] Bug fix: Don't create lossless buffer profile for active ports without speed configured

- cfgmgr/buffermgrdyn.cpp
**What I did**
Bugfix: Don't create lossless buffer profiles for active ports without speed configured
This is to backport PR #1822 to 202012.
Root cause:
- In `handlePortTableUpdate`, `refreshPgsFromPort` is called if admin status is updated even if the speed is not configured.
This is reasonable because the port can be configured as headroom override and the profile should be applied in that case.
- However, as a side-effect, the port's state is set to `PORT_READY` in `refreshPgsForPort` regardless of whether the speed is configured, which is not correct.
This is should be avoided and `PORT_READY` should be set by the caller if necessary
Fix:
- Don't set the port's state to `PORT_READY` in `refreshPgsForPort` and check the port's state before calling it.
Note:
- The change is covered by …
> [Dynamic Buffer Calc][202012]Bug fix: Don't create lossless buffer profile for active ports without speed configured

- cfgmgr/vlanmgr.cpp
- orchagent/muxorch.cpp
**What I did**
1. Set bridge mac same as Vlan mac
2. Format state_db entries to have six digit precision for microseconds
Avoid flooding of self destined packets and consistent formating for MUX METRICS
1. Bridge Mac
_Prior to fix:_
```
admin@sonic$ ip link show Vlan1000
53: Vlan1000@Bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9100 qdisc noqueue state UP 
link/ether **00:aa:bb:cc:dd:ee** brd ff:ff:ff:ff:ff:ff
admin@sonic$ ip link show Bridge
51: Bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9100 qdisc noqueue state UP 
link/ether **94:8e:d3:04:bf:d8** brd ff:ff:ff:ff:ff:ff
```
_After fix:_
```
admin@sonic$ ip link show Vlan1000
97: Vlan1000@Bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9100 qdisc noqueue state UP 
link/ether **00:00:11:22:33:44** …
```
> Bridge mac setting and fix for mux statedb time format

- orchagent/crmorch.cpp
**What I did**
Added more appropriate log message for CRM queries of MPLS_INSEG and MPLS_NEXTHOP resources when platform does not support these resource types.
Mellanox has raised the issue officially here: https://github.com/Azure/sonic-buildimage/issues/8036
System test with VS SAI modified to return NOT_SUPPORTED.
N/A
> [crm] Fix for Issue Azure/sonic-buildimage#8036

- orchagent/neighorch.cpp
**What I did**
VOQ nexthop for remote neighbors should be created on local inband port only for the kernel purpose. SAI should use actual RIF of the remote system port interface. https://github.com/Azure/sonic-swss/pull/1686 seems to be break this condition and this change address it. 
VOQ nexthop for remote neighbors should be created on local inband port only for the kernel purpose. SAI should use actual RIF of the remote system port interface. https://github.com/Azure/sonic-swss/pull/1686 seems to be break this condition and this change address it. 
Test on VOQ chassis. 
> [SWSS] VOQ Nexthop for remote VOQ LC should be created on inband OIF.

- orchagent/portsorch.cpp
- tests/test_port_dpb_lag.py
**What I did**
Added code to increment the port reference counter on the creation of a lag membership that involves that port. Also added code to decrement the counter on the removal of that lag membership as well. This prevents the port from being removed before the lag membership is. 
Fixes https://github.com/Azure/sonic-buildimage/issues/7782
In some cases (particularly in the dynamic port breakout flow) if a LAG membership was removed at the same time a port was removed the host interface would be deleted before the membership removal was processed. This would result in orchagent attempting to strip the VLAN tag from a non-existent host interface causing a crash. 
Tested previously broken flow on a MSN2700
```
root@r-panther-23:/home/admin# …
```
> [orchagent][ports] Add port reference increment / decrement to lag member add / remove flows

- cfgmgr/Makefile.am
**What I did**
Added -lzmq flag to cfgmgr
New changes in sairedis repo will move zmq dependency to libsaimeta
Local build
> [cfgmgr] Update Makefile.am to consume lib zmq

- orchagent/fdborch.cpp
**What I did**
FIx the warmboot issue PR##8367, caused by the changes made as part of the PR#1331
Fixes https://github.com/Azure/sonic-buildimage/issues/8367
During the WB when the MAC addresses are added via refillToSync(&m_fdbStateTable) , the attribute SAI_FDB_ENTRY_ATTR_ALLOW_MAC_MOVE is set wrongly for dynamic MAC as well.
Fix is to set SAI_FDB_ENTRY_ATTR_ALLOW_MAC_MOVE  only for the case of VXLAN or MCLAG  for fdb_type dyamic.
> Fix warmboot issue PR##8367

- tests/test_buffer_traditional.py
- tests/test_speed.py
**What I did**
Skip flaky tests for unblocking PRs, this is under investigation.
> [VS Test] Skip flaky tests

- cfgmgr/Makefile.am
- orchagent/aclorch.cpp
- orchagent/bufferorch.cpp
- orchagent/copporch.cpp
- orchagent/crmorch.cpp
- orchagent/dtelorch.cpp
- orchagent/fdborch.cpp
- orchagent/fgnhgorch.cpp
- orchagent/intfsorch.cpp
- orchagent/mirrororch.cpp
- orchagent/natorch.cpp
- orchagent/neighorch.cpp
- orchagent/orch.cpp
- orchagent/orch.h
- orchagent/policerorch.cpp
- orchagent/portsorch.cpp
- orchagent/qosorch.cpp
- orchagent/routeorch.cpp
- orchagent/sfloworch.cpp
- orchagent/switchorch.cpp
- orchagent/tunneldecaporch.cpp
- orchagent/vrforch.cpp
**What I did**
Backport SAI failure handling related commits into the 202012 branch. The following is a list of backported commits:
```
941875a Deactivate mirror session only when session status is true in updateLagMember (#1666)
be12482 Ignore ALREADY_EXIST error in FDB creation (#1815)
c9c1aa2 Add failure handling for SAI get operations (#1768)
47b4276 [BufferOrch] Don't call SAI API for BUFFER_POOL/PROFILE handling in case the op is DEL and the SAI OID is NULL (#1786)
db9238f Add failure notification for orchagent (#1665)
fc8e43f [synchronous mode] Add failure notification for SAI failures in synchronous mode (#1596)
```
202012 image needs to include failure handling mechanism for enough notification in the presence of SAI failures.
**Details if …
> [202012] Backport SAI failure handling to 202012 branch

- orchagent/port_rates.lua
- orchagent/rif_rates.lua
Signed-off-by: noaOrMlnx noaor@nvidia.com
**What I did**
Change rif_rates.lua and port_rates.lua scripts to calculate rates properly - rates_table_names table should be updated after each iteration and not only once.
Fix issue - https://github.com/Azure/sonic-buildimage/issues/8392
Checked that when sending traffic, the output of 'show interfaces counters rif' and the rates appear in RATES table, counter db are close.  
```
admin@sonic:~$ show interfaces counters rif -p 5
The rates are calculated within 5 seconds period
IFACE    RX_OK     RX_BPS    RX_PPS    RX_ERR    TX_OK    TX_BPS    TX_PPS    TX_ERR
---------  -------  ---------  --------  --------  -------  --------  --------  --------
Ethernet0        5  83.90 B/s    1.00/s         1        0 …
```
> [RIF] Change rif_rates.lua script to calculate rates correctly

- orchagent/aclorch.cpp
- tests/test_acl.py
Signed-off-by: bingwang <wang.bing@microsoft.com>
**What I did**
This PR updates ```aclorch``` to match ```TCP``` protocol number while matching ```TCP_FLAGS```.
We found that ACL rules that only matches ```TCP_FLAGS``` will also capture some UDP packets if we don't explicitly require to match TCP protocol. The issue is only detected on TD3 platform for IPv6 for now.
For example, follow ACL rule will catch UDP packets
```
...
"19": {
"actions": {
"config": {
"forwarding-action": "DROP"
}
},
"config": {
"sequence-id": 19
},
"transport": {
"config": {
"tcp-flags": ["TCP_RST", "TCP_URG"]
}
}
},
...
``` 
To address the issue, this PR updates ```aclorch```. When an ACL rule is to match ```TCP_FLAGS```, we will also try to match ```TCP``` protocol number if it's not set …
> [ACL] Match TCP protocol while matching TCP_FLAG

- cfgmgr/macsecmgr.cpp
- cfgmgr/macsecmgr.h
- orchagent/macsecorch.cpp
- tests/test_macsec.py
What I did
Updated macsecmgrd to program XPN information when starting wpa-supplicant.
Why I did it
MACsec XPN support.
System tests on Juniper platform which supports MACsec XPN.
Details if related
N/A
> [macsecmgrd] MACsec XPN changes

- orchagent/bufferorch.cpp
**What I did**
Currently, SAI_BUFFER_POOL_STAT_WATERMARK_BYTES and SAI_BUFFER_POOL_STAT_XOFF_ROOM_WATERMARK_BYTES are queried for buffer pools.
However, the latter is not supported on all pools and all platforms, which will result in sairedis complaint like this:
```
Jun 17 23:31:34.949613 sonic ERR syncd#SDK: :- updateSupportedBufferPoolCounters: BUFFER_POOL_WATERMARK_STAT_COUNTER: counter SAI_BUFFER_POOL_STAT_XOFF_ROOM_WATERMARK_BYTES is not supported on buffer pool oid:0x1000000018, rv: SAI_STATUS_NOT_IMPLEMENTED
Jun 17 23:31:34.951915 sonic ERR syncd#SDK: :- updateSupportedBufferPoolCounters: BUFFER_POOL_WATERMARK_STAT_COUNTER: counter SAI_BUFFER_POOL_STAT_XOFF_ROOM_WATERMARK_BYTES is not supported on buffer pool oid:0x1200000018, rv: SAI_STATUS_NOT_IMPLEMENTED
Jun 17 23:31:34.954177 …
```
> [buffer orch] Bugfix: Don't query counter SAI_BUFFER_POOL_STAT_XOFF_ROOM_WATERMARK_BYTES on a pool where it is not supported

- orchagent/Makefile.am
- orchagent/aclorch.cpp
- orchagent/aclorch.h
- orchagent/acltable.h
- orchagent/orchdaemon.cpp
- orchagent/orchdaemon.h
- orchagent/pbh/pbhcnt.cpp
- orchagent/pbh/pbhcnt.h
- orchagent/pbh/pbhmgr.cpp
- orchagent/pbh/pbhmgr.h
- orchagent/pbh/pbhrule.cpp
- orchagent/pbh/pbhrule.h
- orchagent/pbhorch.cpp
- orchagent/pbhorch.h
- orchagent/saihelper.cpp
- tests/conftest.py
- tests/dvslib/dvs_acl.py
- tests/dvslib/dvs_pbh.py
- tests/mock_tests/Makefile.am
- tests/mock_tests/aclorch_ut.cpp
- tests/test_pbh.py
**PBH architecture:**
1. PBH OA
2. PBH Helper
3. PBH Container
**PBH business logic:**
1. PBH OA: receive the updates from Redis (Config DB)
2. PBH Helper/PBH Container: parse data/store in internal cache:
- If no errors observed - store task by table key in internal cache
- If task with the same key already exists - postpone processing and proceed with the next one
- Set/Remove tasks are stored in separate maps
- For each type of Config DB entity (table, rule, hash and hash field) a dedicated PBH container is used
3. PBH OA: deploy tasks:
- Use Remove & Setup policy
- Process create/update (SET) tasks in correct order
- Do the same for delete (REMOVE) tasks
* Done as part of PBH development
* Added PBH OA
1. Add PBH configuration
2. Run DPB
* N/A
```
.---.        .-----------
/     \  __ …
```
> [pbh]: Add PBH OA

- orchagent/aclorch.cpp
Signed-off-by: bingwang <wang.bing@microsoft.com>
**What I did**
This PR is to fix https://github.com/Azure/sonic-buildimage/issues/8585
Updating ```ACL_TABLE:EVERFLOW``` and ```ACL_TABLE:EVERFLOWV6``` separately will cause the EVERFLOW table being recreated rather than being updated. 
The root cause for this issue is a minor logic error in https://github.com/Azure/sonic-swss/blob/12f0ee7888be5efac5b4213e92d77a030832c40b/orchagent/aclorch.cpp#L3164-L3170
The MIRROR and MIRRORV6 should be treated as the same type on Broadcom platform.
Verified by replacing ```orchagent``` with the updated one, and update ```ACL_TABLE|EVERFLOWV6``` table by ```redis-cli```, and then check syslog.
Before this update, the ```ACL_TABLE|EVERFLOW``` table will be removed …
> [acl]Update acl type check logic

- orchagent/aclorch.cpp
- tests/test_mirror.py
Signed-off-by: bingwang <bingwang@microsoft.com>
**What I did**
This PR is a cherry-pick of #1761 from master branch to 201911 branch.
I have to create another PR to pick up the code since it's not a cleanup cherry-pick. Conflicts exist in UT code.
This PR will fix #1891 as well.
Please see #1761.
```
sonic-swss/tests$ sudo pytest test_mirror.py -v
===================================================================================================================== test session starts ======================================================================================================================
platform linux2 -- Python 2.7.15+, pytest-3.3.0, py-1.10.0, pluggy-0.6.0 -- /usr/bin/python2.7
rootdir: …
```
> [201911][Cherry-pick] [acl mirror action] Mirror session ref count fix at acl rule attachment

- orchagent/aclorch.cpp
- tests/test_mirror.py
**What I did**
This PR is a cherry-pick of #1761 from master branch to ```201811``` branch.
I have to create another PR to pick up the code since it's not a cleanup cherry-pick. Some UT code issues wrere fixed as well.
This PR will fix #1891
Please see #1761 
Verifyed by UT
```
pytest test_mirror.py -v                                   
===================================================================================================================== test session starts ======================================================================================================================
platform linux2 -- Python 2.7.15+, pytest-3.3.0, py-1.10.0, pluggy-0.6.0 -- /usr/bin/python2.7
rootdir: /home/bingwang/workspace/sonic-swss/tests, …
```
> [201811][Cherry-pick] [acl mirror action] Mirror session ref count fix at acl rule attachment

- orchagent/portsorch.cpp
- tests/mock_tests/mock_hiredis.cpp
- tests/mock_tests/portsorch_ut.cpp
**What I did**
If port operational status is up and port operational speed is 0, don't save it to APPL_DB
Avoid put speed 0 to APPL_DB.
Port operational status is up, but operational speed is 0. It could be a valid case because
port UP event is an aync event, the valid flow could be:
1. port UP event comes
2. SONiC gets the UP event and starts to process the event
3. port goes down due to any reason
4. SONiC reads the oper speed, and gets a 0 because oper_state is down.
And it could also be a bug. So, we log a warning here.
Run sonic-mgmt regression test cases
> [portsorch] Add an extra check before setting oper speed to APPL_DB

- orchagent/flexcounterorch.cpp
**What I did**
Add 'consumer.m_toSync.erase(it++)' before 'continue' statement on while loop.
Running fast-reboot with a delay indicator will result in an infinite loop, following PR: https://github.com/Azure/sonic-swss/pull/1877
Run fast-reboot with this change.
> [Flex-counters] Fix the delay of flex counters flow to prevent infinite loop

- orchagent/muxorch.cpp
**What I did**
Orchagent sometimes took >50ms to finish the state change operations. This change is to update notification to xcvrd (via APPDB) after execution is complete.  This enables xcvrd to simulate the direction change *after* orchagent has completed the state transition. 
Reduce packet drop during state transition. 
> [MuxOrch] Mux state order change

- orchagent/fgnhgorch.cpp
- orchagent/fgnhgorch.h
- orchagent/routeorch.cpp
- tests/test_fgnhg.py
**What I did**
Added ability to set the FG route's next-hop as the RIF, the packets will trap to the kernel and be neighbor resolved via the kernel. Further, added the ability to set the next-hop to a fine grained ECMP next-hop after the 1st neighbor resolution occurs.
To enable packet flow when no FG ECMP neighbors are resolved, and prevent traffic blackhole in that scenario.
SWSS unit test, and packet test in PR: https://github.com/Azure/sonic-mgmt/pull/4225
> [fgnhgorch] Enable packet flow when no FG ECMP neighbors are resolved

- orchagent/pfc_detect_mellanox.lua
- orchagent/pfc_restore.lua
**What I did**
Converted polling interval from milliseconds to microseconds in PFCWD LUA scripts.
Same as PR https://github.com/Azure/sonic-swss/pull/1908 but created directly against ```202012``` release branch
PFCWD storm detection and restoration LUA scripts require values in microseconds.
Due to recent changes polling interval is now passed in milliseconds by "FlexCounter".
* Azure/sonic-sairedis#878
So need to convert values to microseconds (as it was before) in order to make PFCWD working,
Ran PFCWD tests from sonic-mgmt.
N/A
> [202012][pfcwd] Convert polling interval from ms to us in LUA scripts

- orchagent/pfc_detect_mellanox.lua
- orchagent/pfc_restore.lua
**What I did**
Converted polling interval from milliseconds to microseconds in PFCWD LUA scripts.
PFCWD storm detection and restoration LUA scripts require values in microseconds.
Due to recent changes polling interval is now passed in milliseconds by "FlexCounter".
* Azure/sonic-sairedis#878
So need to convert values to microseconds (as it was before) in order to make PFCWD working,
Ran PFCWD tests from sonic-mgmt.
N/A
> [pfcwd] Convert polling interval from ms to us in LUA scripts

- tlm_teamd/main.cpp
- tlm_teamd/teamdctl_mgr.cpp
- tlm_teamd/teamdctl_mgr.h
**Why I did**
Fix https://github.com/Azure/sonic-buildimage/issues/6632
There has been cases when the get_dumps API in tlm_teamd process is not able to get the right data and logs an error message. 
The issue occurs very rarely and it is due to the race condition between teammgrd/teamsyncd/tlm_teamd when a Portchannel is removed. In the teamd telemetry module there are two places where the get_dumps() is called.
1. When the portchannel object is add/removed. [https://github.com/Azure/sonic-swss/blob/master/tlm_teamd/main.cpp#L101]
2. On timeout of 1 sec. [https://github.com/Azure/sonic-swss/blob/master/tlm_teamd/main.cpp#L108]
In case of timeout call for get_dumps(), there could be an inconsistent state where the portchannel/teamd process is getting removed by teammgrd but the STATE table …
> [tlm teamd] Add retry mechanism before logging the ERR in get_dumps.

- orchagent/pfc_detect_barefoot.lua
- orchagent/pfc_detect_broadcom.lua
- orchagent/pfc_detect_innovium.lua
- orchagent/pfc_detect_nephos.lua
Fixes Azure/sonic-buildimage#8773
Pfcwd regressions were observed due to the changes in the PR Azure/sonic-sairedis#878. Hence aligning the polling interval in lua script to use microseconds
Ran pfcwd tests that were failing prior to this change and they passed
> [pfcwd] Fix the polling interval time granularity

- cfgmgr/teammgr.cpp
- cfgmgr/teammgr.h
- cfgmgr/teammgrd.cpp
Signed-off-by: Nazarii Hnydyn nazariig@nvidia.com
This PR is intended to fix LAGs cleanup degradation caused by python2.7 -> python3 migration.
The approach is to replace `teamd -k -t` call with the raw `SIGTERM` and add PID alive check.
This will make sure the `teammgrd` is stopped only after all managed processes are being killed.
resolves: https://github.com/Azure/sonic-buildimage/issues/8071
**What I did**
* Replaced `teamd -k -t` call with raw `SIGTERM`
* Added PID alive check
* To fix LAGs cleanup timeout issue caused by python2.7 -> python3 upgrade
1. Configure 64 LAG RIFs
2. Reload config
* N/A
> [202012][teammgrd]: Improve LAGs cleanup on shutdown

- orchagent/orch.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
**What I did**
When setting invalid interface types to port, do not call handleSaiSetStatus to avoid orchagent exit.
Currently, when setting invalid interface types to port, orchagent would crash, this is not necessary since user still has chance to correct it. Error log see:
```
Jun  1 03:35:22.172518 r-leopard-41 ERR swss#orchagent: :- set: set status: SAI_STATUS_INVALID_ATTR_VALUE_0
Jun  1 03:35:22.172518 r-leopard-41 ERR swss#orchagent: :- handleSaiSetStatus: Encountered failure in set operation, exiting orchagent, SAI API: SAI_API_PORT, status: SAI_STATUS_INVALID_ATTR_VALUE_0
```
Manual test
> [portsorch] Avoid orchagent crash when set invalid interface types to port

- tests/test_port_dpb_lag.py
**What I did**
Fixed the failed DPB LAG tests
The DPB LAG test was not passing. The test case was meant to cover the race condition scenario where on port removal, port delete arrives at orchagent before lag removal(The dependencies would be removed by breakout command automatically). So port delete should wait until dependencies are removed.
To mimic this, app DB LAG member table should be created first and removed after dpb command. The test was earlier mimicing with cfg DB LAG table (which is not the actual use case). Moreover mimicking config_Db lag table has a race condition where removeLAGMember is called by teamd during link down and thus the flow completes and when actual remove lag member from config_db is called, teamd crashes. This results in further lag remove …
> Fix failing DPB LAG tests

- tests/test_route.py
**What I did**
Add sleep in route perf test to ensure the test starts when route table is stable.
This PR aims to fix the PR checker failure due to route perf test failures.
> Ensure route perf test starts when route table is stable

- cfgmgr/Makefile.am
- lgtm.yml
- orchagent/main.cpp
> [lgtm] Fix LGTM build on 202012 branch

- orchagent/routeorch.cpp
- orchagent/routeorch.h
- tests/test_mux.py
**What I did**
Created a map to store single nexthop routes. This is for faster retrieval when you've to fetch the routes for a particular nexthop. No changes to ECMP route handling. 
This is an optimization and the existing [VS test ](https://github.com/Azure/sonic-swss/blob/master/tests/test_mux.py#L276) covers the code for add flow. Set flow is covered with new test case.  
Faster retrieval of route when a particular nexthop state changes. This avoid looping through all the routes to find a matching nexthop. 
Tested on DUT:
```
Sep 21 18:05:46.996655 NOTICE swss#orchagent: :- setState: [Ethernet4] Set MUX state from active to standby
Sep 21 18:05:46.996748 INFO swss#orchagent: :- stateStandby: Set state to Standby for Ethernet4
Sep 21 …
```
> Cache routes for single nexthop for faster retrieval

- tests/test_route.py
**What I did**
Reduce route count for route perf test.
Route perf test sometimes experiences timeout failure. I measured the route creation/removal time locally and it is roughly the same as it was a year ago. As there is no performance degradation, the test failures should be false alarms caused by the test server speed. Reducing the route count to avoid blocking PR tests due to false alarms.
> Reduce route count for route perf test

- portsyncd/portsyncd.cpp
Signed-off-by: tomeri <tomeri@nvidia.com>
**What I did**
- continue the execution of handlePortConfigFromConfigDB when no ports on config db -> continue and set PortConfigDone
- function handlePortConfigFromConfigDB is no longer boolean - change it to void
when there are no ports on config db the PortConfigDone on APP db wasn't set and dynamic add/remove of ports after init stage is damaged.
started with no ports configured and verified that PortConfigDone is set on APP db
> [portsyncd] when no ports on config db on init - continue and set PortConfigDone

- tests/conftest.py
- tests/test_gearbox.py
- tests/test_mirror_ipv6_combined.py
- tests/test_mirror_ipv6_separate.py
**What I did**
* Add test_gearbox
* Add DVS_ENV for module specific dvs env variables
> [gearbox] Add gearbox unit test

- orchagent/orch.cpp
- tests/test_buffer_dynamic.py
**What I did**
Reverted skipped test_buffer_dynamic as part of https://github.com/Azure/sonic-swss/pull/1754
**How I verified it** sudo pytest --dvsname=vs --forcedvs -sv --keeptb test_buffer_dynamic.py
======================================================= test session starts ========================================================
platform linux -- Python 3.6.9, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python3
rootdir: /home/ashokd/swss-vs/ashok-swss/sonic-swss/tests
collected 9 items
test_buffer_dynamic.py::TestBufferMgrDyn::test_changeSpeed remove extra link dummy PASSED
test_buffer_dynamic.py::TestBufferMgrDyn::test_changeCableLen PASSED
test_buffer_dynamic.py::TestBufferMgrDyn::test_MultipleLosslessPg PASSED …
> Reverted skipped test_buffer_dynamic test cases

- orchagent/portsorch.cpp
**What I did**
Added FEC correctable, uncorrectable and symbol errors to the list of statistics collected for a port by the flex counter.
To added CLI support to show fec related counters. Currently, Broadcom has enabled fec counters in their SDK.
Ensured the FEC counters are present in counter table:-
```
root@str-s6000-acs-01:~# redis-cli -n 2 hgetall "COUNTERS:oid:0x1000000000002" | grep FEC
SAI_PORT_STAT_IF_IN_FEC_CORRECTABLE_FRAMES
SAI_PORT_STAT_IF_IN_FEC_NOT_CORRECTABLE_FRAMES
root@str-s6000-acs-01:~#
```
> [FEC] Enable FEC statistics collection for Ethernet ports

- cfgmgr/teammgr.cpp
Warm/Fast reboot requires `USR1`/`USR2` signals to be sent to all LAG pids before `teamd` is stopped.
This automatically triggers graceful LAG pids shutdown and when the `teammgrd` receives `TERM` signal, there is nothing to cleanup.
**What I did**
* Fixed LAGs cleanup on Warm/Fast reboot:
```bash
Sep 28 16:51:21.650824 sonic NOTICE teamd#teammgrd: :- cleanTeamProcesses: Cleaning up LAGs during shutdown...
Sep 28 16:51:21.654356 sonic INFO teamd#/supervisord: teammgrd cat: /var/run/teamd/PortChannel0001.pid: No such file or directory
Sep 28 16:51:21.655125 sonic ERR teamd#teammgrd: :- main: Runtime error: cat "/var/run/teamd/PortChannel0001.pid" :
Sep 28 16:51:22.376959 sonic INFO teamd#supervisord 2021-09-28 16:51:22,376 INFO stopped: …
```
> [teammgrd]: Handle LAGs cleanup gracefully on Warm/Fast reboot

- tests/test_virtual_chassis.py
**What I did**
Skip flaky tests to unblock PRs
```
test_virtual_chassis.py::TestVirtualChassis::test_chassis_system_lag_id_allocator_table_full FAILED [ 88%]
test_virtual_chassis.py::TestVirtualChassis::test_chassis_system_lag_id_allocator_del_id FAILED [ 89%]
```
> [VS tests] Skip flaky virtual chassis test

- orchagent/portsorch.cpp
Depends on https://github.com/Azure/sonic-buildimage/pull/9098
**What I did**
Allow user to set none value for interface type
Say user has speed=50G, interface_type=CR2, and user wants to change it to 10G and CR. Currently, there is no CLI can support it, because:
1. If you change the interface type to CR first, SAI will get 50G and CR, SAI will report error because not supported
2. If you change the speed to 10G first, SAI will get 10G and CR2, also not supported
The only way for now is to manually change the CONFIG_DB and do a config reload, this is not user friendly.
This PR allow user to set none value to interface type. So there is a way to achieve the goal via CLI:
1. config interface type XXX none
2. config interface speed XXX 10000
3. config interface type XXX CR …
> [portsorch] Allow user to set none value for interface type

- .azure-pipelines/build-template.yml
- azure-pipelines.yml
**What I did**
I add step to clean work space.
Thus avoid random failure in azure pipeline.
There are build failures because of work space not clean.
https://dev.azure.com/mssonic/build/_build/results?buildId=48551&view=logs&j=e51ebb60-45fa-5846-0822-3aaf597a9c80&t=29c82d13-0aa4-5ac7-9d6a-e34d59819a1b
> Fix random failure in PR/CI build.

- orchagent/crmorch.cpp
**What I did**
Fix the mpls nexthop CRM attribute
MPLS v4 nexthops will share the same resource as IPv4 NHOP, there is no separate resource partition for MPLS nexthop.
Getting the following error in logs:
Oct 29 22:40:03.679316 str2-7804-lc3-1 ERR swss#orchagent: :- getResAvailableCounters: Failed to get availability for object_type 63 , rv:-5
.
.
Verified the message is not produced anymore
> [CRM][MPLS NHOP] Fix the mpls nexthop CRM attribute

- orchagent/switchorch.cpp
- orchagent/switchorch.h
- tests/test_switch.py
Signed-off-by: Andriy Yurkiv <ayurkiv@nvidia.com>
**What I did**
Added ability to configure UDP VXLAN src port range with help of new added parameters (vxlan_sport and vxlan_mask)
Сorresponding SAI attributes: SAI_SWITCH_TUNNEL_ATTR_VXLAN_UDP_SPORT and SAI_SWITCH_TUNNEL_ATTR_VXLAN_UDP_SPORT_MASK
Implemented configuration of  VXLAN src port feature according to requirements
Use appropriate VS test
`sudo pytest --dvsname=vs tests/test_switch.py::TestSwitch::test_switch_attribute -v -s`
Create json file with params.
Use swssconfig to enable feature and write config params to APP_DB : swssconfig /etc/swss/config.d/switch.json
```
switch.json:
[
{
"SWITCH_TABLE:switch": {
"vxlan_sport": "0xFFA0",
"vxlan_mask": "3"
},
"OP": "SET"
}
] …
```
> [switchorch] Implement VXLAN src port range feature 

- orchagent/muxorch.cpp
- orchagent/orchdaemon.cpp
**What I did**
1. Set default status for each mux port to `standby ` state during init.
2. Change mux orch priority to process entries before neighbor orch
Existing VS tests cover the changes.
Avoid packet duplication by installing drop ACLs during mux port initialization and oper up. 
> [Mux orch] set default as standby, change mux orch priority

- orchagent/qosorch.cpp
- tests/test_pfc.py
Signed-off-by: Alpesh S Patel <alpesh@cisco.com>
**What I did**
Added code to enable disabling PFC from the single TC that is configured on a port.
Currently if a single TC is configured on a port, it cannot be unconfigured by setting the pfc bitmask to 0.
The if (pfc_enable) check skips as pfc_enable bit pattern is 0
This code change adds ability to unconfigure PFC on a single TC that's configured on a port.
tested it on a cisco-8000 router running sonic image.
Note to committer: This also needs to go into 202012 version of the branch.
> [sonic-swss]:enable unconfiguring PFC on last TC on a port

- .azure-pipelines/build-template.yml
**What I did**
Cherry-pick PR from master:  https://github.com/Azure/sonic-swss/pull/2006
> [202012] Fix random failure in PR/CI build.

- orchagent/nexthopkey.h
- orchagent/routeorch.cpp
- orchagent/routeorch.h
- orchagent/vnetorch.cpp
- orchagent/vnetorch.h
- tests/test_vnet.py
**What I did**
Add functions to create/remove next hop groups for vnet tunnel routes.
Count the reference count of next hop groups to create and remove as needed.
Share the counter of next hop groups with routeorch.
Add vs test
To add support for overlay ECMP.
Verify ECMP groups are properly created and removed with the functions.
Verify vs test passes
> [vnetorch] Add ECMP support for vnet tunnel routes

- orchagent/nexthopgroupkey.h
- orchagent/nexthopkey.h
**What I did**
Fixed compilation of SWSS following last 2 commits
Last 2 commits don't compile together due to change in nexthop(group)key definitions
Compiled with this fix
> Fix next hop compilation

- lib/subintf.cpp
- lib/subintf.h
Moving swss-common subinterface library(PR [#529](https://github.com/Azure/sonic-swss-common/pull/529)) to swss library as per subinterface enhancement HLD update.
**What I did**
Routed subinterfae enhancements HLD [#833](https://github.com/Azure/SONiC/pull/833)
Add support for long name and short name routed subinterfaces.
Add support for long name and short name routed subinterfaces.
This swss common library provides APIS for:
- Subinterface validation checks
- Get parent interface corresponding to subinterface(short/long name)
- Get subinterface index
Routed subinterface feature was broken for physical and portchannel subinterfaces for subinterface name exceeding 15 characters due to kernel limitation of netdev name length of 15.
Routed …
> Routed subinterface enhancements

- cfgmgr/buffer_headroom_mellanox.lua
Signed-off-by: Kebo Liu <kebol@nvidia.com>
**What I did**
Peer response time was deduced from a fixed value for all the ports speed.  According to IEEE802.3 31B.3.7 at different operating speeds, the peer response time is also different, to have a more accurate headroom allocation, the way to calculate the peer response time shall be changed accordingly.   See HLD update PR https://github.com/Azure/SONiC/pull/870  for more info
To have the peer response time more accurate, calculate according to the definition in IEEE802.3 31B.3.7
Run buffer regression tests on various Mellanox platforms at various port speeds, cable lengths, with or w/o gearbox.
> [Dynamic buffer] [Mellanox] Calculate the peer response time according to the speed

- orchagent/portsorch.cpp
Signed-off-by: tomeri tomeri@nvidia.com
**What I did**
I added the removal of port buffer drop counter on the deinit port flow.
it was added to the deInitPort function.
the buffer drop counter was never removed when port was deleted.
this flex counter was create on the initPort function but it was removed when the port was deleted
removed and created a port and check the FLEX_COUNTER redis table
FLEX_COUNTER_TABLE:PORT_BUFFER_DROP_STAT table
> Remove buffer drop counter when port is deleted

- cfgmgr/macsecmgr.cpp
**What I did**
Change the prerequisite of enabling macsec to port up
The macsec-related API calls have to be executed after the API calls for gearbox port setup have been done. For that reason, before this change, enabling macsec through config_db.json after reboot cannot succeed.  To fix it by this change, the API calls for enabling macsec are executed only after the port is up.
> [macsec] Wait for port up before enabling macsec

- tests/test_crm.py
Add vs test coverage for https://github.com/Azure/sonic-swss/pull/1569
**What I did**
vs test
> [vstest/crm] Test divide by zero processing path

- cfgmgr/buffer_check_headroom_mellanox.lua
**What I did**
The egress mirror size is not taken into account when checking the accumulative headroom size, which causes the estimated accumulate headroom size to be greater than the real one and unable to be applied.
Bug fix
Run regression test.
An example to explain the logic . 
The current accumulative headroom is 90k, egress mirror headroom is 10k, the ASIC limitation of the port is 100k. 
Now a user wants to change the port configuration which will make the accumulative headroom to be increased by 10k.
Now the accumulative headroom estimated by buffer manager is 100k, which doesn’t exceed the limitation. However in the ASIC the real accumulative headroom is 110k which does.
> [Dynamic buffer][Mellanox] Fix issue: accumulative headroom can exceed limit in rare scenario

- orchagent/orchdaemon.cpp
**What I did**
Added flush for async communication pipeline, every 1 second, not only if select will timeout.
pfcwdorch has a executor timeout which triggers select every second, and somehow from some time select never timeouts (its timeout is also 1 second) and every time is returning valid object, not causing async pipeline to flush, which causes for some operations to wait for next synchronous operation to be processed.
Tested thanks to @shi-su 
> [orchagent] Flush pipeline every 1 second, not only when select will timeout

- orchagent/qosorch.cpp
- orchagent/qosorch.h
**What I did**
The QoS orchagent calls SAI APIs to get the number of child scheduler groups and then initialize them.
After that, the size of the child scheduler groups vector will be non-zero, which indicates the child scheduler groups have been initialized and prevents QoS orchagent from calling SAI get APIs again.
However, on some platforms, it may be that some of the scheduler groups don't have child groups, leaving size of child scheduler groups always being zero. It causes QoS orchagent to call the SAI get API each time the scheduler group is handled, which wastes a lot of time, especially during fast reboot.
An extra flag indicating whether the child groups have been initialized is introduced to avoid redundant calls.
**Why I did …
> Remove redundant calls to get child scheduler group during initialization

- orchagent/muxorch.cpp
- orchagent/orchdaemon.cpp
**What I did**
1. Set default status for each mux port to standby state during init.
2. Change mux orch priority to process entries before neighbor orch
Cherry-pick PR https://github.com/Azure/sonic-swss/pull/2010
> [202012][Mux orch] set default as standby, change mux orch priority

- orchagent/muxorch.cpp
- orchagent/muxorch.h
**What I did**
BInd all physical ports to drop ACL table
With current implementation, ACL table is link/bind to the very first port that triggers creation of drop ACL table followed by rule creation for the same.
For subsequent ports only new rule is created.
If a port is not linked/bind to the drop ACL table, the rule is not applied for that port.
1. Verified using sairedis log and mux logs that was added with new code that all ports are linked/bind to the drop ACL table.
2. Verified that after this fix all standby ports are dropping packets as expected.
> [muxorch] Bind all ports to drop ACL table

- orchagent/flexcounterorch.cpp
- orchagent/flexcounterorch.h
**What I did**
Don't handle buffer pool watermark during warm reboot reconciling
This is to fix the community issue Azure/sonic-sairedis#862 and Azure/sonic-buildimage#8722
Perform a warm reboot. Check whether
- buffer pool watermark handling is skipped during reconciling and handled after it.
- other watermark handling is handled during reconciling as it was before.
The warm reboot flow is like this:
1. System starts. Orchagent fetches the items from database stored before warm reboot and pushes them into `m_toSync` of all orchagents. This is done by `bake`, which can be overridden by sub orchagent.
2. All sub orchagents handle the items in `m_toSync`. At this point, any notification from redis-db is blocked.
3. Warm reboot …
> Don't handle buffer pool watermark during warm reboot reconciling

- cfgmgr/Makefile.am
- cfgmgr/buffermgrd.cpp
- cfgmgr/coppmgrd.cpp
- cfgmgr/intfmgrd.cpp
- cfgmgr/macsecmgrd.cpp
- cfgmgr/natmgrd.cpp
- cfgmgr/nbrmgrd.cpp
- cfgmgr/portmgrd.cpp
- cfgmgr/sflowmgrd.cpp
- cfgmgr/teammgrd.cpp
- cfgmgr/tunnelmgrd.cpp
- cfgmgr/vlanmgrd.cpp
- cfgmgr/vrfmgrd.cpp
- cfgmgr/vxlanmgrd.cpp
- orchagent/Makefile.am
- orchagent/main.cpp
- orchagent/orch.cpp
- orchagent/orch.h
- orchagent/response_publisher.cpp
- orchagent/response_publisher.h
- orchagent/response_publisher_interface.h
- orchagent/return_code.h
- tests/mock_tests/Makefile.am
- tests/mock_tests/database_config.json
- tests/mock_tests/fake_response_publisher.cpp
* Add response publisher.
* Add APPL STATE DB recording.
* Add response path into vrforch.
Submission containing materials of a third party:
Copyright Google LLC; Licensed under Apache 2.0
Co-authored-by: Runming Wu <runmingwu@google.com>
Co-authored-by: Yilan Ji <yilanji@google.com>
Co-authored-by: Akarsh Gupta <akarshgupta@google.com>
Co-authored-by: Jay Hu <jiarenhu@google.com>
Signed-off-by: Don Newton don@opennetworking.org
Depends on https://github.com/pins/sonic-swss-common-public/pull/2
See the Response path HLD for more details:
https://github.com/pins/SONiC/blob/master/doc/pins/appl_state_db_response_path_hld.md
> [orchagent, cfgmgr] Add response publisher and state recording

- orchagent/qosorch.cpp
- orchagent/qosorch.h
- orchagent/switchorch.cpp
- orchagent/switchorch.h
**What I did**
Added support for setting switch level DSCP to TC QoS map. cherry picked the following - 
https://github.com/Azure/sonic-swss/pull/2023
This is required to set correct DSCP -> TC QoS map for tunnels else they will point to some default QoS map (DSCP/8 = TC) which is not correct.
This needs SAI change to support this capability. Verified this to be working fine on T0 testbed with mock dual ToR topology.
> [202012] [orchagent]: Support for setting switch level DSCP to TC QoS map (cherry-pick from master)

- orchagent/orchdaemon.cpp
- orchagent/vnetorch.cpp
- orchagent/vnetorch.h
- tests/test_vnet.py
**What I did**
Add functions to create/remove next hop groups for vnet tunnel routes.
Count the reference count of next hop groups to create and remove as needed.
Share the counter of next hop groups with routeorch.
Adapt route endpoint according to the BFD state of endpoints.
To add support for overlay ECMP.
Verify ECMP groups are properly created and removed with the functions.
> [vnetorch] ECMP for vnet tunnel routes with endpoint health monitor

- orchagent/muxorch.cpp
- orchagent/routeorch.cpp
- orchagent/routeorch.h
- tests/test_route.py
**What I did**
Orchagent update of IPv4 and IPv6 default route status. If there is a valid default route, it shall be updated as `state:ok`. If there is no valid default route (with packet action drop), state db shall be updated as `state:na`
Default route state in state_db can be used as a signal for application to determine if there is a valid default route learned via BGP is available in orchagent
```
redis-cli -n 6
127.0.0.1:6379[6]> KEYS *ROUTE*
1) "ROUTE_TABLE|::/0"
2) "ROUTE_TABLE|0.0.0.0/0"
127.0.0.1:6379[6]> HGETALL "ROUTE_TABLE|0.0.0.0/0"
1) "state"
2) "na"
```
> Update default route status to state DB

- tests/p4rt/acl.py
- tests/p4rt/l3.py
- tests/p4rt/test_l3.py
- tests/p4rt/test_p4rt_acl.py
- tests/p4rt/test_p4rt_mirror.py
- tests/p4rt/util.py
Added p4orch pytest.
Co-authored-by: Yilan Ji yilanji@google.com
Co-authored-by: Manali Kumar manalikumar@google.com
Co-authored-by: Akarsh Gupta akarshgupta@google.com
Co-authored-by: Runming Wu runmingwu@google.com
Co-authored-by: Jay Hu jiarenhu@google.com
Co-authored-by: Howard Yang yhoward@google.com
Co-authored-by: Mike Attig mikeattig@google.com
Co-authored-by: Stephen Wang tingchun@google.com
Co-authored-by: Brian O'Connor <bocon@opennetworking.org>
Co-authored-by: Donald Newton <don@opennetworking.org>
> Add p4orch pytest

- orchagent/cbf/cbfnhgorch.cpp
- orchagent/cbf/nhgmaporch.cpp
- orchagent/cbf/nhgmaporch.h
- orchagent/qosorch.cpp
- tests/test_nhg.py
- tests/test_qos_map.py
**What I did**
Fixed the maximum FC value allowed by a switch.
There was a bit of confusion when I first wrote this, thinking the attribute should return the maximum FC value allowed by the switch, not the maximum number of FC classes. Because of this, the actual maximum FC value allowed is one less than the current one because we're counting from 0. As such, if the switch reports the maximum number of FCs is 255, the actual FC value must be in the 0-254 range.
Updated the existing UTs
> [cbf] Fix max FC value

- orchagent/switchorch.cpp
Signed-off-by: Venkat Garigipati <venkatg@cisco.com>
**What I did**
Enable Debug shell config to enable debug shell. 
Provision for Debug shell
> create debug_shell_enable config to enable debug shell

- orchagent/pfc_detect_barefoot.lua
- orchagent/pfc_detect_broadcom.lua
- orchagent/pfc_detect_innovium.lua
- orchagent/pfc_detect_mellanox.lua
- orchagent/pfc_detect_nephos.lua
- orchagent/pfc_restore.lua
Signed-off-by: Stepan Blyshchak <stepanb@nvidia.com>
**What I did**
It could be that queue counters are populated to FLEX COUNTER DB before the COUNTER_QUEUE_INDEX_MAP is populated which is in accordance to PortsOrch implementation. Fixing it by replacing the order - first the COUNTER_QUEUE_INDEX_MAP then the FLEX COUNTER DB might produce other issues if readers start reading the map and try to find the corresponding entry in COUNTERS DB. Such an order is also in alignment with other maps and counters. So seems like fixing it in the reader is more suitable fix.
Errors observed only for short period of time at system start when PFC WD is enabled:
```
Nov 10 15:12:19.001472 tgs-sonic-n2-s1 ERR syncd#SDK: :- guard: RedisReply catches system_error: command: …
```
> [pfc_detect] fix RedisReply errors

- doc/Configuration.md
**What I did**
Supply the missing ingress/egress port profile list tables in document
> [Document] Supply the missing ingress/egress port profile list tables in document

- cfgmgr/buffermgrd.cpp
- cfgmgr/buffermgrdyn.cpp
- cfgmgr/buffermgrdyn.h
- orchagent/bufferorch.cpp
- orchagent/bufferorch.h
- orchagent/orch.cpp
- orchagent/orch.h
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/test_buffer_dynamic.py
This is to backport #1996 to 202012.
**What I did**
Common code update for reclaiming buffer.
1. Loading zero_profiles when dynamic buffer manager starting
The buffer manager won't consume it for now. This is to pass Azure CI.
2. Support removing a buffer pool.
3. Support exposing maximum PGs and queues per port
4. Support transmit between bitmap and map string
5. Change the log severity from `ERROR` to `NOTICE` when parsing buffer profile from buffer profile list failed. Typically this can be resolved by retrying.
The severity of similar log when parsing buffer PG and queue is already `NOTICE`.
To split large PR into smaller ones and help pass CI.
vs test and regression test.
> [Reclaim buffer][202012] Common code update

- tests/conftest.py
- tests/test_virtual_chassis.py
**What I did**
- In tests/conftest.py Set the FABRIC_NUM_PORTS to 16. This is required since addition of
fabric port orch adds 16 fabrics in asic db internally.
- in tests/test_virtual_chassis.py added back the skipped tests
Fix for virtual chassis tests failure issue https://github.com/Azure/sonic-swss/issues/1809
With sonic-buildimage PR https://github.com/Azure/sonic-buildimage/pull/8008, run the vs test. All tests from test_virtual_chassis.py should pass consistently
This PR is dependent on sonic-buildimage PR https://github.com/Azure/sonic-buildimage/pull/8008
> [vstest] VS test failure fix after fabric port orch PR merge

- orchagent/routeorch.cpp
- orchagent/routeorch.h
- tests/test_route.py
**What I did**
* Orchagent update of IPv4 and IPv6 default route status. If there is a valid default route, it shall be updated as state:ok. If there is no valid default route (with packet action drop), state db shall be updated as state:na - Schema ("ROUTE_TABLE|0.0.0.0/0")
cherry-pick PR https://github.com/Azure/sonic-swss/pull/2009
> [202012] Update default route status to state DB (#2009)

- cfgmgr/buffermgr.cpp
- cfgmgr/buffermgr.h
**What I did**
It's to port #2011 to 202012
To reclaim reserved buffer.
As the way to do it differs among vendors, `buffermgrd` will:
- Handle port admin down on Mellanox platform.
- Not apply lossless buffer PG to an admin-down port 
- Remove lossless buffer PG (3-4) from a port when it is shut down.
- Readd lossless buffer PG (3-4) to a port when a port is started up.
To support reclaiming reserved buffer when a port is shut down on Mellanox platform in traditional buffer model.
Regression test and vs test.
> [Reclaiming buffer][202012] Support reclaiming buffer in traditional buffer model

- cfgmgr/buffer_pool_mellanox.lua
- cfgmgr/buffermgrd.cpp
- cfgmgr/buffermgrdyn.cpp
- cfgmgr/buffermgrdyn.h
- tests/test_buffer_dynamic.py
This is to backport community PR #1910 to 202012 branch.
Depends on #2061 which backports #1996 to 202012 branch.
**What I did**
Reclaim reserved buffer of unused ports for both dynamic and traditional models.
This is done by 
- Removing lossless priority groups on unused ports.
- Applying zero buffer profiles on the buffer objects of unused ports.
- In the dynamic buffer model, the zero profiles are loaded from a JSON file and applied to `APPL_DB` if there are admin down ports.
The default buffer configuration will be configured on all ports. Buffer manager will apply zero profiles on admin down ports.
- In the static buffer model, the zero profiles are loaded by the buffer template.
Regression test …
> [Reclaim buffer][202012] Reclaim unused buffer for dynamic buffer model

- orchagent/bulker.h
- orchagent/mplsrouteorch.cpp
- orchagent/routeorch.cpp
- tests/mock_tests/bulker_ut.cpp
**What I did**
Check if there are items pending removal in bulk before calling bulk set API.
Fixes https://github.com/Azure/sonic-buildimage/issues/9434
When there are items pending removal in bulk before calling set API, it means the item will be removed before the set and it should do create instead.
> [bulk mode] Fix bulk conflict when in case there are both remove and set operations

- orchagent/pfc_detect_barefoot.lua
- orchagent/pfc_detect_broadcom.lua
- orchagent/pfc_detect_innovium.lua
- orchagent/pfc_detect_mellanox.lua
- orchagent/pfc_detect_nephos.lua
- orchagent/pfc_restore.lua
Signed-off-by: Stepan Blyshchak <stepanb@nvidia.com>
**What I did**
It could be that queue counters are populated to FLEX COUNTER DB before the COUNTER_QUEUE_INDEX_MAP is populated which is in accordance to PortsOrch implementation. Fixing it by replacing the order - first the COUNTER_QUEUE_INDEX_MAP then the FLEX COUNTER DB might produce other issues if readers start reading the map and try to find the corresponding entry in COUNTERS DB. Such an order is also in alignment with other maps and counters. So seems like fixing it in the reader is more suitable fix.
Errors observed only for short period of time at system start when PFC WD is enabled:
```
Nov 10 15:12:19.001472 tgs-sonic-n2-s1 ERR syncd#SDK: :- guard: RedisReply catches system_error: command: …
```
> [202012][pfc_detect] fix RedisReply errors

- orchagent/pfc_restore_cisco-8000.lua
- orchagent/pfcactionhandler.cpp
- orchagent/pfcactionhandler.h
Signed-off-by: Alpesh S Patel <alpesh@cisco.com>
**What I did**
1. Enables support for Rx traffic drop for a port/tc by applying the zero buffer profile
2. Changed class hierarchy so that default getHwCounters() function is used (since the Rx counter support is enabled)
3. Fixes a pfc-wd off by 1 detection in case of PFC-WD detection without traffic
1. enabling a missing functionality
2. leveraging sonic code as our sdk now implements the missing counter
3. fixes a bug 
on a cisco-8000 router:
1. detected pfc-wd detection and restore happens within the (detection/restore-time + 1 poll interval) duration and that the changeset passes MSFT tests
2. Verified that when PFC-WD is detected, both Rx and Tx traffic for a port/tc is dropped and no forwarding …
> patch for issue #1971 - enable Rx Drop handling for cisco-8000

- orchagent/routeorch.cpp
- tests/mock_tests/Makefile.am
- tests/mock_tests/mock_orchagent_main.h
- tests/mock_tests/routeorch_ut.cpp
- tests/mock_tests/ut_saihelper.cpp
**What I did**
Fix 2 issues in route bulk operation in the scenario where a SET operation follows a DEL operation on the same prefix.
1. The route entry SET operation can be ignored if it follows a DEL operation with the same prefix and next-hop.
2. DEL and then SET default route results in orchagent aborted
Added test case to cover the scenarios
Manually test
Unit test
***The route entry SET operation can be ignored if it follows a DEL operation with the same prefix and next-hop.***
For example, the following operations
```
2021-12-18.06:17:54.793234|ROUTE_TABLE:1.1.1.0/24|SET|nexthop:10.0.0.33|ifname:Ethernet64
2021-12-18.06:19:53.187294|ROUTE_TABLE:1.1.1.0/24|DEL …
```
> [Route bulk] Fix bugs in case a SET operation follows a DEL operation in the same bulk

- .azure-pipelines/build-template.yml
**What I did**
The armhf sonic-buildimage build is not ready yet, it provides a workaround to download the depended packaged from the failed build 63911.
The armhf build only depends on some of the debian packages of sonic-buildimage, target/debs/buster/libnl-*.deb, although the build 63911 was failed, but the depended packages were good.
The build 63911 is retained, see https://dev.azure.com/mssonic/build/_build/results?buildId=63911&view=results
> Fix armhf buildimage artifacts not found issue

- tests/p4rt/test_l3.py
- tests/p4rt/test_p4rt_acl.py
- tests/p4rt/test_p4rt_mirror.py
**What I did**
In p4rt test scripts, bind response consumer to appl_state_db for consistency.
In p4orch, the relating notification producer for table `P4RT_TABLE` is on database `appl state db`
Run vstest
notification channel name would be tagged `dbId` - https://github.com/Azure/sonic-swss-common/pull/568
> [p4rt-test] Bind response consumer to appl_state_db

- orchagent/nexthopkey.h
**What I did**
Add initial value for weight in overlay nexthops.
Without initializing the weight variable, it may be initialized as non-zero values. This PR aims to prevent it from happening.
> Add initial value for weight in overlay nexthops

- orchagent/vnetorch.cpp
- orchagent/vnetorch.h
- tests/test_vnet.py
**What I did**
Advertise active vnet tunnel routes.
The overlay routes programmed on the device need to be advertised to BGP peers. This PR aims to meet this requirement.
Add an entry in `ADVERTISE_NETWORK_TABLE` for active overlay routes
> [vnetorch] Advertise vnet tunnel routes

- orchagent/Makefile.am
- orchagent/orchdaemon.cpp
- orchagent/pfc_detect_vs.lua
- tests/test_pfcwd.py
Currently vs platform support is missing in pfcwd which is preventing us from adding unit tests in this area. This PR adds vs platform support for pfcwd and unit test for basic functionality
**What I did**
* Define pfcwd port and queue attributes for vs platform and a vs platform detection lua
* Added unit tests for basic functionality
New unit testcases added have passed
```
nejo@nejo-linux:~/SONiC/sonic-swss/tests$ sudo pytest --dvsname=vs test_pfcwd.py
================================================= test session starts ==================================================
platform linux -- Python 3.6.9, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/nejo/SONiC/sonic-swss/tests
collected 4 items …
```
> [pfcwd] Add vs test infrastructure

- cfgmgr/buffermgrdyn.cpp
- cfgmgr/buffermgrdyn.h
**What I did**
Previously, 400G buffer profiles for Mellanox 4xxx switches did not add '_8lane' to the profile name, because there is no other possibility. Now, the condition also applies to 800G buffer profiles for 5xxx switches. The work includes code that other vendors could use in buffermgrdyn if they need to distinguish between models.
No need for '_8lane' in profile name when there is no other possibility.
buffershow -l
> [Mellanox] '_8lane' not added to Mellanox 5xxx models with 800G

- orchagent/crmorch.cpp
Signed-off-by: Sudharsan Dhamal Gopalarathnam <sudharsand@nvidia.com>
**What I did**
When CRM table contains some invalid configurations, the existing logic parses all field values above it and doesn't parse the field values below it. On hitting the unknown field, crm orch returns the execution leaving the crm database inconsistent. To handle this gracefully CRM orch will just log the unknown field and continue processing the fields below the unknown field.
For example when 202012 was misconfigured to have mpls_inseg_high_threshold which was not a supported field, the below error is thrown. However after this error the fields below 'mpls_inseg_high_threshold' are not parsed and fields above this field were parsed and programmed. 
syslog.26.gz:Jan 10 14:55:54.520378 r-anaconda-71 ERR …
> [CRM]Handling Invalid CRM configuration gracefully

- orchagent/portsorch.cpp
**What I did**
Fix unsafe usage of `strncpy` in portsorch.cpp.
The following errors occurred when sonic-swss is being build inside slave docker:
```
portsorch.cpp: In member function 'bool PortsOrch::createVlanHostIntf(swss::Port&, std::__cxx11::string)':
portsorch.cpp:2180:12: error: 'char* strncpy(char*, const char*, size_t)' specified bound 32 equals destination size [-Werror=stringop-truncation]
strncpy(attr.value.chardata, hostif_name.c_str(), sizeof(attr.value.chardata));//SAI_HOSTIF_NAME_SIZE);
~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [Makefile:942: orchagent-portsorch.o] Error 1
```
Originally, `strncpy` is used in the …
> Fix the unsafe usage of strncpy in portsorch.cpp

- orchagent/p4orch/p4orch.cpp
Signed-off-by: Volodymyr Boyko <volodymyrx.boiko@intel.com>
**What I did**
Moved sai_deserialize_free_port_oper_status_ntf(count, port_oper_status); call outside the loop iterating port_oper_status array.
Calling sai_deserialize_free_port_oper_status_ntf(count, port_oper_status); in loop causes double-free.
```
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f66568ed7bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
[Current thread is 1 (Thread 0x7f6656507bc0 (LWP 39))]
(gdb) bt
#0  0x00007f66568ed7bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f66568d8535 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f665692f508 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f6656935c1a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4 …
```
> [p4orch] Fix handlePortStatusChangeNotification operstatus deserialize

- mclagsyncd/mclaglink.h
**What I did**
Reorder class member variables.
I've encountered an issue with m_bufSize, it's initialization is random, some times it may be initializied with 0, some times with random value.
`m_bufSize` use `MSG_BATCH_SIZE` for initialization:
```
MclagLink::MclagLink(Select *select, int port) :
MSG_BATCH_SIZE(256),
m_bufSize(MCLAG_MAX_MSG_LEN * MSG_BATCH_SIZE),
...
```
but `MSG_BATCH_SIZE` declared after `m_bufSize`
```
class MclagLink : public Selectable {
private:
unsigned int m_bufSize;
...
const int MSG_BATCH_SIZE;
...
```
so MSG_BATCH_SIZE will be initialized after m_bufSize, and m_bufSize will use MSG_BATCH_SIZE with uninitialized value.
Setup mclag topology, some times mclagsyncd will not be able to receive data after startup.
**Details if …
> [mclagsyncd] fix out of order initialization

- orchagent/bufferorch.cpp
**What I did**
Currently, SAI_BUFFER_POOL_STAT_WATERMARK_BYTES and SAI_BUFFER_POOL_STAT_XOFF_ROOM_WATERMARK_BYTES are queried for buffer pools.
However, the latter is not supported on all pools and all platforms, which will results in sairedis complaint
To avoid that, we need to test whether it is supported before putting it to FLEX_COUNTER table
It depends on #1987 to be cherry-picked to 202012.
[Bugfix] Don't query SAI_BUFFER_POOL_STAT_XOFF_ROOM_WATERMARK_BYTES if it is not supported by a pool
Run vstest and manually test.
> [buffer orch][202012] Bugfix: Don't query counter SAI_BUFFER_POOL_STAT_XOFF_ROOM_WATERMARK_BYTES on a pool where it is not supported (#1857)

- orchagent/cbf/cbfnhgorch.cpp
- tests/test_nhg.py
**What I did**
Changed the CBF group members sync code to be non-assertive when one of its members is not yet synced.
There can be situations when the member of a CBF group is not yet synced by the time the CBF group is being synced. Some examples would be:
- CBF group entry is created before its member in APPL_DB
- Member sync is being blocked by something, like missing a neighbor/NH entry
In this scenarios, we should wait for the member to be synced instead of asserting as the member might become available shortly.
Added a new UT
> [cbf] Fix cbf sync error

- orchagent/neighorch.cpp
- tests/test_virtual_chassis.py
**What I did**
Changes done to avoid sending SAI_NEIGHBOR_ENTRY_ATTR_ENCAP_IMPOSE_INDEX in neighbor entry while creating neighbor records in SAI
Since neighbor entry attribute SAI_NEIGHBOR_ENTRY_ATTR_ENCAP_IMPOSE_INDEX is deprecated, and since the new version of SAI (version > 6.0.0.11; OCP version 1.9.1) returns error (previous versions just ignores this deprecated attribute instead of returning error), this attribute is no longer sent in the neighbor entry creation to avoid orchagent crash when syncd returns error.
- Load VOQ chassis line card with image that uses SAI version > 6.0.0.11 (OCP version 1.9.1)
- Bring up an interface and configure IP address to the interface.
- Observe that syncd has not returned any error, orchagent process is up and …
> [voq] Neighbor entry impose encap index attribute deprecated

- tests/test_nhg.py
**What I did**
Removed some leftover state from a previous test case that was sometimes messing up with a following test case.
VS test pipelines fail from time to time because of this.
Tried to repro the crash running the test file.
> [test_nhg.py] Cleanup test resources at the end

- cfgmgr/buffermgr.cpp
What I did
Fixed the issue of missing PG lossless profile for set of ports on multiple HWSKUs.
Cherry-picking #2129 
Why I did it
After switch bringup, a set of ports were missing PG profile in config file. This was causing most of QoS test cases to fail.
Verified it on BRCM based HWSKU.
Details if related
Fix involves removing break statement from the logic. This statement was causing exiting the while loop hence no more port updates were processed (in this case PG profile) if doSpeedUpdateTask returns failure for some reason.
Signed-off-by: Vineet Mittal <vineetmittal@microsoft.com>
> Fix for missing lossless PG profile on certain ports

- cfgmgr/intfmgr.cpp
- cfgmgr/intfmgr.h
- cfgmgr/nbrmgr.cpp
**What I did**
By default the metric for ipv6 static route is 1024. This makes it the
routes learned via the internal bgp sessions inferior to the Ebgp
routes. So make the metric 256 which make the static route metric same
as connected route metric.
To fix IPv6 BGP multipath-relax peer-type.
Verified voq chassis can learn a route which ecmps routes advertised by internal ibgp neighbor and ebgp neighbor.
> Fix for 2053, Fix IPv6 BGP multipath-relax peer-type.

- .azure-pipelines/test-docker-sonic-vs-template.yml
**What I did**
Change to use sonic-common as the test agent pool managed by SONiC , to fix the azure image auto-upgrade issue.
> [ci]: Change to the agent pool not use latest azure image

- .azure-pipelines/test-docker-sonic-vs-template.yml
**What I did**
Cleanup the workspace.
In some of the test cases, it is run as root, left some of the file cannot be removed during the checkout step.
Example: https://dev.azure.com/mssonic/build/_build/results?buildId=71009&view=logs&j=3f6395b2-1619-5ebe-f305-2aedcf353cb5&t=aa8a4b4e-56c0-53e8-6540-01f05ca983a1
```
$ ls -l /agent/_work/1/s/tests/.pytest_cache/CACHEDIR.TAG
-rw-r--r-- 1 root root 194 Feb  8 13:28 /agent/_work/1/s/tests/.pytest_cache/CACHEDIR.TAG
$ ls -l /agent/_work/1/s/ -d
drwxr-xr-x 25 AzDevOps AzDevOps 4096 Feb  8 17:11 /agent/_work/1/s/
```
> [ci]: Cleanup the workspace

- orchagent/main.cpp
**What I did**
Do not register for BFD notification during switch create for all platforms
Some platforms are failing switch create with the following logs:
```
/var/log/syslog:Feb 8 17:20:25.726339 str2-7215-acs-1 NOTICE swss#orchagent: :- notifySyncd: sending syncd: INIT_VIEW
/var/log/syslog:Feb 8 17:20:25.727724 str2-7215-acs-1 NOTICE syncd#syncd: :- processNotifySyncd: very first run is TRUE, op = INIT_VIEW
/var/log/syslog:Feb 8 17:20:25.728156 str2-7215-acs-1 NOTICE syncd#syncd: :- clearTempView: clearing current TEMP VIEW
/var/log/syslog:Feb 8 17:20:25.728697 str2-7215-acs-1 NOTICE syncd#syncd: :- clearTempView: clear temp view took 0.000314 sec
/var/log/syslog:Feb 8 17:20:25.745185 str2-7215-acs-1 NOTICE swss#orchagent: :- sai_redis_notify_syncd: switched ASIC to …
```
> [202012] Skip bfd notification during switch create

- .azure-pipelines/test-docker-sonic-vs-template.yml
**What I did**
Changing the docker pool, VS test is taking slightly more than 4hrs. 
> [VS] Increase test timout to 360min

- tests/test_buffer_dynamic.py
- tests/test_nat.py
**What I did**
The following two tests are consistently failing. Skipping for investigation:
```
test_changeCableLen
test_AddTwiceNatEntry
```
> [VS] Skip consistently failing test cases

- orchagent/macsecorch.cpp
**What I did**
Fix a segment fault in MACsec orchagent to record the next iterator before deleting the corresponding MACsec object.
The segment fault will happen if to delete the MACsec Port or MACsec SC that have MACsec SC(s) or MACsec SA(s), Because the original implementation used the for loop to iterate all MACsec sub objects, but the MACsec sub object will be delete on each iteration so that the removed iterator cannot go to the next one.
Use `appl_db_del(appl_db, "MACSEC_PORT_TABLE", ifname)` to delete a MACsec port that has MACsec SC, The segment fault shouldn't happen.
> [macsecorch]: Fix deleting MACsec bug

- cfgmgr/coppmgr.cpp
- cfgmgr/coppmgr.h
- tests/test_copp.py
- What I did
Add the new design for copp manager - always_enabled field in copp_cfg.json file.
- Why I did it
A change was done for traps needs to be installed but doesn't have feature (arp, udld, lacp, ip2me),
in the new implementation, coppmgr will not automatically install traps which has no entry in features table, but will check first if the trap has "always_enabled":"true" field.
- How I verified it
run tests for making sure traps are installed and not when expecting them to.
- Details if related
Related to sonic-buildimage change - Azure/sonic-buildimage#9302
SONiC mgmt test plan can be found in Azure/SONiC#903.
This commit is a cherry-pick of https://github.com/Azure/sonic-swss/pull/2034
> [CoPP] Add always_enabled field to coppmgr logic

- .azure-pipelines/build-docker-sonic-vs-template.yml
- .azure-pipelines/build-template.yml
- .azure-pipelines/test-docker-sonic-vs-template.yml
**What I did**
1. Change reference to 202106 branch. 
2. Pipeline 1 doesn't have artifact on 202106 branch. We use 142 instead.
3. Use sonic-common instead of latest ubuntu.
4. Change vstest timeout from 180 minutes to 240 minutes
1. To resolve dependencies branch not match issue:
OSError: [Errno 24] Too many open files: '/home/vsts/work/1/s/tests/tr.xml'
2. To resolve latest ubuntu image issue: 
sudo /sbin/ip link add Vrf1 type vrf table 1001
Error: Unknown device type.
3. vstest timeout is not enough.
> [ci] Fix dependencies reference branch and use sonic-common agent pool.

- orchagent/neighorch.cpp
**What I did**
Fix for issue: https://github.com/Azure/sonic-buildimage/issues/8606
Orchagent (NeighOrch) currently ignores IPv4 link-local neighbours. Any route pointing to such a nexthop is not added to the ASIC DB. Such routes are expected and should be supported.
```
root@sonic:/home/admin# redis-cli hgetall "NEIGH_TABLE:Ethernet0:169.254.0.1"
1) "family"
2) "IPv4"
3) "neigh"
4) "00:10:94:00:00:01"
root@sonic:/home/admin#
root@sonic:/home/admin# redis-cli hgetall "ROUTE_TABLE:50.0.1.0/24"
1) "nexthop"
2) "169.254.0.1"
3) "ifname"
4) "Ethernet0"
root@sonic:/home/admin#
--- Syslog ---
Sep 10 08:51:22.177963 sonic NOTICE swss#orchagent: :- addNeighbor: Created neighbor ip 169.254.0.1, 00:10:94:00:00:01 on Ethernet0
Sep 10 08:51:22.178802 sonic …
```
> Allow IPv4 link-local nexthops

- orchagent/crmorch.cpp
- orchagent/crmorch.h
**What I did**
Aligned supported CRM resources with the newest way to get counters using sai_object_type_get_availability() API.
To use newest way to get CRM counters
Run CRM test from sonic-mgmt 
N/A
> [crm] Use sai_object_type_get_availability() API to get counters

- orchagent/orch.cpp
- orchagent/orch.h
- orchagent/orchdaemon.cpp
- orchagent/qosorch.cpp
- orchagent/qosorch.h
- tests/mock_tests/Makefile.am
- tests/mock_tests/mock_orchagent_main.h
- tests/mock_tests/qosorch_ut.cpp
- tests/mock_tests/ut_saihelper.cpp
**What I did**
Fix issue `config qos reload` causing orchagent aborted via tracking dependencies among QoS tables
1. Track dependencies among QoS tables.
Won't call SAI remove API for an object if it is still referenced.
2. Support removing/replacing one field in PORT_QOS_MAP and QUEUE tables.
3. Optimize logic to handle QUEUE table.
4. Remove switch level DSCP_TO_TC map before the map is removed.
5. Add mock test
Fix issue.
Manually test and mock test.
> Fix issue config qos reload causing orchagent aborted via tracking dependencies among QoS tables

- orchagent/orch.cpp
- orchagent/orchdaemon.cpp
**What I did**
Use `abort` instead of `exit` in case calling SAI API failure
Currently, `exit` is used in functions `handleSai{Create,Remove,Set,Get}Status` on SAI failure while `abort` is used in some other functions on SAI failure.
IMO using `abort` yields benefits:
- consistent behavior in orchagent on SAI failure
- in mocked test, in case SAI failure occurs the test process will just exit silently, which makes it very difficult for developers to find out what happened. by using `abort`, a coredump will be generated, which helps developers nail down the issue.
So we would like to use `abort` in all cases of receiving SAI failure.
Manually test.
> Use abort instead of exit in case calling SAI API failure

- doc/Configuration.md
**What I did**
Add AAA table description and example to configuration.md 
AAA table description and example are missing in configuration.md 
No code change, not validate.
> [AAA] Add AAA table description and example to configuration.md

- .azure-pipelines/build-template.yml
**What I did**
Update sonic-buildimage build ID used in build job.
Former build ID is out of date. pipeline didn't keep its artifacts.
> [ci] Update default sonic image downloading build ID.

- cfgmgr/tunnelmgr.cpp
- cfgmgr/tunnelmgr.h
- cfgmgr/tunnelmgrd.cpp
- tests/test_warm_reboot.py
**What I did**
Add warmboot support to tunnelmgrd
- At initialization, check if warmboot occurred. Replay IPinIP tunnel creation if it did but avoid duplicate APP_DB set
During warmboot, tunnelmgrd initiates a write to APP_DB for an IPinIP tunnel which already exists in hardware prior to the warmboot. This causes an orchagent crash.
Run the new tunnelmgrd warmboot test
> [tunnelmgrd]: Warm boot support

- orchagent/mirrororch.cpp
**What I did**
Check LAG is not empty before creating mirror session.
Fix issue https://github.com/Azure/sonic-buildimage/issues/7988#issue-930946691
Verified config with empty LAG.
> Validate LAG has members before mirror session create

- cfgmgr/vxlanmgr.cpp
- cfgmgr/vxlanmgr.h
- tests/test_vxlan_tunnel.py
**What I did**
Fixes https://github.com/Azure/sonic-buildimage/issues/9709
Enhanced the Existing cleanup methods i.e. `getAllVxlanNetDevices` & `clearAllVxlanDevices` to also include any stale Brvxlan interfaces and remove them.
Added a vs-test to simulate the scenario.
Config reload with VNET and VxLAN tunnel configuration results in error in syslog "Cannot create vxlan Vxlan1"
```
Jan 6 21:07:10.858785 r-lionfish-16 WARNING swss#vxlanmgrd: :- doVxlanDeleteTask: Vxlan(Vnet Vnet1) hasn't been created
Jan 6 21:07:10.874014 r-lionfish-16 INFO swss#/supervisord: vxlanmgrd RTNETLINK answers: File exists
Jan 6 21:07:10.924868 r-lionfish-16 WARNING swss#vxlanmgrd: :- createVxlan: Fail to create vxlan interface Brvxlan1
Jan 6 21:07:10.924868 r-lionfish-16 ERR swss#vxlanmgrd: :- …
```
> [Vxlanmgr] vnet netdev cleanup during config reload fix

- orchagent/aclorch.cpp
- orchagent/orch.h
**What I did**
Fix for handling broadcom DNX ASIC to have ipv4 and ipv6 ACL rules in separate tables.
Related PR : https://github.com/Azure/sonic-buildimage/pull/10235
Broadcom DNX ASIC need to have ipv4 and ipv6 ACL rules in separate tables.
Verified the SWSS_VARS is updated and sub_platfom populated with 'broadcom-dnx'
> Fix for handling broadcom DNX ASIC to have ipv4 and ipv6 ACL rules in separate tables.

- orchagent/vxlanorch.cpp
- tests/test_vnet.py
**What I did**
* VxLAN tunnel map objects were not removed on VNET tunnel removal.
* It caused config lefovers which is not expected.
* If tunnel is removed then all related objects should be removed as well.
* To do so just used deleteTunnelHw() function which does proper remove.
To cleanup config leftovers after VNET tunnel removal.
* Configure 2 VNETs and then remove them one by one.
* Verify that after 1st VNET removed tunnel and all related objects still exist.
* Verify that after 2nd (last) VNET removed tunnel and all related objects are removed.
N/A
> [vxlan] Remove tunnel map objects on VNET tunnel removal

- orchagent/bfdorch.cpp
- orchagent/bfdorch.h
- orchagent/main.cpp
**What I did**
Register BFD callback during the BFD session creation flow
BFD session callback is required to get state changes from SAI and there by remove or add endpoints. However not all vendors support it. So moved it from switch initialization and set it during first session creation with query for support from SAI.
Verified it manually with BFD show command which also relies on BFD session change notifications
> [BFD]Registering BFD state change callback during session creation

- orchagent/fdborch.cpp
It causes incorrect neighbor processing by MuxOrch and results in test_orchagent_mac_move failure.
**What I did**
Assigned port.m_alias to entry.port_name 
In MuxOrch::updateFdb, there are decisions and assignments done based on this field.
test_orchagent_mac_move that was failing without this change, started passing
> [FdbOrch] SAI_FDB_EVENT_MOVE generates update with empty update.entry.port_name

- orchagent/vxlanorch.cpp
- tests/test_vnet.py
**What I did**
* VxLAN tunnel map objects were not removed on VNET tunnel removal.
* It caused config lefovers which is not expected.
* If tunnel is removed then all related objects should be removed as well.
* To do so just used deleteTunnelHw() function which does proper remove.
To cleanup config leftovers after VNET tunnel removal.
* Configure 2 VNETs and then remove them one by one.
* Verify that after 1st VNET removed tunnel and all related objects still exist.
* Verify that after 2nd (last) VNET removed tunnel and all related objects are removed.
N/A
> [202012] [vxlan] Remove tunnel map objects on VNET tunnel removal

- orchagent/portsorch.cpp
- tests/test_acl_portchannel.py
Add some extra validation to make sure that port can't be made a LAG member when ingress/egress ACL binding is configured.
Before moving port to LAG, user should disable active ACL binding, since LAG uses a different dedicated attributes
fixes Azure/sonic-buildimage#10233
**What I did**
* Prevent LAG member configuration when port has active ACL binding
* To fix ACL PORT/LAG config divergency
1. Deploy t0 topology
2. Create LAG interface
3. Remove arbitrary port from VLAN
4. Make port LAG member
```
root@sonic:/home/admin# show acl table
Name        Type       Binding         Description    Stage
----------  ---------  --------------  -------------  -------
DATAACL     L3 …
```
> [portsorch]: Prevent LAG member configuration when port has active ACL binding

- orchagent/bufferorch.cpp
**What I did**
Remove redundant and problematic code to skip "pool" field in buffer profile handling
When a buffer profile is modified, the snippet of code skipped "pool" field handling without pool's name being parsed, which broke the dependency tracing logic.
In a rare scenario, if buffer orchagent receives a notification to remove the pool before removing the profile, it can cause the buffer pool to be removed when it is still referenced.
Manually and regression test.
> Remove redundant and problematic code to skip "pool" field in buffer profile handling

- orchagent/Makefile.am
- orchagent/pbh/pbhcap.cpp
- orchagent/pbh/pbhcap.h
- orchagent/pbh/pbhcnt.h
- orchagent/pbh/pbhmgr.cpp
- orchagent/pbh/pbhrule.cpp
- orchagent/pbh/pbhrule.h
- orchagent/pbh/pbhschema.h
- orchagent/pbhorch.cpp
- orchagent/pbhorch.h
- tests/dvslib/dvs_acl.py
- tests/dvslib/dvs_database.py
- tests/dvslib/dvs_pbh.py
- tests/mock_tests/Makefile.am
- tests/test_pbh.py
PBH Edit Flows is a second phase of PBH feature implementation. It allows user to modify the already existing objects.
PBH Edit Flows offer a full entity update which assumes Config DB field ADD/UPDATE/REMOVE processing. PBH OA interprets series of Redis HSET/HDEL as SONiC SET operation and internally does the diff of existing/supplied configuration to deploy the new changes.
HLD: https://github.com/Azure/SONiC/pull/909
**What I did**
* Implemented Edit Flows in scope of PBH enhancement
* Implementation is done according to the PBH HLD
* N/A
* N/A
> [pbh]: Implement Edit Flows

- neighsyncd/neighsync.h
Signed-off-by: Stepan Blyschak <stepanb@nvidia.com>
**What I did**
Increased the neighsyncd timeout.
Restore_neigh takes a bit more time to start thus it could be that the neighsyncd timeout is not enough to wait for restore_neighbors.
```
admin@arc-switch1004:~$ sudo zgrep 'restore_neigh' /var/log/syslog.4 | head -n5
Mar 29 09:21:32.330716 arc-switch1004 INFO swss#supervisord 2022-03-29 09:21:32,316 INFO spawned: 'restore_neighbors' with pid 67
Mar 29 09:21:32.336639 arc-switch1004 INFO swss#supervisord 2022-03-29 09:21:32,329 INFO success: restore_neighbors entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Mar 29 09:21:43.017175 arc-switch1004 INFO swss#restore_neighbor: restore_neighbors service is started
Mar 29 09:23:36.163758 …
```
> [neighsyncd] increase neighsyncd timeout

- orchagent/port.h
- orchagent/portsorch.cpp
- tests/test_port.py
- tests/test_port_an.py
Porting https://github.com/Azure/sonic-swss/pull/1705 to 201911
**What I did**
Allowing the first time configuration for FEC and Autoneg to be pushed to SAI even if they are default.
In orchagent, the port struct is pre-initialized with fec = none and autoneg = false (Default SAI values). However in different hardware the underlying implementation might be different. There can also be requirement where the user values need to be forced. In current logic due to the port struct being initialized with default, fec = none or an = false configurations are not pushed from orchagent to SAI. In order to push it even in default case the conditional checks are modified.
> [201911][FEC]Allowing the first time FEC and AN configuration to be pushed to SAI

- cfgmgr/vlanmgr.cpp
**What I did**
Reordered the code so the reference to a deleted object (t) is not used
This was found via ASAN<details><summary>ASAN log</summary>
```
=================================================================
==1269==ERROR: AddressSanitizer: heap-use-after-free on address 0x60e000000518 at pc 0x5557cf441fb8 bp 0x7ffdfbd0fea0 sp 0x7ffdfbd0fe98
READ of size 8 at 0x60e000000518 thread T0
#0 0x5557cf441fb7 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const /usr/include/c++/8/bits/basic_string.h:2291
#1 0x5557cf441fb7 in swss::VlanMgr::doVlanTask(Consumer&) cfgmgr/vlanmgr.cpp:336
#2 0x5557cf4456c6 in swss::VlanMgr::doTask(Consumer&) cfgmgr/vlanmgr.cpp:686
#3 0x5557cf4b4e76 in Consumer::execute() ../orchagent/orch.cpp:235
#4 0x5557cf421e1d …
```
> [vlanmgrd] fix use-after-free memory issue

- orchagent/bufferorch.cpp
- orchagent/bufferorch.h
- orchagent/pfcactionhandler.cpp
- orchagent/pfcactionhandler.h
- tests/mock_tests/mock_orchagent_main.h
- tests/mock_tests/portsorch_ut.cpp
This is to backport PR https://github.com/Azure/sonic-swss/pull/2164 to 202012 branch.
**What I did**
Fix issue: sometimes PFC WD is unable to create zero buffer pool.
On some platforms, an ingress/egress zero buffer profile will be applied on the PG and queue which are under PFC storm. The zero buffer profile is created based on zero buffer pool. However, sometimes it fails to create zero buffer pool due to too many buffer pools existing in the system.
Sometimes, there is a zero buffer pool existing on the system for reclaiming buffer. In that case, we can leverage it to create zero buffer profile for PFC WD.
Fix the issue via sharing the zero buffer pool between PFC WD and buffer orchagent
Manually test
Run PFC WD test and PFC WD warm reboot test …
> [202012] Fix issue: sometimes PFC WD unable to create zero buffer pool

- orchagent/mirrororch.cpp
- orchagent/mirrororch.h
**What I did**
* Added a validation to prevent mirror session configuration if there is no available HW resources
* To prevent system from unexpected reboots
* To add some debuggability information to the system journal
1. Configure mirror sessions
```bash
config mirror_session span add TEST1 Ethernet0 Ethernet4
config mirror_session span add TEST2 Ethernet8 Ethernet12
config mirror_session span add TEST3 Ethernet16 Ethernet20
config mirror_session span add TEST4 Ethernet24 Ethernet28
config mirror_session span add TEST5 Ethernet32 Ethernet36
config mirror_session span add TEST6 Ethernet40 Ethernet44
config mirror_session span add TEST7 Ethernet48 Ethernet52
config mirror_session span add TEST8 …
```
> [mirrororch] Implement HW resources availability validation

- orchagent/tunneldecaporch.cpp
**What I did**
For a specific dst ip, if the tunnel terminator already exists, trying to create a term for the same IP one for another different tunnel should not return ERR log. This is an expected flow, and the log can be NOTICE level. 
False ERR logs while analyzing ERR logs in the system. 
> [Syslog] Change ERR to NOTICE for tunnel term create fail for existing entry

- orchagent/debugcounterorch.cpp
- orchagent/debugcounterorch.h
- orchagent/orchdaemon.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/conftest.py
- tests/dvslib/dvs_database.py
- tests/dvslib/dvs_port.py
- tests/test_drop_counters.py
- tests/test_flex_counters.py
- tests/test_pg_drop_counter.py
**What I did**
add support for adding & removing port counters dynamically each time port was added or removed
the counters that were supported are:
- pg watermark counters
- pg drop counters
- queue stat counters
- queue watermark counters
- debug counters
* buffer drop counters and port stat counters are already supported to be added or removed each time port  is added/removed
Implemented according to the - [Dynamic Port Cfg HLD](https://github.com/Azure/SONiC/pull/900)
in order to support dynamically add or removed ports on sonic
tested manually that the flex counters were added or removed correctly whenever we add or remove ports
added new test cases to the following vs tests:
- test_flex_counters.py
- test_drop_counters.py
- …
> [orchagent] add & remove port counters dynamically each time port was added or removed

- orchagent/bfdorch.cpp
- orchagent/bfdorch.h
**What I did**
The create_bfd_session API can fail when a source port already used by a different application is passed to SAI create. To avoid failure, a retry logic is added to try with a different port number three times before failing
To avoid BFD failure and orchagent crash due to port conflict.
Verified it manually by having an application binding the port and checking if retry is done when BFD tries the same port
> [BFD]Retry create BFD with different source UDP port on failure

- orchagent/aclorch.cpp
- orchagent/aclorch.h
- tests/test_pbh.py
**What I did**
Added the register and deregister functions for the flex counter before updating counters for the ACL rule.
Overcome SAI error in case of flow counters disabled and then enabled.
For example:
1. Show PBH rules:
```
root@sonic:/home/admin# show pbh rule
TABLE      RULE             PRIORITY    MATCH                                 HASH        ACTION         COUNTER
---------  ---------------  ----------  ------------------------------------  ----------  -------------  ---------
pbh_table  nvgre_ipv4_ipv4  2           gre_key:           0x2500/0xffffff00  inner_hash  SET_ECMP_HASH  ENABLED
ether_type:        0x0800
ip_protocol:       0x2f
inner_ether_type:  0x0800
```
2. Update PBH rule:
```
root@sonic:/home/admin# config pbh rule update field set pbh_table …
```
> [pbh] [aclorch] Fixed a bug causes by updating the flow-counter value for the PBH rule

- orchagent/aclorch.cpp
**What I did**
Avoid increment CRM counter when ACL rule creation fails. In existing code there is no return statement after failure during ACL rule creation which results in CRM getting incremented. Since the ACL rule recreation is retried this counter increments in a loop.
Added return statement in case of a failure.
Existing UT should verify the changes
> [ACL]Avoid incrementing crm count when ACL rule create fails

- cfgmgr/vxlanmgr.cpp
- cfgmgr/vxlanmgr.h
**What I did**
set vtep-xxx the netdev down before delete vtep-xxx .
the vxlan netdev will be only delete only when remove vxlan tunnel map,
but the FRR doesn't remove IMET route entirely after receiving the delete event.
Therefore, add to set netdev down before delete the netdev to trigger FRR to remove related IMET route.
using t0 topology config
and flow the cmmand
redis-cli -n 4 -c DEL "VLAN_MEMBER|Vlan1000|Ethernet4"
sudo config interface ip add Ethernet4 10.0.0.64/31
vtysh
configure
ip route 100.0.0.65/31 10.0.0.65
exit
exit
sudo config vxlan add vtep 10.1.0.32
sudo config vxlan evpn_nvo add evpnnvo1 vtep
sudo config vxlan map add vtep 1000 10000
vtysh
configure
router bgp 65100
neighbor 10.0.0.65 remote-as 65200
address-family l2vpn evpn …
> set remote vtep the netdev down before delete.

- orchagent/vnetorch.cpp
- tests/test_vnet.py
**What I did**
If VirtualRouter ID is the default value, then don' remove it.  
When removing Vnet with scope `default`, we need not remove the Vrf object if it is of default value.
Added tests to verify it
> Removing Vnet with scope default

- cfgmgr/natmgrd.cpp
Signed-off-by: Oleksandr Ivantsiv <oivantsiv@nvidia.com>
**What I did**
Fix the issue when *natmgrd* remains running after receiving SIGTERM signal and performing clean-up. 
Supervisord sends SIGTERM to all applications that it controls. Application after receiving the signal may optionally run a clean-up routine and should exit. natmngrd runs a cleanup from the signal handler but doesn't exit after that. After supervisord sends the signal it waits for 10 seconds (default timeout) to allow the application to exit correctly. If the application is not exiting in the given timeout supervisord kills the application. natmngrd is always killed by the supervisord. This affects the container restart time. 
Before the fix NAT container shutting down takes ~10 seconds. Docker kills …
> [NAT] Exit from natmgrd correctly after receiving SIGTERM signal.

- cfgmgr/natmgrd.cpp
**What I did**
* Fixed `natmgrd` signal handler
* To fix `swss` package compilation
1. Compile `swss` package
```bash
natmgrd.cpp: In function 'void cleanup()':
natmgrd.cpp:114:34: error: 'signo' was not declared in this scope
old_sigaction.sa_handler(signo);
^~~~~
natmgrd.cpp:114:34: note: suggested alternative: 'sig_t'
old_sigaction.sa_handler(signo);
^~~~~
sig_t
make[3]: *** [Makefile:1377: natmgrd-natmgrd.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/__w/1/s/cfgmgr'
make[2]: *** [Makefile:418: all-recursive] Error 1
make[2]: Leaving directory '/__w/1/s'
make[1]: *** [Makefile:350: all] Error 2
make[1]: Leaving directory '/__w/1/s' …
```
> [asan]: Fix signal handler

- orchagent/aclorch.cpp
Cherrypick of https://github.com/Azure/sonic-swss/pull/2238 into 202012
**What I did**
Avoid increment CRM counter when ACL rule creation fails. In existing code there is no return statement after failure during ACL rule creation which results in CRM getting incremented. Since the ACL rule recreation is retried this counter increments in a loop.
Added return statement in case of a failure.
Existing UT should verify the changes
> [202012][ACL]Avoid incrementing crm count when ACL rule create fails 

- cfgmgr/buffermgr.cpp
- cfgmgr/buffermgr.h
- cfgmgr/buffermgrd.cpp
- orchagent/pfcwdorch.cpp
- orchagent/port.h
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- orchagent/qosorch.cpp
- orchagent/qosorch.h
- tests/conftest.py
- tests/test_buffer_traditional.py
- tests/test_pfcwd.py
**What I did**
This PR is to cherry-pick #2171 after resolving conflicts.
Currently, the entry `pfc_enable` in table `PORT_QOS_MAP` is used to specify pfc and pfc_watchdog are enabled on which queues.
To avoid PFC deadlock in Dual-ToR scrnario, we are going to introduce two extra lossless queues to carry bounced back traffic.[HLD](https://github.com/Azure/SONiC/pull/950).
The extra lossless queues require another two pfc_watchdogs, and the new watchdogs will be implemented by hardware due to limited resources. The hardware pfc watchdog is not covered in this PR.
To specify on which queue to enable  pfc watchdog, we need to define new table `pfcwd_sw_enable`.
|Table | Description|
|-- | --|
|pfc_enable | Specify on which queues to enable PFC|
|pfcwd_sw_enable | Specify on which queues to …
> [202012][cherry-pick]Update orchagent to support new field `pfcwd_sw_enable`

- cfgmgr/macsecmgr.cpp
**What I did**
It looks like we should use network_id in set_network, although I didn't find a related issue in running macsec before this change.
> [macsec] Fix setting network_id in macsec

- cfgmgr/buffermgrdyn.cpp
- cfgmgr/vxlanmgr.cpp
- orchagent/mirrororch.cpp
- portsyncd/linksync.cpp
**What I did**
Fixed the following memory issues:
* [buffermgrd] the "runningProfileName" is used after the object it references is deleted
* [portsyncd] the 'if_ni' is not freed
* [vxlanmgrd] the 'info' is used after the object it references is deleted
* [mirrororch] removed unneeded calloc()
ASAN reports(shortened for convenience):<details><summary>buffermgrd</summary>
```bash
=================================================================
==915==ERROR: AddressSanitizer: heap-use-after-free on address 0x60d000013610 at pc 0x5583b3773cf1 bp 0x7fff5d5ade00 sp 0x7fff5d5addf8
READ of size 8 at 0x60d000013610 thread T0
#0 0x5583b3773cf0 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const /usr/include/c++/8/bits/basic_string.h:2291
#1 …
```
> [buffermgrd] [portsyncd] [vxlanmgrd] [mirrororch] fix a set of memory issues

- orchagent/intfsorch.cpp
- orchagent/intfsorch.h
**What I did**
Fix for [https://github.com/Azure/sonic-swss/issues/2193](url)
To handle this , whenever RIF is deleted (removeRouterIntfs) , we ensure that these COUNTER_DB tables are deleted(handled in cleanUpRifFromCounterDb) .
In this issue , stale COUNTER_DB table/entries were present even after RIF was deleted.
So cleaning up of such stale tables are needed. 
In the absence of this , if same oid is allocated to a different RIF , we may show stale stats.
Also the COUNTER_DB will keep holding un-necessary tables and this number/used-memory keep growing if there RIFs are deleted . 
Before this fix , here is the snapshot of the stale COUNTER_DB tables.
**a. Before fix , here the steps where problem was seen**
1. After RIF creation derived info of …
> Stale rif counter db removal (fix for #2193)_

- orchagent/intfsorch.cpp
**What I did**
Fix for [https://github.com/Azure/sonic-swss/issues/2270](https://github.com/Azure/sonic-swss/pull/url)
Added a comment for TODO . This comment is for reminding existence of a race condition and moving the cleanup code to syncd .
This is done in follow-up to fix in https://github.com/Azure/sonic-swss/pull/2199
The comment is added as TODO - in future the cleanup for rif counters should move to syncd.
No explicit verification is needed for this.
> Comment add for rif counters cleanup (fix for #2270)

- orchagent/qosorch.cpp
- orchagent/qosorch.h
- orchagent/tunneldecaporch.cpp
- orchagent/tunneldecaporch.h
- tests/test_tunnel.py
Signed-off-by: bingwang <wang.bing@microsoft.com>
**What I did**
This PR is to add a retry logic when creating decap tunnel.
If `decap_dscp_to_tc_map`, `decap_tc_to_pg_map`, `encap_tc_to_queue_map` or `encap_tc_to_dscp_map` is set for a decap tunnel, `TunnelDecapOrch` will retry if any of the values is not ready in `QosOrch`.
This PR also fixed an issue when decap tunnel is removed, the reference count of QoS object that being referenced is not decreased.
We need to wait `QosOrch` to process the required QoS table in `TunnelDecapOrch`.
Verified by vs test
```
sudo pytest test_tunnel.py -v --pdb --dvsname=vs
===================================================================================================================== test session starts …
```
> Retry the creation of decap tunnel if dependant QoS map is not ready

- orchagent/portsorch.cpp
Signed-off-by: Kebo Liu <kebol@nvidia.com>
relevant sonic-utility and Yang PRs:
https://github.com/Azure/sonic-buildimage/pull/10826
https://github.com/Azure/sonic-utilities/pull/2167
**What I did**
Support new interface types CR8/SR8/KR8/LR8.
SAI V.1.10.2 introduced new interface types CR8/SR8/KR8/LR8, they shall be added to `interface_type_map` and `interface_type_map_for_an`.
config from CLI, new interface types can be accepted and correctly passed to SAI.
> [portorch] Support new interface types CR8/SR8/KR8/LR8

- cfgmgr/buffermgr.cpp
- cfgmgr/buffermgr.h
- cfgmgr/buffermgrd.cpp
- orchagent/pfcwdorch.cpp
- orchagent/port.h
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- orchagent/qosorch.cpp
- orchagent/qosorch.h
- tests/conftest.py
- tests/test_buffer_traditional.py
- tests/test_pfcwd.py
Reverts Azure/sonic-swss#2245 because the code requires new field `pfcwd_sw_enable`.
Will revert it back when PR https://github.com/Azure/sonic-utilities/pull/2087 is backed port into `202012` branch.
> Revert "[202012][cherry-pick]Update orchagent to support new field `pfcwd_sw_enable`"

- orchagent/main.cpp
What I did:-
Increase Redis Timeout for Switch Creation Operation for chassis-packet.
Why I did:-
Seeing OA crash as SAI/SDK can take more than 1 min for initialization.
How I verify:
Manual Verification.
> [chassis-packet] Increase Redis Timeout value for Switch Create Operation

- tests/conftest.py
- tests/test_nat.py
**What I did**
Migrate NAT vs tests from using click commands to direct DB access.
To decouple vstests from sonic-utilities, the click commands called in vs tests should be modified to redis-CLI based config_db set.
Run the vs tests
> [vstest] Migrating the NAT vs tests from Click to direct DB access

- orchagent/macsecorch.cpp
- orchagent/macsecorch.h
**What I did**
Taught MacsecOrch to use the SAI_MACSEC_ATTR_MAX_SECURE_ASSOCIATIONS_PER_SC attribute added in
https://github.com/opencomputeproject/SAI/pull/1420
To support SAI_MACSEC_ATTR_MAX_SECURE_ASSOCIATIONS_PER_SC in MacsecOrch.
The changes have no impact until SAI_MACSEC_ATTR_MAX_SECURE_ASSOCIATIONS_PER_SC is supported by the platform.
**Details**
Cache the the result of SAI_MACSEC_ATTR_MAX_SECURE_ASSOCIATIONS_PER_SC in MACsecObject.m_max_sa_per_sc.
Set STATE_DB MACSEC_PORT_TABLE's max_sa_per_sc to the value cached in MACsecObject.m_max_sa_per_sc in createMACsecPort.
> [macsecorch]: Support for non-default sa per sc

- orchagent/bufferorch.cpp
- orchagent/pfcactionhandler.cpp
- orchagent/pfcactionhandler.h
- orchagent/port.h
- orchagent/portsorch.cpp
- tests/mock_tests/portsorch_ut.cpp
**What I did**
According to the current pfcwd detection logic on certain platforms, when wd fires, we create an ingress zero pool, ingress zero profile, egress zero pool, egress zero profile (if not already created) and then attach the ingress zero profile to the ingress pg and egress zero profile to the egress queue. As a result traffic ingressing that port/pg and egressing that port/queue will get dropped. 
The current changes are done to avoid dropping traffic that is ingressing the port/pg that is in storm. The code changes in this PR avoid creating the ingress zero pool and profile and not attach any zero profile to the ingress pg when pfcwd is triggered
Modified the pfcwd func tests (Azure/sonic-mgmt#5665) and …
> [201911][pfcwd] Avoid ingress drop by not attaching zero profiles when pfc storm is detected

- tests/dvslib/dvs_common.py
**What I did**
Increase the default timeout for PollingConfig to 20 seconds
Many VS tests are flaky due to DB entries not being populated quickly enough.
> [vstest]: Increase PollingConfig default timeout

- portsyncd/linksync.cpp
- tests/test_portchannel.py
**What I did**
Ignore netlink DELLINK messages if port has master, this is applicable to the case where port was part of VLAN bridge or LAG.
Netlink messages handler in portsyncd was ignoring all messages that had master.
Therefore we ignored messages on interfaces that belong to LAG (not only interfaces belong to bridge as intended).
The result was "netdev_oper_status" down in PORT_TABLE in state DB for port which is part of LAG although it is actually up.
Check "netdev_oper_status" in PORT_TABLE in state DB for port which is part of LAG.
> Update netlink messages handler

- orchagent/muxorch.h
What I did: Added soc_ipv4 and cable_type as optional attributes in muxorch.
Why I did it: cable_type field in MUX_CABLE table was throwing parse errors
How I did it: adding soc_ipv4 and cable_type wo mux_cfg_request_description
> [muxorch] Handling optional attributes in muxorch

- orchagent/p4orch/acl_table_manager.cpp
- orchagent/p4orch/tests/acl_manager_test.cpp
- orchagent/p4orch/tests/wcmp_manager_test.cpp
- tests/p4rt/test_l3.py
- tests/p4rt/test_p4rt_acl.py
Signed-off-by: Yilan Ji [yilanji@google.com](mailto:yilanji@google.com)
**What I did**
Lazy UDF match creation, create once the first ACL table with UDF is created in P4Orch
Temp solution for [issue](https://github.com/Azure/sonic-buildimage/issues/10410).  
Warm reboot in P4Orch needs to be addressed as the intent view is applied not the programmed view.
> [P4Orch] Lazy UDF match creation to avoid failure during warm reboot

- .azure-pipelines/build-docker-sonic-vs-template.yml
- .azure-pipelines/build-template.yml
- .azure-pipelines/test-docker-sonic-vs-template.yml
- azure-pipelines.yml
**What I did**
1. Use common lib pipeline instead of sonic image pipeline.
2. Use ArtifactStagingDirectory for download to avoid using old artifacts.
1. common lib pipeline has a less failure rate. Because it only builds some third-party packages.
2. ArtifactStagingDirectory will be reset before every job. It will avoid using out-of-date dependencies.
> [ci] Change artifact reference pipeline to common lib pipeline.

- orchagent/aclorch.cpp
- orchagent/aclorch.h
- tests/mock_tests/aclorch_ut.cpp
**What I did**
This PR is derived from #2205
Fix https://github.com/Azure/sonic-buildimage/issues/10425
We were seeing ACL table creation failure on some platform because `action_list` is mandatory, while the `action_list` is not provided by `aclorch`.
```
Apr  1 01:24:11.702608 str2-7050cx3-acs-03 ERR swss#orchagent: :- validate: Action list for table DATAACL is mandatory
Apr  1 01:24:11.702608 str2-7050cx3-acs-03 ERR swss#orchagent: :- doAclTableTask: Failed to create ACL table DATAACL, invalid configuration
Apr  1 01:24:11.702741 str2-7050cx3-acs-03 ERR swss#orchagent: :- validate: Action list for table EVERFLOW is mandatory
Apr  1 01:24:11.702741 str2-7050cx3-acs-03 ERR swss#orchagent: :- doAclTableTask: Failed to create ACL table EVERFLOW, invalid configuration
Apr  1 01:24:11.702926 …
```
> [ACL] Add default action_list for default ACL table type

- tests/conftest.py
- tests/test_warm_reboot.py
**What I did**
Cherry pick UT fixing PR from master branch.
> Cherry pick UT fixing PR about warm reboot

- fpmsyncd/routesync.cpp
**What I did**
This is a cherry-pick PR for #2320.
We don't necessarily think it is the right solution, but before we can make Zebra behavior consistent. This change will unblock SONiC tests.
It will be a temporary solution until we converge with FRR/Zebra changes.
> [202205][fpmsyncd] don't manipulate route weight

- fpmsyncd/routesync.cpp
**What I did**
Return the next hop weight obtained from kernel as-is.
Sample next hop weight:
> admin@svcstr-7050-acs-4:~$ ip route show 193.11.248.128/25
> 193.11.248.128/25 nhid 1452 proto bgp src 10.1.0.33 metric 20 
>         nexthop via 10.0.1.61 dev PortChannel103 weight 1 
>         nexthop via 10.0.1.63 dev PortChannel104 weight 1 
>         nexthop via 10.0.1.59 dev PortChannel102 weight 1 
>         nexthop via 10.0.1.57 dev PortChannel101 weight 1 
> 
Some platforms have issue dealing with arbitrary next hop weight values.
> [fpmsyncd] don't manipulate route weight

- neighsyncd/neighsync.cpp
- tests/test_neighbor.py
[neighsync] Ignoring IPv4 link local addresses (#2260)
* [neighsync] Ignoring IPv4 link local addresses
Skipping over writing ipv4 link local neighbors to APPL_DB. This was causing link local neighbors to appear and led to long switchover times during mux state change.
cherry-pick to 202012 version from (#2260)
> [neighsync] Ignoring IPv4 link local addresses (#2260)

- orchagent/tunneldecaporch.cpp
Signed-off-by: Myron Sosyak <myronx.sosyak@intel.com>
After the latest changes in this PR https://github.com/Azure/sonic-swss/pull/2190 an issue was introduced. When the tunnel was deleted the TunnelTermEntries were deleted from ASIC but not from the OA cache. Due to that then the same tunnel is created the TunnelTermEntries are not created as OA has it in local cache.
**What I did**
Fix key generation in removeDecapTunnel
To fix the issue described above.
On SONiC testbed after deployment of t1/t0 topology
```
docker exec -ti swss bash
cp /etc/swss/config.d/ipinip.json deltun.json
sed -i 's/SET/DEL/g' deltun.json
swssconfig deltun.json
swssconfig /etc/swss/config.d/ipinip.json 
```
Check in logs that entries were removed and then created.
```
Jun 10 …
```
> Fix key generation in removeDecapTunnel

- orchagent/crmorch.cpp
**What I did**
Made the if / else if condition in the CRM logic mutually exclusive so that you cannot enter a state where the resource utilization does not change but the counter is constantly reset and the log is spammed with CRM messages. 
If a user sets the "low" value and the "high" value equal to each other (a condition which is possible to be manually configured using the CLI or CONFIG_DB) the log will immediately get spammed with CRM messages because the counter will almost instantly reset even if the utilization does not change because the condition in the `if` statement and the condition in the `else if` statement can be true simultaneously. 
Manually tested by manually configuring a CRM resource `high` and `low` threshold to be equal and …
> [crmorch] Prevent exceededLogCounter from resetting when low and high values are equal

- cfgmgr/buffermgr.cpp
- orchagent/qosorch.cpp
- orchagent/qosorch.h
- tests/mock_tests/qosorch_ut.cpp
- tests/test_qos_map.py
Signed-off-by: bingwang <wang.bing@microsoft.com>
**What I did**
This PR is to update the code for applying switch level `DSCP_TO_TC_MAP`.
After PR https://github.com/Azure/sonic-buildimage/pull/10565, there will be two DSCP_TO_TC_MAP
- DSCP_TO_TC_MAP|AZURE is the default map, which is used at port level and switch level
- DSCP_TO_TC_MAP|AZURE_TUNNEL is used to remap the priority of tunnel traffic in dualtor deployment
To address the issue, an entry `PORT_QOS_MAP|global` will be added into `config_db`
```
"PORT_QOS_MAP": {
"global": {
"dscp_to_tc_map": "AZURE"
}
}
```
The entry will be consumed by `qosorch`, and the specified map will be applied to switch.
This change is to ensure the correct `DSCP_TO_TC_MAP` is applied to switch level.
Verified by a …
> Apply `DSCP_TO_TC_MAP` from `PORT_QOS_MAP|global` to switch level

- cfgmgr/intfmgr.cpp
**What I did**
When proxy_arp is enabled for a VLAN interface in config DB, set the `proxy_arp` kernel parameter in addtion to the `proxy_arp_pvlan` parameter which is already set
If an ARP request target IP has a kernel route that does not point to a VLAN member, setting only `proxy_arp_pvlan` is insufficient to enable proxy ARP functionality.
> [intfmgr]: Set proxy_arp kernel param

- orchagent/vnetorch.cpp
- orchagent/vnetorch.h
- tests/test_vnet.py
**What I did**
Cherry pick of PR https://github.com/Azure/sonic-swss/pull/2337
> [202012] [Overlay] Add BGP profile to Vnet routes

- tests/test_qos_map.py
**What I did**
This PR is to fix `test_qos_map` in vstest.
The test is failing because the entry is created by qos template after PR https://github.com/Azure/sonic-buildimage/pull/11087
```
"PORT_QOS_MAP": {
"global": {
"dscp_to_tc_map": "AZURE"
}
}
```
So we will have the entry initially, and as a result, the assert will fail
```
assert("SAI_SWITCH_ATTR_QOS_DSCP_TO_TC_MAP" not in fvs)
```
This PR fixed the issue by removing the initial assert.
Fix https://github.com/Azure/sonic-swss/issues/2342
This PR is to fix `test_qos_map` in vstest.
Run vstest. Now all passed.
```
collected 9 items …
```
> Fix qos map test in vs test

- orchagent/dtelorch.cpp
[orchagent, DTel]: report session support to set user vrf
What I did
DTel report session support to set user vrf
Why I did it
set user vrf not work under local testing
set user vrf in DTel report session and confirm the DTel report sent out via the user vrf
> [orchagent, DTel]: report session support to set user vrf

- orchagent/aclorch.cpp
- orchagent/aclorch.h
- tests/test_acl.py
**What I did**
This PR is to fix ACL table creation failure for certain types.
We saw `PFCWD` table failed to be created at `EGRESS` stage. The error logs are
```
Jun 21 07:00:03.409283 str2-7050cx3-acs-08 ERR syncd#syncd: [none] SAI_API_ACL:_brcm_sai_create_acl_table:11205 field group config create failed with error Feature unavailable (0xfffffff0).
Jun 21 07:00:03.409738 str2-7050cx3-acs-08 ERR syncd#syncd: [none] SAI_API_ACL:brcm_sai_create_acl_table:298 create table entry failed with error -2.
Jun 21 07:00:03.409738 str2-7050cx3-acs-08 ERR syncd#syncd: :- sendApiResponse: api SAI_COMMON_API_CREATE failed in syncd mode: SAI_STATUS_NOT_SUPPORTED
Jun 21 07:00:03.409780 str2-7050cx3-acs-08 ERR syncd#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_ACL_BIND_POINT_TYPE_LIST: …
```
> [ACL] Support stage particular match fields

- tests/mock_tests/Makefile.am
- tests/mock_tests/mock_orchagent_main.h
- tests/mock_tests/portal.h
- tests/mock_tests/sfloworh_ut.cpp
- tests/mock_tests/ut_saihelper.cpp
Signed-off-by: Andriy Yurkiv <ayurkiv@nvidia.com>
**What I did**
Added Sflow gtest
Improve sflow orcagent coverage 
```
ayurkiv@487e531606e9:/sonic/src/sonic-swss/tests/mock_tests$ ./tests --gtest_filter=SflowOrchTest*
Running main() from /build/googletest-YnT0O3/googletest-1.10.0.20201025/googletest/src/gtest_main.cc
Note: Google Test filter = SflowOrchTest*
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from SflowOrchTest
[ RUN      ] SflowOrchTest.SflowEnableDisable
[       OK ] SflowOrchTest.SflowEnableDisable (46 ms)
[ RUN      ] SflowOrchTest.SflowCreateDelete
[       OK ] SflowOrchTest.SflowCreateDelete (46 ms)
[----------] 2 tests from SflowOrchTest (92 ms total)
[----------] …
```
> [mock_tests] Add Sflow Orch UTs

- orchagent/aclorch.cpp
Create ACL table fails due to incorrect check for supported ACL actions #11235
Fixes https://github.com/Azure/sonic-buildimage/issues/11235
Signed-off-by: rck-innovium <rck@innovium.com>
**What I did**
Fixed error https://github.com/Azure/sonic-buildimage/issues/11235
Egress ACL table creation was failing.
root@sonic-dut:~#config acl add table DATA_EGRESS_IPV4_TEST L3 -s egress
Error:
Jun 23 02:23:09.467384 sonic-dut ERR swss#orchagent: :- validate: Action SAI_ACL_ACTION_TYPE_REDIRECT is not supported on table DATA_EGRESS_IPV4_TEST
Jun 23 02:23:09.467384 sonic-dut ERR swss#orchagent: :- doAclTableTask: Failed to create ACL table DATA_EGRESS_IPV4_TEST, invalid configur
root@sonic-dut:~#config acl add table DATA_EGRESS_IPV4_TEST L3 -s egress
Jun 23 …
> Create ACL table fails due to incorrect check for supported ACL actions

- orchagent/fdborch.cpp
- orchagent/fdborch.h
The issue is that the SWSS_LOG_INFO() uses the mac&, port_alias&, and bv_id& which are invalidated in the storeFdbEntryState().
ASAN report:<details><summary>fdborch</summary>
```bash 
==38==ERROR: AddressSanitizer: heap-use-after-free on address 0x611000293668 at pc 0x556914460329 bp 0x7ffc930d0dc0 sp 0x7ffc930d0db8
READ of size 8 at 0x611000293668 thread T0
#0 0x556914460328 in FdbOrch::clearFdbEntry(swss::MacAddress const&, unsigned long const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) orchagent/fdborch.cpp:203
#1 0x556914461443 in FdbOrch::handleSyncdFlushNotif(unsigned long const&, unsigned long const&, swss::MacAddress const&) orchagent/fdborch.cpp:271
#2 0x55691446302a in FdbOrch::update(_sai_fdb_event_t, _sai_fdb_entry_t const*, …
```
> [fdborch] fix heap-use-after-free in clearFdbEntry()

- cfgmgr/buffermgrdyn.cpp
- cfgmgr/buffermgrdyn.h
- tests/mock_tests/Makefile.am
- tests/mock_tests/buffermgrdyn_ut.cpp
- tests/test_buffer_dynamic.py
**What I did**
This PR is to backport https://github.com/Azure/sonic-swss/pull/2234
Support mock_test infra for dynamic buffer manager and fix issues found during mock test
> [202111] Support mock_test infra for dynamic buffer manager and fix issues found during mock test (#2234)

- cfgmgr/buffermgr.cpp
- orchagent/qosorch.cpp
- orchagent/qosorch.h
- tests/test_qos_map.py
**What I did**
This PR is to cherry-pick https://github.com/Azure/sonic-swss/pull/2314 to `202012` branch after resolving conflicts.
This PR is to update the code for applying switch level `DSCP_TO_TC_MAP`.
After PR https://github.com/Azure/sonic-buildimage/pull/10565, there will be two DSCP_TO_TC_MAP
- DSCP_TO_TC_MAP|AZURE is the default map, which is used at port level and switch level
- DSCP_TO_TC_MAP|AZURE_TUNNEL is used to remap the priority of tunnel traffic in dualtor deployment
To address the issue, an entry `PORT_QOS_MAP|global` will be added into `config_db`
```
"PORT_QOS_MAP": {
"global": {
"dscp_to_tc_map": "[DSCP_TO_TC_MAP|AZURE]"
}
}
```
The entry will be consumed by `qosorch`, and the specified map will be applied to switch.
This change is to ensure the …
> [202012] [cherry-pick] Apply `DSCP_TO_TC_MAP` from `PORT_QOS_MAP|global` to switch level

- orchagent/srv6orch.cpp
- tests/test_srv6.py
uSID (microsid) support in swss/orchagent
-	uSID “action” mapping to end-point behavior and end-point behavior-flavor
-	uSID actions: uN, uA, uDX and uDT
Current srv6orch already has appropriate infrastructure in place. Only missing piece, to support uSID, is actions mapping to end-point behavior and behavior-flavor. This commit is to add that. Related SAI support also already is in place.
swss/tests
-	Add a test-case for uSID "action" in test_srv6.py
Signed-off-by: shitanshu.shah@intel.com
> [orchagent]: srv6orch support for uSID

- cfgmgr/intfmgr.cpp
- orchagent/intfsorch.cpp
- orchagent/intfsorch.h
- orchagent/port.h
- tests/test_interface.py
**What I did**
Add support for IP interface loopback action.
New feature in SONiC.
New VS tests were added.
> Add support for IP interface loopback action

- orchagent/aclorch.cpp
**What I did**
This PR is to cherry-pick #2356 to `202205` branch. The cherry-pick is clean, no conflict is found.
This PR is to fix the issue of adding `mux_acl_rule` into `IngressTableDrop`.
The error log is
```
Jun 25 08:02:37.159020 svcstr-7050-acs-4 ERR swss#orchagent: :- validateAclRuleMatch: Match SAI_ACL_ENTRY_ATTR_FIELD_IN_PORTS in rule mux_acl_rule is not supported by table IngressTableDrop
``` 
PR #2341 added support for different matching field in different stage (INGRESS/EGRESS). For example, `SAI_ACL_ENTRY_ATTR_FIELD_IN_PORTS ` is only supported at `INGRESS` stage.
However, PR #2341 only handled one path for creating ACL table, that is by CONFIG_DB entry.
There is a case that `addAclTable` is directly called from other `orch`, such as `MuxOrch`.  In that case, the stage …
> [202205][cherry-pick] Fix mux_acl_rule adding issue

- lib/asan.cpp
Currently, ASAN sometimes reports the BufferOrch::m_buffer_type_maps and QosOrch::m_qos_maps as leaked. However, their lifetime is the lifetime of a process so they are not really 'leaked'.
This also adds a simple way to add more suppressions later if required.
Example of ASAN report:
```bash
Direct leak of 48 byte(s) in 1 object(s) allocated from:
#0 0x7f96aa952d30 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xead30)
#1 0x55ca1da9f789 in __static_initialization_and_destruction_0 /__w/2/s/orchagent/bufferorch.cpp:39
#2 0x55ca1daa02af in _GLOBAL__sub_I_bufferorch.cpp /__w/2/s/orchagent/bufferorch.cpp:1321
#3 0x55ca1e2a9cd4  (/usr/bin/orchagent+0xe89cd4)
Direct leak of 48 byte(s) in 1 object(s) allocated from:
#0 0x7f96aa952d30 in operator new(unsigned long) …
```
> [asan] suppress the static variable leaks

- tests/conftest.py
**What I did**
Added a new flag to DVS tests
Currently, when running the tests with ASAN-enabled image, leak reports are not generated. The reason is that dvs.destroy() (via 'ctn.remove(force=True)') uses SIGKILL to stop the container. To address this, a new flag is added.
When the new flag is set, the swss processes are gracefully stopped (via SIGTERM).
So ASAN reports can be generated as a result of DVS tests run
Run the tests with --graceful-stop, observe that swss processes are stopped via SIGTERM
> [tests] [asan] add graceful stop flag

- orchagent/vnetorch.cpp
- orchagent/vxlanorch.cpp
**What I did**
Fixed the following memory usage issues:
* [vnetorch] removeBfdSession(): the monitor_addr is invalid after the "nexthop_info_[vnet].erase(endpoint_addr)"
* [vxlanorch] usage of an invalid iterator in updateRemoteEndPointIpRef()
ASAN reports:<details><summary>vnetorch</summary>
```bash
==446==ERROR: AddressSanitizer: heap-use-after-free on address 0x6070003b2d38 at pc 0x7f5c8324b8dd bp 0x7ffe2cfc9660 sp 0x7ffe2cfc8e10
READ of size 4 at 0x6070003b2d38 thread T0
#0 0x7f5c8324b8dc  (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x408dc)
#1 0x7f5c82c6475a in swss::IpAddress::to_string[abi:cxx11]() const (/usr/lib/x86_64-linux-gnu/libswsscommon.so.0+0x2f075a)
#2 0x55699e6c2d9d in VNetRouteOrch::removeBfdSession(std::__cxx11::basic_string<char, std::char_traits<char>, …
```
> [vnetorch] [vxlanorch] fix a set of memory usage issues

- .azure-pipelines/build-docker-sonic-vs-template.yml
- .azure-pipelines/build-template.yml
- .azure-pipelines/test-docker-sonic-vs-template.yml
- azure-pipelines.yml
**What I did**
Cherry-pick some pipeline related PRs:
https://github.com/Azure/sonic-swss/commit/4d6fa42ab97c236d54ce4d36e884ec3e224e65c2 [ci] Change artifact reference pipeline to common lib pipeline. (https://github.com/Azure/sonic-swss/pull/2294)
https://github.com/Azure/sonic-swss/commit/d7b5ff79907b22ed13a120d599eaf7c1ad8b6837 [ci] Use correct branch when downloading artifact. (https://github.com/Azure/sonic-swss/pull/2292)
https://github.com/Azure/sonic-swss/commit/2f1324473001e9fd26c2ed7bbb92fb387732a0d0 [ci] Improve azp trigger settings to automaticlly support new release branch. (https://github.com/Azure/sonic-swss/pull/2289)
> [ci][202106] Use correct branch when downloading artifact.

- orchagent/vnetorch.cpp
Fixed the following memory usage issue:
* [vnetorch] removeBfdSession(): the monitor_addr is invalid after the "nexthop_info_[vnet].erase(endpoint_addr)"
**What I did**
Cherry-pick of https://github.com/Azure/sonic-swss/pull/2352
Only 1 out of 2 fixes is applicable to 202012
To fix memory usage issue
> [202012][vnetorch] fix use-after-free in removeBfdSession()

- cfgmgr/teammgr.cpp
- cfgmgr/teammgr.h
- tests/test_macsec.py
Signed-off-by: Ze Gan <ganze718@gmail.com>, Judy Joseph <jujoseph@microsoft.com>
**What I did**
If a member of portchannel has macsec profile attached in config, enable MACsec on the port before it's been added as a member of portchannel.
Due to some hardware limitation, cannot enable MACsec on a member of portchannel.  
So we enable the macsec on interface first and then add it as part of portchannel.
**Note: This is a work around which will be removed when h/w supports it future releases.**
The approach taken in this PR is 
> In the teamdMgr when an interface is added as part of the LAG, we wait for the macsecPort creation done in SAI and Ingress SA creation complete (if macsec is enabled on the interface)
> The above takes care of config reload, reboot scenario's where …
> [teammgr]: Waiting MACsec ready before doLagMemberTask

- .azure-pipelines/docker-sonic-vs/Dockerfile
**What I did**
Fix: missing sonic-db-cli in docker-sonic-vs image
> Fix: missing sonic-db-cli in docker-sonic-vs image

- orchagent/aclorch.cpp
**What I did**
This PR is to fix the issue of adding `mux_acl_rule` into `IngressTableDrop`.
The error log is
```
Jun 25 08:02:37.159020 svcstr-7050-acs-4 ERR swss#orchagent: :- validateAclRuleMatch: Match SAI_ACL_ENTRY_ATTR_FIELD_IN_PORTS in rule mux_acl_rule is not supported by table IngressTableDrop
``` 
PR #2341 added support for different matching field in different stage (INGRESS/EGRESS). For example, `SAI_ACL_ENTRY_ATTR_FIELD_IN_PORTS ` is only supported at `INGRESS` stage.
However, PR #2341 only handled one path for creating ACL table, that is by CONFIG_DB entry.
There is a case that `addAclTable` is directly called from other `orch`, such as `MuxOrch`.  In that case, the stage dependent matcing field is not added. As a resule, we will see the above error logs.
To address the …
> Fix `mux_acl_rule` adding issue

- orchagent/vnetorch.cpp
- orchagent/vnetorch.h
- tests/test_vnet.py
**What I did**
Add BGP profile support to Vnet routes
If a profile is specified in Vnet routes, it must be reflected in the STATE_DB routes for advertising:
```
HGETALL "ADVERTISE_NETWORK_TABLE|150.62.192.1/32"
1) "profile"
2) "FROM_SLB_ROUTES"
```
With VS tests
> [Overlay] Add BGP profile to Vnet routes

- fpmsyncd/bgp_eoiu_marker.py
- neighsyncd/restore_neighbors.py
**What I did**
Replace py-swsssdk with sonic-swss-common
To deprecate py-swsssdk, need replace it from code.
Pass all UT.
> Replace swsssdk with swsscommon

- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/test_admin_status.py
**What I did**
Orchagent changes for https://github.com/sonic-net/SONiC/pull/916
1. Create host_tx_ready field in state-db during OA init.
2. Set the host_tx_ready to true in STATE-DB PORT_TABLE when both NPU and PHY device Tx is enabled successfully <PHY device status will be ignored for platform without PHY device>. 
3. Set the field 'host_tx_ready' to false in STATE-DB PORT_TABLE when NPU and PHY line side Tx gets muted/disabled which happens during admin shutdown configuration is committed.
xcvrd will be handling "host_tx_ready" change of value event for CMIS complaint modules to bring it to appropriate CMIS state on the CMIS complaint modules.
UT logs attached.
> Orchagent changes for synchronizing npu/phy device Tx in the data path before enabling transceiver<CMIS compliant> Tx.

- orchagent/muxorch.cpp
- orchagent/muxorch.h
- tests/test_mux.py
**What I did**
For SoC IPs of ports in `active-active` cable type, if mux is toggled to standby, still use direct link instead of changing next-hop to the tunnel.
In an `active-active` dualtor setup, changing the nexthop of route to SoC IP to the tunnel will   have the following problem:
If lower ToR is already standby, and somehow the upper ToR decides to toggle itself to standby, the toggle will fail:
linkmgrd decide to toggle to standby --> muxorch disables the SoC IP neighbor and change the route next-hop to the tunnel --> ycabled could not setup gRPC connection.
Add unittest and verify the change on `active-active` testbeds.
> [muxorch] Always use direct link for SoC IPs

- orchagent/portsorch.cpp
- tests/test_evpn_tunnel_p2mp.py
**What I did**
Fixed caching issue when L2MC member is removed. During the L2MC member removal, the local variables are modified but not updated to cache. Since L2MC removal is not updated in cache, the same member being added again will be skipped as duplicate.
To fix the above mentioned issues. Without the fix, the same L2MC member removal and add will not work.
Flapped the remote end point and verified if it L2MC member is created again
> [vxlan]Fixing L2MC vlan member caching issue

- orchagent/saihelper.cpp
**What I did**
- Added support for PHYs that do not have firmware support and would return SAI_STATUS_NOT SUPPORTED when attempting to retrieve SAI_SWITCH_ATTR_FIRMWARE_MAJOR_VERSION
- Removed format check on gearbox_config.json hwinfo string
- Some PHYs (e.g. BCM54182) do not have firmware support and will return SAI_STATUS_NOT SUPPORTED when attempting to retrieve SAI_SWITCH_ATTR_FIRMWARE_MAJOR_VERSION. This should not fail initSaiPhyApi.
- SAI_SWITCH_ATTR_SWITCH_HARDWARE_INFO is defined to be a string but the exact format is vendor specific. Thus, the current format check in initSaiPhyApi should not be present.
Tested on Arista platform with BCM54182 and appropriate PAI driver
> [orchagent]: Enhance initSaiPhyApi

- cfgmgr/macsecmgrd.cpp
- orchagent/macsecorch.cpp
**What I did**
1. Introduce SIGTERM handlers in macsecmgrd.
- When the macsecmgrd exit with signal SIGTERM, all existing MACsec objs will clean up.
2. Adjust the cleanup order to follow the wpa_supplicant did (Remove Ingress objs firstly and Egress objs then).
When “docker stop”, macsecmgrd need also to cleanup all exiting MACsec objs.
Try "sudo config feature state macsec disabled`, the MACsec objs were removed. 
> [macsecmgr]: Fix cleanup macsec objs if container stop

- .azure-pipelines/gcov.yml
- orchagent/Makefile.am
- orchagent/flex_counter/flex_counter_manager.cpp
- orchagent/flexcounterorch.h
- orchagent/p4orch/tests/Makefile.am
- orchagent/p4orch/tests/fake_flexcounterorch.cpp
- orchagent/p4orch/tests/fake_flowcounterrouteorch.cpp
- orchagent/p4orch/tests/fake_portorch.cpp
- orchagent/p4orch/tests/test_main.cpp
- tests/gcov_support.sh
**What I did**
Enable p4orch unit test for test workflow. This will run the p4orch unit test and sanitizer test. It will also include the p4orch unit test coverage into the swss code coverage.
Today the p4orch unit test does not run. And the coverage data is not included.
Presubmit run.
> Enable p4orch unit test for test workflow.

- orchagent/vnetorch.cpp
**What I did**
Cherry pick change from master for handling delete case - [code ](https://github.com/Azure/sonic-swss/blob/master/orchagent/vnetorch.cpp#L629)
Align with master and avoid repeated delete operation if object does not exists
> [201911] Handle delete case for object not found

- orchagent/portsorch.cpp
- tests/test_evpn_fdb_p2mp.py
**What I did**
Fixed the missing vlan member update notification when the Vlan member add is from remote endpoint in P2MP scenario.
Without this notification, type 2 entries which are stored in a cache will not be pushed to SAI. 
https://github.com/Azure/sonic-swss/blob/419ab1baaa95c2dd4c637f17212649944c961b2c/orchagent/fdborch.cpp#L1202
Added UT to verify this scenario
> [EVPN]Fix missing Vlan member update notification in P2MP scenario

- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/mock_tests/portsorch_ut.cpp
**What I did**
Expose supported FEC modes to `STATE_DB.PORT_TABLE|<port>.supported_fecs`.
The orchagent calls `get_port_attribute` to get attribute `SAI_PORT_ATTR_SUPPORTED_FEC_MODE` during initialization and then records it into internal data.
- By default, the supported FEC modes will be returned by SAI and exposed to `STATE_DB`. Eg. `rs,none` means only `rs` and `none` is supported on the port.
- The orchagent will check whether the FEC mode is supported on the port before calling the SAI API to set it.
- The CLI will check whether the FEC mode is in `supported_fecs` before setting FEC mode on a port to the `CONFIG_DB`
- In case the SAI API does not support any FEC mode on the port, `N/A` will be exposed to `STATE_DB`
- The orchagent will deny any FEC setting and prints log.
- The CLI …
> [portsorch] Expose supported FEC modes to STABE_DB and check whether FEC mode is supported before setting it

- orchagent/saihelper.cpp
**What I did**
Revert change from https://github.com/Azure/sonic-swss/pull/2367 which increases count associated with SAI_SWITCH_ATTR_SWITCH_HARDWARE_INFO by 1, as well as the memset.
Original intention of this change was to accommodate sairedis behaviour when copying null-terminated string; original behaviour is that the null-terminator would not be copied and so receiver of the hwinfo (PAI) would see non-null terminated string.
Reverting this change so that old behaviour is maintained and PAI driver is responsible for not relying on string to be null terminated.
> Revert hwinfo count change

- orchagent/muxorch.cpp
- orchagent/orchdaemon.cpp
**What I did**
Change orch list to make sure mux_orch and mux_cb_orch are placed after tunnel_decap_orch
handlePeerSwitch returns false because mux tunnel not yet created, and that results in create_nh_tunnel failure.
This moves ports into error state.
Verified that after changing the order ports don't move to error state.
Creating a new PR for #2113 
PR #2114 has already been merged into 202012 branch
> [DualToR] Handle race condition between tunnel_decap and mux orchestrator

- orchagent/intfsorch.cpp
- orchagent/intfsorch.h
- orchagent/neighorch.cpp
**What I did**
Changed interface and neighbor orch code in orchagent which handle updates from Chassis DB for system interface and remote neighbors. Fixes https://github.com/Azure/sonic-buildimage/issues/11290
If an update from the Chassis DB for a system interface or a remote neighbor is received prior to receiving an update for the creation of the SYSTEM LAG or SYSTEM_PORT - the current code incorrectly treats this as an update from the local asic and ignores it. As a result the SYSTEM_INTERFACE or the Remote neighbor is not creating when this specific sequence of updates are received.
This change correctly verifies that an update is from the local asic before ignoring it.
Prior to the fix - adding a the system_interface to the Chassis DB before …
> Fix for System interface for remote asic LAG not getting created if received prior to SYSTEM_LAG creation from Chassis DB

- orchagent/p4orch/tests/fake_portorch.cpp
- orchagent/port.h
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/conftest.py
- tests/test_port_an.py
- tests/test_port_lt.py
Signed-off-by: Dante Su <dante.su@broadcom.com>
**What I did**
1. Add Link-Training support to portsorch, while Gearbox is not in the scope
2. Add support for remote speed advertisement
3. Add support for capability checker
1. In the case of DAC, static pre-calibrated pre-emphasis is rarely available on SONIC, as most of the ODM are expecting this to be  done dynamically at runtime via link-training, hence we'll need this feature to improve the link quality
2. Help users identify the cause of autoneg link failure
3. Avoid un-necessary SAI calls for autoneg and link-training controls if this feature is not supported
1. Manual test
2. Ran the Unit-tests to the corresponding changes
This is a subsequent PR of #2149 
HLD: …
> portsorch: initial support for link-training

- orchagent/Makefile.am
- orchagent/aclorch.cpp
- orchagent/orch.h
- orchagent/orchdaemon.cpp
- orchagent/pfc_detect_clounix.lua
**What I did**
Support for platforms based on Clounix Networks' device
Support for platforms based on Clounix Networks' device
Have verified on the hardware device
> Support for platforms based on Clounix Networks' device

- .azure-pipelines/test-docker-sonic-vs-template.yml
**What I did**
Group 20 tests together in pytest.
Hope this can improve the speed.
Presubmit test
> Improve pytest speed by grouping 20 tests together.

- orchagent/qosorch.cpp
- orchagent/qosorch.h
- tests/mock_tests/mock_orchagent_main.h
- tests/mock_tests/qosorch_ut.cpp
**What I did**
Fix issue:
Setting a WRED profile can fail in case
- the current min threshold is greater than the new max threshold
- or the current max threshold is less than the new min threshold
for any color and at any time.
Eg.
- Current min=1M, max=2M, new min=3M, new max=4M
- The min threshold is set first, so current max (2M) < new min (3M), which violates the condition
This is because there can be only one attribute in each SAI SET operation,
which means the vendor SAI does not understand the whole information of the new attributes and can only perform the sanity check against each SET operation.
Fix the issue
Manual test and mock test.
The fix
The thresholds that have …
> [QoS] Fix issue: the WRED profile can not be set if current min > new max or current max < new min

- orchagent/muxorch.cpp
- orchagent/muxorch.h
Orchagent was not programming neighbor IP to h/w L3 host table during
initialization because they were set as Standby. When the links became
active, SoC IPs were added to the skip_neighbors_ list and never
programmed. fix:
- Added public method MuxCable::getSkipNeighborsSet()
- check if nbr is in skip_neighbors_ when checking if cable is Active
related to: https://github.com/sonic-net/sonic-swss/pull/2369
> [muxorch] return true if the nbr IP is in the skip_neighbors list

- orchagent/muxorch.cpp
**What I did**
Set internal class variable to set to STANDBY.
Default value was set to INIT and not modified after setting to standby. 
Fix for https://github.com/sonic-net/sonic-buildimage/issues/11654
> [MuxOrch] Set internal class state to reflect the actual state

- orchagent/orchdaemon.cpp
- orchagent/pfcactionhandler.cpp
- orchagent/pfcactionhandler.h
- orchagent/pfcwdorch.cpp
- orchagent/pfcwdorch.h
- orchagent/qosorch.cpp
- orchagent/switchorch.cpp
- orchagent/switchorch.h
- tests/mock_tests/portsorch_ut.cpp
**What I did**
This is changing PFCWD recovery from SONIC based to SAI/SDK DLR_INIT way.
Existing SONIC scheme will not work for upcoming BRCM devices starting with TH3.
Verified this to be working fine on HW platform where the issue was seen. Added sonic-mgmt test case to handle this scenario.
> [sonic-swss] : PFCWD recovery changes using DLR_INIT

- orchagent/intfsorch.cpp
**What I did**
delete invalid if condition
Line 778 expression if always false because "else if" condition matches previous condition at line 731
Run test
> Delete invalid if condition in intfsorch.cpp

- orchagent/macsecorch.cpp
- orchagent/macsecorch.h
- orchagent/p4orch/tests/fake_portorch.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
**What I did**
Set extra MTU for MACsec enabled port.
MACsec frame will expend the packet with MACsec SecTAG, Otherwise if a packet length equals the MTU which will be dropped by SAI port.
Assume 9100 is the MTU, Check by the command `ping -s 9100 10.0.0.57`
> [macsec]: Set MTU for MACsec

- orchagent/fdborch.cpp
- orchagent/fdborch.h
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/mock_tests/Makefile.am
- tests/mock_tests/fdborch/flush_syncd_notif_ut.cpp
- tests/mock_tests/mock_table.cpp
**What I did**
Backport the fdborch fix to properly handle syncd FDB flush notifications. 
```
1. config vlan add 40
2. config vlan member add 40 Ethernet0
On the other side. 
3. sudo ip link add link enp4s0f0 name enp4s0f0.40 type vlan id 40
4. sudo ip link set enp4s0f0.40 up
5. Make sure a fdb entry is learnt. 
root@sonic:/home/admin# fdbshow
No.    Vlan  MacAddress         Port       Type
-----  ------  -----------------  ---------  -------
1      40  7C:FE:90:12:22:EC  Ethernet0  Dynamic
root@sonic:/home/admin# redis-cli -n 6 keys "*FDB*"
"FDB_TABLE|Vlan40:7c:fe:90:12:22:ec"
6. config vlan member del 40 Ethernet0
root@sonic:/home/admin# redis-cli -n 6 keys "*FDB*"
(empty array)
8. config vlan del 40
```
``` …
```
> [FDB] [202012] Fix fbdorch to properly handle syncd FDB FLUSH Notif

- orchagent/muxorch.cpp
- orchagent/muxorch.h
PR #2407 added a check which returned true in isNeighborActive if it is
in the skip_neighbors_ list, but only checked for Mux in Subnet. This
extends that check to Mux Ports and Nexthop Muxes.
> [muxorch] Returning true if nbr in skip_neighbor_ in isNeighborActive()

- .azure-pipelines/build-docker-sonic-vs-template.yml
- .azure-pipelines/build-template.yml
- .azure-pipelines/docker-sonic-vs/Dockerfile
- .azure-pipelines/test-docker-sonic-vs-template.yml
- azure-pipelines.yml
This adds 3 new stages:
* BuildAsan: same as 'Build' but with ENABLE_ASAN=y
* BuildDockerAsan: same as 'BuildDocker' but uses asan-enabled swss and
adds swss-dbg package. It also uses asan-enabled docker-sonic-vs from
the sonic-buildimage ci.
* TestAsan: same as 'Test' but uses asan-enabled docker and publishes
the asan reports if any.
**What I did**
Added new CI stages to run the DVS tests with ASAN and check the ASAN reports.
To utilize ASAN for catching memory usage issues on PR.
Run the CI on my fork
> [ci][asan] add DVS tests run with ASAN

- orchagent/aclorch.cpp
- orchagent/orch.h
- orchagent/saihelper.cpp
**What I did**
Added support in SWSS code to run SONiC on top of Xsight Platform. 
* Added a new define for xsight platform
* use increased timeout for init response from syncd
* enabled mirrorv6  + disabled mirror combined v6 table for xsight platform
In order to run SONiC on Xsight based platforms. 
Running Community testing on Xsight platform 
> [orchagent|new vendor support] Added support for Xsight platform

- orchagent/bufferorch.cpp
- orchagent/flexcounterorch.cpp
- orchagent/flexcounterorch.h
- orchagent/p4orch/tests/fake_flexcounterorch.cpp
- orchagent/p4orch/tests/fake_portorch.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/mock_tests/portsorch_ut.cpp
- tests/mock_tests/routeorch_ut.cpp
- tests/test_buffer_traditional.py
- tests/test_flex_counters.py
- tests/test_pg_drop_counter.py
- tests/test_watermark.py
commit 6f1199afc3458e526c26b5d7c498fdaf810fbaca
Author: Shlomi Bitton <shlomibi@nvidia.com>
Date:   Sun Jan 2 16:55:58 2022 +0000
Filter unconfigured ports buffers queue/pg counters configurations on init.
If no buffer configurations available, no counters will be created.
Allow creating/removing counters on runtime if buffer PG/Queue is created or removed.
New UT added to verify new flow.
Propagating https://github.com/Azure/sonic-swss/pull/2143 with resolved merge conflicts
Depends on: https://github.com/Azure/sonic-utilities/pull/2239
**What I did**
Currently in SONiC all ports queue and pg counters are created by default with the max possible amount of counters.
This feature change …
> [counters] Improve performance by polling only configured ports buffer queue/pg counters

- tlm_teamd/Makefile.am
- tlm_teamd/main.cpp
Avoid processing portchannel subinterfaces in teamd
**What I did**
Fixes #11218  : https://github.com/Azure/sonic-buildimage/issues/11218
As per Subinterface HLD, portchannel subinterfaces once provisioned by intfmgrd, will be updated to STATE_DB LAG_TABLE.
Teamd subscribes to STATE_DB LAG_TABLE hence it receives portchannel subinterface events though it is not interested in portchannel subinterface events.
Fix is to filter subinterface events prior to adding to teamd event queue.
Fix for issue #11218 where teamd syslog errors were observed when portchannel subinterfaces were configured  on the system.
Ensured tlm does not add portchannel subinterface STATE_DB LAG_TABLE events to its event queue thus filtering portchannel subinterface events. …
> tlm_teamd: Filter portchannel subinterface events from STATE_DB LAG_TABLE

- orchagent/bufferorch.cpp
- tests/test_port_add_remove.py
**What I did**
This PR replace PR [#2022](https://github.com/Azure/sonic-swss/pull/2022)
Added increasing/decreasing to the port ref counter each time a port buffer configuration is added or removed
Implemented according to the - https://github.com/Azure/SONiC/pull/900
In order to avoid cases where a port is removed before the buffer configuration on this port were removed also
VS Test was added in order to test it. 
we remove a port with buffer configuration and the port is not removed. only after all buffer configurations on this port were 
removed - this port will be removed.
> Dynamic port configuration - add port buffer cfg to the port ref counter

- neighsyncd/neighsync.cpp
- tests/test_neighbor.py
Allow ipv4 link local entries to be programmed to the hardware unless on
a dual-tor setup.
fixing sonic-net/sonic-buildimage#11830
> [neighsyncd] Enabling ipv4 link local entries for non-dualtor

- orchagent/portsorch.cpp
Why I did:
PR: https://github.com/sonic-net/sonic-swss/pull/2400 made change to pass `<string>` as argument to API `setPortFecMode` but did not updated the corresponding gbsyncd API call which is making gbsyncd to fail with below errors
```
Aug 25 19:21:54.446591 str2-xxxx-lc1-3 ERR swss1#orchagent: :- meta_generic_validation_set: SAI_PORT_ATTR_FEC_MODE:SAI_ATTR_VALUE_TYPE_INT32 is enum, but value 1989570112 not found on allowed values list
Aug 25 19:21:54.446591 str2-xxxx-lc1-3 ERR swss1#orchagent: :- setGearboxPortAttr: BOX: Failed to set Ethernet13 port attribute 51
Aug 25 19:21:54.446605 str2-xxxx-lc1-3 ERR swss1#orchagent: :- handleSaiSetStatus: Encountered failure in set operation, exiting orchagent, SAI API: SAI_API_PORT, status: SAI_STATUS_INVALID_PARAMETER
```
How I fixed:
Passed …
> Fix the Fec Mode Setting of gbsyncd

- cfgmgr/nbrmgr.cpp
- tests/test_virtual_chassis.py
**What I did**
Change the Error reporting for API's addKernelRoute, addKernelNeigh from ERR to INFO as the code logic already deletes and retries the creation of Neigh/Route 
For the test **tests/test_virtual_chassis.py::test_chassis_system_neigh** the following change was made 
1. Grouped the neighbor creation,  validation of the DB entry present in local and remote LC into a new function chassis_system_neigh_create()
2. Call this function first with mac_address = "00:01:02:03:04:77", action as "add" to create a new neighbor entry.
3. Call this function again with mac_address = "00:01:02:03:04:05", action as "change" to update the mac_addres of that neighbor entry already created before.
There was sonic-mgmt test failures in multi-asic devices where the Neighbor and …
> Change the log messages in addKernelNeigh/Route from ERROR to INFO

- orchagent/bfdorch.cpp
- tests/test_bfd.py
Manual cherry-pick of https://github.com/sonic-net/sonic-swss/pull/2434
**What I did**
Clean up BFD state_db entries during BFD orch initialization
To avoid having stale state_db entries after config reload. This will result in show bfd summary CLI listing stale information
Added UT to verify it.
> [BFD][202012]Clean up state_db BFD entries on swss restart

- cfgmgr/intfmgr.cpp
**What I did**
When enabling gratuitous ARP, also enable acceptance of untracked neighbor advertisements
For dual ToR devices, this helps keep the neighbor caches of both ToRs in sync since the standby ToR's neighbor solicitation messages are always dropped. By enabling this kernel parameter, we allow the standby to learn neighbor entries using NA messages generated by the active ToR's NS messages.
Do not merge until https://github.com/sonic-net/sonic-buildimage/pull/11929 is merged
> [202012][intfmgr]: Enable `accept_untracked_na` kernel param

- lgtm.yml
- orchagent/bufferorch.cpp
- orchagent/flexcounterorch.cpp
- orchagent/flexcounterorch.h
- orchagent/p4orch/tests/fake_portorch.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/mock_tests/portsorch_ut.cpp
- tests/mock_tests/routeorch_ut.cpp
- tests/test_buffer_traditional.py
- tests/test_flex_counters.py
- tests/test_pg_drop_counter.py
- tests/test_watermark.py
commit 6f1199afc3458e526c26b5d7c498fdaf810fbaca
Author: Shlomi Bitton <shlomibi@nvidia.com>
Date:   Sun Jan 2 16:55:58 2022 +0000
Filter unconfigured ports buffers queue/pg counters configurations on init.
If no buffer configurations available, no counters will be created.
Allow creating/removing counters on runtime if buffer PG/Queue is created or removed.
New UT added to verify new flow.
Propagating https://github.com/Azure/sonic-swss/pull/2143 with resolved merge conflicts
Depends on: https://github.com/Azure/sonic-utilities/pull/2239
**What I did**
Currently in SONiC all ports queue and pg counters are created by default with the max possible amount of counters.
This feature change …
> [202205][counters] Improve performance by polling only configured ports buffer queue/pg counters

- orchagent/fdborch.cpp
Root cause:
When fdb flush was issued after adding a static mac, the mac was deleted due to the flush. Then when we try to remove the static mac, it thrown error and crashed due to the mac not found.
Fix:
Updated fdb flush to flush only dynamic mac.
> [202012] Fix for "orchagent crashed when trying to delete fdb static entry with swssconfig #11046"

- orchagent/aclorch.cpp
- orchagent/aclorch.h
- orchagent/mirrororch.cpp
- orchagent/neighorch.cpp
Signed-off-by: Sakthivadivu Saravanaraj <sakthivadivu.saravanaraj@nokia.com>
**What I did**
Fixed the issues reported in https://github.com/Azure/sonic-buildimage/issues/11457
getNeighborEntry:  This function compares Neighbor alias with nexthop alias. Since the alias for nexthop was modified from systemport name to Inband port name in addNextHop, the alias comparison was failing and  mirror session was deactivated. Modified the getNeighborEntry to  compare the correct alias.
updateSessionDstMac: Modified the code to set the dest mac of the mirror to gMacAddress if it is voq switch
updateSessionDstPort: Set the dest port of the mirror to Rec port if the mirror is ERSPAN mirror
removeRanges: Delete the acl range only if it was created . If the acl entry with mirror action …
> [Everflow/ERSPAN] Set correct destination port and mac address when the nexthop is updated for ERSPAN mirror destination

- cfgmgr/buffermgrdyn.cpp
- orchagent/orch.cpp
- tests/mock_tests/buffermgrdyn_ut.cpp
- tests/mock_tests/qosorch_ut.cpp
**What I did**
Enhance orchagent and buffer manager
- Buffer manager: do not insert buffer queue into cache if the profile is illegal, which prevents an empty string from being inserted into `APPL_DB` during initialization.
- orchagent: handle the case that a field referencing other objects is an empty string.
There had been such logic that was broken by a PR last year.
Enhance the error handling logic.
In most cases, a user will not encounter such scenarios in a production environment because it's the front-ends' (eg. CLI) responsibility to identify the wrong configuration and prevent them from being inserted to `CONFIG_DB`.
However, in some cases, like a wrong `config_db.json` composed and copied to the switch, front-ends …
> Enhance orchagent and buffer manager in error handling

- neighsyncd/restore_neighbors.py
**What I did**
As a part of intf check, wait for the LAG_MEMBER_TABLE to be populated for PortChannel ifaces
Currently, restore_neighbors just checks the `/sys/class/net/{0}/carrier` to determine of if the status is up, but during WR teamd 
starts very early. It creates the netdev from the prev-life state and as i understand sets the carrier state to be based on what was found in the prev-life dump. Ref: https://github.com/sonic-net/sonic-buildimage/blob/master/src/libteam/patch/0008-libteam-Add-warm_reboot-mode.patch#L442 
Checking the sysfs attribute is not a reliable option. Thus during WR because of this false-positive, restore_neighbor sends the ARP/NS very early i.e. before anything else is created, resulting in …
> [restore_neigh] Check STATE_DB before sending ARP/ND pkts for neighbors associated with PortChannel

- .azure-pipelines/build-template.yml
- .azure-pipelines/test-docker-sonic-vs-template.yml
sonic-swss-common lib will add depency to libyang, so need install libyang lib to prevent build and UT break.
Modify azure pipeline to install libyang in azure pipeline steps.
Pass all UT.
Modify azure pipeline to install libyang in azure pipeline steps.
> Install libyang in azure pipeline for swss-common.

- orchagent/Makefile.am
- orchagent/flex_counter/flex_counter_manager.cpp
- orchagent/flex_counter/flex_counter_manager.h
- orchagent/flexcounterorch.cpp
- orchagent/tunnel_rates.lua
- orchagent/vxlanorch.cpp
- orchagent/vxlanorch.h
- tests/test_flex_counters.py
Backport of https://github.com/sonic-net/sonic-swss/pull/1859 
**What I did**
Implemented counters and rates for VxLAN.
To display vxlan counters and to enable counterpoll for tunnel counters.
Verified using vs tests
Added a generic directory structure for flex counter manager. Currently tunnel counters are written for VxLAN but in future it might be expanded to other tunnels which might use the same flex counter infra.
> [202012][VxLAN]VxLAN Tunnel Counters and Rates implementation

- fpmsyncd/fpmlink.cpp
- fpmsyncd/routesync.cpp
- mclagsyncd/mclaglink.cpp
- orchagent/natorch.cpp
- tests/mock_tests/aclorch_ut.cpp
Signed-off-by: maipbui <maibui@microsoft.com>
**What I did**
Replace `memset()` by `memset_s()`
`memset()` is an insecure function that can cause buffer overflow.
> [swss] Replace memset functions

- orchagent/qosorch.cpp
- tests/mock_tests/qosorch_ut.cpp
**What I did**
Do not enforce drop probability for a color whose WRED is disabled.
Currently, there is a logic to enforce the drop probability if it is not explicitly designated for a color. However, the drop probability is not a mandatory attribute. It can incur vendor SAI complaints to set it when the color is disabled.
The logic was introduced from the very beginning (by PR #571) because no drop probability was defined in the QoS template at the time, which is no longer true.
So we will enforce drop probability only if it is not configured and the color is enabled.
Unit test and manual test
> [QoS] Enforce drop probability only for colors whose WRED are enabled

- cfgmgr/portmgr.cpp
- cfgmgr/portmgr.h
- orchagent/portsorch.cpp
Backport https://github.com/sonic-net/sonic-swss/pull/2431 to 202205
**What I did**
> [202205] [portmgr] Fixed the orchagent crash due to late arrival of notif

- neighsyncd/restore_neighbors.py
Backport https://github.com/sonic-net/sonic-swss/pull/2444 to 202205
**What I did**
> [202205] [restore_neigh] Check STATE_DB before sending ARP/ND pkts for neighbors associated with PortChannel

- orchagent/aclorch.cpp
- orchagent/aclorch.h
- orchagent/mirrororch.cpp
- orchagent/neighorch.cpp
* [Everflow/ERSPAN] Set correct destination port and mac address when the nexthop is updated for ERSPAN mirror destination
* [Everflow] Fixed show mirror-session, Acl rule remove failure, orchagent crash
Signed-off-by: Sakthivadivu Saravanaraj <sakthivadivu.saravanaraj@nokia.com>
**What I did**
> [202205][Everflow/ERSPAN] Set correct destination port and mac address when the nexthop is updated for ERSPAN mirror destination

- cfgmgr/buffermgrdyn.cpp
- orchagent/orch.cpp
- tests/mock_tests/buffermgrdyn_ut.cpp
- tests/mock_tests/qosorch_ut.cpp
Cherry-pick #2414 to 202205.
**What I did**
Enhance orchagent and buffer manager
- Buffer manager: do not insert buffer queue into cache if the profile is illegal, which prevents an empty string from being inserted into `APPL_DB` during initialization.
- orchagent: handle the case that a field referencing other objects is an empty string.
There had been such logic that was broken by a PR last year.
Enhance the error handling logic.
In most cases, a user will not encounter such scenarios in a production environment because it's the front-ends' (eg. CLI) responsibility to identify the wrong configuration and prevent them from being inserted to `CONFIG_DB`.
However, in some cases, like a wrong `config_db.json` composed and …
> [202205] Enhance orchagent and buffer manager in error handling (#2414)

- orchagent/aclorch.cpp
- orchagent/bufferorch.cpp
- orchagent/main.cpp
- orchagent/orchdaemon.cpp
- orchagent/portsorch.cpp
- portsyncd/linksync.cpp
- portsyncd/portsyncd.cpp
Signed-off-by: Oleksandr Ivantsiv <oivantsiv@nvidia.com>
**What I did**
DPU supports features subset from Switch SONiC. To allow SWSS to run on DPU the initialization flow was simplified. During the start of the SWSS applications unsupported attributes are not configured. The list of SAI attributes supported by DPU is documented in DASH HLD.
- The precondition is to have the switch type as 'dpu'
- SAI Redis timeouts were extended such as for other switch types
- Only SAI calls are masked, the rest is the same using defaults. It is assumed that the user should not invoke flows/CLI commands which DPU does not support. No extra validation has been added.
To allow the SWSS application to run on DPU.
Run SWSS on DPU platform. Verify that unsupported …
> [DPU] Simplify SWSS initialization to meet DPU requirements.

- orchagent/bufferorch.cpp
- orchagent/flexcounterorch.cpp
- orchagent/flexcounterorch.h
- orchagent/p4orch/tests/fake_flexcounterorch.cpp
- orchagent/p4orch/tests/fake_portorch.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/mock_tests/portsorch_ut.cpp
- tests/mock_tests/routeorch_ut.cpp
- tests/test_buffer_traditional.py
- tests/test_flex_counters.py
- tests/test_pg_drop_counter.py
- tests/test_watermark.py
Reverts sonic-net/sonic-swss#2360
Causing submodule pointer update failure. Revert this once sonic-mgmt tests are available
> Revert "[counters] Improve performance by polling only configured ports buffer queue/pg counters"

- orchagent/flex_counter/flowcounterrouteorch.cpp
- tests/mock_tests/flowcounterrouteorch_ut.cpp
**What I did**
Fix issue: ip prefix of a route flow pattern shall be initialized even if VRF/VNET is not ready
The issue cause a crash:
```
Sep 15 13:44:39.986661 sonic INFO swss#supervisord: orchagent terminate called after throwing an instance of 'std::logic_error'
Sep 15 13:44:39.986661 sonic INFO swss#supervisord: orchagent   what():  basic_string::_M_construct null not valid
```
Manual test and added new unit test.
The flow in which IpPrefix had an uninitialized member, consists of:
1. FlowCounterRouteOrch::addRoutePattern() with 'Vnet1|100.1.1.1/32'
2. Vnet1 does not exist yet, but the logic of addRoutePattern ignores that, assuming default vrf was meant and due to the way parseRouteKeyForRoutePattern works IpPrefix is …
> [orchagent] Fix issue: ip prefix shall be inited even if VRF/VNET is not ready

- orchagent/macsecorch.cpp
- orchagent/p4orch/tests/fake_portorch.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
**What I did**
Set extra MTU for MACsec enabled port.
MACsec frame will expend the packet with MACsec SecTAG, Otherwise if a packet length equals the MTU which will be dropped by SAI port.
Assume 9100 is the MTU, Check by the command `ping -s 9100 10.0.0.57`
Cherry-pick from https://github.com/sonic-net/sonic-swss/pull/2398
> [202205][macsec]: Set MTU for MACsec (#2398)

- lgtm.yml
**What I did**
lgtm build process broken. This PR will fix it.
```
[2022-09-30 18:21:33] [build-stderr] In file included from defaultvalueprovider.cpp:10:
[2022-09-30 18:21:33] [build-stderr] defaultvalueprovider.h:8:10: fatal error: libyang/libyang.h: No such file or directory
[2022-09-30 18:21:33] [build-stderr]     8 | #include <libyang/libyang.h>
[2022-09-30 18:21:33] [build-stderr]       |          ^~~~~~~~~~~~~~~~~~~
[2022-09-30 18:21:33] [build-stderr] compilation terminated.
```
The lgtm.yml change does not take effect in this PR's checker. I manually test it https://lgtm.com/logs/19f4015aec3863d7d4e7d5667cbbc251efd1d0f4/lang:cpp
> [build] add missing package libyang-dev in lgtm.yml

- cfgmgr/intfmgr.cpp
- lgtm.yml
- tests/dvslib/dvs_vlan.py
- tests/test_vlan.py
**What I did**
When enabling gratuitous ARP, also enable acceptance of untracked neighbor advertisements
For dual ToR devices, this helps keep the neighbor caches of both ToRs in sync since the standby ToR's neighbor solicitation messages are always dropped. By enabling this kernel parameter, we allow the standby to learn neighbor entries using NA messages generated by the active ToR's NS messages.
Depends on following PRs for their respective branches:
- https://github.com/sonic-net/sonic-linux-kernel/pull/292
- https://github.com/sonic-net/sonic-linux-kernel/pull/291
Do not merge until https://github.com/sonic-net/sonic-buildimage/pull/11947 is merged
> [intfmgr]: Enable `accept_untracked_na` kernel param

- orchagent/main.cpp
- orchagent/orchdaemon.cpp
- orchagent/orchdaemon.h
- orchagent/p4orch/tests/test_main.cpp
- tests/mock_tests/Makefile.am
- tests/mock_tests/mock_orchagent_main.cpp
- tests/mock_tests/mock_orchagent_main.h
- tests/mock_tests/orchdaemon_ut.cpp
**What I did**
Fix Azure/sonic-buildimage#8162
Moved sairedis record file rotation logic out of flush() to fix issue.
Sairedis record file was not releasing the file handle on rotation. This is because the file handle release was inside the flush() which was only being called if a select timeout was triggered. Moved the logic to its own function which is called in the start() loop.
Ran a script to fill log and verified that rotation was happening correctly.
Signed-off-by: Bryan Crossland bryan.crossland@target.com
>  [orchdaemon]: Fixed sairedis record file rotation

- orchagent/fabricportsorch.cpp
- orchagent/fabricportsorch.h
- orchagent/main.cpp
- orchagent/orchdaemon.cpp
- orchagent/orchdaemon.h
- tests/conftest.py
- tests/test_fabric.py
- tests/virtual_chassis/8/default_config.json
- tests/virtual_chassis/chassis_supervisor.json
This change is enabling collections of fabric link counters as port and queue stats.
Currently only fabric asics can be collected, so collection is disabled for switch asics.
The reasons are that BCM SAI supports up to 256 logical ports, which is not enough
for ports + fabric lanes, and fabric queue counters are not supported by SAI at
this moment.
The following sonic-swss-common PR is required: [PR #551](https://github.com/Azure/sonic-swss-common/pull/551)
sonic-utilities [PR #1860](https://github.com/Azure/sonic-utilities/pull/1860) adds the
corresponding `show fabric counters` CLI command.
> [fabricportsorch] Collect counters for fabric links

- orchagent/main.cpp
- orchagent/orchdaemon.cpp
- orchagent/orchdaemon.h
- tests/mock_tests/Makefile.am
- tests/mock_tests/mock_orchagent_main.cpp
- tests/mock_tests/mock_orchagent_main.h
- tests/mock_tests/mock_sai_switch.cpp
- tests/mock_tests/mock_sai_switch.h
- tests/mock_tests/orchdaemon_ut.cpp
**What I did**
Fix Azure/sonic-buildimage#8162
Moved sairedis record file rotation logic out of flush() to fix issue.
Sairedis record file was not releasing the file handle on rotation. This is because the file handle release was inside the flush() which was only being called if a select timeout was triggered. Moved the logic to its own function which is called in the start() loop.
Ran a script to fill log and verified that rotation was happening correctly.
Signed-off-by: Bryan Crossland bryan.crossland@target.com
> [orchdaemon]: Fixed sairedis record file rotation

- cfgmgr/vlanmgr.cpp
- tests/test_vlan.py
**What I did**
To fix: https://github.com/sonic-net/sonic-buildimage/issues/11924
This PR depends on: https://github.com/sonic-net/sonic-linux-kernel/pull/293
Signed-off-by: Longxiang Lyu <lolv@microsoft.com>
Disable the sysctl parameter `arp_evict_nocarrier` for the host vlan interfaces.
So if its member ports are all down and host vlan interfaces become `NO-CARRIER`, the neighbor learned will not be flushed.
Build image together with the kernel change:
1. verify the sysctl param `arp_evict_no_carrier` for `Vlan1000`
```
0
```
2. check the neighbor learned from `Vlan1000`
```
192.168.0.13 dev Vlan1000 lladdr 82:7b:a1:ac:3d:0c STALE
192.168.0.15 dev Vlan1000 lladdr ea:5e:4b:f2:84:0e STALE
192.168.0.9 dev Vlan1000 lladdr 72:ce:37:c0:39:08 STALE …
```
> [vlanmgr] Disable `arp_evict_nocarrier` for vlan host intf

- orchagent/p4orch/tests/fake_portorch.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/test_vlan.py
**What I did**
Add m_voq_ids to SystemPortInfo to maintain the list of queue ids.
Add two new tables COUNTERS_SYSTEM_PORT_NAME_MAP and
COUNTERS_VOQ_NAME_MAP to enable queuestat to differentiate between
Port Tx queues and Voqs.
Add a new function initializeVoqs that retrieves the number of voqs
for a system port and stores the voq object ids in m_voq_ids
Add code to handle queue type SAI_QUEUE_TYPE_UNICAST_VOQ.
Initialize voqs and populate COUNTERS_SYSTEM_PORT_NAME_MAP in
addSystemPorts function.
Update generateQueueMap to generate queue maps for both Txqs and Voq.
For PHY ports in a voq system both Txqs and Voqs are instantiated. For
Voqs of remote system port, only Voq counters are initialized.
Add support for voq counters.
Modified queuestat …
> Add support for voq counters in portsorch.

- orchagent/crmorch.cpp
- orchagent/crmorch.h
- tests/test_crm.py
**What I did**
Moved ```exceededLogCounter``` from ```CrmResourceEntry``` to ```CrmResourceCounter```.
Some resources (ACL group/table) have few different counters but CRM logic counts number of printed EXCEEDED messages only per resource (per group of counters but not per each counter separately). Sharing the same message counter for few different resource counters causes the problem: when we, for example, configure resources for one counter from the group and all other counters from the same resource group are 0, in such case CRM prints EXCEEDED message for 1st counter, then 2nd counter clears it and prints CLEAR message. As a result CRM will continuously print EXCEED and CLEAR messages.
```
WARNING swss#orchagent: :- …
```
> [202205] [crm] Fix issue with continues EXCEEDED and CLEAR logs for ACL group/table counters

- lgtm.yml
- orchagent/bufferorch.cpp
- orchagent/flexcounterorch.cpp
- orchagent/flexcounterorch.h
- orchagent/p4orch/tests/fake_portorch.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/mock_tests/portsorch_ut.cpp
- tests/mock_tests/routeorch_ut.cpp
- tests/test_buffer_traditional.py
- tests/test_flex_counters.py
- tests/test_pg_drop_counter.py
- tests/test_watermark.py
This reverts commit 8eea92e7f57ac457cc5b4d8cd3e8d8c89e301872.
Signed-off-by: Vadym Hlushko [vadymh@nvidia.com](mailto:vadymh@nvidia.com)
```
commit 6f1199afc3458e526c26b5d7c498fdaf810fbaca
Author: Shlomi Bitton <shlomibi@nvidia.com>
Date:   Sun Jan 2 16:55:58 2022 +0000
Filter unconfigured ports buffers queue/pg counters configurations on init.
If no buffer configurations available, no counters will be created.
Allow creating/removing counters on runtime if buffer PG/Queue is created or removed.
New UT added to verify new flow.
```
Propagating [sonic-swss/pull/2143](https://github.com/sonic-net/sonic-swss/pull/2143) with resolved merge conflicts
[sonic-utilities/pull/2239](https://github.com/sonic-net/sonic-utilities/pull/2239) …
> [counters][202205] Improve performance by polling only configured ports buffer queue/pg counters

- orchagent/aclorch.cpp
- orchagent/aclorch.h
- tests/mock_tests/aclorch_ut.cpp
**What I did**
Cherry-pick the following commits 
commit 910bfd4d17782a059daf2d81deb87673ae6ca58e
Author: bingwang-ms <66248323+bingwang-ms@users.noreply.github.com>
Date:   Sat May 28 03:04:14 2022 +0800
[ACL] Add default action_list for default ACL table type (#2298)
commit 1b8bd94ef7e44f6089fc12efd456a3caa7aafd3f
Author: Ravindranath C K <rck@innovium.com>
Date:   Fri Jun 24 20:20:52 2022 +0530
Create ACL table fails due to incorrect check for supported ACL actions #11235 (#2351)
Signed-off-by: rck-innovium <rck@innovium.com>
> [202111] cherrypick ACL fixes (#2298) and (#2351)

- cfgmgr/teammgr.cpp
Signed-off-by: Andriy Kokhan <andriyx.kokhan@intel.com>
**What I did**
Added a check into addLagMember() whether this new LAG member still exists in the kernel.
During syncd container autorestart scenario, on syncd exit, the host interfaces (tun/tap netdevs) go to the DOWN state and then get removed.
Due to the validation as follows, the teammgr will receive the notification about the port state change (the information will be updated in the state DB and pubsub message sent) but the port state record will not be removed from the state DB on port delete:
https://github.com/sonic-net/sonic-swss/blob/7cc035f93d028ea95488ce54e833d1699e3fd08a/portsyncd/linksync.cpp#L210
Due to this, on port state change notification, the isPortStateOk() will succeed and TeamMgr::addLagMember() …
> [teammgr] Added LAG member check into addLagMember()

- tests/dvslib/dvs_vlan.py
- tests/test_vlan.py
**What I did**
Fix: remove the VLAN interface before removing the VLAN itself
There is a logic in VLAN vs test cases `test_VlanGratArp` and `test_VlanProxyArp` to create a VLAN, a VLAN interface and then remove the VLAN and then check whether the VLAN is removed from SAI.
However, the step to remove the VLAN interface is missed, which causes the VLAN to be referenced and prevents it from being deleted.
Run vs test.
> Fix vs test issue: failed to remove vlan due to referenced by vlan interface

- cfgmgr/buffer_pool_mellanox.lua
**What I did**
Originally, it was assumed the names of all the buffer pools follow the community buffer pool name convention (`{ingress|egress}_{lossless|lossy}_pool`). The heuristic algorithm to identify buffer pools and profiles was designed based on the assumption.
However, some users can define the buffer pool names in other ways, which breaks the logic in the Lua plugin and introduces degradation,
- the pool sizes of those pools can not be generated
- the additional reserved memory for lossy PG can not be calculated
In this PR, the logic is improved to tolerate the case.
Manually and regression test.
It has been covered by regression test and vs test. No new test case is required.
**Details if …
> [Dynamic buffer calculation][Mellanox] Enhance the logic to identify buffer pools and profiles

- tests/conftest.py
**What I did**
Extended DVS test "--graceful-stop" flag to also stop syncd.
So ASAN can generate reports for syncd.
Run the tests with --graceful-stop, observe that the syncd process is stopped via SIGTERM
> [tests] [asan] extend graceful stop flag to also stop syncd

- orchagent/intfsorch.cpp
- orchagent/intfsorch.h
The cleanup code for stale rif counters are now moved to syncd . Earlier as part of fix for issue #2193 the cleanup for stale rif counters was added.
But it could create a race condition between orchagent removes RIF rate counters from DB and lua script fetching them.
So as a fix all such cleanup has been moved to syncd.
**What I did**
Fix for https://github.com/sonic-net/sonic-buildimage/issues/11621
As a past fix which aimed at removing stale rif counters (https://github.com/sonic-net/sonic-swss/pull/2199) , there is a chance of race condition and it leads to lua script reporting error.
To handle this , the rif counters cleanup code(handled in cleanUpRifFromCounterDb) is now called from syncd ( removeCounter ) to avoid such race condition.
The operations in Orchagent …
> swss: Fixing race condition for rif counters

- orchagent/p4orch/gre_tunnel_manager.cpp
- orchagent/p4orch/gre_tunnel_manager.h
- orchagent/p4orch/next_hop_manager.cpp
- orchagent/p4orch/p4orch.cpp
- orchagent/p4orch/p4orch_util.h
- orchagent/p4orch/tests/gre_tunnel_manager_test.cpp
- orchagent/p4orch/tests/mock_sai_next_hop_group.h
- orchagent/p4orch/tests/next_hop_manager_test.cpp
- orchagent/p4orch/tests/wcmp_manager_test.cpp
- orchagent/p4orch/wcmp_manager.cpp
- orchagent/p4orch/wcmp_manager.h
- orchagent/response_publisher_interface.h
- tests/p4rt/l3.py
- tests/p4rt/test_l3.py
Upstream new development on p4orch:
1. Reference count bug fix in wcmp manager.
2. New update in gre tunnel manager.
3. Bulk support in wcmp group member.
Co-authored-by: Runming Wu [runmingwu@google.com](mailto:runmingwu@google.com)
Co-authored-by: Yilan Ji [yilanji@google.com](mailto:yilanji@google.com)
Co-authored-by: Manali Kumar [manalikumar@google.com](mailto:manalikumar@google.com)
> New P4Orch development.

- orchagent/dash/dashorch.cpp
**What I did**
Added SAI_ENI_ATTR_VM_UNDERLAY_DIP and SAI_ENI_ATTR_VM_VNI attributes to support inbound routing flow
Loaded DASH configuration referenced in https://github.com/sonic-net/sonic-mgmt/pull/6735 and verified that SAI_ENI_ATTR_VM_UNDERLAY_DIP and SAI_ENI_ATTR_VM_VNI attributes are added
2022-11-11.18:59:49.362557|c|SAI_OBJECT_TYPE_ENI:oid:0x6d000000000018|SAI_ENI_ATTR_VNET_ID=oid:0x71000000000016|SAI_ENI_ATTR_ADMIN_STATE=false|SAI_ENI_ATTR_VM_UNDERLAY_DIP=ac5c:99c2:30c9:98eb:c617:f88f:7c5c:ea90|SAI_ENI_ATTR_VM_VNI=4321
2022-11-11.18:59:49.364037|c|SAI_OBJECT_TYPE_ENI:oid:0x6d000000000019|SAI_ENI_ATTR_VNET_ID=oid:0x71000000000017|SAI_ENI_ATTR_ADMIN_STATE=false|SAI_ENI_ATTR_VM_UNDERLAY_DIP=50.2.2.2|SAI_ENI_ATTR_VM_VNI=4 …
> [orchagent] Add SAI_ENI_ATTR_VM_UNDERLAY_DIP and SAI_ENI_ATTR_VM_VNI attributes for DASH

- fdbsyncd/fdbsyncd.cpp
- tests/mock_tests/database_config.json
This PR is part of the following HLD:
Persistent loglevel HLD: https://github.com/sonic-net/SONiC/pull/1041
**- What I did**
Deleted the LOGLEVEL_DB.
After the Logger tables moved from the LOGLEVEL_DB to the CONFIG_DB and the jinja2_cache was deleted the LOGLEVEL_DB is not in use.
**- How I did it**
Removed the LOGLEVEL_DB from the SONiC code
**- How to verify it**
All tests were passed
Persistent loglevel HLD: https://github.com/sonic-net/SONiC/pull/1041
> Remove LOGLEVEL DB since is no longer used

- orchagent/dash/dashvnetorch.cpp
- orchagent/dash/dashvnetorch.h
**What I did**
Added SAI_OUTBOUND_CA_TO_PA_ENTRY_ATTR_USE_DST_VNET_VNI value handling to addOutboundCaToPa()
To support DASH_VNET_MAPPING_TABLE:use_dst_vni configuration
Created DASH_VNET_MAPPING_TABLE entry with 'use_dst_vni' configuration
> [dash] add USE_DST_VNET_VNI attribute to CA-to-PA entry

- fdbsyncd/fdbsync.cpp
- What I did
On local MAC learning, update the MAC entry as local then delete the DST entry from the Kernel for remote MAC. This will make sure that FRR doesn't reinstall the remote MAC(#12363)
When installing the static MAC in the kernel set the sticky flag as well. (#12419)
- How I did it
Move the DST entry delete code after the MAC update code.(#12363)
Pass sticky flag to the kernel in fdbsyncd code.((#12419)
- How to verify it
Tested MAC move from remote to local and verified the MAC is local in Kernel.(#12363)
Verified in Kernel that sticky bit is set and the same as advertised by FRR in the network.(#12419)
Signed-off-by: kishore.kunal@broadcom.com
> [Fdbsyncd] Bug Fix for remote to local MAC and Static MAC Adv in EVPN

- orchagent/muxorch.cpp
- tests/test_mux.py
Signed-off-by: Andriy Yurkiv <ayurkiv@nvidia.com>
**What I did**
add SAI_TUNNEL_ATTR_DECAP_TTL_MODE and SAI_TUNNEL_ATTR_DECAP_DSCP_MODE
Need to pass additional SAI attrib. Align encap end decap params
1 **SAI_TUNNEL_ATTR_DECAP_DSCP_MODE** 
Problem:
Long time ago this attribute was defined as “mandatory on create” in SAI API, but at some point it was changed to “optional”.
But MLNX SAI implementation didn’t change it and still expects this attribute to be always provided on tunnel creation.
SONiC “dual ToR” implementation, when it creates IP-in-IP tunnel, does not provide this attribute because it is “optional”.
So we get SAI error for creating tunnel because as mentioned above MLNX SAI implementation still expects this attribute as “mandatory on create”.
Need to always …
> [dual-tor] add missing SAI attribte in order to create IPNIP tunnel

- mclagsyncd/mclaglink.cpp
- mclagsyncd/mclaglink.h
**What I did**
Add centec platform to supported platform list for port isolation group
Centec platform support port isolation group for mclag, but it was not in the supported platforms list
Build image, run regression
> [Centec]for support mclag of centec to configure port isolate-group

- orchagent/muxorch.cpp
- tests/test_mux.py
What I did:
Added a case where if current and previous Mux states
are the same, post a log entry that acknowleges this
change and returns without doing anything.
Why I did it:
Valid state changes such as active-active and
standby-standby were causing error logs
How I tested it:
added a case to check active-active state change
and standby-standby state change.
> [muxorch] Adding case for maintaining current state

- orchagent/portsorch.cpp
* generateQueueMap uses m_portList[port].m_queue_ids.size to allocate m_queueStates in FlexCounterQueueStates. But m_portList[port].m_queue_ids.size is zero for system ports which results in isQueueCounterEnabled crash for system ports. Since we do not have support disable voq counters yet, do not check isQueueCounterEnabled for voqs.
**What I did**
Fix orchagent crash in voq systems with the following backtrace.
gdb) bt
#0  0x000055cbe38f7d2d in std::_Bit_reference::operator bool (this=<optimized out>) at /usr/include/c++/10/bits/stl_bvector.h:87               
#1  std::_Bit_const_iterator::operator* (this=<optimized out>) at /usr/include/c++/10/bits/stl_bvector.h:348
#2  std::vector<bool, std::allocator<bool> >::operator[] (__n=0, this=0x55cbe53688f0) at …
> sonic-swss: Fix orchagent crash in generateQueueMapPerPort.

- tests/test_virtual_chassis.py
**What I did**
The click commands usage is avoided in test_virtual_chassis.py
To fix issue https://github.com/Azure/sonic-buildimage/issues/10246
- Executed vstest for test_virtual_chassis.py with docker-sonic-vs.gz and observed that the VOQ inband port is brought up correctly and tests related to VOQ inband interface pass.
> [vstest][virtual chassis] Removed dvs.runcmd using click commands

- orchagent/p4orch/tests/fake_portorch.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
**What I did**
During port init if AutoNeg is enabled do not do GET oper on `SAI_PORT_ATTR_SPEED` (do not call `getPortSpeed`)
This PR fixes an issue where in some platforms syncd crashes when AutoNeg is enabled and port is oper down.
The crash happens in the warmboot recovery path:
1. In the target image as part of portinit, GET operation on `SAI_PORT_ATTR_SPEED` returns a random value.
4. This random value does not match the speed in the base image.
5. Diff in speed causes syncd comparison logic to attempt to set newly detected speed.
6. Comparison logic crashes in APPLY_VIEW when doing a SET speed operation on port with the new speed.
Why SAI returns random value in GET oper on `SAI_PORT_ATTR_SPEED`:
SAI returns random value as when autoneg is enabled attribute …
> [portinit] Do not call GET on SAI_PORT_ATTR_SPEED when AUTONEG is enabled

- gearsyncd/gearboxparser.cpp
- lib/gearboxutils.cpp
- lib/gearboxutils.h
- orchagent/p4orch/tests/fake_portorch.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/test_gearbox.py
**What I did**
This change adds support for setting tx tap or tuning values on gearbox ports. It uses the SAI attributes such as SAI_PORT_SERDES_ATTR_TX_FIR_PRE1 to communicate with SAI-based gearbox drivers. For the values, they are provided in the format like "system_tx_fir_pre2": [1,1] for an interface from gearbox_config.json. 
We verified that values provided in https://github.com/Azure/sonic-buildimage/pull/10084 are set to the chip with this change.
Added test to tests/test_gearbox.py. The added test will not pass until the following two changes (which should be merged first) are merged:
Support SAI_PORT_ATTR_PORT_SERDES_ID on vs gearbox: https://github.com/Azure/sonic-sairedis/pull/1082
Add gearbox taps to vs gearbox_config.json: …
> [gearbox] Support setting tx taps on gearbox ports

- orchagent/muxorch.cpp
- orchagent/muxorch.h
- tests/test_mux.py
**What I did**
Skip adding ACL for `active-active` ports.
Please refer to the HLD for more details: https://github.com/sonic-net/SONiC/pull/1180
> [muxorch] Skip programming ACL for `active-active` ports

- orchagent/aclorch.cpp
- orchagent/aclorch.h
- tests/test_acl.py
**What I did**
Added checks to ignore the range type qualifier for L3 and L3V6 ACL tables in egress for Broadcom platforms.
There are issues seen when creating Egress L3/L3V6 table in Broadcom platforms. Error returned as "Feature not supported". 
Further analysis shows that range qualifiers seem to part of Ingress ACL in Broadcom and the same does not seem to be supported on the egress side. 
So checks are added to avoid the range qualifier in egress side for Broadcom platforms.
**Without changes:**
_* Created egress L3/L3 V6 table and ensured that the tables are created without range qualifiers._
"config acl add table -s egress -p Ethernet0 L3_TABLE L3/L3V6"
Dec  7 06:35:00.262994 sonic ERR syncd#syncd: :- processQuadEvent: attr: …
> L3 / L3 V6  Egress ACL table creation failure

- orchagent/bufferorch.cpp
- orchagent/flexcounterorch.cpp
- orchagent/flexcounterorch.h
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/test_flex_counters.py
This PR fixes the following issue:
https://github.com/sonic-net/sonic-buildimage/issues/11219
**What I did**
Align watermark flow with port configuration
correct the queue, watermark and pg-drop counterpoll functionality according to cli commands
the flow before this commit was wrong, when watermark counterpoll was enabled, stats wasn't created in FLEX_COUNTERS_DB
and COUNTERS_DB unless enabling queue counterpoll as well.
in the same way when pg-drop counterpoll was enabled stats weren't added until watermark was enabled.
This is due to the wrong flow where queue and pg maps were generated only when queue or watermark (pg-watermark)
key was detected in flexcountersorch.cpp
manual testing
VS test (updated to reflect current flow) - before this commit …
> align watermark flow with port configuration

- orchagent/aclorch.cpp
**What I did**
Deleting ACL Tables deletes all the associated Rules but it doesn't delete the associated counters.
```
{
"ACL_TABLE_TYPE": {
"CUSTOM_L3": {
"MATCHES": [
"IN_PORTS",
"OUT_PORTS",
"SRC_IP"
],
"ACTIONS": [
"PACKET_ACTION",
"MIRROR_INGRESS_ACTION",
"COUNTER"
],
"BIND_POINTS": [
"PORT"
]
}
},
"ACL_RULE": {
"DATAACL|RULE0": {
"PRIORITY": "999",
"PACKET_ACTION": "DROP",
"SRC_IP": "1.1.1.1/32"
}
}
}
```
config acl add table DATAACL CUSTOM_L3 --description="DATAACL table" --stage=ingress
**Delete the ACL Table:** sudo config acl remove table DATAACL
Flex Counter Object is not removed
```
Dec 16 02:21:04.343646 r-leopard-32 ERR syncd#SDK: [SAI_ACL.ERR] mlnx_sai_acl.c[14363]- mlnx_acl_counter_get:  Failure to get …
```
> [AclOrch] Dereg ACL Counters during ACL_TABLE Del Op

- tests/conftest.py
- tests/test_fdb.py
- tests/test_port_an.py
- tests/test_port_lt.py
- tests/test_warm_reboot.py
**What I did**
This PR is to fix the flaky test cases in vstest.
We frequently saw test failures in PR testing like below
```
test_PortAutoNegWarm failed (1 runs remaining out of 2).
<class 'AssertionError'>
assert 'RESTARTCHECK...unction 267\n' == 'RESTARTCHECK succeeded\n'
RESTARTCHECK succeeded
- profiling:/__w/1/s/common/.libs/libswsscommon_la-consumerstatetable.gcda:Merge mismatch for function 267
[<TracebackEntry /agent/_work/1/s/tests/test_port_an.py:262>]
```
The output is produced by gcov. However, it's collected into the output of `orchagent_restart_check` and leads to test failure because the output is not as expected.
```
- profiling:/__w/1/s/common/.libs/libswsscommon_la-consumerstatetable.gcda:Merge mismatch for function 267
[<TracebackEntry …
```
> [vstest] Only collect stdout of orchagent_restart_check in vstest

- tests/dvslib/dvs_vlan.py
**What I did**
The signature of `wait_for_n_keys` is:
```
def wait_for_n_keys(
self,
table_name,
num_keys,
wait_at_least_n_keys,
polling_config = PollingConfig(),
failure_message = None,
):
```
In the following methods:
`DVSVlan.get_and_verify_vlan_ids`
`DVSVlan.get_and_verify_vlan_hostif_ids`
They pass `polling_config` as the third argument, stored in the parameter `wait_at_least_n_keys` and always evaluated to `True`. This will cause trouble in the vlan or vlan interface removal, `wait_for_n_keys` will always return early as there are always more than expected keys existing in the table. So when next testcase starts, those keys might still exist in the table and fail the next testcase.
Signed-off-by: Longxiang Lyu <lolv@microsoft.com>
Stabilize `test_vlan.py`
**How I …
> Fix `test_vlan.py`

- orchagent/main.cpp
**What I did**
Enable show fabric counters port command:
show fabric counters port
```# show fabric counters port
ASIC    PORT    STATE    IN_CELL    IN_OCTET    OUT_CELL    OUT_OCTET    CRC    FEC_CORRECTABLE    FEC_UNCORRECTABLE    SYMBOL_ERR
------  ------  -------  ---------  ----------  ----------  -----------  -----  -----------------  -------------------  ------------
0       0       up          0           0           4          740      0                  3               305128             3
0       1       up          0           0           4          740      0                314               232123           245
0       2       up          0           0           4          740      0                  0               265156             0
.......
```
Enable show fabric …
> Add show fabric counters port/queue commands

- orchagent/fdborch.cpp
When the FDB entry is updated as dynamic_local, then the FDB entry is updated in the FDB state table.
When the MCLAG synced FDB entries are modified as dynamic_local, then such entries are NOT updated in the FDB state table.
due to this, when these FDB entries are aged out, then the MCLAG module is not initimated about the MAC ageing, hence
there is no way the peer MCLAG node could flush these. it will remain as stale entries in the peer node.
Let both the MCLAG peers(A & B) both have locally learnt as well as synced in FDB entries.
when the MCLAG interface at node A is going down, then the synced in FDB entries in node B will be modified as dynamic_local.
when these entries are aged out at node B, then its flushed in node A as well.
without the fix, the FDB entries will remain stale at …
> Update FDB state table when , MAC entries are modified as dynamic_local.

- orchagent/bufferorch.cpp
- orchagent/bufferorch.h
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/test_virtual_chassis.py
- tests/test_vlan.py
**What I did**
Added support for applying QoS profiles on VoQ on chassis
egress_lossy_profile/egress_lossless_profiles were not applied on remote ports on the DUT and were only available for local ports.
Verified that buffer profiles are applied properly on lossy/lossless VoQs on real HW.
This PR is dependent on -
https://github.com/sonic-net/sonic-swss/pull/1913
https://github.com/sonic-net/sonic-buildimage/pull/12156
https://github.com/sonic-net/sonic-swss/pull/2467
> [bufferorch] : Support for buffer profiles for VoQ on chassis

- orchagent/vrforch.h
- orchagent/vxlanorch.cpp
- orchagent/vxlanorch.h
- tests/evpn_tunnel.py
- tests/test_evpn_l3_vxlan.py
- tests/test_evpn_l3_vxlan_p2mp.py
**What I did**
Updated handling of VRF_VNI mapping and VLAN_VNI mapping for same VNI ID
When a VNI (L3 VNI) is mapped to VRF,  corresponding VNI (L2 VNI) to Vlan mapping is not required.
Updated VxLAN Orchagent code to remove Vlan-VNI mapping entry when VRF is mapped to same VNI.
Also Re-add Vlan-VNI mapping entry when VRF-VNI mapping for same VNI is removed.
> Updated handling of VRF_VNI mapping and VLAN_VNI mapping for same VNI ID

- orchagent/dash/dashvnetorch.cpp
- orchagent/dash/dashvnetorch.h
**What I did**
When adding a VNET map entry, if the VNET doesn't yet exist, defer the operation and retry it later.
Currently, adding a VNET map before the corresponding VNET causes an orchagent crash.
1. Copy the SWSS package with these changes and install to a testbed
2. Set orchagent log level to INFO
3. Use `swssconfig` to apply a DASH config with only a VNET mapping table
4. Check that orchagent doesn't crash, and the following logs are seen in the syslog:
```
INFO swss#orchagent: :- addVnetMap: Not creating VNET map for Vnet2:20.2.2.2 since VNET Vnet2 doesn't exist
```
5. Use `swssconfig to apply a DASH config with a VNET table matching the original VNET mapping table
6. Check that orchagent …
> [DASH] Add retry logic for VNET mapping table

- cfgmgr/intfmgr.cpp
**What I did**
Ignores errors on the set MTU command for subinterface when the subinterface state is not OK.
A race condition between the portmgrd and the intfmgrd sometimes causes running a set MTU command on a deleted subinterface.
The logs and the error:
```
INFO swss#supervisord: intfmgrd Cannot find device "Ethernet32.58"
ERR swss#intfmgrd: :- main: Runtime error: /sbin/ip link set "Ethernet32.58" mtu "9100" :
INFO swss#supervisord 2022-11-08 05:53:33,057 INFO exited: intfmgrd (exit status 255; not expected)
```
Run the test_loopback_action_reload test and saw no errors in the logs.
> Fixed set mtu for deleted subintf due to late notification

- cfgmgr/coppmgr.cpp
- cfgmgr/coppmgr.h
- tests/mock_tests/Makefile.am
- tests/mock_tests/copp_cfg.json
- tests/mock_tests/copp_ut.cpp
This PR should be merged together with https://github.com/sonic-net/sonic-utilities/pull/2524 and is required to 202205 and 202211.
This PR implements [fastboot] Preserve CoPP table HLD to improve fastboot flow (https://github.com/sonic-net/SONiC/pull/1107).
**What I did**
Modified coppmgr mergeConfig logic to support preserving copp tables contents through reboot. Handle duplicates, overwrites, unsupported keys preserved and new keys. According to https://github.com/sonic-net/SONiC/pull/1107
To shorten dataplane downtime on fast-reboot.
Manual tests (community fast-reboot test)
> Modify coppmgr mergeConfig to support preserving copp tables through reboot.

- cfgmgr/intfmgr.cpp
PR against 202205 based on the following PR: https://github.com/sonic-net/sonic-swss/pull/2571
**What I did**
Ignores errors on the set MTU command for subinterface when the subinterface state is not OK.
A race condition between the portmgrd and the intfmgrd sometimes causes running a set MTU command on a deleted subinterface.
The logs and the error:
> INFO swss#supervisord: intfmgrd Cannot find device "Ethernet32.58"
> ERR swss#intfmgrd: :- main: Runtime error: /sbin/ip link set "Ethernet32.58" mtu "9100" :
> INFO swss#supervisord 2022-11-08 05:53:33,057 INFO exited: intfmgrd (exit status 255; not expected)
Run the test_loopback_action_reload test and saw no errors in the logs.
> [202205] Fixed set mtu for deleted subintf due to late notification

- orchagent/aclorch.cpp
*Deleting ACL Tables deletes all the associated Rules but it doesn't delete the associated counters.
Backport https://github.com/sonic-net/sonic-swss/pull/2574
**What I did**
> [202205] [ACL] dereg acl-rule counters during acl-table del (#2574)

- orchagent/aclorch.cpp
- orchagent/aclorch.h
- orchagent/muxorch.cpp
Signed-off-by: Andriy Yurkiv <ayurkiv@nvidia.com>
**What I did**
For Dual-Tor scenario on standby ports drop packets on the egress stage for mellanox platform only.
Remain old behavior for other platform.
**NOTE**
Currently, it is short-term solution which will be replaced with more generic one
Current SAI ACL implementation drops both data plane and control-plane traffic if rules are installed on ingress stage.
But DualToR expects only data-plane traffic to be dropped, and control-plane should not be affected.
In order to handle this limitation, we will allow traffic to go into ingress port, then handle control plane traffic and drop that traffic on egress ports
Setup Dual-ToR, both Active and Standby should have "healthy" status
**Details if …
> [202205][dual-tor] use 'egress' port for Mellanox platform for ACL rules for standby ToR

- neighsyncd/neighsync.cpp
**What I did**
In some rare cases, kernel neighbor add notifications are received with Mac string as 'none'. This is from the following libnl code:
https://www.infradead.org/~tgr/libnl/doc/api/lib_2addr_8c_source.html
This can cause a neighsyncd crash as below from [here](https://github.com/sonic-net/sonic-swss-common/blob/master/common/macaddress.cpp#L20)
```
Dec 12 07:36:37.149555 ST12-M0 INFO swss#/supervisord: neighsyncd terminate called after throwing an instance of 'std::invalid_argument'
Dec 12 07:36:37.149555 ST12-01M0 INFO swss#/supervisord: neighsyncd   what():  can't parse mac address 'none'
```
Prevent crash by checking if MacString is 'none' during neighbor 'add' operation. 
> [Neighsync] Handle Mac address 'none' during neigh add

- orchagent/notifications.cpp
- orchagent/notifications.h
The switch_id parameter missing in on_switch_shutdown_request() method.
Add missing parameter to on_switch_shutdown_request method.
Pass all UT and E2E test cases.
Add ZMQ based ProducerStateTable and CustomerStateTable.
> Add missing parameter to on_switch_shutdown_request method.

- orchagent/bfdorch.cpp
**What I did**
Add local_discriminator to state DB when bfdorch create_bfd_session. 
For upcoming BFD debugging related CLI, user need to use local_discriminator to specify which BFD session they want to debug. current show bfd CLI does not have this information (the local_discriminator is not in state DB).
Also, this is local_discriminator printed into syslog, user may want to correlate this local_discriminator to BFD session.
with modified code, and modified show bfd python script, the local discriminator can be shown in 'show bfd' cmd:
(show "NA" if there is no local_discriminator in state DB.)
modification for "show bfd" script will be committed separately in another PR.
```
cisco@sonic:/var/tmp$ show bfd sum
Total number of BFD sessions: 1
Peer …
```
> [orchagent]:add local_discriminator  for BFD session to state_db

- orchagent/vnetorch.cpp
- orchagent/vnetorch.h
- tests/test_vnet.py
**What I did**
Added handling of overlay_DMAC, monitoring, adv_prefix, and primary attributes in Vnet config.
new attributes are needed for primary/secondary switching of nexthops of vxlan tunnels
added the config in a test to see if it is processed correctly.
> Added new attributes for Vnet and Vxlan ecmp configurations.

- orchagent/portsorch.cpp
- orchagent/portsorch.h
This pr contains changes from https://github.com/sonic-net/sonic-swss/pull/2467 and https://github.com/sonic-net/sonic-swss/pull/2552.
* Add m_voq_ids to SystemPortInfo to maintain the list of queue ids.
* Add two new tables COUNTERS_SYSTEM_PORT_NAME_MAP and COUNTERS_VOQ_NAME_MAP to enable queuestat to differentiate between Port Tx queues and Voqs.
* Add a new function initializeVoqs that retrieves the number of voqs for a system port and stores the voq object ids in m_voq_ids
* Add code to handle queue type SAI_QUEUE_TYPE_UNICAST_VOQ.
* Initialize voqs and populate COUNTERS_SYSTEM_PORT_NAME_MAP in addSystemPorts function.
* Update generateQueueMap to generate queue maps for both Txqs and Voq.
* For PHY ports in a voq system both Txqs and Voqs are instantiated. For Voqs of remote system …
> swss: Add voq counters.

- fpmsyncd/routesync.cpp
**What I did**
Changes are done to delete those route entries from APPL_DB which have next hop on eth0 or docker0 interface.
This is done to fix the issue https://github.com/sonic-net/sonic-buildimage/issues/12442. 
For more information about root cause and the solution, please see details below
Tested using the following scenario 
- Establish eBGP sessions and advertise default route (IPv4 or IPv6).
- Make sure that default routes exists in kernel, APPL_DB and ASIC_DB as expected.
-Shutdown interfaces such that all the eBGP neighbors that advertised the default route are down.
- Dump the routes in the kernel and make sure that the defautl route has only one next on the "eth0"
- Clear the dynamically learned neighbors using "sonic-clearp ndp" or …
> [routesync] Fix for stale dynamic neighbor

- orchagent/muxorch.cpp
- orchagent/neighorch.cpp
- tests/test_mux.py
What I did: called enable when adding a neighbor in active state
Why I did it: NH routes weren't being updated if they existed in standby state before neighbor is added
> [MuxOrch] Enabling neighbor when adding in active state

- cfgmgr/intfmgrd.cpp
- cfgmgr/portmgrd.cpp
- cfgmgr/vrfmgrd.cpp
- orchagent/qosorch.cpp
- orchagent/qosorch.h
**What I did**
I removed TODO comments that are no longer relevant.
To clean source code, non relevant comments should be cleared from source.
TODOs can be removed from vrfmgrd.cpp, intfmgrd.cpp and portmgrd.cpp as approach was changed and instead of listening to state DB changes, we call function isIntfStateOk() that fetches the information from state DB.
TODO can be removed from qosorch.cpp as there is no plan from SAI to support setting of scheduler group priority.
Run compilation.
> Remove TODO comments that are no longer relevant

- tests/mock_tests/Makefile.am
- tests/mock_tests/warmrestartassist_ut.cpp
- warmrestart/warmRestartAssist.cpp
**What I did**
Fix issue sonic-net/sonic-buildimage#13341 the issue that ARP entry is out of sync between kernel and APPL_DB
In `AppRestartAssist::insertToMap`, in case an entry has been updated more than once with the same value but different from the stored one, keep the state as `NEW`.
Eg.
Assume the entry's value that is restored from the warm reboot is `V0`, the following events received.
1. The first update with value V1 is received and handled by the `if (found != appTableCacheMap[tableName].end())` branch,
- the state is set to `NEW`
- value is updated to V1
2. The second update with the same value V1 is received and handled by this branch
- Originally, the state was set to `SAME`, which is wrong because V1 is different from the stored value V0
- The correct logic should be: set …
> Fix issue #13341 ARP entry can be out of sync between kernel and APPL_DB if multiple updates are received from RTNL

- orchagent/dash/dashaclorch.cpp
- tests/test_dash_acl.py
**What I did**
Before binding an ACL group  to an ENI, make sure that the ACL group contains at least 1 rule. If the group is empty, retry the bind operation later.
Test improvements:
- Use `wait_for*` methods in `DVSDatabase` to verify database contents instead of naively sleeping
- Leverage pytest fixtures for automatic cleanup
Attempting to bind  an empty ACL group to an ENI results in a SAI failure with no opportunity to retry.
- Run `test_dash_acl.py`
> [dash]: Don't attempt to bind empty ACL groups

- orchagent/main.cpp
- orchagent/port.h
- orchagent/portsorch.cpp
- portsyncd/portsyncd.cpp
**What I did**
Fix the following potential risks:
- Uncaught execptions in /src/nvos-swss/orchagent/main.cpp and /src/nvos-swss/portsyncd/portsyncd.cpp
- Uninitialized scalar fields in /src/nvos-swss/orchagent/port.h
- Unchecked return value in /src/nvos-swss/orchagent/portsorch.cpp
- Pointer to local outside scope in /src/nvos-swss/orchagent/portsorch.cpp
**How I did it**
- Add "catch" to the uncaught execptions
- Add initialization value to the uninitialized fields
- Add a check to the unchecked return value
- Delete an unnecessary comma
- Inspection and sanity tests
> Fix potential defects: Uncaught exceptions, Uninitialized scalar, Unchecked return value and Pointer to local outside scope

- orchagent/portsorch.cpp
- orchagent/portsorch.h
Cherry-picking #2484
What I did
During port init if AutoNeg is enabled do not do GET oper on SAI_PORT_ATTR_SPEED (do not call getPortSpeed)
Why I did it
This PR fixes an issue where in some platforms syncd crashes when AutoNeg is enabled and port is oper down. The crash happens in the warmboot recovery path:
In the target image as part of portinit, GET operation on SAI_PORT_ATTR_SPEED returns a random value. This random value does not match the speed in the base image. Diff in speed causes syncd comparison logic to attempt to set newly detected speed. Comparison logic crashes in APPLY_VIEW when doing a SET speed operation on port with the new speed. Why SAI returns random value in GET oper on SAI_PORT_ATTR_SPEED: SAI returns random value as when autoneg is enabled attribute …
> [201811][portinit] Do not call GET on SAI_PORT_ATTR_SPEED when AUTONEG is enabled (#2484)

- orchagent/portsorch.cpp
- orchagent/portsorch.h
Cherry-picking #2484
What I did
During port init if AutoNeg is enabled do not do GET oper on SAI_PORT_ATTR_SPEED (do not call getPortSpeed)
Why I did it
This PR fixes an issue where in some platforms syncd crashes when AutoNeg is enabled and port is oper down. The crash happens in the warmboot recovery path:
In the target image as part of portinit, GET operation on SAI_PORT_ATTR_SPEED returns a random value. This random value does not match the speed in the base image. Diff in speed causes syncd comparison logic to attempt to set newly detected speed. Comparison logic crashes in APPLY_VIEW when doing a SET speed operation on port with the new speed. Why SAI returns random value in GET oper on SAI_PORT_ATTR_SPEED: SAI returns random value as when autoneg is enabled attribute …
> [2020212][portinit] Do not call GET on SAI_PORT_ATTR_SPEED when AUTONEG is enabled (#2484)

- orchagent/bfdorch.cpp
- tests/test_bfd.py
Double commit for same design changes in 202012, PR https://github.com/sonic-net/sonic-swss/pull/2587
**What I did**
add local discriminator to state DB for "show bfd summary/peer" to show it.
For upcoming BFD debugging related CLI, user need to use local_discriminator to specify which BFD session they want to debug. current show bfd CLI does not have this information (the local_discriminator is not in state DB).
Also, this is local_discriminator printed into syslog, user may want to correlate this local_discriminator to BFD session.
with modified code, and modified show bfd python script, the local discriminator can be shown in 'show bfd' cmd:
(show "NA" if there is no local_discriminator in state DB.)
modification for "show bfd" script will be …
> [bfdorch] add local discriminator to state DB

- orchagent/vnetorch.cpp
- orchagent/vnetorch.h
- tests/test_vnet.py
**What I did**
Added support to advertise a different prefix rather than a route prefix. This commit also changes the behavior to create NH group based on primary endpoints. This change doesnt support switchover to endpoint monitoring( custom or otherwise.)
To cater to a use case where a common prefix range can be advertised by multiple routes to avoid BGP route table overload.
Added IPV4 and IPV6 tests
Pushing to 202012 first for urgency.
> custom advertised prefix for primary vxlan tunnel [202012] 

- orchagent/portsorch.cpp
- tests/test_virtual_chassis.py
Added a test case in test_virtual_chassis.py
Signed-off-by: Nathan Wolfe <nwolfe@arista.com>
**What I did**
-Remove newly created ports from the default vlan on VOQ systems.
-Add a test to confirm we're executing `removeDefaultVlanMembers` when a new port is added on a VOQ system.
-When a port is created via create_port SAI call the port may be added to the default vlan, this is undesired.
-On a 7800R3AK-36DM2 linecard with multiple 400G ports I verified that the `TX_TAG_ENABLE` field in `ETPPC_EDITING_PER_PORT_TABLE` was not set for and ports. This confirms that no port is a member of any vlan
Note: I believe we want this change `backported to 202205`
> [voq][chassis] Remove created ports from the default vlan.

- orchagent/muxorch.cpp
**What I did**
Do not use counters for mux ACL
Noticed that with PR https://github.com/sonic-net/sonic-swss/pull/1982 counters are enabled by default. It was not the case earlier.
User won't be able to see it with aclshow and it will waste valuable hardware counter resource.
Master PR: https://github.com/sonic-net/sonic-swss/pull/2643
> Remove counters for Mux ACL

- orchagent/vxlanorch.cpp
- tests/evpn_tunnel.py
- tests/test_evpn_tunnel.py
- tests/test_evpn_tunnel_p2mp.py
**What I did**
Added check in remote VNI add to ensure vxlan tunnel map is created before adding the remote end point.
In some race conditions, the VXLAN_REMOTE_VNI_TABLE arrives before VXLAN_TUNNEL_MAP_TABLE. The below log shows race condition as for VNI 500101 is set seen before vxlan tunnel map entry.
2023-01-18.09:35:21.223861|VXLAN_TUNNEL_MAP_TABLE:vtep101032:map_500100_Vlan100|SET|vlan:Vlan100|vni:500100
2023-01-18.09:35:21.326760|VXLAN_FDB_TABLE:Vlan101:aa:e9:21:5a:48:3b|SET|remote_vtep:30.0.0.2|type:dynamic|vni:500101
2023-01-18.09:35:21.327053|VXLAN_FDB_TABLE:Vlan100:5e:3d:f7:1e:93:f6|SET|remote_vtep:30.0.0.2|type:dynamic|vni:500100
2023-01-18.09:35:21.327079|VXLAN_FDB_TABLE:Vlan100:2e:a1:55:f6:59:2e|SET|remote_vtep:40.0.0.3|type:dynamic|vni:500100 …
> [EVPN]Handling race condition when remote VNI arrives before tunnel map entry 

- tests/test_mux.py
What I did: added sleep after adding/removing neighbors in test_NH
Why I did it: resolve PR failures due to timing issues between adding/deleting neighbors and them being present in the asic_db
> [test_mux] add sleep in test_NH

- cfgmgr/buffermgrdyn.cpp
**What I did**
Remove "TODO" comment which is no longer relevant.
Running CI.
> [Buffer manager] Remove "TODO" comment which is no longer relevant

- orchagent/portsorch.cpp
- tests/test_port_an.py
**What I did**
Allowing advertised interface types to be set even when AN is disabled. The SAI header doesn't restrict this field. In some cases when this field is changed during AN disable, it may not be reflected in SAI leading to errors as seen in the issue below. This will occur when interface type mismatches with advertise interface type and the vendor SAI library has checks.
To fix https://github.com/sonic-net/sonic-buildimage/issues/13414
Added UT to verify
> [autoneg]Fixing adv interface types to be set when AN is disabled

- tests/conftest.py
- tests/dvslib/dvs_hash.py
- tests/dvslib/dvs_pbh.py
- tests/test_pbh.py
**HLD:** https://github.com/sonic-net/SONiC/pull/1101
**What I did**
* Added UT infra for Generic Hash feature
* Aligned PBH tests with Generic Hash UT infra
* Implementation is done as part of Generic Hash feature development
1. Run PBH UTs
* N/A
> [hash]: Add UT infra

- orchagent/main.cpp
…mands (#2522)" (#2612)"
This reverts commit 34995f149a34125f9108473d092c95ed67482af0.
**What I did**
Reverted https://github.com/sonic-net/sonic-swss/commit/34995f149a34125f9108473d092c95ed67482af0 to re-enable fabric counters support. Broadcom SAI 7.1.32 has been integrated into 202205 which fixes the crash problem.
To re-enable fabric counters support.
Loaded image to confirm that syncd no longer crashes.
**Other details**
The corresponding revert against `master` is this PR: https://github.com/sonic-net/sonic-swss/pull/2652. However, the PR against `master` cannot merge until the corresponding Broadcom SAI has the appropriate fix.
> [202205] enable fabric counters support

- orchagent/fdborch.cpp
- orchagent/muxorch.cpp
**What I did**
- When looking up bridge port ID from MAC address, use orchagent's internal FDB cache instead of making a SAI API call
- Add some more logs to MuxOrch
The SAI API will process FDB events immediately/asynchronously. If orchagent is in the middle of another task and an FDB event occurs, orchagent will not process it until after the current task but the SAI API will. If orchagent's current task requires looking up the bridge port ID a MAC address is learned on, the current SAI API call will return a port that is inconsistent with orchagent's current internal state.
> [202012][orchagent]: Get bridge port ID from FDBOrch cache instead of SAI API #2657

- orchagent/main.cpp
- orchagent/orchdaemon.cpp
- orchagent/saihelper.cpp
- orchagent/saihelper.h
- tests/mock_tests/Makefile.am
- tests/mock_tests/portsorch_ut.cpp
- tests/mock_tests/test_failure_handling.cpp
Cherry-pick of https://github.com/sonic-net/sonic-swss/pull/2644
**What I did**
Added logic to invoke SAI failure dump during any SAI programming failure before invoking abort.
To collect necessary dumps in problem state in syncd before abort is called and all processes restarts
Manual verification. Added UT to cover abort scenario as well.
> [202205][sai_failure_dump]Invoking dump during SAI failure 

- orchagent/fdborch.cpp
This PR contains part of the changes from #2657 to the master branch. The rest of the changes from #2657 are in #2658 to the 202012 branch.
**What I did**
When looking up a bridge port OID in the FDB cache, misses are logged at level INFO.
Orchagent does not always process FDB updates first, which means the FDB cache may be incomplete at times. For example, if orchagent learns a new neighbor on a new MAC address, the neighbor update may be processed first, then the FDB update for the new MAC. During neighbor update processing, orchagent may access the FDB cache which has not yet been updated to include the new MAC address.
> [202012]: Reduce log level when FDB cache lookup fails

- orchagent/portsorch.cpp
- tests/mock_tests/mock_sai_bridge.h
- tests/mock_tests/portsorch_ut.cpp
**What I did**
Do not allow to add port to .1Q bridge while router port deletion is not completed.
Adding router port to .1Q bridge is not allowed and will cause to errors in the driver.
Create PortChannel102 and set it as router port.
Make sure PortChannel102 has active neighbors.
Now run the following commands using a shell script (not one by one).
1. config interface ip remove PortChannel102 10.0.0.0/31
2. config vlan add 1000
3. config vlan member add 1000 PortChannel102
Follow the logs and verify addBridgePort is not perfomed until removeRouterIntfs is completed.
Unitest added as well.
This PR fixes issue https://github.com/sonic-net/sonic-buildimage/issues/13714
> Do not allow to add port to .1Q bridge while router port deletion is not completed 

- orchagent/portsorch.cpp
- orchagent/portsorch.h
**What I did**
* Do not add Voq oids to CounterCheckOrch since CounterCheckOrch is not relevant for voqs. Fixed https://github.com/sonic-net/sonic-buildimage/issues/13662 where voq counters stopped working after https://github.com/sonic-net/sonic-swss/pull/2525
To fix the invalid oids messages generated by CounterCheckOrch for voq.
Verified that the invalid port oid messages go away. Verified voq counters.
> swss: Fix Invalid port oid messages generated because of voq counters.

- orchagent/aclorch.cpp
- tests/test_mirror_ipv6_separate.py
**What I did**
Fixed issue #2204 
Community test case "sonic-mgmt/tests/everflow/everflow/test_everflow_per_interface.py::test_everflow_per_interface[ipv6]" 
fails for IPV6 traffic with below error.
```
Feb 15 09:06:44.205490 sonic ERR swss#orchagent: :- validateAclRuleMatch: Match SAI_ACL_ENTRY_ATTR_FIELD_IN_PORTS in rule RULE_1 is not supported by table EVERFLOWV6
Feb 15 09:06:44.206501 sonic ERR swss#orchagent: :- doAclRuleTask: Unknown or invalid rule attribute 'IN_PORTS : Ethernet2,Ethernet3,Ethernet8,Ethernet9'
Feb 15 09:06:44.207624 sonic ERR swss#orchagent: :- doAclRuleTask: Failed to create ACL rule. Rule configuration is invalid
```
Verify the Community Testcase with IPV6 traffic is passing.
RootCause:
ACL rule with …
> [aclorch] Fixed issue #2204.Support IN_PORTS qualifer in MIRRORV6 table.

- orchagent/muxorch.cpp
- orchagent/muxorch.h
- orchagent/neighorch.cpp
- orchagent/neighorch.h
- tests/test_mux.py
**What I did**
The issue is that `MuxOrch::m_syncdNeighbors` assumes all cached zero-mac neighbors have tunnel routes installed. The check before adding tunnel routes ignores the following zero-mac neighbor events.
Let's ensure that, if a zero-mac neighbor is present in `MuxOrch::m_syncdNeighbors`, it has a tunnel route installed.
So let's check the tunnel route install success before adding a neighbor to `MuxOrch::m_syncdNeighbors`.
To fix #2675
If `MuxOrch` is not fully initialized, and there is a `FAILED` neighbor added to kernel, the tunnel route creation will fail. But the subsequent `FAILED` neighbor events cannot trigger tunnel route creation because `MuxOrch::m_syncdNeighbors` caches the first event and regard the tunnel as already installed. …
> [dualtor] Fix neighbor miss when mux is not ready

- orchagent/fdborch.cpp
- orchagent/muxorch.cpp
**What I did**
- When looking up bridge port ID from MAC address, use orchagent's internal FDB cache instead of making a SAI API call
- Add some more logs to MuxOrch
The SAI API will process FDB events immediately/asynchronously. If orchagent is in the middle of another task and an FDB event occurs, orchagent will not process it until after the current task but the SAI API will. If orchagent's current task requires looking up the bridge port ID a MAC address is learned on, the current SAI API call will return a port that is inconsistent with orchagent's current internal state.
> [orchagent]: Get bridge port ID from orchagent cache instead of SAI API

- orchagent/fdborch.cpp
- orchagent/fdborch.h
- tests/mock_tests/fdborch/flush_syncd_notif_ut.cpp
- tests/mock_tests/mock_orchagent_main.h
- tests/mock_tests/ut_saihelper.cpp
**What I did**
Fixed FDB flush for remote MACS in EVPN scenario. Even though FDB MAC is received as dynamic, it would be installed as static in SAI and thus during flush it would not be removed. However SONiC's db when processing the FLUSH event removes all the dynamic macs and thus clearing VXLAN remote mac from cache.
Hence during flush modified logic to check by sai_fdb_type rather than SONiC's type
To avoid Remote VxLAN FDB getting cleared wrongly in flush.
Added UT to verify
> [FDB]Fixing FDB consolidated flush for Remote MACs

- orchagent/aclorch.cpp
- tests/test_mirror_ipv6_separate.py
Reverts sonic-net/sonic-swss#2668
which cause ACL creation failure on Mellanox platform with below err msg. 
2023-03-02T11:25:00.2743784Z E               Mar  2 11:22:51.042274 str2-msn2700-spy-2 ERR syncd#SDK: [ACL.ERR] Failed calculating key blocks - too many keys selected.
2023-03-02T11:25:00.2744673Z E               
2023-03-02T11:25:00.2745732Z E               Mar  2 11:22:51.043026 str2-msn2700-spy-2 ERR swss#orchagent: :- create: create status: SAI_STATUS_FAILURE
2023-03-02T11:25:00.2746583Z E               
2023-03-02T11:25:00.2747724Z E               Mar  2 11:22:51.043196 str2-msn2700-spy-2 ERR swss#orchagent: :- addAclTable: Failed to create ACL table EVERFLOWV6
2023-03-02T11:25:00.2748625Z E               
2023-03-02T11:25:00.2749932Z E               Mar  2 11:22:51.043384 …
> Revert "[aclorch] Fixed issue #2204.Support IN_PORTS qualifer in MIRRORV6 table."

- doc/swss-schema.md
- orchagent/srv6orch.cpp
- orchagent/srv6orch.h
- tests/test_srv6.py
If user doesn't set the sid list type, type will be ENCAPS_RED
What I did
create seglist support to set sid list type
Why I did it
could not set different sidlist type under local testing
set different sidlist type of seg list and confirm it works under local testing
Signed-off-by: link_chiang <link_chiang@edge-core.com>
> [orchagent, SRv6]: create seglist support to set sid list type

- .azure-pipelines/build-template.yml
- azure-pipelines.yml
**What I did**
[Ci] Support to build sonic-swss-common
It is to improve the chance to build successful rate on sonic-swss.
It removes the dependency of the build artifacts of sonic-swss-common in sonic-swss, always uses the latest code of the sonic-swss-common to build it.
> [Ci] Support to build sonic-swss-common

- orchagent/bfdorch.cpp
- tests/test_bfd.py
**What I did**
Add default TOS value when create BFD session, default DSCP value is 46, default ECN is 0. The BFD session configuration will override this default value.
Higher DSCP value is preferred for BFD packet.
Set different TOS value in BFD session configuration, and create BFD session in DUT.
Load the test image with the design change, connect a traffic generator (with BFD protocol support), capture the packet sent out by DUT, check the DSCP and ECN field in the captured packet.
```
cisco@sonic:/var/tmp$ cat bfd.cfg
[
{
"BFD_SESSION_TABLE:default:default:192.168.88.2": {
"tos": "186",
"multihop": "true",
"rx_interval": "1000",
"tx_interval": "1000",
"local_addr": "192.168.88.1"
},
"OP": "SET"
}
]
```
APP_DB dump:
```
 cisco@sonic:/var/tmp$ …
```
> [bfdorch] add default TOS value for BFD session

- orchagent/routeorch.cpp
- orchagent/vxlanorch.cpp
- tests/evpn_tunnel.py
- tests/test_evpn_l3_vxlan.py
- tests/test_evpn_l3_vxlan_p2mp.py
- tests/test_evpn_tunnel.py
- tests/test_evpn_tunnel_p2mp.py
**What I did**
Handling error scenarios for the following cases
1) When route is propagated through FRR but SONiC is yet to process VRF - VNI mapping. The route needs to be skipped
2) When VNI is configured  as L3 in SONiC but misconfigured as L2 in FRR leading to remote IMR add, avoid adding the IMR since the local VLAN VNI map doesn't exist according to the recent updated design.
These scenarios will lead to issues and result in SAI failures which needs to be avoided
Added UT to verify.
> [EVPN]Handling error scenarios during route programming and IMR add

- orchagent/intfsorch.cpp
- orchagent/intfsorch.h
- tests/mock_tests/Makefile.am
- tests/mock_tests/intfsorch_ut.cpp
- tests/mock_tests/orchdaemon_ut.cpp
- tests/mock_tests/test_failure_handling.cpp
Backport https://github.com/sonic-net/sonic-swss/pull/2679
**What I did**
Fix issue: there is no retry while creating a RIF which is in removing state
For following command:
```
config interface ip add Ethernet64 100.0.0.2/24
config interface ip add Ethernet64 3001::2/64
config vrf add Vrf_data
config interface vrf bind Ethernet64 Vrf_data
config interface ip add Ethernet64 100.0.0.2/24
```
`config interface vrf bind` would implicitly remove previous RIF created on Ethernet64 and create a new one. But it could fail intermittently in following flow:
1.  intfsorch got a DEL request for Ethernet0
2. intfsorch found there is a ref to Ethernet0, so it put the request back to the queue
3. intfsorch got a SET request for Ethernet0
4. intfsorch found that rif for Ethernet0 …
> [202205] Fix issue: there is no retry while creating a RIF which is in removing state (#2679)

- orchagent/aclorch.cpp
- orchagent/aclorch.h
- tests/dvslib/dvs_acl.py
- tests/test_acl.py
**What I did**
HLD https://github.com/sonic-net/SONiC/pull/1261
This PR is to update `orchagent` to write ACL table/rule creation status into `STATE_DB`.
Currently, `show acl table` and `show acl rule` commands read ACL table/rule configuration from `CONFIG_DB` directly. We don't know whether the ACL table or rule is created successfully.
We improved `orchagent` to write the status of ACL table/rule into a `STATE_DB` table. 
Add the status of ACL table and ACL rule into `STATE_DB` so that user can tell whether the table or rule is created successfully.
Verified by copying the updated `orchagent` to a testbed and run.
HLD https://github.com/sonic-net/SONiC/pull/1261
> [ACL] Write ACL table/rule creation status into STATE_DB

- orchagent/bufferorch.cpp
- orchagent/bufferorch.h
- orchagent/flexcounterorch.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/test_virtual_chassis.py
* QoS changes for VoQ on chassis
**What I did**
Porting https://github.com/sonic-net/sonic-swss/pull/2465 from master branch
Due to merge conflict
> [bufferorch] : Support for buffer profiles for VoQ on chassis (#2465)

- cfgmgr/intfmgr.cpp
- tests/mock_tests/Makefile.am
- tests/mock_tests/intfmgrd/add_ipv6_prefix_ut.cpp
- tests/mock_tests/intfmgrd/intfmgr_ut.cpp
**What I did**
Handled a race condition in intfmgrd which tries to immediately apply an admin_status SET notif after a DEL causing it to crash
Ignores errors on the set admin_status command for subinterface when the subinterface state is not OK.
This PR reference to older PR that fix the same issue in portmgr: https://github.com/sonic-net/sonic-swss/pull/2431
> Fixed set admin_status for deleted subintf due to late notification

- orchagent/portsorch.cpp
**What I did**
In voq systems, the buffer profiles are defined on sysports.  So the
phy ports do not have buffer queue config and queuesStateVector
built by getQueueConfigurations in flexcounterorch never has phy
ports in voq systems. So in voq systems, always enable egress queue
counters.
Fix https://github.com/sonic-net/sonic-buildimage/issues/14061
Verified egress queue counters and voq counters on both 7800r3ak_36dm2_lc and 7800r3_48cqm2_lc
> 202205:Fix Egress queue counters on voq systems.

- orchagent/muxorch.cpp
- orchagent/muxorch.h
- orchagent/neighorch.cpp
- orchagent/neighorch.h
- tests/test_mux.py
What I did
cherry-pick https://github.com/sonic-net/sonic-swss/pull/2676 into 202211 branch
Why I did it
To fix #2675
UT and verify on testbed.
**What I did**
> [202211][dualtor] Fix neighbor miss when mux is not ready

- cfgmgr/intfmgr.cpp
- tests/mock_tests/Makefile.am
- tests/mock_tests/intfmgrd/intfmgr_ut.cpp
**What I did**
Handled a race condition in intfmgrd which tries to immediately apply an admin_status SET notif after a DEL causing it to crash
Ignores errors on the set admin_status command for subinterface when the subinterface state is not OK.
Unit tests
This PR reference to older PR that fix the same issue in portmgr: https://github.com/sonic-net/sonic-swss/pull/2431
> [202205] Fixed set admin_status for deleted subintf due to late notification

- orchagent/muxorch.cpp
- orchagent/muxorch.h
- orchagent/routeorch.cpp
- orchagent/routeorch.h
- tests/test_mux.py
What I did: added logic to handle when a route points to a nexthop group with mux neighbors. In this case, only one active neighbor, or the tunnel nexthop will be programmed to the ASIC.
Why I did it: having a route with multiple mux neighbors caused a data loop which lead to packet loss when different neighbors were in different states.
How I did it: added logic to update routes when a route is changed, a mux neighbor is changed, or there is a mux state change.
HLD: https://github.com/sonic-net/SONiC/pull/1256
cherry-pick of https://github.com/sonic-net/sonic-swss/pull/2656
> [202012][muxorch] handling multiple mux nexthops for route

- orchagent/orchdaemon.cpp
- orchagent/vnetorch.cpp
- orchagent/vnetorch.h
- tests/test_vnet.py
This PR implements the Vxlan ECMP priority tunnels where route next hop groups are switched based on the state of the next hop monitor session and their priority.
This implementation allows primary and secondary next hop groups which are switched based on the monitor state of the next hops.
Please see the included tests to see what this code would do for detail.
custom monitor-based next-hop groups switchover.
Please see the included test to see what this code would do.
adv prefix parameter-based advertisement is done.
**What I did**
> Custom monitoring based priority tunnels

- orchagent/vnetorch.cpp
- orchagent/vnetorch.h
- tests/test_vnet.py
Added support to handle changing overlay_dmac in Vnet configurations.
**What I did**
Added support to handle Vnet configuration changes such as Overlay_dmac.
In a running system, if the overlay_dmac of a Vnet is changed, this needs to be reflected in the VNET monitor configuration.
Added a unit test.
> overlay_dmac change in Vnet configuration.

- cfgmgr/intfmgr.cpp
- cfgmgr/intfmgr.h
- tests/test_sub_port_intf.py
**What I did**
Fix race condition in sub-interface handling
A sub-interface's becomes admin up in the following scenarios:
1. A port becomes admin up in STATE_DB.LAG_TABLE when there are sub-interfaces created based on it
2. A sub-interfaces is created when the parent port's admin_status is up in APPL_DB.LAG_TABLE
However, it's possible that
- the sub-interfaces have not been created while STATE_DB.LAG_TABLE is updated
- the LAGs, as the parent ports, are still admin-down in APPL_DB.LAG_TABLE when sub-interfaces are created. In this scenario, sub-interfaces will keep admin-down forever.
Fix:
In (2), check LAG's admin status in STATE_DB instead of APPL_DB
The same logic is applied to the MTU setting …
> Fix race condition in sub-interface handling

- orchagent/fdborch.cpp
- orchagent/fdborch.h
- tests/mock_tests/fdborch/flush_syncd_notif_ut.cpp
- tests/mock_tests/mock_orchagent_main.h
- tests/mock_tests/ut_saihelper.cpp
**What I did**
Cherrypick of https://github.com/sonic-net/sonic-swss/pull/2673 to 202205
Fixed FDB flush for remote MACS in EVPN scenario. Even though FDB MAC is received as dynamic, it would be installed as static in SAI and thus during flush it would not be removed. However SONiC's db when processing the FLUSH event removes all the dynamic macs and thus clearing VXLAN remote mac from cache.
Hence during flush modified logic to check by sai_fdb_type rather than SONiC's type
To avoid Remote VxLAN FDB getting cleared wrongly in flush.
Added UT to verify
> [202205][FDB]Fixing FDB consolidated flush for Remote MACs

- orchagent/p4orch/tests/fake_portorch.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
* SYSTEM_LAG_MEMBER_TABLE is updated to carry the member status.
* Pass lag member status to addLagMember so that it can be updated in SYSTEM_LAG_MEMBER_TABLE.
* In doLagMemberTask add code to update lag member status in SYSTEM_LAG_MEMBER_TABLE so that remote linecards can handle the member status.
* Remove the code that ignore collecting/distributing update for members of remote lags.
* Update voqSyncAddLagMember to update the lag member status.
**What I did**
Sync and program remote lag member status.
To fix the issue where remote lag memberships were not updated when the local lag memberships changes.
Verified that the traffic from remote linecards is redistributed to active members when a link goes down.
> sonic-swss: Sync and program remote lag member status.

- cfgmgr/buffer_pool_mellanox.lua
- cfgmgr/buffermgrd.cpp
- cfgmgr/buffermgrdyn.cpp
- cfgmgr/buffermgrdyn.h
- orchagent/bufferorch.cpp
- tests/mock_tests/buffermgrdyn_ut.cpp
- tests/mock_tests/bufferorch_ut.cpp
**What I did**
Enforce the order when the shared headroom pool is enabled.
The current flow to enable the shared headroom pool
1. Configure the shared headroom pool size or over-subscribe ratio
2. Update lossless buffer profiles with `xon == size`
3. Calculate and update the shared headroom pool size.
In step 2, the lossless buffer profiles have been updated to values as if the shared headroom pool is enabled. However, it is enabled only in step 3, which is inconsistent between steps 2 and 3. Therefore, we open the PR to guarantee the order.
The new flow
1. A user configures the shared headroom pool size or over-subscribe ratio
2. The dynamic buffer manager invokes the vendor-specific Lua plugin to calculate the shared …
> Enforce the order when the shared headroom pool is enabled

- orchagent/vnetorch.cpp
- tests/test_vnet.py
When a configuration is added with custom monitoring such that there are no secondary endpoints in the configuration, this does not result in vnet ping session creation. This change fixes that and adds a test.
**What I did**
added a fix.
added a test which emulates this scenario.
> [bugfix] vnet ping missing with secondary endpoints empty in priority routes.

- orchagent/main.cpp
**What I did**
Reverted a change that increased SYNC_OPERATION_RESPONSE_TIMEOUT for DPU.
To remove unneeded workaround. 
Run sonic-mgmt DASH VNET to VNET test.
> [DPU] use default operation response timeout

- orchagent/portsorch.cpp
- tests/dvslib/dvs_vlan.py
- tests/test_port.py
* To avoid data and control packets sharing the same TX queue and possibly leading to control packet losses, pin control traffic to queue 7 by default.
**What I did**
Set default queue for control packets to 7.
To avoid control packets like BGP keepalives from being lost when link utilization becomes 100%
Tested on multiple platorms with ICMP packets to make sure they use TX queue 0
> [portsorch]: Set default hostif TX queue

- orchagent/orchdaemon.cpp
**What I did**
Fix orchagent request missing when logrotate happens.
The sairedis logrotate has been moved into the daemon main select loop. After it finishes, it should not continue, because that will drop the event that has been selected.
> Fix orchagent missing request when logrotate happens.

- orchagent/aclorch.cpp
- orchagent/muxorch.cpp
…
**What I did**
Bind LAG to ACL table in order to guarantee ACL rule coverage if LAG member will be added to LAG after ACL binding
After config reload or reboot due to timing, we often see race condition when port are not yet added to LAG, but egress ACL table group already created and port is bound to this group.
It causes that ACL rules are not working on LAG's members that were added after binding.
Run test:
`py.test dualtor_io/test_normal_op.py::test_normal_op_upstream[active-standby`]
> Dual-ToR][ACL] bind LAG to ACL table in order to guarantee rule coverage if lag menber will be added to LAG after binding

- orchagent/saihelper.cpp
- tests/test_vnet.py
* With VNET routes, the same route can be learned via multiple sources, like via BGP. Handle this special situation gracefully without orchagent crash during both create and remove operations.
* Add a test case to simulate duplicate route creation/removal
**What I did**
> Handle duplicate routes in a graceful manner

- orchagent/routeorch.cpp
- tests/evpn_tunnel.py
- tests/test_evpn_l3_vxlan.py
**What I did**
When multiple routes point to a nexthop group which means the ref count of ngh is more than one, there is an error condition in the removal flow. The original logic is to remove nhg only when ref count becomes zero. However due to the structuring of if else statements, if the nhg count is not zero, the logic fallbacks to removeOverlayNextHops which will also get added to the list of tasks.
Later when bulker logic kicks in, the nexthop group removal will remove the nexthops associated. However the removeOverlayNextHops  will also subsequently try to remove the same nexthops resulting in errors below.
```
Apr 19 11:51:05.323909 anc-ali-t9 NOTICE swss#orchagent: :- removeRoutePost: Remove overlay Nexthop 173.106.106.2@vniVlan30@30@b6:a1:0b:0b:d3:cc,173.108.108.2@vniVlan30@30@c2 …
```
> [EVPN]Fixing nexthop group delete when multiple routes point to the nexthop group

- orchagent/routeorch.cpp
- tests/evpn_tunnel.py
- tests/test_evpn_l3_vxlan.py
Manual cherry-pick of https://github.com/sonic-net/sonic-swss/pull/2744
**What I did**
When multiple routes point to a nexthop group which means the ref count of ngh is more than one, there is an error condition in the removal flow. The original logic is to remove nhg only when ref count becomes zero. However due to the structuring of if else statements, if the nhg count is not zero, the logic fallbacks to removeOverlayNextHops which will also get added to the list of tasks.
Later when bulker logic kicks in, the nexthop group removal will remove the nexthops associated. However the removeOverlayNextHops  will also subsequently try to remove the same nexthops resulting in errors below.
```
Apr 19 11:51:05.323909 anc-ali-t9 NOTICE swss#orchagent: :- removeRoutePost: Remove overlay Nexthop …
```
> [202211][EVPN]Fixing nexthop group delete when multiple routes point to the nexthop group

- orchagent/saihelper.cpp
* Handle SAI_STATUS_TABLE_FULL errors for routes
* Handle SAI_STATUS_ITEM_ALREADY_EXISTS, SAI_STATUS_ITEM_NOT_FOUND and SAI_STATUS_TABLE_FULL errors for nexthops, nexthop groups and neighbors
**What I did**
> [orchagent]: Handle additional SAI error conditions gracefully

- orchagent/vxlanorch.cpp
- tests/test_evpn_tunnel.py
- tests/test_evpn_tunnel_p2mp.py
Fixes https://github.com/sonic-net/sonic-buildimage/issues/14949
**What I did**
Sometime during config reload, EVPN NVO table arrives later than remote VNI table entries. In such scenarios, remote vni entries are ignored and this leads to traffic loss. Added fix to retry instead of ignoring.
```
2023-04-30.14:23:40.528130|VXLAN_TUNNEL_MAP_TABLE:vtep1:map_98_Vlan98|SET|vlan:Vlan98|vni:98
2023-04-30.14:23:40.559594|VXLAN_TUNNEL_MAP_TABLE:vtep1:map_99_Vlan99|SET|vlan:Vlan99|vni:99
2023-04-30.14:23:40.572133|VXLAN_REMOTE_VNI_TABLE:Vlan98:1.1.1.1|SET|vni:98
2023-04-30.14:23:40.572180|VXLAN_REMOTE_VNI_TABLE:Vlan98:1.1.1.2|SET|vni:98
2023-04-30.14:23:40.575208|VXLAN_FDB_TABLE:Vlan98:04:3f:72:f7:2d:52|SET|remote_vtep:1.1.1.2|type:dynamic|vni:98 …
```
> [EVPN]Fixing race condition when EVPN NVO add arrives late

- tests/mock_tests/mux_rollback_ut.cpp
Segmentation fault is observed during SWSS compilation:
```
nazariig@3aac6fa57f5a:/sonic/src/sonic-swss/tests/mock_tests$ ./tests --gtest_filter=MuxRollbackTest*
Running main() from /build/googletest-YnT0O3/googletest-1.10.0.20201025/googletest/src/gtest_main.cc
Note: Google Test filter = MuxRollbackTest*
[==========] Running 14 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 14 tests from MuxRollbackTest
[ RUN      ] MuxRollbackTest.StandbyToActiveNeighborAlreadyExists
Segmentation fault (core dumped)
```
**What I did**
* Fixed segmentation fault
* To resolve SWSS compilation errors
* Compile the SWSS package
```
Starting program: /sonic/src/sonic-swss/tests/mock_tests/tests …
```
> [mux]: Fix UTs segmentation fault

- orchagent/vxlanorch.cpp
- tests/test_evpn_tunnel.py
- tests/test_evpn_tunnel_p2mp.py
This reverts commit 750e0649bfc5144e6dce3cdd20835dabedfe3b50.
Reverts the PR https://github.com/sonic-net/sonic-swss/pull/2756
The fix added breaks the previously added workaround https://github.com/sonic-net/sonic-swss/pull/2626. Hence requesting to revert the fix.
Once we find a proper solution for https://github.com/sonic-net/sonic-buildimage/issues/12361 we need to reintegrate this PR
**What I did**
> Revert "[EVPN]Fixing race condition when EVPN NVO add comes late

- .gitignore
- orchagent/aclorch.cpp
- orchagent/muxorch.cpp
- orchagent/muxorch.h
- orchagent/neighorch.cpp
- tests/mock_tests/Makefile.am
- tests/mock_tests/mock_orchagent_main.h
- tests/mock_tests/mock_sai_api.h
- tests/mock_tests/mux_rollback_ut.cpp
- tests/mock_tests/ut_saihelper.cpp
Depends on https://github.com/sonic-net/sonic-sairedis/pull/1237 being merged first
- Make all SAI API operations needed for switchover idempotent
- Implement rollback when a switchover fails
**What I did**
> [202205][mux]: Implement rollback for failed mux switchovers (#2714)

- orchagent/main.cpp
This reverts commit 506b3608482393ad091049d818c5a0291a2e0d2d.
**What I did**
Revert changes introduced in https://github.com/sonic-net/sonic-swss/pull/2742.
In some corner cases, 60 seconds is insufficient for the "create switch" operation on BF-2.
Run sonic-mgmt tests on DPU
> Revert "[dpu] use default operation response timeout (#2742)"

- orchagent/portsorch.cpp
This fixes an issue with the system initialization of the inband ports.
**What I did**
I removed the variable local_port. Data was being read into it but it was not being used.
This was causing incorrect data to be written to CHASSIS_APP_DB for some ports. Here is an example of what the relevant records look like in the database before this issue was fixed:
admin@cmp218-3:~$ sonic-db-cli CHASSIS_APP_DB keys \*
SYSTEM_LAG_ID_END
SYSTEM_NEIGH||fc00:3000::1
SYSTEM_LAG_ID_START
SYSTEM_NEIGH||1.1.1.3
SYSTEM_NEIGH||1.1.1.1
SYSTEM_NEIGH||fc00:3000::3
SYSTEM_INTERFACE
Some of the keys are malformed.
With the fix this is the result:
admin@cmp218-3:~$ sonic-db-cli CHASSIS_APP_DB keys \* | grep -i IB0
SYSTEM_INTERFACE|cmp218-3|asic0|Ethernet-IB0 …
> Inband ports not being initialized correctly #14520

- orchagent/bufferorch.cpp
- orchagent/bufferorch.h
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/mock_tests/bufferorch_ut.cpp
- tests/mock_tests/portsorch_ut.cpp
**What I did**
This is to backport #2752 to 202211 branch
Optimize QoS operations:
1. Cache queue information to avoid fetching them from SAI every time
- The cache is created when a queue's information is fetched for the first time
- Avoid calling SAI API to fetch queue information if it exists in the cache
- Cache will be cleared for the queues of a certain port when the port is removed
2. Apply buffer items (table: BUFFER_QUEUE, BUFFER_PG, BUFFER_PORT_INGRESS_PROFILE_LIST, BUFFER_PORT_EGRESS_PROFILE_LIST) only if they are updated
- There is only one attribute, profile or profile_list, in the items in all the tables, and the attribute is stored in `BufferOrch::m_buffer_type_maps`, which means we can just check whether the new value is the same as the one stored in the mapping and apply …
> [202211][QoS] Optimize QoS operations of buffer setting and queue information fetching

- cfgmgr/buffer_check_headroom_mellanox.lua
- cfgmgr/buffermgrdyn.cpp
- tests/test_buffer_dynamic.py
**What I did**
Enhance the logic to check maximum headroom exceeding to cover corner scenarios
Currently, the logic to check the maximum headroom exceeding works well when a user changes any buffer configuration in the dynamic buffer model, preventing all problematic configurations from being applied to the ASIC.
However, it can fail when a problematic configuration is `config_db.json` and `config reload` is executed. To cover this scenario, the following actions need to be done:
1. Take the pending PG keys and buffer profiles into account when calculating the maximum headroom
- Existing buffer PGs and buffer profiles can be in the pending queue since there are a large number of notifications needed to be handled during system initialization, which takes time.
2. Take the lossy PG into …
> [Dynamic Buffer Calc] Enhance the logic to check maximum headroom exceeding to cover corner scenarios

- orchagent/bufferorch.cpp
- orchagent/bufferorch.h
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/mock_tests/bufferorch_ut.cpp
- tests/mock_tests/portsorch_ut.cpp
**What I did**
Optimize QoS operations:
1. Cache queue information to avoid fetching them from SAI every time
- The cache is created when a queue's information is fetched for the first time
- Avoid calling SAI API to fetch queue information if it exists in the cache
- Cache will be cleared for the queues of a certain port when the port is removed
2. Apply buffer items (table: BUFFER_QUEUE, BUFFER_PG, BUFFER_PORT_INGRESS_PROFILE_LIST, BUFFER_PORT_EGRESS_PROFILE_LIST) only if they are updated
- There is only one attribute, profile or profile_list, in the items in all the tables, and the attribute is stored in `BufferOrch::m_buffer_type_maps`, which means we can just check whether the new value is the same as the one stored in the mapping and apply to SAI only if it differs.
- For the …
> [QoS] Optimize QoS operations of buffer setting and queue information fetching

- orchagent/aclorch.cpp
- orchagent/aclorch.h
- orchagent/acltable.h
- tests/test_acl_l3v4v6.py
**What I did**
Support a new ACL table type called L3V4V6.
This table supports both v4 and v6 Match types.
Add unit tests for this new ACL table type.
HLD: https://github.com/sonic-net/SONiC/pull/1267
Signed-off-by: Ravi(Marvell) rck@innovium.com
To optimise ACL TCAM usage in capable platforms.
Add unit tests for this new ACL table type.
```
sudo pytest -s test_acl_l3v4v6.py
collected 2 items
test_acl_l3v4v6.py ..
======================= 2 passed, 1 warning in 60.88s (0:01:00) 
```
> Combine v4 and v6 L3 ACL rules on optimized platforms #1267

- orchagent/dash/dashaclorch.cpp
- orchagent/dash/dashorch.cpp
- orchagent/dash/dashrouteorch.cpp
- orchagent/dash/dashvnetorch.cpp
Fix Dash orchagent build issue caused by not include 'saihelper.h'.
**What I did**
Include 'saihelper.h' in all Dash orch.
All dash orch using methods defined in saihelper.h but not include this header file:
if (handle_status != task_success)
{
return parseHandleSaiStatusFailure(handle_status);
}
Manually build orchagent.
> Fix Dash orchagent build issue caused by not include 'saihelper.h'.

- tests/README.md
**What I did**
* Extend the list of required external dependencies with `bridge-utils`
* To fix the issue of missing `brctl` command
* Run `test_fabric.py` test
Test log:
```
======================================================================= test session starts ========================================================================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-0.13.1 -- /usr/bin/python3
rootdir: /root/work/development/ppi/sonic-swss/tests
collected 2 items                                                                                                                                                  
test_fabric.py::TestVirtualChassis::test_voq_switch …
```
> [vstest]: Extend the list of required external dependencies

- tests/conftest.py
- tests/test_mclag_cfg.py
**What I did**
* Fixed DB connection errors in mclag test
* To fix VS test standalone run
1. Run `test_mclag_cfg.py`
Test script:
```
root@r-sonic-vs: ~# cat run_single.sh
#!/bin/bash
IMAGE="docker-sonic-vs:latest"
TEST="${1}"
cd sonic-swss/tests
py.test --force-flaky --log-cli-level=info --imgname=${IMAGE} ${TEST} -vvv
```
Test log:
```
root@r-sonic-vs: ~# ./run_single.sh test_mclag_cfg.py
========================================================================= test session starts =========================================================================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-0.13.1 -- /usr/bin/python3
rootdir: /root/work/development/ppi/sonic-swss/tests
plugins: …
```
> [vstest] Fix DB connection for mclag test

- orchagent/vnetorch.cpp
**What I did**
changed log severity to WARN
When BfdOrch sends an update notification, it is handled in VNetRouteOrch::update()
Sometimes instead of a valid BFD peer string (like this one):
`NOTICE swss#orchagent: :- doTask: BFD session state for default|default|104.0.0.241 changed from Up to Down `
We receive an empty string (like this one):
`NOTICE swss#orchagent: :- doTask: BFD session state for  changed from Admin_Down to Down`
This will also cause passing empty string in the notification mentioned above, and in updateVnetTunnel(), we will receive an error message due to the if condition:
`ERR swss#orchagent: :- updateVnetTunnel: Failed to parse key , no vrf is given `
There could be a possibility that while SAI gives notification for a session, the BFD object itself …
> [VNET] [202211] consider empty an peer string in BFD entry as a Warning

- orchagent/main.cpp
**What I did**
When running ASAN images with low CPU systems, due to the additional overhead associated with ASAN, it results in switch create timeout as seen in logs below. Hence increasing the **switch create timeout to 2x for ASAN builds.** e.g. For regular switch scenario, the timeout will be 120 seconds  instead of 60 seconds.
```
Apr 18 20:23:46.749074 arc-switch1004 NOTICE swss#orchagent: :- create: request switch create with context 0
Apr 18 20:23:46.749074 arc-switch1004 NOTICE swss#orchagent: :- allocateNewSwitchObjectId: created SWITCH VID oid:0x21000000000000 for hwinfo: ''
Apr 18 20:24:46.816998 arc-switch1004 ERR swss#orchagent: :- wait: SELECT operation result: TIMEOUT on getresponse
Apr 18 20:24:46.817243 arc-switch1004 ERR swss#orchagent: :- wait: failed to get response …
```
> [ASAN]Increasing switch create timeout for ASAN images

- cfgmgr/sflowmgr.cpp
- cfgmgr/sflowmgr.h
- orchagent/sfloworch.cpp
- orchagent/sfloworch.h
- orchagent/switchorch.cpp
- orchagent/switchorch.h
- tests/test_sflow.py
**What I did**
Added egress sflow support.
HLD: https://github.com/sonic-net/SONiC/pull/1268
New enhancement added to sflow to support egress sampling at port level.
Verify the sonic-vs UT scripts. Compile and loaded the swss debian in HW.
Related PRs:
https://github.com/sonic-net/sonic-utilities/pull/2790
https://github.com/sonic-net/sonic-buildimage/pull/14630
> Egress Sflow Support

- orchagent/qosorch.cpp
- tests/mock_tests/qosorch_ut.cpp
**What I did**
Enhance `QosOrch::doTask` by handling QUEUE table after all the rest tables handled to avoid retry
During system initialization, QoS table items are received before `gPortsOrch->allPortsReady()` becomes true and will be handled all together after it becomes true.
In most cases, it will be handled in the for loop in the following snippet of code in `OrchDaemon::start()`
```
auto *c = (Executor *)s;
c->execute();
/* After each iteration, periodically check all m_toSync map to
* execute all the remaining tasks that need to be retried. */
/* TODO: Abstract Orch class to have a specific todo list */
for (Orch *o : m_orchList)
o->doTask();
```
The `QUEUE` table items …
> [QoS] Enhance QosOrch::doTask by handling QUEUE table after all the rest tables handled to avoid retry

- orchagent/portsorch.cpp
**What I did**
With macsec profile attached on multiple interfaces, there is a orchagent crash due to SIGABRT seen in Broadcom based devices.
Steps to recreate 
> configure macsec profile 
> attach macsec_profile on all interfaces in a linecard
> do config reload 
```
May 17 05:14:49.068001 str2--lc1-1 NOTICE swss0#orchagent: :- processQueue: Set buffer queue str2--lc2-1:asic1:Ethernet192:5-6 to BUFFER_PROFILE_TABLE:egress_lossy_profile
May 17 05:14:49.071409 str2--lc1-1 ERR syncd1#syncd: [07:00.0] SAI_API_PORT:brcm_sai_set_port_attribute:1959 Invalid MTU size of 16392 bytes; Max supported MTU size is 16360 bytes.
May 17 05:14:49.071409 str2--lc1-1 ERR syncd1#syncd: :- sendApiResponse: api SAI_COMMON_API_SET failed in syncd mode: SAI_STATUS_INVALID_PARAMETER
May 17 05:14:49.071463 …
```
> Consider macsec sectag header size in getPortMtu during InitializePort

- orchagent/orchdaemon.cpp
- orchagent/pfcactionhandler.cpp
- orchagent/pfcwdorch.cpp
- orchagent/pfcwdorch.h
- tests/mock_tests/mock_orchagent_main.h
- tests/mock_tests/portsorch_ut.cpp
What I did
This PR contains the following changes
* for brcm platforms that support DLR_INIT based recovery, use that method for both drop and forward action
* While using DLR_INIT based recovery, do not update the pfc bitmask for that port
* Update the logic to handle allowing drop/forward action on all ports without requiring a restart of swss
* Mock tests for DLR_INIT and DLR_PACKET action
Why I did it
To provide support for DLR_INIT based pfcwd recovery on broadcom platforms in certain roles
Mock tests
Tested on various brcm platforms (TD3 dual tor, Th2 T1, TD3 single tor) with a custom swss deb along with updated bcm config and verified that the pfcwd recovery mechanism is as expected on 202205
Tested on td3 dual tor with custom deb along with updated bcm config and …
> [pfcwd] Enhance DLR_INIT based recovery and DLR_PACKET_ACTION for broadcom platforms

- orchagent/orchdaemon.cpp
- orchagent/orchdaemon.h
**What I did**
Improve orch agent: output heartbeat message to systemd.
Currently SONiC monit system only monit orchagent process exist or not. If orchagent process stuck and stop processing, current monit can't find and report it.
Pass all UT.
Manually validate the heartbeat message works correctly.
Another inprogress PR will add watchdog for this heartbeat message:
https://github.com/sonic-net/sonic-buildimage/pull/14686
sonic-mgmt UT PR: https://github.com/sonic-net/sonic-mgmt/pull/8306
> Add orchagent heart beat message for watchdog.

- cfgmgr/sflowmgr.cpp
- cfgmgr/sflowmgr.h
- cfgmgr/sflowmgrd.cpp
- tests/mock_tests/Makefile.am
- tests/mock_tests/sflowmgrd_ut.cpp
**What I did**
Backport https://github.com/sonic-net/sonic-swss/pull/2799 to 2211
1) Remove sflowSpeedRateInitMap and infer the default sampling rate based on speed on the interface.
2) Make the rate inference based on oper_speed.
1) With Static Map, adding a new speed would require updating the code.
2) auotneg might change the operational speed on the port but the default sampling rate is not updated
1) UT's:
```
vkarri@3e8d51f2fa45:/sonic/src/sonic-swss/tests/mock_tests$ ./tests --gtest_filter="*SflowMgrTest*"
Running main() from /build/googletest-YnT0O3/googletest-1.10.0.20201025/googletest/src/gtest_main.cc
Note: Google Test filter = *SflowMgrTest*
[==========] Running 8 tests from 1 test suite.
[----------] Global test environment set-up. …
```
> [202211] [sflowmgrd] Infer sampling rate dynamically based on oper speed

- orchagent/aclorch.cpp
**What I did**
Resolved TODO
To resolve TODO
Build and run. Verify capabilities written in STATE DB:
```
127.0.0.1:6379[6]> hgetall  "SWITCH_CAPABILITY|switch"
...
13) "ACL_ACTION|PACKET_ACTION"
14) "DROP,FORWARD"
...
```
> [aclorch] Fix TODO: use SAI object API to query capabilities

- orchagent/intfsorch.cpp
closes https://github.com/sonic-net/sonic-buildimage/issues/15282
The bug is caused by a logic in `intfmgr` which aims to reduce the redundant admin state configuration.
Because of that, `intfsorch` falls back to defaults and treats admin state configuration as disabled.
These changes allow to reset port admin state to it's default value,
when configuration is not received by producer-consumer mechanism.
**What I did**
* Fixed invalid RIF admin state during VNET port subinterface configuration
* To resolve the issue with RIF admin state configuration
* Run VS tests
* N/A
> [subinterface] Fix admin state handling

- orchagent/aclorch.cpp
- orchagent/muxorch.cpp
**What I did**
Bind LAG to ACL table in order to guarantee ACL rule coverage if LAG member will be added to LAG after ACL binding
After config reload or reboot due to timing, we often see race condition when port are not yet added to LAG, but egress ACL table group already created and port is bound to this group.
It causes that ACL rules are not working on LAG's members that were added after binding.
Run test:
`py.test dualtor_io/test_normal_op.py::test_normal_op_upstream[active-standby]`
> [202205][Dual-ToR][ACL] bind LAG to ACL table in order to guarantee rule coverage if LAG member will be added to LAG after binding

- orchagent/portsorch.cpp
**What I did**
It seems that currently, we don't print the value of host_tx_ready in some places while setting it. We need to ensure to log the value of host_tx_ready in such cases.
Example:
https://github.com/sonic-net/sonic-swss/blob/872b80b699d25e84a352a8511cb8882792a2443c/orchagent/portsorch.cpp#L1105-L1106
Also, we should display port number instead of port_id to keep logging consistent.
https://github.com/sonic-net/sonic-swss/blob/872b80b699d25e84a352a8511cb8882792a2443c/orchagent/portsorch.cpp#LL1149C28-L1149C44
May 25 22:28:47.759325 sonic NOTICE swss#orchagent: :- doPortTask: Set port Ethernet136 admin status to up
May 25 22:28:47.759566 sonic INFO swss#orchagent: :- initHostTxReadyState: initalize hostTxReady Ethernet144 with status
May 25 22:28:47.760391 sonic INFO …
> [portsorch]: Enhancing SWSS OA logs to capture host_tx_ready change events

- orchagent/dash/dashaclorch.cpp
- orchagent/dash/dashaclorch.h
- orchagent/dash/dashorch.cpp
- orchagent/dash/dashorch.h
- orchagent/dash/dashrouteorch.cpp
- orchagent/dash/dashrouteorch.h
- orchagent/dash/dashvnetorch.cpp
- orchagent/dash/dashvnetorch.h
- orchagent/main.cpp
- orchagent/orch.cpp
- orchagent/orch.h
- orchagent/orchdaemon.cpp
- orchagent/orchdaemon.h
- tests/mock_tests/orchdaemon_ut.cpp
Change dash orchagent from Redis consumer state table to ZMQ consumer state table.
**What I did**
Change dash orchagent from Redis consumer state table to ZMQ consumer state table.
To improve dash entry create performance, change dash orchagent from Redis consumer state table to ZMQ consumer state table.
Pass all UT.
> [dash] Change dash orchagent from Redis consumer state table to ZMQ consumer state table.

- orchagent/main.cpp
- orchagent/orch.cpp
Enable/disable Dash ZmqConsumer by parameter.
**What I did**
Change code to allow disable ZMQ and switch back to Redis Consumer.
Dash orch UT still need Redis based Consumer, so improve to disable ZMQ and switch back to Redis Consumer.
Pass all UT.
> Enable/disable Dash ZmqConsumer and switch back to Redis based consumer by parameter.

- tests/test_dash_acl.py
- tests/test_dash_crm.py
- tests/test_dash_vnet.py
**What I did**
Define a generic NPU SKU for docker-sonic-vs
Bluefield3 hwsku(Nvidia-MBF2H536C) is not planned to be made available upstream in the near future. Therefore , inorder to pass DASH vstests on azure pipeline runs, this change is being made.
By making sure that DASH vstests are able to run and pass on azure pipeline.
> [tests]: Set HWSKU to NPU for dash vstests

- orchagent/mirrororch.cpp
**What I did**
Added SAI_STATUS_NOT_IMPLEMENTED to SAI return status check while fetching resource availability.
If resource availability lookup API is not supported for a specific object, the API returns SAI_STATUS_NOT_IMPLEMENTED or SAI_STATUS_NOT_SUPPORTED. These return values do not indicate unavailability of the resource itself and need to be ignored.
Everflow tests on 202205 with SAI which returns SAI_STATUS_NOT_IMPLEMENTED
> Allow NOT_IMPLEMENTED sai return status for availability monitoring API

- .github/workflows/codeql-analysis.yml
Signed-off-by: Nazarii Hnydyn [nazariig@nvidia.com](mailto:nazariig@nvidia.com)
**What I did**
* Increase robustness of `CodeQL`: use only dependencies with the relevant versions
* To fix `CodeQL` compilation failures
1. Make a PR
2. Do a push
* Resolves checker issue: https://github.com/sonic-net/sonic-swss/pull/2564
* Takes effect only after PR is merged
> [CodeQL]: Use dependencies with relevant versions in azp template

- orchagent/muxorch.cpp
- orchagent/muxorch.h
- tests/test_mux.py
**What I did**
cherry-pick https://github.com/sonic-net/sonic-swss/pull/2557 into 202211 branch.
> [202211][muxorch] Skip programming SoC IP kernel tunnel route

- tests/test_dash_acl.py
- tests/test_dash_crm.py
- tests/test_dash_vnet.py
* Change DVS ENV HWSKU to a more appropriate DPU-2P from NPU-2P for DASH vstest
**What I did**
Change DVS ENV HWSKU to a more appropriate DPU-2P from NPU-2P for DASH vstest
DPU-2P is more appropriate for 2-port simulator for DASH vstests 
By running DASH vstest manually
Related sonic-buildimage and sonic-sairedis changes are listed below:
https://github.com/sonic-net/sonic-buildimage/pull/15695
https://github.com/sonic-net/sonic-sairedis/pull/1259
> [tests]: Change DVS ENV HWKSU to DPU-2P for DASH vstest

- .github/workflows/codeql-analysis.yml
Signed-off-by: Nazarii Hnydyn [nazariig@nvidia.com](mailto:nazariig@nvidia.com)
**What I did**
* Increase robustness of `CodeQL`: use only dependencies with the relevant versions
* To fix `CodeQL` compilation failures
1. Make a PR
2. Do a push
* Backport from `master`: https://github.com/sonic-net/sonic-swss/pull/2845
* Resolves checker issue: https://github.com/sonic-net/sonic-swss/pull/2821
* Takes effect only after PR is merged
> [202211][CodeQL]: Use dependencies with relevant versions in azp template

- orchagent/fabricportsorch.cpp
**What I did**
Call to `updateFabricPortState` in `FabricPortsOrch::getFabricPortList()` is redundant as `FabricPortsOrch::doTask()` already calls it.
This change helps mitigate the MHz spikes during boot up of the supe as described in https://github.com/sonic-net/sonic-buildimage/issues/15321.
To help address https://github.com/sonic-net/sonic-buildimage/issues/15321.
Boot up supe on Voq chassis and query fabric counters.
> [Chassis]Remove redundant updateFabricPortState

- orchagent/neighorch.cpp
**What I did**
Remove system neighbor DEL operation in m_toSync if SET operation for the same neighbor succeeds. This is to avoid mistakenly removing the system neighbor.
Fix https://github.com/sonic-net/sonic-buildimage/issues/15266
https://github.com/sonic-net/sonic-buildimage/issues/15266 was uncovered by https://github.com/sonic-net/sonic-mgmt/blob/master/tests/voq/test_voq_disrupts.py.  The issue was not seen in the test anymore with the fix.
> Remove system neigh DEL operation if SET operation succeeds

- orchagent/bufferorch.cpp
- orchagent/portsorch.cpp
- orchagent/qosorch.cpp
**What I did**
Added support to apply wred profile on system ports
remote system ports were missing wred profile
Tested on sonic chassis
> [Chassis][orchagent] : Support WRED profiles on system ports

- orchagent/dash/dashrouteorch.cpp
- tests/test_dash_vnet.py
**What I did**
1. For outbound routing, I fix a bug that vnet name will lose in vnet_direct case.
2. The fvs from asic db is the dict type in test cases of dash vnet, for a dict will just for its keys.
1. The vnet name in vnet and vnet_direct cases are defined in a different field.
https://github.com/sonic-net/sonic-dash-api/blob/3f728d1bbf65d2e8c41bdc023d5c07702a7f848b/proto/route.proto#L30-L32
```
message VnetDirect {
// destination vnet name if action_type is {vnet, vnet_direct}, a vnet other than eni's vnet means vnet peering
string vnet = 1;
...
}
message Route {
route_type.RoutingType action_type = 1;
oneof Action {
// destination vnet name if action_type is vnet,, a vnet other than eni's vnet means vnet peering
string vnet = 2;
// destination vnet name if …
```
> [Fixbug]: Fix vnet attribute miss if route action is vnet_direct and vnet test cases

- orchagent/bufferorch.cpp
- orchagent/orch.h
- orchagent/qosorch.cpp
**What I did**
Fix the Mem Leak by moving the raw pointers in type_maps to use smart pointers
```
Indirect leak of 83776 byte(s) in 476 object(s) allocated from:
#0 0x7f0a2a414647 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
#1 0x5555590cc923 in __gnu_cxx::new_allocator, std::allocator > const, referenced_object> > >::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115
#2 0x5555590cc923 in std::allocator_traits, std::allocator > const, referenced_object> > > >::allocate(std::allocator, std::allocator > const, referenced_object> > >&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460
#3 0x5555590cc923 in std::_Rb_tree, std::allocator >, std::pair, std::allocator > const, referenced_object>, …
```
> [ASAN] Fix Indirect Mem Leaks in Orchagent

- orchagent/muxorch.cpp
- tests/test_mux.py
Warm reboot with manual mux mode was causing orchagent crash.
Initializing mux state to INIT upon warm reboot, the state will then be updated to reflect previous APPDB state.
**What I did**
Initialize mux state to INIT during warm reboot
initializing mux state to Standby during warm reboot was causing orchagent to crash if mux was put in manual mode
vstests included in PR
> [muxorch] set mux state to init upon warm reboot

- cfgmgr/buffer_headroom_mellanox.lua
**What I did**
Fix an error in peer response time when headroom is calculated for 800G
Bug fix.
Manually test
> [Mellanox] Fix error in peer response time when headroom is calculated for 800G

- orchagent/port/porthlpr.cpp
Signed-off-by: Nazarii Hnydyn [nazariig@nvidia.com](mailto:nazariig@nvidia.com)
**HLD:** https://github.com/sonic-net/SONiC/pull/1084
**What I did**
* Relaxed port attributes validation: decreased message severity
* To resolve `LogAnalyzer` failures during DPB test
1. Run DPB test
* A W/A for: https://github.com/sonic-net/sonic-buildimage/issues/15999
> [ppi]: Relax port attributes validation

- cfgmgr/macsecmgr.cpp
**What I did**
Support type7 encoded CAK key for macsec in config_db
MSFT ADO : 25046448
The external store has the macsec CAK keys stored in type7 format. Hence the automation tools retrieve these keys and stores in config_db in type7 format. 
This need to be decoded to text format for wpa_supplicant to consume.
Verified with type7 encoded CAK keys, macsec sessions should come up 
MACSEC_PROFILE **(earlier format where CAK is in text)**
```
},
"MACSEC_PROFILE": {
"macsec-profile": {
"cipher_suite": "GCM-AES-XPN-256",
"primary_cak": "0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF",
"primary_ckn": "6162636465666768696A6B6C6D6E6F707172737475767778797A303132333435",
"priority": "4",
"rekey_period": "1800"
},
"macsec-profile2": { …
```
> Support type7 encoded CAK key for macsec in config_db

- .gitignore
- cfgmgr/teammgr.cpp
- tests/mock_tests/Makefile.am
- tests/mock_tests/teammgrd/teammgr_ut.cpp
**What I did**
- During LAG creation, if the teamd process fails for any reason, cleanup any leftover teamd processes for the LAG alias
- Call `kill` directly in `removeLag` instead of using `teamd -k`
- If the teamd process times out for any reason, subsequent attempts to create a LAG may fail if there is an orphaned process left running
- As detailed in https://github.com/sonic-net/sonic-buildimage/issues/8071, `team -k` may block for some time.
> [teamd]: Clean teamd process if LAG creation fails

- orchagent/fdborch.cpp
**What I did**
Only call flushFDBEntries() when there is a bridge port OID in port state update for fdborch.
The flushFDBEntries() has the check at the beginning. But it is wrong to call the function to begin with.
This will get rid of the false warning log message in flushFDBEntries().
> [fdborch] Only call flushFDBEntries() when there is a bridge port OID in port state update

- orchagent/main.cpp
This will be required since SAI v1.13
**What I did**
Add extra parameter when creating switch when switch type is fabric
It will be required attribute since SAI v1.13
Build locally
Build on THIS will fail, since it will require sairedis to updates first, and sairedis will fail because swss don't contain this change, both repos needs to be update before test will start to pass
OA will require to pass "switch_id" param in config for fabric devices, not only for voq, devices, because of that test updates may be required
> [orchagent] Add SAI_SWITCH_ATTR_SWITCH_ID for fabric switch

- .github/workflows/codeql-analysis.yml
**What I did**
* Increase robustness of `CodeQL`: use only dependencies with the relevant versions
* To fix `CodeQL` compilation failures
1. Make a PR
2. Do a push
* Backport from `master`: https://github.com/sonic-net/sonic-swss/pull/2845
* Takes effect only after PR is merged
> [202205][CodeQL]: Use dependencies with relevant versions in azp template

- orchagent/p4orch/tests/fake_portorch.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
**DEPENDS:**
1. https://github.com/sonic-net/sonic-swss/pull/2821
**HLD:** https://github.com/sonic-net/SONiC/pull/1084
**What I did**
* Removed unused code
* To complete code cleanup
* UT tests
* VS tests
* Backport from `master`: https://github.com/sonic-net/sonic-swss/pull/2867
> [202211][ppi]: General code cleanup: remove unused methods (#2867)

- .github/workflows/codeql-analysis.yml
**What I did**
* Increase robustness of `CodeQL`: use only dependencies with the relevant versions
* To fix `CodeQL` compilation failures
1. Make a PR
2. Do a push
* Backport from `master`: https://github.com/sonic-net/sonic-swss/pull/2845
* Takes effect only after PR is merged
> [202305][CodeQL]: Use dependencies with relevant versions in azp template

- orchagent/bufferorch.cpp
- tests/mock_tests/bufferorch_ut.cpp
**What I did**
Retry one more time when it fails to set buffer profiles' attributes to SAI
Vendor SAI can perform a sanity check on all the attributes when an attribute is modified or a new object is created.
However, while the user or buffer manager daemon passes all new attributes in an (atomic) operation, there can be only one attribute in each SAI SET operation, which means the vendor SAI does not understand the whole information of the new attributes and can only perform the sanity check against each SET operation.
In some rare scenarios, the sanity check can fail due to one single attribute not being compatible with the old attributes set but being compatible with the new attributes set. In this case, all new attributes will be applied to SAI successfully by …
> [Buffer Orch] Retry one more time when it fails to set buffer profiles' attributes to SAI

- orchagent/muxorch.cpp
**What I did**
When mux transits from active to standby, orchagent first disable the
neighbor[1], then program the tunnel route[2].
There is a small period of time between [1] and [2] that the ASIC
is unable to forward the traffic to the neighbor.
So let's reorder those two operations - program the tunnel route first,
then disable the neighbor.
Signed-off-by: Longxiang Lyu <lolv@microsoft.com>
Packet loss observed during `config mux standby`
Validate that, with the fix, no more packet loss is observed when `config mux standby`
> [muxorch] Reorder the neighbor disable operations

- orchagent/portsorch.cpp
**What I did**
Do not set internal port count to the PortConfigDone DB value.
Fix https://github.com/sonic-net/sonic-swss/issues/2904
> [orchagent] Do not set internal port count to the PortConfigDone DB value.

- .gitignore
- cfgmgr/teammgr.cpp
- tests/mock_tests/Makefile.am
- tests/mock_tests/teammgrd/teammgr_ut.cpp
202305 cherry pick for https://github.com/sonic-net/sonic-swss/pull/2888
**What I did**
- During LAG creation, if the teamd process fails for any reason, cleanup any leftover teamd processes for the LAG alias
- Call `kill` directly in `removeLag` instead of using `teamd -k`
- If the teamd process times out for any reason, subsequent attempts to create a LAG may fail if there is an orphaned process left running
- As detailed in https://github.com/sonic-net/sonic-buildimage/issues/8071, `team -k` may block for some time.
> [202305][teamd]: Clean teamd process if LAG creation fails

- orchagent/flexcounterorch.cpp
- orchagent/flexcounterorch.h
- orchagent/p4orch/tests/fake_flexcounterorch.cpp
- orchagent/portsorch.cpp
- tests/test_flex_counters.py
**What I did**
Add support in the orchagent for the configuration knob:
```
{
"DEVICE_METADATA": {
"localhost": {
"create_only_config_db_buffers": "true"
...
}
}
}
```
If the `"create_only_config_db_buffers"` is equal to `"true"` - buffers will be created according to the config_db configuration (for example `BUFFER_QUEUE|*` table).
If the `"create_only_config_db_buffers"` is equal to `"false"` or does not exist - the maximum available buffers (which are read from SAI) will be created, regardless of `the config_db` buffer config.
Add UT.
Manual verification:
1. Install the image with this PR included on the not `MSFT SKU` switch
2. Check the `show queue counters` output and verify that only configured in `CONFIG_DB` buffers are created
``` …
```
> [buffers] Add handler for the 'create_only_config_db_buffers' configuration knob

- orchagent/flexcounterorch.cpp
- orchagent/flexcounterorch.h
- orchagent/portsorch.cpp
- tests/test_flex_counters.py
**What I did**
Add support in the orchagent for the configuration knob:
```
{
"DEVICE_METADATA": {
"localhost": {
"create_only_config_db_buffers": "true"
...
}
}
}
```
If the `"create_only_config_db_buffers"` is equal to `"true"` - buffers will be created according to the config_db configuration (for example `BUFFER_QUEUE|*` table).
If the `"create_only_config_db_buffers"` is equal to `"false"` or does not exist - the maximum available buffers (which are read from SAI) will be created, regardless of `the config_db` buffer config.
Add UT.
Manual verification:
1. Install the image with this PR included on the not `MSFT SKU` switch
2. Check the `show queue counters` output and verify that only configured in `CONFIG_DB` buffers are created
``` …
```
> [202205][buffers] Add handler for the 'create_only_config_db_buffers' configuration knob

- orchagent/dash/dashaclorch.cpp
- tests/test_dash_acl.py
**What I did**
Correct the table name of doTask in DashAclOrch
For fixing the typo
Add test cases and check Azp
> [fixbug]: Fix wrong table name for acl_out_table

- orchagent/portsorch.cpp
**What I did**
Reduced the severity of log when get attribute of oper fec failed.
The oper fec is not a mandatory attribute and may not be implemented by vendor SAI, in which case throwing an error is wrong. Reduced the severity of the log message to notice. This will also fix the checker issues in https://github.com/sonic-net/sonic-buildimage/pull/16785
> Reducing the severity of oper fec attribute get failure

- orchagent/notifications.cpp
The data race in on_switch_shutdown_request() is the following:
* the on_switch_shutdown_request() calls exit() which calls the destructors for global static variables (e.g.BufferOrch::m_buffer_type_maps)
* in parallel to that, orchagent accesses the global static variables
A fix is to avoid calling the destructors by using quick_exit() instead of exit()
**What I did**
Changed exit() -> quick_exit() in on_switch_shutdown_request().
Added __lsan_do_leak_check() call for ASAN build.
To address a data race in the on_switch_shutdown_request()
> Fix data race in on_switch_shutdown_request()

- orchagent/orch.cpp
- orchagent/orch.h
**What I did**
Add refillToSync() into ConsumerBase to support warmboot.
Add warmboot support for zmq consumer.
This will be useful when we migrate other orchs to use zmq.
UT
> Add refillToSync() into ConsumerBase to support warmboot.

- orchagent/portsorch.cpp
Issue seen on platforms that are not supporting queue-watermark and pg counters.
**What I did**
Fixed orchagent crash reported in #2935 
Added checks to skip if max values for PG and queue are 0
Reloaded swss debian with fix and enable flex counters watermark and pg-drop
> [FlexCounters] Fixed orchagent crash issue#2395

- orchagent/portsorch.cpp
Issue seen on platforms that are not supporting queue-watermark and pg counters.
**What I did**
Cherry-pick fix for orchagent crash reported in https://github.com/sonic-net/sonic-swss/issues/2935
Added checks to skip if max values for PG and queue are 0
Reloaded swss debian with fix and enable flex counters watermark and pg-drop
> [202205][FlexCounters] Fixed orchagent crash issue#2395

- orchagent/Makefile.am
- orchagent/dash/dashaclgroupmgr.cpp
- orchagent/dash/dashaclgroupmgr.h
- orchagent/dash/dashaclorch.cpp
- orchagent/dash/dashaclorch.h
- orchagent/dash/dashtagmgr.cpp
- orchagent/dash/dashtagmgr.h
- orchagent/dash/pbutils.cpp
- orchagent/dash/pbutils.h
- orchagent/orchdaemon.cpp
- tests/mock_tests/Makefile.am
- tests/test_dash_acl.py
**What I did**
Implement the DASH ACL tags feature according to [DASH ACL tags HLD](https://github.com/sonic-net/SONiC/blob/master/doc/dash/dash-acl-tags/dash-acl-tags.md)
To add support for DASH ACL tags feature
Run extended VS tests that cover new implementation
> [DASH] ACL tags implementation

- .gitignore
- cfgmgr/teammgr.cpp
- tests/mock_tests/Makefile.am
- tests/mock_tests/mock_shell_command.cpp
- tests/mock_tests/teammgrd/teammgr_ut.cpp
**What I did**
- 202205 cherry-pick for #2888 
- During LAG creation, if the teamd process fails for any reason, cleanup any leftover teamd processes for the LAG alias
- Call `kill` directly in `removeLag` instead of using `teamd -k`
- If the teamd process times out for any reason, subsequent attempts to create a LAG may fail if there is an orphaned process left running
- As detailed in https://github.com/sonic-net/sonic-buildimage/issues/8071, `team -k` may block for some time.
> [202205][teamd]: Clean teamd process if LAG creation fails (#2888)

- orchagent/muxorch.cpp
- tests/test_mux.py
What I did:
- Removed logic that prevented routes from updating if an active nexthop was already found in updateRoute cache.
- added test to check for scenario where ecmp route update triggers after updateRoute programs route to point to single nh
- Added logs to some key paths in updateRoute logic to add visibility
Why I did it:
Bug in logic was causing routes getting updated multiple times to skip updateRoute logic
How I did it:
removing logic that checked cache for active nexthop
https://github.com/sonic-net/sonic-swss/pull/2952
> [muxorch] Fixing updateRoute logic

- orchagent/orchdaemon.cpp
- orchagent/orchdaemon.h
Orchangent send heartbeat during warm-reboot to prevent Orchagent stuck alert.
Orchangent will freese during warm-reboot, then supervisor-proc-exit-listener will generate false alert during warm reboot:
https://github.com/sonic-net/sonic-buildimage/issues/16686
- Microsoft ADO: 25295846
Send heartbeat during warm-reboot freeze.
Pass all UT.
Manually verify issue fixed by check syslog.
Orchangent send heartbeat during warm-reboot to prevent Orchagent stuck alert.
> [202305] Send hearbeat during warm reboot freese (#2923)

- orchagent/dash/dashaclgroupmgr.cpp
**What I did**
Updated the code to avoid using the vector (protocols) that goes out of scope before its data is used
To fix a use-after-free bug
> [dash] fix DASH ACL Rule protocol use-after-free

- tests/test_virtual_chassis.py
- tests/virtual_chassis/1/default_config.json
- tests/virtual_chassis/2/default_config.json
- tests/virtual_chassis/3/default_config.json
**What I did**
Added test case for wred profile on system ports
Added test case for  https://github.com/sonic-net/sonic-swss/pull/2855
Verified on VS testbed.
> [Chassis][master][orchagent] : Added test case to verify WRED profile on system ports

- orchagent/bufferorch.cpp
- orchagent/qosorch.cpp
- tests/test_virtual_chassis.py
- tests/virtual_chassis/1/default_config.json
- tests/virtual_chassis/2/default_config.json
- tests/virtual_chassis/3/default_config.json
MSFT ADO: 24595422
What I did
Added support to apply wred profile on system ports
Why I did it
remote system ports were missing wred profile
Tested on sonic chassis
Details if related
> [Chassis][202205][orchagent] : Support WRED profiles on system ports

- cfgmgr/coppmgr.cpp
**What I did**
When handling the copp entries that are updated in new life, coppmgrd is deleting them directly from the table instead of using ProducerStateTable Del. Thus updated the value.
**Why i did it**
Without this, the copp traps are not created during reconciliation phase (because the key is deleted entirely from APP_DB) and are created at a later point. This would case a delay in LACP trap creation and would result in a 30 sec delay for the LACP sessions to be established and dplane downtime
Did a fastboot from 202205 -> 202305 (it had a difference in default copp fields and so the the del logic is triggered) and verified if the dplane downtime is < 30 sec
> [coppmgrd] Use Producer del instead of del from Table

- orchagent/muxorch.cpp
- orchagent/muxorch.h
- orchagent/routeorch.cpp
- tests/test_mux.py
**What I did**
Fixed a bug where cache was not removing entry when an ecmp mux route gets updated to a single nexthop route. And added test case to cover the edge case.
Mux switchover was failing because it was skipping over the route in updateNextHopRoutes.
Removing cache from updateRoute logic, and relying on other logic to skip over multiple mux nexthop case.
ADO: 26099588
> [muxorch] Fixing cache bug in updateRoute logic

- orchagent/muxorch.cpp
- orchagent/muxorch.h
- orchagent/routeorch.cpp
- tests/test_mux.py
**What I did**
Fixed a bug where cache was not removing entry when an ecmp mux route gets updated to a single nexthop route. Removed cache from updateRoute logic, and relying on other logic to skip over multiple mux nexthop case.
Mux switchover was failing because it was skipping over the route in updateNextHopRoutes.
Added vstest and ran test cases on virtual switch
cherry-pick of https://github.com/sonic-net/sonic-swss/pull/2982
MSFT ADO - 26099588
> [muxorch][202205] Fixing cache bug in updateRoute logic

- orchagent/routeorch.cpp
- tests/test_mux.py
**What I did**
- Fixed a bug where multiple routes pointing to the same nhg would not remove the route from m_nextHops cache in routeorch
- Refactored multi_mux_nexthops tests and added new test cases
Caught the bug while refactoring, this will cause issues with switchover if one of the routes is removed
Ran refactored tests on local vstest setup, and all test cases passed
> [routeorch] Fixing bug with multiple routes pointing to nhg

- orchagent/routeorch.cpp
- tests/test_drop_counters.py
- tests/test_mux.py
- tests/test_virtual_chassis.py
**What I did**
- Fixed a bug where multiple routes pointing to the same nhg would not remove the route from m_nextHops cache in routeorch
- Refactored multi_mux_nexthops tests and added new test cases
Caught the bug while refactoring, this will cause issues with switchover if one of the routes is removed
Ran refactored tests on local vstest setup, and all test cases passed
cherry-pick of https://github.com/sonic-net/sonic-swss/pull/2999
> [202205][routeorch] Fixing bug with multiple routes pointing to nhg 

- orchagent/routeorch.cpp
- tests/test_mux.py
**What I did**
- Fixed a bug where multiple routes pointing to the same nhg would not remove the route from m_nextHops cache in routeorch
- Refactored multi_mux_nexthops tests and added new test cases
Caught the bug while refactoring, this will cause issues with switchover if one of the routes is removed
MSFT ADO - 26099588
Ran refactored tests on local vstest setup, and all test cases passed
cherry-pick of https://github.com/sonic-net/sonic-swss/pull/2999
> [202305][routeorch] Fixing bug with multiple routes pointing to nhg

- orchagent/routeorch.cpp
- tests/mock_tests/routeorch_ut.cpp
**What I did**
Publish exception route state to APPL_STATE_DB.
Fixes https://github.com/sonic-net/sonic-buildimage/issues/17638
Route to loopback interface is not advertised to peers when FIB suppression is enabled.
The proper way would be to program route to HW and then publish the route state, however to keep the existing behaviour this W/A is proposed until a final solution.
Route is queued:
```
admin@sonic:~$ show ipv6 route |grep q
> - selected route, * - FIB route, q - queued route, r - rejected route
S>qfc00:1::/64 [1/0] is directly connected, Loopback0, 00:02:00
```
With this change:
```
admin@sonic:~$ show ipv6 route | grep q
> - selected route, * - FIB route, q - queued route, r - rejected route
```
> [RouteOrch] Publish route state for route to Loopback interface

- .artifactignore
- .azure-pipelines/build-docker-sonic-vs-template.yml
- .azure-pipelines/build-template.yml
- .azure-pipelines/docker-sonic-vs/Dockerfile
- .azure-pipelines/test-docker-sonic-vs-template.yml
- azure-pipelines.yml
- cfgmgr/Makefile.am
- debian/rules
- fdbsyncd/Makefile.am
- fpmsyncd/Makefile.am
- gcovpreload/Makefile
- gcovpreload/gcovpreload.cpp
- mclagsyncd/Makefile.am
- natsyncd/Makefile.am
- neighsyncd/Makefile.am
- orchagent/Makefile.am
- orchagent/neighorch.cpp
- portsyncd/Makefile.am
- swssconfig/Makefile.am
- teamsyncd/Makefile.am
- tests/conftest.py
- tests/run-tests.py
- tlm_teamd/Makefile.am
**What I did**
1. Support to dump the gcda files in the each of docker-sonic-vs containers when running the tests of sonic-swss.
2. Support to collect the coverage in the cobertura format directly from the sonic-swss build and the docker-sonic-vs containers during the component tests.
3. Simply the logic to collect the coverage. Use the dotnet tool reportgenerator to merge all the coverage files in cobertura  format.
4. Reduce build time using the sonicbld agent pool (36 minutes -> 20 minutes), reduce test time by running the tests in parallel (8 pytest processes) and using more powerful agent pool sonic-common-test (4hours -> 1 hours).
5. Improve the test stability, retry 3 times if failed.
Fix the coverage issue, some of the files are not covered in the coverage report. …
> [Build] Support to collect the test coverage in cobertura format

- orchagent/fabricportsorch.cpp
- orchagent/fdborch.cpp
- orchagent/fdborch.h
- orchagent/mirrororch.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/mock_tests/aclorch_ut.cpp
**What I did**
When compiled with GCC 12, there are two types of compiler errors that get revealed. The first is GCC saying that in a for-loop, if the variable used for the objects is const, then a reference to the original object in the list can be used, instead of making a copy. The second is that two variables could potentially be used uninitialized. This appears to be a false positive to me, but I assigned it to 0 regardless.
There are, however, issues seen when running the tests. In a Bookworm-based container, the CoppMgrTest.CoppTest test case failed when run as part of the full test suite. However, when run individually, it passes. The error message is the following:
```
[ RUN      ] CoppMgrTest.CoppTest
mkdir: cannot create directory '/etc/sonic/': File exists
copp_ut.cpp:16: …
```
> Fix memory leak and object copying bugs in orchagent

- orchagent/orch.cpp
**What I did**
GCC 12 (in Debian Bookworm) claims that on armhf targets, the `lower` local variable in `Orch::generateIdListFromMap` could potentially be used uninitialized a few lines later when it's being converted to a string. I don't see how that could be the case here, since if the string is being printed, the only code path where this is possible requires `lower` to have been set to something. It also only complains about this for armhf and i386 (i.e. 32-bit platforms); amd64 and arm64 (64-bit platforms) are fine. (i386 was manually tested by installing the 32-bit crosscompiler and development headers in a slave container and running the g++ command to compile orch.cpp.)
To silence the warning, set both `lower` and `upper` to 0 explicitly. …
> Explicitly initialize two local variables to 0

- orchagent/bufferorch.cpp
**What I did**
Modified BufferOrch::processQueue in orchagent to pass the correct token for queue-id range if the switch_type is voq to  gPortsOrch->createPortBufferQueueCounters.
VM crashes with  Qos "BUFFER_QUEUE|system-port|Queue-id-range" config for system ports. The crash was not seen in hardware somehow and queue & voq stats are working with the different code path adding the QUEUE stats counters to FLEX_COUNTER_DB
FlexCounterOrch::doTask -> generateQueueMap -> generateQueueMapPerPort (true) -> addQueueFlexCountersPerPortPerQueueIndex
verified that the correct queue id-range is passed to gPortsOrch->createPortBufferQueueCounters. and not crashing.
> Fixed orchagent crash in VM with the Qos BUFFER_QUEUE|system-port|Queue-id-range config

- orchagent/intfsorch.cpp
- tests/test_vnet.py
setting SAI_VLAN_ATTR_UNKNOWN_MULTICAST_FLOOD_CONTROL_TYPE to SAI_VLAN_FLOOD_CONTROL_TYPE_NONE when proxy arp is enabled. This fixes a bug where ipv6 NS packets were flooding ports with duplicate packets. We now set multicast flood type to none.
**What I did**
Set SAI_VLAN_ATTR_UNKNOWN_MULTICAST_FLOOD_CONTROL_TYPE to vlan_flood_type. This will either be SAI_VLAN_FLOOD_CONTROL_TYPE_NONE or SAI_VLAN_FLOOD_CONTROL_TYPE_ALL depending on if proxy arp is enabled.
Fixes issue where ndp packets were flooding ports ADO: 26395578
Tested change on a lab device, confirmed that when proxy-arp was enabled multicast packets were being blocked in the hardware
sonic-buildimage fix to block packets in kernel to come, will link here.
ADO: …
> [intfsorch] Enable ipv6 proxy ndp along with proxy arp

- orchagent/neighorch.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/mock_tests/Makefile.am
- tests/mock_tests/flowcounterrouteorch_ut.cpp
- tests/mock_tests/mock_orch_test.h
- tests/mock_tests/mock_sai_api.cpp
- tests/mock_tests/mock_sai_api.h
- tests/mock_tests/mux_rollback_ut.cpp
- tests/mock_tests/neighorch_ut.cpp
- tests/mock_tests/routeorch_ut.cpp
**What I did**
- When adding a new neighbor, check if the neighbor IP has already been learned on a different VLAN. If it has, remove the old neighbor entry before adding the new one.
- On Gemini devices, if a neighbor IP moves from an active port in one VLAN to a second VLAN, then back to the first VLAN (with 3 different MAC addresses), orchagent will crash. Even though the MAC address of the last move is different from the first MAC address, orchagent believes the last MAC address to already be programmed in the hardware and tries to set an attribute of the entry which doesn't exist.
- Run the NeighOrch unittests
> Fix multi VLAN neighbor learning

- configure.ac
**What I did**
Fix compilation with ASAN enabled for the Debian Bookworm with GCC version 12.2.0 (Debian 12.2.0-14):
```
g++ -DHAVE_CONFIG_H -I. -I.. -I ../lib -I .. -I ../warmrestart -I ../cfgmgr -g  -std=c++14 -Wall -fPIC -Wno-write-strings -I/usr/include/swss -I/usr/include/libnl3 -Werror -Wno-reorder -Wcast-align -Wcast-qual -Wconversion -Wdisabled-optimizatio
n -Wextra -Wfloat-equal -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wimport -Winit-self -Winvalid-pch -Wlong-long -Wmissing-field-initializers -Wmissing-format-attribute -Wno-aggregate-return -Wno-padded -Wno-switch-enum -Wno-
unused-parameter -Wpacked -Wpointer-arith -Wredundant-decls -Wstack-protector -Wstrict-aliasing=3 -Wswitch -Wswitch-default -Wunreachable-code -Wunused -Wvariadic-macros …
```
> [asan] Disable the "maybe-uninitialized" warning when compiled with ASAN enabled.

- orchagent/neighorch.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/mock_tests/Makefile.am
- tests/mock_tests/flowcounterrouteorch_ut.cpp
- tests/mock_tests/mock_orch_test.h
- tests/mock_tests/mock_sai_api.cpp
- tests/mock_tests/mock_sai_api.h
- tests/mock_tests/mux_rollback_ut.cpp
- tests/mock_tests/neighorch_ut.cpp
- tests/mock_tests/routeorch_ut.cpp
202311 cherry-pick of https://github.com/sonic-net/sonic-swss/pull/3049
What I did
When adding a new neighbor, check if the neighbor IP has already been learned on a different VLAN. If it has, remove the old neighbor entry before adding the new one.
Why I did it
On Gemini devices, if a neighbor IP moves from an active port in one VLAN to a second VLAN, then back to the first VLAN (with 3 different MAC addresses), orchagent will crash. Even though the MAC address of the last move is different from the first MAC address, orchagent believes the last MAC address to already be programmed in the hardware and tries to set an attribute of the entry which doesn't exist.
**What I did**
> [202311]Fix multi VLAN neighbor learning (#3049)

- orchagent/main.cpp
- orchagent/portsorch.cpp
**What I did**
Changed SAI_SWITCH_ATTR_PORT_HOST_TX_READY_NOTIFY callback attribute to be set only after query capabilities approved that CMIS mgmt. feature is enabled. 
Before that change, in orchagent/main.cpp, that attribute was set without checking if SAI version is not supporting this feature. 
This could cause an issue to unsupported SAI versions with supported SONiC versions. 
Made sure all functionality is the same as before, and this attribute set will not break not-supporting SAI versions.
> Set HOST_TX_READY_NOTIFY attribute only after query capabilities

- orchagent/routeorch.cpp
- tests/mock_tests/routeorch_ut.cpp
**What I did**
Skip EVPN routes with invalid VNI or router mac field
Code assumes number of next hops is equal to amount of VNIs and to amount of router macs.
Usually this is this the case however, we encountered a case of inequality due to bug in FRR. 
Bug was opened to FRR but the code should not assume equality therefore I added the check.
I ran EVPN test with code that enforced different vector length, and made sure error is printed to log and route is skipped.
> [EVPN] Skip EVPN routes with invalid VNI or router mac field

- cfgmgr/fabricmgr.cpp
- orchagent/fabricportsorch.cpp
- orchagent/fabricportsorch.h
- tests/test_fabric_port_isolation.py
- tests/virtual_chassis/8/default_config.json
**What I did**
Added basic fabric link monitoring counters and states handling, and the test for this. 
> Add basic fabric link monitoring counters and states handling.

- cfgmgr/buffer_pool_mellanox.lua
- tests/test_buffer_dynamic.py
**What I did**
Fix inconsistent initialization of the shared headroom pool by setting a small size to indicate the shared headroom pool is enabled.
During initialization, if SHP is enabled
1. the buffer pool sizes, xoff have initialized to 0, which means SHP is disabled
2. but the buffer profiles already indicate SHP
3. later on the buffer pool sizes are updated with off being non-zero
In case the orchagent starts handling buffer configuration between 2 and 3, it is inconsistent between buffer pools and profiles, which fails Mellanox SAI sanity check.
To avoid it, it indicates SHP enabled by setting a very small buffer pool and SHP sizes
> [Mellanox] Fix inconsistence in the shared headroom pool initialization

- orchagent/aclorch.cpp
- tests/test_acl.py
**What I did**
Added IN_PORTS for L3 v4 and v6 tables
IN_PORTS qualifier was allowed for L3 table in 202012 release and below. Changes in #1982 removed that support leading to regression in some of our testcases. The following error was observed
ERR swss#orchagent: :- validateAclRuleMatch: Match SAI_ACL_ENTRY_ATTR_FIELD_IN_PORTS in rule RULE_1 is not supported by table DATAACL
Build swss deb with the changes and rule creation is successful. Rules are installed in the asic as well
/var/log/syslog.3.gz:Mar 13 23:01:55.331230 str2-7050qx-32s-acs-02 INFO swss#orchagent: :- doAclRuleTask: OP: SET, TABLE_ID: DATAACL, RULE_ID: RULE_1
/var/log/syslog.3.gz:Mar 13 23:01:55.355294 str2-7050qx-32s-acs-02 INFO swss#orchagent: :- createCounter: Created counter for …
> [acl] Add IN_PORTS qualifier for L3 table

- orchagent/muxorch.cpp
- orchagent/muxorch.h
- orchagent/routeorch.cpp
- tests/test_mux.py
**What I did**
Manual cherry-pick of https://github.com/sonic-net/sonic-swss/pull/2982 and https://github.com/sonic-net/sonic-swss/pull/2999
- Fixed a bug where cache was not removing entry when an ecmp mux route gets updated to a single nexthop route. And added test case to cover the edge case.
- Fixed a bug where multiple routes pointing to the same nhg would not remove the route from m_nextHops cache in routeorch
- Refactored multi_mux_nexthops tests and added new test cases
Mux switchover was failing because it was skipping over the route in updateNextHopRoutes.
Caught the bug while refactoring, this will cause issues with switchover if one of the routes is removed
MSFT ADO - 26099588
Ran refactored tests on local vstest setup, and all test cases …
> [202311][muxorch] Fixing cache bug in updateRoute logic and Fixing bug with multiple routes pointing to nhg

- cfgmgr/buffermgr.cpp
- tests/test_buffer_traditional.py
Fix for: 
[swss] BUFFER_PG and BUFFER_QUEUE configs are not getting applied on new ports created from dynamic breakout #2865
and most l likely other bugs related to dynamic buffer management.
**What I did**
Fixed bug that would cause an infinite loop in buffermgr.cpp when sending a non-set command (eg. delete)
The Bug would cause buffermgrd to be stuck in infinite loop, blocking its function.
Buffer configuration after deletion of a port(eg. dynamic port breakout command) will now be correctly processed. This was checked through log outputs on buffermgrd
The switch statement which would normally erase buffer events was moved to be inside the if-statement which would only enter if the event is a SET event. This was introduced in …
> [buffermgrd] Move switch-statement outside of if-statement in BufferMgr::doTask

- orchagent/port/porthlpr.cpp
- orchagent/port/porthlpr.h
- orchagent/portsorch.cpp
- tests/mock_tests/portsorch_ut.cpp
**What I did**
Fixing an issue when setting some port attribute in APPL_DB triggers serdes parameters to be re-programmed with port toggling. Made portsorch to handle only those attributes that were pushed to APPL_DB, so that serdes programming happens only by xcvrd's request to do so.
To fix an issue seen on warm-reboot. After orchagent reconciles, portmgrd sends another update to APPL_DB PORT_TABLE to sync. That trigger port flapping as portsorch does not handle just the fields that got pushed but all fields it has cached in ```m_portConfigMap```.
This also causes unconditionally re-set serdes attributes on any port attribute change, e.g.:
```
config interface mtu Ethernet136 9100
```
```
2024-01-18.09:02:30.712260|s|SAI_OBJECT_TYPE_PORT:oid:0x100000000001e|SAI_PORT_ATTR …
```
> [portsorch] process only updated APP_DB fields when port is already   created

- cfgmgr/coppmgr.cpp
- cfgmgr/coppmgr.h
- tests/mock_tests/Makefile.am
- tests/mock_tests/copp_ut.cpp
**What I did**
Refactoring coppmgr mock tests
After migration to bookworm, coppmgr tests started failing due to the use of sudo commands.
```
[----------] 1 test from CoppMgrTest
[ RUN      ] CoppMgrTest.CoppTest
sudo: pam_open_session: Too many open files
sudo: policy plugin failed session initialization
copp_ut.cpp:28: Failure
Expected equality of these values:
status
Which is: 256
0
CoppMgrTest.CoppTest (107 ms)
1 test from CoppMgrTest (107 ms total)
```
Avoided the logic of replacing the files using sudo by slightly refactoring the code.
Run the UT to verify.
> [Copp]Refactor coppmgr tests

- orchagent/Makefile.am
- orchagent/crmorch.cpp
- orchagent/crmorch.h
- orchagent/notifications.cpp
- orchagent/notifications.h
- orchagent/orchdaemon.cpp
- orchagent/orchdaemon.h
- orchagent/saihelper.cpp
- orchagent/twamporch.cpp
- orchagent/twamporch.h
- tests/conftest.py
- tests/dvslib/dvs_twamp.py
- tests/mock_tests/Makefile.am
- tests/mock_tests/mock_orchagent_main.h
- tests/mock_tests/portal.h
- tests/mock_tests/twamporch_ut.cpp
- tests/mock_tests/ut_saihelper.cpp
- tests/test_twamp.py
**What I did**
Implemented the TWAMP Light feature according to the SONiC TWAMP Light HLD(https://github.com/sonic-net/SONiC/pull/1320).
Part of the TWAMP Light feature support.
It Implemented VS test.
sonic-swss-common: https://github.com/sonic-net/sonic-swss-common/pull/823
sonic-sairedis: https://github.com/sonic-net/sonic-sairedis/pull/1306
> [orchagent] TWAMP Light orchagent implementation

- orchagent/neighorch.cpp
- orchagent/orch.cpp
- tests/test_virtual_chassis.py
**What I did**
On T2-VOQ chassis Emulation with multi-asic linecards, iBGP sessions dont come up. Related Issue: https://github.com/sonic-net/sonic-buildimage/issues/18129
This PR fixes above issue. More details:
a. iBGP packet path is different in real target as compared to vs. 
b. In real target, iBGP packets go out via IB interface, which get recycled to ingress pipeline and it does hostTable lookup for the packet to go out over Fabric link (For this to work, in Kernel Neighbor entries were programmed differently than in asic). 
In kernel, neighbor entries were programmed with MyMAC and in Asic Neighbor entries were programmed with the received MAC. This was done to make sure that CPU generated packet can do hostlookup in asic (packet to get promoted to L3(my mac)).  
For more details, …
> T2-VOQ-VS: Fix iBGP bringup issue 

- fdbsyncd/fdbsync.cpp
- What I did
extern_learn flag is added while programming the fdb entry into the Kernel. This will make sure that kernel doesn't age out the fdb entry. (#15004)
- How I did it
A flag extern_learn will be passed while programing the fdb entry. ([#15004](https://github.com/sonic-net/sonic-buildimage/issues/15004))
- How to verify it
Tested MAC add/del to the Kernel from the local FDB entry. ([#15004](https://github.com/sonic-net/sonic-buildimage/issues/15004))
Signed-off-by: kishore.kunal@broadcom.com
> [Fdbsyncd] Adding extern_learn flag with fdb entry so Kernel doesn't age out

- orchagent/portsorch.cpp
- tests/mock_tests/portsorch_ut.cpp
**What I did**
Updating oper FEC status in state_db after warm-reboot as part of refresh port status call
Oper FEC was not properly displayed after warm-boot. Hence fixing the issue. 
With the issue
```
Interface    FEC Oper    FEC Admin
-----------  ----------  -----------
Ethernet0         N/A          N/A
Ethernet4         N/A         auto
Ethernet8         N/A         auto
Ethernet12         N/A         auto
Ethernet14         N/A          N/A
Ethernet16         N/A         auto
```
After the fix
```
Interface    FEC Oper    FEC Admin
-----------  ----------  -----------
Ethernet0          rs          N/A
Ethernet4        none         auto
Ethernet8        none         auto
Ethernet12          fc         auto
Ethernet14          fc          N/A
Ethernet16          fc …
```
> Fix oper FEC retrieval after warmboot

- fpmsyncd/routesync.cpp
- fpmsyncd/routesync.h
- tests/mock_tests/fake_producerstatetable.cpp
- tests/mock_tests/fpmsyncd/test_routesync.cpp
**What I did**
Fix fpmsyncd crash when evpn is configured with fib suppression enabled. When protocol is not set, it's value is empty and fpmsyncd throws exception trying to covert to int and exits https://github.com/sonic-net/sonic-swss/blob/04912ad05aab8f4ebc40bcec70f00492a886e2ce/fpmsyncd/routesync.cpp#L1437. Protocol field was not extracted in the evpn flow. Decoding protocol from raw message fixed the issue.
To handle BGP suppress fib and evpn interop
Manually verified the fix. Added UT to cover.
> [EVPN]Fix fpmsyncd crash when EVPN type5 is received with bgp fib suppression enabled

- orchagent/portsorch.cpp
- tests/mock_tests/Makefile.am
- tests/mock_tests/mock_subscriberstatetable.cpp
- tests/mock_tests/portsorch_ut.cpp
**What I did**
Process TRANSCEIVER_INFO STATE_DB table on warm start to configure SAI_PORT_ATTR_HOST_TX_SIGNAL_ENABLE on warm boot.
Fix an issue that the port becomes operationally down after APPLY_VIEW.
Run warm-reboot.
> [portsorch] Handle TRANSCEIVER_INFO table on warm boot

- orchagent/p4orch/acl_rule_manager.cpp
- orchagent/p4orch/acl_table_manager.cpp
- orchagent/p4orch/acl_util.cpp
- orchagent/p4orch/acl_util.h
- orchagent/p4orch/ext_tables_manager.cpp
- orchagent/p4orch/ext_tables_manager.h
- orchagent/p4orch/gre_tunnel_manager.cpp
- orchagent/p4orch/l3_admit_manager.cpp
- orchagent/p4orch/mirror_session_manager.cpp
- orchagent/p4orch/neighbor_manager.cpp
- orchagent/p4orch/next_hop_manager.cpp
- orchagent/p4orch/p4orch_util.cpp
- orchagent/p4orch/route_manager.cpp
- orchagent/p4orch/router_interface_manager.cpp
- orchagent/p4orch/tables_definition_manager.cpp
- orchagent/p4orch/tables_definition_manager.h
- orchagent/p4orch/tests/acl_manager_test.cpp
- orchagent/p4orch/tests/gre_tunnel_manager_test.cpp
- orchagent/p4orch/tests/l3_admit_manager_test.cpp
- orchagent/p4orch/tests/mirror_session_manager_test.cpp
- orchagent/p4orch/tests/neighbor_manager_test.cpp
- orchagent/p4orch/tests/next_hop_manager_test.cpp
- orchagent/p4orch/tests/route_manager_test.cpp
- orchagent/p4orch/tests/wcmp_manager_test.cpp
- orchagent/p4orch/wcmp_manager.cpp
**What I did**
This PR has no real code change. It is purely clang formatting.
It does the same as https://github.com/sonic-net/sonic-swss/pull/3080.
However, there are some mystery of the clang tool result in weird behaviors in the previous PR.
The previous PR run the following clang commands:
find orchagent/p4orch -name *.h -o -name .cpp | xargs clang-format -i -style="{BasedOnStyle: Microsoft, DerivePointerAlignment: false}"
find orchagent -name response_publisher -o -name return_code.h | xargs clang-format -i -style="{BasedOnStyle: Microsoft, DerivePointerAlignment: false}"
However, if we first convert the format to google style and change it back to Microsoft style, there are differences (mainly on the #include statement):
find orchagent/p4orch -name *.h -o -name *.cpp | xargs …
> Clang format change.

- orchagent/dash/dashorch.cpp
- tests/test_dash_vnet.py
**What I did**
Add proper handling of DASH ENI admin state
To fix DASH ENI admin state update logic
vstest for ENI admin state update
> [dash] fix ENI admin state update

- orchagent/twamporch.cpp
**What I did**
Explicitly initialized local variable.
We met below error message in sonic-buildimage armhf build (https://github.com/sonic-net/sonic-buildimage/pull/18334)
```
2024-04-16T05:39:14.6186367Z     inlined from 'task_process_status TwampOrch::createEntry(const std::string&, const std::vector<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > >&)' at twamporch.cpp:693:34:
2024-04-16T05:39:14.6187130Z /usr/include/c++/12/bits/stl_pair.h:535:42: error: 'hw_stats' may be used uninitialized [-Werror=maybe-uninitialized]
2024-04-16T05:39:14.6187615Z   535 |         : first(std::forward<_U1>(__x)), second(std::forward<_U2>(__y)) { }
2024-04-16T05:39:14.6188040Z       |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```
> [twamporch] Explicitly initialize local variable

- orchagent/portsorch.cpp
- tests/mock_tests/Makefile.am
- tests/mock_tests/mock_subscriberstatetable.cpp
- tests/mock_tests/portsorch_ut.cpp
Backport of https://github.com/sonic-net/sonic-swss/pull/3087
**What I did**
Process TRANSCEIVER_INFO STATE_DB table on warm start to configure SAI_PORT_ATTR_HOST_TX_SIGNAL_ENABLE on warm boot.
Fix an issue that the port becomes operationally down after APPLY_VIEW.
Run warm-reboot.
> [202311][portsorch] Handle TRANSCEIVER_INFO table on warm boot

- orchagent/aclorch.cpp
- tests/dvslib/dvs_acl.py
- tests/test_acl.py
**What I did**
This PR is to fix https://github.com/sonic-net/sonic-buildimage/issues/18719 
When ACL rule is created for the first time, a flex counter is created and registered https://github.com/sonic-net/sonic-swss/blob/9e183a650cf38e0d5af46adc1342dcde85ecb84d/orchagent/aclorch.cpp#L4076
When the same ACL rule is being updated, the FlexCounter created before is not removed, and another FlexCounter is created and registered.
Fix the issue that FlexCounter is duplicated when updating existing ACL rule.
1. Verified by VS test
2. Verified by building orchagent and run on a physical device
> [ACL] Remove flex counter when updating ACL rule

- orchagent/Makefile.am
- orchagent/eliminate_events.lua
- orchagent/notifications.cpp
- orchagent/notifications.h
- orchagent/orchdaemon.cpp
- orchagent/p4orch/tests/Makefile.am
- orchagent/p4orch/tests/test_main.cpp
- orchagent/switchorch.cpp
- orchagent/switchorch.h
- tests/mock_tests/Makefile.am
- tests/mock_tests/mock_table.cpp
- tests/mock_tests/switchorch_ut.cpp
**What I did**
Support ASIC/SDK health event
1. Initialization
- Fetch capabilities and expose to STATE_DB
- Register the event handler and categories for each severity when supported
2. Handle suppress ASIC/SDK health event categories
3. Handle ASIC/SDK health event reported by SAI redis in the callback context
- Decode it
- Log message
- Send event
4. Eliminate old events of each severity according to users' configuration
Unit test.
> Support ASIC/SDK health event

- orchagent/fabricportsorch.cpp
- orchagent/fabricportsorch.h
- tests/test_fabric_capacity.py
- tests/test_fabric_port_isolation.py
**What I did**
Add fabric capacity monitoring code.
The HLD can be found at 
https://github.com/sonic-net/SONiC/blob/master/doc/voq/fabric.md
The current design does not cover the card hotswap/OIR cases.  We will discuss how to handle that in a separate proposal. 
> Add fabric capacity monitoring code.

- orchagent/port/port_capabilities.cpp
**What I did**
Change log level from ERR to WARN for pfc asym not supported
To address issue reported in https://migsonic.atlassian.net/browse/MIGSMSFT-473
Load new debian on testbed and check the log.
```
cisco@r2-lc0:~$ sudo cat /var/log/syslog | grep "queryPortAttrCapabilities"
Apr 25 22:52:26.787428 r2-lc0 WARNING swss1#orchagent: :- queryPortAttrCapabilities: Failed to get attribute(SAI_PORT_ATTR_PRIORITY_FLOW_CONTROL_TX) capabilities
Apr 25 22:52:26.787846 r2-lc0 WARNING swss1#orchagent: :- queryPortAttrCapabilities: Failed to get attribute(SAI_PORT_ATTR_PRIORITY_FLOW_CONTROL_RX) capabilities
cisco@r2-lc0:~$ 
```
> [orchagent] Change log level from ERR to WARN for pfc asym not supported

- orchagent/debugcounterorch.cpp
Partially addresses the debug counter comment in https://github.com/sonic-net/sonic-buildimage/issues/11798#issuecomment-1366192486
**What I did**
During the removal of drop counters, the counter is deleted first followed by removing it from flexcounter. This would result in a race condition where counterpoll might try to access the counter after it is deleted.
```
Apr 22 21:55:33.131134 r-panther-01 INFO python[125700]: ansible-command Invoked with _raw_params=config dropcounters delete TEST warn=True _uses_shell=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 21:55:33.611079 r-panther-01 NOTICE syncd#SDK: [SAI_DEBUG_COUNTER.NOTICE] ./src/mlnx_sai_debug_counter.c[1817]- mlnx_remove_debug_counter: Remove …
```
> [DropCounter]Fix the ordering issue with dropcounter

- orchagent/portsorch.cpp
In https://github.com/sonic-net/sonic-swss/pull/3052 2 new fields were added the `PORT_TABLE` in `APPL_DB`: `last_down_time` and `last_up_time`.
But their value was generated with `std::ctime` which includes a newline character at the end of the character array which causes issues for parsing the output.
Output today:
```
> sonic-db-cli APPL_DB hgetall PORT_TABLE:Ethernet8
{'admin_status': 'up', 'alias': 'Ethernet3/1', 'asic_port_name': 'Eth8', 'coreId': '0', 'corePortId': '3', 'description': 'Ethernet8-connected-to-@Ethernet5/4/1', 'fec': 'rs', 'index': '3', 'lanes': '4,5', 'mtu': '9100', 'numVoq': '8', 'pfc_asym': 'off', 'role': 'Ext', 'speed': '100000', 'tpid': '0x8100', 'oper_status': 'up', 'flap_count': '1', 'last_up_time': 'Wed Apr 10 00:18:44 2024
', 'system_oper_status': 'up', …
```
> Remove unwanted newline character at end of timestamp

- orchagent/pfc_detect_mellanox.lua
**What I did**
Adjust PFC watchdog detection algorithm to reduce false alarms.
In the old PFC watchdog detection algorithm, the PFC watchdog can be triggered if either of the following conditions is satisfied in a detection interval:
1. There are packets accumulated in the queue && there is no packet sent out of the queue && there are PFC frames received in the queue
2. There is no packet accumulated in the queue and there are PFC frames received and blocking more than 80% of the detection interval.
The new PFC watchdog detection algorithm merges two conditions into one:
The PFC watchdog is triggered only if:
- There are packets accumulated in the queue && there is no packet sent out of the queue && there are PFC frames received and blocking more than 99% of the detection interval. …
> [Mellanox] PFC watchdog long term solution to reduce false alarm

- orchagent/portsorch.cpp
- orchagent/portsorch.h
**What I did**
Add transceiver info to bake only if saiHwTxSignalSupported and  saiTxReadyNotifySupported are supported
The executor is added only if the above flags are supported https://github.com/sonic-net/sonic-swss/blob/f62eed23fcdd62544f3a7a0e5cea15b0cafa9600/orchagent/portsorch.cpp#L596
On unsupported platforms the following error logs will be observed
```
swss#orchagent: :- addExistingData: No consumer TRANSCEIVER_INFO in Orch
```
Running warmboot with the fix
> Add transceiver info to bake only if supported

- orchagent/vrforch.cpp
- tests/test_evpn_l3_vxlan.py
**What I did**
Update state_db VRF_OBJECT table when there is update flow in the Vrf. 
Since there is no EVPN nvo the addOperation returns  here without updating state_db
https://github.com/sonic-net/sonic-swss/blob/2e6c5b209d575f73b867de9f3e56b3be4066acec/orchagent/vrforch.cpp#L114
However later when evpn nvo arrives there is no subsequent update operation.
This will result in removal message not getting processed due to the check in vrfmgrd
https://github.com/sonic-net/sonic-swss/blob/a821af0421de316555146615cffd4108ec566e20/cfgmgr/vrfmgr.cpp#L208
```
May  4 03:37:49.578686 r-anaconda-51 INFO swss#orchagent: :- updateVrfVNIMap: VRF 'Vrf1' vni 500200 old_vni 0
May  4 03:37:49.578701 r-anaconda-51 NOTICE swss#orchagent: :- updateVrfVNIMap: updateVrfVNIMap unable to find EVPN VTEP
May  4 …
```
> [VRF]Fixing vrf orch to update state_db when evpn nvo arrives late

- orchagent/switchorch.cpp
- tests/test_switch.py
**What I did**
Add support to update ECMP and LAG hash offset. Orchagent checks for SAI attribute capability and configure the offset values.
To avoid ECMP hash imbalance across T0 and T1s, different hash offsets can be configured.
sonic-mgmt tests ipfwd/test_nhop_group.py
sonic-mgmt PR to update the existing test with the nexthop rewrites after default hash_offset changes: https://github.com/sonic-net/sonic-mgmt/pull/12765
> Add support for ECMP and LAG hash offset

- orchagent/bufferorch.cpp
- orchagent/bufferorch.h
- orchagent/copporch.cpp
- orchagent/copporch.h
- orchagent/fabricportsorch.cpp
- orchagent/fabricportsorch.h
- orchagent/flex_counter/flex_counter_manager.cpp
- orchagent/flex_counter/flex_counter_manager.h
- orchagent/flexcounterorch.cpp
- orchagent/flexcounterorch.h
- orchagent/intfsorch.cpp
- orchagent/intfsorch.h
- orchagent/macsecorch.cpp
- orchagent/main.cpp
- orchagent/p4orch/tests/test_main.cpp
- orchagent/pfcwdorch.cpp
- orchagent/pfcwdorch.h
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- orchagent/saihelper.cpp
- orchagent/saihelper.h
- orchagent/vxlanorch.cpp
- tests/mock_tests/Makefile.am
- tests/mock_tests/bufferorch_ut.cpp
- tests/mock_tests/flexcounter_ut.cpp
- tests/mock_tests/mock_orch_test.h
- tests/mock_tests/mock_orchagent_main.cpp
- tests/mock_tests/mock_table.cpp
- tests/mock_tests/qosorch_ut.cpp
- tests/mock_tests/routeorch_ut.cpp
**What I did**
Fix flex counter out-of-order issue by notifying counter operations using SelectableChannel
Depends on https://github.com/sonic-net/sonic-sairedis/pull/1362
Currently, the operations of SAI objects and their counters (if any) are triggered by different channels, which introduces racing conditions:
- the creation and destruction of the objects are notified using the `SelectableChannel`,
- the operations of counters, including starting and stopping polling the counters, are notified by listening to the `FLEX_COUNTER` and `FLEX_COUNTER_GROUP` tables in the `FLEX_COUNTER_DB`
- The orchagent always respects the order when starting/stopping counter-polling (which means to start counter-polling after creating the object and to stop counter-polling before …
> Fix flex counter out-of-order issue by notifying counter operations using SelectableChannel

- orchagent/nhgorch.cpp
- orchagent/nhgorch.h
- tests/test_nhg.py
**What I did**
Implemented recursive nexthop group enhancement in Orchagent (NhgOrch). They have been proposed in:
https://github.com/sonic-net/SONiC/pull/1636
These changes are required to handle a new field - "nexthop_group" in the App DB NEXT_HOP_GROUP_TABLE. Such nexthop groups are called recursive nexthop groups. This field contains the list of member (singleton) nexthop groups. Such recursive nexthop groups are represented by NEXT_HOP_GROUP objects.
> [Orchagent] Recursive nexthop group enhancement

- orchagent/portsorch.cpp
- orchagent/portsorch.h
**What I did**
Update the call to setHostTxReady() to receive Port instead of port_id.
So we won't need to call getPort() inside the function, and we will be able to call setHostTxReady from within port initialization. 
Tested it on running switch.
> Refactor Host Tx Ready setting

- .azure-pipelines/test-docker-sonic-vs-template.yml
**What I did**
Use requests 2.31.0 instead of latest 2.32.0
requests 2.32.0 breaks Test stage.
> revert requests from 2.32.0 to 2.31.0

- cfgmgr/coppmgr.cpp
- orchagent/copporch.cpp
- tests/test_copp.py
Fixes https://github.com/sonic-net/sonic-buildimage/issues/18226
**What I did**
Fix coppmgr when there are multiple feature tables using same trap.
In addition fixed the following issues
1) When a new feature is added which is not present during the init, the copp entry will not get programmed. 
2) When a copp trap attribute is set, it overrides the other existing attributes
Fix copp issues
Added UT to verify
> [COPP]Fix coppmgr when there are multiple features using same trap

- orchagent/port/portcnt.h
- orchagent/port/porthlpr.cpp
- orchagent/port/porthlpr.h
- orchagent/port/portschema.h
**What I did**
https://github.com/sonic-net/sonic-buildimage/pull/18499 Added support for subport values to be automatically calculated and inserted on creation of config_db.json. This change succeeds in adding the subport value into config_db.json - but it results in a log 
`WARNING #orchagent: message repeated 18564 times: [ :- parsePortConfig: Unknown field(subport): skipping ...]`
being printed. This prevents the log being printed by handling the subport value.
To prevent the orchagent log
I manually tested on an Arista device that the log no longer appears
Question to reviews - should we assert on an unhandled/unknown field ? Rather than logging this message, it is easy to miss and the value still ends up in config_db
> Parse subport value added to config_db

- cfgmgr/vlanmgr.cpp
**What I did**
Disable MAC learning for Link Local Multicast Frames on the Linux Bridge
The 01:80:c2 link local frame is used to control the purpose. To disable the MAC learning for these frames to prevent MAC flap if there are multiple links between 2 switches.
Inject LLDP frame and use `sudo bridge fdb show` to check
> [Bridge] Disable MAC learning for Link Local Mulitcast Frames on the linux Bridge

- .azure-pipelines/test-docker-sonic-vs-template.yml
What I did
Use requests 2.31.0 instead of latest 2.32.0
Why I did it
requests 2.32.0 breaks Test stage.
**What I did**
> revert requests from 2.32.0 to 2.31.0 (#3154)

- tests/test_route.py
**What I did**
Revert suppress FIB pending feature
Some unresolved FRR issues in current version
Build and run
> [tests] mark suppress-fib-pending VS test as expected to fail

- orchagent/vnetorch.cpp
- orchagent/vnetorch.h
- tests/test_vnet.py
**What I did**
Support dynamic decap rule generation based on the Vxlan tunnel route of Overlay ECMP.
This depends on: https://github.com/sonic-net/sonic-swss/pull/3117
To enable SONiC with the capability to decap IPinIP packets with dest IP in the Overlay ECMP Vxlan tunnel route prefix.
VS test:
```
test_vnet.py::TestVnetOrch::test_vnet_orch_1 PASSED                                                                                                                                            [  3%]
test_vnet.py::TestVnetOrch::test_vnet_orch_2 PASSED                                                                                                                                            [  6%]
test_vnet.py::TestVnetOrch::test_vnet_orch_3 PASSED …
```
> [subnet decap] Add subnet decap rule based on overlay ECMP

- orchagent/qosorch.cpp
- tests/mock_tests/qosorch_ut.cpp
**What I did**
Do not apply the global DSCP to TC map to the switch object until the mapping object has been created.
Fix issue: if orchagent handles tables in the following order, it will fail in step 1 and the configure will never applied.
1. PORT_QOS_MAP|global object
2. and then DSCP_TO_TC object
Mock and manual test
> Do not apply QoS mapping object until it is resolved

- .azure-pipelines/build-docker-sonic-vs-template.yml
Allowing partial build for sairedis to make sure build isn't skipping latest on branch.
**What I did**
add `allowPartiallySucceededBuilds: true` to docker-sonic-vs build template
swss PR is pulling from an older build, which does not have critical changes to syncd
> [build-docker-sonic-vs] Allowing partial build for sairedis

- orchagent/neighorch.cpp
- tests/mock_tests/mock_orch_test.h
- tests/mock_tests/neighorch_ut.cpp
202311 cherry-pick of https://github.com/sonic-net/sonic-swss/pull/3165
**What I did**
Fixes https://github.com/sonic-net/sonic-buildimage/issues/18890
- If we try to learn an existing neighbor on a different VLAN in the same VRF, delete the old neighbor entry before creating the new one.
- For all other scenarios, proceed with neighbor learning normally.
Allow learning the same IP in two different VRFs
Run the C++ unit tests
> [202311] Handle learning duplicate IPs on different VRFs (#3165)

- orchagent/portsorch.cpp
- orchagent/portsorch.h
**What I did**
Cherry-picked following PR https://github.com/sonic-net/sonic-swss/pull/3133 from master sonic-swss. 
So we won't need to call getPort() inside the function, and we will be able to call setHostTxReady from within port initialization.
> [202311]Update setHostTxReady() to receive Port instead of portId (#3133)

- lib/recorder.cpp
**What I did**
Rotate file before writing the log for record files.
If we configure logrotate to compress, the old file stream will write to void after the old file is rotated and compressed. This PR changes the order of write and rotate. It will always rotate first and then write. There might still be log lost if logrotate sends HUP signal too late.
N/A
N/A
> Rotate record file before writing new log.

- orchagent/muxorch.cpp
- tests/test_mux.py
mux neighbors that were not the configured mux ip were being treated as active.
cherry-pick of: https://github.com/sonic-net/sonic-swss/pull/3187
**What I did**
use isNeighborActive to determine if neighbor is active for updateRoute logic
bug was causing crash when neighbor was not the same as the mux configured neighbor
added new vstests and ran locally
tests passed on master PR
tested on 202305 dualtor testbed:
```
w/out fix:
Jun  9 06:05:46.642266 svcstr-7050-acs-4 NOTICE swss#orchagent: :- setState: [Ethernet12] Set MUX state from active to standby
Jun  9 06:05:46.642559 svcstr-7050-acs-4 NOTICE swss#orchagent: :- nbrHandler: Processing neighbors for mux Ethernet12, enable 0, state 2
Jun  9 06:05:46.642719 svcstr-7050-acs-4 NOTICE swss#orchagent: …
```
> [202305][muxorch] Fixing bug with updateRoute and mux neighbors

- cfgmgr/vlanmgr.cpp
**Why  I did**
Database privileges give RW permission to /sys. In container hardening, when remove database privileges, /sys is changed to RO permission for all Sonic containers
```
admin@vlab-08:~$ docker exec -it swss1 bash
root@vlab-08:/# mount | grep sys
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
```
When /sys is RO, there will be some errors in vlanmgrd.
```
2024 Jun 12 22:14:30.915170 vlab-08 INFO swss1#supervisord: vlanmgrd sh: 1: cannot create /sys/class/net/Bridge/bridge/vlan_filtering: Read-only file system
2024 Jun 12 22:14:30.921253 vlab-08 INFO swss1#supervisord: vlanmgrd sh: 1: cannot create /sys/class/net/Bridge/bridge/no_linklocal_learn: Read-only file system
2024 Jun 12 22:14:30.922472 vlab-08 ERR swss1#vlanmgrd: :- main: Runtime error: /bin/echo 1 > …
```
> [vlanmgr] use IP command for vlan_filtering and no_linklocal_learn, remove echo command

- teamsyncd/teamsync.cpp
- teamsyncd/teamsync.h
Fix for [#3192](https://github.com/sonic-net/sonic-swss/issues/3192)
In teamSync::addLag method, update lag "oper_status" status in state_db.
```c++
bool lag_update = true;
/* Return when the team instance has already been tracked */
if (m_teamSelectables.find(lagName) != m_teamSelectables.end())
{
auto tsync = m_teamSelectables[lagName];
if (tsync->admin_state == admin_state && tsync->oper_state == oper_state && tsync->mtu == mtu)
return;
tsync->admin_state = admin_state;
tsync->oper_state = oper_state;
tsync->mtu = mtu;
lag_update = false;
}
FieldValueTuple s("state", "ok");
fvVector.push_back(s);
if (m_warmstart)
{
m_stateLagTablePreserved[lagName] = fvVector;
}
else
{
m_stateLagTable.set(lagName, fvVector);
}
``` 
Manual Testing
> [teamsyncd] Update "oper_status" of LAG_TABLE in state_db (#3192)

- orchagent/portsorch.cpp
- tests/mock_tests/portsorch_ut.cpp
**What I did**
Remove the buffer maximum parameter table entry when the port is removed.
To avoid the informational message `handleBufferMaxParam: BUFFER_MAX_PARAM: Port Ethernet190 is not configured, need retry` after the port is removed.
Unit test and manual test
> Remove buffer maximum parameter table when the port is removed

- cfgmgr/vxlanmgr.cpp
- cfgmgr/vxlanmgr.h
* On sonic-vs linux vxlan interfaces serve as data plane, so disable fdb learning on them when it is disabled through SAI
**What I did**
When vxlan tunnels are supposed to have fdb learning disabled, I also disabled fdb learning on vxlan linux interfaces
For EVPN feature the learing on vxlan interfaces should be disabled, but it is not disabled on vxlan linux interfaces, and thus causes trouble when testing sonic-vs EVPN setups on virtual machines.
With existing vxlan tunnel create new vlan and vxlan map, then verify that vxlan interface has fdb learning off. Save config, reboot the device and verify that vxlan interface still has learning off.
```
yaroslav_fedoriachenko@Leaf-1:~$ config vlan add 200
Root privileges are required for this operation …
```
> [vxlanmgr]: Add disabling of fdb learning for linux vxlan interfaces

- orchagent/intfsorch.cpp
**What I did**
Fixes: https://github.com/sonic-net/sonic-buildimage/issues/19357
In the  sonic-mgmt pc test suite. When an empty lag is created. The portchannel changed is sync'ed to the remote LC even if there portchannel has no route interface created. This results in a dummy route interface created on the remote LC.
So when the empty port channel is removed on the local card, the removal fails in the remote LC because of the dummy route interface.
Add a fix to sync the portchannel interface state to the remote LC only when there routeinterface is created on the local LC.
Run sonic-mgmt failed PC tests on chassis
```
pc/test_po_update.py::test_po_update_io_no_loss[str2-sonic-lc5-1-0] PASSED 
pc/test_po_update.py::test_po_update[str2-sonic-lc5-1-1] …
```
> [Chassis][voq] do not synchronize the system interface state if there is no rif assciated with the port

- orchagent/switchorch.cpp
**What I did**
Changed it so that if the configuration has an unsupported attribute, it would continue processing the rest of the configuration rather than break out of the loop and end the processing immediately.
Also added syslogs to make it more clear.
Would cause FDB aging time to stay default (0) and never cause aging to occur. Fixes this bug in sonic-mgmt: https://github.com/sonic-net/sonic-mgmt/issues/13375
Caused by this commit `https://github.com/sonic-net/sonic-swss/commit/2f8bd9cf6df839abec0ecc9bf31fc9c4b06a6c47`
TBD
> switchorch: fixed unsupported attribute causes skipping of processing the rest of the configurations

- .azure-pipelines/build_and_install_module.sh
**What I did**
The current version of the script does not work at all when the host kernel is Azure's 5.15 kernel on Ubuntu 20.04. It does seem to work with 5.11 and older.
Update the script to add support for building and loading the kernel modules for the 5.15 kernel, while keeping support for the non-HWE kernel.
In addition, use a separate updates/sonic directory for the kernel modules we compile, to make it clear they were compiled separately and don't come from the official kernel build packages.
Finally, add a warning if we're compiling a kernel module for a different version of the kernel than what is currently running.
This is a cherry-pick of sonic-net/sonic-swss-common#720
> Revamp module build script to make it work for 5.15 on Ubuntu 20.04

- orchagent/portsorch.cpp
This is a cherry-pick of https://github.com/sonic-net/sonic-swss/pull/3232
**What I did**
I added a query before setting host tx ready - must check that Oid exists before setting attribute to SAI.
When we do dynamic port breakout to a Fw-control port, portsorch receives a notification that something was deleted in TRANSCEIVER_INFO table from State DB, and tries to set HOST_TX_READY_SIGNAL_ENABLE attribute to false for the deleted OID. 
The issue is the Oid is already deleted and we receive an error from SAI. 
Run DPB on the switch
> Add a check if OID exists before setting Host Tx Ready Signal Enable

- orchagent/portsorch.cpp
- tests/mock_tests/portsorch_ut.cpp
**Why I did**
SAI_SWITCH_ATTR_SUPPORTED_OBJECT_TYPE_LIST is not a mandatory attribute and is not supported in some platforms. 
There is an error log seen for such platforms. Reduce noise by changing the verbosity to INFO. 
> Reduce log verbosity when the capability is not implemented

- orchagent/dash/dashrouteorch.cpp
- tests/_test_dash_crm.py
- tests/test_dash_vnet.py
**What I did**
For DASH_ROUTE_TABLE entries, change `action_type` references to `routing_type` references.
https://github.com/sonic-net/sonic-dash-api/pull/20 deprecates `action_type` in DASH_ROUTE_TABLE in favor of `routing_type` to more accurately describe the field.
Any downstream repositories which build SWSS will see a deprecation warning for `action_type` and builds with `-Werror` set will not compile.
> [DASH] Remove deprecated 'action_type' refs

- orchagent/fabricportsorch.cpp
- orchagent/fabricportsorch.h
- tests/test_fabric_port_isolation.py
**What I did**
reset the skip error counters for fabric link monitoring if a link was down and up again. 
The fabric link monitoring feature does not take care the peer card restart cases. Peer card reload could lead to links go in to isolation state, and that's a case where we can ignore the error due to the init churn.  So in this change , the skip error on init counters get reset if a link was down and up again. 
> Reset skip error counter on a fabric link if it was down.

- cfgmgr/buffer_headroom_mellanox.lua
**What I did**
1. Fix a bug in lossless headroom calculation regarding the small packet percentage which should be calculated in a size-based approach instead of packet-based
2. Adjust Mellanox-specific lossless headroom calculation algorithm
Manual test
Regression test https://github.com/sonic-net/sonic-mgmt/pull/14229
> [Mellanox] Update headroom calculation algorithm

- cfgmgr/teammgr.cpp
**What I did**
Close socket descriptor in checkPortIffUp.
Currently the file descriptor is not closed. It will cause descriptor leak.
N/A
N/A
> Close socket descriptor in checkPortIffUp.

- cfgmgr/portmgr.cpp
Fix portmgr write partial port config to app DB issue.
Test case test_add_remove_neg_admin_status unstable.
Improve portmgr code to write all port config with one API call.
Pass all UT.
Manually verify issue fixed.
Fix portmgr write partial port config to app DB issue.
> Fix portmgr write partial port config to app DB issue.

- cfgmgr/buffer_check_headroom_mellanox.lua
- cfgmgr/buffermgrdyn.cpp
**What I did**
Check maximum port headroom pool in dynamic buffer calculation
Depends on https://github.com/sonic-net/sonic-buildimage/pull/20085
To avoid orchagent from crash
Manual test
Regression test https://github.com/sonic-net/sonic-mgmt/pull/14479
> [Dynamic Buffer][Mellanox] Enhance port shared headroom pool check

- tests/dash/dash_db.py
- tests/dash/test_dash_acl.py
- tests/dvslib/dvs_hash.py
- tests/test_ipv6_link_local.py
Fix the issue where the test case randomly fails due to not waiting after updating the config DB.
Some test case randomly fails due to not waiting after updating the config DB.
Add few seconds wait after update config DB.
Pass all UT.
Manually verify issue fixed.
Fix the issue where the test case randomly fails due to not waiting after updating the config DB.
> Fix the issue where the test case randomly fails due to not waiting after updating the config DB.

- tests/mock_tests/portsorch_ut.cpp
- tests/mock_tests/switchorch_ut.cpp
Error is show up when we move  sai headers from v1.14 to v1.15
https://github.com/sonic-net/sonic-sairedis/pull/1431#issuecomment-2405924026
**What I did**
Fix tests so they can pass during backward compatibility break
because of breaking change in SAI headers, g++ requires all struct fields to be populated:
```
g++ -DHAVE_CONFIG_H -I. -I../..  -g -DNDEBUG  -std=c++14 -Wall ...... echo './'`warmrestarthelper_ut.cpp
switchorch_ut.cpp: In member function 'virtual void switchorch_test::SwitchOrchTest_SwitchOrchTestHandleEvent_Test::TestBody()':
switchorch_ut.cpp:295:83: error: missing initializer for member '_sai_switch_health_data_t::data' [-Werror=missing-field-initializers]
295 |         sai_switch_health_data_t data = {.data_type = SAI_HEALTH_DATA_TYPE_GENERAL};
| …
```
> [tests] Attempt to fix compatibility break from SAI headers

- orchagent/Makefile.am
- orchagent/p4orch/tests/Makefile.am
- orchagent/p4orch/tests/acl_manager_test.cpp
- orchagent/p4orch/tests/wcmp_manager_test.cpp
**What I did**
Make sure that the p4orch tests are always run (not just when code coverage is enabled), and fix the p4orch tests following the SAI update.
sonic-net/sonic-sairedis#1431 updated the SAI submodule to the latest version, and #3321 fixed some of the compatibility issues, but there were still some that got through, because p4orch tests are enabled only when code coverage is enabled.
> Fix p4orch tests after SAI update

- tlm_teamd/values_store.cpp
What I did: 
Fixes:
https://github.com/sonic-net/sonic-buildimage/issues/20059
Why  I did:
On T2 testbed with multiple backend port channel we have seen sometime Portchannel gets created fine and with entry in APP_DB and STATE_DB gets populated. tlm_teamd is able to get the teamdctl handle to get state dump view of teamd. However while getting dump if might have passed in 1st iteration but it might fail in 2nd iteration (transient issue in getting data using teamdctl) which result in deletion of State db entry which is not correct. Instead we should just clean up local cache and wait for retry done as part of Select Timeout cycle  where we try to get dump again. 
```
2024 Aug 27 20:33:56.985209 sfd-t2-sup INFO teamd0#supervisord: teammgrd Using team device "PortChannel02".
2024 Aug 27 …
```
> Fix the tlm_teamd deleting STATE_DB LAG_TABLE entry.

- tlm_teamd/values_store.cpp
What I did:
Original issue and and PR: https://github.com/sonic-net/sonic-swss/pull/3333
Why I did:
Fix the failure in `test_po_update.py` as seen in this PR checker: https://github.com/sonic-net/sonic-buildimage/pull/20610
Previous fix blocked State Db `LAG_MEMBER_TABLE` deletion which is not correct as this table is created by tlm_teamd (owner).
Intention was to prevent deletion of State Db `LAG_TABLE` owner of which is teamsyncd.
> Fix State Db LAG_MEMBER_TABLE removal not happening.

- cfgmgr/buffer_headroom_mellanox.lua
* [Mellanox] Update headroom calculation algorithm (#3235)
* Bug fix: small packet percentage should be byte-based instead of packet-based
Cherry-pick #3235 to the 202405 branch
**What I did**
> [Mellanox][202405] Update headroom calculation algorithm (#3235)

- orchagent/p4orch/tests/fake_portorch.cpp
- orchagent/port.h
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/mock_tests/portsorch_ut.cpp
Handler Port oper down error status notification as per [sai_port_error_status_t](https://github.com/opencomputeproject/SAI/blob/8b8fa85178383ae0a8bf1a64279934a6b3087837/inc/saiport.h#L84) flag as part of existing port oper status notification `sai_port_oper_status_notification_t`
**What I did**
Whenever Orchagent gets the notification for `port_state_change` for link down event, OA will update the error count for the error flags that are set and the timestamp of the error port down event in new STATE_DB table `PORT_OPERR_TABLE`
To correlate various error events like MAC local and remote fault with the link oper down status notification.
Since we don't have real hardware to test this modified notification, I modified the sairedis to generate this new …
> Handle Port oper down error status notification

- .azure-pipelines/test-docker-sonic-vs-template.yml
**What I did**
Fix pipeline error.
here is the error message:
```
/tmp/823d4a0e-75c7-4ca8-b487-06e1f38eae6d/restore.csproj : error NU1202: Package dotnet-reportgenerator-globaltool 5.4.1 is not compatible with net7.0 (.NETCoreApp,Version=v7.0) / any. Package dotnet-reportgenerator-globaltool 5.4.1 supports:
/tmp/823d4a0e-75c7-4ca8-b487-06e1f38eae6d/restore.csproj : error NU1202:   - net8.0 (.NETCoreApp,Version=v8.0) / any
/tmp/823d4a0e-75c7-4ca8-b487-06e1f38eae6d/restore.csproj : error NU1202:   - net9.0 (.NETCoreApp,Version=v9.0) / any
+ reportgenerator -reporttypes:Cobertura '-reports:tests/*coverage.xml' -targetdir:.
/agent/_work/_temp/057fa35b-9e5b-426a-bd88-2c5956cb8dcf.sh: line 2: reportgenerator: command not found
```
pipeline in this PR …
> [ci] Fix reportgenerator installation error

- tests/dash/test_dash_route_group.py
**What I did**
When grabbing the second route group OID, ensure that it is distinct from the first route group OID
The order in which DB keys are returned is not deterministic, so blindly taking the last key returned will sometimes lead to selecting the wrong OID
Run the test 10 times and verify they all pass. (Prior to the fix at least one run would fail, usually more)
> Ensure second route group OID is correct

- orchagent/flexcounterorch.cpp
- orchagent/p4orch/tests/fake_portorch.cpp
- orchagent/port.h
- orchagent/portsorch.cpp
- orchagent/portsorch.h
- tests/test_flex_counters.py
**What I did**
Verified the following scenarios
1. No BUFFER_QUEUE covering host CPU queue
```
Port    TxQ    Counter/pkts    Counter/bytes    Drop/pkts    Drop/bytes
-----------  -----  --------------  ---------------  -----------  ------------
Ethernet248    UC0               0                0            0           N/A
Ethernet248    UC1               0                0            0           N/A
Ethernet248    UC2               0                0            0           N/A
Ethernet248    UC3               0                0            0           N/A
Ethernet248    UC4               0                0            0           N/A
Ethernet248    UC5               0                0            0           N/A
Ethernet248    UC6               0 …
```
> Create counter for the queue to which the host CPU traffic is sent when create_only_config_db_buffers  is enabled

- tests/dash/test_dash_route_group.py
**What I did**
Skip VS test `dash/test_dash_route_group.py::test_bound_route_group_immutable`
This test causes orchagent to crash since the VS SAI has not been updated to include implicit deletion of high-volume DASH objects (https://github.com/sonic-net/SONiC/blob/master/doc/dash/dash-sonic-hld.md#18-implicit-deletion-of-sai-objects)
> Skip DASH route group immutability test

- fpmsyncd/fpmsyncd.cpp
- fpmsyncd/fpmsyncd.h
- fpmsyncd/routesync.cpp
**What I did**
- change the pipeline size for `RouteSync`
- modify the fpmsyncd flush behavior so that it could delay the flush with an expiring timer
- the timer is simulated by setting the timeout for `select` function
- to batch the data that fpmsyncd flush to `APP_DB`
measure the performance with [PerformanceTimer](https://github.com/sonic-net/sonic-swss-common/pull/893)  ![GitHub issue/pull request detail](https://img.shields.io/github/pulls/detail/state/Azure/sonic-swss-common/893)
> [fpmsyncd] support pipeline to flush with a timer

- orchagent/aclorch.cpp
**What I did**
Fixed 3 narrowing conversion issues in the code.
g++ 9.4.0 and 10.5.0 both reported compile errors when trying to compile `aclorch.cpp` using `-Werror` and `-Wconversion` flags.
I compiled the code using g++ 10.5.0 after the changes it was successful.
> Fixed compile errors caused by conversion from `int` to `uint16_t`

- orchagent/lagids.lua
- tests/test_virtual_chassis.py
**What I did**
Create SYSTEM_LAG_IDS_FREE_LIST for assign lagId for all portchannel creation.  
1)  Portchannel creation
a)  If Portchannel is created with a valid plagid
*  check if plagid is in free list, use plagid and remove it from SYSTEM_LAG_IDS_FREE_LIST.  Add this lagid to the SYSTEM_LAG_ID_SET for debug info
* If plagid is not in the FREE_LIST,  lpop and use the first lagid from the SYSTEM_LAG_IDS_FREE_LIST.  Add this lagid to the SYSTEM_LAG_ID_SET for debug info
b) If Portchannel is created with invalid plagid or without any lagid
* lpop and use the first lagid from the SYSTEM_LAG_IDS_FREE_LIST.  Add this lagid to the SYSTEM_LAG_ID_SET for debug info  
2) Portchannel delection
* Append the lagid to the end of SYSTEM_LAG_IDS_FREE_LIST.  Also remove it from SYSTEM_LAG_ID_SET.
This …
> [Chassis][LAG_ID] Address the same lagid been used in two different LCs issue

- orchagent/bulker.h
- orchagent/mplsrouteorch.cpp
- orchagent/neighorch.cpp
- orchagent/neighorch.h
- orchagent/nhgorch.cpp
- orchagent/p4orch/tests/mock_sai_next_hop.h
- orchagent/p4orch/tests/next_hop_manager_test.cpp
- orchagent/routeorch.cpp
- tests/mock_tests/aclorch_ut.cpp
- tests/mock_tests/mock_sai_api.h
- tests/mock_tests/mux_rollback_ut.cpp
Using nexthop object bulker when processing neighbors. This is only enabled during mux switchover.
When processing neighbors during mux switchover:
- add nexthop object to add/remove using nexhop bulker
- flush nexthop bulker
- post-process bulker results
**What I did**
Added nexthop bulking operations to addNexthop function in neighOrch.
This is currently only used when processing neighbors during mux switchover
Neighbor bulking during mux switchover was still limited by sai calls made to create/remove nexthops. This uses the existing sai bulk nexthop api to also bulk program nexthops
Ran switchover testing on 7260cx3 dualtor testbed running 202405
> [muxorch] Process nexthops using bulker during mux switchover

- orchagent/neighorch.cpp
- tests/test_virtual_chassis.py
**What I did**
Don't add the remote system neighbor if the same neighbor exists.
The IMM has two asics and has 2 port channels in each asic and 2 port members in each port channel.
The ip address is configured on each port channel and bgp is enabled. The neighbor and routes are learned on these port channel.
In sonic-mgmt pc suite, the test case po-update removes the port members from one of the port channel, removes the ip address configured on that port channel, creates new port channel, adds the same port members to the new port channel, adds the same ip address to the new port channel.
In the remote asic, before all the routes learned on the old port channel are removed by routeOrch, orchagent trries to remove the neighbor and nexthop for the old portchannel. But …
> Fix Voq chassis orchagent crash with 34K routes

- cfgmgr/buffer_pool_mellanox.lua
**What I did**
Put a very small shared buffer pool size when shared pool is detected enabling.
Avoid a timing issue like following:
1. the buffer pool sizes, xoff have initialized to 0, which means the shared headroom pool is disabled
2. but the buffer profiles already indicate the shared headroom pool is enabled
3. later on the buffer pool sizes are updated with xoff being non-zero
In case the orchagent starts handling buffer configuration between 2 and 3, it is inconsistent between buffer pools and profiles, which fails Mellanox SAI sanity check and causes orchagent abort
Manual test
Run sonic-mgmt regression
> [buffer] indicate shared pool by putting a very small shared buffer pool size

- .azure-pipelines/build-template.yml
- .azure-pipelines/docker-sonic-vs/Dockerfile
- .azure-pipelines/docker-sonic-vs/start.sh
- .github/workflows/codeql-analysis.yml
- azure-pipelines.yml
- debian/rules
- tests/conftest.py
- tests/dvslib/dvs_acl.py
- tests/test_pbh.py
- tests/test_srv6.py
**What I did**
Update the Azure Pipeline build to build for Bookworm.
This is dependent on https://github.com/sonic-net/sonic-buildimage/pull/20697.
> Upgrade the Azure Pipeline build to use Bookworm

- orchagent/dash/dashorch.cpp
RemoteRedisSaiInterface wrongly returns a stale SAI object ID even if the underlying SAI API object create returns NOT_IMPLEMENTED. Fix the error caused by saving and using this stale dash appliance object ID during subsequent object delete.
> Fix dash appliance delete error if SAI api is not implemented

- orchagent/bufferorch.cpp
- orchagent/bufferorch.h
- orchagent/flexcounterorch.cpp
**What I did**
Do not start counter-polling for queues with zero buffer profiles if create_only_config_db_buffers is enabled.
If create_only_config_db_buffers is enabled, counters will be polled only on queues with a buffer configured based on the hypothesis that a customer must configure a buffer profile before using the queue.
The system performance can be optimized by reducing the number of counter polled.
However, zero buffer profiles are configured on queues of inactive ports to reclaim unused buffers. Those queues are not used by customers. Hence, we do not need to start counter polling for queues with such buffer profiles configured.
Manual and regression test.
Flows verified:
1. System starts up with inactive ports
2. Shutdown a port
3. Start …
> Do not start counter polling for queues with zero buffer profiles if create_only_config_db_buffers is enabled

- orchagent/dash/dashorch.cpp
- tests/dash/test_dash_vnet.py
**What I did**
Set SAI_DIRECTION_LOOKUP_ENTRY_ATTR_DASH_ENI_MAC_OVERRIDE_TYPE to SAI_DASH_ENI_MAC_OVERRIDE_TYPE_DST_MACby default.
This can be changed to be configurable once other vnet scenarios are onboarded on smartswitch.
For direction lookup to work properly for PL scenarios on smartswitch, ENI mac needs to match dst MAC.
Ran updated vstest to verify the new attribute and value.
> [dash]: Set SAI_DIRECTION_LOOKUP_ENTRY_ATTR_DASH_ENI_MAC_OVERRIDE_TYPE attribute

- orchagent/port/porthlpr.cpp
- orchagent/port/portschema.h
**What I did**
When using "mode" as defined in
https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-yang-models/yang-models/sonic-port.yang this warning is emitted for each interface:
```
WARNING swss#orchagent: :- parsePortConfig: Unknown field(mode): skipping ...
```
It appears this field is not needed in orchagent at all, so we need to at least recognize it as valid then skip processing.
Warnings harm debugging and can cause wasted cycles when debugging real issues.
built via my private fork https://github.com/bradh352/sonic-buildimage and installed on physical switches
Signed-off-by: Brad House (@bradh352)
> [orchagent] fix "parsePortConfig: Unknown field(mode)"

- orchagent/portsorch.cpp
- tests/mock_tests/portsorch_ut.cpp
**What I did**
Ignore setPortPfcAsym failure if SAI_STATUS_NOT_SUPPORTED.
Orchagent crash seen.
Some ports don't support PFC feature, if set pfc_asym to off (means SAI_PORT_PRIORITY_FLOW_CONTROL_MODE_COMBINED), it will return SAI_STATUS_NOT_SUPPORTED.
Verified it in testbed. ERR log is kept but no crash.
log:
```
cisco@m623-dut:~$ sudo config load_minigraph 
Reload config from minigraph? [y/N]: y
Acquired lock on /etc/sonic/reload.lock
Disabling container monitoring ...
Stopping SONiC target ...
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json --write-to-db
Running command: /usr/local/bin/sonic-cfggen -d -y /etc/sonic/sonic_version.yml -t /usr/share/sonic/templates/sonic-environment.j2,/etc/sonic/sonic-environment …
```
> Ignore failure in setPortPfcAsym if SAI_STATUS_NOT_SUPPORTED

- orchagent/macsecorch.cpp
What I did
-Modified the MACsec orchestration logic to conditionally include or exclude the ability to match the SCI in ACL configurations based on the ASIC's capabilities.
-Implemented a capability check in SONiC to determine whether the SAI_ACL_TABLE_ATTR_FIELD_MACSEC_SCI attribute is supported by the ASIC, thus ensuring that neither SAI_ACL_TABLE_ATTR_FIELD_MACSEC_SCI nor SAI_ACL_ENTRY_ATTR_FIELD_MACSEC_SCI is used when unsupported.
Why I did it
The current implementation attempts to use the SAI_ACL_ENTRY_ATTR_FIELD_MACSEC_SCI attribute even when it's not supported by the underlying ASIC or driver, causing failures in the vendor's SAI/SDK code.
The capability check prevents these errors, ensuring compatibility with different hardware.
Compiled the code successfully …
> Capability query for MACSEC ACL attribute

- orchagent/portsorch.cpp
- orchagent/vxlanorch.cpp
**What I did**
Tunnel ports are always considered tagged and we can't create an untagged/pvid vlan.  But the code currently tries to set a pvid on a tunnel which is disallowed leading to an error in the logs.
This is a simple fix to get rid of the error in the logs.  It does not actually change behavior in any way other than getting rid of an error thus helping debugability.
To get rid of confusing log message:
```
ERR swss#orchagent: :- setPortPvid: pvid setting for tunnel Port_EVPN_XXX is not allowed
```
Applied patch, notice error no longer printed in logs.
Signed-off-by: Brad House (@bradh352)
> [orchagent] Fix: ERR swss#orchagent: :- setPortPvid: pvid setting for tunnel Port_EVPN_XXX is not allowed

- orchagent/portsorch.cpp
Breakout port from 4x100G  to 1x100G. It still have host_tx_ready for the removed interface in STATE_DB.
```
root@as9736-64d-2:/# config interface breakout Ethernet504 1x400G -f -y
Running Breakout Mode : 4x100G
Target Breakout Mode : 1x400G
Ports to be deleted :
{
"Ethernet504": "100000",
"Ethernet506": "100000",
"Ethernet508": "100000",
"Ethernet510": "100000"
}
Ports to be added :
{
"Ethernet504": "400000"
}
Breakout process got successfully completed.
Please note loaded setting will be lost after system reboot. To preserve setting, run `config save`.
root@as9736-64d-2:/# redis-cli -n 0 hgetall "PORT_TABLE:Ethernet504"
1) "alias"
2) "Eth64(Port64)"
3) "index"
4) "64"
5) "lanes"
6) "410,411,412,413,414,415,416,417"
7) "speed"
8) "400000"
9) "subport"
10) "0"
11) "mtu"
12) "9100"
13) …
```
> [swss] The removed interface still exits in STATE_DB PORT_TABLE

- tests/test_srv6.py
The current SRv6 test cases have a typo in the prefix length of the locator. This PR fixes the prefix length.
> [tests]: Fix a typo in SRv6 locator prefix

- orchagent/Makefile.am
**What I did**
Force orchagent to use `jemalloc` instead of the standard glibc `malloc` implementation.
Glibc's `malloc` implementation can result in memory fragmentation which prevents orchagent from returning freed memory to the kernel - this results in excessively high memory utilization.
> Link orchagent against jemalloc

- orchagent/portsorch.cpp
- orchagent/vxlanorch.cpp
- orchagent/vxlanorch.h
- tests/evpn_tunnel.py
- tests/test_vxlan_tunnel.py
**What I did**
This fixes 2 issues across a range of open tickets building upon patches created by others with modifications as requested by @VladimirKuk.
The first issue this resolves is the status shown for remote vteps which in the fact that it is wrong makes debugging nearly impossible:
```
+------------+------------+-------------------+--------------+
| SIP        | DIP        | Creation Source   | OperStatus   |
+============+============+===================+==============+
| 172.16.0.1 | 172.16.0.2 | EVPN              | oper_down    |
+------------+------------+-------------------+--------------+
Total count : 1
```
The remote VTEP is really up.
Original PR for that is #2080.
Also fixes https://github.com/sonic-net/sonic-buildimage/issues/10004 or at least the error message which …
> [orchagent]: VXLAN: Fix oper_status and tunnel encapsulation TTL

- orchagent/routeorch.cpp
- orchagent/swssnet.h
- tests/mock_tests/routeorch_ut.cpp
**What I did**
Avoid removing a VRF routing table when there are pending creation entries in gRouteBulker
1. Remove a VRF routing table when a routing entry is removed only if there is no pending creation entry in gRouteBulker
2. Avoid uninitialized value SAI IP address/prefix structure
Fix issue: out of range exception can be thrown in `addRoutePost` due to non exist VRF
```
(gdb) bt
#0  0x00007f5791aedebc in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f5791a9efb2 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f5791a89472 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f5791de0919 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f5791debe1a in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f5791debe85 in …
```
> Avoid removing a VRF routing table when there are pending creation entries in gRouteBulker

- debian/rules
- tests/conftest.py
**What I did**
use `--add-tracefile` option in `debian/rules` and `tests/conftest.py` to sanitize `coverage.info` generated by `lcov`
`lcov` generates an initial `coverage.info` file based on collected `.gcno` and `.gcda` files, this `.info` file contains coverage information for different source files (marked as `SF`).  Sometimes you would observe that the same `SF` appears multiple times, it means `lcov` gets multiple copies of coverage information for this file, since this file may have appeared in multiple compilation units, and for each copy, the hit times of its lines are different. 
Then `lcov_cobertura` generates  `coverage.xml` based on `coverage.info`. However, it can't deal with duplicate SF in `coverage.info` properly. If it sees duplicate coverage information …
> Handle duplicate SF in coverage.info to make sure coverage.xml gets correct statistics

- orchagent/main.cpp
- orchagent/orchdaemon.cpp
- orchagent/orchdaemon.h
- tests/test_zmq.py
Add heartbeat interval parameter.
Make this feature can be disable, because log spam issue on small disk device:
https://github.com/sonic-net/sonic-buildimage/issues/21157
- Microsoft ADO: 30594076
Add heartbeat interval parameter. and disable heartbeat  when interval is 0.
Pass all UT.
Add heartbeat interval parameter.
> Add heartbeat interval parameter.

- orchagent/switchorch.cpp
- tests/mock_tests/switchorch_ut.cpp
**What I did**
Prevent orchagent from being segment fault when it receives a timestamp indicating a time in the far future (2^31 years later) in the ASIC/SDK health event from the vendor SAI.
It's vendor SAI's failure to pass such a large timestamp but we need to protect such invalid input.
Mock test
In case vendor SAI passed a very large timestamp, put_time can cause segment fault which can not be caught by try/catch infra
We check the difference between the timestamp from SAI and the current time and force to use current time if the gap is too large
By doing so, we can avoid the segment fault
> Avoid segment fault in ASIC/SDK health event handling when vendor SAI passes an invalid timestamp

- .azure-pipelines/test-docker-sonic-vs-template.yml
**What I did**
Something wrong in agent pool sonictest and sonic-common. No one maintain the agent initial script.
Now I did a quick fix on these two agent pool. sonictest agent pool works but sonic-common still has issues.
1. sonictest is by design to run swss related tests. swss-common and sairedis tests run on sonictest. Only swss run on sonic-common. It is not as expected.
> [ci]Use sonictest instead of sonic-common for test stage.

- orchagent/flexcounterorch.cpp
- orchagent/flexcounterorch.h
- orchagent/pfc_detect_mellanox.lua
- orchagent/saihelper.cpp
- orchagent/saihelper.h
- tests/mock_tests/flexcounter_ut.cpp
**What I did**
Optimize the counter-polling performance in terms of polling interval accuracy
1. Enable bulk counter-polling to run at a smaller chunk size
There is one counter-polling thread for each counter group. All such threads can compete for the critical sections at the vendor SAI level, which means a counter-polling thread can wait for a critical section if another thread has been in it, which introduces latency for the waiting counter group.
An example is the competition between the PFC watchdog and the port counter groups.
The port counter group contains many counters and is polled in a bulk mode which takes a relatively longer time. The PFC watchdog counter group contains only a few counters but is polled quickly. Sometimes, PFC watchdog counters must wait before polling, which …
> Optimize counter polling interval by making it more accurate

- fpmsyncd/fpmlink.cpp
- fpmsyncd/routesync.cpp
- fpmsyncd/routesync.h
- tests/mock_tests/fpmsyncd/test_routesync.cpp
**What I did**
Implementing code changes for https://github.com/sonic-net/SONiC/pull/1425
add nexthop group feature to fpmsyncd.
- Klish will call REST API to configure `feature next-hop-group enable`.
- `FEATURE|nexthop_group` will be created in `CONFIG_DB`
- template `zebra.conf.j2` will generate `zebra.conf` with `fpm use-next-hop-groups` if `FEATURE|nexthop_group` exists in `CONFIG_DB`. Else, it will generate `zebra.conf` with `no fpm use-next-hop-groups` (default behavior)
- Do `config save` comman and write to `/etc/sonic/config_db.json`
- restart SONiC: `virsh reboot sonic-nhg`
- `/etc/frr/zebra.conf` has `fpm use-next-hop-groups` instead of `no fpm use-next-hop-groups`
- Enable: `sonic(config)# feature next-hop-group enable`
- Disable: …
> [fpmsyncd] Fpmsyncd Next Hop Table Enhancement

- neighsyncd/neighsync.cpp
VXLAN EVPN learned routes are not entered into NEIGH_TABLE as per Issue #3384.
The EVPN VXLAN HLD specifically states this should be populated so it triggers an update to the SAI database:
https://github.com/sonic-net/SONiC/blob/master/doc/vxlan/EVPN/EVPN_VXLAN_HLD.md#438-mac-ip-route-handling
> The remote MAC-IP routes will be installed by BGP (Zebra) in Linux neighbor table against Vlan netdevice. Neighsyncd subscribes to neighbor entries and will receive remote MAC-IP bindings as well. These entries will continue to go into NEIGH_TABLE in APP_DB, and neighorch will update SAI database.
It appears this was mistakingly introduced in #943 with a short conversation here about the reason, but it didn't take into account other reasons for NOARP entries: …
> [neighsync] bug: VXLAN EVPN neighbors not in NEIGH_TABLE

- orchagent/orchdaemon.cpp
- orchagent/srv6orch.cpp
- orchagent/srv6orch.h
- tests/mock_tests/aclorch_ut.cpp
- tests/mock_tests/flowcounterrouteorch_ut.cpp
- tests/mock_tests/intfsorch_ut.cpp
- tests/mock_tests/mock_orch_test.cpp
- tests/mock_tests/routeorch_ut.cpp
- tests/test_srv6.py
**What I did**
Added support for the "dscp_mode" MySID entry configuration:
* add a sync with CONFIG_DB to store MySID entry dscp mode
* create a tunnel/tunnel term entry for a static uN/uDT46 MySID entry (the tunnel is reused for the same dscp_mode)
* add a new vs test
To support "dscp_mode" MySID entry configuration
New vstest `test_Srv6MySidUNTunnelDscpMode`
> SRv6: add dscp_mode configuration for MySID entry

- orchagent/bufferorch.cpp
- orchagent/bufferorch.h
- tests/mock_tests/bufferorch_ut.cpp
**What I did**
Make use of SAI set bulk API to improve switch boot up performance, especially in warm-boot and fast-boot scenarios.
The general concept:
1. First, tasks are processed one by one by corresponding ```process*``` methods which add the SAI operation with a context to a bulk buffer. Bulk buffers are split by DB operation.
2. Bulk buffer is flushed to syncd using SAI bulk API, first DELETE operations are pushed in bulk then SET operations are pushed. Status code for each operation is updated in the task context structure.
3. Lastly, corresponding ```process*Post``` methods are invoked to handle SAI status code and perform post set operations like enabling FC counter for a PG/queue upon success.
This design allows re-use of all existing code that is written to handle one task at …
> [BufferOrch] Use SAI bulk API to configure port, PG and queue

- orchagent/portsorch.cpp
- tests/test_portchannel.py
**What I did**
Only call `updateDbPortOperStatus()` on PHY and TUNNEL ports.
PORT_TABLE contains PortChannel oper_status entries which are not expected by portsorch which leads to warm/fastreboot failures like:
```
2025 Feb 10 09:33:07.111055 sonic NOTICE swss#orchagent: :- bake: foundPortConfigDone = 1
2025 Feb 10 09:33:07.111080 sonic NOTICE swss#orchagent: :- bake: foundPortInitDone = 1
2025 Feb 10 09:33:07.111395 sonic NOTICE swss#orchagent: :- bake: m_portTable->getKeys 263
2025 Feb 10 09:33:07.111403 sonic NOTICE swss#orchagent: :- bake: portCount = 257, m_portCount = 0
2025 Feb 10 09:33:07.111403 sonic ERR swss#orchagent: :- bake: Invalid port table: portCount, expecting 257, got 261
```
Regression caused by #3383
Asked @stepanblyschak to …
> portsorch: don't call updateDbPortOperStatus on all port types

- orchagent/dash/dashorch.cpp
- orchagent/dash/dashorch.h
- orchagent/dash/dashvnetorch.cpp
- tests/dash/dash_db.py
- tests/dash/test_dash_vnet.py
Do not allow more than 1 entry in DASH Appliance table.
Do not allow DASH VNET creation before DASH Appliance entry creation.
DASH ENI already has similar check for Appliance entry.
> Add appliance entry validation

- orchagent/copporch.cpp
- tests/test_copp.py
**What I did**
Microsoft ADO **29981358**
Updated swss code to use a priority of 1 instead of 0 for default trap group.
Some vendor SAI implementations use zero as a default lowest priority internally which can impact TTL 1 packet trapping behavior in certain platforms.
* By running copp tests which include rate-limiting tests for TTL 1 packets on on Cisco/Mellanox/Arista platforms.
* By manual tests with TTL 1 packets generated by scapy
Example packet:
def send_pkt(intf):
pkt = Ether(src='00:06:07:08:09:0a',dst='84:7f:c2:88:57:a7') \
/IP(dst='20.0.0.46',src='20.0.0.47',ttl=1) \
/TCP(sport=1025,dport=179)
sendp(pkt,count=50000,iface=intf)
> [copp]: Use non-zero trap priority for default trap group

- tests/test_macsec.py
**What I did**
Provide an explicit value for send_sci in the macsec vstest
The kernel 5.15 requires the send_sci to be true if the sci value was provided explicitly.
```
AzDevOps@test-os-u000048:/agent/_work/1/s/sonic-swss/tests$ sudo pytest --dvsname=vs test_macsec.py  --pdb
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.8.10, pytest-4.6.2, py-1.11.0, pluggy-0.13.1
rootdir: /agent/_work/1/s/sonic-swss/tests
collected 4 items …
```
> [vstest]: Fix MACsec test in the kernel 5.15

- orchagent/bfdorch.cpp
**What I did**
Change capability check for BFD_SESSION_OFFLOAD_TYPE from set to get.
BFD_SESSION_OFFLOAD_TYPE is read only, need to check for get instead of set, addressing comment in https://github.com/sonic-net/sonic-swss/pull/3525
Ran vstests locally
> Change capability check to get.

- orchagent/fabricportsorch.cpp
- tests/test_virtual_chassis.py
…
**What I did**
Fix the switch level Voq counter to use switch_id Oid instead of counter name for PACKET_INTEGRITY counter
The counter:oid table was using switch_id oid, but the COUNTERS_DEBUG_NAME_SWITCH_STAT_MAP was adding the counter name instead of the switch_id oid. So changed the COUNTERS_DEBUG_NAME_SWITCH_STAT_MAP to set the switch_id oid so that using the switch_id, the counters:oid:<switch-id-id> can be queried to get the counters for the packet_integrity counters.
Verified by dumping the counters_db tables and the show command
admin@ixre-egl-board7: sudo ip netns exec asic0 sonic-db-dump -n COUNTERS_DB -y -k "*SWITCH*"
{
"COUNTERS_DEBUG_NAME_SWITCH_STAT_MAP": {
"expireat": 1739911359.7264578,
"ttl": -0.001,
"type": "hash",
"value": { …
> Fix the switch level Voq counter to use switch_id Oid instead of counter name for PACKET_INTEGRITY counter

- orchagent/portsorch.cpp
**What I did**
Initialize the argument `sai_stat_capability_list_t` to a zero size when calling `sai_query_stats_capability` for the first time in `initCounterCapabilities`.
Currently, it is initialized as the sum of all the counter IDs that orchagent requires. This works, but it is misleading because the purpose of this SAI API is to return all the counters that are supported by the vendor SAI, regardless of what the SAI client requires.
Usually, it should be either 0 or the number of counters that vendor SAI supports. It is strange to pass any other value for vendor SAI and might indicate an error. Some vendors can report an error in this case.
To avoid this kind of error message, we always pass 0 in this case.
Run unit test and manual test. …
> Initialize number of counters to 0 before querying the capabilities

- .azure-pipelines/build-docker-sonic-vs-template.yml
- .azure-pipelines/docker-sonic-vs/Dockerfile
- azure-pipelines.yml
**What I did**
When building the DVS image, remove the framework package when purging libswsscommon and other related packages. Re-install framework package when installing other packages.
DVS build is failing as swsscommon is a dependency of the framework package, so during the build the purge of libswsscommon fails. This package is not currently used for VS tests
> [DVS] Remove framework package during DVS build

- orchagent/dash/dashorch.cpp
- tests/dash/test_dash_vnet.py
* If no value is specified, use a default value of SAI_DASH_ENI_MAC_OVERRIDE_TYPE_SRC_MAC, else use the specified value.
Ref: https://github.com/sonic-net/SONiC/pull/1911/
**What I did**
`Handle outbound_direction_lookup for DASH_APPLIANCE_TABLE.`
`To unblock vnet-vnet tests which relies on the default value of SAI_DASH_ENI_MAC_OVERRIDE_TYPE_SRC_MAC`
`By running vstests and sonic-mgmt tests and ensuring that the default value for SAI_DIRECTION_LOOKUP_ENTRY_ATTR_DASH_ENI_MAC_OVERRIDE_TYPE is set to SAI_DASH_ENI_MAC_OVERRIDE_TYPE_SRC_MAC when no value is specified.`
> Handle outbound_direction_lookup for DASH_APPLIANCE_TABLE

- orchagent/dash/dashvnetorch.cpp
- orchagent/dash/dashvnetorch.h
- tests/mock_tests/Makefile.am
- tests/mock_tests/dashvnetorch_ut.cpp
- tests/mock_tests/mock_orch_test.cpp
- tests/mock_tests/mock_orch_test.h
- tests/mock_tests/mock_orchagent_main.h
- tests/mock_tests/mock_sai_api.h
- tests/mock_tests/ut_saihelper.cpp
**What I did**
- Make pre/post bulk methods in DashVnetOrch have consistent return value meaning
Fixes #3349 
> [DASH] Make DASH vnet orch bulk logic consistent

- orchagent/p4orch/tests/fake_portorch.cpp
- orchagent/portsorch.cpp
- orchagent/portsorch.h
**What I did**
Save SAI set API call when possible to provide a value during creation.
Save time on fast boot.
Test fast-boot, make sure host-if brought up after boot.
Extracted from https://github.com/sonic-net/sonic-swss/pull/3506
> [portsorch] pass oper status at hostif creation

- orchagent/pfc_detect_mellanox.lua
**What I did**
The timestamp of PFC watchdog polling is moved out of the COUNTER table. The PFC watchdog Lua plugin should be adjusted accordingly.
> Move timestamps out of counter table to avoid update too frequently

- cfgmgr/stpmgr.cpp
- cfgmgr/stpmgr.h
- Updated `stpmgr.h` to replace packed structs with aligned structs  
- Replaced the old `processStpPortAttr` in `stpmgr.cpp` with a version that uses properly aligned `STP_PORT_CONFIG_MSG` allocations  
- Ported the 202211 alignment fixes into `master`  
- Removed `#pragma GCC diagnostic` usage  
- Introduced `ALIGNED(4)` macros and added padding for the relevant `STP_*` structures  
- To resolve address-of-packed-member warnings that break builds on certain platforms (e.g., Broadcom)  
- Properly aligned data structures avoid misalignment issues and ensure stable builds  
- Validated on **bullseye**  
- Tested on the **Broadcom** platform with **no functionality changes**  
- Local builds and runtime tests confirmed successful compilation  
- Observed no regressions or functional impact …
> swss: Align STP structures and remove GCC diagnostic pragmas

- orchagent/lagids.lua
**What I did**
Modify the lagids.lua script to check both SYSTEM_LAG_IDS_FREE_LIST and SYSTEM_LAG_ID_SET to make sure the LagId is really free before it is assigned.  If it is in the FREE_LIST and also in the SYSTEM_LAG_ID_SET, remove it from the FREE_LIST and check/use the next one in the FREE_LIST. This will avoid using the ID which has been using by the LC which is still running the 202205 image.  This will address the orchagent    
The orhcgent crash during upgrade from 202205 to 202405 is caused by the same lagid used by multiple PortChannels.  On chassis with mulitple LCs,  upgrade LCs image from 202205 to 202405.   orchagent crash could be occured when one LC is running with latest image while other LCs is still running with the old image. This PR fixes issue …
> [voq][chassis][orchagent][lagid] Modified the lua script to fix orhagent crash during upgrade from 202205 to 202405

- fpmsyncd/routesync.cpp
- tests/mock_tests/fpmsyncd/test_routesync.cpp
**What I did**
1. Nexthops are now considered to have a weight of 1 by default. This means that if `libnl` returns a weight of 0 for a nexthop, `fpmsyncd` will assume that its weight is 1.
2. Added a unit test for `getNextHopWt` to verify that it treats nexthops with a weight of 0 as having a weight of 1.
3. Every time a default weight is used for a nexthop, `fpmsyncd` will log an INFO-level message. The first time that this happens, a NOTICE-level message will also be logged.
If `libnl` reports 0 as the weight of nexthops in a nexthop group used in a route, then the route entry in the APP DB will not have a `weight` attribute. This can cause further issues.  
Ran the newly-added unit test for `getNextHopWt`.
> [202405] Setting default nexthop weight to 1 in `fpmsyncd`

- fpmsyncd/routesync.cpp
- tests/mock_tests/fpmsyncd/test_routesync.cpp
**What I did**
1. Nexthops are now considered to have a weight of 1 by default. This means that if `libnl` returns a weight of 0 for a nexthop, `fpmsyncd` will assume that its weight is 1.
2. Added a unit test for `getNextHopWt` to verify that it treats nexthops with a weight of 0 as having a weight of 1.
3. Every time a default weight is used for a nexthop, `fpmsyncd` will log an INFO-level message. The first time that this happens, a NOTICE-level message will also be logged.
If `libnl` reports 0 as the weight of nexthops in a nexthop group used in a route, then the route entry in the APP DB will not have a `weight` attribute. This can cause further issues.  
Ran the newly-added unit test for `getNextHopWt`.
> [202411] Setting default nexthop weight to 1 in `fpmsyncd`

- tests/test_mirror.py
`test_MirrorDestMoveLag` performs the following steps:
1. Create mirror session
2. Enable non-LAG monitor port
3. Create LAG; move to LAG with one member
4. Remove LAG member
5. Create LAG member
6. Remove LAG; move to non-LAG
7. Disable non-LAG monitor port
8. Remove mirror session
At Step3, we call `create_port_channel` and `set_interface_status` to create LAG and set admin_status "up".
This creates a "PortChannel080" entry in the "PORTCHANNEL" table of CONFIG_DB, which results in the creation of a team device "PortChannel080" in Linux.
When step 6 calls `remove_port_channel` to remove the LAG, it is expected that the "PortChannel080" entry created previously will be removed and the team device will be deleted.
However, the current code does not remove the "PortChannel080" entry from …
> [tests]: Fix `test_MirrorDestMoveLag` test failure

- orchagent/routeorch.h
Fix NextHopGroupEntry class data member not initialized bug
Another PR blocked by test_nhg.py test failure: https://github.com/sonic-net/sonic-swss/pull/3632
After investigation, the root cause is NextHopGroupEntry::is_default_route_nh_swap not initialized. which means when create a new instance of this class, the value of is_default_route_nh_swap is depends on the data in the new allocated memory.
Following trace log show this flag value some time is 127:
May 13 08:29:30.502308 6509aaa83e64 NOTICE #orchagent: :- addNextHopGroup: addNextHopGroup 10.0.0.1@Ethernet0,10.0.0.3@Ethernet4,10.0.0.5@Ethernet8, ID: 500000000061a, swap 127
This bug not only impact test, in production environment this also will cause nexthop not delete after interface shut, because the code in …
> Fix NextHopGroupEntry class data member not initialized bug

- fpmsyncd/routesync.cpp
- tests/mock_tests/fpmsyncd/test_routesync.cpp
**What I did**
1. Nexthops are now considered to have a weight of 1 by default. This means that if `libnl` returns a weight of 0 for a nexthop, `fpmsyncd` will assume that its weight is 1.
2. Added a unit test for `getNextHopWt` to verify that it treats nexthops with a weight of 0 as having a weight of 1.
3. Every time a default weight is used for a nexthop, `fpmsyncd` will log an INFO-level message. The first time that this happens, a NOTICE-level message will also be logged.
If `libnl` reports 0 as the weight of nexthops in a nexthop group used in a route, then the route entry in the APP DB will not have a `weight` attribute. This can cause further issues.  
Ran the newly-added unit test for `getNextHopWt`.
> Setting default nexthop weight to 1 in `fpmsyncd`

- orchagent/flex_counter/flex_counter_manager.cpp
- orchagent/flex_counter/flex_counter_manager.h
- orchagent/flexcounterorch.cpp
- orchagent/srv6orch.cpp
- orchagent/srv6orch.h
- tests/test_flex_counters.py
**What I did**
Extended srv6orch to support SRv6 MySID counters (utilizing flex counter infrastructure)
To support SRv6 MySID counters
New test in test_flex_counters.py
> [SRv6] add MySID counters support

- orchagent/dash/dashhaorch.cpp
GCC error:
```
g++ -DHAVE_CONFIG_H -I. -I.. -I ../lib -I .. -I ../warmrestart -I switch -I flex_counter -I debug_counter -I port -I pbh -I nhg -g -DNDEBUG  -std=c++14 -Wall -fPIC -Wno-write-strings -I/usr/include/swss -I/usr/include -I/usr/include/libnl3 -Werror -Wno-reorder -Wcast-align -Wcast-qual -Wconversion -Wdisabled-optimization -Wextra -Wfloat-equal -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wimport -Winit-self -Winvalid-pch -Wlong-long -Wmissing-field-initializers -Wmissing-format-attribute -Wno-aggregate-return -Wno-padded -Wno-switch-enum -Wno-unused-parameter -Wpacked -Wpointer-arith -Wredundant-decls -Wstack-protector -Wstrict-aliasing=3 -Wswitch -Wswitch-default -Wunreachable-code -Wunused …
```
> [dashhaorch]: Fix error: stack protector not protecting local variables

- orchagent/muxorch.cpp
- tests/test_mux.py
Orchagent crashes when looking for mux port based on missing interface alias. Add a check to ensure that alias is present.
**What I did**
Added checks to prevent mux port lookup when interface alias is missing
Orchagent was crashing with std::logic_error when trying to parse non-existant interface alias
build in progress (will update once completed)
test will be added in full fix for the issue ETA: 6/6
ado: #33039282
lab repro logs:
```
025 May 30 23:18:47.134652 str2-7050cx3-acs-06 NOTICE test.py: SET ROUTE_TABLE:2603:10e2:112b:152::/64:{'nexthop': '2603:10c0:14:917a:0:100:aa2:2c8,2603:10c0:14:917a:0:100:aa2:2d5', 'ifname': 'Vlan1000,Vlan1000'}
2025 May 30 23:18:47.136654 str2-7050cx3-acs-06 INFO swss#orchagent: :- set: …
```
> [muxorch] Catch error when checking active state of missing neighbor

- orchagent/copporch.cpp
Fixes #3637 
Issue is applicable only to 202411 branch.
PR #3424 altered the platform string for Marvell Prestera to "marvell" causing it to become a substring of marvell-teralynx.
marvell-teralynx platform supports DHCP trap priority, which is crucial for dhcp packets getting trapped to the CPU. However, Marvell Prestera platform does not support trap priority.
Due to a substring match issue, the trap priority is not being applied correctly on the teralynx platform.
This results in DHCP packets not being trapped to the CPU.
**What I did**
Changed sub-string match to string compare, so that trap_priority is skipped only for marvell prestera platforms but not marvell-teralynx.
To fix issue with DHCP packets not gettting trapped to CPU.
By running …
> [202411] [dhcp_relay]: Fix dhcp_relay issue on marvell-teralynx platform

- orchagent/srv6orch.cpp
- tests/test_srv6.py
**What I did**
Set the SRv6 decap tunnel TTL mode to PIPE
As part of updated requirements for SRv6 Tunnel, it needs to be initialized with TTL mode set to PIPE
Extended vs tests
> SRv6: set TTL decap mode to PIPE

- .azure-pipelines/build-docker-sonic-vs-template.yml
- .azure-pipelines/test-docker-sonic-vs-template.yml
- tests/test_warm_reboot.py
Part of the changes in https://github.com/sonic-net/sonic-swss/pull/3664. test_mirror.py fixes have already bee backported to 202505 via https://github.com/sonic-net/sonic-swss/pull/3700
**What I did**
* Allow partially succeeded swss common artifacts to be pulled. Otherwise, swss builds in 202505 will fail with the error `##[error]No builds currently exist in the pipeline definition supplied.` when pulling swss-common artifacts
* To fix docker vs build and test on 202505 branch
* By ensuring that pipeline runs are successful on 202505 swss branch
> [202505] [ci]: Changes to unblock swss pipeline tests

- orchagent/main.cpp
- orchagent/orchdaemon.cpp
- orchagent/saihelper.cpp
- orchagent/saihelper.h
- tests/mock_tests/mock_saihelper.cpp
- tests/mock_tests/orchdaemon_ut.cpp
- tests/mock_tests/portsorch_ut.cpp
- tests/mock_tests/test_failure_handling.cpp
**What I did**
This change aims to reduce self-induced orchagent exit when any SAI API call fails (i.e returns anything other than SAI_STATUS_SUCCESS). This change is the first set of changes that does the following:
1.  handleSaiCreateStatus() / handleSaiSetStatus() changes
- Return 'task_success' for SAI_STATUS_ITEM_ALREADY_EXISTS, SAI_STATUS_ITEM_NOT_FOUND, SAI_STATUS_ADDR_NOT_FOUND and SAI_STATUS_OBJECT_IN_USE irrespective of the object type.
- Return 'task_need_retry' for SAI_STATUS_INSUFFICIENT_RESOURCES, SAI_STATUS_TABLE_FULL, SAI_STATUS_NO_MEMORY and 
SAI_STATUS_NV_STORAGE_FULL.
-  Call handleSaiFailure() and return 'task_failed' for other SAI errors. This will log a structured syslog via eventd and also take a SAI dump.
2. handleSaiRemoveStatus() changes
- Return 'task_success' …
> Orchagent SAI error handling improvements

- orchagent/main.cpp
- orchagent/orchdaemon.cpp
- orchagent/saihelper.cpp
- orchagent/saihelper.h
- tests/mock_tests/mock_saihelper.cpp
- tests/mock_tests/orchdaemon_ut.cpp
- tests/mock_tests/portsorch_ut.cpp
- tests/mock_tests/test_failure_handling.cpp
Cherry-pick of master PR #3587
**What I did**
This change aims to reduce self-induced orchagent exit when any SAI API call fails (i.e returns anything other than SAI_STATUS_SUCCESS). This change is the first set of changes that does the following:
1.  handleSaiCreateStatus() / handleSaiSetStatus() changes
- Return 'task_success' for SAI_STATUS_ITEM_ALREADY_EXISTS, SAI_STATUS_ITEM_NOT_FOUND, SAI_STATUS_ADDR_NOT_FOUND and SAI_STATUS_OBJECT_IN_USE irrespective of the object type.
- Return 'task_need_retry' for SAI_STATUS_INSUFFICIENT_RESOURCES, SAI_STATUS_TABLE_FULL, SAI_STATUS_NO_MEMORY and 
SAI_STATUS_NV_STORAGE_FULL.
-  Call handleSaiFailure() and return 'task_failed' for other SAI errors. This will log a structured syslog via eventd and also take a SAI dump.
2. handleSaiRemoveStatus() …
> [202505]: Orchagent SAI error handling improvements

- orchagent/saihelper.cpp
- tests/mock_tests/mock_saihelper.cpp
**What I did**
* Gracefully handle errors when accessing dpu app_state DB on NPU from DPU
* If DPU cannot reach NPU DBs for some reason, redis operations can throw exceptions, that need to be handled gracefully.
> Gracefully handle errors when accessing dpu app_state DB on NPU from DPU

- orchagent/routeorch.cpp
- tests/mock_tests/mock_sai_api.h
- tests/mock_tests/neighorch_ut.cpp
- tests/mock_tests/routeorch_ut.cpp
In dualtor systems, muxorch will program tunnel route entries for mux neighbors on standby ports. If a route with the same prefix as the mux tunnel route is learned, a cache entry will be created in routeorch. Then when the neighbor is moved to an active mux port, the tunnel route will be deleted.
In certain race-conditions the delete notification will be delayed, causing a mismatch in routeoch between the internal cache and syncd state. If a route update is processed during this time, routeorch will attempt to set the route entry in syncd. This will return an error code SAI_STATUS_ITEM_NOT_FOUND.
This adds error handling logic to remove the internal cache entry from routeorch, then attempt to retry the route set.
**What I did**
- Added error handling logic for SAI_STATUS_ITEM_NOT_FOUND …
> [routeorch] Handle SAI_STATUS_ITEM_NOT_FOUND when setting route entries

- orchagent/routeorch.cpp
Fixes https://github.com/sonic-net/sonic-buildimage/issues/22642
**What I did**
With VRF configuration and route getting added in the startup, the orchangent crashes.
`addRoutePost()` assumes the VRF is already added and attempts to get the VRF ID for the same and used it to lookup the route entry. Since the VRF is not yet created, exception gets thrown.
When the VRF is not yet created, the route add can be postponed for the VRF to be created first (returning `false` in `RouteOrch::addRoutePost` keeps the entry in `consumer.m_toSync` and will be retried later).
Running the tests/vrf/test_vrf.py, the orchagent doesnt crash anymore and the route gets created in the ASIC
> [routeorch] Wait for the VRF to be created before route add

- orchagent/muxorch.cpp
- orchagent/muxorch.h
- orchagent/routeorch.cpp
**What I did**
Skip ref counting the MUX neighbor NHs while getting added to NH group when MUX state is in standby.
This issue was causing ref counts of mux NHs to go wrong, observed this in DVS test. 
m_neighOrch->getNextHopId(it) this returns tunnel NH id when mux state is standby. However the code was incrementing the ref count of local neighbor NH based on the nh-key.
DVS test
> Skip ref counting standby mux neighbor NHs when added to NH group

- orchagent/dash/dashhaorch.cpp
- orchagent/orchdaemon.cpp
- orchagent/zmqorch.cpp
[ssw][ha] fix dpu_state_db connection issue and zmq not supporting dpu_appl_db
sign-off: Jing Zhang zhangjing@microsoft.com 
**What I did**
1. use tcp connection for remote db connect (dpu to dpu_state_db hosted on npu).
2. adapt zmqorch to consume dpu_appl_db
1 was cause crash. 2 was needed for ha to work. 
* Load the binary to 4280's DPU. 
2025 Jul 11 22:06:28.332176 sonic DEBUG swss#orchagent: :- addConsumer: ZmqConsumer initialize for: DASH_HA_SET_TABLE
2025 Jul 11 22:06:28.332401 sonic DEBUG swss#orchagent: :- addConsumer: ZmqConsumer initialize for: DASH_HA_SCOPE_TABLE
> [ssw][ha] fix dpu_state_db connection issue and zmq not supporting dpu_appl_db

- orchagent/portsorch.cpp
Mentioned in https://github.com/sonic-net/sonic-utilities/pull/3956 oper error status last timestamp always shows 'Never' because we never publish the time it last changed. 
```
Port Errors                     Count  Last timestamp(UTC)
----------------------------  -------  ---------------------
code group error                    0  Never
crc rate                            0  Never
data unit crc error                 0  Never
data unit misalignment error        0  Never
data unit size                      0  Never
fec alignment loss                  0  Never
fec sync loss                       0  Never
high ber error                      0  Never
high ser error                      0  Never
mac local fault                     7  2025-06-27 23:36:28
mac remote fault                    5 …
```
> Publish oper_status time to STATE_DB

- orchagent/copporch.cpp
- orchagent/copporch.h
- orchagent/debugcounterorch.cpp
- tests/mock_tests/copp_cfg.json
- tests/mock_tests/copporch_ut.cpp
- tests/mock_tests/portal.h
- tests/test_copp.py
**What I did**
- Added neighbor_miss trap type support
- enum capability query for hostif trap type in copporch.cpp
- Added hw_status field to COPP_TRAP_TABLE table in state_db
HLD: [sonic-net/SONiC#1943](https://github.com/sonic-net/SONiC/pull/1943)
Verified with test_copp.py DVS test
Verified on Sonic switch with and without neighbor_miss trap support by vendorSAI.
PR Dependencies:
- Depends on: sonic-net/sonic-swss-common#1010
- Depends on: sonic-net/sonic-sairedis#1586
Signed-off-by: Ravi Minnikanti <rminnikanti@marvell.com>
> [orchagent] CoPP neighbor miss trap and enhancements

- orchagent/dash/dashhaorch.cpp
- orchagent/dash/dashhaorch.h
- orchagent/dash/pbutils.cpp
- orchagent/dash/pbutils.h
- tests/mock_tests/dashhaorch_ut.cpp
**What I did**
1. Adapt to recent sonic-dash-api changes
2. instead of expecting hamgrd to write serialized pb object to DPU_APPL_DB, now haorch will expect plain kfv. 
sign-off: Jing Zhang zhangjing@microsoft.com 
Otherwise integrated tests won't work. 
1. UTs.
2. Load binary to DPU (pending). 
> [ssw][haorch] use kfv instead of serialized pb objects for internal tables

- lib/orch_zmq_config.cpp
**What I did**
Make sure empty namespace is treated as global namespace
NAMESPACE_ID env variable is set as "" and this is leading to zmq_port being 8101. This breaks all the NPU-DPU channel needed for DASH configuration
```
root@sonic:/ netstat -tulpn | grep orch
tcp        0      0 169.254.200.1:8101      0.0.0.0:*               LISTEN      1302652/orchagent
```
```
root@sonic:/ docker inspect swss
"Env": [
"RUNTIME_OWNER=local",
"DEV=",
"PLATFORM=arm64-nvda_bf-bf3comdpu",
"ASIC_VENDOR=nvidia-bluefield",
"NAMESPACE_ID=",
"NAMESPACE_PREFIX=asic",
"NAMESPACE_COUNT=",
"CONTAINER_NAME=swss",
.....
]
```
Built and verified if orchagent starts on 8100 on DPU 
> [Zmq] Make sure empty namespace is treated as global namespace

- orchagent/muxorch.cpp
- orchagent/muxorch.h
- orchagent/neighorch.cpp
- orchagent/neighorch.h
- tests/mock_tests/Makefile.am
- tests/mock_tests/mux_rollback_ut.cpp
**What I did**
When a switchover failure is detected in MuxOrch, clear relevant bulkers to provide a clean slate for the rollback process.
In certain failure scenarios, if an exception is thrown inside the bulker, it's possible that the bulker is not cleared and still contains data in `creating_entries` or `removing_entries`. When the rollback process begins, these entries will be programmed to the SAI a second time, which is a) incorrect b) could potentially trigger the same exception second time.
Run the `MuxRollbackTest.StandbyToActiveExceptionRollbackToStandby` test
> [Mux] Clear bulkers when rolling back mux switchover

- .azure-pipelines/test-docker-sonic-vs-template.yml
- orchagent/dash/dashmeterorch.cpp
- orchagent/dash/dashmeterorch.h
- orchagent/dash/dashorch.cpp
- orchagent/dash/dashorch.h
- orchagent/flex_counter/flex_counter_manager.cpp
- orchagent/flex_counter/flex_counter_manager.h
- orchagent/flexcounterorch.cpp
- tests/dash/test_dash_meter.py
- tests/dash/test_dash_vnet.py
- tests/mock_tests/flexcounter_ut.cpp
- tests/mock_tests/mock_orch_test.cpp
- tests/mock_tests/mock_orch_test.h
- tests/mock_tests/mock_orchagent_main.h
- tests/mock_tests/ut_saihelper.cpp
**What I did**
This PR  enables SWSS support for DASH Metering countering using flex counter .
Added a new table COUNTERS_METER_ENI_NAME_MAP  for use by meter stats. 
This is currently manually defined in dashmeterorch.cpp . 
This definition needs to be added to sonic-swss-common/common/schema.h  before this PR gets merged.
To enabled support for metering counters .
Added new  UT test case in test_dash_meter.py and   in tests/mock_tests.
The  existing COUNTERS_ENI_NAME_MAP is being used for ENI  counters and  entries are added/deleted based on  ENI Counters enable/disable. 
Hence  added a new table   COUNTERS_METER_ENI_NAME_MAP to be used by meter counters.
> [DASH] Add support for Metering counters

- orchagent/switch/trimming/capabilities.cpp
Backport to msft-202412, msft-202503, 202505
**What I did**
Change the return code handling such that it does not produce an ERR level syslog in the case that SAI_STATUS_NOT_SUPPORTED is returned. Instead handle it gracefully.
Sonic seems to expect queryEnumCapabilitiesSai() to only be sucessful when it returns SAI_STATUS_SUCCESS. However, SAI_STATUS_NOT_SUPPORTED is also a valid return code if the attribute queried is not supported on a platform.
Verified that the new LOG messages are printed at NOTICE level rather than ERROR level.
SONiC Software Version: SONiC.branch.202505-ars.ca6b34cb-buildimage.origin.202505-review.478334.1-2025.07.30.06.38
admin@ldp412:~$ show log "SAI_SWITCH_ATTR_PACKET_TRIM_"
2025 Jul 31 01:24:26.140966 ldp412 NOTICE …
> Enhance return code handling for queryEnumCapabilitiesSai

- orchagent/pfc_detect_broadcom.lua
- orchagent/pfcwdorch.cpp
- orchagent/pfcwdorch.h
- tests/mock_tests/portsorch_ut.cpp
pfcwdorch has been updated to allow pfc historical statistic estimation. The orch allows the feature to be enabled or disabled and the pfc_detect_broadcom.lua script will perform the estimation and update counters_db for ports that tracking is enabled on.
This implementation was made in accordance with comments from the community HLD review
https://zoom.us/rec/share/jWkZRs51QULsDQvrSlm-5qC4OZ3gkG6RVdB2k_vqwgLcnezsaG1XtX5Aqk6xBYCZ.YMhHymrP4jbpkLbm
HLD: https://github.com/sonic-net/SONiC/pull/1903
**What I did**
Edited the pfcwdorch and the pfc_detect_broadcom.lua to allow enable/disable-able PFC statistical history tracking.
Part of the PFC Historical Statistics Feature: https://github.com/sonic-net/SONiC/issues/1904
- New Unit tests added for the …
> Add PFC historical statistics estimation to the PFCWD Orch

- orchagent/dash/dashhaorch.cpp
- tests/mock_tests/dashhaorch_ut.cpp
**What I did**
Address the minor changes in HA HLD:
1. reject ha_scope object createion if ha_set is not created first.
2.  get ha_set_id mapping from ha_scope table
3. get vip from ha_scope table 
Dependency:  https://github.com/sonic-net/sonic-dash-api/pull/44
To align with HLD change. 
* UTs. 
* load on DPU, program objects (pending)
> [ssw][ha] consume new ha_scope fields

- .azure-pipelines/test-docker-sonic-vs-template.yml
- orchagent/dash/dashhaorch.cpp
- orchagent/dash/dashhaorch.h
- tests/mock_tests/dashhaorch_ut.cpp
**What I did**
Take disabled field from HA_SCOPE_TABLE and set ha scope sai attribute `SAI_HA_SCOPE_ATTR_ADMIN_STATE` accordingly. 
https://github.com/opencomputeproject/SAI/blob/b925fc0f0fc8c620eea7d9dead7fc99e33b7b44e/experimental/saiexperimentaldashha.h#L310
sign-off: Jing Zhang zhangjing@microsoft.com 
If admin state is not set to true, the state machine won't be activated in ASIC for DPU scope HA. 
- UTs. 
- Integrated tests on DPU. 
> [ssw][ha] set `SAI_HA_SCOPE_ATTR_ADMIN_STATE`  

- orchagent/high_frequency_telemetry/hftelorch.cpp
**What I did**
Added missing initialization for the m_sai_tam_obj variable.
To fix an issue with access to the uninitialized m_sai_tam_obj (in HFTelOrch::deleteTAM())
Manual test with ASAN build
> HFT: fix uninitialized m_sai_tam_obj

- orchagent/dash/dashportmaporch.cpp
- orchagent/dash/dashportmaporch.h
- orchagent/dash/dashvnetorch.cpp
- tests/mock_tests/dashvnetorch_ut.cpp
- tests/mock_tests/mock_dash_orch_test.cpp
- tests/mock_tests/mock_dash_orch_test.h
**What I did**
Push VNET mapping table entry port-map attribute to SAI as  SAI_OUTBOUND_CA_TO_PA_ENTRY_ATTR_OUTBOUND_PORT_MAP_ID 
Without this the VNET mapping entry will not be associated with the port-map in datapath.
> [DASH] Fix to push VNET mapping entry's port-map id to SAI

- orchagent/high_frequency_telemetry/hftelorch.cpp
**What I did**
This pull request makes a minor update to the group deletion logic in the high frequency telemetry orchestration code. The change improves the consistency of key generation when deleting telemetry session state.
If the group name of hft uses the lowercases, we could not delete it due to the name miss-matched in the state db. Because the uppercases was used in the state db set.
Check it locally.
> [Fixbug]: state db of hft miss-matched

- orchagent/high_frequency_telemetry/hftelorch.cpp
- tests/test_hft.py
**What I did**
This pull request improves the robustness of the high frequency telemetry (HFT) group creation logic and adds a new test to cover edge cases with empty fields. The main changes ensure that empty `object_names` and `object_counters` are handled correctly, and that the system behaves as expected when the profile is disabled.
Updated `HFTelOrch::groupTableSet` in `hftelorch.cpp` to only process `object_names` and `object_counters` if they are present and non-empty, preventing unnecessary splitting and processing of empty strings. 
If the counters or objects is empty, the orchagent will get crashed. Because the `boost::split` will still generate an empty item in the vector from the empty string.
Added a new test …
> [fixbug]: Fix orchagent crashed issue due to empty counters or stats in HFTorch

- orchagent/bufferorch.cpp
- orchagent/flexcounterorch.cpp
- orchagent/flexcounterorch.h
- orchagent/orchdaemon.cpp
- tests/mock_tests/bufferorch_ut.cpp
- tests/mock_tests/mock_orchagent_main.h
- tests/mock_tests/mock_table.cpp
**What I did**
Avoid notifying counter polling for duplicated PG or queue when `create_only_config_db_buffers` is `False` in the flow:
1. Flex counter orchagent enables counter polling for PG or queue. It notifies counter polling for all PGs or queues since `create_only_config_db_buffers` is `False`
2. Particular items in BUFFER_PG or BUFFER_QUEUE is configured. It notifies counter polling for the items again.
In most cases, BUFFER_PG and BUFFER_QUEUE are handled ahead of counter polling (i.e., the order is 2, 1), and the issue won't occur. But in a rare scenario, it can be 1 and then 2.
Manual test, mock test
> Avoid notifying counter polling for duplicated priority groups or queues
