sonic-net/sonic-swss

intfsyncd/intfsync.cpp
intfsyncd: Returning when scope == RT_SCOPE_UNIVERSE
=> intfsyncd: Returning when scope == RT_SCOPE_UNIVERSE

orchagent/neighorch.cpp, orchagent/neighorch.h, orchagent/orchdaemon.cpp, orchagent/routeorch.cpp, orchagent/routeorch.h
- RouteOrch depends on NeighOrch
- Move m_syncdNextHops to NeighOrch class
=> orchagent: Refacotring

orchagent/main.cpp
if user set the switch mac via -m, then set the switch mac to it.
Otherwise, get switch mac from SAI.
=> fix switch mac logic.

orchagent/intfsorch.cpp, orchagent/intfsorch.h, orchagent/orch.cpp, orchagent/port.h, orchagent/portsorch.cpp, orchagent/portsorch.h
commit 1e9878a017fe6db2cc63b86e32da8ee4edddef64
Author: Shuotian Cheng <shuche@microsoft.com>
Date:   Mon May 23 14:58:21 2016 -0700
orchagent: Adding VLAN support
- Add add/remove VLAN/VLAN member functions
- Rename and move addRouterIntfs function to IntfsOrch class
commit bc1b91b093176cd7bf59527aa9739e296e1cd147
Author: Shuotian Cheng <shuche@microsoft.com>
Date:   Mon May 23 13:58:05 2016 -0700
orchagent: Using port id to create router intfs instead of vlan id
=> VLAN support

orchagent/orch.cpp, orchagent/portsorch.cpp, orchagent/routeorch.cpp, portsyncd/linksync.cpp
And clearing the auto to use range-based for loop in various places
=> orchagent: Fixing auto to auto& to modify the content of iterator

doc/swss-schema.md
Adding the TUNNEL_DECAP_TABLE schema to swss-schema.md
=> doc: Adding TUNNEL_DECAP schema

portsyncd/linksync.cpp, portsyncd/linksync.h, portsyncd/portsyncd.cpp
VLAN will be configured via brctl utility in kernel. And nlmsg is listened to address type "bridge" and configure the VLANs.
=> portsyncd: Adding vlan sync logic for portsyncd

swssconfig/sample/copp.config.json
* NOTE:
*  1. ssh not supported currently
*  2. default trap group policer not supported currently
=> [swssconfig] [copp] adding copp configuration file

orchagent/Makefile.am, orchagent/bufferorch.cpp, orchagent/bufferorch.h, orchagent/main.cpp, orchagent/orch.cpp, orchagent/orch.h, orchagent/orchdaemon.cpp, orchagent/orchdaemon.h, orchagent/port.h, orchagent/portsorch.cpp, orchagent/portsorch.h, orchagent/qosorch.cpp, orchagent/qosorch.h, swssconfig/sample/buffer.config.json, swssconfig/sample/qos.config.json
* Class BufferOrch to handle buffer configuration
*   refactored Orch based class to contain common functions from QosOrch
and BufferOrch
* Class QosOrch
*   serialization for qos -
*	PFC-PG, PFC-TC, TC-PG, DSCP-TC, TC-queue maps
*	ECN support
*	WRED support
*		NOTE: Only max for green/yellow can specified. The value for min is internally set == max.
*   scheduler group/profile processing
* PFC enable - list of queues for which to enable PFC.
* main.cpp
*    changed log level DEBUG back to INFO
* portsqosorch.cpp, Port::getQueue
* portsqosorch.cpp, Port::getPG
* Samples
*  Added QOS and Buffer related configuration samples under swssconfig/sample.
* Schema
*	WRED schema changes
* 		Added WRED red max threshold support
*		Added ECN mode support
signed-off-by: hrachya@mellanox.com
=> orchagent: Adding QosOrch and BufferOrch classes

orchagent/Makefile.am, orchagent/intfsorch.cpp, orchagent/main.cpp, orchagent/notifications.cpp, orchagent/orch.h, orchagent/port.h, orchagent/portsorch.cpp, orchagent/portsorch.h, portsyncd/linksync.cpp
- Write back to APPL_DB to indicate port oper status
- Fixing log levels in various places
=> orchagent: Adding port_status_change notification handling function

orchagent/neighorch.cpp
* This fixes issue #19 (https://github.com/Azure/SONiC/issues/19)
=> sonic-swss/orchagent: Add support of neighbour MAC change

orchagent/notifications.cpp
=> orchagent: Processing port state change notification whenever gPortsOrch is initialized or not

orchagent/intfsorch.cpp
* IntfsEntry shall only be created the first time a new IP is assigned to it
* Remove router interface only when no IP addresses are associated with it
* Add INFO level logs to increase/decrease ref count functions
* Add more information to misc logs
=> orchagent: Fixing intfsorch bug wrong reference count and remove intfs case

portsyncd/linksync.cpp
* whitelist: Ethernet*, Vlan*, PortChannel*
* ignore lag members
=> portsyncd: Using whitelist to filter out the interfaces

portsyncd/linksync.cpp
=> portsyncd: Enabling LAG members admin/oper status setting

orchagent/copporch.cpp, orchagent/copporch.h
- If DEL_COMMAND is received, the trap IDs associated to the trap group
will be reset to default trap group with packet action set to forward.
- Refactor debug logs
=> [orchagent]: Update CoppOrch to suppport DEL command

orchagent/mirrororch.cpp
=> orchagent: Setting SAI_MIRROR_SESSION_ATTR_TC as optional

orchagent/qosorch.cpp
=> orchagent: Setting SAI_SWITCH_ATTR_DEFAULT_INGRESS_ACL_LIST for system ACL table

fpmsyncd/fpmsyncd.cpp, intfsyncd/intfsyncd.cpp, orchagent/main.cpp, portsyncd/portsyncd.cpp, swssconfig/swssconfig.cpp, teamsyncd/teamsyncd.cpp
=> Enable runtime loglevel setting via Redis DB

neighsyncd/neighsyncd.cpp
=> [neighsyncd]: Enable dynamic loglevel setting.

orchagent/orch.cpp, orchagent/qosorch.cpp, orchagent/qosorch.h
- Fix retry logic when the map is yet to create
- Refactor code to suppress logs that are not errors
=> [orchagent]: Fixing retry logic when QoS map is not created

orchagent/portsorch.cpp
=> [orchagent]: Check VLAN is created before creating VLAN members

orchagent/neighorch.cpp
=> [orchagent]: Refactor NOTICE logs in neighorch.cpp

orchagent/aclorch.cpp, orchagent/mirrororch.cpp
- Move string to int converters to swss-common repo
- Use common converters in Everflow and ACL code
=> [orchagent]: Fix ACL input attributes validation.

orchagent/orchdaemon.cpp, orchagent/portsorch.cpp, orchagent/portsorch.h, teamsyncd/teamsync.cpp, teamsyncd/teamsync.h
- Add LAG_MEMBER_TABLE in teamsyncd
- Add LAG_MEMBER_TABLE in orchagent
=> [orchagent]: Support LAG_MEMBER_TABLE

orchagent/routeorch.cpp
- The current logic will have a deadlock when the following scenario
happens:
The maximum number of next hop groups is set to 1.
prefix -> [ next_hop_1, next_hop_2]
When a new entry prefix -> [ next_hop_1, next_hop_2, next_hop_3 ] comes,
a new next hop group cannot be created because the maximum number of
next hop groups is reached. However, it will also not create a temporary
route as the current next hop group is a subset of the new next hop group.
In this case, the new next hop group will never be syncd.
With this commit of removing the logic of deciding whether to add or not,
the new entry could be syncd with a temporary route inserted first so as
to remove the previous entry and release the resource. On the second try,
the new entry could be inserted as the old next hop group is …
=> [routeorch]: Remove the logic of deciding if to add temp route or not

orchagent/aclorch.cpp
=> Fix acl range attribute enabling

doc/swss-schema.md, orchagent/fdborch.cpp, orchagent/fdborch.h, orchagent/orchdaemon.cpp
This pull request allows us to recreate fdb entries without waiting until ASIC recreate them.
It allows us to route traffic with less downtime.
=> [FDB orch]: Fdb orchagent to support fast-reboot

orchagent/aclorch.cpp, orchagent/mirrororch.cpp
- Fix issue with session update observed when more than one
session exist with destination IP address from the same subnet.
- Fix issue with deletion of ACL rules attached to everflow session
in inactive state.
=> [everflow]: Fix minor everflow issues.

orchagent/routeorch.cpp
- field name fix to match ifname
- log more information when next hop cannot be retrieved
- when a default route is to be removed, set the next hop to empty IpAddresses
=> [routeorch]: Set default route's next hop to empty IpAddresses when DROP

orchagent/main.cpp
- Add -d record_location option to indicate the folder for putting
SAI Redis recording file and SwSS recording file.
- The size of this folder should be monitored and limited to prevent
disk space full issue.
=> [orchagent]: Add option to set record log folder

orchagent/routeorch.cpp
- Do not add a temporary route when there existing a route whose next hop is part
of the next hop group to sync. This could prevent excessive route updates when
routes fail to be inserted due to next hop group creat failure.
=> [routeorch]: Checking if a temp route is already there before adding a new one

orchagent/Makefile.am, orchagent/main.cpp, orchagent/saihelper.cpp, orchagent/saihelper.h
- To lighten the weight of main.cpp and make it easier for future refactor
=> [orchagent]: Separate global SAI API pointers and initialization function

orchagent/bufferorch.cpp
Suppress reference related logs and print out successful logs.
=> [bufferorch]: Update logging messages and levels

orchagent/main.cpp
Latest sairedis package will be required for this to compile
=> Add support for sairedis logrotate

swssconfig/sample/msn2740.32ports.buffers.json, swssconfig/sample/msn2740.32ports.qos.json
=> [qos/buffers]: Add QoS and buffers config files for SN2740 platform.

orchagent/copporch.cpp
This version of Mellanox SAI implementation doesn't support this
attribute right now. Right now, Mellanox use queue setting to
take care of this case.
=> [copporch]: Add extra condition to skip trap priority for mlnx

.github/PULL_REQUEST_TEMPLATE.md
**What I did**
Add the pull request template.
To enforce future pull requests format and help reviewers understand the pull request better.
Checked this patch on the private fork and verified it worked.
=> [github]: Add the pull request template

orchagent/aclorch.cpp, orchagent/aclorch.h
**What I did**
Refactor doAclTableTask and doAclRuleTask
To make it more reusable
Pass the Acltest
=> [AclOrch]: refactor doAclTableTask and doAclRuleTask

orchagent/portsorch.cpp, orchagent/portsorch.h
SWSS part of SNMP queue stat counters feature.
=> Added queue stat counters map

orchagent/portsorch.cpp, orchagent/portsorch.h
=> [portsorch]: Add queue-port and queue-index map

orchagent/aclorch.cpp, orchagent/fdborch.h, orchagent/main.cpp, orchagent/mirrororch.cpp, orchagent/mirrororch.h, orchagent/orch.cpp, orchagent/orch.h, orchagent/orchdaemon.cpp, orchagent/orchdaemon.h, orchagent/portsorch.cpp
**What I did**
- Add possibility to subscribe *Orch to both APP DB and Config DB
- Rename ACL and Everflow tables.
- Fix issue with DBConnector obbject multiple deletion.
All changes are done according to ACL dynamic configuration design.
- Run BGP and FIB tests.
- Run ACL tables and Rule manual tests with "acl-loader" utility.
- Run Everflow manual tests.
=> Move ACL and Everflow configuration to Config DB.

orchagent/aclorch.cpp, orchagent/aclorch.h, orchagent/orchdaemon.cpp, orchagent/pfcactionhandler.cpp, orchagent/pfcactionhandler.h, orchagent/pfcwdorch.cpp, orchagent/pfcwdorch.h, orchagent/port.cpp
This is following https://github.com/Azure/sonic-swss/pull/350. The original one will be closed.
**What I did**
Add pfcAclHandler to drop ingress packets by acl rules.
To drop ingress packets during PFC storm recovery with acl rules.
Test on DUT.
=> [Pfcwd]: Add pfcAclHandler to drop ingress packets by acl rules

orchagent/mirrororch.cpp
=> [everflow]: Use MLNX_PLATFORM_SUBSTRING define to get platform.

orchagent/port.h, orchagent/portsorch.cpp, orchagent/portsorch.h, portsyncd/portsyncd.cpp
**What I did**
Add support for port fec setting 
Need to interoperate with devices that has fec enabled.
System startup test, and fec mode update test
=> Add support for port fec setting

orchagent/orchdaemon.cpp, orchagent/pfcwdorch.cpp, orchagent/pfcwdorch.h, orchagent/portsorch.cpp, orchagent/portsorch.h
Updated the implementation to use Flex counter for review. Under manual testing.
=> Update port and queue stat counters by Flex counter

orchagent/orchdaemon.cpp
=> [pfcwd]: Switch to Config DB

debian/swss.install, swssconfig/sample/th2.118ports.buffers.json, swssconfig/sample/th2.118ports.qos.json
**What I did**
Defined the buffer and qos configuration files for Tomahawk2 chip. Followed the guidance from Broadcom.
Some register values have been verified against Broadcom guidance.
=> [MMU] define/install buffer and qos configuration for TomaHawk2 chip

README.md
**What I did**
point build badge to new build server
point build badge to new build server
NA
NA
=> point build badge to new build server

orchagent/orchdaemon.cpp, orchagent/pfcwdorch.cpp, orchagent/pfcwdorch.h, orchagent/portsorch.cpp, orchagent/portsorch.h
This reverts commit 8fc09d04a14529dc83cca454536b9c6a2a1bdf38.
**What I did**
Since the dependent PR was already merged.
=> Revert "Revert "Update port and queue stat counters by Flex counter (#358)" (#371)"

cfgmgr/intfmgrd.cpp, cfgmgr/vlanmgr.cpp, cfgmgr/vlanmgrd.cpp, orchagent/aclorch.cpp, orchagent/aclorch.h, orchagent/bufferorch.cpp, orchagent/notifier.h, orchagent/orch.cpp, orchagent/orch.h, orchagent/orchdaemon.cpp, orchagent/orchdaemon.h, orchagent/pfcwdorch.cpp, orchagent/pfcwdorch.h, orchagent/portsorch.cpp, orchagent/qosorch.cpp, orchagent/timer.h
**What I did**
Remove the threads inside PfcWdSwOrch and AclOrch, instead, use Selectable objects to represent the notification event or timer event, and process these events similar to ConsumerTable events.
One design principle of orchagent is single thread. libsairedis is not thread-safe.
Manual PFC WD test on DUT
Depends on https://github.com/Azure/sonic-swss-common/pull/160
=> Remove the threads inside PfcWdSwOrch and AclOrch

tests/test_vs.py
**What I did**
Added a python test for port notification testing
To add more check in build process
Using local build and jenkins
=> Add python test for port notification

orchagent/pfcactionhandler.cpp
=> [PFCWD]: Match correct value when aclhandler creates acl rule

orchagent/portsorch.cpp, orchagent/portsorch.h
Create queue to queue type mapping. Fill COUNTERS_QUEUE_TYPE_MAP table.
=> [qos]: Fill COUNTERS_QUEUE_TYPE_MAP table.

orchagent/main.cpp
**What I did**
Write start recording time into the record file.
Otherwise it's hard to find where every record was started.
Output in a recording file
=> Output recording start time into the record file

.gitignore, tests/README.md, tests/conftest.py, tests/test_acl.py, tests/test_interface.py, tests/test_port.py, tests/test_route.py, tests/test_vlan.py
**What I did**
add vlan member and acl tests
add README.md
```
lgh@lgh-issaquah:/data/sonic/sonic-swss/tests$ sudo pytest -v
================================================== test session starts ===================================================
platform linux2 -- Python 2.7.12, pytest-3.3.0, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python
rootdir: /data/sonic/sonic-swss/tests, inifile:
collected 6 items                                                                                                        
test_acl.py::TestAcl::test_AclTableCreation PASSED                                                                 [ 16%]
test_acl.py::TestAcl::test_AclRuleL4SrcPort PASSED …
```
=> [tests]: add README, vlan, acl tests

tests/test_vlan.py
**What I did**
add pvid test for vlan member
add swss integration test
=> [test]: test pvid of vlan member port

tests/conftest.py, tests/test_vlan.py
**What I did**
add test vlan tag for vlan member port
virtual switch test
=> [test]: test vlan tag for vlan member port

tests/conftest.py
**What I did**
setup container name correctly in the test
```
pytest -v dnsname=vs
```
=> [bug]: setup container name correctly in the test

orchagent/aclorch.cpp, orchagent/aclorch.h
- Orchagent should now recognize and ignore control plane ACLs.
=> Add support for handling control plane ACLs

orchagent/pfcwdorch.cpp, orchagent/pfcwdorch.h
=> [pfcwd]: Log PFC frame for a lossy queue

orchagent/pfcactionhandler.cpp
=> [pfcwd]: fix typo in syslog

orchagent/pfcwdorch.cpp
=> [pfcwd]: Clean up auxilary fields, port ID

orchagent/pfcwdorch.cpp
**What I did**
Delete pfcwd handler only when it exists.
Accessing null handler will result in orchagent segfault 
Test on DUT
=> [pfcwd]: Delete pfcwd handler only when it exists

orchagent/Makefile.am, orchagent/aclorch.cpp, orchagent/crmorch.cpp, orchagent/crmorch.h, orchagent/fdborch.cpp, orchagent/intfsorch.cpp, orchagent/neighorch.cpp, orchagent/orchdaemon.cpp, orchagent/orchdaemon.h, orchagent/portsorch.cpp, orchagent/qosorch.cpp, orchagent/routeorch.cpp
**What I did**
Implemented Critical Resources Monitoring feature.
Feature request.
Manual tests and unit tests on top of virtual switch
recreated https://github.com/lguohan/sonic-swss/pull/7 against Azure/master
=> [crmorch]: Implement CRM feature

orchagent/aclorch.cpp, orchagent/aclorch.h, tests/test_acl.py
**What I did**
Add ipv6 ingress ACL support 
Need support ipv6 ACL
Manual test cases for now. Adding test cases to the framework as well.
=> [sonic-swss] Support IPv6 ACL

orchagent/countercheckorch.cpp, orchagent/countercheckorch.h, orchagent/pfcwdorch.cpp, orchagent/pfcwdorch.h
**What I did**
Simple refactor: move lossy class PFC pause alerting to countercheckOrch
The logic by design align with countercheckOrch. Refactor to make it clearer
Tested on DUT
=> [countercheck]: move pfc counter alerting to countercheckorch

doc/swss-schema.md
**What I did**
Add ipv6 ACL related schema.
To have updated schema file
Information from the code.
=> Add ipv6 ACL support in schema file

orchagent/portsorch.cpp
Signed-off-by: Nadiya Stetskovych <Nadiya.Stetskovych@cavium.com>
**What I did**
Fix type when updating ACl CRM Counters
=> [crm] Fix Crm Acl used counter update

orchagent/copporch.cpp, swssconfig/sample/00-copp.config.json
=> [copporch]: Add SAI_HOSTIF_TRAP_TYPE_UDLD

tests/test_portchannel.py
**What I did**
add portchannel virtual switch test
=> [test]: add portchannel vs test

orchagent/aclorch.cpp, orchagent/mirrororch.cpp, tests/test_mirror.py
=> [aclorch]: Add support for value/mask match for DSCP value

tests/test_acl.py
**What I did**
Use Table instead of ProducerStateTable for setting stateDB table.    
The consumers of stateDB lagTable is SubscriberStateTable,  they don't clear "LAG_TABLE_KEY_SET"
VS test.
=> VS: ProducerStateTable should not be used to set stateDb table

tests/test_mirror.py
=> [test]: Fix minor assertion issue in test_mirror.py

cfgmgr/vlanmgr.cpp
**What I did**
When a port belongs to several vlans, it is possible that
grep doesn't match with " None".
Just call exec and stop throwing in case of the failure
`cfgmgr` crashes when removing a VLAN assignment on a port which is configured with multiple VLANs
1. Configure multiple VLAN on a specific port like the configuration below.
```json
{
"VLAN": {
"Vlan1000": {
"members": [
"Ethernet1",
"Ethernet9_1"
],
"vlanid": "1000"
},
"Vlan2000": {
"members": [
"Ethernet1",
"Ethernet9_2"
],
"vlanid": "2000"
}
},
"VLAN_MEMBER": {
"Vlan1000|Ethernet1": {
"tagging_mode": "tagged"
},
"Vlan2000|Ethernet1": {
"tagging_mode": "tagged"
},
"Vlan1000|Ethernet9_1": {
"tagging_mode": "untagged"
},
"Vlan2000|Ethernet9_2": {
"tagging_mode": "untagged"
}
}
}
```
2. …
=> [cfgmgr] Don't throw when grep cmd didn't match

tests/test_crm.py, tests/test_setro.py
=> add test_setro and crm back which were mis-deleted in the dtel PR

tests/conftest.py, tests/test_acl.py, tests/test_crm.py, tests/test_mirror.py
add acl table created by dtel to acl default tables
**What I did**
there is intermittent failure in test_crm.py::test_CrmAcl
run test_crm.py::test_CrmAcl 10 times and make sure there is no failure.
=> fix intermittent failures in test_crm

orchagent/orch.cpp, orchagent/orch.h, orchagent/qosorch.cpp, orchagent/qosorch.h
Cherry-pick from master
**What I did**
=> Expose wred drop probability configurability & Support ecn on/off on a queue

orchagent/main.cpp, orchagent/orchdaemon.cpp
We don't call syncd_apply_view() at 2 places.
=> Init OrchDaemon with optional warm starting

tests/test_warm_reboot.py
**What I did**
Fix the return value check error for dvs.runcmd().
VS test
=> [VS] update dvs.runcmd() return value check

doc/swss-schema.md, warmrestart/warm_restart.cpp, warmrestart/warm_restart.h
**What I did**
Simplify the timer schema
Add a common function to get the warm-start timer
Use the same function for different timers.
=> Add a common function to get the warm-start timer

tests/conftest.py, tests/test_warm_reboot.py
Fixed https://github.com/Azure/sonic-swss/issues/596
=> Fix warm restart test left neighbors on vEthernet(s)

orchagent/aclorch.cpp, orchagent/aclorch.h, tests/test_acl.py
- Add IN_PORTS and OUT_PORTS match fields
- Add VS unit test
- Remove deprecated toUpper() function
- Add space between if and (
=> [aclorch]: Add IN/OUT_PORT match field

orchagent/mirrororch.cpp
=> [mirrororch]: Fix bug: return false when SAI API call fails

orchagent/mirrororch.cpp
=> [mirrororch]: Change Mellanox GRE type to 0x8949

cfgmgr/vrfmgr.cpp, cfgmgr/vrfmgr.h
=> [vrfmgrd]: UPdate State DB

cfgmgr/buffermgr.cpp
**What I did**
Convert NOTICE to INFO since the logs are coming repeatedly 
Suggested fix for issue [631](https://github.com/Azure/sonic-swss/issues/631)
N/A
=> Moved retry logs to INFO to avoid continuous logs

cfgmgr/Makefile.am
=> [cfgmgr]: Update Makefile.am to remove warm_restart.h

orchagent/portsorch.cpp
Fixed https://github.com/Azure/sonic-swss/issues/567
=> Fix portorch bake: get port count from db

tests/conftest.py
=> disable ipv6 for vEthernet interface in virtual switch

tests/test_warm_reboot.py
**What I did**
Fix swss warm restart test
=> [VS]: fix swss warm restart test

tests/conftest.py, tests/test_route.py
=> [vstest]: get subscribed objects from appdb and asicdb

cfgmgr/vrfmgr.cpp, cfgmgr/vrfmgr.h, cfgmgr/vrfmgrd.cpp
=> [vrfmgrd]: Support VNET setting

orchagent/portsorch.cpp
updatePortOperStatus will update the port operation status regardless of the
previous operation status. The comparison logic is moved into the notification
receiving part.
=> [portsorch]: Move status comparison outside updatePortOperStatus function

orchagent/portsorch.cpp
=> [portsorch]: Remove duplicate local variables - port

tests/test_acl.py, tests/test_acl_portchannel.py
The tests in test_acl.py are duplicate with the ones in the
test_acl_portchannel.py.
=> [test]: Remove duplicate legacy ACL tests

.gitignore
=> [gitignore]: Update all binary names in the ignore list

orchagent/port.h, tests/test_interface.py, tests/test_vnet.py
=> Revert "Align default MTU value as SAI default"

doc/swss-schema.md
**What I did**
- include description of new key warm-shutdown
=> [schema] update WARM_RESTART_TABLE:process_name schema document

cfgmgr/vlanmgr.cpp, orchagent/port.h, orchagent/portsorch.cpp
**What I did**
https://github.com/Azure/sonic-swss/pull/705 +  fix for LAG and VLAN router interface MTU
Fix for issue Azure/sonic-buildimage#2293
=> Align orchagent MTU value as SAI default

orchagent/portsorch.cpp
=> [portsorch]: Remove unused variable

tests/test_warm_reboot.py
@rodnymolina Could you help check the original testcase?
=> Temporarily skip the testcase test_routing_WarmRestart to unblock other pull requests

orchagent/watermarkorch.cpp
**What I did**
Made the logic deciding which watermark to clear more deterministic. 
Add some more warning logs
There was a bug, PG would not clear
show priority-group persistent-watermark shared
sudo sonic-clear priority-group persistent-watermark shared
show priority-group persistent-watermark shared
=> [watermark] fix watermark clear not working for PG

neighsyncd/neighsync.cpp, neighsyncd/neighsync.h, neighsyncd/neighsyncd.cpp, neighsyncd/restore_neighbors.py, warmrestart/warmRestartAssist.cpp, warmrestart/warmRestartAssist.h
Improve comments for neighsyncd functions and warmRestartAssist class
**What I did**
Improve comments for neighbor warmrestart related functions and warmRestartAssist class
To have better inline documents.
No real function changes in this PR.
=> Improve comments for neighbor warmrestart related functions 

tests/test_warm_reboot.py
**What I did**
Clean up neighbor data to avoid affecting later testing.
=> [VS] neighbor test post clean up to avoid messing up test environment

orchagent/pfcactionhandler.cpp
=> use sai_stat_id_t for new SAI header file

orchagent/intfsorch.cpp, orchagent/intfsorch.h, orchagent/vnetorch.cpp, orchagent/vnetorch.h
=> [vnetorch] Change logic for adding VNet interface

orchagent/portsorch.cpp
**What I did**
support 8 lanes port
400GE has 8 lanes
use virtual switch with 8 lane portmap.ini
=> support 8 lanes for a physical port

orchagent/intfsorch.cpp, orchagent/intfsorch.h, orchagent/main.cpp, orchagent/orchdaemon.cpp, orchagent/saihelper.cpp, orchagent/switchorch.cpp, orchagent/vnetorch.cpp, orchagent/vnetorch.h
=> [vnetorch]: Bitmap VNet implementation

orchagent/vnetorch.h
**What I did**
fix c++ 11 build complaint for destructors default to noexcept
build failed on stretch.
=> fix c++ 11 build complaint for destructors default to noexcept

orchagent/Makefile.am, orchagent/orch.h, orchagent/orchdaemon.cpp, orchagent/pfc_detect_nephos.lua
**What I did**
Add pfc-wd support for nephos.
We need to support this feature.
Test in the nephos lab.
=> [Pfc-wd]: Add pfc-wd support for nephos

fpmsyncd/routesync.cpp, orchagent/routeorch.cpp
=> [fpmsyncd]: Remove redundant new line character and trailing spaces

orchagent/routeorch.cpp
=> [routeorch]: Move extra log into INFO level

orchagent/mirrororch.cpp
=> [mirrororch]: Fix comments typo

tests/test_watermark.py
**What I did**
Looks like sometimes the clear request is not finished when the verification of the values starts. This is possible due to clear request being propagated to watermarkorch.
I added a little delay and some additional assertions to the test code. 
=> [test_watermark] avoid watermark clear vs test random failure

orchagent/qosorch.cpp, tests/test_crm.py
**What I did**
fix bad parameter for gCrmOrch->incCrmAclUsedCounter in qosorch
it's an obvious code error.  attr.value.s32 is not the acl stage, but dscp value.
=> fix bad parameter for gCrmOrch->incCrmAclUsedCounter in qosorch

orchagent/vnetorch.cpp, orchagent/vnetorch.h
=> [vnetorch]: Use metadata matching for tunnel

orchagent/Makefile.am
=> [Makefile]: Remove header files from source files

README.md
remove build badge for cavium and p4
**What I did**
=> [badge]: add vs build badge

tests/test_vlan.py
=> [vstest]: skip test_AddMaxVlan as it takes almost two hours to finish

orchagent/orchdaemon.cpp
**What I did**
"MIRROR_SESSION" table is in stateDB. 
=> Fix MIRROR_SESSION table macro name

tests/test_vlan.py
=> [test]: Mark some VLAN tests as Stretch only

orchagent/vxlanorch.cpp, orchagent/vxlanorch.h
**What I did**
Add support of vxlan removal. Porting https://github.com/Azure/sonic-swss/pull/931
To remove vxlan termination of WR restore
with test from sonic-mgmt.
=> Add support of VXLAN tunnel removal [201811]

tests/test_vnet.py, tests/test_vxlan_tunnel.py
=> Enable Vnet/Vxlan VS test

tests/test_watermark.py
=> [test]: Skip test_clear in test_watermark

orchagent/pfc_detect_mellanox.lua
**What I did**
Convert quanta to us in lua script by getting configured speed from ASIC DB, since SONiC supports only signle speed mode, admin speed == oper speed
SAI has changed to return quanta pfc duration instead of us
Mannually simulated pfc storm from fanout switch and verify orchagent detects storm.
Run PFCWD test on t1 and t0
=> [mellanox] convert logic to use quanta in pfc_detect_mellanox.lua

orchagent/orchagent_restart_check.cpp
**What I did**
Add --retryCount (-r) option for orchagent_restart_check,  so it may stay listening on the RESTARTCHECKREPLY notification channel for the whole retry period. 
This is a try to address issue: https://github.com/Azure/sonic-swss/issues/827
Issue orchagent_restart_check with -r option
```
admin@sonic:~$ docker exec -i swss /usr/bin/orchagent_restart_check -r 5
RESTARTCHECK succeeded
```
```
Apr 10 22:21:44.758066 sonic NOTICE swss#orchagent_restart_check: main:90: Number of retries for the request to orchagent is set to 5
Apr 10 22:21:44.758530 sonic INFO swss#orchagent_restart_check: subscribe:60: subscribed to RESTARTCHECKREPLY
Apr 10 22:21:44.758530 sonic NOTICE …
```
=> Add retryCount option for orchagent_restart_check program.

tests/test_vlan.py
**What I did**
[vlan] Add pytest cases to validate nonexistent vlan behavior.
Add test cases:
1. Add member to nonexistent vlan => not allow
2. Remove nonexistent vlan => nothing happened, vlanmgrd still work fine
=== Test Results ===
test_vlan.py::TestVlan::test_AddVlanMemberWithNonExistVlan PASSED					[ 91%]
test_vlan.py::TestVlan::test_RemoveNonexistentVlan PASSED							[100%]
Signed-off-by: Emma Lin <emma_lin@edge-core.com>
=> [vlan] Add pytest cases to validate nonexistent vlan behavior.

orchagent/policerorch.cpp
Throw error when the return code is NOT successful :(
=> [policerorch]: Fix return code comparison error

orchagent/crmorch.cpp, orchagent/crmorch.h
=> Fix: crash while destructing crmorch (#731)

.gitignore
=> [gitignore]: Add swss-dbg related files

tests/test_vnet.py
=> [test]: Skip unstable test test_vnet_orch_1

tests/test_watermark.py
This test is not stable enough.
=> [test]: Skip test_watermark.py::TestWatermark::test_lua_plugins

teamsyncd/teamsync.cpp
=> [teamsyncd]: Add information for LAG membership changes

orchagent/routeorch.cpp
- erase the correct observer in the observer list
- remove the NextHopObserverEntry once no observer is observing the entry
- refine some logs and comments
=> [routeorch]: Fix observer detaching procedure for next hop observers

tests/test_vnet.py
**What I did**
Enabled "vnet_orch_1" VS test case
I was disabled due some failures but now it passes so enabled it back.
Ran VS tests and verified all passed
N/A
=> [vnet]: Enable "vnet_orch_1" VS test case

orchagent/Makefile.am, orchagent/orch.h, orchagent/orchdaemon.cpp, orchagent/pfc_detect_innovium.lua, orchagent/portsorch.cpp
Signed-off-by: Tony Titus ttitus@innovium.com
**What I did**
Added Innovium support
To support Innovium platform
PTF tests
=> [orchagent] Add support for Innovium platform

teamsyncd/teamsync.cpp
=> [teamsyncd]: Check if LAG exists before removing

orchagent/Makefile.am, orchagent/chassisorch.cpp, orchagent/chassisorch.h, orchagent/orchdaemon.cpp, orchagent/vnetorch.cpp, orchagent/vnetorch.h
Renew the PR : https://github.com/Azure/sonic-swss/pull/970
**What I did**
=> [chassisorch]: Add everflow feature for chassis

tests/test_crm.py
**What I did**
VS test fix
Frequent failures due to extra log messages for CRM 
=> [CRM] Check if we got more than expected number of log messages 

orchagent/pfcwdorch.cpp
=> Fix pfc watchdog compile error

tests/Makefile.am
**What I did**
Fixed https://github.com/Azure/sonic-swss/issues/1122
Build against VS SAI - make check run tests and mock_tests
Build against Real SAI - build successfull
=> [tests] fix build against real SAI

tests/conftest.py
**What I did**
gather logs when dvs fail to start
explicit make check_ready() fail and test.
=> [vstest]: gather logs when dvs fail to start

cfgmgr/vxlanmgr.cpp
=> [sonic-swss/vxlanmgr] : Fix bug - Wrong condition for mac address

cfgmgr/vlanmgr.cpp
Fix bug in https://github.com/Azure/sonic-swss/pull/1098#issuecomment-574264500
@banagiri could you please help review?
=> Fix bug: shellquote the inner string

orchagent/aclorch.cpp
**What I did**
Add MIRRORv6 support for Barefoot platform
=> Enable MIRRORv6 for BFN platform

tests/conftest.py
**What I did**
print out stdout/stderr message when cmd fails
to know why a command fails.
=> [pytest]: print out stdout/stderr message when cmd fails

orchagent/aclorch.cpp
**What I did**
adding mirror v6 support for marvell
mrvl supports mirrorv6
creating mirror v6 sessions
v4 and v6 mirror are not shared
=> adding mirrorv6 support for mrvl platform

orchagent/aclorch.cpp
**What I did**
Add MIRRORv6 support for the Barefoot platform.
This is backporting of https://github.com/Azure/sonic-swss/pull/1177 from the master branch
=> Enable MIRRORv6 for BFN platform 

.gitignore, tests/README.md
=> [dvs] Update instructions for running dvs tests locally

orchagent/portsorch.cpp
**What I did**
Removed dead code
=> Removed dead code

orchagent/aclorch.cpp
**What I did**
Enable m_isCombinedMirrorV6Table for BFN
Due to internal changes in the BFN platform
=> [BFN] Enable m_isCombinedMirrorV6Table for BFN

orchagent/aclorch.cpp
=> Revert "[BFN] Enable m_isCombinedMirrorV6Table for BFN"

orchagent/aclorch.cpp
**What I did**
Enable m_isCombinedMirrorV6Table for BFN
To fix typo in initial PR https://github.com/Azure/sonic-swss/pull/1177
=> Enable m_isCombinedMirrorV6Table for BFN platform

cfgmgr/nbrmgr.cpp
Fixes refactor: https://github.com/Azure/sonic-swss-common/commit/e6d5c1a367e9993ec1ec492c79838a65bf3e77b9
=> Add missing netlink include

tests/README.md
**What I did**
Updated readme file for tests
Because the instructions there doesn't work anymore. zipp and pytest packages abandoned python 2 support.
Try it on clean system
=> [tests]: Specify versions of pip packages

tests/dvslib/dvs_common.py, tests/dvslib/dvs_database.py
**What I did**
I refactored the `_db_poll` method used internally by the database into a generic polling utility function.
There are a bunch of other use-cases where polling could be useful, so it makes sense to implement it independently of the DB. Also, making the polling interface public makes it possible for people to write custom DB polling functions more easily as well.
Newly refactored tests (NAT and ACL) still pass.
The diff of `dvs_database` is really wacky, you will probably need to look at the file itself for the changes to make sense. Apologies. 😝
=> [dvs] Add generic polling utility

tests/README.md
for the command line `vconfig`
=> Update README.md: install vlan package

lgtm.yml
=> [lgtm] Add LGTM checks to vs tests

orchagent/orch.h, tests/mock_tests/consumer_ut.cpp, tests/mock_tests/mock_dbconnector.cpp, tests/mock_tests/mock_table.cpp
Fix build after https://github.com/Azure/sonic-swss-common/pull/336/files
=> Refine getDbId() calling to fix build after swss-common change

configure.ac
=> configure extra inc/lib directory for build

lgtm.yml
=> [lgtm]: add lgtm cpp check

tests/dvslib/dvs_database.py, tests/test_sub_port_intf.py
**What I did**
I refactored the sub-port interface tests to use the new polling functions.
Stabilize/speed-up the tests.
20/20 successful test runs locally (~50s avg).
=> [dvs] Stabilize sub-port tests

tests/dvslib/dvs_common.py, tests/dvslib/dvs_database.py
**What I did**
I updated the `wait_for_result` method to return the result of failed polling calls in order to provide more debug information for failed tests.
Currently, failed polling calls simply print "assert False," making it difficult to quickly find the source of the failure. This change gives the test author more information about assertion failures.
Tests still pass with this change.
=> [dvslib] Improve support for assert logging

tests/test_crm.py, tests/test_fdb.py, tests/test_fdb_update.py, tests/test_nat.py, tests/test_nhg.py, tests/test_port.py, tests/test_warm_reboot.py
**What I did**
Changed the tests over from the Linux command to the SONiC config command.
To fix the PR tests.
Tests pass after the change locally.
=> [dvs] Update tests to use correct command to bring up interfaces

tests/test_watermark.py
**What I did**
Replace direct calls to `redis-cli` with more civilized methods of interaction with the DB :joy:
Due to moving to MultiDB
Run the test suite
=> [test_watermark] avoid calls to redis-cli

mclagsyncd/mclaglink.cpp, mclagsyncd/mclaglink.h
**What I did**
fix compilation issue for gcc 8.3
gcc 8.3 is used in debian buster  release
compile swss under buster
=> fix compiling issue for gcc8.3

tests/README.md, tests/conftest.py, tests/dvslib/dvs_vlan.py, tests/port_dpb.py, tests/test_crm.py, tests/test_mirror.py, tests/test_mirror_ipv6_separate.py, tests/test_nhg.py, tests/test_port_config.py, tests/test_port_dpb.py, tests/test_port_mac_learn.py, tests/test_setro.py, tests/test_tunnel.py, tests/test_vlan.py, tests/test_vrf.py, tests/test_warm_reboot.py, tests/test_watermark.py
**What I did**
support swss vstest in python3
support python3
```
lgh@jenkins-worker-17:~/sonic-swss/tests$ sudo py.test -v | tee make.out                                                  ============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-4.6.2, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
rootdir: /home/lgh/sonic-swss/tests
plugins: flaky-3.6.1
collecting ... collected 257 items
============= 249 passed, 7 skipped, 1 xpassed in 6875.88 seconds ==============
```
=> support swss vstest in python3

tests/conftest.py
**What I did**
clean up processes in server namespace at start
run test with --dvsname option
=> [vstest]: clean up processes in server namespace at start

tests/dvslib/dvs_common.py, tests/dvslib/dvs_database.py
- Use `fstrings` instead of `format`
- Add type hints
- Simplify some of the comments
**What I did**
I made some changes to the common part of `dvslib` to incorporate some new python3 features into the framework.
- `fstrings` are easier to read and more resource efficient than the `.format` method.
- Type hints are helpful for clients, and a little more explicit than docstring comments.
- The docstring format was inconsistent in places.
Run the tests.
=> [vs] Incorporate python3 best practices into DVSLib

orchagent/port_rates.lua, orchagent/rif_rates.lua
**What I did**
Fixed some minor issueswith lua scripts:
- undefined variables
- typo
`redis-cli --eval port_rates.lua ,`
observe no error
=> [rates] fix undefined var in lua scripts

tests/README.md
- Document --keeptb flag
- Add dynamic port option to ./create_vnet.sh
- Add `libswsscommon` installation issue
**What I did**
I added some additional info to the README for the docker virtual switch.
Fixes #1324 
Tried the specified options locally.
=> [dvs] Update README with new flags, options, and known issues

tests/README.md
**What I did**
I updated the README to reflect the VS setup steps for Python 3.
There have been a lot of issues getting the VS working recently, so I ran through the steps again to make sure they were accurate for python3.
I set up an 18.04 VM and a 20.04 VM and ran through the setup steps from scratch. Afterwards I verified that I could run the test commands as described in the README.
=> [dvs] Fix install instructions in README

tests/dvslib/dvs_database.py, tests/test_sflow.py, tests/test_speed.py
**What I did**
I converted the sflow and speed tests to use `dvslib` to poll redis rather than relying on static `time.sleep` calls.
Both tests have been failing a lot recently, so I updated them to help stabilize the PR tests.
Ran both locally x20, no failures.
=> [dvs] Convert sflow and speed tests to use dvslib

tests/conftest.py
**What I did**
I updated `dvs` to use the module log path even if the failure occurs during virtual switch setup.
Previously the `get_logs()` call in `check_ready_status` passed None as the `modpath`, which means any failure during startup would reset the logs. This makes it hard to debug startup issues for particular test cases, and it deletes a lot of helpful data from other non-startup related test failures.
Inserted `assert 2 == 3` into the DockerVirtualSwitch constructor, verified that logs were output to `test_speed` (no dvs specified) and `my_virtual_switch` (persistent container specified) respectively.
=> [dvs] Upload logs even if failure occurs during startup

.gitignore
Ignore gearsyncd binary. Also remove duplicate entry for portsyncd binary
=> [.gitignore] Ignore gearsyncd binary

tests/test_route.py
**What I did**
Refactor route tests to use dvslib.
Add a performance test for adding and deleting routes.
The performance test allows quantifying the efficiency of interactions between orchagent and syncd. The performance test also makes it possible to check if changes can be pushed into hardware within the required time limits.
Run the tests locally.
**Sample output of performance test**
Time to add 10000 routes is 6.55 seconds.
Time to remove 10000 routes is 5.86 seconds.
=> [dvs] Add performance test for adding and deleting routes

tests/conftest.py
- Relax timeout for startup sequence
- Break constructor into logical segments
**What I did**
I updated the ASIC DB Validator to 1) wait 30 seconds for the DB to initialize and 2) break it up into a few logical segments.
A few tests failed over the weekend because ASIC DB wasn't finished creating all of the host interfaces, so I made the timeout longer than the normal 5s timeout. Adding this made `__init__` really long, so I broke the code up into private methods.
Re-run tests locally with the change, they all still pass.
=> [dvs] Refactor AsicDbValidator

tests/test_port_dpb.py, tests/test_port_dpb_acl.py, tests/test_port_dpb_vlan.py
**What I did**
Removed the xfail for DPB.
The swsssdk fix has merged and the submodule has been updated.
https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/sonic-swss-build/1708/console
All tests are XPASS'ing with the new image.
=> [dvs] Re-enable DPB VS tests

tests/test_nhg.py
**What I did**
Add a wait for route entries in ASIC_DB in `test_nhg.py::TestNextHopGroup::test_route_nhg_exhaust` so that the test case could pass in synchronous mode.
The test case `test_nhg.py::TestNextHopGroup::test_route_nhg_exhaust` fails in synchronous mode due to a delay between the creation of next-hop groups and routes in ASIC_DB. Getting the count of routes entries immediately after the creation of next-hop groups results in an inaccurate result. This PR fixes this by waiting for the number of route entries in ASIC_DB to be the expected value.
Verified by running the test locally.
=> [dvs] Update test_nhg.py to make it pass in synchronous mode

tests/test_watermark.py
**What I did**
Refactor the watermark testcases to properly cleanup the tables in case of failure
Added buffer pool watermark cases
```
================================================================================== test session starts ==================================================================================
platform linux -- Python 3.6.9, pytest-6.0.2, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
rootdir: /home/nejo/SONiC/sonic-swss/tests
collected 4 items …
```
=> [dvs] Add buffer pool watermark test

README.md
**What I did**
Add libzmq5 to README
Build fails if this library is not installed
Run `fakeroot debian/rules binary` without it installed, build fails. 
Re-run again after installing and build succeeds.
=> Add libzmq to README dependencies

lgtm.yml
Otherwise, the LGTM pull request checker will fail
=> Add missing lib of zmq for lgtm

mclagsyncd/mclaglink.h, orchagent/bufferorch.h, orchagent/countercheckorch.cpp, orchagent/flexcounterorch.cpp, orchagent/pfcwdorch.cpp, orchagent/pfcwdorch.h, orchagent/portsorch.cpp, orchagent/routeorch.cpp
**What I did**
The RedisClient class is deprecated so no need to include the header file.
=> Clean code, remove unused header file

tests/test_fgnhg.py
**What I did**
use standard wait API to wait for asic db and state db updates
stabilize the tst
run fgnhg 10 times locally
=> [vstest]: stablize fgnhg test

tests/test_fgnhg.py
**What I did**
Add polling function for ecmp group validation and use wait API for asic_db/state_db update
Resolve intermittent timing related test failure in test_fgnhg.py
50 iterations passing of test_fgnhg.py
=> [vstest] Resolve intermittent timing failure in test_fgnhg.py

tests/conftest.py
**What I did**
I re-added the copy_file method that was removed in a recent refactor.
Buildimage tests depend on this method, so subsequent submodule updates will fail.
=> [dvs] Re-add copy_file method to DVS

orchagent/portsorch.cpp
=> [orchagent] Fixed compilation failure with debug option

orchagent/saihelper.cpp
**What I did**
Update the initSaiPhyApi() call to properly propagate the firmware_path information coming from gearbox_config.json to the create_switch SAI call.
This change is needed for the propagation of firmware path info in gearbox_config.json to the SAI.
Tested that the firmware specified in gearbox_config.json is loaded by the SAI in a syncd container for gearbox in an internal Arista SONiC build with this change.
=> [orchagent/phy]: Add firmware info propagation

orchagent/fdborch.cpp, orchagent/fdborch.h
**What I did**
I added code to handle update() function of FDB orchagent for the FDB FLUSH event.
I added code because earlier the FDB FLUSH event was not handled not fully, it was saying unsupported. So, I handled the event as like in master branch.
Adding a port as VLAN member, learning FDB entries for the port and then removing VLAN membership was causing ERROR logs in SWSS. With this fix, no more error logs were observed.
Changeset is in orchagent/fdborch.cpp and orechagent/fdborch.h
=> handled update() function of fdb orchagent for FDB FLUSH event

cfgmgr/sflowmgr.cpp, cfgmgr/sflowmgr.h
**What I did**
Added Support of handling NULL fields while removing sflow sampling rate.
to avoid NULL in field.
=> Sflow fix to avoid NULL in field.

azure-pipelines.yml
**What I did**
add build for arm64 and armhf
check ci results
=> [ci]: add build for arm64 and armhf

tests/README.md
**What I did**
Update the test setup guide according to the issue I encountered lately.
=> [swss test] update setup guide for swss tests

azure-pipelines.yml
**What I did**
only copy artifacts when build is successful
fix false negative 
=> [ci]: only copy artifacts when build is successful

orchagent/fgnhgorch.cpp, orchagent/fgnhgorch.h, orchagent/routeorch.cpp, tests/test_fgnhg.py
**What I did**
Added Fine Grained ECMP match mode changes 
So that Fine Grained ECMP routes can be filtered via next-hop IPs(match_mode next-hop-based). The originally implemented solution filtered routes via the prefix, this continues to be supported via match_mode route-based
Verified using VS swss test cases
https://github.com/Azure/SONiC/pull/727
=> [fgnhgorch] Match mode changes for Fine Grained ECMP

azure-pipelines.yml
**What I did**
download artifacts from master branch build
Fix #1589 
=> [ci]: download artifacts from master branch build

orchagent/bufferorch.cpp, orchagent/muxorch.cpp, orchagent/tunneldecaporch.cpp
**What I did**
Fix repeating logs in case of tunnel creation fail
Avoid cluttering of mux logs
=> [Mux] Fix repeating logs in case of tunnel creation fail

tests/mock_tests/aclorch_ut.cpp, tests/mock_tests/check.h
Signed-off-by: kcudnik <kcudnik@gmail.com>
**What I did**
Remove legacysaiattributelist.h dependency
This file was refactored in sairedis repo to SaiAttributeList.h proper class
locally compile
Copy contents of saiattributelis.h directly to check.h
=> [tests] Remove legacy saiattributelist.h dependency

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/build_and_install_module.sh, .azure-pipelines/docker-sonic-vs/Dockerfile, .azure-pipelines/test-docker-sonic-vs-template.yml, azure-pipelines.yml, tests/test_virtual_chassis.py
**What I did**
add vstest in azure pipeline
check pr
=> [ci]: run vstest

orchagent/macsecorch.cpp
**What I did**
Remove useless included header in macsecorch
Make code to be clearer
=> Remove useless headers

tests/conftest.py, tests/dvslib/dvs_route.py, tests/test_nhg.py
**What I did**
* cd960ff 2021-02-17 | [vstest/nhg]: use dvs_route fixture to make test_nhg more robust (HEAD -> nhg, lgh/nhg) [Guohan Lu]
* 1b65ba1 2021-01-02 | [vstest]: add dvs_route fixture [Guohan Lu]
make test_nhg more robust
locally
=> [vstest/nhg]: use dvs_route fixture to make test_nhg more robust

orchagent/aclorch.cpp, orchagent/aclorch.h, tests/mock_tests/aclorch_ut.cpp
**What I did**
Ported the changes from https://github.com/Azure/sonic-swss/pull/1648 to 201911.
Cherry-pick conflicts
Re-tested against 201911 on DUT
See https://github.com/Azure/sonic-swss/pull/1648
=> [201911][acl] Enable VLAN ID qualifier for ACL rules

cfgmgr/vlanmgr.cpp, orchagent/portsorch.cpp, tests/dvslib/dvs_vlan.py
**What I did**
hostif_name -> host_ifname as per the schema definition
Fix typo
=> [Monitor Vlan] Fix a typo in hostif

orchagent/macsecorch.cpp, tests/test_macsec.py
=> [orchagent]: Update MACsec SAI API to 1.8.0 and re-enable MACsec test

orchagent/bulker.h
**What I did**
Log error with failure status when bulk API fails.
Allow better understanding about bulk failures.
=> [Bulk mode] Improve log in bulk failures

.azure-pipelines/docker-sonic-vs/Dockerfile
**What I did**
Purge swss-common before installing
VS test failing as docker start fails
=> [VS] Fix for VS test failures

cfgmgr/Makefile.am
**What I did**
* Refactored `cfgmgr` Makefile
* To avoid code duplication of common libs
* Build `swss`
* N/A
=> [cfgmgr]: Introduce common libs

orchagent/orch.cpp
**What I did**
Open record file (swss.rec) in append mode. Similar to [sairedis.rec](https://github.com/Azure/sonic-sairedis/blob/master/lib/src/Recorder.cpp#L233)
Found missing records during debug
Tested the changes by running on a device over a period of time. One observation is frequent NEIGH_TABLE updates. 
=> [Swss Rec] Open record file in append mode

cfgmgr/Makefile.am
**What I did**
Added -lzmq flag to cfgmgr
New changes in sairedis repo will move zmq dependency to libsaimeta
Local build
=> [cfgmgr] Update Makefile.am to consume lib zmq [202106]

lgtm.yml
Needed for code coverage in configure.ac
=> Add autoconf-archive package to lgtm

tests/test_port_dpb_lag.py
**What I did**
`test_dependency` is under investigation
=> [VS test] Skipping a flaky test temporarily

.azure-pipelines/build-template.yml
**What I did**
fix artifacts download from swss-common and sairedis
fix build issues
=> [ci]: fix artifacts download from swss-common and sairedis

orchagent/pfc_detect_innovium.lua
[SWSS] Innovium platform specific changes PFC Detect lua script for SONiC 202012
Signed-off-by: Ravindranath C K <rck@innovium.com>
**What I did**
Update pfc_detect_innovium.lua
pfc_detect_innovium.lua changes for 202012
Verified running PTF and pytest on Innovium platforms
=> Innovium platform specific changes PFC Detect lua script for SONiC 202012

cfgmgr/teammgr.cpp, cfgmgr/teammgr.h, cfgmgr/teammgrd.cpp
This PR is intended to fix LAGs cleanup degradation caused by python2.7 -> python3 migration.
The approach is to replace `teamd -k -t` call with the raw `SIGTERM` and add PID alive check.
This will make sure the `teammgrd` is stopped only after all managed processes are being killed.
resolves: https://github.com/Azure/sonic-buildimage/issues/8071
**What I did**
* Replaced `teamd -k -t` call with raw `SIGTERM`
* Added PID alive check
* To fix LAGs cleanup timeout issue caused by python2.7 -> python3 upgrade
1. Configure 64 LAG RIFs
2. Reload config
```bash
Jul 21 12:28:14.754221 sonic INFO systemd[1]: Stopping TEAMD container...
Jul 21 12:28:14.761918 sonic NOTICE admin: …
```
=> [teammgrd]: Improve LAGs cleanup on shutdown

tests/test_copp.py
**What I did**
Enable the Copp tests that were skipped
Tests were left disabled. Enabled them since no copp manager changes are pending
Ran tests locally. All passed
============================================================ 13 passed, 8 warnings in 121.69s (0:02:01) =============================================================
=> Enabling copp tests

tests/test_port_config.py
**What I did**
Test is failing for swss-common and sairedis repos. 
Temporarily skip to unblock PRs
=> [VS] Skip failing test - test_recirc_port 

orchagent/routeorch.cpp, orchagent/routeorch.h, tests/test_mux.py
**What I did**
Manually cherry-pick PR https://github.com/Azure/sonic-swss/pull/1922 from master
Conflict in auto-merge
Tested on DUT
=> [202012] Cache route for single nexthop for faster retrieval

tests/conftest.py
**What I did**
Increase timeout during VS tests when checking DVS services
=> [pytest]: Increase timeout when checking services

.azure-pipelines/build-template.yml, azure-pipelines.yml
=> [ci]: use native arm64 and armhf pool

tests/conftest.py
**What I did**
Ignore exceptions caused by non-existing interfaces when trying to delete those interfaces
The delete command can occasionally fail if the interface has been auto-deleted before the command is run. This causes cascading failures for the VS test suite.
=> [pytest]: Ignore errors deleting host ifs

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/test-docker-sonic-vs-template.yml, tests/test_mirror_port_erspan.py, tests/test_vlan.py
=> [202012] Check VS test failure

lgtm.yml
Signed-off-by: Stepan Blyshchak <stepanb@nvidia.com>
**What I did**
=> [lgtm.yml] add libgmock-dev

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/test-docker-sonic-vs-template.yml
**What I did**
Revert the WA to unblock swss-common build as part of https://github.com/Azure/sonic-swss/pull/2033
=> [202012] Revert partial build temporary work-around

.azure-pipelines/build-template.yml
=> Cherry pick some azure pipeline PR from master.

doc/Configuration.md
**What I did**
Supply the missing ingress/egress port profile list tables in the document
=> [Document][202012] Supply the missing ingress/egress port profile list in document

lgtm.yml
**What I did**
[LGTM] lgtm to use 202106 branches of swss-common and sairedis
Signed-off-by: stephens <stephens@contoso.com>
See azure pipelin checkers as a reference:
- with this commit merged, LGTM [passed](https://lgtm.com/projects/g/Azure/sonic-swss/logs/rev/pr-846fb51afd6f09f05cf7e66c3941b6c1951d4d1a/lang:cpp/stage:Build%20merge_0bd44afc3eddf81c77371193836bcd695e0fb2ca).
- without it, LGTM [failed](https://lgtm.com/projects/g/Azure/sonic-swss/logs/rev/pr-846fb51afd6f09f05cf7e66c3941b6c1951d4d1a/lang:cpp/stage:Build%20202106_c68bad07b049ec0e71fcd5f011a694423d9e167d) as expected, which is why LGTM is marked as failed in the checkers.
=> [LGTM][202106] lgtm to use 202106 branches of swss-common and sairedis

gearsyncd/gearboxparser.cpp
**What I did**
With this change, macsec_ipg can be added to gearbox_config.json for setting the IPG of port on ASIC
=> [macsec] Support setting IPG by gearbox_config.json

.azure-pipelines/gcov.yml
**What I did**
Enable diff coverage for PR builds
Maintain high level of code coverage
=> [azp]: Enable PR diff coverage

orchagent/aclorch.cpp
Signed-off-by: Venkat Garigipati <venkatg@cisco.com>
**What I did**
Enable ACL mirror capabilities for platform type CISCO_8000_PLATFORM_SUBSTRING
Enable Mirror ACL for Cisco Silicon Platforms. 
=> Enable Mirror ACL for cisco-8000 asic type

orchagent/aclorch.cpp
**What I did**
This is a double commit for PR#2059 into 202012 branch 
=> provide support for mirror acl for 202012 branch

orchagent/portsorch.cpp
**What I did**
Added removal of port serdes objects if exists, before removing port.
If port serdes is present on device, it's a reference dependency on port.
locally
=> Remove port serdes object before removing port

orchagent/portsorch.cpp, orchagent/portsorch.h, portsyncd/portsyncd.cpp
HLD change: https://github.com/Azure/SONiC/pull/932
**What I did**
1. Put port operational speed to STATE DB
2. Remove previous workaround https://github.com/Azure/sonic-swss/pull/1769
For issue https://github.com/Azure/sonic-buildimage/issues/9595
Manual test
=> Try get port operational speed from STATE DB

.azure-pipelines/test-docker-sonic-vs-template.yml, tests/test_port_dpb_vlan.py, tests/test_route.py
**What I did**
DPB tests are flaky, need investigation before enabling. 
Increase VS test duration
Unblock some PRs
=> [VS test] Increase VS test time, skip dpb flaky test

tests/test_port_dpb_vlan.py
**What I did**
Skip flaky DPB VS tests
Unblock PRs
=> [VS test] skip dpb flaky test (#2195)

orchagent/bfdorch.cpp, orchagent/bfdorch.h, orchagent/vnetorch.cpp
**What I did**
Register BFD callback during the BFD session creation flow
BFD session callback is required to get state changes from SAI and there by remove or add endpoints.
Verified it manually with BFD show command which also relies on BFD session change notifications
=> [202012][BFD]Registering BFD state change callback during session creation

.azure-pipelines/gcov.yml
=> [azp]: Set diff coverage threshhold to 80%

tests/test_copp.py
**What I did**
Enable CoPP UT in docker-sonic-vs.
N/A
Run Copp UT and make sure all tests pass
Tests will pass after https://github.com/Azure/sonic-buildimage/pull/10230 will be merged
=> [202012] [CoPP] Enable CoPP UT

.azure-pipelines/gcov.yml
**What I did**
Reduce PR diff coverage threshold to 50%
Currently, CPP unit test results are not included in diff coverage reporting. Once this is fixed, the threshold will be increased again.
=> [azp]: Reduce diff coverage to 50% threshold

orchagent/vnetorch.cpp, tests/test_vnet.py
**What I did**
Set multihop to true for BFD sessions created by Vnetorch
As per HLD
=> [Vnet] Set BFD multihop to true for Vnet routes

tests/test_buffer_dynamic.py, tests/test_route.py
**What I did**
Skip tests that are failing consistently.
Unblock PRs
=> [VS} Skip consistent fail tests

tests/mock_tests/Makefile.am, tests/mock_tests/copporch_ut.cpp, tests/mock_tests/mock_orchagent_main.h, tests/mock_tests/portal.h, tests/mock_tests/ut_helper.h, tests/mock_tests/ut_saihelper.cpp
**What I did**
* Added `CoPP` UTs
* To increase code/feature coverage
1. Compile `swss` package
```
nazariig@c13d94125e90:/sonic/src/sonic-swss/tests/mock_tests$ ./tests --gtest_filter=CoppOrchTest*
Running main() from /build/googletest-YnT0O3/googletest-1.10.0.20201025/googletest/src/gtest_main.cc
Note: Google Test filter = CoppOrchTest*
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from CoppOrchTest
[ RUN      ] CoppOrchTest.TrapGroup_AddRemove
[       OK ] CoppOrchTest.TrapGroup_AddRemove (49 ms)
[ RUN      ] CoppOrchTest.TrapGroupWithPolicer_AddRemove
[       OK ] …
```
=> [mock_tests]: Add CoPP Orch UTs

tests/mock_tests/Makefile.am, tests/mock_tests/flowcounterrouteorch_ut.cpp, tests/mock_tests/mock_orchagent_main.h, tests/mock_tests/ut_saihelper.cpp
Signed-off-by: kebol@nvidia.com
**What I did**
Add unit test framework for FlowCounterRouteOrch
Add unit test case to cover the route pattern add/delete flow
The unit test framework is not available for FlowCounterRouteOrch which will block the developers to add UT to cover the code change in the future. So add the unit test framework for it. Add also add a test to cover the route pattern add/delete flow. 
run unit test and all of the new test can pass.
=> [unit test] Add unit test for FlowCounterRouteOrch

orchagent/macsecorch.cpp, tests/test_macsec.py
Waiting for PR: https://github.com/Azure/sonic-wpa-supplicant/pull/48
**What I did**
To change SCI in appdb for better readability.
The original SCI was like `Ethernet0:72068799825728594`, The new SCI is like `Ethernet0:5254000D310A0001`
Check Azp.
=> [macsecorch]: Change SCI in appdb for better readability

azure-pipelines.yml
**What I did**
Change pipeline trigger settings
1. Support new release branch pipeline automatically.
2. Build swss weekly to keep artifact available.
=> [ci] Improve azp trigger settings to automatically support new release branch

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/test-docker-sonic-vs-template.yml, azure-pipelines.yml
**What I did**
Change downloading artifact branch.
Always using master branch artifact will lead to test failure.
=> [ci] Use correct branch when downloading artifact.

orchagent/bufferorch.cpp, orchagent/flexcounterorch.cpp, orchagent/flexcounterorch.h, orchagent/portsorch.cpp, orchagent/portsorch.h, tests/mock_tests/portsorch_ut.cpp, tests/mock_tests/routeorch_ut.cpp, tests/test_buffer_traditional.py, tests/test_flex_counters.py, tests/test_pg_drop_counter.py, tests/test_watermark.py
Reverts Azure/sonic-swss#2143
#2143 is a good change, however, it requires matching CLI changes to not break the CLI/tests.
=> Revert "[Counters] Improve performance by polling only configured ports buffer queue/pg counters"

.azure-pipelines/test-docker-sonic-vs-template.yml
**What I did**
Don't publish gcov artifact when test failed.
When we retry test stage, publish gcov will fail because artifact is already published by old failure test.
=> [ci] Don't publish gcov artifact when test failed.

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/test-docker-sonic-vs-template.yml, azure-pipelines.yml
**What I did**
Cherry-pick some pipeline related PRs:
9da86f3 [ci] Don't publish gcov artifact when test failed. (#2331)
4d6fa42 [ci] Change artifact reference pipeline to common lib pipeline. (#2294)
d7b5ff7 [ci] Use correct branch when downloading artifact. (#2292)
2f13244 [ci] Improve azp trigger settings to automaticlly support new release branch. (#2289)
=> [ci][202111] Use correct branch when downloading artifact.

orchagent/flexcounterorch.cpp, orchagent/flexcounterorch.h, orchagent/macsecorch.cpp, orchagent/macsecorch.h, orchagent/portsorch.cpp, orchagent/portsorch.h
**What I did**
1. Default macsec poll interval 10s, except of xpn1s 
2. Correct COUNTERS_MACSEC_NAME_MAP entry in GB_COUNTERS_DB for gearbox macsec
3. Support macsec flex couner config
4. Correct port flex counter config for gearbox
Support macsec counter w/o gearbox completely
=> [macsec] Update macsec flex counter

orchagent/fdborch.cpp, orchagent/fdborch.h, orchagent/portsorch.cpp, orchagent/portsorch.h, tests/mock_tests/Makefile.am, tests/mock_tests/fdborch/flush_syncd_notif_ut.cpp, tests/mock_tests/mock_table.cpp
**What I did**
Backport https://github.com/Azure/sonic-swss/pull/2254
=> [202111] [FDB] Fix fbdorch to properly handle syncd FDB FLUSH Notif

tests/test_sub_port_intf.py
**What I did**
Skip failing subport tests. Temporary WA for https://github.com/Azure/sonic-swss/issues/2365
To unblock unrelated PRs
=> [VS Test] Skip failing subport tests

orchagent/bufferorch.cpp, tests/mock_tests/bufferorch_ut.cpp
**What I did**
Support removing an entry from BUFFER_PORT_INGRESS/EGRESS_PROFILE_LIST table.
- To remove it, set the list as empty.
Add mock test to verify the change
Mock test and manual test
=> [Buffer Orch] Support removing buffer port profile list

lgtm.yml
**What I did**
Fix lgtm: fatal error: uuid/uuid.h: No such file or directory
=> [lgtm] Fix lgtm error: uuid/uuid.h

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/docker-sonic-vs/Dockerfile, .azure-pipelines/test-docker-sonic-vs-template.yml, azure-pipelines.yml
Reverts sonic-net/sonic-swss#2363
Failing all the PR builds
=> Revert "[ci][asan] add DVS tests run with ASAN"

lgtm.yml, orchagent/bufferorch.cpp, orchagent/flexcounterorch.cpp, orchagent/flexcounterorch.h, orchagent/p4orch/tests/fake_portorch.cpp, orchagent/portsorch.cpp, orchagent/portsorch.h, tests/mock_tests/portsorch_ut.cpp, tests/mock_tests/routeorch_ut.cpp, tests/test_buffer_traditional.py, tests/test_flex_counters.py, tests/test_pg_drop_counter.py, tests/test_watermark.py
**What I did**
Revert the [sonic-swss/pull/2432](https://github.com/sonic-net/sonic-swss/pull/2432)
The community test [test_iface_namingmode.py](https://github.com/sonic-net/sonic-mgmt/blob/202205/tests/iface_namingmode/test_iface_namingmode.py) is not passing because of [sonic-swss/pull/2432](https://github.com/sonic-net/sonic-swss/pull/2432). 
=> [202205][counters] Revert PR #2432 for the buffer queue/pg counters improvement

.azure-pipelines/test-docker-sonic-vs-template.yml, azure-pipelines.yml
**What I did**
Don't publish test result and don't run Gcov when job failed.
When the test jobs failed once, it will fail forever.
=> [ci] Only when test stage succeeded or succeededwithissues, PR run Gcov

orchagent/pfc_detect_innovium.lua
[SWSS] Innovium platform specific changes in PFC Detect lua script
Signed-off-by: Maulik Patel maulikp@marvell.com
**What I did**
Update pfc_detect_innovium.lua
pfc_detect_innovium.lua changes for master and 202111 branch
Verified running PTF and pytest on Innovium platforms
Cherry picking the same change from https://github.com/sonic-net/sonic-swss/pull/1893
=> [SWSS] Innovium platform specific changes in PFC Detect lua script

orchagent/vnetorch.cpp, tests/test_vnet.py
The vxlan tunnel feature goes into an unpredictable state if the same tunnel configuration is applied twice.
Any further configuration update worsens the problem.
**What I did**
Added a fix to check if the configuration updates has no impact and avoid internal state update.
Bug causes feature failure.
Added 5 tests to verify idempotent behavior
These tests check with a single endpoint with/without BFD, and multiple endpoints with/without BFD scenarios.
=> [Bugfix]Vxlan ecmp configuration idempotent behavior fix.[202012]

orchagent/aclorch.cpp, tests/dvslib/dvs_acl.py, tests/test_acl.py
**What I did**
We found that without specifying `action_list`, the `PFCWD` and `DROP` ACL tables takes more TCAM resources than expected.
Actually, only `SAI_ACL_ACTION_TYPE_PACKET_ACTION` is required for `PFCWD` and `DROP` table.
This PR is to specify the `action_list` for `PFCWD` and `DROP` ACL table. 
This PR is to specify the `action_list` for `PFCWD` and `DROP` ACL table. 
Verified by vstest and physical testbed.
=> [202012] [ACL] Specify action list for `PFCWD` and `DROP` ACL table

orchagent/muxorch.cpp, orchagent/muxorch.h, tests/test_mux.py
**What I did**
Let mux orch skip adding kernel tunnel routes for SoC IPs.
Signed-off-by: Longxiang Lyu <lolv@microsoft.com>
Please refer to https://github.com/sonic-net/SONiC/pull/1132 for more details.
Add unittest.
=> [muxorch] Skip programming SoC IP kernel tunnel route

orchagent/flex_counter/flowcounterrouteorch.h
**What I did**
Remove TODO comments which are no longer needed
MUX support has already been removed, the TODO item is not valid
Only comment change
=> Remove TODO comments which are no longer needed

orchagent/vnetorch.cpp, tests/test_vnet.py
orignal PR https://github.com/sonic-net/sonic-swss/pull/2508
Cast to master
**What I did**
=> [Bugfix]Vxlan ecmp configuration idempotent behavior fix. [master]

.azure-pipelines/gcov.yml
**What I did**
Increase diff cov from 50 to 80%
Overall quality improvement
=> [Coverage] Increase diff coverage to 80%

orchagent/main.cpp
Reverts sonic-net/sonic-swss#2522
Fixes sonic-net/sonic-buildimage#13324
=> Revert "Add show fabric counters port/queue commands"

orchagent/vnetorch.cpp, orchagent/vnetorch.h, tests/test_vnet.py
Cherry-pick of https://github.com/sonic-net/sonic-swss/pull/2589
**What I did**
Added logic to Write to VNET_MONITOR table in appl DB.
This effort is done so that we can have a custom endpoint monitoring solution in place of BFD if required.
added a testcase in test_vnet.py
=> [202012] Vxlan tunnel endpoint custom monitoring APPL DB table

orchagent/portsorch.cpp, tests/test_virtual_chassis.py
This is a cherry pick of https://github.com/sonic-net/sonic-swss/pull/2607 for 202205
=> [202205][voq][chassis] Remove created ports from the default vlan.

.azure-pipelines/build-template.yml
=> [ci] Fix pipeline error about team5 not found.

orchagent/bfdorch.cpp, tests/test_bfd.py
double commit to 202012
https://github.com/sonic-net/sonic-swss/pull/2689
**What I did**
=> [202012][bfdorch] add default TOS value for BFD packet

orchagent/orch.cpp, tests/conftest.py, tests/test_vnet.py
* With VNET routes, the same route can be learned via multiple sources, like via BGP. Handle this special situation gracefully without orchagent crash
**What I did**
Handle duplicate routes learned via multiple sources
To prevent orchagent crashes and thereby improve system stability
=> [202012][orchagent]: Handle duplicate routes in a graceful manner

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-template.yml
**What I did**
Allow partially succeeded builds to download to avoid unstable UT.
=> [ci] Allow partially succeeded builds to download.

orchagent/orchdaemon.cpp, orchagent/vnetorch.cpp, orchagent/vnetorch.h, tests/test_vnet.py
Please see the included test to see what this code would do.
custom monitor-based next-hop groups switchover.
adv prefix parameter-based advertisement is done.
**What I did**
=> [202012]Custom monitoring based priority tunnels

orchagent/orchdaemon.cpp
**What I did**
Cherry pick https://github.com/sonic-net/sonic-swss/pull/2712
=> [202012] Fix orchagent missing request when logrotate happens

orchagent/dash/dashrouteorch.cpp
**What I did**
Do not use an action drop with the inbound routing table.
Action "drop" is not supported by the inbound routing table. SAI_INBOUND_ROUTING_ENTRY_ACTION_DENY action is no longer available in SAI v1.12
Run sonic-mgmt DASH VNET to VNET test.
=> [dash] Do not use an action drop with the inbound routing table.

orchagent/orchdaemon.cpp, orchagent/vnetorch.cpp, orchagent/vnetorch.h, tests/test_vnet.py
Cherry picking https://github.com/sonic-net/sonic-swss/pull/2721
**What I did**
Added support to handle Vnet configuration changes such as Overlay_dmac.
In a running system, if the overlay_dmac of a Vnet is changed, this needs to be reflected in the VNET monitor configuration.
Added a unit test.
=> [202012] overlay_dmac change in Vnet configuration.

orchagent/srv6orch.cpp, tests/test_srv6.py
What I did
mysid support to set default vrf
Why I did it
set default vrf not work under local testing
set default vrf of mysid and confirm srv6 works under local testing
Signed-off-by: link_chiang <link_chiang@edge-core.com>
=> [orchagent, SRv6]: mysid support to set default vrf

orchagent/portsorch.cpp
**What I did**
Remove the TODO comment that is no longer relevant.
To clean up the code and remove non-relevant comments. 
The change doesn't touch the code itself. No additional verification is required.
=> Remove the TODO comment that is no longer relevant.

orchagent/dash/dashrouteorch.cpp
**What I did**
For vnet_direct routing, check if overlay IP is specified
Orchagent will throw a logic error if it attempts to set an overlay IP value when one is not given
=> [dash]: Check if overlay IP is specified

orchagent/dash/dashorch.cpp, orchagent/dash/dashorch.h, orchagent/dash/dashrouteorch.cpp, orchagent/dash/dashvnetorch.cpp, orchagent/dash/dashvnetorch.h, tests/test_dash_vnet.py
=> [DASH]: Miscellaneous bug fixes and adding vstests

.azure-pipelines/test-docker-sonic-vs-template.yml
=> Fix pipeline issue caused by urllib3 v2

orchagent/neighorch.cpp, orchagent/neighorch.h, orchagent/vnetorch.cpp, tests/test_nhg.py
**What I did**
valid/invalid nexthop based on BFD session state.
Microsoft ADO: https://msazure.visualstudio.com/One/_workitems/edit/17793093
to accelerate traffic convergence when BFD session state changes
load test image to testbed, set up static route nexthop group with 2 members.
trigger BFD session UP/DOWN and check sairedis.rec to see add/remove member transection:
```
2023-05-09.21:54:24.553671|C|SAI_OBJECT_TYPE_ROUTE_ENTRY||{"dest":"192.85.4.0/24","switch_id":"oid:0x21000000000000","vr":"oid:0x3000000000042"}|SAI_ROUTE_ENTRY_ATTR_NEXT_HOP_ID=oid:0x60000000009a9||{"dest":"192.85.0.0/24","switch_id":"oid:0x21000000000000","vr":"oid:0x3000000000042"}|SAI_ROUTE_ENTRY_ATTR_NEXT_HOP_ID=oid:0x60000000009a8
... …
```
=> [orchagent][neighorch] traffic convergence acceleration for staticroutebfd

orchagent/crmorch.cpp, orchagent/crmorch.h, orchagent/dash/dashaclorch.cpp, orchagent/dash/dashorch.cpp, orchagent/dash/dashrouteorch.cpp, orchagent/dash/dashvnetorch.cpp, tests/conftest.py, tests/test_crm_dash.py
**What I did**
Extend CrmOrch to support DASH resources.
Add a possibility to monitor and report DASH critical resources.
Run VS tests.
A new `tests/test_crm_dash.py` is added to cover DASH CRM functionality.
=> [CRM][DASH] Extend CrmOrch to support DASH resources.

azure-pipelines.yml
=> Run regular VS tests for DASH PRs

tests/test_nhg.py
**What I did**
fix UT error
ntf = swsscommon.NotificationProducer(dvs.adb
-- test_bfd.py (https://github.com/baorliu/sonic-swss/blob/master/tests/test_bfd.py#L41) use this code but it does not work here.
changed to:
ntf = swsscommon.NotificationProducer(self.asic_db.db_connection
pass all the 14 pipeline checks
original PR:
https://github.com/sonic-net/sonic-swss/pull/2769
Passed all UT and build checking.
=> [swss][orchagent] fix srt-bfd ut error

azure-pipelines.yml
=> [master] Run regular VS tests for DASH PRs

.azure-pipelines/build-template.yml, azure-pipelines.yml
=> [azp] Add DASH to PR trigger for non-DASH VS tests

orchagent/orch.cpp, orchagent/orch.h
This is a cherry-pick PR for https://github.com/sonic-net/sonic-swss/pull/2562
**What I did**
Improve Consumer interface to support ZMQ based Producer/Consumer table.
To improve route create performance, swsscommon lib will add ZMQ based Producer/Consumer table. Because currently Consumer interface only support Redis based Producer/Consumer table, so improve this interface to support ZMQ based Producer/Consumer table.
ZMQ based Producer/Consumer table can find in this PR: https://github.com/sonic-net/sonic-swss-common/pull/715
Pass all UT.
**What I did**
=> [cherry-pick] Improve Consumer interface to support ZMQ based Producer/Consumer table. (#2562)

tests/README.md
**What I did**
* Updated user manual for VS tests
* To resolve broken URLs
* N/A
* N/A
=> [vstest]: Update documentation

orchagent/muxorch.cpp, orchagent/muxorch.h, tests/test_mux.py
**What I did**
Skip adding ACL for active-active ports.
Please refer to the HLD for more details: sonic-net/SONiC#1180
=> [muxorch] Skip programming ACL for standby `active-active` ports

.azure-pipelines/test-docker-sonic-vs-template.yml
**What I did**
Change the sonic_buildimage_ubuntu20_04 from master to $(BUILD_BRANCH)
Azp maybe apply to other branch
Check Azp
=> [Azp]: Change default branch to build_branch

.github/workflows/codeql-analysis.yml, cfgmgr/buffermgrd.cpp, cfgmgr/coppmgr.cpp, gearsyncd/gearparserbase.h, orchagent/p4orch/acl_rule_manager.cpp, orchagent/p4orch/acl_table_manager.cpp, orchagent/p4orch/acl_util.cpp, orchagent/p4orch/acl_util.h, orchagent/p4orch/ext_tables_manager.cpp, orchagent/p4orch/ext_tables_manager.h, orchagent/p4orch/gre_tunnel_manager.cpp, orchagent/p4orch/l3_admit_manager.cpp, orchagent/p4orch/mirror_session_manager.cpp, orchagent/p4orch/neighbor_manager.cpp, orchagent/p4orch/next_hop_manager.cpp, orchagent/p4orch/route_manager.cpp, orchagent/p4orch/router_interface_manager.cpp, orchagent/p4orch/tables_definition_manager.cpp, orchagent/p4orch/tables_definition_manager.h, orchagent/p4orch/tests/acl_manager_test.cpp, orchagent/p4orch/tests/gre_tunnel_manager_test.cpp, orchagent/p4orch/tests/l3_admit_manager_test.cpp, orchagent/p4orch/tests/mirror_session_manager_test.cpp, orchagent/p4orch/tests/neighbor_manager_test.cpp, orchagent/p4orch/tests/next_hop_manager_test.cpp, orchagent/p4orch/tests/route_manager_test.cpp, orchagent/p4orch/tests/wcmp_manager_test.cpp, orchagent/p4orch/wcmp_manager.cpp, swssconfig/swssconfig.cpp
**What I did**
This header file comes from an external package, and a very old version of the header file has been checked into swss-common. This will cause problems for the upcoming Bookworm upgrade.
Change references to the header file to use the Debian package nlohmann-json-dev (added in sonic-net/sonic-buildimage#16308), instead of from swss-common.
=> Use json.hpp from nlohmann-json-dev instead of from swss-common

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-template.yml
**What I did**
Allow partially succeeded builds when downloading.
sonic-sairedis on 202211 branch failed on vstest.
=> [ci] Allow partially succeeded builds when downloading artifacts.

.azure-pipelines/build-template.yml
**What I did**
When downloading other pipeline artifact, allow vstest failures.
ADO:  26046039
=> [ci] Allow partially success build artifact in PR checker pipeline.

tests/mock_tests/Makefile.am, tests/mock_tests/warmrestarthelper_ut.cpp, warmrestart/warmRestartHelper.cpp
**What I did**
Cherry-pick https://github.com/sonic-net/sonic-swss/pull/2981
=> [fpmsyncd][WR][2305] Relax the static schema constraint for ROUTE_TABLE 

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/docker-sonic-vs/Dockerfile, orchagent/dash/dashrouteorch.h
**What I did**
Rename dash route namespace to follow the PR: https://github.com/sonic-net/sonic-dash-api/pull/9
The previous name `route_lpm` was inconsistent with convention.
Locally compile it.
=> [dashrouteorch]: Rename dash route namespace (#2966)

orchagent/aclorch.cpp, tests/test_acl.py
Reverts sonic-net/sonic-swss#3078
Regression observed on Mellanox platforms
=> Revert "[acl] Add IN_PORTS qualifier for L3 table"

tests/mock_tests/Makefile.am, tests/mock_tests/warmrestarthelper_ut.cpp, warmrestart/warmRestartHelper.cpp
**What I did**
Cherry pick https://github.com/sonic-net/sonic-swss/pull/2981
=> [202311][fpmsyncd][WR] Relax the static schema constraint for ROUTE_TABLE

orchagent/port.h, orchagent/port/porthlpr.cpp, orchagent/port/portschema.h
**What I did**
Introduce a new role for DPU-NPU Interconnect
Support DPU Connect Role for internal ports of smartswitch and dpu
Verified by loading a SKU that defines this role and made sure orchagent didn't crash
=> Introduce a new role for DPU-NPU Interconnect

azure-pipelines.yml, orchagent/p4orch/tests/acl_manager_test.cpp, orchagent/twamporch.cpp
**What I did**
Add a Bookworm build to the PR checkers. Also fix some Bookworm build errors that crept in.
Buildimage now builds swss for Bookworm, so the build needs to succeed.
=> Add bookworm build to the PR checkers

cfgmgr/buffermgrdyn.cpp, tests/mock_tests/buffermgrdyn_ut.cpp
**What I did**
It was harmless unless there were too many messages indicating the depending buffer pools and profiles on some certain platforms, which triggers the syslog rate limit.
Manual and mock test
=> Do not apply zero buffer profile list until all buffer pools are ready

mclagsyncd/mclaglink.cpp, mclagsyncd/mclaglink.h
**What I did**
MCLAG: Use port-isolation functionality instead of ACLs for Marvell platforms
Minimize the impact of ACL scaling in marvell platforms.
Validate the MC-LAG functionality on marvell platforms.
=> [mclag] Use port-isolation feature for Marvell platforms.

orchagent/Makefile.am, orchagent/orchdaemon.cpp, orchagent/pfc_detect_marvell.lua
**What I did**
Add PFC detect lua script for Marvell platform.
Support PFC Detect functionality
Verify the build and script execution
=> [Marvell] PFC Detect lua script

.azure-pipelines/test-docker-sonic-vs-template.yml
**What I did**
Migrate agent pool to fix S360 ticket.
=> [ci] use sonictest instead of sonic-common-test

.azure-pipelines/build-template.yml, .azure-pipelines/gcov.yml, .azure-pipelines/test-docker-sonic-vs-template.yml, azure-pipelines.yml
**What I did**
Agent pool migration to fix S360 alert.
=> [ci] Migrate from sonicbld to sonicbld-1es to fix S360 alert.

orchagent/dash/dashrouteorch.cpp, tests/test_dash_vnet.py
**What I did**
Fixed the dashrouterorch to use the correct INBOUND_ROUTING_ENTRY_ATTR_ACTION values
To align with the latest DASH SAI headers
=> [dash] align dash inbound route actions with the latest SAI headers

cfgmgr/buffer_pool_mellanox.lua, tests/test_buffer_dynamic.py
**What I did**
Support allocate buffer pool size based on percentage of available memory by `percentage` field in `BUFFER_POOL` table.
It is used in the dynamic buffer model only and represents the percentage of a buffer pool's size compared to the available memory size.
On Nvidia devices, if the percentage is defined, the buffer pool size is `available memory` * `percentage`.
Mock test
=> Support allocate buffer pool size based on percentage of available memory

orchagent/muxorch.cpp, tests/test_mux.py
**What I did**
Cherry-pick of https://github.com/sonic-net/sonic-swss/pull/3188
Fix was not present in 202311
- validated on 202305
- vstest added with PR
- (wip) validating on 202311 with image built from PR
=> [202311][muxorch] Fixing bug with updateRoute and mux neighbors (#3188)

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-template.yml
**What I did**
Use the latest master branch sairedis artifacts for building and testing
https://github.com/sonic-net/sonic-swss/pull/3048 changed the AZP jobs to use a specific sonic-sairedis build/artifact. This PR is reverting the sonic-sairedis build back to the latest master after sonic-sairedis breaking changes are merged.
=> [azp] Use master branch sairedis artifact

orchagent/dash/dashorch.cpp, tests/dash/test_dash_pl.py
**What I did**
If present, parse `pl_sip_encoding` field in ENI table and pass it to SAI
`pl_sip_encoding` was previously deprecated but now has been un-deprecated (see https://github.com/sonic-net/SONiC/pull/1805)
=> [DASH] Pass pl_sip_encoding to SAI

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/gcov.yml
**What I did**
Fix 202311 branch pipeline issue.
=> [ci] Fix pipeline issue in 202311 branch.

orchagent/main.cpp
Backport of PR #3258
**What I did**
Change adds optional create_switch timeout as command line parameter to orchagent.
Changes are verified to see passed timeout value is reflected only for create_switch api call from orchagent.
=> [Orchagent] Add optional create_switch timeout parameter

README.md, tests/README.md
**What I did**
Updated build and install instructions in `README.md` and `tests/README.md` to include missing steps and removed outdated information.
sonic-swss cannot be built using current instructions in `README.md`.
Successfully built and installed sonic-swss using the new set of steps.
=> Updated SWSS build and install instructions

orchagent/routeorch.cpp, orchagent/routeorch.h, orchagent/vnetorch.cpp
**What I did**
Renamed the function hasBgpRoute to hasBgpRoute in routeOrch and in places it called from
passing build
=> [code refactor] renamed hasBgpRoute to isRouteExists in RouteOrch

.github/workflows/codeql-analysis.yml
**What I did**
Fix the codeql checker following the Bookworm and libnl 3.7.0 upgrade.
=> Fix codeql following Bookworm upgrade

cfgmgr/Makefile.am, cfgmgr/stpmgr.cpp, cfgmgr/stpmgr.h, cfgmgr/stpmgrd.cpp, configure.ac, orchagent/Makefile.am, orchagent/fdborch.cpp, orchagent/fdborch.h, orchagent/orchdaemon.cpp, orchagent/orchdaemon.h, orchagent/p4orch/tests/mock_sai_stp.h, orchagent/port.h, orchagent/portsorch.cpp, orchagent/saihelper.cpp, orchagent/stporch.cpp, orchagent/stporch.h, tests/mock_tests/Makefile.am, tests/mock_tests/mock_orchagent_main.h, tests/mock_tests/stporch_ut.cpp, tests/mock_tests/ut_saihelper.cpp
Added new stpmgr for STP config handling
Added changes in orchagent for STP programming via SAI APIs
What I did
Added new stpmgr under cfgmgr for handling STP config notifications
Added STP changes in stporch component to handle STP operations (STP Instance creation/deletion, STP Port Add/Update/Del to STP instance) via SAI
Why I did it
PVST Feature support
How I Verified it
Added UT cases for stporch changes
=> PVST feature support

.gitignore
**What I did**
Ignore `.gcda` and `.gcno` in all folders to avoid seeing a large number of untracked files in `git status`
=> Git ignore .gcda and .gcno in all folders

portsyncd/linksync.cpp
**What I did**
Added additional values for debug log
Enhance debug prints with additional inof needed for offline debug
=> [portsync] print flags for port netlink message

.github/CODEOWNERS
**What I did**
Code owners update
=> [Code Owner] Update code owners for swss repo files

orchagent/portsorch.cpp, tests/mock_tests/portsorch_ut.cpp
**What I did**
Fix a typo. The current word is "high ber_error", but the correct word should be "high_ber_error"
Fix a typo 
unit test
=> [orchagent] Fix issue: typo in high BER

orchagent/nhgorch.cpp, orchagent/routeorch.cpp, orchagent/srv6orch.cpp
Add null checks for variable assignments in RouteOrch, NhgOrch and Srv6Orch. The assignments will only proceed if the string is not empty.
**What I did**
Add value validity checks to the assignment part of SET_COMMAND in the doTask methods for RouteOrch, NhgOrch and Srv6Orch, ensuring that the values assigned to fields are not empty.
For the value obtained by orchagent, assigning an empty value without validation may cause an issue. 
So add a validity check before assigning the value.
=> [orchagent] Add value validation for RouteOrch, NhgOrch and Srv6Orch

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/docker-sonic-vs/Dockerfile
Those packages are required by sonic-sairedis
**What I did**
Modified az pipeline to install vpp packages
sonic-sairedis have dependency now on those packages
On az pipeline
=> [az] Install vpp artifacts

orchagent/dash/dashrouteorch.cpp, orchagent/dash/dashvnetorch.cpp, tests/dash/test_dash_vnet.py
**What I did**
- Check vnet exists for ROUTING_TYPE_VNET_DIRECT in `addOutboundRouting`
- Not remove outbound routing, route group if in use
- Keep adding OutboundCaToPa and PaValidation consistently
In updating dash vnet test cases - https://github.com/sonic-net/sonic-mgmt/pull/17994, find some DASH objects cannot be added/removed due to the dash object dependency.
All dash objects can be added/removed successfully in dash vnet test.
=> [DASH] Update dash orch

orchagent/fgnhgorch.cpp, orchagent/fgnhgorch.h, orchagent/orchdaemon.cpp, tests/test_fgnhg.py
**What I did**
Orchagent changes for Dynamic Fine Grain Nexthop Group as updated in the HLD PR:
https://github.com/sonic-net/SONiC/pull/1823
A route prefix points to an ECMP group without all the nexthop members of the group known ahead of time and they are dynamically learnt from the BGP updates. FGNHG current implementation required all nexthops to be known ahead and configured statically.
Added FGNHG related DVS tests verified.
Changes were tested with traffic on hardware.
=> FGNHG changes for NHs learned dynamically from BGP

.azure-pipelines/test-docker-sonic-vs-template.yml, tests/conftest.py
=> [build] Support optionally using other container registries instead of DockerHub

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/test-docker-sonic-vs-template.yml, tests/test_mirror.py, tests/test_warm_reboot.py
**What I did**
* Allow partially succeeded swss common artifacts to be pulled
* Temporarily skip some tests that are failing consistently now
To unblock swss test pipeline
By running the pipeline and making sure all tests can pass
=> [ci]: Changes to unblock swss pipeline tests

.azure-pipelines/test-docker-sonic-vs-template.yml
=> Install symlink to Python 3 to work around AzP diff coverage issue

orchagent/bfdorch.cpp
**What I did**
Changed BFD offload capability Log Level to NOTICE Instead of error.
The BFD offload capability is optional for the product, so changing the log level from ERROR to NOTICE.
=> Change Log Level for BFD Offload Capability Implementation

orchagent/request_parser.cpp, orchagent/request_parser.h, tests/request_parser_ut.cpp
**What I did**
Added support for parsing bool list in request.
sign-off: Jing Zhang zhangjing@microsoft.com
I will need to parse a list of boolean values in the request. 
1. verified it with vnet route tunnel requests
2. verified with UTs. 
=> add `parseBoolList` in request parser

tests/test_mux.py
PR #3676 broke vstest for multi-mux. this fixes that.
**What I did**
fix vstest for multi-mux
#3676 had a bug in vstest
#3674 has the fix and vstests pass
=> [202411][test_mux] fix vstest multi-mux

orchagent/dash/dashorch.cpp, tests/mock_tests/dashorch_ut.cpp, tests/mock_tests/dashrouteorch_ut.cpp, tests/mock_tests/dashvnetorch_ut.cpp, tests/mock_tests/mock_dash_orch_test.cpp, tests/mock_tests/mock_dash_orch_test.h, tests/mock_tests/mock_orch_test.cpp
**What I did**
- Program ENI mode to SAI if given in APPL_DB
- Add mock test to cover new behavior
- Refactor mock test code to program DASH APPL_DB tables with protobuf messages
=> [DASH]: Program ENI mode SAI attribute

orchagent/dash/dashhaorch.cpp
**What I did**
Use the exact string mentioned in HLD to align with hamgrd. 
sign-off: Jing Zhang zhangjing@microsoft.com 
=> [haorch] use the exact string mentioned in HLD

cfgmgr/stpmgr.h, orchagent/stporch.cpp, orchagent/stporch.h, tests/mock_tests/stporch_ut.cpp
**What I did**
Fix issue - stpd crashes due to wrong no.of stp instance passed from stpmgrd
=> Fix issue - stpd crashes due to wrong no.of stp instance passed from stpmgrd

orchagent/flex_counter/flex_counter_manager.cpp, orchagent/flexcounterorch.cpp
**What I did**
1. Check whether gPortsOrch is null before dereferencing it
2. Change log severity to INFO in clearCounterIdList when there is no relevant counter IDs
Fix issue #22775 and #22478
Manually test
=> Fix counter issue #22775 and #22478

tests/mock_tests/mux_rollback_ut.cpp
**What I did**
Skip a test that is failing and blocking unrelated PRs
=> [UT] Skip failing mux rollback unit test

orchagent/p4orch/p4oidmapper.cpp, orchagent/p4orch/p4oidmapper.h, orchagent/p4orch/tests/p4oidmapper_test.cpp
**What I did**
Added a method to dump the OID mapping cache as formatted JSON.
To make debugging and state inspection easier.
Added unit tests and checked the JSON output manually.
=> [P4Orch] Implement p4oidmapper dump.

orchagent/p4orch/router_interface_manager.cpp, orchagent/p4orch/tests/router_interface_manager_test.cpp, orchagent/p4orch/tests/test_main.cpp
**What I did**
Added a new feature to the router_interface_manager that allows it to support SUBPORT interfaces.
This was done to make the system more flexible.
=> [P4Orch] Add support for SUBPORT in router_interface_manager.
