orchagent/intfsorch.cpp

1. Incorrect ip prefix parsing is fixed.
2. IntfsTable map is updated after removal of ip address from the interface.
Signed-off-by: Denys Haryachyy <Denys.Haryachyy@caviumnetworks.com>

swss/orchagent : Fixed the case of removing ip address from the interface.

---

.gitignore
Makefile.am
README.md
ThirdPartyLicenses.txt
configure.ac
debian/rules
fpmsyncd/fpm/fpm.h

fpmsyncd: Adding fpm.h file into repo

---

orchagent/intfsorch.cpp
orchagent/neighorch.cpp
orchagent/portsorch.cpp
orchagent/portsorch.h
orchagent/routeorch.cpp
portsyncd/portsyncd.cpp

As most of the applications depend on port initialization, we add
a 'ConfigDone' notification in portsyncd after finishing reading
the file 'port_config.ini'. Before orchagent receives this notification,
all other tasks from other applications are stored without actually
being executed. Only when the orchagent get this notification will all
other tasks been executed.

portsyncd: Adding ConfigDone notification in portsyncd

---

orchagent/orch.cpp
orchagent/orch.h
orchagent/orchdaemon.cpp
orchagent/orchdaemon.h

- Moving all Orch class into a list
- doTask when select() returns TIMEOUT

orchagent: Fixing iterate m_toSync map after select times out

---

doc/swss-schema.md

* Added support for specifying ECN mode values
* Added red_max_threshold
signed-off-by hrachya@mellanox.com

[schema] WRED red max threshold and ECN modes

---

doc/swss-schema.md
orchagent/Makefile.am
orchagent/copporch.cpp
orchagent/copporch.h
orchagent/main.cpp
orchagent/orch.cpp
orchagent/orch.h
orchagent/orchdaemon.cpp
orchagent/orchdaemon.h

* Added new class CoppOrch
* Added schema for COPP_TABLE
Signed-off-by: hrachya@mellanox.com

[sonic-swss] Add support for COPP

---

orchagent/intfsorch.cpp
orchagent/portsorch.cpp
orchagent/portsorch.h

* Trapping ip2me traffic to CPU.

[orchagent] [intfsorch] Adding ip2me route

---

fpmsyncd/routesync.cpp

- This happens when the host interfaces change and then we need to update
the link cache.

fpmsyncd: Re-allocating link cache when interface name cannot be resolved

---

orchagent/copporch.cpp
orchagent/copporch.h
orchagent/orch.h
orchagent/portsorch.cpp
swssconfig/sample/copp.config.json

* Default trap group should be referenced with name 'default' in the configuration json file.
* Create policer and attach to default trap group
* Initialize ttl_error with TRAP action belonging to default trap group.
signed-off-by hrachya@mellanox.com

[orchagent][copp] default trap group support

---

orchagent/bufferorch.cpp
orchagent/bufferorch.h
orchagent/intfsorch.cpp
orchagent/intfsorch.h
orchagent/main.cpp
orchagent/neighorch.cpp
orchagent/neighorch.h
orchagent/orch.cpp
orchagent/orchdaemon.cpp
orchagent/orchdaemon.h
orchagent/portsorch.cpp
orchagent/qosorch.cpp
orchagent/qosorch.h
orchagent/routeorch.cpp
orchagent/routeorch.h
orchagent/tunneldecaporch.cpp
orchagent/tunneldecaporch.h
portsyncd/linksync.cpp

- Moving portsOrch to global
- Adding intfsOrch dependency check
- Adding struct IntfsEntry
- Adding increase/decrease reference count functions
- Removing some trailing '\n's in logs

Moving portsOrch to global

---

portsyncd/portsyncd.cpp

Provided the reading of 'alias' field from port_config.ini, and storing it into Redis DB.

portsyncd: added 'alias' field into PORT_TABLE

---

orchagent/routeorch.cpp

Reverts Azure/sonic-swss#136
This change breaks the test as the current SAI implementation doesn't support the mid-state that the route with packet action DROP is set with next hop ID and packet action FORWARD by two steps. After the SAI implementation is fixed, this change will be re-introduced.

Revert "orchagent: Updating the route next hop ID also sets action to forward"

---

doc/swss-schema.md
orchagent/portsorch.cpp
teamsyncd/teamsync.cpp
teamsyncd/teamsync.h

enabled is a more appropriate option/flag to be tracked and syncd
with the ASIC LAG state. Because 802.3ad LACP is used here, port will
only be put into distributing/collecting mode when it is enabled.
In orchagent, LAG member link up/down logic is removed since when
port is not enabled, it will be directly removed from the LAG.

teamsyncd: Use TEAM_OPTION_CHANGE 'enabled' to track LAG membership

---

orchagent/routeorch.cpp

When routes' next hop interfaces are updated to eth0, they need to
be removed from the ASIC.

[orchagent]: Fixing the issue that routes cannot be removed

---

portsyncd/linksync.cpp
portsyncd/portsyncd.cpp

- allow-hotplug stanza is added to interfaces file
https://github.com/Azure/sonic-swss/issues/165

[portsyncd]: Removing manual commands to bring up interfaces

---

orchagent/intfsorch.cpp

This bug will be triggered when flapping the router interfaces.

[orchagent]: Fixing bug internal entry not removed after DEL

---

teamsyncd/teamsync.cpp

- teamsyncd now tracks the admin/oper status of teams
- teamsyncd supports swss restart to recreate all teams

[teamsyncd]: Supporting docker-swss restart to recreate all teams

---

orchagent/routeorch.cpp
orchagent/routeorch.h

Instead of using the default value of 128, query the switch first to
get the NUMBER_OF_ECMP_GROUPS and use this value as the maximum supported
number of next hop groups. If the query fails, the default value of 128
will be used.
Also fix the corner case by changing '>' to '>=' when checking the number
of next hop groups.

[orchagent]: Add query of NUMBER_OF_ECMP_GROUPS in routeorch

---

orchagent/portsorch.cpp
orchagent/portsorch.h
portsyncd/linksync.cpp

[orchagent]: Remove updating APP_DB port oper_status logic from orchagent

---

orchagent/routeorch.cpp

[routeorch]: Do not set packet action for updating next hop ID

---

orchagent/aclorch.cpp
orchagent/aclorch.h

In order to mitigate https://github.com/Azure/sonic-swss/issues/201

Temporarily disable Acl thread to collect counters

---

orchagent/aclorch.cpp
orchagent/aclorch.h

Due to incorrect usage of thread class and race conditions
from time to time conter thread was accessing AclOrch
object members before thay were initialized.

[acl]: Fix crash in ACL counters thread.

---

orchagent/aclorch.cpp
orchagent/aclorch.h

Lock mutex only at the beginning of critical sections.

[acl]: Simplify AclOrch class locking schema.

---

orchagent/bufferorch.cpp
orchagent/copporch.cpp
orchagent/main.cpp
orchagent/orch.cpp
orchagent/orch.h
orchagent/qosorch.cpp

Similar to sairedis record, this swss record provides a log that records
all applications tasks according to the sequence of incoming messages from
the Redis database queue. The format follows the sairedis record format:
TIMESTAMP|TABLE_NAME:KEY|OP|FIELD:VALUE|FIELD:VALUE|...
The record file is saved at where the daemon is started from, with the file
name swss.TIMESTAMP.rec.
-R option will control both sairedis record and swss record

[orch]: Add SwSS record mechanism that record all tasks from applications

---

orchagent/aclorch.cpp

When ACL rules are created before the corresponding table is created,
orchagent needs to wait under dependency issue is resolved instead
of dropping the tasks.

[aclorch]: Fix ACL rule creation before ACL table creation issue

---

orchagent/orchdaemon.cpp

If it is checked only in TIMEOUT case, the blocked tasks will not be processed
if there are continuous incoming messages.

[orchagent]: Periodically check all m_toSync map in each while iteration

---

orchagent/portsorch.cpp
orchagent/portsorch.h

portsyncd synchronizes net device settings with the PORT_TABLE
Added code to set MTU to hardware on PORT_TABLE update

Add MTU set on port (issue #77)

---

doc/swss-schema.md
orchagent/orchdaemon.cpp
orchagent/portsorch.cpp
orchagent/portsorch.h
portsyncd/linksync.cpp
portsyncd/linksync.h

127.0.0.1:6379> keys VLAN*
1) "VLAN_MEMBER_TABLE:Vlan2:Ethernet7"
2) "VLAN_MEMBER_TABLE:Vlan2:Ethernet10"
3) "VLAN_MEMBER_TABLE:Vlan2:Ethernet25"
4) "VLAN_MEMBER_TABLE:Vlan2:Ethernet15"
5) "VLAN_MEMBER_TABLE:Vlan2:Ethernet39"
6) "VLAN_MEMBER_TABLE:Vlan2:Ethernet58"
7) "VLAN_MEMBER_TABLE:Vlan2:Ethernet37"
8) "VLAN_MEMBER_TABLE:Vlan2:Ethernet42"
9) "VLAN_MEMBER_TABLE:Vlan2:Ethernet9"
10) "VLAN_MEMBER_TABLE:Vlan2:Ethernet55"
11) "VLAN_MEMBER_TABLE:Vlan2:Ethernet22"
12) "VLAN_MEMBER_TABLE:Vlan2:Ethernet53"
13) "VLAN_MEMBER_TABLE:Vlan2:Ethernet40"
14) "VLAN_MEMBER_TABLE:Vlan2:Ethernet12"
15) "VLAN_MEMBER_TABLE:Vlan2:Ethernet6"
16) "VLAN_MEMBER_TABLE:Vlan2:Ethernet29"
17) "VLAN_MEMBER_TABLE:Vlan2:Ethernet13"
18) "VLAN_MEMBER_TABLE:Vlan2:Ethernet27"
19) "VLAN_MEMBER_TABLE:Vlan2:Ethernet48"
20) …

[Vlans]: Extract VLAN_MEMBER_TABLE from VLAN_TABLE

---

orchagent/main.cpp
orchagent/orch.cpp

- Add flexibility to set pop batch size for consumer table. This parameter
affects the speed of consuming entries from the database. Use a larger
number will force the consumer to pop out more entries from the database
on one SPOP operation.

[orchagent]: Add set batch size option to configure consumer table behavior

---

orchagent/portsorch.cpp

When we make port tagged, we don't want to change pvlan_id for the port.

[portsorch]: Set pvlan id only for untagged vlan on a port

---

.gitignore
swssconfig/Makefile.am
swssconfig/swssplayer.cpp

Usage: swssplayer <file>
The file is the SwSS record file get from orchagent. This module
enables better debugging to replay all application tasks to orchagent.
It is a similar tool as saiplayer but dedicated for orchagent.

[swssplayer]: Add swssplayer to replay the swss record file

---

orchagent/intfsorch.cpp
orchagent/intfsorch.h

Issue: https://github.com/Azure/SONiC/issues/22
Issue was observed only when setting IP address via ifconfig
command. Caused by ifconfig command behavior: first is sets
IP address with netmask /8 and then changes netmask to specified
in command. Problem is not observed when set IP address with
"ip addr" command.

Fix issue with setting IP address in run time.

---

orchagent/fdborch.cpp
orchagent/intfsorch.cpp
orchagent/port.h
orchagent/portsorch.cpp
orchagent/portsorch.h
orchagent/routeorch.cpp
orchagent/routeorch.h

1. Change the initialization order
After switch initialization, remove all VLAN members from the default
VLAN and all bridge ports from the default .1Q bridge. Later, router
interfaces and LAG members could be created directly upon the raw ports.
2. VLAN members are created by first creating the corresponding .1Q bridge
ports and then using the bridge ports to create VLAN members.
3. Remove bimap data structure as bridge port ID is not one to one mapping
to port ID. Further work is needed to support multiple bridge port per
port scenarios.
4. Fix ECMP group member removal issue. Use set to store member IDs per
next hop group.

[orchagent]: Support LAG/VLAN with SAI 1.0

---

orchagent/main.cpp

- Instead of creating the switch and later setting the source MAC address,
use the source MAC address as an attribute to create the switch.
- Move corresponding switch attribute code to above the switch creation.

[orchagent]: Create the switch with source MAC address

---

orchagent/main.cpp
orchagent/saihelper.cpp
orchagent/saihelper.h

Move SAI Redis initialization related code outside main function.
In the future, global variables could be eliminated to make code cleaner.
getTimestamp could be moved to common library as well.

[saihelper]: Create initSaiRedis function and put related code inside it

---

orchagent/copporch.cpp
orchagent/copporch.h
swssconfig/sample/00-copp.config.json

Right now we don't have trap priority defined. This will cause packets put into
different queues and dropped due to policer settings. With the trap priority
attribute added, protocol level packets are assigned with higher priorities and
will not be dropped correspondingly.

[copporch]: Add trap priority support and update COPP configurations

---

orchagent/portsorch.cpp

Reverts Azure/sonic-swss#251
This attribute SAI_PORT_ATTR_BIND_MODE is not yet supported by Mellanox.

Revert "[portsorch]: Set port bind mode after adding VLAN member"

---

orchagent/portsorch.cpp

This attribute is removed in the SAI master.
Port can be part of .1D bridge and VLANs at the same time. Hence
bind mode is not necessary.

[portsorch]: Remove SAI_PORT_ATTR_BIND_MODE

---

orchagent/routeorch.cpp

In orchagent, route's next hop packet action is set to DROP. But the previous
next hop object is still referenced by the route. This will cause the next
hop group removal failure.
Reset the drop route next hop ID to NULL to remove the reference for the
previous next hop object.

[routeorch]: Need to set drop route next hop ID to NULL

---

orchagent/portsorch.cpp

- There is a default 1Q router port as a member of the default 1Q
bridge. During initialization, this port is not removed from the
default 1Q bridge.

[portsorch]: Update default bridge port removal logic

---

orchagent/bufferorch.cpp

SAI_BUFFER_PROFILE_THRESHOLD_MODE_DYNAMIC/STATIC attribute is required
in order to set the corresponding threshold values.

[bufferorch]: Add SAI_BUFFER_PROFILE_THRESHOLD_MODE_*

---

orchagent/mirrororch.cpp

This attribute is required to set VLAN TPID and VLAN ID, etc in SAI v1.0

[mirrororch]: Add SAI_MIRROR_SESSION_ATTR_VLAN_HEADER_VALID

---

orchagent/qosorch.cpp
orchagent/qosorch.h
swssconfig/sample/msn2700.32ports.qos.json
swssconfig/sample/msn2740.32ports.qos.json
swssconfig/sample/td2.32ports.qos.json

- Set min thresholds equal to max to preserve default behavior.

[qosorch]: Add possibility to set min value for WRED thresholds.

---

orchagent/fdborch.cpp
orchagent/fdborch.h

- FDB entry creation code update:
Add switch_id, bridge_type, bridge_id to FDB entry
Use bridge port ID as an attribute
- Simplify key tokenization
- Comment table modification code due to race condition issue

[fdborch]: Fix FdbOrch code to work upon SAI v1.0

---

orchagent/qosorch.cpp

- Remove the tasks with erase(it) to avoid looping inside the while
- Refactor the error messages
- Remove table verification code since it is unnecessary

[qos]: Remove failed tasks from the m_toSync queue

---

orchagent/bufferorch.cpp
orchagent/qosorch.cpp

- Remove the task with erase(it) to avoid looping inside the while
- Align the code and refactor the error messages
- Remove table verification code since it is unnecessary

[buffer]: Remove failed tasks from the m_toSync queue

---

orchagent/orch.cpp
orchagent/orch.h
orchagent/orchdaemon.cpp
orchagent/orchdaemon.h

I will merge this PR after v1.0.3 merged into master.
Following https://github.com/Azure/sonic-swss-common/pull/115

Refactor Consumer*Table interface

---

orchagent/orch.cpp

For route sync performance, original implementation will pop route one-by-one, and go through m_toSync each time. If using pops(), the times of loop m_toSync will decrease largely.

Optimize orch performance by pops()

---

orchagent/Makefile.am
orchagent/orchdaemon.cpp
orchagent/orchdaemon.h
orchagent/switchorch.cpp
orchagent/switchorch.h

Right now, three switch attributes are supported: FDB unicast/multicast/
broadcast miss packet action. The attribute could be set to drop, forward,
or trap.
The current implementation adds switch configuration to the APPL_DB.
In the future, it would be migrated to the CONF_DB.
**What I did**
Add the functionality of updating switch attributes. This architecture also allows future expansion for richer attributes other than FDB related ones.
It's a feature request from various sources.
Use `swssconfig` to load a switch attribute set JSON file and check in the database if this attribute is set.

[switchorch]: Add SwitchOrch to deal with switch attributes changes

---

swssconfig/sample/msn27xx.32ports.buffers.json.j2

**What I did**
Updated Mellanox buffer profile template to work in 1.0.3
Changes in minigraph parser made template incompatible with the new names exported
Build SONiC, ensured buffers profile is generated, applied, records in DB created.

Updated Mellanox buffer profile template to work in 1.0.3

---

portsyncd/linksync.cpp
portsyncd/linksync.h

**What I did**
Remove unused variables
Refactor the code
Bulid

[portsyncd]: Remove unused LAG related tables

---

swssconfig/sample/msn27xx.32ports.buffers.json.j2

**What I did**
Updated buffer profile template to produce config even when there are no ports speed and cable length info in the minigraph
Buffer config failed to generate on incomplete minigraph
Verified buffer config generated and applied on incomplete minigraph
By default "worst case values"  are used (100G and 300m)

Update Mellanox buffer profile template to work with an incomplete minigraph

---

orchagent/portsorch.cpp
orchagent/portsorch.h
portsyncd/portsyncd.cpp

[portsorch]: Add support of cable breakout feature

---

orchagent/switchorch.cpp

[switchorch]: Add support of ECMP and LAG hash seed attribute

---

orchagent/portsorch.cpp

[portsorch]: Update comments

---

orchagent/portsorch.cpp

Keep object IDs serializeable in database,
so that they can be reused later by client code

[portsorch]: Use sai_serialize api to write to DB

---

orchagent/portsorch.cpp

Rename vector -> tuples since vector is a keyword.

[portsorch]: Rename confusing variable names

---

orchagent/pfcactionhandler.cpp
orchagent/pfcactionhandler.h

PFC storm drop handler that applies zero size buffer profile to a queue, also
has to apply zero size profile to ingress PG to drop RX traffic too.
Code that creates profiles and pools was refactored to always create
only one mode of pools/profiles (because it actually doesn't matter which mode
is configured - traffic is dropped anyway).

[pfcwdactionhandler]: Add PG setting

---

orchagent/aclorch.cpp
orchagent/aclorch.h
orchagent/copporch.cpp
orchagent/orch.h
orchagent/portsorch.cpp
orchagent/qosorch.cpp
orchagent/routeorch.cpp

For other platform that do not support SAI create/remove_port API,
generate a log message instead of crash.
**What I did**
Limit FlexPort feature (port breakout feature) to only Mellanox Platform
Only mellanox platform currently support this feature. Other platform would crash if we do not do this limit.
Change port_config.ini and tested the new syslog messages.
```
Oct  5 05:53:16.002653 str-a7050-acs-1 NOTICE orchagent: :- doPortTask: Failed to remove Port 1000000000022 due to missing SAI remove_port API.
Oct  5 05:53:16.011418 str-a7050-acs-1 NOTICE orchagent: :- doPortTask: Failed to create Port Ethernet124 due to missing SAI create_port API.
```

Limit FlexPort feature to only Mellanox Platform

---

orchagent/pfcactionhandler.h
orchagent/pfcwdorch.cpp
orchagent/pfcwdorch.h

Alert mode tells watchdog that whenever it detects PFC storm, it should
only write message to the log. It is implemented as a separate action
along with drop and forward.

[pfcwdorch]: Add alert mode

---

orchagent/switchorch.cpp

Please also provide the following information in this pull request:
-->
**What I did**
Fix orchagent hang problem caused erase operation on empty map
https://github.com/Azure/sonic-swss/issues/347
After the change, switch attributes may be set without problem.
swss.rec:
2017-10-13.06:00:03.019460|SWITCH_TABLE:SWITCH_ATTR|SET|fdb_unicast_miss_packet_action:drop|fdb_multicast_miss_packet_action:forward|fdb_broadcast_miss_packet_action:forward
2017-10-13.06:00:21.739177|SWITCH_TABLE:SWITCH_ATTR|SET|fdb_unicast_miss_packet_action:forward|fdb_multicast_miss_packet_action:forward|fdb_broadcast_miss_packet_action:drop
sairedis.rec: 
017-10-13.06:00:03.019580|s|SAI_OBJECT_TYPE_SWITCH:oid:0x21000000000000| …

Fix orchagent hang problem caused by erase operation on empty map

---

orchagent/bufferorch.cpp
orchagent/bufferorch.h

**What I did**
1. Cleaned up function BufferOrch::processBufferPool and BufferOrch::processBufferPRofile, cache the repeated used attributes in local variables. And use local variable in function.
2. Re-organized some buffer related definitions to place related definitions close to each other.
1. Minor performance optimization.
2. Code readability.
This is non-functional change. It passed nightly tests on 2 duts.

[swss] a couple non-functional code cleanup changes

---

teamsyncd/teamsync.cpp
teamsyncd/teamsync.h
teamsyncd/teamsyncd.cpp

Create an entry in stateDB for each LAG created, and delete the entry when lag removed

Add support for lag state in stateDB

---

portsyncd/linksync.cpp
portsyncd/linksync.h
portsyncd/portsyncd.cpp

- Add m_stateTableProducer to write to the state database once the ports are ready
- Remove suffix Consumer in some variables since they are not 'consumers'

[portsyncd]: Add producer for state database updates

---

orchagent/aclorch.cpp
orchagent/aclorch.h
orchagent/bufferorch.cpp
orchagent/copporch.cpp
orchagent/fdborch.cpp
orchagent/intfsorch.cpp
orchagent/mirrororch.cpp
orchagent/neighorch.cpp
orchagent/orch.cpp
orchagent/pfcwdorch.cpp
orchagent/portsorch.cpp
orchagent/qosorch.cpp
orchagent/routeorch.cpp
orchagent/switchorch.cpp
orchagent/tunneldecaporch.cpp

This change is the first step of refactoring Orch class.
The global variable gPortsOrch is removed from that orch.cpp file
and this class no longer requires such external variable.
The current solution is to move the global variable into each different
places that need this variable. Later, a better design could be
introduced to further remove all the global variables from the whole
project.
**What I did**
Remove the gPortsOrch from the orch.cpp file.
Free the orch.cpp file.
Compile and run the code.

[orchagent]: Remove the global variable gPortsOrch in orch.cpp file

---

orchagent/orchdaemon.cpp
orchagent/pfcwdorch.cpp
orchagent/pfcwdorch.h
orchagent/portsorch.cpp
orchagent/portsorch.h

This reverts commit 87649024c03fd0a2233628a4be586ae672de5697.
**What I did**
revert commit 8764902
Update port and queue stat counters by Flex counter (#358) [AndriiS]
The commit needs https://github.com/Azure/sonic-sairedis/pull/230 to be merged first.
Revert it and tested with the latest sonic buildimage.

Revert "Update port and queue stat counters by Flex counter (#358)"

---

orchagent/bufferorch.cpp
orchagent/bufferorch.h

This commit adds new code to support PFC shared headroom pool size
(Ingress) for lossless traffic feature.  This is one of the requirement
for PFC support on SONiC.
Verified by using a JSON configuration file to push the XOFF parameter
to program in Hardware.  XOFF parameter in JSON file translates to
SAI_BUFFER_POOL_ATTR_XOFF_SIZE which gets programmed in register
THDI_HDRM_BUFFER_CELL_LIMIT_HP. The register was programmed with correct
values.
Signed-off-by: Harish Venkatraman <Harish_Venkatraman@dell.com>

[orchagent] Add PFC shared headroom support

---

orchagent/pfc_restore.lua
orchagent/pfcwdorch.cpp

In case if user does not pass restoration time, it is assumed that queue
will be mitigated indefinitely in an event of PFC storm until user disables
watchdog on that port.

[pfcwdorch]: Allow unlimited restoration time

---

cfgmgr/vlanmgrd.cpp

**What I did**
change vlanmgrd to read switch mac from DEVICE_METADATA|localhost entry
unify the switch level attribute to DEVICE_METADATA field. 
Check the wiki. https://github.com/Azure/SONiC/wiki/Configuration
```
admin@str-s6000-on-1:~$ redis-cli -n 4 hget "DEVICE_METADATA|localhost" "mac"                    
"00:00:11:11:11:11"
```

read switch mac from DEVICE_METADATA|localhost:mac

---

portsyncd/portsyncd.cpp

Signed-off-by: Haiyang Zheng <haiyang.z@alibaba-inc.com>
**What I did**
Now, portsyncd is subscribed to config DB, and use handlePortConfig to copy port config from config DB to APP DB. Here, we also need to update the host interfaces MTU in linux kernel if the port config changes.
Otherwise, there will be discrepancy between linux kernel MTU and port MTU in config DB/app DB. 
Update the port inside config_db.json file with new mtu field, and verify both kernel MTU and ASIC port MTU has been updated properly.
This pull request require the following pull request
https://github.com/Azure/sonic-buildimage/pull/1128
With both changes, the MTU from config DB will be the only source for Kernel MTU and port MTU on ASIC.

[mtu] Update the mtu on host interfaces if config DB changes

---

debian/swss.install
swssconfig/sample/th.64ports.buffers.json
swssconfig/sample/th.64ports.qos.json

This commit adds new code and JSON file to support PFC and broadcom
recommended MMU settings for PFC feature. The JSON has the Broadcom
recommended settings. JSON file dynamic_th values are exponent values
for ALPHA setting taken from SAI code.
Verified by running the JSON configuration file and checking the
hardware registers and tables. The setting in the hardware was reflecting
the Broadcom recommended values.
Signed-off-by: Harish Venkatraman <Harish_Venkatraman@dell.com>

[sonic-swss]: Add PFC Broadcom recommeded MMU Settings

---

portsyncd/portsyncd.cpp

**What I did**
remove ports enumerating in portsyncd init
portsyncd enumerate all ports in initialization phase via netlink.
which is not neccessary by design. portsyncd is supposed to read
the port_config.ini and translate them into appdb, and then once
all ports are created, it sets PortInitDone.
enumerating all ports in the initialization causes issue in swss
restart. When swss restarts, the old ports are still here which
triggers portsyncd to set PortInitDone falsely.
manually restart swss.service and also reboot the box.
verify vlan and vlan member are created correctly

[bug]: do not enumerate all ports in portsyncd init

---

portsyncd/linksync.cpp

**What I did**
In netlink process for link events, a new interface creation always comes without a _master_ or _admin_ status set to iff_up.  These are set after the interface is created. In this way, if the first netlink message comes with master set,  add it to `old-interface-map` and ignore this and all subsequent netlink message for this `ifIndex`. 
Without this fix, portsynd publishes the old interface events to stateDB. This resulted in failure of bridge creation and member port addition. Also, the newly created interfaces were not made admin-up
Related bug - https://github.com/Azure/sonic-buildimage/issues/1153
Restart swss in t0/t1-lag topology
Execute 'sudo brctl show', 'ip link show' and ensure bridge is added with member ports and links …

Ignore netlink messages for old interface during swss restart

---

cfgmgr/shellcmd.h
cfgmgr/vlanmgrd.cpp

this enforces portablity of vlanmgrd
Signed-off-by: Wataru Ishida <ishida.wataru@lab.ntt.co.jp>
**What I did**
Use `sonic-swss-common` instead of executing `redis-cli` to get MAC address of the device.
This is kinda refactoring but I'm actually facing a problem with current implementation.
I'm running `redis-server` in a diffrent docker container from a container which runs sonic's daemons.
Two containers shares a redis unix socket file and doesn't share a network namespace.
In this case, `vlanmgrd` crashes since current implementation executes `redis-cli` directly to get MAC address.
Since we are passing `DBConnector::DEFAULT_UNIXSOCKET` to `DBConnector `, using `sonic-swss-common` can solve this issue.
Also, we can easily add an option to `vlanmgrd` for choosing how to …

[cfgmgr] Use sonic-swss-common instead of exec redis-cli

---

orchagent/portsorch.cpp

The hardcoded for loop was not the good option to query all
IDs defined in the SAI header. While only limited partial of
the counters are needed, we don't need to query each of them.

[portsorch]: Only add stat IDs that are needed to query

---

orchagent/pfcwdorch.cpp
orchagent/pfcwdorch.h

[PFCWD]: Set correct polling interval for pfcWdOrch object

---

orchagent/switchorch.cpp

Signed-off-by: Haoran Liu gongjian.lhr@alibaba-inc.com
**Add codes in switchorch to support changing mac aging time dynamically**

[switchorch]:support changing mac aging time dynamically.

---

cfgmgr/vlanmgr.cpp

**What I did**
use IP cmd to setup vlan_filter as a backup method
echo will fail in virtual switch since /sys directory is read-only.
need to use ip command to setup the vlan_filtering which is not available in debian 8.
Once we move sonic to debian 9, we can use IP command by default 
build virtual switch and verified.
Will generate an PR to add test for virtual switch. The test will be in another PR since we need to build the new virtual switch docker first.

use IP cmd to setup vlan_filter as a backup method

---

portsyncd/portsyncd.cpp

**What I did**
read port configuration from configDB when `-p` is not specified.
configDB is the master data of port configuration.
We can simply use it instead of passing dedicated configuration file for `portsyncd`
Run `portsyncd` without `-p` option.

[portsyncd] support read port configuration from configDB

---

orchagent/orchdaemon.cpp
orchagent/pfcwdorch.cpp

**What I did**
Create queue pfcwd handler only when it doesn't exist.
Redis pub/sub might have latency and it's possible that orchagent receives multiple storm/restore notification continuously. This PR is to prevent orchagent keeps creating new handler smart pointer and removing existing one in such case. Instead, it will only honor the first notification and do the corresponding operation.
Verified on DUT

[pfcwd]: create queue pfcwd handler only when it doesn't exist

---

tests/README.md

**What I did**
Fixed readme file
Incomplete instruction how to build swss-common, wrong formatting
Manually

[Tests]: Readme fixes

---

orchagent/aclorch.cpp
orchagent/portsorch.cpp

**What I did**
Allowed to bind ACL table to LAGs and VLANs.
Denied to bind ACL table to LAG members.
Fixed issue with ACL table type and ports validation.
All changes are done in the scope of ACL dynamic configuration feature.
Manual tests
Run ACL testbed tests

[acl]: Allow ACL table bind to LAGs and VLANs.

---

orchagent/pfcactionhandler.cpp
orchagent/pfcactionhandler.h

**What I did**
Inherit PfcAclHandler from PfcLossyHandler instead of PfcActionHandler
PfcActionHandler is the base class. And in PfcLossyHandler (inherits from PfcActionHandler), it adds support to disable PFC once storm is detected. Since this function is also needed for PfcAclHandler. We need to let PfcAclHandler inherit from PfcLossyHandler instead of the base class.
Test on DUT

[pfcwd]: Inherit PfcAclHandler from PfcLossyHandler

---

orchagent/orchdaemon.cpp

**What I did**
Rename FLEX_COUNTER_POLL_MSECS to PFC_WD_POLL_MSECS  and move definition to swss common repo.
As this variable is specific to PFCWD, rename it to better match its function. sairedis also need this variable, so move to swss-common.
Test on DUT

[pfcwd]: rename FLEX_COUNTER_POLL_MSECS  and move define in swss common

---

orchagent/pfcactionhandler.cpp
orchagent/pfcactionhandler.h

**What I did**
Add port name and queue index in the syslog message when pfc storm is detected or restored.
It's more user-friendly, and normal user can have straightforward Ethernet port name from syslog instead of only sai_stat_t ids.
Verified on DUT.

[pfcwd]: Log port name and queue index during storm detect/restore

---

orchagent/portsorch.cpp

**What I did**
Only query needed port stat sai attributes.
The hardcoded for loop was not the good option to query all
IDs defined in the SAI header. While only limited partial of
the counters are needed, we don't need to query each of them
Verified on DUT

[portsorch]: Only add port stat IDs that are needed to query

---

orchagent/pfcwdorch.cpp

Having executors with same names results in only first being registered.

[pfcwd]: Assign different names to executors.

---

orchagent/bufferorch.cpp
orchagent/bufferorch.h

This commit adds new code to support XON_OFFSET support for PFC Buffer Profile.
The XON_OFFSET value is passed from JSON file.
Verified by running the JSON file with XON_OFFSET in buffer_profile and checked
the hardware registers The setting in the hardware was reflecting the JSON values.
Signed-off-by: Harish Venkatraman <Harish_Venkatraman@dell.com>
**What I did**

[sonic-swss/orchagent]: Added XON_OFFSET support

---

cfgmgr/shellcmd.h
cfgmgr/vlanmgr.cpp
orchagent/pfcactionhandler.cpp

Use bash -c to minimize numbers of fork-execs in the Vlan Manager
**What I did**
I rewrote vlanmgr to minimize number of fork-execs in the code. Now vlanmgr should work faster and generate less tasks.
Because I found that vlanmgr used a lot of resources when SONiC started. It slowed down SONiC start time.
Manually checked output of ip and bridge commands.
It's better to avoid using ip and bridge command completely. But I found that currently libnl3 doesn't support vlan_filtering feature and also knows nothing about bridge vlans. Also I found that ioctls don't support everything I need. Later it's possible to rewrite the code using libmnl library which is recommended to be used by creators of iproute2.

[vlanmgr]: Run a sequence of shell commands using bash -c

---

tests/test_speed.py

**What I did**
Added test for port speed change and PG buffer profile update
Ran the test and checked it passes
should pass after
https://github.com/Azure/sonic-swss/pull/417 and
https://github.com/Azure/sonic-buildimage/pull/1250
are merged

Add speed and buffer set test

---

orchagent/orchdaemon.cpp
orchagent/pfcwdorch.cpp
orchagent/pfcwdorch.h
orchagent/portsorch.cpp
orchagent/portsorch.h

**What I did**
Make the polling interval configurable
Extend the feature.
Test on DUT

[PfcWd]: Make polling interval configurable

---

cfgmgr/buffermgr.cpp
cfgmgr/buffermgr.h
cfgmgr/buffermgrd.cpp

**What I did**
Add xon_offset support to buffer manager.
We will set xon_offset in production. The orchagent support has been checked in. This PR adds the matching buffer manager support.
1. Tested with a pg_profile_lookup.ini without xon_offset column, the profiles were applied with xon_offset set to 0xffff (SAI default).
2. Tested with a pg_profile_lookup.ini with xon_offset column, the profiles were applied with xon_offset set to the expected value.
3. Changed xon_offset values and rebooted dut, new values were applied.
4. A test will come to test the profile generation, making sure the profile contains the correct values.

[swss - buffer manager] set xon_offset when available in lookup table

---

portsyncd/portsyncd.cpp

**What I did**
- Parse the column header to decide column ordering.
- Extra column(s) will be ignored.
When processing a port_config.ini with columns name, lanes, alias, index, speed. Though portsyncd ignores the index column, it didn't skip the values in the column, the values were read as speed. Later causing orchagent to crash after setting values in index column as port speed.
With the change, orchagent stayed up, the values were process correctly, and all ports went online.

[portsyncd] allow port syncd to parse port_config.ini in random column order

---

orchagent/pfc_detect_broadcom.lua
orchagent/pfc_detect_mellanox.lua
orchagent/pfc_restore.lua
orchagent/pfcactionhandler.cpp

**What I did**
Check whether the value is nil before redis set
During pfcwd start/stop, occasionally have the following error if orchagent removes the entry before lua script runs.
ERR syncd: :- runRedisScript: Caught exception while running Redis lua sc
ipt: ERR Error running script (call to f_ac71cbd58a59a2d9e49ff896ab51b8d189d4acd2): @user_script:83: @user_script: 83: Lua r
dis() command arguments must be strings or integers : Input/output error\n\n[LogAnalyzer][diagnostic]:matching line: Feb 23 
0:07:48.075531 str-s6000-acs-13 ERR syncd: :- guard: RedisReply catches system_error: command: *63#015#012$7#015#012EVALSHA#
Run on DUT

[lua]: Only set the entry values when they are not nil

---

orchagent/crmorch.cpp
orchagent/crmorch.h
orchagent/orch.cpp
orchagent/orch.h
tests/test_crm.py

**What I did**
make reset crm polling interval effective immediately
it takes too long to run the crm test
passing swss integration test
```
lgh@gulv-vm1:/data/sonic/sonic-swss/tests$ sudo pytest -v --dvsname=vs test_crm.py 
======================================================== test session starts ========================================================
platform linux2 -- Python 2.7.12, pytest-3.3.1, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python
rootdir: /data/sonic/sonic-swss/tests, inifile:
collected 10 items                                                                                                                  
test_crm.py::test_CrmFdbEntry PASSED …
```

make reset crm polling interval effective immediately

---

orchagent/neighorch.cpp
orchagent/neighorch.h
orchagent/orchdaemon.cpp
orchagent/portsorch.cpp
orchagent/routeorch.cpp
orchagent/routeorch.h
tests/test_nhg.py

These changes introduce support for ecmp acceleration for physical i/f down events. The design document was reviewed a couple of months back and checked into the repo.
The functionality has been verified through manual testing in a physical topology having 2 T0 switches (asw01, asw02) connected 4-way to 4 T1 switches (csw01, csw02, csw03, csw04). IXIA was connected in the topology to both T0 switches. Prefixes were advertised to asw02 and traffic was towards asw01. The ecmp acceleration was tested by bring down the links in different combinations on the T1 devices and checking the membership through logs on asw01 as well as having IXIA measure the traffic loss duration.
Nikos.-

ECMP acceleration for physical i/f down events

---

orchagent/pfc_restore.lua
orchagent/pfcwdorch.cpp
orchagent/pfcwdorch.h

**What I did**
1. Only init counter when handler is created
2. Update lua script to support infinite restoration time
3. Clean up no need code
Tested on DUT

[pfcwd]: only init counter when creating action handler

---

orchagent/fdborch.cpp

**What I did**
CRM FDB _used_ counters are incremented/decremented based on STL return values
With some SAI vendors, the FDB entries that are programmed via application, is also notified back by the SAI. This resulted in double increment of _used_ counter for the same FDB entry.  In another case, observed some notifications for _AGE_ out FDB entries that are not originally added. This resulted in incorrect decrement of CRM counters. 
Check CRM counters after adding FDB entry and _used_ counter must be same as the number of entries _added_
**Duplicate add case:**
```
NOTICE orchagent: :- addFdbEntry: Create dynamic FDB 52:54:00:25:07:e9 on Ethernet0
INFO orchagent: :- update: FdbOrch notification: mac 52:54:00:25:07:e9 is …
```

Update FDB CRM counters based on return value

---

cfgmgr/buffermgr.cpp
cfgmgr/intfmgr.cpp
cfgmgr/vlanmgr.cpp
cfgmgr/vlanmgrd.cpp
orchagent/orch.cpp
portsyncd/linksync.cpp
portsyncd/portsyncd.cpp
teamsyncd/teamsync.cpp
tests/test_acl.py
tests/test_crm.py
tests/test_dirbcast.py
tests/test_fdb.py
tests/test_speed.py
tests/test_vlan.py
tests/test_vrf.py

Required to make sonic-swss work with https://github.com/Azure/sonic-swss-common/pull/190

Align with swss-common table name separator changes

---

orchagent/fdborch.cpp

**What I did**
I modified getPort function in FdbOrch, where the key for get_attribute hadn't set switch_id. It was the same for  removeFdbEntry. I just added it like addFdbEntry.
I found a bug that mirror didn't work when mirrored to an vlan interface, while ok for port interface.
After checking the syslog, I found ERR that said failed to get bridge port ID, while the entry can be found in DB. Then read the source code and I found that meta_key for fdb_entry was serialized as a whole, so the key string included switch_id, so in our case it failed in checking object_exists.
ERR orchagent: :- getPort: Failed to get bridge port ID for FDB entry 00:1b:21:bb:2f:de, rv:-5

FdbOrch getPort failed because fdb_entry have no switch_id

---

orchagent/pfc_detect_broadcom.lua
orchagent/pfc_detect_mellanox.lua
orchagent/pfc_restore.lua
orchagent/pfcactionhandler.cpp
orchagent/pfcwdorch.cpp
orchagent/pfcwdorch.h

**What I did**
Enable support for BIG_RED_SWITCH mode:
The Expect behavior:
1. When BIG_RED_SWITCH mode is enabled:
- Regardless of PFCWD configuration or PFC storm status, PFCWD starts to drop all lossless TC packets on all ports. It's a big red button to drop all lossless packets "blindly".
- PFCWD will not do storm check/restore once BIG_RED_SWITCH is enabled. If there is some active action handler handling ongoing PFC storm when enabling BIG_RED_SWITCH, stop these handlers and rely on BIG_RED_SWITCH to drop all the packets.
- Lossy traffic should not be affected.
2. When BIG_RED_SWITCH mode is disabled:
PFCWD goes back to normal, and start to check/restore pfc storm.
3. BIG_RED_SWITCH mode can be enabled and disabled anytime even if PFCWD …

[pfcwd]: support BIG_RED_SWITCH mode

---

cfgmgr/buffermgrd.cpp
cfgmgr/intfmgrd.cpp
cfgmgr/vlanmgrd.cpp
fpmsyncd/fpmlink.cpp
fpmsyncd/fpmlink.h
fpmsyncd/fpmsyncd.cpp
intfsyncd/intfsyncd.cpp
neighsyncd/neighsyncd.cpp
orchagent/orch.h
orchagent/orchdaemon.cpp
portsyncd/portsyncd.cpp
teamsyncd/teamsync.cpp
teamsyncd/teamsync.h
teamsyncd/teamsyncd.cpp

**Please don't push into the master**
**What I did**
Refactor swss to support refactored swss-common
Because refactored version has changed interface of Select class (fd parameter was removed from Select::select() method) and also Selectable interface was changed
Build new image, install it on str-s6100-acs-1 and run FR test
This PR relies on the following PR: https://github.com/Azure/sonic-swss-common/pull/192

Use the refactored version of Selectables

---

cfgmgr/vlanmgr.cpp

**What I did**
Fix the incorrect ip link del command for vlan remove.
Incorrect IP link del command causes vlanmgr to exit.
vlan del command now works:
config vlan add 1200
config vlan del  1200
config vlan add 1200

[vlanmgr]: Fix the incorrect ip link del command for vlan remove

---

orchagent/fdborch.cpp
orchagent/neighorch.cpp

**What I did**
Modified crmorch stats for neighbor used counter. Increase it just after create neighbor entry success. Decrease it when remove neighbor entry success in case of add nexthop failure.
Test found bug.
By code walkthrough I found neighbor used counter increased both before and after add nexthop.
before add ipv4 neighbor,the value of crm_stats_ipv4_neighbor_used is 8
3) "crm_stats_ipv4_neighbor_used" 
4) "8"
after add one ipv4 neighbor,the value of crm_stats_ipv4_neighbor_used is 10
3) "crm_stats_ipv4_neighbor_used" 
4) "10"

[crmorch]: neighbor used counter increased twice

---

orchagent/fdborch.cpp
orchagent/intfsorch.cpp
orchagent/neighorch.cpp
orchagent/orch.cpp
orchagent/orch.h
orchagent/orchdaemon.cpp
orchagent/portsorch.cpp
orchagent/portsorch.h
orchagent/routeorch.cpp

**What I did**
I've added support of Selectable priorities for orchagent.
I've put following priorities to orchagent tables:
```
APP_PORT_TABLE_NAME = 45
APP_VLAN_TABLE_NAME = 42
APP_LAG_TABLE_NAME = 42
APP_VLAN_MEMBER_TABLE_NAME = 40
APP_LAG_MEMBER_TABLE_NAME = 40
APP_INTF_TABLE_NAME = 35
APP_NEIGH_TABLE_NAME= 30
APP_FDB_TABLE_NAME = 20
APP_ROUTE_TABLE_NAME = 5
```
All other orchagent run with lowest priority which is 0.
To prioritize messages inside of the orchagent message queue.
Build swss and run it

[orchagent]: Use priorities in orchagent

---

tests/test_crm.py

**What I did**
Updated CRM test case to check for exact used counter for IPv4/v6 neighbor tables
https://github.com/Azure/sonic-swss/pull/472 fixed the double increment for neighbor counters.
This PR is to check for the usage based on exact used counter.
Run CRM VS test case (In-progress)
N/A

Updated CRM test case to check for exact used counter

---

orchagent/aclorch.cpp
orchagent/aclorch.h
orchagent/pfcactionhandler.cpp
orchagent/pfcactionhandler.h

**What I did**
Create a new ACL type called for PFCWD
L3 ACL has many qualifiers that are not needed for PFCWD. Creating L3 ACL consumes more resources than needed, which will cause issue when the ACL resources is limited.
Tested on DUT

[pfcwd]: create PFCWD acl instead of L3 ACL

---

orchagent/pfcactionhandler.cpp

**What I did**
Fixed used by pfcwd "zero buffer profile" parameters (alpha)
To create proper profile which will drop packets
Create/simulate storm on port, make sure pfcwd assigned "zero profile" on one of it's queues

[PFCWD] Fix ZeroBufferProfile parameters

---

cfgmgr/buffermgr.cpp
cfgmgr/buffermgr.h

**What I did**
Fixed issue which may leave switch not fully configured when speed is applied before cable length table
Bug fix
Forced CABLE_LENGTH to be applied the last and checked switch completes config after all input i available.

Fix tables handling race condition in buffermgr

---

orchagent/portsorch.cpp
orchagent/portsorch.h

**What I did**
Separate port and queue query. By default query port counters every 1s, and queue counters every 10s
Querying all queue counters every 1s is cpu consuming. Reducing queue counter query rate helps to reduce cpu overhead. 
Tested on DUT.

[counters]: separate query of port/queue counters

---

orchagent/qosorch.cpp
orchagent/qosorch.h

**What I did**
Optimized qosorch to make it run faster. I'm caching intermediate results, to avoid re-request the information which was already requested from ASIC.
It reduces qosorch working time significantly. For example on the target platform it was reduced by 4 secs.
Here the statistics of SAI requests before and after the change:
Before:
```
128 SAI_OBJECT_TYPE_INGRESS_PRIORITY_GROUP - 128 set
832 SAI_OBJECT_TYPE_PORT                   - 512 get, 320 set
128 SAI_OBJECT_TYPE_QUEUE                  - 128 set 
2304 SAI_OBJECT_TYPE_SCHEDULER_GROUP        - 256 set, 2048 get
256 SAI_OBJECT_TYPE_SWITCH                 - 256 get
2816 SAI_STATUS_SUCCESS                     - results of get
```
After:
```
128 SAI_OBJECT_TYPE_INGRESS_PRIORITY_GROUP - 128 set
448 …
```

[qosorch]: Optimizations of qosorch

---

portsyncd/linksync.cpp
portsyncd/linksync.h

**What I did**
During swss initialization, iterate through the existing kernel interfaces and populate cache. Also bring down the _old_ interfaces during initialization 
During swss initialization (swss restart, load minigraph), it was observed that sometimes Netlink messages are generated for _old_ kernel interfaces which incorrectly results in populating the state_db and notifying subscribers as interface create. By having the old interface cache, this Netlink messages could be ignored. 
Do config load_minigraph, service swss restart and verify logs
The following logs are meant to show the `ifindexes ` and `timestamps `on when it is added to `state_db`
```
May  1 01:07:44.661599 str-s6100-acs-5 INFO supervisord: portsyncd …
```

Populate existing interface cache, bring down before configDone

---

orchagent/pfc_restore.lua

**What I did**
Use not command to check whether the field exists
Redis will convert nil to false in lua script. Need to use "not a" instead of "a==nil"
Redis to Lua conversion table.
Redis integer reply -> Lua number
Redis bulk reply -> Lua string
Redis multi bulk reply -> Lua table (may have other Redis data types nested)
Redis status reply -> Lua table with a single ok field containing the status
Redis error reply -> Lua table with a single err field containing the error
**Redis Nil bulk reply and Nil multi bulk reply -> Lua false boolean type**

[lua]: use not command to check whether the field exists

---

orchagent/pfcactionhandler.cpp
orchagent/pfcactionhandler.h
orchagent/pfcwdorch.cpp
orchagent/pfcwdorch.h

For every action handler call commitCounters on a periodic basis

[PFCWD]: Periodically poll WD counters

---

teamsyncd/teamsync.cpp

Without the return value check, it is possible that ifname is
empty due to interface not found.

[teamsyncd]: Add team_ifindex2ifname return value check

---

orchagent/bufferorch.cpp
orchagent/pfcactionhandler.cpp

**What I did**
fix SAI_BUFFER_PROFILE_ATTR_SHARED_DYNAMIC_TH value type mismatch bug
according to SAI_BUFFER_PROFILE_ATTR_SHARED_DYNAMIC_TH defination in saibuffer.h:
/**
* @brief Dynamic threshold for the shared usage
*
* The threshold is set to the 2^n of available buffer of the pool.
*
* @type sai_int8_t
* @flags MANDATORY_ON_CREATE | CREATE_AND_SET
* @condition SAI_BUFFER_PROFILE_ATTR_THRESHOLD_MODE == SAI_BUFFER_PROFILE_THRESHOLD_MODE_DYNAMIC
*/
SAI_BUFFER_PROFILE_ATTR_SHARED_DYNAMIC_TH,
the value type is a sai_int8_t, support negative value
on centec goldengate chip platform, we support range [-7, 3], 
but currnetly in swss, uint32 type value is used, have to fix it
1. build success
2. startup and init success
3. set a negative value to …

[orchagent]fix SAI_BUFFER_PROFILE_ATTR_SHARED_DYNAMIC_TH value type mismatch bug

---

orchagent/neighorch.cpp

* [crmorch]: neighbor used counter increased twice
**What I did**
Cherry-picked the https://github.com/Azure/sonic-swss/pull/472 PR
The bug with duplicate neighbor count is present in 201803 branch
1) `crm show resources ipv4 neighbor` shows 0
2) Adding 10 neighbors
3) `crm show resources ipv4 neighbor` shows 10

[crmorch]: neighbor used counter increased twice (#472) - Cherry-pick to 201803 branch

---

orchagent/portsorch.cpp

Don't print 'orchagent: :- doPortTask: Failed to get port id by alias PortConfigDone error'
**What I did**
Don't print 'orchagent: :- doPortTask: Failed to get port id by alias PortConfigDone error'
Because this error message was an error
Build swss and run it

[portsorch]: Don't print error when alias equal to PortConfigDone

---

orchagent/aclorch.cpp

**What I did**
Remove SAI_ACL_TABLE_ATTR_FIELD_TC from data/mirror acl type
SAI_ACL_TABLE_ATTR_FIELD_TC is a qualifier specific for ACL_PFC_WD type. So remove it for other L3/mirror ACL type.

[aclorch]: remove SAI_ACL_TABLE_ATTR_FIELD_TC from data/mirror acl type

---

orchagent/bufferorch.cpp
orchagent/pfcactionhandler.cpp

**What I did**
fix SAI_BUFFER_PROFILE_ATTR_SHARED_DYNAMIC_TH value type mismatch bug
according to SAI_BUFFER_PROFILE_ATTR_SHARED_DYNAMIC_TH defination in saibuffer.h:
/**
* @brief Dynamic threshold for the shared usage
*
* The threshold is set to the 2^n of available buffer of the pool.
*
* @type sai_int8_t
* @flags MANDATORY_ON_CREATE | CREATE_AND_SET
* @condition SAI_BUFFER_PROFILE_ATTR_THRESHOLD_MODE == SAI_BUFFER_PROFILE_THRESHOLD_MODE_DYNAMIC
*/
SAI_BUFFER_PROFILE_ATTR_SHARED_DYNAMIC_TH,
the value type is a sai_int8_t, support negative value
on centec goldengate chip platform, we support range [-7, 3],
but currnetly in swss, uint32 type value is used, have to fix it
build success
startup and init success
set a negative value to …

fix SAI_BUFFER_PROFILE_ATTR_SHARED_DYNAMIC_TH value type mismatch bug on 201803 branch

---

orchagent/portsorch.cpp
orchagent/portsorch.h

**What I did**
I've overwritten validatePortSpeed() method of PortsOrch class. Also I've rename it to more suitable `isSpeedSupported`.
Previously:
1. The method tried to get the speed list many times if this operation is not supported by platform
2. The method use two get operations to get the list, currently it should be one in the most cases.
3. The method returns false if:
1. internally it gets any error except NOT_SUPPORTED and NOT_IMPLEMENTED
2. the `speed` is not found in the list of speeds.
Now:
1. the number of SAI GET operations are minimized.
2. the function return false only if we get a list of speeds and the requested `speed` not in the list of successfully returned supported speeds. Otherwise it's always true.
Because this method slowed fast-reboot …

[portsorch]: Rewrite validatePortSpeed() method. Use true lazy approach

---

orchagent/Makefile.am
orchagent/flexcounterorch.cpp
orchagent/flexcounterorch.h
orchagent/orchdaemon.cpp
orchagent/orchdaemon.h
orchagent/portsorch.cpp
orchagent/portsorch.h

**What I did**
Add support to change port/queue counter poll interval
Tested on DUT.

[flexcounter]: add support to change port/queue counter poll interval

---

orchagent/portsorch.cpp

**What I did**
Remove no need counters from query
SAI_QUEUE_STAT_CURR_OCCUPANCY_BYTES and SAI_QUEUE_STAT_WATERMARK_BYTES are not needed.

[queuestat]: remove no need counters from query

---

cfgmgr/buffermgr.cpp
cfgmgr/buffermgr.h

**What I did**
Suppress the error messages like below
May 19 07:39:02.473125 sonic NOTICE buffermgrd: :- doSpeedUpdateTask: Unable to create/update PG profile for port Ethernet0. Cable length is not set
If we don't have pg_profile_lookup.ini file provided.
In some platform, pg_profile_lookup.ini is not provided and we don't need this buffer management feature. 
Today the code is repeating these messages:
May 19 07:39:02.473125 sonic NOTICE buffermgrd: :- doSpeedUpdateTask: Unable to create/update PG profile for port Ethernet0. Cable length is not set
May 19 07:39:02.473362 sonic NOTICE buffermgrd: :- doSpeedUpdateTask: Unable to create/update PG profile for port Ethernet1. Cable length is not set
May 19 07:39:02.473558 sonic NOTICE buffermgrd: :- doSpeedUpdateTask: Unable …

Suppress Cable length errors in case pg profile lookup file is not provided

---

tests/test_acl.py

**What I did**
Added a test case that checks that different subnet mask for dest/src ip addresses in ACL rules are programmed correctly in the ASICDB
Part of the ACL test cases propsed by Dell and approved by Microsoft
Ran the python test script in the repo
Output of test attatched
[subnet_test_logs.txt](https://github.com/Azure/sonic-swss/files/1930588/subnet_test_logs.txt)

[acl]: test different subnet masks

---

orchagent/bufferorch.cpp
orchagent/bufferorch.h
orchagent/orchdaemon.cpp
orchagent/portsorch.cpp
tests/test_port_buffer_rel.py

**What I did**
I created an extra logic to bring the ports UP only after the buffer configuration was applied. If there is no any buffer configuration on the device, orchagent brings the ports UP immediately. This change suppose all buffer configuration on the disk before SONiC starts orch agent.
As a side change I put changing MTU operation before changing MTU state operation.
It's possible to create a deadlock in ASIC pipeline when we change buffer configurations with ports which are active
Build and run on DUT. Ensure that /var/log/swss/sairedis.rec contains ADMIN_STATE = true attribute after BUFFER_PROFILE application to the ports.
The test is not comprehensive. vs docker already has buffer configuration, so it's impossible …

[portsorch]: Bring the physical ports up are only after buffer configuration was applied

---

tests/test_nhg.py

**What I did**
Minor fix to the link oper_status check.
jipan@sonic-build:~/igbpatch/vs/sonic-buildimage/src/sonic-swss/tests$ sudo pytest -v --dvsname=vs   test_nhg.py 
=========================================================================================== test session starts ============================================================================================
platform linux2 -- Python 2.7.12, pytest-3.3.0, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python
rootdir: /home/jipan/igbpatch/vs/sonic-buildimage/src/sonic-swss/tests, inifile:
collected 1 item …

VS: Check oper_status of the link being brought up instead of Ethernet0

---

orchagent/flexcounterorch.cpp

**What I did**
Add support to enable/disable counter query
Add the flexibility to enable or disable counter query.
Tested on DUT

[counter]: add support to enable/disable counter query

---

orchagent/fdborch.cpp

**What I did**
Fix a bug which could cause to free the same memory twice.
To fix a segmentation fault in case we got 'count' variable greater than 1.
Build and run on DUT.

[fdborch]: Fix 'double free' bug in fdb event handler

---

orchagent/flexcounterorch.cpp
orchagent/portsorch.cpp
orchagent/portsorch.h

**What I did**
I postponed generation of the QueueMaps until the counters are activated. 
We don't need QueueMaps until the counters are active
Build an image and run on DUT

Postpone QueueMap initialization until activation of the counters

---

orchagent/crmorch.cpp

Placeholder PR to migrate to SAI 1.3 headers

SAI 1.3 changes

---

orchagent/aclorch.cpp

if (stage == ACL_STAGE_UNKNOWN) return false;
This logic should be part of the AclTable validate() function
instead of in the create() function.

[aclorch]: Move ACL stage check to validate() function

---

orchagent/intfsorch.cpp
orchagent/orchdaemon.cpp

This also ensures all port setting applied before intf setting.
**What I did**
Don't apply intf setting on a port before buffer applied on the port.
The order of orches in  m_orchList guaranteed that for pending tasks, buffer is processed before port, port before intf.
There is racing condition that, even when "PortInitDone" has been received and m_initDone set  true,  buffer configuration hasn't been applied.  
https://github.com/Azure/sonic-swss/blob/dcf6c905410f08b004e880dbed56823d29e7bd5e/orchagent/portsorch.cpp#L1360
mtu setting for port will be postponed, while IntfsOrch::doTask() only checks gPortsOrch->isInitDone().  For router interface creation,  it uses default port mtu which may be different from the one …

Postpone intf task after buffer configuration applied on the port.

---

orchagent/portsorch.cpp

Refix https://github.com/Azure/sonic-swss/pull/503
The original fix has this code flow:
1. alias == "PortConfigDone"
2. getPort returns false and undefined port (p)
3. the undefined port is used

[portsorch]: Refix: Don't print error when alias equal to PortConfigDone

---

orchagent/orch.cpp
portsyncd/linksync.h
portsyncd/portsyncd.cpp
tests/test_port_an.py

The entries in APP_PORT_TABLE_NAME are sequence sensitive because there are event entries (PortConfigDone, PortInitDone). Change it back to ProducerTable.

Port table should be ProducerTable

---

orchagent/portsorch.cpp

Originally the function PortsOrch::initializePort() is only design for cold start. ie. the admin_status and oper_status attribute is missing or 'down'.
In warm reboot, we would like to initialize the port with leftover APP DB PORT_TABLE entries, which include the admin_status and oper_status attribute. So this PR will make it friendly to warm reboot scenario.

Fix initializePort: only set down status if attr missing

---

orchagent/aclorch.cpp

**What I did**
Only bind to port for ACL_TABLE_PFCWD type
PFCWD only requires to bind to port regardless if port is a LAG member. And LAG binding is not supported for egress acl table which will be used for PFCWD.

[aclorch]: only bind to port for ACL_TABLE_PFCWD type

---

orchagent/orch.cpp
portsyncd/linksync.h
portsyncd/portsyncd.cpp
tests/test_port_an.py

Revert "Port table should be ProducerTable"

---

orchagent/portsorch.cpp
orchagent/portsorch.h
tests/test_port.py

(Reduce the scope of this PR, please check the updated comment below)
I tested with virtual switch (vs) and Mellanox platform. The initial config of 'fec' is added in ```/usr/share/sonic/device/*/*/port_config.ini```. However this manual test is not materialized as a unit test because of some difficulty.
Original implementation of PortsOrch::doPortTask() has some issues:
1. ~~It was using a ConsumerStateTable, which makes the message coming out of order. The complex logic was used to handle the order. After replace ConsumerStateTable by ConsumerTable, we can simplify the logic.~~
2. The original ConsumerStateTable implementation will always pop all entry attributes even there is one attribute coming. This behavior is not by design and was changed after …

Improve PortsOrch::doPortTask()

---

doc/swss-schema.md

**What I did**
Basic schema for warm start 
Configuration:   Mainly to decide whether to flush the DB data and some timer setting for arp/route sync.
AppDB:   Store basic warm restore and sync up state and restart count for each process.

Warm reboot: Add basic schema for warm start in configDB and stateDB.

---

orchagent/orch.cpp
orchagent/orch.h
orchagent/portsorch.cpp
orchagent/portsorch.h

The non-warm reboot behavior is backward compatible, and tested in lab.
The idea is best effort warm reboot based on left over entries in PORT_TABLE.
1. During a cold reboot, the whole table is empty, so keep original behavior
2. During a warm reboot, the previous port entries are left in the table, together with event entries such as PortConfigDone, PortInitDone. So PortsOrch will add them into PortsOrch's consumer queue to propagate to downstream syncd and ASIC.
3. During a warm reboot, if any corruption found in the table, clean up the table and fallback to cold reboot.
The warm reboot is not end-to-end tested.

Warm reboot for PortsOrch

---

tests/test_tunnel.py

Signed-off-by: stepanb <stepanb@mellanox.com>
**What I did**
I added VS test for IPv4/IPv6 tunnel creation
There was no VS test for tunnel creation, so I added it
Run VS tests

Add test for IPv4/IPv6 tunnel creation

---

orchagent/orchdaemon.cpp

* add flush() after event is handled in case some entries are still in buffer, don't wait
* with the changes in sairedis and swss-common, route performance improved by 200~300 routes/sec
Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com
**What I did**

swss: flush g_asicState after each event is done

---

cfgmgr/intfmgr.cpp
cfgmgr/intfmgr.h
tests/test_interface.py

Enable configuring IPv4 and IPv6 addresses on regular ports
Add tests to test IPv4 add/remove to regular ports
NOTE:
1. LAG IP configuration test will be added later once the support of LAG creation/removal feature is added.
2. IPv6 tests will be added later once the docker vs supports IPv6 after some docker configuration changes.

[intfmgr]: Support configuring IPs for all regular interfaces

---

orchagent/intfsorch.cpp
orchagent/intfsorch.h
orchagent/orchdaemon.cpp
orchagent/port.h
orchagent/portsorch.cpp
tests/test_interface.py

This function allows the propagation of MTU from port MTU to router
interface MTU if the router interface is created based on this port.
Once the port MTU gets changes, the router interface MTU will also
get changed.

[intfsorch]: Add setRouterIntfsMtu function

---

cfgmgr/Makefile.am
cfgmgr/portmgr.cpp
cfgmgr/portmgr.h
cfgmgr/portmgrd.cpp
portsyncd/linksync.cpp
portsyncd/portsyncd.cpp
tests/test_port.py

In order to get rid of /etc/network/interfaces file and move
all the configurations to the configuration database, MTU configurations
are required to be put into the database and monitored by a specific
daemon. This daemon is right now to achieve this goal.
Currently, this daemon will only listen to the port MTU configurations
if existed in the database and then call the 'ip link' command to
configure the kernel netdevs. Then, portsyncd will catch the messages
via libnl and send the message to orchagent.

[portmgrd]: Add portmgrd to monitor port MTU configurations

---

tests/test_interface.py

With the recent pull requests, if the router interface is created
without specifying the MTU in the configuration database, the
default MTU would be 9100 instead of 1500.
Note:
9100 comes from the orchagent/port.h; 1500 comes from the kernel.

[test]: Change the default router interface MTU to 9100

---

orchagent/qosorch.cpp
orchagent/qosorch.h

Expose the capability to config wred drop probability of all packet colors (green, yellow, and red)
Signed-off-by: Wenda <wenni@microsoft.com>
**What I did**
Tested on dut 3 cases:
1) drop probabilities all specified in qos.json
2) drop probabilities partly specified in qos.json
3) no drop probabilities specified in qos.json

Expose the capability to config wred drop probability

---

orchagent/orch.cpp
orchagent/orch.h
orchagent/qosorch.cpp

The approach is to use "[]" as a CLI signal to unbind wred profile from a queue or a list of queues; Add the parsing and processing logic in qosorch to support such an operation. 
With the correct SAI support, we can see asic_db is correctly set to "SAI_QUEUE_ATTR_WRED_PROFILE_ID":"oid:0x0"
"ASIC_STATE:SAI_OBJECT_TYPE_QUEUE:oid:0x15000000000285":{"type":"hash","value":
{"SAI_QUEUE_ATTR_BUFFER_PROFILE_ID":"oid:0x190000000005d6","SAI_QUEUE_ATTR_WRED_PROFILE_ID":"oid:0x0","NULL":"NULL","SAI_QUEUE_ATTR_TYPE":"SAI_QUEUE_TYPE_UNICAST"}}
**What I did**
Tested on dut

Support ecn on/off on a queue

---

tests/README.md
tests/conftest.py
tests/test_warm_reboot.py

start from docker 3.0.0, results from exec_run changed to
dict(outout, code)
**What I did**
allow test to use latest python docker 3.5.0
to use latest python docker 3.5.0
run test with both docker 3.5.0 and 2.6.1

support to use python docker 3.5.0

---

tests/conftest.py

- cleanup testbed during init failure
- turn off nic tx offloading
- add runcmd_async
- add copy_file
- enable ipv6
**What I did**
- cleanup testbed during init failure
- turn off nic tx offloading
- add runcmd_async
- add copy_file
- enable ipv6

various improvements of testbed setup

---

doc/swss-schema.md
orchagent/tunneldecaporch.cpp
orchagent/tunneldecaporch.h
tests/test_tunnel.py

**What I did**
- Allow decap tunnel configuration without "src_ip" field
- Remove overlay interface when removing tunnel
- Add test cases to test_tunnel.py to check the above two changes
- Couldn't create a decap tunnel without "src_ip" field, also there is no need to specify "src_ip" for decap only tunnel
- After tunnel deletion, created overlay interface still exists, so I fixed that
- Mannual testing on SONiC switch: created tunnel without "src_ip", deleted tunnel and verified overlay interface is also deleted
- Run unittests
When trying to create tunnel without "src_ip":
```json
[
{
"TUNNEL_DECAP_TABLE:IPINIP_V4_TUNNEL" : {
"tunnel_type":"IPINIP",
"dst_ip":"1.1.1.1",
"dscp_mode":"uniform",
"ecn_mode":"standard", …
```

Tunneldecaporch fixes

---

tests/test_vlan.py

[test]: Add test_MultipleVlan test to test creation/removal
Refactored test_vlan.py so that each test is independent from
each other and intermediate state will be cleaned up afterwards.
Add test_MultipleVlan test to cover scenarios with VLAN and
VLAN members change. This test would fail on earlier kernel version
.e.g 3.16.0-4 when the bridge interface cannot remain UP all
the time. This would cause new VLAN failed to be created later on.
The current Debian stretch doesn't have this issue and the test
shall pass with current implementation.

[test]: Add test_MultipleVlan test to test creation/removal

---

orchagent/bufferorch.cpp
orchagent/bufferorch.h
orchagent/orch.h
orchagent/orchdaemon.cpp
orchagent/orchdaemon.h

Tested in VS:
1. cold start
2. change config DB
```
127.0.0.1:6379[4]> hset WARM_RESTART|swss enable true
```
3. restart orchagent process only
4. observe syslog about "There are pending consumer tasks after restore". There will be no buffer related tasks.

Tune consumer order in BufferOrch::doTask() based on dependency for warm start

---

orchagent/neighorch.cpp

The router interface creation may be delayed, so neighorch should leave task in m_toSync instead of erasing. Tested in both cold start and warm start.

Fix bug: NeighOrch waits for router interface ready

---

orchagent/fdborch.cpp
orchagent/intfsorch.cpp
orchagent/intfsorch.h
orchagent/mirrororch.cpp
orchagent/mirrororch.h
orchagent/neighorch.cpp
orchagent/routeorch.cpp
orchagent/routeorch.h
tests/test_mirror.py

- Add FdbUpdate notification when manually inserting/removing FDB
entries
- Refactor MirrorOrch so that it supports:
1. create mirror session pointing to VLAN
2. destination port move to VLAN/non-VALN
3. destination port move to LAG
Remove unnecessary variables in MirrorEntry
- Add destination IP to the NextHopUpdate message
- Add subnset routes for route observers

[mirrororch]: Enable mirror session destination to point into VLAN

---

orchagent/aclorch.cpp
orchagent/mirrororch.cpp
orchagent/mirrororch.h
orchagent/orchdaemon.cpp
tests/conftest.py
tests/test_mirror.py

The old implementation store only session status in a plain Table in ApplDB, which is not correct databese.
1. Store mirror session state in StateDB
2. Store many session fields besides status

 Store mirror session state in StateDB

---

orchagent/aclorch.cpp

Fail to find a match criteria is a completely valid flow (orchagent/aclorch.cpp:L2076-L2093)
This caused ACL test failure in loganalysis phase.
**What I did**

[aclorch] Remove error message when match not found

---

orchagent/port.h
orchagent/portsorch.cpp

ifindex is never used by orchagent and orchagent shall be
ignorant to this value.

[portsorch]: Remove m_ifindex from Port class

---

.gitignore
cfgmgr/Makefile.am
cfgmgr/vrfmgr.cpp
cfgmgr/vrfmgr.h
cfgmgr/vrfmgrd.cpp

vrfmgrd is responsible for VRF configuration in Linux
It creates VRF-Lite device for every VRF entry in Config DB

[cfgmgr]: Add vrfmgrd

---

cfgmgr/vlanmgrd.cpp
doc/swss-schema.md
orchagent/main.cpp
orchagent/orchdaemon.cpp
portsyncd/portsyncd.cpp
tests/test_warm_reboot.py
warmrestart/warmRestartAssist.cpp
warmrestart/warm_restart.cpp
warmrestart/warm_restart.h

The current WarmStart class assumes that restarting applications will invoke checkWarmStart() method during initialization. Currently, this method serves two main purposes: 1) a static-constructor and 2) checks if WarmRestart feature has been enabled for a given application.
In this PR i'm proposing to split these different logics in two separated methods. The main goal here is to allow applications such as fpmSyncd to call checkWarmStart whenever it please (i.e. fpmSyncd restart event or zebra<->fpmSyncd tcp re-establishment). There could be other applications in the future interested in this differentiated approach.
Other than that i'm making small adjustments in the code to enhance readibility.
Signed-off-by: Rodny Molina <rmolina@linkedin.com>

WarmRestart class changes

---

tests/test_warm_reboot.py

**What I did**
Switch to "config warm_restart" CLI for warm restart configuration from operating on configDB directly.

Switch to "config warm_restart" CLI for warm restart configuration

---

portsyncd/Makefile.am
portsyncd/linksync.cpp
portsyncd/linksync.h

portsyncd listens to the netlink messages. In order for SNMP
to get the current oper status of the managemnt interface,
portsyncd will store eth0 oper status explicitly into the
state database.

[portsyncd]: Store eth0 oper status into state DB

---

cfgmgr/intfmgr.cpp
cfgmgr/intfmgr.h
orchagent/orch.h

**What I did**
Add interface IP config state to StateDB.
To be used by arp refresh during warm reboot, and other possible scenarios.
Add IP address 20.20.20.20/24 and check state
```
root@sonic:/home/admin# config  interface Vlan10  ip add 20.20.20.20/24 
root@sonic:/home/admin# 
root@sonic:/home/admin# 
root@sonic:/home/admin# ip add show Vlan10
6: Vlan10@Bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
link/ether 00:05:64:30:73:c0 brd ff:ff:ff:ff:ff:ff
inet 11.163.117.119/26 scope global Vlan10
valid_lft forever preferred_lft forever
inet 11.213.14.247/26 scope global Vlan10
valid_lft forever preferred_lft forever
inet 20.20.20.20/24 scope global …
```

Add Intf config state to StateDB

---

orchagent/dtelorch.cpp
orchagent/mirrororch.cpp
orchagent/portsorch.cpp
tests/conftest.py
tests/test_acl.py
tests/test_crm.py
tests/test_dirbcast.py
tests/test_dtel.py
tests/test_fdb_cold.py
tests/test_fdb_warm.py
tests/test_interface.py
tests/test_mirror.py
tests/test_nhg.py
tests/test_pfc.py
tests/test_port.py
tests/test_port_an.py
tests/test_port_buffer_rel.py
tests/test_portchannel.py
tests/test_route.py
tests/test_setro.py
tests/test_speed.py
tests/test_tunnel.py
tests/test_vlan.py
tests/test_vrf.py
tests/test_vxlan_tunnel.py
tests/test_warm_reboot.py

When the destination port type is not VLAN related, there
is no need to update the session type.

[mirrororch]: Fix bug when no need to update session type

---

tests/conftest.py

**What I did**
run test with ```--dvsname``` option
```
lgh@gulv-vm1:/data/sonic/sonic-swss/tests$ sudo pytest -v test_crm.py::test_CrmFdbEntry --dvsname=vs
========================================================= test session starts =========================================================
platform linux2 -- Python 2.7.12, pytest-3.3.1, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python
rootdir: /data/sonic/sonic-swss/tests, inifile:
collected 1 item                                                                                                                      
test_crm.py::test_CrmFdbEntry PASSED …
```

[vstest]: fix redis mount point with --dvsname option

---

teamsyncd/teamsync.cpp
teamsyncd/teamsync.h
teamsyncd/teamsyncd.cpp

In the current implementation, the selectable is removed inside the
select() function. However, the select function will retrieve multiple
file descriptors at one time. If the file descriptor is removed, it
will cause segmentation fault.

[teamsyncd]: Fix bug when removing selectable in select function

---

tests/test_portchannel.py

After the creation of the LAG and the LAG member, clean
the application database and verify that the LAG and member
are removed from the ASIC database.

[test]: Clean up LAGs after finishing the test

---

cfgmgr/vlanmgr.cpp

VLAN members' admin status and MTU are controlled by portmdrd.
vlanmgrd shall not bring up and set MTU automatically by default.

[vlanmgrd]: Do not bring up VLAN members by default

---

orchagent/orchdaemon.cpp

**What I did**
Fix issue of "pending consumer tasks exist after restore even when the data is consistent"
Three iterations of `o->doTask();` are needed for orchagent state restore.

Orchagent warm restart data restore requires three iterations

---

cfgmgr/portmgr.cpp
tests/test_admin_status.py

When a port is enslaved into the portchannel, portmgrd shall still
be able to bring the port admin up/down according to the configuration
changes.

[portmgrd]: portmgrd shall be responsible for all ports update

---

tests/conftest.py

**What I did**
print output when runcmd returns error
make it easier to debug issue
sample output when test goes wrong.
```
-------------------------------------------------------- Captured stdout call ---------------------------------------------------------
------rc=2 for cmd: ip netns exec suspicious_noyce-srv16 ip route add default via 6.6.6.1------
RTNETLINK answers: File exists
------
------rc=2 for cmd: ip netns exec suspicious_noyce-srv17 ip route add default via 6.6.6.1------
RTNETLINK answers: File exists
------
-----rc=1 for cmd config warm_restart enable swss-----
Traceback (most recent call last):
File "/usr/bin/config", line 9, in <module>
load_entry_point('sonic-utilities==1.2', …
```

[vstest]: print output when runcmd returns error

---

cfgmgr/intfmgr.cpp
tests/test_interface.py

Add one IPv6 address to a port based router interface
and check the router interface is created and the corresponding
routes are also created.

[test]: Add interface IPv6 add/remove test case

---

orchagent/intfsorch.cpp

**What I did**
Add check to see if lo interface already processed. If yes, skip addIp2MeRoute() for it.
It is possible lo interface request comes again,  or comes after warm restore in case of warm reboot.

Don't add loopback ip2me route again if already configured

---

fpmsyncd/Makefile.am
fpmsyncd/fpmlink.cpp
fpmsyncd/fpmsyncd.cpp
fpmsyncd/routesync.cpp
fpmsyncd/routesync.h
tests/conftest.py
tests/test_warm_reboot.py
warmrestart/warmRestartHelper.cpp
warmrestart/warmRestartHelper.h

[ dependencies with PR/600: https://github.com/Azure/sonic-swss/pull/600 ]
Please refer to the corresponding design document for more details: https://github.com/Azure/SONiC/pull/239
The following manual UT plan has been successfully executed. UT automation pending.
Physical topology formed by various BGP peers connecting to the DUT. Both non-ecmp and ecmp prefixes are learned/tested.
```
Testcase Suite 1: Making use of “pkill -9 bgpd && pkill -9 zebra” as trigger.
=============
IPv4 prefixes
==========
* Restart zebra/bgpd:
- Verify that all prefixes are properly stale-marked and that no
change is pushed to AppDB during reconciliation.
- Result: PASSED
* Restart zebra/bgpd and add one new non-ecmp IPv4 prefix.
- To produce a route-state-inconsistency, add prefix in adjacent
node before …
```

Routing-stack warm-reboot feature.

---

debian/swss.install
doc/swss-schema.md
neighsyncd/neighsync.cpp
neighsyncd/neighsync.h
neighsyncd/neighsyncd.cpp
neighsyncd/restore_neighbors.py
tests/conftest.py
tests/test_warm_reboot.py

Support neighsyncd system warmreboot.
neighsyncd will waits for kernel restore process to be done
before reconciliation
Add vs testcases to cover kernel neighbor table restore process
and neignsyncd process upon system warm reboot
**What I did**
Support neighsyncd system warmreboot.
neighsyncd will waits for kernel restore process to be done
before reconciliation
Add vs testcases to cover kernel neighbor table restore process
and neignsyncd process upon system warm reboot
Support system warm reboot
vs test cases and on box manual tests
This is dependent on below PRs:
https://github.com/Azure/sonic-buildimage/pull/2213
https://github.com/Azure/sonic-swss-common/pull/243 …

Support neighsyncd system warmreboot.

---

cfgmgr/teammgr.cpp

[teammgrd]: Check if port is enslaved on all conditions
During the warm restart, port is already enslaved in the kernel.
This change is to avoid teammgrd to re-configure those member
ports which causes link flap.

[teammgrd]: Check if port is enslaved on all conditions

---

tests/test_interface.py

The test is already using teammgrd and configuration database
to configure the port channels.

[test]: Remove deprecated TODO comment

---

cfgmgr/vlanmgrd.cpp
orchagent/main.cpp
portsyncd/portsyncd.cpp
tests/test_warm_reboot.py

The default docker name caused a lot of confusion when the libraries used in other dockers
**What I did**
Adapt to the change with WarmStart library,  default docker name of swss has been removed.
The default docker name caused a lot of confusion when the libraries used in other dockers
VS test.

Remove default docker name value of swss.

---

orchagent/aclorch.cpp

Because AclOrch listens to all notifications from PortsOrch,
every time LAG member changes the change message will be sent to
AclOrch which is unncessary. This warning message is not wanted.

[aclorch]: Remove unnecessary warning message

---

tests/conftest.py
tests/test_acl_portchannel.py
tests/test_admin_status.py
tests/test_speed.py

align with vs kvm image physical interface name ethXX instead of vEthernetXXX
**What I did**
use eth1~32 as physical interface name in vs docker
align with the physical interface name in vs kvm
run all vstest. depends on kamil's fix in sonic-sairedis repo.
```
lgh@gulv-vm1:/data/sonic/sonic-swss/tests$ sudo pytest -v --dvsname musing_leakey                     
========================================================= test session starts =========================================================
platform linux2 -- Python 2.7.12, pytest-3.3.1, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python
rootdir: /data/sonic/sonic-swss/tests, inifile:
collected 80 items …
```

[vstest]: use eth1~32 as physical interface name in vs docker

---

orchagent/port.h
tests/test_interface.py
tests/test_vnet.py

**What I did**
Set default MTU in orchagent to SAI default value (`1514`)
To fix issue https://github.com/Azure/sonic-buildimage/issues/2293
_**Before fix:**_
```
admin@str-a7060cx-acs-1:~$ show interfaces status 
Interface            Lanes    Speed    MTU         Alias    Oper    Admin
-----------  ---------------  -------  -----  ------------  ------  -------
Ethernet0            33,34      50G   9100   Ethernet1/1      up       up
admin@str-a7060cx-acs-1:~$ bcmcmd 'ps'
xe12( 34)  up     2   50G  FD   SW  No   Forward  TX RX   None   FA    KR2  **9412**    No 
```
**_After fix:_**
```
admin@str-a7060cx-acs-1:~$ bcmcmd 'ps xe12'
ena/        speed/ link auto    STP                  lrn  inter   max   cut   loop
port  link  Lns   duplex scan neg? …
```

Align default MTU value as SAI default

---

orchagent/switchorch.cpp
tests/test_switch.py

**What I did**
Add vxlan port and router mac to switch profile
Require for Vxlan use-case
VS test. 
```
127.0.0.1:6379> HGETALL "SWITCH_TABLE:switch"
1) "vxlan_port"
2) "12345"
3) "vxlan_router_mac"
4) "00:01:02:03:04:05"
```

Add vxlan attributes to switch profile

---

orchagent/aclorch.cpp
orchagent/aclorch.h
tests/test_acl_ctrl.py

To prevent control plane ACL rules from being stored in the pending
task set, store the control plane ACL table in orchagent first and
check if the ACL rule is associated with control plane ACL table and
ignore it.
The next step is to combine the data structure of control plane ACL
tables and data plane ACL tables to make the code more efficient.

[aclorch]: Store control plane ACL tables in orchagent

---

orchagent/pfc_detect_mellanox.lua

**What I did**
Fixed race condition between lua script and orchagent which sometimes caused double storm detection
Stricter usage of *_last counters used in script to detect storm
PFC_WD test case for _last counters should pass

[Mellanox] Fix lua/orchagent storm detection race

---

orchagent/neighorch.cpp
orchagent/port.h
orchagent/portsorch.cpp
orchagent/portsorch.h

**What I did**
- Change 'p' varaible name to 'port'
- Pass 'Port' struct object to set/update methods instead of SAI OID to avoid
unncessary 'for' loops that search port object in m_portList
- make setHostIntfsOperStatus/updateDbPortOperStatus methods const
- minor simple changes
This PR was derivied from https://github.com/Azure/sonic-swss/pull/704.
I will create another PR with fix for Mellanox fastfast boot feature
Installed swss deb package on switch & verify it is working good

[portsorch] Portsorch simple improvements

---

neighsyncd/restore_neighbors.py
tests/test_warm_reboot.py

During the neigh restore process, we set neighbor entries to stale
instead of reachable to kernel. The subsuquent arp/ns packets will bring the
active neighbors to reachable. And stale entries will be expired after
stale timer (default 60 seconds) or kernel will probe and delete the stale
entires if garbage collection is activated at any point.
**What I did**
Optimize the neighbor restore process during the warm-reboot
This is to avoid the stale entries to stay in kernel/SONiC for unnecessarily too long.
vs tests

Optimize neigh restore process during warm-reboot

---

orchagent/crmorch.cpp
orchagent/crmorch.h

Fix https://github.com/Azure/sonic-buildimage/issues/1991

Fix: crash while destructing crmorch

---

orchagent/neighorch.cpp

**What I did**
Return back original condition for port operational status when adding a next hop.
port::m_oper_status is by default SAI_PORT_OPER_STATUS_UNKNOWN.
If port is LAG or VLAN m_oper_status is not overridden with value in state DB, so
(p.m_oper_status != SAI_PORT_OPER_STATUS_UP) is true and next hop flag IFDOWN is set.
This is workaround, need to listen to state db to update oper status in port struct
Built and verified that next hops are added to ecmp group

[neighorch] return back original condition for port oper status

---

cfgmgr/intfmgr.cpp
cfgmgr/intfmgrd.cpp
tests/test_interface.py

In #635, the intfmgrd does not read loopback address from config db at all and then it does not configure the loopback address in the asic. The PR fix the issue by reading from the config db. Since loopback address is configured via /etc/network/interface so it is skipped in intfmgrd. 

[intfmgrd]: Support loopback

---

cfgmgr/intfmgr.cpp

intfmgrd can hang on first interface it tries to configure untill this
interface becomes "ready". This delays other interfaces configuration to
be processed.
This commit fixes this issue by skiping "not ready" interface and
proceed with others. Skipped interface can be processed on next
iterations.
**What I did**
Skip interface when it is not ready. Interface will be processed on next iterations.
This is to nail the issue described in https://github.com/Azure/sonic-swss/pull/744
What I see from intfmgrd:
```
Jan 11 12:44:17.861611 mts-sonic-dut DEBUG swss#intfmgrd: :> doIntfAddrTask: enter
Jan 11 12:44:17.861830 mts-sonic-dut DEBUG swss#intfmgrd: :- doIntfAddrTask: Interface is not ready, skipping PortChannel0001
Jan …
```

[intfmgrd] Fix intfmgrd hanging untill first interface becomes ready

---

orchagent/portsorch.cpp

setHostIntfsOperStatus accepts bool instead of sai_oper_status_t
While trying to investigate issue described in #744 I tried to find a diff in behaviour that #718 brought to fast/warm reboot and noticed a bug.
**What I did**

[portsorch] fix bug in initializePort

---

cfgmgr/teammgr.cpp
cfgmgr/teammgr.h

teamd command may fail when failed to allocate memory to create the port
channel. Retry logic make sure the creation will be successful.

[teammgrd]: Add retry logic for starting port channel with teamd

---

orchagent/aclorch.cpp
orchagent/aclorch.h

Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>
**What I did**
Fixed ACL IP type parser logic
Because of SAI headers documentation:
/** Ip Type [sai_acl_ip_type_t] (field mask is not needed) */
SAI_ACL_ENTRY_ATTR_FIELD_IP_TYPE
* N/A
* N/A

Fixed ACL IP type parser

---

orchagent/aclorch.cpp
orchagent/aclorch.h

Reverts Azure/sonic-swss#715
This is breaking the VS test for IP_TYPE since it removed the mask field. For "ACL_FIELD_DATA_INT32" (s32) type, sai redis expects a mask. @nazariig, please work with @kcudnik to resolve this
VS Test logs:
```
elif fv[0] == "SAI_ACL_ENTRY_ATTR_FIELD_ACL_IP_TYPE":
>               assert fv[1] == "SAI_ACL_IP_TYPE_IPV6ANY&mask:0xffffffffffffffff"
E               AssertionError: assert 'SAI_ACL_IP_T...fffff96d47560' == 'SAI_ACL_IP_TY...fffffffffffff'
E                 - SAI_ACL_IP_TYPE_IPV6ANY&mask:0xffffffff96d47560
E                 ?                                        ^^^^^^^^
E                 + SAI_ACL_IP_TYPE_IPV6ANY&mask:0xffffffffffffffff
E                 ?                                        ^^^^^^^^
test_acl.py:373: AssertionError
```

Revert "Fixed ACL IP type parser"

---

portsyncd/portsyncd.cpp

**What I did**
Implemented #2 from [this comment](https://github.com/Azure/sonic-buildimage/issues/2047#issuecomment-423681870) to the issue
Fixes issue with the custom port split reset after SONiC-to-SONiC update
Executed SONiC-to-SONiC update on one of setups where we use custom port split. Verified split survived.

If available, read port settings from Config DB first

---

orchagent/watermarkorch.cpp

**What I did**
Fix the m_pg_ids, m_unicast_queue_ids and m_multicast_queue_ids init logic error.
The problem exhausts  system cpu and memory eventually in case multicast queue does not exist. 
size of m_pg_ids: 873152
```
(gdb) bt
#0  0x00007f3e9345ca9d in read () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f3e928f946e in read (__nbytes=16384, __buf=0x7ffca1347990, __fd=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/unistd.h:44
#2  redisBufferRead (c=0x21eace0) at hiredis.c:802
#3  0x00007f3e928f9760 in redisGetReply (c=0x21eace0, reply=0x7ffca134ba98) at hiredis.c:888
#4  0x00007f3e92f951c1 in pop (this=0x21eaa10) at ../common/redispipeline.h:74
#5  flush (this=<optimized out>) at …
```

[watermarkorch] Fix repeated m_pg_ids and m_unicast_queue_ids add up issue

---

cfgmgr/vrfmgr.cpp

vrfmgrd always set VNET_TABLE in APP_DB whatever the table name is. It should use CFG_VRF_TABLE_NAME instead of APP_VRF_TABLE_NAME to judge which table(Vrf or VNET) to be operated.
Signed-off-by: yorke <yorke.yuan@asterfusion.com>
**What I did**
Fix bug: vrfmgrd does not read VRF configuration from CONFIG_DB correctly and then it does not add/remove VRF_TABLE in APP_DB.    
vrfmgrd always set VNET_TABLE in APP_DB whatever the table name is. It should use CFG_VRF_TABLE_NAME instead of APP_VRF_TABLE_NAME to judge which table(Vrf or VNET) to be operated.
Add vrf configuration into CONFIG_DB and then can find correct VRF_TABLE in APP_DB. 
Test configuration likes:
"VRF": {
"VRF-red":{}
}
Then check the result:
redis-dump -d 0 -k "VRF*" …

[vrfmgrd] Fix VRF is not set to VRF_TABLE in APP_DB correctly

---

orchagent/intfsorch.cpp
orchagent/intfsorch.h

**What I did**
Don't add broadcast ip specific neighbor entry for the /31 subnet routing vlan.
In intfsorch code, it is creating neighbor entry for net directed broadcast address for a Routing VLAN when the routing VLAN interface is created. 
In case of /31 subnets there is no broadcast IP as (last 32nd bit) .0 and .1 corresponding to the only 2 hosts in the subnet. When adding neighbor entry for the .1 host, it is conflicting with the neighbor entry created for the directed broadcast IP and hence it throws the below error. As a result the .1 neighbor entry is not added to the hardware. 
Dec 8 19:15:55.732017 sonic ERR swss#orchagent: :- meta_sai_validate_neighbor_entry: object key SAI_OBJECT_TYPE_NEIGHBOR_ENTRY:{"ip":"12.12.1.1","rif":"oid:0x6000000000606","switch_id":"oi …

On a routing vlan, the neighbor entry in the /31 subnet is not added to hardware

---

cfgmgr/portmgr.cpp
cfgmgr/portmgr.h
cfgmgr/teammgr.cpp

**What I did**
This is try to address:  https://github.com/Azure/sonic-swss/issues/754
After the fix, port admin status back to normal:
```
US-70998M:sonic-telemetry jipanyang$ ssh root@30.57.185.38
Linux sonic 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2015-12-19) x86_64
You are on
____   ___  _   _ _  ____
/ ___| / _ \| \ | (_)/ ___|
\___ \| | | |  \| | | |
___) | |_| | |\  | | |___
|____/ \___/|_| \_|_|\____|
-- Software for Open Networking in the Cloud --
Unauthorized access and/or use are prohibited.
All access and/or use are subject to monitoring.
Help:    http://azure.github.io/SONiC/
root@sonic:~# show interfaces  description 
Interface    Oper    Admin         Alias    Description …
```

[teammgrd] Fix inconsistent port admin status

---

tests/test_port_an_warm.py

the test should set the speed and autoneg in config db instead
of application db. As if the speed in config db is not changed,
it will override the value in app db after warm reboot
**What I did**

[vstest]: fix test_port_an_warm.py test

---

neighsyncd/neighsync.h
neighsyncd/restore_neighbors.py

**What I did**
Neighbor syncd is restoring important information for teamd and BGP. therefore, our timeout should not be shorter than the down stream service.
If some interface becomes ready too slow, restore_neighbors script will timeout and leave some neighbors not restored. That will cause sonic to relearn these neighbors and re-create these neighbor entries. And thus that cause data plane disruption.
Without the change, when vlan interface becomes ready 20 seconds later, data plane disruption is noticed by test. With the change, there is no data plane disruption.

[neighsyncd] increase neighbor syncd restore timeout to 110 seconds

---

tests/test_warm_reboot.py

Goal with this one is to reactivate the unit-tests written as part of the routing warm-reboot effort. There seems to be a timing issue behind the sporadic failure seen during the execution of Testcase-15. I'm adjusting the restart_timer value that i'm using in these testcases to see if that fixes the issue. Notice that i'm unable to reproduce this problem in my testbed, so i'm hoping to be able to run various jenkin's testing-cycles before merging this PR.

Potential fix for timing issue in warm_reboot's routing UT

---

fpmsyncd/routesync.cpp
fpmsyncd/routesync.h

fpmsyncd: Handle VNET routes
* Identify VNET routes based on routing table ID
* Parse VNET routes according to [Vxlan SONiC design document](https://github.com/Azure/SONiC/blob/master/doc/vxlan/Vxlan_hld.md)
Pending items: 
* Parse [VRF routes](https://github.com/Azure/SONiC/blob/master/doc/sonic-vrf-hld-v0.4.md).  
* Identify VXLAN routes using a more general approach 
* Support warm reboot for VNET and VRF routes
Signed-off-by: Wei Bai baiwei0427@gmail.com

[fpmsyncd] Add VNET routes support

---

orchagent/pfcwdorch.cpp
orchagent/portsorch.cpp
orchagent/portsorch.h

Signed-off-by: Wenda <wenni@microsoft.com>
**What I did**
On the PFCWD stats list installment, create egress ACL table group for each port and bind to it.
In pfc watchdog warm-reboot, we find that brcm sai not supporting ACL table group port unbind yet. If pfc storm ever occurred on a port, egress ACL table group will be created and bound to the port, and persist the association with the port even after the storm is restored. In the situation that there is restored but not ongoing pfc storm before warm-reboot, egress table group will not be created in view after warm-reboot. Syncd comparison logic will see the difference, and remove the egress ACL table group object from the port, the underlying unbind operation of which is not supported in brcm sai yet.
We use the …

Create egress ACL table group during the PFCWD stats list installment

---

orchagent/port.h
orchagent/portsorch.cpp
orchagent/portsorch.h

**What I did**
When port is already down during speed configuration don't put port down again.
Cache admin status in Port structure, do not set admin port status again if already set.
Avoid unnessesary SAI calls. It also had implications on Mellanox fastfast boot solution causing port flapping.
Currently VS fails (Check https://github.com/Azure/sonic-sairedis/pull/419)
Verified it is passing all VS tests.
Mannual testing.

[portsorch] Don't flap port when setting speed if port is down

---

orchagent/flexcounterorch.cpp
orchagent/intfsorch.cpp
orchagent/intfsorch.h

**What I did**
- add RIF counter flex group
- add logic to register RIF objects in Flex Counter

[intfsorch] add RIF flex counter group

---

orchagent/aclorch.cpp

**What I did**
CRM counter got incremented for stage `egress `when there is a mirror session. With the mirror session removed, the CRM counter was decremented for stage `ingress`. 
Orchagent could crash if the used and available counters add up to `zero `(divide/zero) error. 
Tested with the fix and checked for values

Incorrect ACL stage CRM increment with Mirror

---

orchagent/vnetorch.cpp
orchagent/vnetorch.h

**What I did**
Added support of local routes for Bitmap VNET implementation.
Implemented new logic for Bitmap VNET implementation in order to add support of local routes.
1. Verified manually by configuring VNETs and local routes (for Bitmap VNET) and checking that traffic is going between two VNETs.
2. Ran ```vnet_vxlan``` ansible test and verified that third test case, which tests local routes, passed.
N/A

[vnetorch]: Add support of local routes for Bitmap VNET implementation

---

orchagent/vnetorch.cpp

**What I did**
Added support of nexthop routes for Bitmap VNET implementation.
Implemented new logic for Bitmap VNET implementation in order to add support of nexthop routes.
1. Verified manually by configuring VNETs and nexthop routes (for Bitmap VNET) and checking that traffic is going as expected.
2. Ran `vnet_vxlan` ansible test and verified that it passed.
N/A

[vnetorch]: Add support of nexthop routes for Bitmap VNET implementation

---

orchagent/portsorch.cpp

**What I did**
After comments handling in https://github.com/Azure/sonic-swss/pull/764 this bug was introduced.
```m_portList[alias]``` will be overridden with ```p```, however ```p``` has no updated speed

[portsorch] fix bug in speed set

---

orchagent/portsorch.cpp

**What I did**
Fix uninitialized value access
To fix following error:
Feb 25 22:34:17.837004 switch120 NOTICE swss#orchagent: :- bake: Add warm input: BUFFER_PROFILE, 3
Feb 25 22:34:17.837092 switch120 NOTICE swss#orchagent: :- bake: Add warm input: BUFFER_QUEUE, 3
Feb 25 22:34:17.837687 switch120 ERR swss#orchagent: :- main: Failed due to exception: stoul
Feb 25 22:34:17.841919 switch120 INFO kernel: [   35.606307] traps: orchagent[3721] general protection ip:49c16c sp:7ffde2755580 error:0
Feb 25 22:34:17.841922 switch120 WARNING kernel: [   35.606312]  in orchagent[400000+151000]
Feb 25 22:34:18.844587 switch120 INFO swss.sh[2027]: 2019-02-25 22:34:18,843 INFO success: buffermgrd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
**How I …

[orchagent] Fix orchagent SEGV when PortConfigDone not set

---

orchagent/portsorch.cpp

Signed-off-by: yorke <yorke.yuan@asterfusion.com>
**What I did**
Fix inconsistent return value in PortsOrch::bindAclTable.
The type of return value for PortsOrch::bindAclTable is bool, but type sai_status_t is returned in PortsOrch::bindAclTable. Once it is failed on binding acl group to port by set_port_attribute, the return value would be true as non-SAI_STATUS_SUCCESS.

[portsorch] Fix inconsistent return value in bindAclTable

---

tests/conftest.py
tests/test_fdb_cold.py
tests/test_fdb_warm.py

**What I did**
fix occasional test_fdb_notifications vs test failure
We had configurations like below
Though no IP configured on vlan 7, layer 2 FDB entries may be created  depending on the timing.
The FDB entry number validation may fail with (assert counter_inserted - counter_before == 4).
Here we explicitly configure IP on all three VLANs, and run ping on the interfaces to trigger creation of the 6 FDB entries.

[VS]: fix occasional test_fdb_notifications vs test failure

---

orchagent/vnetorch.cpp
orchagent/vxlanorch.cpp

```
vxlanorch.cpp: In function 'sai_object_id_t create_tunnel_map(MAP_T)':
/usr/include/swss/logger.h:15:143: error: format '%d' expects argument of type 'int', but argument 5 has type 'MAP_T' [-Werror=format=]
#define SWSS_LOG_ERROR(MSG, ...)       swss::Logger::getInstance().write(swss::Logger::SWSS_ERROR,  ":- %s: " MSG, __FUNCTION__, ##__VA_ARGS__)
^
vxlanorch.cpp:85:9: note: in expansion of macro 'SWSS_LOG_ERROR'
SWSS_LOG_ERROR("Invalid map type %d", map_t);
^~~~~~~~~~~~~~
vnetorch.cpp: In member function 'bool VNetVrfObject::createObj(std::vector<_sai_attribute_t>&)':
/usr/include/swss/logger.h:19:143: error: format '%d' expects argument of type 'int', but argument 5 has type 'VR_TYPE' [-Werror=format=]
#define SWSS_LOG_DEBUG(MSG, …
```

[orchagent]: Cast enum class variable to int

---

orchagent/aclorch.cpp
orchagent/aclorch.h

**What I did**
In pfc watchdog, packet drop stats does not come from the acl counters on brcm platform. In such a case, we do not need to attach the acl counters to the ACL entry. This is also the application case for acl entry creation in QosOrch::initAclEntryForEcn, which does not come with the acl counters attached.
On brcm dut

Allow ACL entry creation without ACL counter attaching to it

---

fpmsyncd/fpmlink.cpp
fpmsyncd/fpmlink.h

**What I did**
Fixed compilation issue when disabled optiomizations (SONIC_PROFILING_ON=y in SONiC build system)
To fix compilation issue
Built swss debian package
Error from gcc:
```
stepanb@ac724d5440a8:/sonic/src/sonic-swss$ make
make  all-recursive
make[1]: Entering directory '/sonic/src/sonic-swss'
Making all in fpmsyncd
make[2]: Entering directory '/sonic/src/sonic-swss/fpmsyncd'
g++ -DHAVE_CONFIG_H -I. -I.. -I .. -I ../warmrestart -I  -g  -std=c++11 -Wall -fPIC -Wno-write-strings -I/usr/include/libnl3 -I/usr/include/swss -Werror -Wno-reorder -Wcast-align -Wcast-qual -Wconversion -Wdisabled-optimization -Wextra -Wfloat-equal -Wformat=2 -Wformat-nonliteral …
```

[fpmsyncd] align port variable type with sockaddr_in.sin_port

---

orchagent/crmorch.cpp

1. Modify IPV6_Neighbor to IPV6_NEIGHBOR using upper case of full word.
2. Except this variable, the others all use upper case full word.
For consistency, I modified it to use upper case full word.
3. I test the case by python test. I set the high thresholds of ipv6 neighbor to 90 ,  and  set the thresholds ipv6 neighbor type to "free". Setting the value to 1000 for ipv6 neighbors by function setReadOnlyAttr, and check the syslog . The syslog should display as  "IPV6_NEIGHBOR THRESHOLD_EXCEEDED for TH_FREE" .

modify the string from IPV6_Neighbor to IPV6_NEIGHBOR for crmResTypeNameMap.

---

fpmsyncd/routesync.cpp
fpmsyncd/routesync.h

fpmsyncd: Improve VNET routes support
* Identify VNET routes based on the name of the master device
* Parse VRF routes like regular routes
Pending items:
* Support warm reboot for VNET routes
Signed-off-by: Wei Bai baiwei0427@gmail.com

[fpmsyncd] Improve VNET routes support

---

orchagent/pfcwdorch.cpp
orchagent/portsorch.cpp

**What I did**
On the PFCWD stats list installment, create ingress ACL table group for each port and bind to it.
When a port is in a LAG, typically an uplink port in tier 0, the bind point of ingress ACL table group is LAG not port. Make up this gap by proactive creation of port bind point in accordance to its egress counterpart: https://github.com/Azure/sonic-swss/pull/787
On brcm dut

Create ingress ACL table group with bind point PORT during the PFCWD stats list installment

---

cfgmgr/teammgr.cpp

**What I did**
change the team conf active/fallback value to Boolean type
Teamd failed to get the correct boolean value for active/fallback config, because teammgr use string "true" in the conf.
/var/log/teamd.log:44324:Feb 15 10:15:24.023782 ASW-C2-4-C11-A.NA61 ERR teamd#teamd_PortChannel2[37]: Failed to get boolean from non-boolean object
/var/log/teamd.log-44447-Feb 15 10:15:24.023782 ASW-C2-4-C11-A.NA61 DEBUG teamd#teamd_PortChannel2[37]: Using active "1".
With the fix, the teamd was able to get the correct boolean value from teammgr without above error.

[teammgr] use boolean value for active/fallback in teamd conf

---

orchagent/vnetorch.cpp

* Initialize VNET ID before creating VNET object
**What I did**
Fixed incorrect creation flow for bitmap VNET: initialize VNET ID before creating VNET object.
It is a bug in VNET creation flow and it should to be fixed (it causes random failures for "decap" traffic flow).
- Manual tests
- Ansible tests
- Virtual switch tests
N/A

[vnetorch]: Fix incorrect creation flow for bitmap VNET

---

cfgmgr/vxlanmgr.cpp
cfgmgr/vxlanmgr.h
orchagent/aclorch.cpp
orchagent/aclorch.h
orchagent/portsorch.cpp
orchagent/vnetorch.cpp
orchagent/vnetorch.h
orchagent/vxlanorch.cpp
tests/conftest.py
tests/test_fdb_cold.py
tests/test_fdb_warm.py

vxlanmgrd is responsible for vxlan configuration in Linux
It creates vxlan interface for every vxlan entry in Config DB
Signed-off-by: Ze Gan <zegan@microsoft.com>

[vxlanmgrd]: Add vxlanmgrd

---

teamsyncd/teamsync.cpp
teamsyncd/teamsync.h
teamsyncd/teamsyncd.cpp

**What I did**
As other applications with data reconciliation processing, have teamsyncd to provide similar observability.
```
admin@sonic:~$ show warm_restart state
name          restore_count  state
----------  ---------------  ----------
orchagent                10  reconciled
vlanmgrd                 10
teammgrd                  1
portsyncd                10
neighsyncd               10  reconciled
teamsyncd                 1  reconciled
syncd                     0
bgp                       1  reconciled
```

 Save teamsyncd data reconciliation state to stateDB for observability.

---

cfgmgr/vlanmgr.cpp
tests/test_vlan.py

**What I did**
Fix the issue #850 vlanmgrd will crashed if there has incorrect type value on cfg_db.json.
vlanmgrd will crashed cause by the issue.
1. Add test cases in test_vlan.py to make sure the bug fixed.
- Add vlan with incorrect key prefix
- shall not succeed
- shall not cause vlanmgrd crashed
- Add vlan with incorrect value type
- shall not succeed
- shall not cause vlanmgrd crashed
2. Execute the same steps on #850 to make sure the bug fixed.
Signed-off-by: Emma Lin emma_lin@edge-core.com

Fix issue #850 vlanmgrd will crashed if there has incorrect type value on cfg_db.json.

---

orchagent/aclorch.cpp
orchagent/aclorch.h
orchagent/orchdaemon.cpp
tests/test_mirror_ipv6_combined.py
tests/test_mirror_ipv6_separate.py

Enable both IPv4 and IPv6 source and destination IP match and
mirror functionality in SONiC.

[aclorch]: Add MIRRORv6 support for ACL table

---

orchagent/crmorch.cpp

What I did
Fix issue: If  the op of attr is "del", CRM consumer dotask will cause infinite loop or  delete next operation cmd.
Why I did it
We can't erase any cmd only for del case. We should ignore it, and integrate erasing the operation cmd in the last.
I add only one del attr parameter to check whether consumer dotask will cause infinite loop or not. 
Here is the del attr parameter.
KeyOpFieldsValuesTuple Attr("CRM", "DEL", {{ "polling_interval", "20" }});

Removing the erase action for DEL_COMMAND option.

---

fpmsyncd/routesync.cpp
fpmsyncd/routesync.h

fpmsyncd: Fix memory leak bug
* Allocate and free Netlink memory in RouteSync::getIfName()
Signed-off-by: Wei Bai baiwei0427@gmail.com

[fpmsyncd] Fix memory leak bug

---

swssconfig/sample/00-copp.config.json

**What I did**
Switch arp/arp response/neighbor_discovery IO trap action from 'trap' to 'copy'. These IO, instead of trap to CPU and dropped, they will be copy to CPU and forwarded on VLAN.
During warm reboot, we need VLAN take care of ARP traffic by itself.
Tested with matching test: https://github.com/Azure/sonic-mgmt/pull/824

[arp] copy arp IO to cpu instead of trap and drop

---

orchagent/orchdaemon.cpp
orchagent/watermarkorch.cpp
orchagent/watermarkorch.h

No need to periodically clear watermarks if the polling is disabled.
**What I did**
Changes:
- make watermarkorch aware of Flex Counter config
- enable/disable periodic timer based on Flex Counter status of watermarks. 
```
Apr 25 13:02:21.782115 sonic DEBUG swss#orchagent: :- doTask: Periodic watermark cleared by timer!
Apr 25 13:02:31.762604 sonic DEBUG swss#orchagent: :- doTask: Periodic watermark cleared by timer!
Apr 25 13:02:41.772739 sonic DEBUG swss#orchagent: :- doTask: Periodic watermark cleared by timer!
Apr 25 13:02:51.756292 sonic DEBUG swss#orchagent: :- doTask: Periodic watermark cleared by timer!
Apr 25 13:03:06.765902 sonic DEBUG swss#orchagent: :- doTask: Periodic watermark cleared …
```

[watermarkorch] only perform periodic clear if the polling is on

---

neighsyncd/restore_neighbors.py

**What I did**
Fix crash https://github.com/Azure/sonic-swss/issues/861
To fix a restore_neighbors.py crash
```
Apr 26 09:13:09.165635 arc-switch1025 INFO swss#supervisord: start.sh restore_neighbors: started
Apr 26 09:13:11.388802 arc-switch1025 INFO swss#supervisord: restore_neighbors WARNING:__main__:Neigh exists in kernel with family: IPv4, intf_idx: 2, ip: 10.210.25.32, mac: 14:18:77:33:f0:50
Apr 26 09:13:15.180388 arc-switch1025 INFO swss#supervisord 2019-04-26 09:13:09,135 INFO spawned: 'restore_neighbors' with pid 47
Apr 26 09:13:15.180388 arc-switch1025 INFO swss#supervisord 2019-04-26 09:13:09,140 INFO success: restore_neighbors entered RUNNING state, process has stayed up for > than 0 …
```

[restore_neighbors] fix restore_neighbors crash

---

orchagent/intfsorch.cpp

**What I did**
Add "!" to the if statement of vrf_name existence checking.
It should skip non-existent VRF, not the opposite.
Verified with local gtest.
N/A

[intfsorch] Fix bug for VRF existence check

---

tests/test_crm.py

**What I did**
if stats (used/available) is not present, the function returns None. Modified to return 0 if no stats match.
Fixing an issue introduced as part of https://github.com/Azure/sonic-swss/pull/830
N/A

Return 0 for CRM counter instead of None if no match

---

cfgmgr/intfmgr.cpp
tests/test_vnet.py

**What I did**
Re-enable Vnet Vxlan tests. 
Check VRF name before setting it as master. It is possible to have INTERFACE table without the `vrfname `for the `default ` VRF case. Check added to handle this. 
Dependency with https://github.com/Azure/sonic-buildimage/pull/2705 resolved
N/A
N/A

Undo skipping Vnet tests, Vrf check before enslaving

---

tests/test_vlan.py

**What I did**
[vlan] Add pytest cases to add max vlan.
Add test case:
1. Add max vlan (2-4094) and remove it. => succeed
==================================================================== test session starts =====================================================================
platform linux2 -- Python 2.7.15rc1, pytest-3.3.0, py-1.8.0, pluggy-0.6.0 -- /usr/bin/python
rootdir: /home/ubuntu/sonic-buildimage/src/sonic-swss/tests, inifile:
collected 25 items
test_vlan.py::TestVlan::test_VlanAddRemove PASSED 										[  4%]
test_vlan.py::TestVlan::test_MultipleVlan PASSED										[  8%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectKeyPrefix[test_input0-0] PASSED		[ 12%] …

[vlan] Add pytest case to add max vlan.

---

orchagent/Makefile.am
orchagent/copporch.cpp
orchagent/mirrororch.cpp
orchagent/mirrororch.h
orchagent/orchdaemon.cpp
orchagent/orchdaemon.h
orchagent/policerorch.cpp
orchagent/policerorch.h
tests/test_mirror_policer.py

Now that we could create a policer for the mirror session to
throttle the mirroring traffic.
configuration:
POLICER|NAME:
meter_type:packets|bytes
mode:sr_tcm|tr_tcm|storm_control
cir|DIGITS
cbs|DIGITS
pir|DIGITS
pbs|DIGITS
corlor_source:aware|blind
red_action:drop
yellow_action:drop
green_action:drop
MIRROR_SESSION|NAME:
policer:policer_name

[policerorch]: Add PolicerOrch to bundle with mirror session

---

neighsyncd/neighsync.cpp
orchagent/neighorch.cpp

**What I did**
In certain cases, we get neighbor entries with BCAST MAC. This can be safely ignored from programming the hardware
Directed bcast entries are added as part of Interface IP address creation. The neighbor update is redundant. 
Configure neighbor entry with BCAST mac. 
```
sudo ip neigh add 10.1.1.255 lladdr ff:ff:ff:ff:ff:ff dev Ethernet124
NOTICE swss#neighsyncd: :- onMsg: Broadcast Mac recieved, ignoring for 10.1.1.255
```

Ignore neighbor entry with BCAST MAC, check SAI status exists

---

tests/test_mirror.py
tests/test_mirror_ipv6_combined.py
tests/test_mirror_ipv6_separate.py

Due to the change
c033b2380419fe36dfc3b5e055bbe0376cc8f4e7
Fix MIRROR_SESSION table macro name (#802)

[test]: Update the mirror session state table name

---

neighsyncd/neighsync.cpp

**What I did**
Fix compilation issue. For delete case, this code will not be executed as it gets returned earlier

Fix compilation issue to ignore neighbor entries with Broadcast Mac

---

warmrestart/warmRestartAssist.cpp
warmrestart/warmRestartAssist.h

**What I did**
When comparing 2 vectors, assume their elements could be re-ordered.
Without he change, during warm reboot, some neighbor entries will be mistakenly judged as having new value and recreated.
With the change, no neighbor entry got recreated due to having 'new value' after warm reboot.

[warm restart assist] assume vector values could be reordered

---

doc/swss-schema.md
orchagent/portsorch.cpp
orchagent/portsorch.h
tests/test_port.py

**- What I did**
Dynamic transceiver tuning support
**- How I did it**
Dynamically program pre-emphasis and other settings based on media detected in xcvrd. The various supported media are defined in media_settings.json
**- How to verify it**
Perform OIR of different media types. Dump the pre-emphasis values from hardware and verify that they got reflected
**- Description for the changelog**
Support for dynamically programming pre-emphasis
**DO NOT MERGE THIS PULL REQUEST UNTIL BCM SDK SUPPORT FOR SAI PREEMPHASIS ATTRIBUTES HAVE BEEN MERGED**
**- A picture of a cute animal (not mandatory but encouraged)**

Dynamic transceiver tuning support 

---

tests/test_vnet.py

**What I did**
Extended Bitmap VNET virtual switch test with "remove" flows
In order to test Bitmap VNET remove flows
Executed VNET test and verified it passed
N/A

[vnet]: Extend Bitmap VNET test with "remove" flows

---

orchagent/vxlanorch.cpp

**What I did**
If the tunnel is not existed, it should change to return false when remove next hop for a tunnel 
For `VxlanTunnelOrch::removeNextHopTunnel` it both checkt tunnel and nexthop existed or not. But in the checking fail case, the first return true and the second return false   
Call r`VxlanTunnelOrch::removeNextHopTunnel` for a non existed tunnel for testing.

[vxlanorch] Ambiguous return code for removeNextHopTunnel

---

orchagent/pfcwdorch.cpp
orchagent/pfcwdorch.h

Address review comment: remove data member m_entriesCreated, which is introduced for dependancy resolution purpose.
Improve on https://github.com/Azure/sonic-swss/pull/794
**What I did**
On brcm dut

Resolve execution dependancy in pfcwd warm-reboot by overriding doTask(void)

---

teamsyncd/teamsync.cpp
teamsyncd/teamsync.h

**What I did**
Set LAG `mtu `value based on kernel netlink msg along with `admin `and `oper `status 
During initialization, the `mtu `attribute is not always present in `LAG_TABLE`. This change ensures that MTU is always set to APP DB as  the same value as configured in kernel. 
Check APP DB entry and verify syslog config

Set LAG mtu value based on kernel netlink msg

---

orchagent/main.cpp

**What I did**
This is a try to work around the coredump create issue:  https://github.com/Azure/sonic-swss/issues/734
core dump with right stack trace created.
Actually It might be caused by incorrect destruct of multiple orch ( inter-dependency, order and etc.), which triggered more segmentation during try/catch stack unwinding, then only the latest segfault got recorded. 
If people have idea about how to fix the possible orch destruct issue, that would be better.

Remove try/catch for correct coredump file

---

debian/rules
tests/.clang-format
tests/Makefile.am
tests/aclorch_ut.cpp
tests/check.h
tests/mock_consumerstatetable.cpp
tests/mock_dbconnector.cpp
tests/mock_hiredis.cpp
tests/mock_orchagent_main.cpp
tests/mock_redisreply.cpp
tests/portal.h
tests/request_parser_ut.cpp
tests/saispy.h
tests/saispy_ut.cpp
tests/ut_helper.h

**What I did**
Add unit test for aclorch.
Do unit test in development phase. The developer can check each variable in each stack frame. And also do memory leakage detection or buffer overrun test. That is different than pytest, it is black box test. But, this is white box test.
The new committed testes are all passed.
The unit test of aclorch have two scopes. One is cover the whole aclorch behaviors. Second is for internal component like AclTable or AclRule.
The first scope. Each test will call doTask() that simulate configDB was changed. All reaction by AclOrch, AclTable or AclReult will save into libvs via SAI. Then we can verify the results via SAI to make sure every operation is correct.
The second scope using spy function …

[aclorch] unittest by gtest

---

orchagent/vnetorch.cpp
orchagent/vnetorch.h

**What I did**
Fixed tunnel route removal flow for bitmap VNET by adding remove logic for newly added ```meta tunnel``` entry.
Some time ago, when ```encap``` flow was changed for bitmap VNET, only ```create``` flow was added for new ```meta tunnel``` entry and ```remove``` was missed. As a result if remove tunnel route ```meta tunnel``` entry still exists in HW, which is incorrect.
Ran ansible and VS tests.
N/A

[vnetorch]: Fix tunnel route removal flow for bitmap VNET

---

tests/conftest.py
tests/test_warm_reboot.py

**What I did**
use pkill -9 for zebra kill during warm restart test.  This is the same as warm reboot.
FRR 7.0 zebra resends all existing route to fpm channel upon receiving sigterm signal, that caused warm restart vs DB operation check failure.
VS

pkill -9 zebra for frr warm restart VS test fix

---

orchagent/orchdaemon.cpp
orchagent/pfc_detect_barefoot.lua

**What I did**
This is a clone of this PR: https://github.com/Azure/sonic-swss/pull/823 for 201811
pfc_wd community test on barefoot platform passed.

[orchagent] PFC WD support for BFN platform

---

orchagent/orchdaemon.cpp
orchagent/vnetorch.cpp
orchagent/vnetorch.h
tests/test_vnet.py

Signed-off-by: Weixi Chen <Weixi.Chen@microsoft.com>
**What I did**
1. Add VNET_ROUTE and VNET_ROUTE_TUNNEL tables in CONFIG_DB so that VNET routes get persistent after reboot if a config_save is performed. 
2. Add a new orchagent VnetRouteCfgOrch that listens for newly exposed tables in CONFIG_DB which have a one to one relation with existing APP_DB tables. 
Static vnet routes provisioned in sonic are not persistence. Switch reboot leads to the loss of static routes. Tables in CONFIG_DB will be persistent if a config save is manually performed.
run vs test: sudo pytest test_vnet.py -s -v --dvsname=vs
output:
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause …

swss-orchagent: add new orch for vnet routes/tunnel routes tables in CONFIG_DB 

---

tests/test_vnet.py

**What I did**
Fixed bitmap VNET virtual switch test failures related to extra FDB entries learned
Bitmap VNET vs test fails due to some FDB entries learnt during test execution
Executed virtual switch tests
N/A

[vs]: Fix bitmap VNET virtual switch test

---

orchagent/aclorch.cpp

What I did
Fix issue: When it creates or deletes DTelWatchListTables successfully, it dosen't inc/decCrmAclUsedCounter.
Why I did it
When it creates or deletes DTelWatchListTables successfully, it should inc/decCrmAclUsedCounter with SAI_ACL_BIND_POINT_TYPE_SWITCH case.
Create AclOrch to check whether DTelWatch add call incCrmAclUsedCounter two times or not, and aslo call decCrmAclUsedCounter two times when it delete AclOrch.

add inc/decCrmAclUsedCounter for SAI_ACL_BIND_POINT_TYPE_SWITCH case.

---

orchagent/aclorch.cpp

In order to simplify operations, it may be desirable to combine the
DTEL flow and drop watchlists into one single watchlist that contains
both flow and drop actions. This change adds the drop actions to the
flow watchlist, allowing the combination of flow and drop actions in
a single ACL table.
This change also allows ACTION_DTEL_REPORT_ALL_PACKETS in drop
watchlists.
Signed-off-by: Mickey Spiegel <mspiegel@barefootnetworks.com>
**What I did**
This change adds the drop actions to the flow watchlist, allowing the combination of flow and drop actions in a single ACL table.
This change also allows ACTION_DTEL_REPORT_ALL_PACKETS in drop watchlists.
In order to simplify operations, it may be desirable to combine the DTEL flow and drop watchlists into one single watchlist that …

[aclorch]: Allow DTEL drop actions in DTEL flow watchlist

---

orchagent/orchagent_restart_check.cpp

**What I did**
Fix typo.
Though the "fasle" typos don't affect current warm_restart_check functions duo to the fact that both noFreeze and skipPendingTaskCheck are being checked against "true" value,  they pose some potential risk for future update.
https://github.com/Azure/sonic-swss/blob/master/orchagent/switchorch.cpp#L175
https://github.com/Azure/sonic-swss/blob/master/orchagent/switchorch.cpp#L179
VS test.

Fix typo in orchagent_restart_check from fasle to false.

---

orchagent/crmorch.cpp

Set timer only when interval changes. Not in each firing of the timer.

---

tests/conftest.py
tests/test_mirror_ipv6_combined.py
tests/test_mirror_ipv6_separate.py
tests/test_mirror_policer.py

INTF_NAME entry is needed besides INTF_NAME|PREFIX
This change is introduced in commit 185e9a184 #794

[test]: Fix set interface in configuration database

---

orchagent/copporch.cpp

copporch.cpp: In member function ‘virtual void CoppOrch::doTask(Consumer&)’:
copporch.cpp:607:34: error: catching polymorphic type ‘const class std::out_of_range’ by value [-Werror=catch-value=]
catch(const out_of_range e)
^
cc1plus: all warnings being treated as errors

[copporch]: Fix polymorphic type error

---

orchagent/mirrororch.cpp

Otherwise, in the getgetNeighborInfo function, it will check whether
the nexthop is zero, but it will return false according to
IpAddress::isZero(), then it will try to query the
neighbor orch about this invalid ip address.
Signed-off-by: Richard Wu <wutong23@baidu.com>
**What I did**
In current implement， in the getgetNeighborInfo function, it will check whether the nexthop is zero, but it will return false according to  IpAddress::isZero(), then it will try to query the neighbor orch about this invalid ip address.

[MirrorOrch]: Init the next hop ip with 0 instead of default constructor

---

orchagent/aclorch.cpp

First check if the string to compare is a match action and then
check if the match action is MATCH_DSCP.

[aclorch]: Fix matching MIRROR_DSCP throws unnecessary errors

---

cfgmgr/vxlanmgr.cpp
cfgmgr/vxlanmgr.h

- What I did
Clear old vxlan devices that were created at last time
- Why I did it
1. "config reload" command will kill the swss container, which will make the vxlanmgrd loss the cache information. And to execute "ip link add xxx " command will fail after the vxlanmgrd process restart, because the vxlan device has been created.
2. The Vnet was deleted by modifying config_db.json, and then execute "config reload" command, which will kill vxlanmgrd process. And when vxlanmgrd restart again, it will cannot receive the delete message, because the redis database also was clear after "config reload". So those vxlan devices will become garbage until the kernel restart.
- How I verified it
Test it in Chassis topology.

[vxlanmgrd]: Fix for vxlanmgrd cannot correctly work after config reload

---

tests/test_dirbcast.py

**What I did**
Add VS test for verifying neighbor entry with BCAST MAC
Run VS tests
```
sudo pytest -v test_dirbcast.py --dvsname=vs
============================================================================= test session starts ==============================================================================
platform linux2 -- Python 2.7.12, pytest-3.3.0, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python
rootdir: /datadrive/sonic/build/vnet/sonic-swss/tests, inifile:
collected 1 item                                                                                                                                                               
test_dirbcast.py::test_DirectedBroadcast PASSED
```

Add a neighbor entry with BCAST MAC and verify its ignored

---

orchagent/copporch.cpp

**What I did**
The map m_syncdTrapIds maps trapid to trap_group object. However in the implementation it was mapped to trap object.  Hence modified to map to trap_group object.
TrapIdTrapGroupTable m_syncdTrapIds
Fixing it would handle delete sequence in a correct fashion. Without this mapping trap ids would not get mapped to default trap group.

Fixing copporch DEL command

---

orchagent/orchdaemon.cpp

Avoid crash due to accessing deleted pointer, during process exit.
In this case, FdbOrch was calling detach on PortsOrch which is already deleted
and the memory got returned to Kernel, which resulted in kernel exception.
**What I did**

Fix crash during orchagent process exit

---

orchagent/orchdaemon.cpp

**What I did**
Fixed VNET orchagents order for warm-reboot flow
Changed order for VNET and VxLAN orchagents in order to avoid failures on start after warm-reboot
Applied VxLAN/VNET config then performed warm-reboot and verified all is restored and no failures
N/A

[vnetorch]: Fix VNET orchagents order for warm-reboot flow

---

orchagent/aclorch.cpp
orchagent/orchdaemon.cpp
tests/mock_tests/aclorch_ut.cpp

TABLE_NAME” is the suffix and “ACL_TABLE” is the table name.
it is good to keep the convention here and align with all other table names.
Please refer to https://github.com/Azure/sonic-swss-common/pull/296

[aclorch]: Change CFG_ACL_TABLE_NAME to CFG_ACL_TABLE_TABLE_NAME

---

orchagent/vnetorch.cpp
orchagent/vnetorch.h
orchagent/vxlanorch.cpp
orchagent/vxlanorch.h

**What I did**
Implemented logic to set default VxLAN encap TTL value
On different platforms default VxLAN encap TTL value is different, so we need to set same value for all
Executed "VNET" ansible test and verified it passed.

[vnetorch]: Set default VxLAN encap TTL value

---

orchagent/aclorch.cpp
orchagent/copporch.cpp
orchagent/fdborch.cpp
orchagent/flexcounterorch.cpp
orchagent/intfsorch.cpp
orchagent/mirrororch.cpp
orchagent/neighorch.cpp
orchagent/orchdaemon.cpp
orchagent/pfcwdorch.cpp
orchagent/policerorch.cpp
orchagent/portsorch.cpp
orchagent/portsorch.h
orchagent/qosorch.cpp
orchagent/routeorch.cpp
orchagent/tunneldecaporch.cpp
orchagent/watermarkorch.cpp

Rename Port member function isPortReady() to allPortsReady()

---

orchagent/aclorch.cpp
orchagent/bufferorch.cpp
orchagent/copporch.cpp
orchagent/countercheckorch.cpp
orchagent/crmorch.cpp
orchagent/fdborch.cpp
orchagent/intfsorch.cpp
orchagent/main.cpp
orchagent/orch.cpp
orchagent/pfcactionhandler.cpp
orchagent/pfcwdorch.cpp
orchagent/policerorch.cpp
orchagent/portsorch.cpp
orchagent/qosorch.cpp
orchagent/routeorch.cpp
orchagent/switchorch.cpp
orchagent/tunneldecaporch.cpp
orchagent/vnetorch.cpp
orchagent/vxlanorch.cpp
orchagent/watermarkorch.cpp

Signed-off-by: Antony Rheneus <arheneus@marvell.com>
**What I did**

ARM32 bit fixes, for 64bit printf format specifier

---

orchagent/main.cpp

**What I did**
Implement synchronous flag for orchestration agent
To allow dynamic enable synchronous mode from command line
Running from command line and checking if attribute was passed to sairedis lib and waiting for response from syncd.
Related to https://github.com/Azure/sonic-sairedis/pull/476

Add synchronous switch to orch agent

---

tests/test_vlan.py

Signed-off-by: Shu0t1an Cheng <shuche@microsoft.com>

[test]: Update test_vlan to use dvs functions

---

orchagent/bufferorch.cpp
orchagent/portsorch.cpp
orchagent/watermarkorch.h

**What I did**
Buffer pool watermark design is built on a READ_AND_CLEAR polling mode at the syncd level. We observe some SAI implementation is missing the clear_stats operation support for buffer pool watermark, either simply not coded yet or having hardware limitation. In such cases, we have mismatch between the actual polling behavior and what a user perceives from FLEX_COUNTER_DB read from FLEX_COUNTER_GROUP_TABLE.
To have a consistent view, we propose per buffer pool watermark stats polling mode at the orchagent level when not all buffer pools support clear_stats operation on a switch. The situation is detected by issuing clear_stats operation at the orchagent level to probe the capability over all pools first. If this is truly the case, we then do not set "STATS_MODE" field in …

Support per buffer pool watermark polling mode

---

tests/conftest.py

make explicit failure if team kernel module is not available on the system
**What I did**

[vstest]: report error when team kernel module is not available

---

orchagent/qosorch.cpp
orchagent/qosorch.h

Signed-off-by: tengfei <tengfei@asterfusion.com>
**What I did**
Add  cir, pir, cbs, pbs parameters for scheduler 
SAI interface supports cir, pir, cbs, pbs parameters for scheduler, but these parameters were not in orchagent 
I wrote these parameters to redis database by json, and then verified by redis-cli

[qosorch]: Add cir and pir parameters for scheduler

---

tests/conftest.py

default image is docker-sonic-vs:latest
**What I did**

[vstest]: add --imgname option to specify vs image to test

---

orchagent/portsorch.cpp

Remove the platform check for remove/add port action at init phase.
**What I did**
Remove the platform check so all platform can remove/add port based on the configDB or port_config.ini during the init time. 
BRCM is now supporting this. Also we should expect all platforms support this.
Along with sonic-buildimage PR: https://github.com/Azure/sonic-buildimage/pull/3240,  see the test results on that PR.

Remove the platform check for remove/add port action at init phase

---

doc/Configuration.md

Config DB manual is being moved from Wiki to SWSS repo.
Once if this is merged, the page from Wiki will point to this config DB manual.
After that, whichever developer makes changes on config DB, are expected to make the corresponding changes in this manual.

Config DB manual is being moved from Wiki to SWSS repo

---

cfgmgr/vlanmgr.cpp
tests/test_vlan.py

**What I did**
The change includes two parts:
<1> Bring member out of default VLAN 1 upon putting port/lag in a VLAN
<2>  Second part was done by @tieguoevan ( https://github.com/tieguoevan) and incorporated here to avoid test error that would follow change <1>.
```
Summary:
The Bridge interface needs to be up all the time. Otherwise, the command bridge vlan will fail.
Not sure it is a kernel bug, but it cause error when clear all vlan members and reconfigure it.
create a dummy interface in the Bridge to keep it up all the time
```
Without change <2>
```
root@bc133f3f180f:/var/log# /sbin/bridge vlan add vid 2 dev Bridge self
RTNETLINK answers: Invalid argument
root@bc133f3f180f:/var/log# echo $?
255
root@bc133f3f180f:/var/log# bridge …
```

Fix VLAN error introduced with new 4.9 kernel behavior

---

orchagent/vxlanorch.cpp
orchagent/vxlanorch.h

**What I did**
Add the validity checking before we call sai_api to remove tunnel_id and tunnel_term_id.
As the vxlan tunnel_id and tunnel_term_id are not created until the map entrys are added, in case of configuring the vxlan tunnel without map entry, and then it is invalid to remove it without validity checking.
Applied Vxlan tunnel configure without the map entry and then remove the tunnel, there are no errors.

[vxlanorch] Fix Logic of Vxlan tunnel removal 

---

tests/test_crm.py

add some CRM pytest test cases, the list is shown below for CRM test.
1.Test the mechanism for CRM threshold displaying SWSS_LOG_WARN by syslog checking.
2.Add CRM Acl Group test case.
3.Add the configuration tests of threshold and polling interval.
**What I did**
The test is from #859 
https://github.com/Azure/sonic-swss/pull/859

[vstest]: Add the CRM tests

---

cfgmgr/intfmgr.cpp
cfgmgr/intfmgr.h

Signed-off-by: Vasant Patil <vapatil@linkedin.com>
Problem: When SONiC CLI command is used to display summary of interface(s), broadcast address is always 0.0.0.0 irrespective of prefix length
Solution: When interface ip address is added using the command "ip addr add ...", we can specify the broadcast address as well. I did NOT set broadcast addr for interface with point-to-point link addresses(/31, and /127)
Testing:
admin@lnos-x1-a-csw06:~$ show interfaces summary Vlan100
Vlan100: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.1.1.0  netmask 255.255.255.0  broadcast 10.1.1.255
inet6 fe80::2e0:ecff:fe3b:d72f  prefixlen 64  scopeid 0x20<link>
ether 00:e0:ec:3b:d7:2f  txqueuelen 1000  (Ethernet)
RX packets 0  bytes 0 (0.0 B)
RX errors 0  dropped 0  overruns 0  frame 0
TX …

Provide broadcast IP while configuring interface ip address

---

orchagent/Makefile.am
orchagent/orch.h
orchagent/orchdaemon.cpp
orchagent/pfc_detect_innovium.lua

Signed-off-by: Tony Titus ttitus@innovium.com
**What I did**

[orchagent] Add support for Innovium platform

---

orchagent/main.cpp

* before changes:
*  orchagent create_switch first, which is using redis_generic_create() to write ASIC_DB, and syncd will handle this request, since syncd is in syncMode, a response with op "getresponse" is send via internal_syncd_api_send_response().
* but in orchagent , g_syncMode is not set yet at this moment, so there is no internal_api_wait_for_response() waiting the response generated by internal_syncd_api_send_response()
* later internal_redis_generic_get() is invoked and got the response which is not for it. That response cause get_switch_attr  into  segfault  and orchagent exit
> Aug  1 01:58:34.926936 ASW-7005 NOTICE swss#orchagent: :- clear_local_state: clearing local state
> Aug  1 01:58:34.927130 ASW-7005 NOTICE swss#orchagent: :- initSaiRedis: Notify syncd INIT_VIEW
> Aug …

orchagent core dump when executing with -s option (syncMode)

---

orchagent/policerorch.cpp
tests/test_policer.py

Monitor the changes in the configuration databaes and update
the corresponding rate/size for the policers

[policerorch]: Add the capability to update policer rate/size

---

portsyncd/linksync.cpp
portsyncd/portsyncd.cpp

[portsyncd] fix undefined behaviour in Linksync ctor
**What I did**
Fix portsyncd restart bugs
See comments on https://github.com/Azure/sonic-swss/pull/963

[portsyncd] fix portsyncd restart case

---

orchagent/routeorch.cpp

The log statement will cause segmentfault if `observerEntry->second.routeTable` is empty.
**What I did**

[Orchagent]: Fixbug segmentfault at routeorch

---

tests/test_warm_reboot.py

Adjust stale timer for warm-reboot neighborsync test cases
Increase the stale timer to "600" seconds so it won't be aged
out in case the test server is busy or slow
**What I did**

Adjust stale timer for warm-reboot neighborsync test cases

---

tests/test_vnet.py

**What I did**
Fixed FDB related failure in ```vnet_bitmap``` virtual switch test
```vnet_bitmap``` virtual switch test cases fail from time to time due to some extra FDB entries present in ```ASIC_DB```
Ran virtual switch tests and verified they passed
N/A

[vnet]: Fix FDB related failure in "vnet_bitmap" virtual switch test

---

portsyncd/portsyncd.cpp

**What I did**
Added a default catch block in portsyncd code as current catch block only accepts parameter of type Exception. In the throw currently, a const char * is passed which leads to a core dumped scenario.
Added a default catch block.
To test, Build a sonic-Broadcom image. 
Loaded the image in a DUT, rebooted the DUT without a minigraph.xml or config_db.json in /etc/sonic. 
While booting up, when systemd tries to start portsyncd process, it passes the parameter port_config.ini. The right port_config.ini is selected and placed in the right directory in swss docker before starting portsyncd process. The right port_config.ini is selected based HW SKU and platform type which is obtained from DEVICE_METADATA. If the device configuration is not …

[portsyncd]: Add default catch block in portsyncd

---

orchagent/aclorch.cpp

Adding the table name in the log when creating/removing
the ACL rules.

[aclorch]: Revise ACL rule creation/removal logs

---

cfgmgr/nbrmgr.cpp
cfgmgr/nbrmgr.h
cfgmgr/nbrmgrd.cpp
neighsyncd/restore_neighbors.py

**What I did**
1. During Warmboot, the restore_neighbor script sends out ARP/NS for Vlan interfaces based on **oper** status. Since Vlan interface is bound to bridge, it is up by default. Modified to wait for Vlan members to be added.
2. Logger is changed to syslog for getting correct timestamps for events
3. Nbrmgrd  push to kernel must happen only after warmboot neighbor restoration
To fix neigh restore issue for Vlans
```
Aug 28 02:29:09.296187 str-msn2700-04 INFO swss#supervisord: start.sh restore_neighbors: started
Aug 28 02:29:22.277583 str-msn2700-04 INFO swss#restore_neighbor: Error: [Errno 2] No such file or directory: '/sys/class/net/Vlan1000/carrier'
Aug 28 02:29:33.573648 str-msn2700-04 NOTICE swss#vlanmgrd: :- …
```

Warmboot Vlan neigh restore fix

---

doc/swss-schema.md
orchagent/Makefile.am
orchagent/aclorch.cpp
orchagent/aclorch.h
orchagent/acltable.h
tests/test_acl.py
tests/test_mirror.py

**What I did**
- add support for egress mirror action
- move redirect out from PACKET_ACTION to its own REDIRECT_ACTION key preserving backwards compatibility with old schema to be aligned with SAI data types
- query ACL action list supported by ASIC per stage and put this information in STATE DB SWITCH_CAPABILITY table
- perform secondary query for ACL action attributes which parameters are enum values (e.g. for PACKET_ACTION - DROP,FORWARD)
- implement VS test cases for 1 and 2
- fix restart of portsyncd (required for one of the test cases which restart SwSS daemons)
- To add egress mirroring support 
- Ability to check if specific action is supported before applying the configuration 
- VS test cases
- DUT manual tests
- Run ansible "acl" and …

[aclorch] egress mirror action support and action ASIC support check

---

cfgmgr/nbrmgrd.cpp

**What I did**
Check warmboot flag during init, fix a delay issue with VS test
Addressing a previous review comment from PR https://github.com/Azure/sonic-swss/pull/1040
Run on DUT

[neighmgrd]: Check warmboot flag during nbrmgr init

---

teamsyncd/teamsync.cpp

**What I did**
Revert changes done as part of https://github.com/Azure/sonic-swss/pull/922
In some use-cases it is required that kernel MTU is different (may be default 1500) from the config_db value (say 9000).  In this case, if `teamsyncd `updates the MTU value via Netlink, orchagent/asic mtu value would be different from the user configured value. We want `teammgr ` which listens on config db to update the mtu value to APP_DB.
Original change was done due to a timing issue where mtu value was found to be missing in APP_DB. This resulted in orchagent creating router interface with 1492 mtu value - Logs are in details
Load the changes and `reboot`, `config reload` and check if `mtu `is correct in `APP_DB` as expected.
```
Jun …
```

[teamsyncd]: Do not update lag mtu from teamsyncd (netlink)

---

fpmsyncd/routesync.cpp

change in fpmsyncd to skip the lookup for the Master device name if the route object table value is zero

---

orchagent/aclorch.cpp

In ACL combined mode, v4 and v6 rules are sharing the same
physical table while having separated configuration tables.
The daemon needs to use the configuration table name to store
the counter information.

[aclorch]: Fix table name in counter table for mirror rules

---

fpmsyncd/fpmlink.cpp
fpmsyncd/fpmlink.h
orchagent/orch.h
teamsyncd/teamsync.cpp
teamsyncd/teamsync.h

which switched return type from void to uint64_t.
**What I did**

Adopt to signature change of Selectable::readData

---

neighsyncd/neighsync.cpp

**What I did**
Revert back one change from this [PR](https://github.com/Azure/sonic-swss/pull/774) to ignore link local neighbor as there are some current limitations with handling link-local neighbors

[neighsyncd]: Ignore link local neighbor entries

---

orchagent/mirrororch.cpp
orchagent/mirrororch.h

Remove deprecated mirror session states in the state database
Signed-off-by: Shu0t1an Cheng <shuche@microsoft.com>

[mirrororch]: Remove mirror session state after it is remvoed

---

orchagent/mirrororch.cpp

As a workaround, this commit prevents SET API get executed when toggling
between a VLAN monitor port and a non-VLAN monitor port.
Until SAI validation is completed, this workaround is needed.

[mirrororch]: Toggle the mirror session when moving between VLAN/non-VLAN

---

orchagent/mirrororch.cpp

**What I did**
Address compile issue.

[swss] address compiler switch issue

---

cfgmgr/buffermgr.h
cfgmgr/intfmgr.h
cfgmgr/nbrmgr.h
cfgmgr/portmgr.h
cfgmgr/teammgr.h
cfgmgr/vlanmgr.h
cfgmgr/vrfmgr.h
cfgmgr/vxlanmgr.h
orchagent/copporch.h
orchagent/countercheckorch.h
orchagent/crmorch.cpp
orchagent/crmorch.h
orchagent/flexcounterorch.h
orchagent/notifier.h
orchagent/orch.h
orchagent/request_parser.cpp
orchagent/request_parser.h
orchagent/switchorch.h
orchagent/timer.h
orchagent/tunneldecaporch.h
orchagent/vrforch.cpp
orchagent/vrforch.h
orchagent/watermarkorch.h

not using namespace in header files

---

orchagent/intfsorch.cpp
orchagent/vnetorch.cpp
orchagent/vnetorch.h
tests/test_vnet.py

**What I did**
Change the model from creating two different VRFs (ingress and egress) as captured [here ](https://github.com/opencomputeproject/SAI/blob/master/doc/SAI-Proposal-QinQ-VXLAN.md
)and use only one VRF
To avoid potential scaling issues with replicating routes to multiple VRFs.
Run ansible test (vnet_vxlan) and the pytest.

Single VRF for ingress and egress flows, skip route replication

---

orchagent/aclorch.cpp
orchagent/aclorch.h

Use similar DSCP value parsing logic for TCP falgs value parsing.
Remove the deprecated functions.
Signed-off-by: Shu0t1an Cheng <shuche@microsoft.com>

[aclorch]: Simplify the TCP flags matching code and support exact value match

---

debian/changelog

**What I did**
Revert changelog that was done for passing VS test as part of https://github.com/Azure/sonic-swss/pull/977
Original issue is fixed as part of  Azure/sonic-build-tools@e9e3957

Revert changelog that was done for passing VS test.

---

tests/test_crm.py
tests/test_route.py

**What I did**
Update Route test to check for added entry
Sometimes, default routes keeps coming on eth0 during the route add and this can result in test failure
Run VS test
For CRM check log case:
```
marker = '=== start marker 2019-10-10T05:25:38.550022 ==='
err_log = 'IPV6_ROUTE THRESHOLD_EXCEEDED for TH_FREE', expected_cnt = 1
def check_syslog(dvs, marker, err_log, expected_cnt):
(exitcode, num) = dvs.runcmd(['sh', '-c', "awk \'/%s/,ENDFILE {print;}\' /var/log/syslog | grep \"%s\" | wc -l" % (marker, err_log)])
>       assert num.strip() == str(expected_cnt)
E       AssertionError: assert '2' == '1'
E         - 2
E         + 1
```

Update Route test to check for added entry

---

orchagent/aclorch.cpp

[aclorch]: Check for existing mirror table only when creating a new table
**What I did**
I modified aclorch to check for existing mirror tables only when creating new tables, not when modifying/replacing an existing table.
Configlets may modify the bindings for MIRROR tables, this change makes it easier to do so. It also makes the behavior for updates to MIRROR tables consistent with the behavior with updates for other table types.
I updated the bindings for the EVERFLOW ACL table and verified that the group was deleted and created, as expected.

[aclorch]: Check for existing mirror table only when creating a new table

---

orchagent/copporch.cpp

sonic-swss/orchagent:  Add new protocol trap name support in CoPP
Added new protocol name support so these names can be used in copp_config.json file and properly parsed.
This is to support new feature requirement.
Verified Sonic image on Broadcom target by specifying these new traps in copp_config.json file and verified these new protocols are trapped and policed as they are configured in the copp_config.json file.
Signed-off-by: jingping.xie@broadcom.com

sonic-swss/orchagent:  Add new protocol trap name support

---

Makefile.am
configure.ac
tests/Makefile.am
tests/request_parser_ut.cpp

Enable C++ unit test during build

---

orchagent/copporch.cpp

Signed-off-by: wangshengjun <wangshengjun@asterfusion.com>
**What I did**
fix the endless loop problem when removing copp table group.
When removing copp table group, the copp orchangent trapped into endless loop.
1.remove the copp table group, as follows:
00-copp.config_back.json :
[
{
"COPP_TABLE:trap.group.bgp.lacp": {
"trap_ids": "bgp,bgpv6,lacp",
"trap_action":"trap",
"trap_priority":"4",
"queue": "4"
},
"OP": "DEL"
}
]
swssconfig  00-copp.config_back.json
2.check the syslog, as follows
Aug 27 15:40:02.982399 48S-sdd NOTICE swss#orchagent: :- processCoppRule: processCoppRule OP DEL trap_group_name trap.group.bgp.lacp 
Aug 27 15:40:03.982379 48S-sdd NOTICE swss#orchagent: :- processCoppRule: processCoppRule OP DEL trap_group_name …

[copporch]: fix the endless loop problem when removing copp table group.

---

orchagent/mirrororch.cpp
orchagent/mirrororch.h

When a mirror session is referenced by an ACL rule, we cannot remove
the mirror session. However, once the ACL rule gets removed, a retry
would help clean up the to-be-removed mirror session.

[mirrororch]: Add retry logic when deleting referenced mirror session

---

portsyncd/portsyncd.cpp
tests/test_port_config.py

[portsyncd] Remove the port_config.ini dependency from portsyncd
portsyncd will rely on configDB port table, not from port_config.ini
port_config.ini is used when we convert minigraph to configDB, then
everything should come from configDB.
Also for the DPB feature, we are going to deprecate port_config.ini
**What I did**
Remove the port_config.ini dependency from portsyncd
port_config.ini is used when we convert minigraph to configDB, then
everything should come from configDB.
Also for the DPB feature, we are going to deprecate port_config.ini
vs-test

[portsyncd] Remove the port_config.ini dependency from portsyncd

---

orchagent/copporch.cpp
orchagent/copporch.h
orchagent/orchdaemon.cpp
swssconfig/sample/00-copp.config.json

**What I did**
Copp orch changes for programming genetlink attributes defined in https://github.com/opencomputeproject/SAI/pull/936 and also defining trap group for SFLOW
As part of SFLOW changes in host interface are required to support genetlink.
PLEASE DO NOT MERGE UNTIL SAI Support is added.

Copp sflow changes

---

orchagent/bufferorch.cpp
orchagent/portsorch.cpp
orchagent/portsorch.h
portsyncd/portsyncd.cpp

Allow buffer profile apply after init

---

orchagent/neighorch.cpp

**What I did**
Check RIF/Port in case of set
During warmboot, we get neighbor delete notifications for Bridge member ports. This looks to be an indexing issue and transient. As a safety fix, the check for RIF is moved in orch to set case
Logs:
```
syslog.1:Sep  6 10:41:37.362397 DSM09T0 INFO kernel: [   74.426644] Bridge: port 25(Ethernet124) entered forwarding state
syslog.1:Sep  6 10:41:43.899725 DSM09T0 NOTICE swss#orchagent: :- addVlanMember: Add member Ethernet120 to VLAN Vlan809 vid:809 pid1000000000552
syslog.1:Sep  6 10:41:43.900683 DSM09T0 NOTICE swss#orchagent: :- addBridgePort: Add bridge port Ethernet124 to default 1Q bridge
syslog.1:Sep  6 10:41:43.901039 DSM09T0 NOTICE swss#orchagent: :- addVlanMember: Add member Ethernet124 to VLAN Vlan809 vid:809 …
```

Check RIF/Port exists only for add entries

---

cfgmgr/intfmgr.cpp
cfgmgr/portmgr.cpp
cfgmgr/shellcmd.h
cfgmgr/teammgr.cpp
cfgmgr/vlanmgr.cpp
cfgmgr/vrfmgr.cpp
cfgmgr/vxlanmgr.cpp
configure.ac
portsyncd/linksync.cpp
tests/Makefile.am
tests/quoted_ut.cpp

Quote input strings from function arguments before constructing a command line, so prevent of the bash script input injection.
`man dash` shows below section, which indicates the double quotes and escaping is enough for general use.
```
Double Quotes
Enclosing characters within double quotes preserves the literal meaning of all characters except dollarsign ($), backquote (`), and backslash (\).  The backslash inside double quotes is historically weird, and serves to quote only the following characters:
$ ` " \ <newline>.
Otherwise it remains literal.
```

Quote input strings before constructing a command line

---

tests/test_sflow.py

**What I did**
Update pytests for sflow
The updated pytests test the flow from cfg_db to sflowmgr to sfloworch to asic_db. Thus end to end flow is tested
Execute the tests
DO NOT MERGE UNTIL THE BELOW PULL REQUEST IS MERGED
https://github.com/Azure/sonic-buildimage/pull/3595

Updating pytest for sflow

---

orchagent/pfc_detect_broadcom.lua

[fix] Use the same storm detection condition for queue occupancy non-zero case as the zero case

---

orchagent/bufferorch.cpp
orchagent/portsorch.cpp
orchagent/portsorch.h

Apply buffer profiles when hardware physical ports are created
Introduce a mini state machine to track the portConfigState transition on receiving event from APPL_DB PORT_TABLE 
**What I did**
On brcm dut
```
Oct 30 03:46:13.403689 str-dx010-acs-1 ERR swss#orchagent: :- doPortTask: m_portConfigState: key PortConfigDone received, transit to state PORT_CONFIG_RECEIVED*
Oct 30 03:46:14.346703 str-dx010-acs-1 ERR swss#orchagent: :- doPortTask: m_portConfigState: transit to state PORT_CONFIG_DONE
Oct 30 03:46:14.566002 str-dx010-acs-1 ERR swss#orchagent: :- doPortTask: admin up port Ethernet112
Oct 30 03:46:14.566813 str-dx010-acs-1 ERR swss#orchagent: :- doPortTask: m_portConfigState: state PORT_CONFIG_DONE …
```

Apply buffer profiles: not wait till kernel net_devices are created for all physical ports

---

orchagent/pfcwdorch.cpp
orchagent/portsorch.cpp

[201811] [portsorch] fix PortsOrch::allPortsReady() returns true when it should not

---

orchagent/vnetorch.h

**What I did**
Corrected VNET route table size for BITMAP implementation
It wasn't updated according to current supported value which is 3K BITMAP VNET routes
Ran VNET ansible test for 3K BITMAP VNET routes
N/A

[vnet]: Correct VNET route table size for BITMAP implementation

---

tests/conftest.py
tests/test_fdb.py
tests/test_fdb_update.py

**What I did**
1. Change  test_FdbAddedAfterMemberCreated not to assert the count of entries but to check the existance of entry added by itself, because other entry may be learned after flush. The former test case does't clean the config, that makes more chance to learn fdb entry.
2. Fix the bug is_fdb_entry_exists didn't match key. Add a function get_vlan_oid to change vlanid to bvid. Change mac format to match in asic_db.
fdb test failed often
pass vs tests

[vs_test]fix fdb test failed randomly

---

orchagent/bufferorch.cpp
orchagent/pfcactionhandler.cpp

Signed-off-by: Vitaliy Senchyshyn <vsenchyshyn@barefootnetworks.com>
**What I did**
Changed type of buffer and buffer profile attributes from u32 to u64 as this was done in SAI 1.5
As some buffer attributes migrated to from u32 to u64 sonic just initializes u32 field only and the most significant 4 bytes contain garbage. I such case we receive very big and incorrect number for buffer size, threshold, etc.
Issued **sudo config qos reload** command on BFN platform and saw that the numbers passed to SDK are the same as in the config. 

[bufferorch] Fixed buffer and buffer profile attributes types accoring to changes in SAI 1.5

---

cfgmgr/vxlanmgr.cpp
cfgmgr/vxlanmgr.h

**What I did**
Change the MAC address of vxlan bridge to the switch's.
The vxlan device will not response the traceroute message if its MAC address isn't same with the switch's.
To compare the MAC address of switch's with the Brvxlanxxxx's. We expect that they are exactly same.
Signed-off-by: zegan@microsoft.com

Fix traceroute issue

---

orchagent/aclorch.cpp
orchagent/qosorch.cpp

Signed-off-by: Antony Rheneus <arheneus@marvell.com>
**What I did**

[orchagent] warning fixes for 32bit arch compilation

---

teamsyncd/teamsync.cpp

team_alloc and team_init fail occationally when they start the same time as
teamd instances. Add the retry logic to avoid such cases.

[teamsyncd]: Add retry logic in teamsyncd to avoid team hanlder init failure

---

configure.ac

Signed-off-by: Andriy Kokhan <akokhan@barefootnetworks.com>
**What I did**
Removed BFN specific code from configure.ac
Migration from libswitchsai to libsai
Private build of BFN target

Cleanup configure.ac from BFN specific code

---

cfgmgr/teammgr.cpp

Signed-off-by: shine.chen <shine.chen@nephosinc.com>
**What I did**
- When creating new portchannel, teammgrd gets the MAC from the saved LACP PDU and updates the port-channel MAC accordingly.
- Pls refer to [MCLAG-HLD](https://github.com/Azure/SONiC/pull/325) for details.
- In MC-LAG scenario, two peer devices form one end point of a LAG, these two devices must have the same MAC address since it’s used for LACP. During warm-reboot, this MAC must not be changed. 
- test it on nephos lab. With this approach we observe zero packet loss during mclag warm-reboot procedure.

[teammgrd]during warm-reboot teamd need to recover system-id from saved lacp-pdu

---

orchagent/vnetorch.h

**What I did**
Updated VNET route table size to 40K for BITMAP implementation
Updated it according to latest supported value for BITMAP implementation
Configured 40K BITMAP VNET routes and verified they are applied correctly
N/A

[vnet]: Update VNET route table size to 40K for BITMAP implementation

---

swssconfig/sample/00-copp.config.json

Increase incoming packet rate on in-band interfaces to support faster
download of large files. SONiC firmware image download over in-band can
take a lot of time if the incoming packet rate is limited to 600pps. This,
change increases it to 6000pps. Especially when used by Zero Touch Provisioning
or by sonic_installer for firmware upgrade over in-band interfaces.
Signed-off-by: Rajendra Dendukuri <rajendra.dendukuri@broadcom.com>
**What I did**
Increased packet rate for traffic destined to CPU.
This is required for ZTP or sonic_installer to download large files (firmware image) over in-band interface.
sonic_installer install -y "url" over in-band network

Increase ip2me CIR/CBS for faster in-band file transfers

---

orchagent/vnetorch.cpp

**What I did**
Fixed removal flow for BITMAP VNET tunnel route
There was a mistake in BITMAP VNET code that caused ```used_count``` for endpoints not to be decremented during removing tunnel route. As a result some SDK resources were not fully removed in case one endpoint is shared between two or more tunnel routes.
* Configured multiple VNET tunnel routes with the one shared endpoint
* Removed all the configured tunnel routes
* Verified that all CRM counters are updated as expected
N/A

[bitmap_vnet]: Fix removal flow for tunnel route

---

orchagent/aclorch.cpp
tests/test_mirror_ipv6_separate.py

- Enable DSCP field for MIRRORV6 tables
- Add vs test for MIRRORV6 table initialization
**What I did**
I enabled the DSCP field for MIRRORV6 tables.
I did it to allow users to add DSCP ACL rules to MIRRORV6 tables.
I added a virtual switch test "test_MirrorV6TableCreation" to validate that ASIC DB is updated correctly.
```
daall@valhalla:~/dev/sonic-swss/tests$ sudo pytest -s -v --dvsname=vs test_mirror_ipv6_separate.py::TestMirror
============================================= test session starts ==============================================
platform linux2 -- Python 2.7.15+, pytest-3.3.0, py-1.8.0, pluggy-0.6.0 -- /usr/bin/python2
rootdir: /home/daall/dev/sonic-swss/tests, inifile: …
```

[aclorch] Enable DSCP rules on IPv6 mirror tables

---

orchagent/bufferorch.cpp
orchagent/pfcactionhandler.cpp
orchagent/pfcactionhandler.h
orchagent/port.h
orchagent/portsorch.cpp
tests/mock_tests/mock_orchagent_main.h
tests/mock_tests/portsorch_ut.cpp
tests/mock_tests/ut_saihelper.cpp

**What I did**
I introduce a sync mechanism to protect port PG/queue from changes under PFC storm.
Under warm reboot conditions on Mellanox platform, buffermgrd starts after BufferOrch gets initialized and sets initial state to DB; after reconciliation BufferOrch reacts on those changes and sets PG profile overriding PG profile set by PfcWdOrch.
Run PFC WD + warm reboot test cases.
Mannual restart of buffermgrd when port is under PFC storm - verified PG profile was not overriten.
After storm, PG profile was set according to config db.

[port/buffer] introduce a sync mechanism to protect port PG/queue from changes under PFC storm

---

orchagent/main.cpp
orchagent/orchdaemon.cpp
tests/mock_tests/mock_orchagent_main.cpp
tests/mock_tests/mock_orchagent_main.h

**What I did**
Move away logrotate from signal handler to main orch loop, to not execute any sairedis library code which potentially can be under mutex and cause deadlock when signal handler occur
to not execute sai_switch_api->set_attribute() under signal handler, just to set logrotate flag
running orchagent against vs switch and sending HUP signal to orch process
Since flush method is executed every time that select is returning object from orchdaemon main/start loop, this is good point to check if logrotate is needed

Move away sairedis logrotate from signal handler

---

orchagent/bufferorch.cpp
orchagent/pfcactionhandler.cpp
orchagent/pfcactionhandler.h
orchagent/port.h
orchagent/portsorch.cpp

**What I did**
I introduce a sync mechanism to protect port PG/queue from changes under PFC storm.
Under warm reboot conditions on Mellanox platform, buffermgrd starts after BufferOrch gets initialized and sets initial state to DB; after reconciliation BufferOrch reacts on those changes and sets PG profile overriding PG profile set by PfcWdOrch.
Run PFC WD + warm reboot test cases.
Mannual restart of buffermgrd when port is under PFC storm - verified PG profile was not overriten.
After storm, PG profile was set according to config db.

[201811][port/buffer] introduce a sync mechanism to protect port PG/queue from changes under PFC stormPfcwd bufferorch sync 201811

---

cfgmgr/teammgr.cpp
cfgmgr/teammgr.h
cfgmgr/teammgrd.cpp
teamsyncd/teamsync.cpp
teamsyncd/teamsync.h
teamsyncd/teamsyncd.cpp

**What I did**
The changes implemented in the final fix are, 
(1)	In teammgrd: While adding LAG, save the mapping of lag <-> teamd PID
(2)	In teammgrd: While removing LAG, remove the mapping of lag <-> teamd PID
(3)	Introduce SIGTERM handlers in both teammgrd and teamsyncd
- (a) In teammgrd, send the SIGTERM to all the teamd processes. It takes just a second for teamd processes + port channel interfaces to be cleaned up
- (b) In teamsyncd, clean up the teamd resources like nl_socket etc.
There were multiple Issues seen, in random on doing a config reload/ config loadminigraph
(i)	Teamsyncd segfault 
(ii)	Teamsyncd getting the NETLINK messages with the older IFINDEXs
(iii) "TeamPortSync: Unable to init team socket" error messages
Root cause
With config reload command , …

Teamd :: fix for cleaning up the teamd processes correctly on teamd docker stop

---

orchagent/orchdaemon.cpp
orchagent/portsorch.cpp
orchagent/portsorch.h
tests/mock_tests/portsorch_ut.cpp

**What I did**
To support hitless warm reboot on Mellanox we need to add lag member before any other objects are created that depend on LAG, like RIF

[portsorch] process PortsOrch tables in specific order

---

tests/mock_tests/aclorch_ut.cpp

**What I did**
add CRM validation
run test case

[AclOrch] add validation for check CRM

---

.gitignore
Makefile.am
configure.ac
natsyncd/Makefile.am
natsyncd/natsync.cpp
natsyncd/natsync.h
natsyncd/natsyncd.cpp
neighsyncd/neighsync.cpp
neighsyncd/neighsync.h
warmrestart/warmRestartAssist.cpp
warmrestart/warmRestartAssist.h

Added natsyncd and warmboot related changes.
Link to NAT HLD : https://github.com/Azure/SONiC/blob/master/doc/nat/nat_design_spec.md
Depends on:
sonic-swss : https://github.com/Azure/sonic-swss/pull/1059/ and https://github.com/Azure/sonic-swss/pull/1125
sonic-swss-common : Azure/sonic-swss-common#304
sonic-linux-kernel : Azure/sonic-linux-kernel#100
sonic-sairedis : Azure/sonic-sairedis#519

Natsyncd changes in sonic-swss submodule to support NAT feature.

---

cfgmgr/Makefile.am
orchagent/debugcounterorch.cpp
orchagent/flex_counter/flex_counter_manager.cpp
orchagent/flex_counter/flex_counter_manager.h
orchagent/flex_counter/flex_counter_stat_manager.cpp
orchagent/flex_counter/flex_counter_stat_manager.h
orchagent/portsorch.cpp
orchagent/portsorch.h

- Updates portsorch to use FlexCounterManager for port and queue stats instead of direct redis operations
- Updates FlexCounterManager to support standard Port and Queue counters
- Updates FlexCounterManager to allow clients to enable the group in the constructor, for convenience
- Updates the makefile for cfgmgr to include new flex_counter dependency from portsorch
**What I did**
I refactored portsorch to use FlexCounterManager to handle flex counter operations rather than directly interacting with the FLEX_COUNTER_DB.
I did it to abstract away some of the details of flex counter setup from portsorch and make portsorch simpler. This is also makes it easier to update the flex counter implementation in the future.
**How I …

[portsorch] Refactor portsorch to use FlexCounterManager to setup port and queue stats

---

tests/conftest.py
tests/test_nat.py

**What I did**
Disabled NAT tests.
All Jenkins builds in swss and utilities have been failing for the past 4 days with the following error:
```
if started > timeout:
>               raise ValueError(out)
E               ValueError: arp_update                       STOPPED   Not started
E               bgpd                             STOPPED   Not started
E               buffermgrd                       RUNNING   pid 594, uptime 0:01:10
E               fpmsyncd                         RUNNING   pid 390, uptime 0:01:22
E               intfmgrd                         RUNNING   pid 547, uptime 0:01:16
E               nbrmgrd                          RUNNING   pid 602, uptime 0:01:09
E               neighsyncd …
```

[vs tests] Disable NAT tests to unblock Jenkins

---

orchagent/debug_counter/drop_counter.cpp
orchagent/debug_counter/drop_counter.h
orchagent/debugcounterorch.cpp
orchagent/debugcounterorch.h

- Refactor drop reason capability query to trim SAI prefixes
- Store device capabilities in orchagent to perform safety checks
**What I did**
I added a check in orchagent to prevent unsupported drop counter types and drop reasons from crashing orchagent.
I did this to prevent devices from crashing due to inadvertent configuration errors.
I locally tested by:
1. Inserting a SWITCH_INGRESS counter into config DB on a device where SWITCH_INGRESS_COUNTER was not supported
2. Adding L2_ANY to a counter on a device where L2_ANY was not supported.
3. Created a valid counter on a device to ensure that normal operation was not impacted.
Fixes #1136 - Rather than depending on each ASIC …

[debugcounterorch] Add checks for supported counter types and drop reasons

---

cfgmgr/intfmgr.cpp
cfgmgr/intfmgr.h
cfgmgr/intfmgrd.cpp
cfgmgr/vrfmgr.cpp
cfgmgr/vrfmgrd.cpp

**What I did**
Clear loopback interfaces in kernel at intfmgrd starting except warmstart.
Clear vrf interfaces in kernel at vrfmgrd starting except warmstart.
After loopback moved to intfmgrd, the behavior is changed. 
[issue #3814](https://github.com/Azure/sonic-buildimage/issues/3814)
tests

[cfgmgr] clear loopback and vrf in kernel if not warmstart

---

tests/test_vlan.py
tests/test_warm_reboot.py

**What I did**
I marked the VLAN and warm reboot vs tests as xfail, which means that test failures in those tests will not cause the entire test suite to fail.
I did it to try to reduce the number of test suite failures so that we don't have to spam "retest this please" to unblock PRs.
Opened #1181 and #1182 to track test stabilization.

[vs tests] Mark VLAN and warm reboot tests as xfail

---

neighsyncd/restore_neighbors.py

Otherwise, we can see that DUT after warm reboot sends ARP
packets with management IP (10.112.71.4)
$ sudo tcpdump -ni PortChannel0003 --direction out
16:33:40.572995 ARP, Request who-has 10.0.0.61 tell 10.112.71.4, length
28
All neighbors than are stil considered as STALE.
**What I did**

[restore_neighbors.py] build arp packet with correct hwsrc and psrc

---

README.md

removed the wrong platform build links and updated the build link with sonic-swss-common-build
**What I did**
removed the wrong platform build links and updated the build link with sonic-swss-common-build
the build link is not existed
verified if there is no broken images for build icon

update the build link

---

orchagent/portsorch.cpp
orchagent/portsorch.h
tests/test_portchannel.py

by teamd
Originally portsorch was designed to remove LAG member from LAG when
member gets disabled by teamd. This could lead to potential issues
including flood to that port and loops, since after removal member
becomes a switch port.
Now, portsorch will make use of SAI_LAG_MEMBER_ATTR_INGRESS_DISABLE and SAI_LAG_MEMBER_ATTR_EGRESS_DISABLE
to control collection/distribution through that LAG member port.
With this new flow, teammgrd and teamsyncd are candidates to be refactored, especially teamsyncd
warm reboot logic, since now we don't need to compare old, new lags and lag members.
Teamsyncd's job is simply to signal "status" field update without waiting for reconciliation timer to expire.
e.g. one port channel went down on peer:
```
admin@arc-switch1025:~$ show interfaces portchannel …
```

[portsorch] fix wrong orchagent behaviour when LAG member gets disabled

---

tests/test_fdb_update.py

**What I did**
I updated the fdb_update tests to follow the same convention as the rest of the vs tests (e.g. they all sit inside a wrapper object.
This makes it easier to add pytest fixtures to the whole set of test cases, as well as keeps the Jenkins test report neat and tidy.
```
daall@valhalla:~/dev/sonic-swss/tests$ sudo pytest -s -v --dvsname=vs test_fdb_update.py 
=============================================================================================== test session starts ===============================================================================================
platform linux2 -- Python 2.7.15+, pytest-3.3.0, py-1.8.0, pluggy-0.6.0 -- /usr/bin/python2
rootdir: …
```

[vs tests] Refactor fdb_update tests to be consistent with vs test suite

---

orchagent/aclorch.cpp

Fix the stack-overflow issue in AclOrch::getTableById()
In case the table_id and m_mirrorTableId/m_mirrorTableId are empty
The function would be called recursively without ending.
**What I did**
Fix the potential issue where the function AclOrch::getTableById() could be called recursively without ending.
If we have some rule that does not have table defined, it will trigger this issue.
```
(gdb) bt
#0  0x00007f77ac5af3a9 in swss::Logger::write (this=0x7f77ac801ec0 <swss::Logger::getInstance()::m_logger>, prio=swss::Logger::SWSS_DEBUG, fmt=0x7f77ac5f1690 ":> %s: enter")
at logger.cpp:209
#1  0x00000000004a5792 in AclOrch::getTableById (this=this@entry=0x1c722a0, table_id="") at aclorch.cpp:2617
#2  0x00000000004a59d1 in …
```

Fix the stack-overflow issue in AclOrch::getTableById()

---

cfgmgr/portmgr.cpp
orchagent/portsorch.cpp
orchagent/portsorch.h
portsyncd/linksync.cpp
tests/conftest.py
tests/port_dpb.py
tests/test_acl.py
tests/test_port_config.py
tests/test_port_dpb.py

**What I did**
Support port add/delete cases in different daemons without dependencies
Baseline code for dynamic port breakout code.   
vs test cases
Support port add/delete cases in different daemons
Changes were made on portmgrd/portsyncd and orchagent portsorch
so it should be able to remove/add ports in case no configuration
dependencies or runtime depencies (neighbor, mac etc) on them
Also skipped the netlink for port add/delete with master in portsyncd
and cleaned up g_init and g_portSet flag and data strcutures usage.
Added dynamic portbeakout test cases including the conf_test.py changs
Signed-off-by: Vasant Patil <vapatil@linkedin.com>

[DPB portsyncd/portmgrd/portorch] Support dynamic port add/deletion without dependencies

---

cfgmgr/teammgr.cpp
teamsyncd/teamsync.cpp

**What I did**
These functions are called only once in the time of service stopping,
add events will help debug. And these messages won't be chatty.
Once the cleanup code was on radar as a suspect. If we had these debug messages, it would have cleared the suspect very quickly.

[team sync/mgr] Add debug message before cleaning up LAGs

---

tests/conftest.py
tests/test_nat.py

- Validate that NAT processes are running on dvs
- Mark tests as xfail so results can be monitored
Fixes #1178 
Introduces #1199

[dvs] Add NAT tests back to test suite

---

tests/test_nat.py

The NAT test cases are failed due to NAT commands are not present at time of issue (https://github.com/Azure/sonic-swss/issues/1199) was reported.
Later on sonic-utilities submodule got updated to master "sonic-buildimage" branch and after this update all NAT test cases are passed.
And also fixed a failure seen in test case "test_NatInterfaceZone".
So removing the xfail mark for NAT test cases.

Removed the xfail mark for NAT test cases.

---

orchagent/portsorch.cpp
orchagent/portsorch.h

**What I did**
The code is to add/del items in LAG_NAME_MAP_TABLE in COUNTERS_DB if a lag is added or removed. 
The code need the below pull request:
#51 in Azure/sonic-py-swsssdk 
read portchannel name from LAG_NAME_MAP_TABLE in COUNTERS_DB #51
For use of LAG_NAME_MAP_TABLE in COUNTERS_DB just like fdbshow.
I have create another pull request in Azure/sonic-utilities:
Show mac learned on lag interface #730

Add/Del lag_name_map item when adding and removing lag.

---

orchagent/aclorch.cpp

Default action for Egress ACL Table not populated. 
SAI Query for ACL Capability is not supported as of now for all
platform. This fix issue Swss Issue #1207 
**What I did**
Updated default acl action for Egress ACL Table
Refer Issue #1207 
Manually Verified Running PFC WD testcase

Default action for Egress ACL Table not populated.

---

orchagent/vnetorch.cpp

**What I did**
In VNET route remove handler return ```true``` instead of ```false``` if route is not found in the internal vnetorch cache. It is needed because vnetorch might receive double ```remove``` event and it causes endless warning messages since event will be forever in a message queue. In order to remove it from the queue just need to return ```true``` to the caller (Orch2::doTask).
To fix continues warning messages (shown below) after config reload with the saved VNETs and VNET routes.
```WARNING swss#orchagent: :- removeTunnelRoute: VNET tunnel route 172.2.10.0/24 doesn't exist```
Added VNET config with the different routes to the config_db.json, perform config reload and verified …

[vnet]: Fix continues warning messages after config reload

---

orchagent/copporch.cpp
orchagent/debug_counter/debug_counter.cpp
orchagent/debug_counter/debug_counter.h
orchagent/flex_counter/flex_counter_manager.cpp
orchagent/flex_counter/flex_counter_manager.h
orchagent/routeorch.cpp
orchagent/sfloworch.cpp
orchagent/sfloworch.h

Compiling for 32 bit arch causes compilation issue with %l variants
**replace %l variants with PRI**
**to fix compilation for 32 bit arch**
**compile for 32 bit arch (marvell-armhf)**

using PRI instead of %l to support 32 bit arch

---

orchagent/aclorch.cpp
orchagent/aclorch.h
orchagent/pfcactionhandler.cpp
orchagent/pfcwdorch.cpp
orchagent/port.h
orchagent/portsorch.cpp
orchagent/portsorch.h
portsyncd/linksync.cpp
tests/conftest.py
tests/port_dpb.py
tests/test_acl_portchannel.py
tests/test_port_dpb.py
tests/test_port_dpb_acl.py

NOTE: Please review only commit 77db91c. The other commit will be pushed as a different PR https://github.com/Azure/sonic-swss/pull/1112.
**What I did**
Add update capability for ACL tables when stage and type attributes are not modified. That is provide an way to update portlist of ACL tables
Existing code never deleted a ACL group associated with a port once it is created(it is created when port is bound to an ACL table), that is because we never deleted the port. As part of DPB, as we need to delete the port, hence we also need to delete the ACL group associated with port. But note that, a port can be part of multiple ACL tables. We should delete the ACL group once port is unbound with the last ACL table, and we should create the ACL group once the port is bound to the first ACL table. …

[DPB-ACL] Handle ACL dependency 

---

cfgmgr/natmgrd.cpp
natsyncd/natsyncd.cpp
orchagent/natorch.cpp

Added multi-db changes for natmgrd and natsyncd.

Multi-Db changes for NAT feature.

---

cfgmgr/vrfmgr.cpp

**What I did**
In vrfmgr.cpp, for non-warm reboot case, skip removal of mgmt vrf table from the kernel.
mgmt vrf table in the kernel is installed via /etc/network/interfaces upon reboot, if vrfmgrd removes it after that, mgmt vrf table is missing in the kernel even though it is in the config db.
configure mgmt vrf and data VRF, save the configurations and do node reboot. After reboot, check mgmt vrf table is in the kernel.
Also check data VRFs are also present in the kernel.
root@sonic:~# ip vrf show
Name              Table
-----------------------
Vrf_red           1001
Vrf_green         1002
mgmt              5000   <<<<<<<<

upon cold reboot, skip remove mgmt vrf table from the kernel

---

tests/conftest.py
tests/dvslib/dvs_database.py
tests/test_acl.py

* Introduce new DVSDatabase abstraction and SONiC redis fixtures
* Refactor ACL tests to use redis fixtures
* To help make the vs tests more reliable by not relying on arbitrary wait times
* To make the vs tests faster by reducing the wait time (acl tests run in ~50% of the time now)
```
daall@rainier:~/dev/sonic-swss/tests$ sudo pytest -s -v --dvsname=vs test_acl.py
=========================================================================================== test session starts ============================================================================================
platform linux2 -- Python 2.7.17, pytest-4.6.9, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python
rootdir: …
```

[dvs] Refactor ACL tests to use polling interface to access redis

---

tests/test_interface.py
tests/test_nat.py
tests/test_port_dpb.py

- Disable VRF and NAT test cases due to VS image issues
- Disable DPB test case due to instability
Signed-off-by: Danny Allen
To unblock PRs in sonic-swss and sonic-utilities.
Azure/sonic-sairedis#574 to track VRF image issue
Azure/sonic-sairedis#575 to track NAT image issue
Azure/sonic-swss#1222 to track DPB stability issue

[dvs] Mark unstable test cases as xfail

---

orchagent/port.h
orchagent/portsorch.cpp
orchagent/portsorch.h

* Use SAI REDIS return code to track dependency on port.
**What I did**
While deleting a port, if SAI call return OBJECT_IN_USE error code, we will continue to wait/loop in orchagent to delete the port. Once all the dependencies are removed, we will go-ahead remove the port. Note that dependency tracking itself is done in SAI REDIS layer. Also note that identifying dependencies and removing the dependencies is done in config mgmt layer.
As part Dynamic Port Breakout feature, we need to delete and re-create ports. During deletion of a port, we need to ensure that all dependencies are also removed. For example, port being part of ACL, VLAN, QoS, etc. Initial approach was to track these dependencies in orchagent itself. But after discussion with Microsoft team, we decided …

[DPB:orchagent:portsorch] Rework port dependency  (#23)

---

tests/dvslib/dvs_database.py
tests/test_nat.py

**What I did**
I refactored the NAT tests to use the redis polling fixtures added by #1213.
The NAT tests are failing intermittently due to timing issues, which is blocking PR builds.
```
daall@rainier:~/dev/sonic-swss/tests$ sudo pytest -s -vv --dvsname=vs test_nat.py
=========================================================================================== test session starts ============================================================================================
platform linux2 -- Python 2.7.17, pytest-4.6.9, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python
rootdir: /home/daall/dev/sonic-swss/tests
plugins: flaky-3.6.1
collected 10 items …
```

[dvs] Refactor NAT tests to use redis polling fixtures

---

orchagent/vnetorch.cpp

**What I did**
Vnet RIF interface must be deleted when interface delete happens and not when IP is removed. Logic is made same as VRF implementation

Don't remove RIF for Vnet interface when ip prefix is deleted

---

orchagent/portsorch.cpp
tests/test_sub_port_intf.py

Fix to https://github.com/Azure/sonic-buildimage/issues/4142
Add vs test on lag sub interface based on unconventional lag naming "PortChannel1.20" to fit the interface name within 15 characters
```
$ sudo pytest -s test_sub_port_intf.py::TestSubPortIntf --dvsname=vs
====================================================================== test session starts =======================================================================
platform linux2 -- Python 2.7.13, pytest-4.6.9, py-1.8.0, pluggy-0.13.1
rootdir: /data01/home/wendani/sonic-buildimage-201911/src/sonic-swss/tests
plugins: flaky-3.6.1
collected 5 items …
```

[sub intf] Use m_lag_id to be the parent port object id when parent port is LAG

---

orchagent/portsorch.cpp

**What I did**
Added the SAI buffer drop counters to the list of port stats to be polled.
To enable stats for MMU related drops.
Loaded the modified SWSS onto a physical DUT and verified that 1) the stat was added to the flex counter polling list and 2) that the flex counter had added the stat to the COUNTERS_DB for each port.

[portsorch] Enable port-level buffer drop counters

---

tests/conftest.py
tests/dvslib/dvs_database.py
tests/test_vlan.py

- Refactor tests to use polling interface
- Refactor redundant testing methods
- Reenable unstable tests
**What I did**
I refactored the VLAN tests to use the new library functions in dvslib.
I did it to stabilize the test suite and speed up the runtime of the VLAN tests.
Ran a batch of 20 tests locally, 20/20 passed (avg time ~65s).

[dvs] Refactor VLAN tests to use dvslib

---

tests/test_interface.py

**What I did**
Re-enabled most of the RIF tests.
Since we've narrowed down the issue to setting the MTU, we can skip the MTU tests while we implement the fix so that we can at least continue to verify the rest of the RIF behavior.
Local test runs

[dvs] Re-enable RIF tests

---

orchagent/portsorch.cpp

ref: https://lgtm.com/logs/17a00021acc56bf7a82ba4ade589d7c385cca8bb/lang:cpp
```
[2020-04-08 10:39:16] [build] g++ -DHAVE_CONFIG_H -I. -I.. -I .. -I ../warmrestart -I flex_counter -I debug_counter -g -DNDEBUG  -std=c++14 -Wall -fPIC -Wno-write-strings -I/usr/include/libnl3 -I/usr/include/swss -Werror -Wno-reorder -Wcast-align -Wcast-qual -Wconversion -Wdisabled-optimization -Wextra -Wfloat-equal -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wimport -Winit-self -Winvalid-pch -Wlong-long -Wmissing-field-initializers -Wmissing-format-attribute -Wno-aggregate-return -Wno-padded -Wno-switch-enum -Wno-unused-parameter -Wpacked -Wpointer-arith -Wredundant-decls -Wstack-protector -Wstrict-aliasing=3 -Wswitch -Wswitch-default -Wunreachable-code -Wunused -Wvariadic-macros …
```

const initializer_list is not a constant expression

---

orchagent/bufferorch.cpp

**What I did**
As per  SAI 1.5 made value of SAI_BUFFER_PROFILE_ATTR_BUFFER_SIZE  as uint64_t
Buffer size was getting corrupted and not programming ASIC Correctly.
Verified Manually in ASIC DB the value of the attribute is correct.

[bufferorch] Fixed SAI_BUFFER_PROFILE_ATTR_BUFFER_SIZE to uint64_t

---

cfgmgr/buffermgr.cpp

**What I did**
Do not set PG to Buffer profile mapping again if already exist.
This will avoid not to call SAI API
set_ingress_priority_group_attribute() if mapping already exist
Calling SAI API set_ingress_priority_group_attribute()  Multiples times result in Buffer getting reduced on Dell-6000
a) Load Minigraph
b) Config save
c) config reload
Made sure set of  PG to Buffer profile mapping is not done more than one time via syslog and checking buffer limit in SAI.

 Do not set PG to Buffer porfile mapping again if already exist.

---

orchagent/main.cpp

**What I did**
Added the new option [-i INST_ID] in orchagent to get the asic instance id passed by user and populate it in SAI_SWITCH_ATTR_SWITCH_HARDWARE_INFO during create_switch().
In multi-ASIC platforms the create_switch API should inform the syncd/SAI/SDK the particular ASIC instance to be initialized and controller by this orchagent.
Verified on a multi-ASIC and single ASIC devices the orchagent/syncd is up interfaces in good state. 
**Need additional change in the file sonic-buildimage/dockers/docker-orchagent/orchagent.sh to pass the instance ID with -i option.**

[Multi-AISC] Pass the asic instance as SAI attribute during switch_create 

---

orchagent/routeorch.cpp

**What I did**
Add handling route entries with abnormal field in RouteOrch.
a. empty "ifname", skip it and do nothing
b. empty "nexthop", fill ips with zeros to match ifnames
c. ip number < interface number, like b, append zeros to ips to match ifnames
d. ip number > interface number,  truncate ips to match ifnames
Ussually none of above would happen, while warmboot from old version b will happen, others only when writing app_db manully.
To fix the issue [sonic-buildimage#4399](https://github.com/Azure/sonic-buildimage/issues/4399)
test varies of route entries & vs test

[routeorch] Handle the empty "nexthop" field for backward compatibility

---

orchagent/vnetorch.cpp
orchagent/vnetorch.h

**What I did**
In BITMAP implementation, set MTU for the internal VNET bridge RIF to max value.
To make jumbo frames routed on BITMAP VNET interfaces. Currently if sending traffic from VNET to another VNI using a tunnel route then frames larger than 1500 are not routed and trapped to the CPU.
Executed ```vxlan_vnet``` ansible test with the modified MTU.
N/A

[vnet] Set MTU for the VNET bridge RIF in BITMAP implementation

---

tests/conftest.py
tests/dvslib/dvs_acl.py
tests/dvslib/dvs_database.py
tests/port_dpb.py
tests/test_acl.py
tests/test_port_dpb_acl.py

* DPB-ACL scale tests and code-review comments addressed
* Remove sleeps that were put earlier
Co-authored-by: Vasant <vapatil@linkedin.com>
**What I did**
Wrote DPB scale test cases
To catch any race conditions or corner cases
Ran VS test cases
```
vapatil@server09:~/workspace/DPB/sonic-buildimage/src/sonic-swss/tests$ sudo pytest --pdb -s -v --dvsname=vs-vp test_port_dpb_acl.py
======================================================================= test session starts ========================================================================
platform linux2 -- Python 2.7.15+, pytest-3.3.0, py-1.8.0, pluggy-0.6.0 -- /usr/bin/python
rootdir: /home/vapatil/workspace/DPB/sonic-buildimage/src/sonic-swss/tests, …
```

DPB-ACL scale tests (#30)

---

mclagsyncd/mclagsyncd.cpp

* use new DBConnector() in new added maclag codes
Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com

[MultiDB] fix wrong MultiDB APIs usage in mclags

---

portsyncd/portsyncd.cpp

Default select timeout was set to 1 ms, causing 3-5% CPU usage when
idles.
**What I did**
I changed default select timeout from 1ms to 1000ms.
portsyncd is causing 3-5% CPU usage when system idles.
Basic sanity verification on T0 topology

[portsyncd] fix default select timeout

---

cfgmgr/intfmgr.cpp
cfgmgr/intfmgr.h
orchagent/intfsorch.cpp
orchagent/intfsorch.h
orchagent/port.h
tests/test_vnet.py

**What I did**
Implemented ARP proxy feature.
Feature request according to HLD https://github.com/Azure/SONiC/blob/master/doc/arp/Proxy%20Arp.md.
- Verified that it is possible to enable and disable proxy ARP on non VNET interfaces
- Verified kernel configuration via ```proc``` FS
- Verified VLAN flood SAI configuration for VLAN RIF
- Verified that proxy ARP is enabled by default on VNET interfaces
- Verified that ARP packets are propagated correctly when proxy ARP is enabled 
N/A

[proxy_arp] Implement proxy ARP feature

---

cfgmgr/natmgr.cpp
orchagent/natorch.cpp
orchagent/portsorch.cpp

Fixing compilation issue in 32-bit arch(marvell-armhf)
**What I did**
Replaced %l variants with PRI.
Replaced %lu with %zu for size_t
fix for compilation issue in bit arch
compiled for 32 bit arch (marvell-armhf)

Using PRI instead of %l to support 32-bit arch

---

orchagent/aclorch.cpp
orchagent/aclorch.h
tests/test_mirror_ipv6_separate.py

**What I did**
I made it so that users can create MIRROR tables with ingress ACLs and MIRROR tables with egress ACLs at the same time (and similarly for MIRRORv6 tables).
Currently only one mirror table of each type is allowed in order to support the logic for reconciling combined v4/v6 mirror tables. However, we can differentiate based on ACL stage, keeping the reconciliation logic intact while allowing users to mirror with ingress and egress ACLs simultaneously (on devices that support this).
WIP. I've provided a new VS test case to check the behavior, I'm in the process of testing the changes on a DUT just to be safe.

[aclorch] Add support for creating ingress and egress MIRROR tables concurrently

---

orchagent/main.cpp

**What I did**
Set default MTU for the underlay loopback interface to ```9100``` in order to make it working with jumbo frames.
Underlay loopback is used for VxLAN tunnel and without setting MTU jumbo frames are trapped to CPU on ```decap``` flow. But they should be successfully decapsulated and routed to the appropriate destination.
* Configure VxLAN tunnel 
* Send encapsulated jumbo frame to switch port 1
* Verify that decapsulated jumbo frame is sent by switch from port 2
N/A

[orchagent] Set default MTU for the underlay loopback interface

---

tests/conftest.py

**What I did**
unmark fixture for create/remove_dpb_config_file
see issue
Fixture "create_dpb_config_file" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
check vstest

[vstest]: unmark fixture for create/remove_dpb_config_file

---

tests/test_vlan.py

**What I did**
Fixed LAG memeber test case and ran the VS test case to ensure it passes.
Test was expecting only two fields for LAG member where actual is 4
```
(('SAI_LAG_MEMBER_ATTR_LAG_ID', 'oid:0x20000000005c4'), ('SAI_LAG_MEMBER_ATTR_PORT_ID', 'oid:0x1000000000002'), ('SAI_LAG_MEMBER_ATTR_INGRESS_DISABLE', 'false'), ('SAI_LAG_MEMBER_ATTR_EGRESS_DISABLE', 'false'))
```
Test case was broken.
By running VS test case
```
test_vlan.py::TestVlan::test_AddPortChannelToVlan PASSED                                                                                                                                                                 [100%]
```

Fix LAG member test case

---

swssconfig/sample/00-copp.config.json

Updated the rate-limit value as per the "https://github.com/Azure/SONiC/blob/master/doc/nat/nat_design_spec.md"  in copp json file.
This PR is to address the issue - https://github.com/Azure/SONiC/issues/611

 Corrected the copp rule as per NAT HLD

---

orchagent/orch.cpp
orchagent/orch.h
orchagent/pfcwdorch.cpp

Remove references to hardcoded DB ID in swss as in a MultiDB, the DB Name
should always be used to accurately identify the connector's database role.
Signed-off-by: Rajendra Dendukuri <rajendra.dendukuri@broadcom.com>
**What I did**
Use database name as the key to match a database instead of DB ID. In a MultiDB environment,
the db ID can be changed in database_config.json
Modify default DB ID's in database_config.json
Swap APPL_DB and CONFIG_DB IDs in database_config.json and reboot. Ensure that switch comes
back up and ports are created.
Use database name instead of database ID

[MultiDB] Use database name instead of database ID

---

orchagent/portsorch.cpp

Reverts Azure/sonic-swss#1237
These counters are causing widespread issues in the master branch, so we're backing them out for now to be revisited in a later PR. They will likely need to be polled separately from the other counters, and on a longer interval, to avoid performance issues and conflicts.

Revert "[portsorch] Enable port-level buffer drop counters"

---

tests/test_warm_reboot.py

Signed-off-by: Sangita Maity <sangitamaity0211@gmail.com>
**What I did**
Modified the test_warm_reboot.py script to **stabilize the test case** and also, started using **swsscommon dbconnector** instead of **redis-cli** command in one of the functions.
To stabilize the test case. 
```
samaity@server09:~/REPO_FACTORY/GIT_REPO/vs_swss_test/sonic-buildimage/src/sonic-swss$ sudo pytest -v --dvsname=vs-sang tests/test_warm_reboot.py -k "test_system_warmreboot_neighbor_syncup"
============================================================================================================ test session starts =============================================================================================================
platform linux2 -- Python 2.7.15+, …
```

[dvs] Stabilize warm reboot neighbor syncup test

---

cfgmgr/natmgr.cpp
natsyncd/natsync.cpp
natsyncd/natsync.h
tests/test_nat.py

This PR fixes all NAT lgtm erros (https://github.com/Azure/sonic-buildimage/issues/4698)

Fixes for NAT lgtm alerts

---

portsyncd/linksync.cpp

**What I did**
add debug message if a port cannot be found in port able
to debug https://github.com/Azure/sonic-buildimage/issues/4821

[portsyncd]: add debug message if a port cannot be found in port able

---

doc/swss-schema.md
orchagent/qosorch.cpp
orchagent/qosorch.h

**What I did**
- Added shaping meter_type field to SCHEDULER_TABLE
- Added scheduler reference field to PORT_QOS_MAP table for port level shaping
Update the shaping feature to reflect the corresponding QoS scheduling and shaping design doc: - https://github.com/Azure/SONiC/pull/535
See test cases executed in the QoS scheduling and shaping design doc
Signed-off-by: Michael Li <michael.li@broadcom.com>

[qosorch] Update QoS scheduler params for shaping features

---

mclagsyncd/mclaglink.cpp

Compiler Warnings : cast increases required alignment of target type [-Wcast-align]
Fix: Use reintrepret cast to cast lower size pointer to bigger size
pointer types
Signed-off-by: Antony Rheneus <arheneus@marvell.com>
**What I did**

[sonic-swss] ARMHF warning fixes

---

orchagent/aclorch.cpp
orchagent/aclorch.h
tests/test_mirror_ipv6_separate.py

**What I did**
I updated the qualifiers we use internally for IP_PROTOCOL to IPV6_NEXT_HEADER for Mellanox SKUs.
IPV6_NEXT_HEADER *should* be used for MIRRORV6 and L3V6 across the board, but some SAI libraries do not implement this qualifier yet. We will push the other SAI vendors to implement this qualifier so we can transition to it moving forward.
The reason this is important to do now for Mellanox is that certain ACL rules will crash if they include the IP_PROTOCOL field.
1. Install new SWSS with this change
2. Confirm that ASIC DB shows IPV6_NEXT_HEADER as a MIRRORV6 table qualifier
3. Confirm that ASIC DB shows IPV6_NEXT_HEADER as a qualifier for rules with IP_PROTOCOL
4. Confirm that rules with …

[aclorch] Use IPv6 Next Header internally for protocol number on MLNX platform

---

cfgmgr/natmgr.cpp
cfgmgr/natmgr.h
cfgmgr/natmgrd.cpp
natsyncd/natsync.cpp
natsyncd/natsync.h
orchagent/natorch.cpp
orchagent/natorch.h
swssconfig/sample/00-copp.config.json
tests/test_nat.py

Approach:
1. All NAT conntrack entries would be updated with large timeout (432000) value initially (when entry is created) by sending notifcation from NatSync to NatMgr.
2. All NAT conntrack enrries would be updated with Zero timeout value (when entry is deleted) be sending notification from OA to NatMgr.
3. Added a 1 day timer in NatMgr to reset the timeout for all conntrack entries to large time (43200) value.
4. NatOrch caches the time in secs whenever the entry is active, and compares it with specific timeout for every 30 secs when entry is not active.
Code changes:
NatSync:
1. Added a new timeout notification producer to send notifications to NatMgr.
2. Send a notification (whenever a new entry to created) to NatMgr to set 43200 time for that conntrack entry.
NatMgr:
1. While …

 Update NAT conntrack entries from natmgr instead of natorch

---

tests/dvslib/dvs_database.py
tests/test_qos_map.py
tests/test_tunnel.py

explicitly conver the items to list instead of dict_items
**What I did**
explicitly conver the items to list instead of dict_items
dict_items cannot be converted to vector<std:pair<>> in c++
pytest

[vstest]: fix vstest for python3

---

orchagent/pfcwdorch.cpp

**What I did**
Avoid creating/binding AclTableGroup for platforms that do not use AclHandler logic in pfcwd
Install swss with the changes
Verified that createBindAclTableGroup() is called only on platforms that uses AclHandler logic when pfcwd is started on a port
--- on a platform using AclHandler logic ---
Jul 19 02:38:04.586515 str-7260cx3-acs-7 DEBUG swss#orchagent: :> initWdCounters: enter
Jul 19 02:38:04.586515 str-7260cx3-acs-7 DEBUG swss#orchagent: :> getQueueStats: enter
Jul 19 02:38:04.586515 str-7260cx3-acs-7 DEBUG swss#orchagent: :< getQueueStats: exit
Jul 19 02:38:04.586515 str-7260cx3-acs-7 DEBUG swss#orchagent: :< initWdCounters: exit
Jul 19 02:38:04.586515 str-7260cx3-acs-7 DEBUG swss#orchagent: :> …

[201911] Create AclTableGroup only for platforms using AclHandler logic in pfcwd

---

cfgmgr/natmgr.cpp
cfgmgr/natmgr.h
orchagent/natorch.cpp
orchagent/natorch.h
orchagent/orchdaemon.cpp
tests/test_nat.py

Code changes:
NatMgr:
1. Setting the "APP_NAT_DNAT_POOL_TABLE_NAME" table with destination-ip when first Static NAT/NAPT entry is added at config_db.
2. Incrementing the ref count in "m_natDnatPoolInfo" for same destination-ip for next Static NAT/NAPT entry is added at config_db.
3. Decrementing the reference count in "m_natDnatPoolInfo" for same destination-ip when Static NAT/NAPT entry is deleted at config_db.
4. Deleting the "APP_NAT_DNAT_POOL_TABLE_NAME" table with destination-ip when last Static NAT/NAPT entry is deleted at config_db.
5. It does the same for all IP-Addresses from pool-addresses range in NAT Pool configuration in config_db.
NatOrch:
1. Creating DNAT_POOL entries using nat_type as "SAI_NAT_TYPE_DESTINATION_NAT_POOL" when "APP_NAT_DNAT_POOL_TABLE_NAME" table is created. …

[201911] Update nat entries to use nat_type to support DNAT Pool changes.

---

tests/test_nat.py
tests/test_vrf.py
tests/test_warm_reboot.py

**Motivation**
I marked three tests that are consistently flaky as `xfail` so that they do not block PRs. Following up with the test authors to get them stabilized in the meantime.

[dvs] Mark unstable tests as xfail

---

tlm_teamd/main.cpp
tlm_teamd/teamdctl_mgr.cpp
tlm_teamd/teamdctl_mgr.h
tlm_teamd/values_store.cpp

**What I did**
1. I add a queue, to try add a LAG for up to 10 times. tlm_teamd will make 1 seconds between attempts while working on other tasks.
2. I found another bug: "tlm_teamd doesn't work properly when teamd doesn't have member ports registered for a LAG"
3. I made an enhancement to prevent spam syslog with libteamdctl internal log messages.
1. To fix first half of the reported bug: https://github.com/Azure/sonic-swss/issues/1346
2. To fix the bug which prevented tlm_teamd to update telemetry data for teamds.
3. To clean up syslog from libteamd internal messages.
Run command `sudo config portchannel add PortChannelTest`
Before the fix you can see following output in syslog:
```
Jul  8 19:29:14.466829 str-s6100-acs-1 WARNING teamd#tlm_teamd: …
```

[tlm_teamd]: Try to add LAG again, when teamd is not ready first time

---

orchagent/fdborch.cpp

Signed-off-by: Rajkumar Pennadam Ramamoorthy <rpennadamram@marvell.com>
**What I did**
Fixed Orchagent crash in FDB flush on port disable.
Steps to reproduce:
1) configure vlan and a port.
2) Learn MAC and populate FDB table.
3) Disable the port.
In fdborch.cpp:485, "m_entries" element is erased (from function "storeFdbEntryState") inside range based loop.
Iterators or references to erased element are invalidated. Hence update the iterator before removing the element.
Validate the above testcase with fix.
Logs:
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Core was generated by `/usr/bin/orchagent -d /var/log/swss -b 8192 -m 00:50:b6:50:51:51'.
Program terminated with signal SIGSEGV, Segmentation …

[fdborch] Fixed Orchagent crash in FDB flush on port disable.

---

gearsyncd/gearsyncd.cpp

* changes made to supervisord conf require gearsyncd to return 0 otherwise
restarts are performed, fail, and swss docker exits
* originally, gearsyncd did not exit, and if it did, 1 exit code was returned
to indicate failure. We converted this to do its job and exit, but did not
correct the exit code.
* prior state was not a problem until changes that are yet to merge for
sonic-buildimage supervisord conf made returning a 1 problematic.
**What I did**
change exit code for gearsyncd to 0 from 1
for compatibility with supervisord.conf. Not to mention, processes should return 0 on success.
Local build.
HLD is located at https://github.com/Azure/SONiC/blob/b817a12fd89520d3fd26bbc5897487928e7f6de7/doc/gearbox/gearbox_mgr_design.md
Signed-off-by: …

swss: gearsyncd should return 0 on exit

---

tests/conftest.py
tests/dvslib/dvs_acl.py
tests/test_acl.py
tests/test_mirror_port_span.py
tests/test_port_dpb_acl.py

- Add docstrings to dvs_acl
- Revert dvs_acl to a vanilla fixture
- Combine redundant dvs_acl methods
- Refactor test_acl, test_port_dpb_acl, and test_mirror_port_span to use new interface
**What I did/why I did it**
1. I changed `dvs_acl` back into an explicit fixture that is passed in to the test methods. The reason for this is because I figured out that tools like `pylint` and `flake8` do not handle the `request.cls...` update very well, which is going to be problematic very soon. In addition, this change makes it a little easier for new contributers/new `dvslib` adopters to see what is going on by making the inclusion of the `dvs_acl` module a little more explicit.
2. I merged a few methods together in `dvs_acl` that were checking the …

[dvs_acl] Refactor and document dvs_acl library

---

tests/conftest.py

- Enhance AsicDbValidator to be stricter
- Add a new SWSS ready-check to validate that orchagent is done processing ports
**What I did**
I added some additional ready-checks during the DVS initialization to ensure that the virtual switch is fully initialized before starting the tests.
We've noticed recently that a lot of tests are failing from the very first test case, even ones that we have gone through and stabilized in the past. We figured out by checking the logs that, even though orchagent was running, it was still busy processing the initial port config when the tests started running. Since most things in orchagent depend on portsorch initializing everything before they can proceed, nothing was ever written to ASIC …

[dvs] Validate that SWSS is ready to receive input before starting tests

---

orchagent/port_rates.lua
orchagent/rif_rates.lua

Fix 2 issues with the lua scripts:
- introduce separate INIT flag for PORT and RIF. Previously could cause problems on init of one of the groups.
- skip if there is no initial config (alpha in DB). When reboot/config reload, it happens that alpha is not set until the `enable_counters.py` is executed
**What I did**
reboot, config reload, 
check rates initialized correctly, w/o errors in log

[rates] fix issue with rates init

---

orchagent/aclorch.cpp
orchagent/aclorch.h
orchagent/orchdaemon.cpp
orchagent/routeorch.cpp
orchagent/routeorch.h
orchagent/switchorch.cpp
orchagent/switchorch.h
tests/mock_tests/aclorch_ut.cpp

**What I did**
Added Max Nexthopgroup/ECMP Count supported by device into State DB
as part of Switch Capability Table.
Since we are using SWITCH_CAPABILITY Table moved the setting of table
field from aclorch to switchorch via public function
so that in future this can used by any agent.
Motivation for adding this to StateDB was to make sure
we can query this value (n) from external test case and make sure
we add (n) number of ECMP Group successfully and (n+1) should fail
without termination of orchagent.
admin@str-s6000-on-2:~$ redis-cli -n 6
127.0.0.1:6379[6]> hgetall "SWITCH_CAPABILITY|switch"
1) "MIRROR"
2) "true"
3) "MIRRORV6"
4) "true"
5) "ACL_ACTIONS|INGRESS"
6) "PACKET_ACTION,MIRROR_INGRESS_ACTION"
7) "ACL_ACTIONS|EGRESS"
8) "PACKET_ACTION"
9) …

Added Max Nexthopgroup/ECMP Count supported by device into State DB.

---

tests/README.md
tests/conftest.py

**What I did**
I added a flag to limit the CPU usage of a DVS container.
I did it to try to set an expectation of how much CPU the DVS container /should/ be using, and to try to make the performance more deterministic b/w the PR runners and different peoples' local setups (without a limit Docker just uses as much as it can from the host).
Ran tests locally, still passing. Typical CPU usage was <1 core, but need to experiment/monitor more with the PR runner to see if that is sufficient.

[dvs] Add options to limit CPU usage

---

tests/test_speed.py

Signed-off-by: Sangita Maity sangitamaity0211@gmail.com
Co-authored-by: Vasant Patil <vapatil@linkedin.com>
**What I did**
Initialized the configured speed list by reading port speed from ASIC DB
[sonic-buildimage #3910 PR](https://github.com/Azure/sonic-buildimage/pull/3910) has a dependency on it. 
Otherwise `test_speed` test is getting failed and other few test cases are dependent on it.
```
23:21:21  test_speed.py::TestSpeedSet::test_SpeedAndBufferSet FAILED  
```
Since Speed is introduced in port_config.ini of VS platform, one of the buffer profiles is already created(speed 40G). Hence the test case is modified by reading port speed from ASIC DB. The list of speeds is [10G, 25G, 40G, 50G, 100G], the initial number of buffer profiles present is 4 (including the one …

Get initial speed from ASIC DB 

---

cfgmgr/vlanmgr.cpp

The bridge created for vlans has a a default MTU of 1500 which is
serving as default for vlans added to the bridge. This PR changes
the default MTU to 9100 to be inline with portchannels and other
interfaces.
signed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>
**What I did**
Change the default mtu size of the host bridge interface
Adding support for jumbo frames
building an image with the change and could see Vlan100 having mtu set as 9100
```
admin@str-s6000-acs-14:~$ sudo ifconfig Vlan1000
Vlan1000: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9100
inet 192.168.0.1  netmask 255.255.248.0  broadcast 192.168.7.255
inet6 fe80::f68e:38ff:fe16:bc8d  prefixlen 64  scopeid 0x20<link>
ether f4:8e:38:16:bc:8d  txqueuelen 1000  (Ethernet)
RX packets 0 …
```

[vlanmgr] Support Jumbo Frame By Default

---

fpmsyncd/routesync.cpp
tests/test_vnet.py

**What I did**
Ignore IPv6 link-local and multicast entries as Vnet routes
Otherwise creating stale VNET route entries and displayed in "show vnet routes" command
Run in DUT

Ignore IPv6 link-local entries as Vnet routes

---

orchagent/portsorch.cpp

Signed-off-by: Vadym Hlushko <vadymh@mellanox.com>
**What I did**
Added logic that put port down before applying FEC configuration, like in the case with speed change
Because if we don't put port down FEC changes will not apply
_On the fanaout side:_
1. Put port down
2. Change FEC
3. Put port up
_On the switch side:_
1. Change FEC
2. Verify FEC state by using SDK script (in syncd docker)

[fec] added logic that put port down before applying fec onfiguration

---

orchagent/portsorch.cpp

**What I did**
I added a line to fetch the FEC mode from the map before setting it.
This check was missed in an earlier PR, causing tests to fail in sairedis like so: https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/sonic-sairedis-build/1196/testReport/junit/test_port/TestPort/test_PortFec/
Re-run VS tests with this change.
We're not totally sure why this was caught in the sairedis PR tests and not the swss PR tests. Investigation ongoing.

[fec] Get FEC mode when port is already admin down

---

cfgmgr/intfmgr.cpp

[intfmgr] Fix OA crash issue due to link local configurations
This should be backported to 201811 and 201911.
**What I did**
Fix OA crash issue due to link local configurations. 
In this PR, it will not send the link local configurations towards AppDB as it was configured on HW by default.
In case we have ipv6 link local configuration in configDB, it will crash OA.
**configuration:**
```
"VLAN_INTERFACE": {
"Vlan100|10.11.10.1/26": {
"family": "IPv4", 
"scope": "global"
}, 
"Vlan100|2000:11:10::1/64": {
"family": "IPv6", 
"scope": "global"
}, 
"Vlan100|fe80::1/10": {
"family": "IPv6", 
"scope": "local"
}, 
"Vlan777|10.11.77.1/26": {
"family": "IPv4", 
"scope": "global"
}, 
"Vlan777|2000:11:77::1/64": { …
```

[intfmgr] Fix OA crash issue due to link local configurations

---

orchagent/mirrororch.cpp
tests/conftest.py
tests/dvslib/dvs_mirror.py
tests/test_mirror_port_erspan.py

What I did:
Fix the issue of field "next_hop_ip" not getting updated in state DB
Table: MIRROR_SESSION_TABLE when mirror destination ip next hop changes
for ERSPAN Mirror.
Also fixed divs_mirror library to use wait_for_field_match instead wait_for_entry
when comparing expected value for ASIC and State Db Table.
How I Verify:
Updated ERSPAN DVS test case to check next_hop_ip in state db.
Also test case is enhanced to see if route change in propagated correctly
to state and asic db.

[sonic-swsss] Fix the issue of field "next_hop_ip" not getting updated in state DB in ERSPAN Mirror

---

tests/conftest.py

**What I did/why I did it**
While testing https://github.com/Azure/sonic-buildimage/pull/5192 we figured out that the port config that is generated from `port_config.ini` does not include any information about the admin status of the ports on the virtual switch.
However, with this PR, ports are set to `DOWN` by default in the DVS. This causes the connectivity checks in `test_virtual_chassis.py` to fail indefinitely.
This PR ensures that the necessary ports in the chassis are admin UP so that pings can be sent from the LC instances to the neighboring servers.
I kept mixing up which interface was which while working on this PR, so I also refactored some of the variable names to be more descriptive.
Ran the chassis tests …

[dvs/chassis] Bring up SONiC interfaces in virtual chassis

---

cfgmgr/intfmgr.cpp
cfgmgr/intfmgr.h

Issue  (https://github.com/Azure/sonic-swss/issues/1311) :
Add Loopback interface to NAT zone 1
sudo config nat add interface Loopback0 -nat_zone 1
Seeing below error logs when NAT zone for Loopback changed to 1.
Apr 21 11:44:33.805637 cab18-3-dut INFO swss#supervisord: intfmgrd RTNETLINK answers: File exists
Apr 21 11:44:33.805637 cab18-3-dut ERR swss#intfmgrd: :- exec: /sbin/ip link add Loopback0 mtu 65536 type dummy && /sbin/ip link set Loopback0 up: Success
Apr 21 11:44:33.805637 cab18-3-dut ERR swss#intfmgrd: :- addLoopbackIntf: Command '/sbin/ip link add Loopback0 mtu 65536 type dummy && /sbin/ip link set Loopback0 up' failed with rc 512
Root cause for logs:
Whenever the ip address is assigned to Loopback1 using below command, "ip link" gets added for Loopback1 like shown below …

Avoid adding loopback interface (ip link add) when setting nat zone on loopback interface

---

tests/README.md

**What I did**
I added some notes to the README and a table of contents.
I added the notes in response to recent feedback and questions I got from different community members who had tried out the new instructions.
I also added the table of contents as it is useful to be able to be able to jump around (especially if you already have the DVS set up and you just want to read about the options).
N/A
N/A

[dvs] Add new common issues and TOC to DVS README

---

tests/test_nat.py
tests/test_port_dpb.py

- Re-enable test_port_dpb
- Add polling to NAT
**What I did**
I re-enabled the DPB test because it is now passing consistently and I added a skip to the NAT test because it is broken.
To un-block two tests that have been removed from the test suite for an extended period of time.
Ran both locally x10.
Fixes #1222

[dvs] Fix unstable DPB and NAT test cases

---

cfgmgr/portmgr.cpp

Delete port alias from portList set in portmgr. So that when the por is re-created we can identify it as new configuration and set the default MTU.
**What I did**
Remove port from portList in portmgrd on deleting a port
If we did NOT, when we re-create the port, it wont be considered as new port, and some of the default initializations wont happend
As we were observing that MTU was NOT being set correctly on re-creating port, we fixed the issue and verified.
```
admin@lnos:~$ show int status Ethernet0
Interface        Lanes    Speed    MTU    Alias    Vlan    Oper    Admin    Type    Asym PFC
Ethernet0  65,66,67,68     100G   9100   Eth1/1   trunk    down       up     N/A         N/A
admin@lnos:~$ sudo config interface breakout …
```

[Portmgrd]: Remove deleted port from portList

---

tests/test_nat.py

This PR is to address the issue https://github.com/Azure/sonic-swss/issues/1409.

[dvs/NAT] Fix for test_VerifyConntrackTimeoutForNatEntry test case

---

tests/test_port_dpb.py
tests/test_port_dpb_acl.py
tests/test_port_dpb_vlan.py

There is a known regression in the VS docker image that is impacting the DPB tests (buildimage#5263). While this is being fixed, we will xfail this set of tests so that 1) the PRs are not blocked and 2) so we can continue to run the tests and verify that the fix is complete.
https://github.com/Azure/sonic-buildimage/issues/5263

[dvs] Mark DPB tests as xfail

---

orchagent/dtelorch.h

Initialize uninitialized member in DTelQueueReportEntry, which
cause compilation error when build with compilation flag
-Werror=maybe-uninitialized.
Signed-off-by: Icarus Chau <icarus.chau@broadcom.com>
**What I did**

[dtel] Initialize uninitialized member in DTelQueueReportEntry

---

orchagent/vnetorch.cpp
orchagent/vnetorch.h

**What I did**
Provided logic to create "full mask" routes with highest priority.
To fix VNET route priority issue in order to support flow when some IPs from the subnet are defined by another route (nexthop tunnel) .
* Create VxLAN tunnel
* Create VNET
* Create VNET interface (```192.168.1.1/24```)
* Create neighbor for VNET interface (```192.168.1.2```)
* Create VNET tunnel route for the host from the local subnet (```192.168.1.10/32 via tunnel```)
* Send TCP packet to the switch with destination IP equal to ```192.168.1.2```
* Verify packet was routed correctly and received on the neighbor host
* Send TCP packet to the switch with destination IP equal to ```192.168.1.10```
* Verify that …

[bitmap_vnet] Fix VNET route priority issue

---

cfgmgr/teammgrd.cpp
teamsyncd/teamsyncd.cpp

**What I did**
When SIGTERM is received, gracefully exist teamsyncd and teammgrd after cleaning up teamd processes and resources.
Below errors are after config reload
1. portchannel interfaces in kernel were not cleaned up.
2. teamsyncd gets netlink messages with old ifIndex.
3. Error - "TeamPortSync: Failed to initialize team handler".
I did multiple config reloads and docker stop teamd. 
Verified all portchannel intf are cleaned up in kernel and all teamd processes exists cleanly.

[teamsyncd][teammgrd] Graceful exit after receiving SIGTERM

---

cfgmgr/sflowmgr.cpp

**What I did**
Fixed SFLOW handling in the DEL path. Below issues reported
https://github.com/Azure/sonic-swss/pull/1012#discussion_r479609637
https://github.com/Azure/sonic-swss/pull/1012#discussion_r479610706
Fixed the DEL sequence in the handling of sflow global and sflow interface all commands
1) Perform config sflow interface level command
Execute redis-cli -n 4 del "SFLOW|global"
The above command should remove the local level entry along with global entries. (Earlier local interface level entries are not removed)
2) sudo config sflow interface disable all
redis-cli -n 4 del "SFLOW|global"
redis-cli -n 4 del "SFLOW_SESSION|all"
redis-cli -n 0 keys *SFLOW*
(empty array)
(Earlier the above command was listing all the entries)
**Details if …

Sflow fixes during DEL processing

---

tests/conftest.py
tests/dvslib/dvs_acl.py
tests/dvslib/dvs_database.py
tests/test_acl.py
tests/test_acl_ctrl.py
tests/test_acl_egress_table.py

**What I did**
Refactored `acl_cntrl` and `acl_egress` to use `dvslib`.
Both test files were huge and contained a lot of duplicate code that has since been added to `dvs_acl`.
Re-ran tests locally.
`acl_mclag` and `acl_portchannel` are a little trickier to refactor as 1) all of the ACL code is currently hard-coded to assume physical ports only and 2) `dvs_acl` doesn't really touch app DB at all. These will both require broader changes to be onboarded to `dvslib`, so better left for another PR.
Additionally, all of the `MIRROR` table tests are also huge, so those are being saved for another PR.

[dvs] Refactor acl_ctrl and acl_egress to use dvslib

---

orchagent/orch.cpp

Signed-off-by: tengfei <tengfei@asterfusion.com>
**What I did**
Fix the logic of judging malformed reference. Change 'if ((ref_in[0] != ref_start) && (ref_in[ref_in.size()-1] != ref_end))' to 'if ((ref_in[0] != ref_start) || (ref_in[ref_in.size()-1] != ref_end))'
The reference must be surrounded by [ ], so the relationship of 'ref_in[0] != ref_start' and 'ref_in[ref_in.size()-1] != ref_end' should be 'OR'
I load a wrong format qos map configuration , such as:
"PORT_QOS_MAP": {
"Ethernet0": {
"dscp_to_tc_map": "[DSCP_TO_TC_MAP:default", 
}
And verify if orchagent can make error log

[orch] Fix the logic of judging malformed reference

---

teamsyncd/teamsync.cpp

The current `apply_temp_view` logic doesn't handle MTU configuration during warm-reboot:
Before warm-reboot:
```
root@sonic:/home/admin# redis-cli -n 0 HGETALL 'LAG_TABLE:PortChannel0001'
1) "admin_status"
2) "up"
3) "oper_status"
4) "up"
5) "mtu"
6) "9100"
```
After warm-reboot:
```
root@sonic:/home/admin# redis-cli -n 0 HGETALL 'LAG_TABLE:PortChannel0001'
1) "admin_status"
2) "up"
3) "oper_status"
4) "up"
```
Apply state logs:
```
Aug 31 09:46:37.787959 sonic NOTICE teamd#teamsyncd: :- applyState: Applying state
Aug 31 09:46:37.789065 sonic NOTICE teamd#teamsyncd: :- dump: getting took 0.000322 sec
Aug 31 09:46:37.789065 sonic INFO teamd#teamsyncd: :- apply_temp_view: View switch of table LAG_TABLE required.
Aug 31 09:46:37.789065 …
```

[teamsyncd]: Fix LAG add: write MTU configuration

---

orchagent/bufferorch.cpp

**What I did**
Skip create-only fields when modify buffer pool or profile in orchagent
This PR also fixes the issue [dynamic_th failed because redis sends unchanged field to orchagent when updating dynamic_th #3971](https://github.com/Azure/sonic-buildimage/issues/3971)

Fix #3971 by skipping create-only SAI attributes when modifying buffer pools or profiles in orchagent

---

cfgmgr/intfmgr.cpp
cfgmgr/intfmgr.h

This is a clone for the PR https://github.com/Azure/sonic-swss/pull/1411
Issue (#1311) :
Add Loopback interface to NAT zone 1
sudo config nat add interface Loopback0 -nat_zone 1
Seeing below error logs when NAT zone for Loopback changed to 1.
Apr 21 11:44:33.805637 cab18-3-dut INFO swss#supervisord: intfmgrd RTNETLINK answers: File exists
Apr 21 11:44:33.805637 cab18-3-dut ERR swss#intfmgrd: :- exec: /sbin/ip link add Loopback0 mtu 65536 type dummy && /sbin/ip link set Loopback0 up: Success
Apr 21 11:44:33.805637 cab18-3-dut ERR swss#intfmgrd: :- addLoopbackIntf: Command '/sbin/ip link add Loopback0 mtu 65536 type dummy && /sbin/ip link set Loopback0 up' failed with rc 512
Root cause for logs:
Whenever the ip address is assigned to Loopback1 using below command, "ip link" gets added for …

[201911] Avoid adding loopback interface (ip link add) when setting nat zone on loopback interface

---

mclagsyncd/mclaglink.cpp
mclagsyncd/mclaglink.h
mclagsyncd/mclagsyncd.cpp
orchagent/bufferorch.cpp
orchagent/bufferorch.h
orchagent/countercheckorch.cpp
orchagent/pfcwdorch.cpp
orchagent/pfcwdorch.h
orchagent/portsorch.cpp

After this PR: https://github.com/Azure/sonic-swss-common/pull/382
After this PR: https://github.com/Azure/sonic-sairedis/pull/660
*Please move submodules together to include above commits*

Replace RedisClient with DBConnector

---

orchagent/bufferorch.cpp

**What I did**
Fix issue: bufferorch only pass the first attribute to sai when setting attributes for BUFFER_POOL and BUFFER_PROFILE object. 

[bufferorch] Fix issue: bufferorch only pass the first attribute to sai when setting attributes

---

orchagent/aclorch.cpp
tests/mock_tests/aclorch_ut.cpp

**What I did**
I removed ethertype from the qset for L3V6 tables.
This change was already done for MIRRORV6 tables a while back. ETHER_TYPE is unnecessary for V6 tables as the ethertype should always be the same (86DD) for IPv6 traffic. Additionally, this qualifier breaks IPv6 support on some platforms (e.g. Mellanox).
1. Update C++ unit tests
2. Test table behavior on BRCM and MLNX devices

[acl] Remove Ethertype from L3V6 qualifiers

---

orchagent/debugcounterorch.cpp

**What I did**
I updated the logging messages in debugcounterorch to:
1) Clearly display that drop reasons have been added to counters if they haven't been created yet.
2) Differentiate between counter creation and free counter reconciliation
Fixes https://github.com/Azure/sonic-buildimage/issues/4434
Create counter from the CLI and verify that all drop reasons are shown in the syslog and that there is a "counter created" and a "counter matched" message.

[drop counters] Clarify log messages for initial counter setup

---

orchagent/Makefile.am
tests/mock_tests/Makefile.am

libzmq is required since orchagent will compile against libsairedis

Add libzmq to Makefiles

---

orchagent/fdborch.cpp

**What I did**
1. Use .clear() on a vector after using std::move() from it to make sure that the vector is in a correct state.
2. Remove the if condition which is not required here.
1. std::move() from an object leaves the object in correct state. The correct state could be not empty. So I clear the vector to make sure that the vector is empty.
2. We don't need to check the vector on the emptiness. The for loop will do nothing, if there is no elements in the vector.
Make a draft PR and wait to make sure that there is no regression.

Use .clear() after std::move()

---

cfgmgr/teammgr.cpp
cfgmgr/teammgr.h
cfgmgr/teammgrd.cpp

Why I did:
The Netdevice created by teamd process not getting clean when Teamd feature/docker/service is disabled/stop
as observed  and  fixed by 2PR's -
https://github.com/Azure/sonic-swss/pull/1159
https://github.com/Azure/sonic-swss/pull/1407
is still being observed on Multi-asic platforms consistently and also on KVM VS testbed ( it is not consistent but happens every few runs (https://github.com/Azure/sonic-buildimage/issues/5432)
Issue seems to be timing issue where
SIGTERM (generated by docker stop) and  send via kill() of teammgrd to teamd was not cleaning
all teamd process netdevice resources.
How I did:
So fix is Instead  of sending explicit SIGTERM via kill() system call to teamd we are calling
teamd -k. Using this teamd itself generate SIGTERM …

Some of Netdevice created by teamd are not cleaned up when teamd service is disabled.

---

orchagent/request_parser.cpp
tests/request_parser_ut.cpp

**What I did**
Add support for parsing IPv6 key items in request parser when the key separator is `:` (e.g. in AppDB). Note: if a key contains an IPv6 address/prefix, it must be the last item in the key to be properly parsed.
Some components that use the request parser are being updated to support IPv6 key items (notably VnetOrch). These components also communicate with AppDB, which uses `:` as the delimiter for key items. Since IPv6 addresses are also separated with `:`, the original parsing logic will fragment an IPv6 address into multiple key items.
Added unit tests to verify correct parsing behavior for the following key formats:
* `<string>:<valid ipv6 address or prefix>`
* `<string>:<invalid ipv6 address or prefix>` (an exception should be …

Add IPv6 key item support to request parser

---

tests/test_portchannel.py

As per https://github.com/Azure/sonic-swss/pull/1030#discussion_r496319518
**What I did**
test_port.py test failure if follows test_portchannel.py using persistent vs container
```
$ sudo pytest -v --dvsname=vs -s test_portchannel.py 
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.13, pytest-4.6.9, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python2
rootdir: /home/wendani/sonic-buildimage-201911/src/sonic-swss/tests
collected 2 items …
```

[vs test bug fix] Restore eth0 up in post-test clean up

---

orchagent/Makefile.am
orchagent/fgnhgorch.cpp
orchagent/fgnhgorch.h
orchagent/neighorch.cpp
orchagent/orchdaemon.cpp
orchagent/routeorch.cpp
orchagent/routeorch.h
tests/mock_tests/Makefile.am
tests/mock_tests/aclorch_ut.cpp
tests/mock_tests/mock_orchagent_main.h
tests/test_fgnhg.py

**What I did**
Added fine grained ECMP changes.
To support consistent and layered hashing in SONiC.
Verified using VS swss test cases
HLD: https://github.com/Azure/SONiC/blob/master/doc/ecmp/fine_grained_next_hop_hld.md
SAI: https://github.com/opencomputeproject/SAI/blob/master/doc/ECMP/Ordered_and_Fine_Grained_ECMP.md

[fgnhgorch] Changes for Fine Grained ECMP

---

orchagent/fdborch.h
orchagent/portsorch.cpp
orchagent/portsorch.h

**What I did**
To fix an issue when removing bridgeport, I introduced code to remove FDB entries of the bridgeport before calling SAI API remove BridgePort.
I introduced this fix because by directly removing the bridgeport without flushing the bridge port's FDB entries, the bridge port removal was failing, since it had uncleaned ASIC DB FDB entries.
I verified it by sending traffic to the vlan port and creating a FDB entry for the vlan port. By, then when I remove the bridge port member from the VLAN port, the FDB entry was removed as well as bridge port is removed from VLAN membership.
The fix is introduced in PortsOrch.cpp

remove FDB entires of BridgePort before removing the BridgePort

---

orchagent/debug_counter/drop_counter.cpp

**What I did**
Check for string length before calling sustring with a specific length.
For unsupported DROP counters the string returned is the enum value as a string, whose max length is 2. 
Calling a substring with a length greater than 2 was crashing syncd.
Verified syncd doesn't crash after the fix.
Oct  1 16:07:39.387872 str-s6000-acs-9 INFO swss#supervisord: orchagent terminate called after throwing an instance of 'std::out_of_range'
Oct  1 16:07:39.387872 str-s6000-acs-9 INFO swss#supervisord: orchagent   what():  basic_string::substr: __pos (which is 19) > this->size() (which is 2)

[syncd][Drop Counters] Check for string length before calling substr

---

orchagent/portsorch.cpp
orchagent/portsorch.h

This PR provides a fix for the next situation:
Suppose switch was configured with a LAG of two members.
The min links was set to one. The traffic is running and everything is ok.
One of the LAG members was set to down. The LAG is still operational.
Then warm-reboot was issued. The NOS loads a new kernel and starts DB recovery.
At this point a LAG members will be configured with the default forwarding state - allowed.
This will cause a short traffic disruption.
Sample logs:
```
Sep 17 14:26:55.109000 sonic NOTICE swss#orchagent: :- addLagMember: Add member Ethernet16 to LAG PortChannel0001 lid:20000000005de pid:100000000056f
Sep 17 14:26:55.112803 sonic NOTICE swss#orchagent: :- setCollectionOnLagMember: Enable collection on LAG member …
```

[portsorch]: Set proper initial forwarding state for LAG member

---

tests/mock_tests/mock_dbconnector.cpp

**What I did**
I updated the MockDBConnector class to respect the access-level of the m_conn member variable.
https://github.com/Azure/sonic-swss-common/pull/387 refactored the DBConnector class and changed the access level of a few member fields. So, to make the mock implementation correct, we need to use the proper setter method to update the redis connection.
Built locally w/ latest sairedis and swsscommon changes.
This should fix the following jenkins issue:
https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/sonic-sairedis-build/1344/console
Which will in turn fix this issue:
https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/sonic-swss-build/1944/console

[mock tests] Update MockDBConnector to match new swsscommon interface

---

orchagent/bufferorch.cpp
orchagent/bufferorch.h
orchagent/orch.cpp
orchagent/orch.h
orchagent/qosorch.cpp
orchagent/watermarkorch.cpp
orchagent/watermarkorch.h

**What I did**
The issue is caused by the orchagent receiving notification in a different order in which they were sent.
orchagent doesn't have any dependency check and try notifying sai-redis to release an object which is still being referenced,
which causes sai-redis to complain and the object leaks.
The idea is to introduce a mechanism to identify the dependency thus preventing a referenced object from being released.
1. Introduce a new type representing the dependency among the variant type of objects, including the following fields:
- m_objsDependingOnMe, a set representing the objects that reference the current object.
- m_objsReferencingByMe, a map from a field of the current object's to the …

Fix issue #5157 by identifying the dependency among objects and avoiding releasing an object still being referenced

---

orchagent/aclorch.cpp
orchagent/aclorch.h
orchagent/portsorch.cpp
orchagent/portsorch.h

**What I did**
I moved getAclBindPortId from portsorch to aclorch.
This serves two purposes:
1. There was a bug wherein AclTable::update would fail to handle port deletion events because the getAclBindPortId method lived in portsorch. Because this method was using the provided alias to get the OID internally, this method would fail in the delete case because the port had already been deleted from portsorch. As a result, all delete events would fail and print a "Unable to retrieve OID" method. This was caught by the `test_po_update` pytest because it deletes the PortChannel at the end of the test case, which triggers a delete event, which triggers this bug.
2. The behavior implemented in this method is specific to the ACL …

[acl] Refactor port OID retrieval into aclorch

---

orchagent/aclorch.cpp
tests/mock_tests/aclorch_ut.cpp
tests/test_acl.py
tests/test_mirror_ipv6_combined.py
tests/test_mirror_ipv6_separate.py

- Update qualifiers for all platforms
- Fix C++ unit tests
- Add new VS test cases
**What I did**
I updated aclorch to use NEXT_HEADER rather than IP_PROTOCOL for all IPv6 ACL tables.
The 202012 release will still allow users to specify IP_PROTOCOL in config DB, but it will use the new SAI attributes under the hood and print a deprecation warning to the logs.
Fixes https://github.com/Azure/sonic-buildimage/issues/4570
Fixes https://github.com/Azure/sonic-swss/issues/1316
Added new test cases and updated the old VS/C++ unit test cases. Change looks good on physical devices as well.

[acl] Replace IP_PROTOCOL with NEXT_HEADER for IPv6 ACL tables

---

cfgmgr/vlanmgr.cpp

**What I did**
Set the dot1q_bridge MAC address to gMacaddress instead of random MAC address.
The dot1q_bridge is created without setting mac_address now, when we execute reboot or reload, the mac_address will be set to different random mac_address. 
```
admin@leaf-229:~$ ip link show Bridge
14: Bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
link/ether 5a:15:aa:19:17:22 brd ff:ff:ff:ff:ff:ff
admin@leaf-229:~$ sudo config reload -y
admin@leaf-229:~$ ip link show Bridge
175: Bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
link/ether aa:f7:76:39:c2:d3 brd ff:ff:ff:ff:ff:ff
```
reload and see the mac_address of Bridge
**Details …

[vlanmgr] Set the dot1q_bridge MAC address to gMacaddress instead of random MAC address.

---

cfgmgr/vlanmgr.cpp
cfgmgr/vlanmgr.h
orchagent/intfsorch.cpp
orchagent/intfsorch.h
orchagent/port.h
orchagent/portsorch.cpp

**What I did**
Use vlan-mac if specified in Config DB Vlan table
```
"VLAN": {
"Vlan1000": {
"mac": "00:00:11:22:33:44",
"vlanid": "1000"
}
},
```
Test:
```
$ ip addr show Vlan1000
172: Vlan1000@Bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9100 qdisc noqueue state UP group default qlen 1000
link/ether 00:00:aa:22:33:44 brd ff:ff:ff:ff:ff:ff
$ redis-cli -n 4 hmset "VLAN|Vlan1000" mac 00:00:11:22:33:44
$ ip addr show Vlan1000
172: Vlan1000@Bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9100 qdisc noqueue state UP group default qlen 1000
link/ether 00:00:11:22:33:44 brd ff:ff:ff:ff:ff:ff
inet 192.168.0.1/21 brd 192.168.7.255 scope global Vlan1000
```

Use vlan-mac for Vlan interfaces if specified in VLAN table

---

doc/Configuration.md

* Update Configuration.md with SCHEDULER_TABLE and PORT_QOS_MAP
* Refer to corresponding design document for more details: https://github.com/Azure/SONiC/pull/535

Update Configuration.md with SCHEDULER_TABLE and PORT_QOS_MAP

---

tlm_teamd/teamdctl_mgr.cpp

Fixes: https://github.com/Azure/sonic-buildimage/issues/5306
**What I did**
Force tlm_teamd to connect to teamd using usock method only.
Previously libteamdctl had only one method enabled: "usock". After we introduced zmq inside of our sonic-slave, libteamdctl is being build with two teamd connection method enabled: "usock" and "zmq", Autoselect crashes because we need to put a [connection string](https://github.com/jpirko/libteam/blob/master/libteamdctl/libteamdctl.c#L286) for zmq method.
1. Check that tlm_teamd is working
```
admin@str-s6100-acs-1:~$ ps ax | grep tlm
2961 pts/0    Sl     0:00 /usr/bin/tlm_teamd
4902 pts/0    S+     0:00 grep tlm
```
2, Issue command `sudo config portchannel add PortChannel0010`
3. Check that tlm_teamd is still …

[tlm_teamd]: Force tlm_teamd to connect using usock method only

---

orchagent/intfsorch.cpp

**What I did**
Init proxy_arp variable while adding router interface.
Proxy ARP will be considered as enabled while dealing with deletion action in void IntfsOrch::doTask(Consumer &consumer) if you never enable it.
Add an router interface and then delete it. 

[intfsorch] Init proxy_arp variable while adding router interface.

---

cfgmgr/natmgr.cpp
cfgmgr/natmgr.h
orchagent/natorch.cpp
orchagent/natorch.h
orchagent/orchdaemon.cpp
tests/test_nat.py

Code changes:
NatMgr:
Setting the "APP_NAT_DNAT_POOL_TABLE_NAME" table with destination-ip when first Static NAT/NAPT entry is added at config_db.
Incrementing the ref count in "m_natDnatPoolInfo" for same destination-ip for next Static NAT/NAPT entry is added at config_db.
Decrementing the reference count in "m_natDnatPoolInfo" for same destination-ip when Static NAT/NAPT entry is deleted at config_db.
Deleting the "APP_NAT_DNAT_POOL_TABLE_NAME" table with destination-ip when last Static NAT/NAPT entry is deleted at config_db.
It does the same for all IP-Addresses from pool-addresses range in NAT Pool configuration in config_db.
NatOrch:
Creating DNAT_POOL entries using nat_type as "SAI_NAT_TYPE_DESTINATION_NAT_POOL" when "APP_NAT_DNAT_POOL_TABLE_NAME" table is created.
Deleting …

Update nat entries to use nat_type to support DNAT Pool changes.

---

orchagent/neighorch.cpp

**What I did**
Remove unfinished DEL operation after SET operation for the same key in neighbor orch.
Since DEL operation is supposed to be executed before SET for the same neighbor [ref: #1184 ],  a remaining DEL after the SET operation means the DEL operation failed previously and should not be executed anymore. The remaining DEL operation will be kept for retrying and block following warm-reboot.
Verified on kvm.
Log messages in the presence of failed  DEL operation
```
Oct 26 22:23:15.259851 vlab-01 INFO swss#orchagent: :- removeNeighbor: Failed to remove still referenced neighbor 26:74:37:ff:3b:fa on PortChannel0004
Oct 26 22:23:15.260014 vlab-01 NOTICE swss#orchagent: :- doTask: Removed unfinished DEL operation for …
```

[neighorch] Remove pending DEL operation after SET operation for the same key

---

orchagent/aclorch.cpp
tests/mock_tests/aclorch_ut.cpp
tests/test_acl.py

**What I did**
I updated the AclOrch to correctly report using LAG bindings.
Fixes the issue described here: https://github.com/Azure/sonic-utilities/pull/1178
Tested on a DUT locally. ~**THIS STILL NEEDS VS TESTS AS WELL.**~
~In draft while I finish the VS tests.~

[acl] Update CRM to include LAG bindings for ACL tables

---

orchagent/vnetorch.cpp

**What I did**
There was a bug that accessed nullpointer, if a vnet config is pushed and it already exist.  This is to check if vnet exists before creating tunnel map
Fix issue https://github.com/Azure/sonic-buildimage/issues/5706

Create vnet tunnel map only if it doesn't exist

---

tlm_teamd/teamdctl_mgr.cpp

Fixes: https://github.com/Azure/sonic-buildimage/issues/5755
Fixes: https://github.com/Azure/sonic-buildimage/issues/5433
**What I did**
Make the destination for std::transform() to use std::back_inserter() for allocating new space for the copied objects
To fix a bug which causes a segfault.
-  Manually
```
admin@str-s6100-acs-1:~$ sudo config portchannel add PortChannel0040      
admin@str-s6100-acs-1:~$ sudo config portchannel add PortChannel00E0
admin@str-s6100-acs-1:~$ sudo config portchannel add PortChannel00EB
admin@str-s6100-acs-1:~$ sudo config portchannel add PortChannel00EC
admin@str-s6100-acs-1:~$ sudo config portchannel add PortChannel00E5
admin@str-s6100-acs-1:~$ sudo config portchannel add PortChannel00E6
admin@str-s6100-acs-1:~$ sudo …
```

[tlm_teamd]: Fix segfault, when retrying to do teamd_connect() again

---

orchagent/portsorch.cpp
orchagent/portsorch.h
tests/test_portchannel.py
tests/test_sub_port_intf.py

**What I did**
Sub interface inherits mtu from parent physical port or port channel according to https://github.com/Azure/SONiC/blob/master/doc/subport/sonic-sub-port-intf-hld.md#1-requirements
This inheritance should include the scenario of mtu changes on parent physical port or port channel.
In newly added vs unit test on both master and 201911 branches:
Before the change:
```
E           AssertionError: Expected field/value pairs not found: expected={'SAI_ROUTER_INTERFACE_ATTR_MTU': '8888'},                 received={'SAI_ROUTER_INTERFACE_ATTR_VIRTUAL_ROUTER_ID': 'oid:0x3000000000022', 'SAI_ROUTER_INTERFACE_ATTR_SRC_MAC_ADDRESS': '02:42:AC:11:00:05', 'SAI_ROUTER_INTERFACE_ATTR_TYPE': 'SAI_ROUTER_INTERFACE_TYPE_SUB_PORT', …
```

[sub intf] Inherit parent port mtu changes

---

tests/conftest.py
tests/test_acl.py

- Refactor check_services to use common polling method
- Convert remaining python 2 code to python 3 (f-strings, type hints, etc.)
- Make the formatting consistent
- Note remaining test dependencies in dvs
**What I did/Why I did it**
I cleaned-up/refactored `conftest.py`:
1. `check_services` implemented its own polling mechanism, so I refactored it to use `wait_for_result` instead.
2. There was some left-over python2 code from using `2to3` for the conversion. Because we are using python3 syntax in a lot of places now, and because python2 is EOL, it no longer makes sense to include the python2 support, so I refactored the rest of it out. This includes swapping `format` for `f-string`, `subprocess` for `command`, and adding type hints.
3. The …

[dvs] Clean-up conftest.py

---

orchagent/orchdaemon.cpp

**What I did**
Revert https://github.com/Azure/sonic-swss/pull/570
We should only `flush` the orchagent/syncd communication channel when there is no active tasks in orchagent. This will not influence the end-to-end performance in long run but introduce SELECT_TIMEOUT (1 s) latency if there is remaining data left inside the orchagent/syncd communication channel after previous `flush`, which is not a big deal.
Fix Azure/sonic-buildimage#5570

Revert: swss: flush g_asicState after each event is done #570

---

orchagent/mirrororch.cpp
orchagent/portsorch.cpp
orchagent/saihelper.cpp

**What I did**
Replaced %l variants with PRI format specifier to fix compilation warnings for arm 32-bit arch
Compiled and verified for arm 32-bit arch (marvell-armhf)

[orchagent] Arm 32-bit arch compilation warning Fixes

---

orchagent/portsorch.cpp

**What I did**
In case of successful creation set log level to INFO instead of ERR
For successful port creation the log level is set to ERR.
```
Nov 11 00:57:13.403421 str-s6000-acs-8 ERR swss#orchagent: :- initPort: Initialized port Ethernet36
Nov 11 00:57:13.518152 str-s6000-acs-8 ERR swss#orchagent: :- initPort: Initialized port Ethernet32
Nov 11 00:57:13.693872 str-s6000-acs-8 ERR swss#orchagent: :- initPort: Initialized port Ethernet40
Nov 11 00:57:13.901144 str-s6000-acs-8 ERR swss#orchagent: :- initPort: Initialized port Ethernet44
Nov 11 00:57:14.061818 str-s6000-acs-8 ERR swss#orchagent: :- initPort: Initialized port Ethernet0
Nov 11 00:57:14.225700 str-s6000-acs-8 ERR swss#orchagent: :- initPort: Initialized port Ethernet4
Nov 11 00:57:14.376864 str-s6000-acs-8 …
```

[orchagent][port] In case of successful port creation set log level to INFO

---

orchagent/routeorch.cpp
orchagent/routeorch.h

**What I did**
Remove next-hop groups after updating the reference counter for a bulk of routes instead of removing next-hop groups in the loop of updating the reference counter.
Fix https://github.com/Azure/sonic-buildimage/issues/5813
The bulk route API has two loops of updating the reference counter: 
1. update the sairedis reference counter
2. update the orchagent reference counter
Currently, the removal of next-hop groups is triggered in the second loop of updating the orchagent reference counter when the reference counter decreases to zero. This may result in a reference counter mismatch between orchagent and sairedis since the sairedis reference counter has already included the operation of the whole bulk but the orchagent reference counter has not. Therefore, the …

[Routeorch] Fix next hop group reference count in bulk operation

---

warmrestart/warmRestartAssist.cpp

**What I did**
Fix https://github.com/Azure/sonic-buildimage/issues/5841 and https://github.com/Azure/sonic-buildimage/issues/5580
We found that neighbor table loaded by ```swssconfig``` from ```arp.json``` after ```fast-reboot``` is cleared by ```neighsyncd``` mistakenly at the initial stage. This PR adds a check for ```WarmStart``` before cleaning up, and only do that if ```WarmStart``` is enable.
This PR is to fix the issue that arp table is not recovered after fast-reboot.
Verified on Arista-7260, running 201911 image.
1. Run some test to populate ARP entries on DUT, such as ```test_fast_reboot```
2. Issue a fast-reboot
3. Verify the ```arp.json``` backed up by ```fast-reboot-dump.py``` is loaded and NEIGH_TABLE is restored.
``` …
```

[fast-reboot] Add a check for warmstart before cleaning up neigh table

---

tests/conftest.py

**What I did**
Re-added the runcmd_async method that was removed in a recent refactor.
The buildimage tests depend on this command to work properly.

[dvs] Re-add runcmd_async command

---

orchagent/portsorch.cpp

**What I did**
I fixed a bug where the port buffer drop flex counters were using the same list of stats as the standard port counters.
To get the correct stats for port buffer drops.
Checked in COUNTERS_DB to verify that "SAI_PORT_STAT_IN_DROPPED_PKTS" and "SAI_PORT_STAT_OUT_DROPPED_PKTS" are present. Ran the QoS SAI tests to verify that these counters are incremented as expected.

[201911/portsorch] Add correct stat list for port buffer drop counters

---

cfgmgr/intfmgr.cpp
cfgmgr/intfmgr.h

In the interface manager, set `arp_accept` to 1 when gratuitous ARP is enabled for an interface in config DB.
**What I did**

[intfmgr]: Add GARP support

---

orchagent/fdborch.cpp
orchagent/fdborch.h
orchagent/portsorch.cpp

**What I did**
I added coded in sonic-swss orchagent to flush the FDB entries corresponding to the bridge port before removing the bridgeport.
I did it because if we don't flush the FDB entries before removing the bridge port and try to remove the bridge port, the bridge port removal results in a failure and the port operational status is set to down.
I created a VLAN interface, assigned IP address to it and added 2 Ethernet ports as tagged members to it. I waited for the switch to add its neighbors through these bridge ports. Then I removed VLAN membership of one of the bridge ports and see it is successful and the operational state of the port does not go down on removing the VLAN membership.
flushFDBEntries() function is …

[201911 sonic-swss] Flushing FDB entries before removing BridgePort

---

tests/conftest.py
tests/dvslib/dvs_policer.py
tests/test_mirror_policer.py
tests/test_policer.py

**What I did**
I updated the DVS tests to take into account the default COPP configuration when checking for policers.
https://github.com/Azure/sonic-buildimage/pull/4861 added a COPP config to the DVS and this is causing a few policer related tests to fail in PR builds across repos b/c there is a mismatch between the expected number of policers and the actual number.
Re-ran the failing tests locally w/ my changes.

[dvs/copp] Adjust policer checks in VS tests for default COPP policers

---

orchagent/orchdaemon.cpp
orchagent/port.h
orchagent/portsorch.cpp
orchagent/portsorch.h
orchagent/vxlanorch.cpp
orchagent/vxlanorch.h
tests/test_vxlan_tunnel.py

1. Existing code supports a single mapper type to be created. Either
BRIDGE or VRF type mappers are supported.
Change to support multiple mapper type creations is being added.
Here mappers of type VLAN-VNI as well as VRF-VNI will be supported.
support for single mapper type creation is not changed.
Only one mode is accepted at a time.
2. Changes to support P2P tunnel creation and deletion.
A refcnt is maintained per resource type (IMR or IP prefix)
and based on this a P2P tunnel is created or deleted.
The VxlanTunnel object is reused for P2P and P2MP tunnels.
State DB updation for every P2P VXLAN tunnel discovered.
3. Changes to support handling of VXLAN_REMOTE_VNI table.
Interfaces with portsorch to create a Port object of type
TUNNEL on tunnel discovery. This is also used to extend
4. …

[Orchagent] Vxlanorch and Portsorch changes for EVPN VXLAN

---

orchagent/bufferorch.cpp
orchagent/pfcactionhandler.cpp
orchagent/port.h
orchagent/portsorch.cpp
tests/mock_tests/portsorch_ut.cpp

**What I did**
One action for the PFC storm is to set a zero buffer profile on the PG under PFC storm.
The zero buffer won't be removed until the PFC storm has gone.
If the user wants to modify the buffer profile for the PG, the bufferorch will return "task_need_retry".
General speaking it doesn't matter unless that:
- the system can't be warm rebooted until the PFC storm has gone.
- the "task_need_retry" will block the update coming from any entry of the BUFFER_PG table from being programmed to ASIC.
In this sense, we need a better solution.
In the new solution, it will:
- record the new profile user wants to apply during PFC storm as the "pending profile" for that PG and return "task_success" if the PG is under PFC storm.
- apply the pending profile once the PG is unlocked.
- the latest …

Improve the way of handling BUFFER_PG during PFC storm

---

orchagent/port_rates.lua
orchagent/rif_rates.lua

Signed-off-by: Volodymyr Boyko <volodymyrx.boiko@intel.com>
**What I did**
Set rate collect logic init state per port
Observing following syslog:
`Nov 26 19:34:28.821608 sonic ERR syncd[26]: :- guard: RedisReply catches system_error: command: *39#015#012$7#015#012EVALSHA#015#012$40#015#0121140a72bbf8e5306e589cb798796067294922901#015#012$2#015#01232#015#012$19#015#012oid:0x600000000034f#015#012$19#015#012oid:0x6000000000350#015#012$19#015#012oid:0x6000000000351#015#012$19#015#012oid:0x6000000000352#015#012$19#015#012oid:0x6000000000353#015#012$19#015#012oid:0x6000000000354#015#012$19#015#012oid:0x6000000000355#015#012$19#015#012oid:0x6000000000356#015#012$19#015#012oid:0x6000000000357#015#012$19#015#012oid:0x6000000000358#015#012$19#015#012oid:0x6000000000359#015#012$19#015 …

[port_rates][rif_rates] Fix port_rates.lua

---

orchagent/main.cpp

**What I did**
Added support for zmq synchronous mode flag, passed from command line to sairedis
To add easy access for zmq sync mode from command line
Run OA with -z flag and syncd with -z flag

[orchagent] Add zmq sync mode flag

---

orchagent/portsorch.cpp

**What I did**
Adjust port initialized event back to notice.
This event was raised from notice to error unnecessarily in PR #1264. This event is causing test to fail with loganalyzer.

[portsorch] adjust port initialized event back to notice

---

orchagent/main.cpp
tests/mock_tests/aclorch_ut.cpp

**What I did**
1. Change gAsicInstance to type string with max length limit
2. Replace malloc with calloc to prevent risk of integer overflow, in test code
1. Remove `calloc` manual memory management.
2. Graceful release memory before exiting. 
3. Save memory if input is very long
Ad-hoc test with different input arguments.

Change gAsicInstance to type string with max length limit

---

orchagent/bufferorch.cpp
orchagent/watermark_bufferpool.lua
orchagent/watermarkorch.cpp
tests/test_watermark.py

**What I did**
Added 'SAI_BUFFER_POOL_STAT_XOFF_ROOM_WATERMARK_BYTES' in the interested counters to be queried
Updated the the buffer lua script to update the headroom pool watermark counters
Updated watermark orch to act on headroom pool clear request
To expose the headroom pool watermark counters in SONiC
On platforms with headroom pool support, verified that headroom pool watermark counters are getting updated as expected
```
admin@sonic:~$ show headroom-pool persistent-watermark 
Headroom pool maximum occupancy:
Pool    Bytes
---------------------  -------
ingress_lossless_pool   863616
```
On platforms without headroom pool support, headroom pool watermark counters show as N/A
```
admin@sonic:~$ show headroom-pool persistent-watermark 
Headroom …
```

Add support for headroom pool watermark

---

tests/conftest.py

**What I did**
I moved some of the dynamic test setup steps to run inside the network namespace. This needs to be done b/c we may have multiple test runs ongoing at the same time on Jenkins, and if two tests re-use a name such as "eth9" before the link has been added to the namespace then it will cause the tests to crash and fail.
Fixes https://github.com/Azure/sonic-buildimage/issues/5205
Ran tests locally with `sudo pytest -sv` and they passed.

[dvs] Fix issue where concurrent netns operations cause test setup to fail

---

orchagent/fgnhgorch.cpp

**What I did**
Changed format specifier %lu to %zu for size_t to avoid compilation warnings in arm 32-bit

[fgnhgorch] Change format specifier %lu to %zu for size_t

---

orchagent/aclorch.cpp

**What I did**
Enable v6 ACL rule based Mirroring for Innovium Platform
It was not previously enabled.
Verified on Innovium based SONiC platform
redis-cli -n 6 hgetall "SWITCH_CAPABILITY|switch"
:
:
3) "MIRROR"
4) "true"
5) "MIRRORV6"
6) "true"
:
:
root@sonic-dut:~#

Enable ACL table type  mirror_v6 for Innovium Platform

---

orchagent/aclorch.cpp
orchagent/aclorch.h
orchagent/mirrororch.cpp
orchagent/mirrororch.h
orchagent/orch.cpp
orchagent/orch.h
orchagent/orchdaemon.cpp
tests/conftest.py
tests/dvslib/dvs_acl.py
tests/dvslib/dvs_mirror.py
tests/dvslib/dvs_policer.py
tests/mock_tests/mock_orchagent_main.cpp
tests/test_warm_reboot.py

**What I did**
I added retry mechanisms to `AclOrch` for mirror sessions and `MirrorOrch` for policers.
Fixes https://github.com/Azure/sonic-buildimage/issues/5497
Tested on a DUT locally. ~**THIS STILL NEEDS VS TESTS AS WELL.**~
This will not cherry-pick cleanly to 201911 b/c of the port mirroring feature, so I will open a separate PR for 201911 once this one is reviewed + merged.
~In draft while I finish the VS tests.~

[everflow] Add retry mechanism for mirror sessions and policers

---

orchagent/vxlanorch.cpp

[vxlanorch] Use PRI instead of %l to avoid warnings in 32-bit arch

---

cfgmgr/vxlanmgr.cpp
cfgmgr/vxlanmgr.h
cfgmgr/vxlanmgrd.cpp
orchagent/portsorch.cpp
orchagent/vxlanorch.cpp

1. Add support for EVPN NVO config table.
2. VxlanTunnel and TunnelMap handlers are enhanced to also cache the data so that
this can be used during the deletion.
3. ARP suppression changes
Create state db for vxlanmgr and vlanmgr to sync the tunnel association to vlan
4. Changes to support warm reboot.
HLD Location : https://github.com/Azure/SONiC/pull/437/commits
Signed-off-by: Rajesh Sankaran <rajesh.sankaran@broadcom.com>
**What I did**
Please refer to details provided above.
EVPN VXLAN Implementation
Tested along with PR 1264. Used test script in PR 1318.
Also ran test_vnet.py from master branch to verify there were no failures. 

[VxlanMgr] changes for EVPN VXLAN

---

tests/dvslib/dvs_common.py
tests/dvslib/dvs_database.py
tests/dvslib/dvs_vlan.py
tests/test_fgnhg.py
tests/test_nat.py
tests/test_route.py
tests/test_sub_port_intf.py

- Fix formatting for default assert messages
- Add support for customized assert messages
- Use dataclass for PollingConfig
**What I did**
- Fixed formatting for default assert messages
- Added support for customized assert messages
- Used dataclass for PollingConfig instead of namedtuple
- Some logging messages look choppy when printed out b/c the line break was including all the extra whitespace as well. f-strings provide a clean way of avoiding this problem, so I moved all the log statements to use that.
- For some tests it may be more useful to say what _logically_ went wrong rather than just saying "the database looks wrong," so that support has been added.
- `dataclass`  is a new construct in python3 that fulfills the …

[dvs] Clean-up dvs_database and dvs_common

---

cfgmgr/Makefile.am
cfgmgr/buffer_check_headroom_mellanox.lua
cfgmgr/buffer_check_headroom_vs.lua
cfgmgr/buffer_headroom_mellanox.lua
cfgmgr/buffer_headroom_vs.lua
cfgmgr/buffer_pool_mellanox.lua
cfgmgr/buffer_pool_vs.lua
cfgmgr/buffermgr.cpp
cfgmgr/buffermgr.h
cfgmgr/buffermgrd.cpp
cfgmgr/buffermgrdyn.cpp
cfgmgr/buffermgrdyn.h
orchagent/bufferorch.cpp
orchagent/bufferorch.h
orchagent/orchdaemon.cpp
tests/buffer_model.py
tests/conftest.py
tests/mock_tests/portsorch_ut.cpp
tests/test_buffer.py
tests/test_buffer_dynamic.py
tests/test_buffer_mode.py

**What I did**
***Support dynamic buffer calculation***
1. Extend the CLI options for buffermgrd:
- -a: asic_table provided,
- -p: peripheral_table provided
The `buffermgrd` will start the dynamic headroom calculation mode with -a provided.
Otherwise, it will start the legacy mode (pg_headroom_profile looking up)
2. A new class is provided for dynamic buffer calculation while the old one remains.
The daemon will instantiate the corresponding class according to the CLI option when it starts.
3. In both modes, the `buffermgrd` will copy BUFFER_XXX tables from CONFIG_DB to APPL_DB and the `bufferorch` will consume BUFFER_XXX tables from APPL_DB
***Backward compatibility***
For legacy mode, the backward compatibility is provided. As mentioned above, `buffermgrd` will check whether the json …

[Dynamic buffer calc]  Support dynamic buffer calculation

---

lgtm.yml
orchagent/orchdaemon.cpp
orchagent/pfc_detect_mellanox.lua

* Use "PFC duration" counters in micro seconds instead of quanta
**What I did**
Updated PFCWD storm detection logic for Mellanox platforms in order to use "PFC duration" counters in micro seconds instead of quanta.
Depends on below PRs so they should be merged first.
- https://github.com/Azure/sonic-sairedis/pull/731
- https://github.com/Azure/sonic-buildimage/pull/6156
SONiC PFCWD logic requires "pfc duration" value in micro seconds but in SAI it was provided as quanta of time. So it required additional conversion which used speed value to do such conversion and it could cause PFCWD to detect storm on operationally down port in case of link flapping.
Now there are new SAI attributes that provide "pfc duration" in …

[pfcwd] Update PFC storm detection logic for Mellanox platforms

---

cfgmgr/natmgr.cpp
natsyncd/natsync.cpp
natsyncd/natsync.h

This PR is similar as https://github.com/Azure/sonic-swss/pull/1320 which is merged on master branch.

[201911] Fixes for NAT lgtm alerts

---

cfgmgr/vxlanmgr.cpp

Changed format specifiers from %lu to %zu for size_t to avoid compilation
errors in arm 32-bit
**What I did**
This commit modifies various SWSS_LOG calls to use the correct format specifier (%zu) for size_t
This fixes a build break when compiling for ARM 32-bit (armhf)
Successfully built the  sonic-marvell-armhf.bin image

[vxlanmgr] Fix build error when compiling for armhf (32-bit)

---

orchagent/crmorch.cpp

**What I did**
Static cast to uint64_t
Fix orchagent crash in case of overflow resulting in divide by 0
Wrote a test program to simulate

[CRM] Typecast to unit64_t to avoid divide by 0 during overflow

---

orchagent/portsorch.cpp

with multiset SET may get replace with DEL. Need to make sure bring  down the port before remove.
**What I did**
Bring down the port before remove. During DPB SET request to bring down the port may get replaced DEL. Make sure to bring down the port before remove.
To make sure port is in admin down state before remove port.
config interface breakout Ethernet8 4x25G -y -f
UT logs:
Nov  5 19:40:27.774309 sonic INFO lldp#lldpmgrd[38]: Unable to retrieve description for port 'Ethernet8'. Not adding port description
Nov  5 19:40:40.606602 sonic INFO lldp#lldpmgrd[38]: Port name Ethernet8 oper status: up
Nov  5 19:40:40.606721 sonic NOTICE swss#orchagent: :- doPortTask: Set port Ethernet8 admin status to down
Nov  5 19:40:40.607883 …

with multiset SET may get replace with DEL. Need to make sure bring  down the port before remove.

---

orchagent/fgnhgorch.cpp
orchagent/fgnhgorch.h
tests/test_fgnhg.py

**What I did**
Added fine grained ecmp link oper state handling changes
To adjust ECMP appropriately on link oper change
Verified using VS swss test cases
HLD update associated with change: https://github.com/Azure/SONiC/pull/693

[fgnhgorch] Fg Nhg link handling

---

cfgmgr/buffermgrdyn.cpp
orchagent/bufferorch.cpp

Changed format specifiers to avoid compilation errors in arm 32-bit
**What I did**
This commit modifies various SWSS_LOG calls to use the correct format specifier
This fixes a build break when compiling for ARM 32-bit (armhf)
Successfully built the sonic-marvell-armhf.bin image

[buffermgmt] more build error fixes when compiling for armhf (32-bit)

---

neighsyncd/restore_neighbors.py

[restore_neighbors] python3 support for restore_neighbors.py
This is dependent on https://github.com/Azure/sonic-buildimage/pull/6207
**What I did**
Change the restore_neighbors.py to support python3
python2 EOL.
swss vs tests

[restore_neighbors] python3 support for restore_neighbors.py

---

tests/test_evpn_tunnel.py

Added Pytest to test changes to VxlanMgr, VxlanOrch and PortsOrch for EVPN VXLAN feature.
HLD Location : https://github.com/Azure/SONiC/pull/437/commits
Signed-off-by: Rajesh Sankaran rajesh.sankaran@broadcom.com
What I did
Please refer to details provided above.
Why I did it
EVPN VXLAN Implementation
Changes as part of PR 1264 and 1266 verified with this pytest
#1264  and #1266 should be merged for this PR.

[VxlanOrch] pytest for EVPN VXLAN

---

orchagent/aclorch.cpp

**What I did**
Enable v6 ACL rule based Mirroring for Innovium Platform
It was not previously enabled.
Verified on Innovium based SONiC platform
show version
SONiC Software Version: SONiC.SONiC201911_Innovium.0-dirty-20201106.003458
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: d72517d7
Build date: Fri Nov  6 10:37:45 UTC 2020
redis-cli -n 6 hgetall "SWITCH_CAPABILITY|switch"
:
:
3) "MIRROR"
4) "true"
**5) "MIRRORV6"
6) "true"**
:
:
root@sonic-dut:~#

Support ACL Table type Mirrorv6 for Innovium

---

orchagent/routeorch.cpp

Changed format specifiers to avoid compilation errors in arm 32-bit
**What I did**
This commit modifies various SWSS_LOG calls to use the correct format specifier
This fixes a build break when compiling for ARM 32-bit (armhf)
Successfully built the sonic-marvell-armhf.bin image

[routeorch] more build error fixes when compiling for armhf (32-bit)

---

orchagent/aclorch.cpp
tests/dvslib/dvs_acl.py
tests/test_nat.py

Issue : Applied below ACL Table and Rule
printf '{"ACL_TABLE": {"in_nat_eg":{"stage": "INGRESS", "type": "L3", "policy_desc": "ingress-acl", "ports": ["Ethernet0"]}}}\n' > /tmp/apply_json.json
config load -y /tmp/apply_json.json
printf '{"ACL_RULE": {"in_nat_eg|rule-33":{"PRIORITY": "97", "PACKET_ACTION": "DO_NOT_NAT", "SRC_IP": "14.1.0.1/32"}}}\n' > /tmp/apply_json.json
config load -y /tmp/apply_json.json
Seeing below OA errors when Rule is applied:
root@sonic:/home/admin# printf '{"ACL_RULE": {"in_nat_eg|rule-33":{"PRIORITY": "97", "PACKET_ACTION": "DO_NOT_NAT", "SRC_IP": "14.1.0.1/32"}}}\n' > /tmp/apply_json.json
root@sonic:/home/admin# config load -y /tmp/apply_json.json
Running command: /usr/local/bin/sonic-cfggen -j /tmp/apply_json.json --write-to-db
Nov 09 06:03:35.914100 sonic ERR …

[NAT] ACL Rule with DO_NOT_NAT action is getting failed.

---

orchagent/crmorch.cpp

**What I did**
Check if divisor is 0. If yes, log warning and skip division
Safety check to avoid exception and crash.

[CRM] Safety check for division by 0

---

orchagent/intfsorch.cpp
orchagent/routeorch.cpp
orchagent/routeorch.h

**What I did**
skip route pointing to loopback interface
if we assign the loopback interface with non full-masked route, then we could 
receive a route from fpmsyncd. we need to skip it otherwise, it will be queued 
in orchagent. 
```
Dec 26 19:45:40.063448 vlab-01 INFO swss#orchagent: :- addRoute: Failed to get next hop ::@Loopback0 for fc00:1::/64
```

[loopback]: skip route pointing to loopback interface

---

tests/test_evpn_l3_vxlan.py

**What I did**
Added PY Test script for EVPN L3 VxLAN.
Added following test cases.
1. Testing Create and Delete SIP Tunnel and VRF VNI Map entries
2. Testing Create and Delete DIP Tunnel on adding and removing prefix route
3. Testing IPv4 Route and Overlay Nexthop Add and Delete
4. Testing IPv4 Route and Overlay Nexthop Update
5. Test VRF IPv4 Route with ECMP Tunnel Nexthop Add and Delete
6. Test VRF IPv4 Route with Tunnel Nexthop update from non-ECMP to ECMP
7. Test VRF IPv4 Route with Tunnel Nexthop update from ECMP to non-ECMP
8. Testing IPv6 Route and Overlay Nexthop Add and Delete
9. Testing IPv6 Route and Overlay Nexthop Update
10. Test VRF IPv6 Route with ECMP Tunnel Nexthop Add and delete
11. Test VRF IPv6 Route with Tunnel Nexthop update from non-ECMP to ECMP
12. Test VRF IPv6 …

PY Test script for EVPN L3 VxLAN

---

doc/Configuration.md
orchagent/crmorch.cpp
orchagent/crmorch.h
tests/test_crm.py

Signed-off-by: Prabhu Sreenivasan <prabhu.sreenivasan@broadcom.com>
**What I did**
Added support for snat, dnat and ipmc resources under CRM module.
New feature NAT adds new resources snat_enty and dnat_entry that needs to be monitored. ipmc_entry tracks IP multicast resources used by switch.
**Associated PRs**
Azure/sonic-utilities/pull/1258
Azure/sonic-buildimage#6012
```
root@sonic:/home/admin# crm show resources snat
Resource Name      Used Count    Available Count
---------------  ------------  -----------------
snat_entry                  0               1024
root@sonic:/home/admin# crm show resources dnat
Resource Name      Used Count    Available Count
---------------  ------------  -----------------
dnat_entry                  0             …
```

[crm] Add support for snat, dnat and ipmc crm resources

---

tests/test_fdbsync.py

[FDBSYNCD]
Added pytest for fdbsyncd
What I did
Added below UT cases for fdbsyncd.
1) Add local MAC entry in STATE_FDB_TABLE and verify MAC is installed in Kernel. Delete Local MAC entry and verify MAC is uninstalled from Kernel.
2) Add local MAC entry in STATE_FDB_TABLE without config Vxlan NVO and verify MAC is not installed in Kernel.
3) Move STATE_FDB_TABLE entry to another port and verify MAC is updated in Kernel.
4) Add static MAC entry in STATE_FDB_TABLE and verify MAC is installed as static in Kernel. Delete static MAC entry in STATE_FDB_TABLE and verify MAC is uninstalled in Kernel.
5) Add remote IMET route entry in Kernel and verify entry is present in VXLAN_REMOTE_VNI_TABLE. Delete remote IMET and verify entry is deleted from the VXLAN_REMOTE_VNI_TABLE.
6) Add remote MAC entry …

[FDBSYNCD] Added pytest for fdbsyncd

---

orchagent/fgnhgorch.cpp
orchagent/fgnhgorch.h
orchagent/orchdaemon.cpp
tests/mock_tests/aclorch_ut.cpp
tests/test_fgnhg.py

**What I did**
1. Add bake() functions in FgnhgOrch
bake() function retrieves the state database information
so that when the new route is added, fgnhg orch is able to recover
the nexthop and bucket the same as before warm reboot.
2. Add priority to fgnhg tables so that fgnhg tables can be loaded prior to route table.
After warm reboot, it is expected that the fgnhg local structure and relationship between nexthop and bucket is retained.
Verified using VS swss test cases by stop and restart swss.

[fgnhgorch] add warm reboot support for fgnhg

---

orchagent/fgnhgorch.cpp

**What I did**
Fix format string for size_t
We met below error message in armhf build (32-bit)
```
g++ -DHAVE_CONFIG_H -I. -I.. -I ../lib -I .. -I ../warmrestart -I flex_counter -I debug_counter -g -DNDEBUG  -std=c++14 -Wall -fPIC -Wno-write-strings -I/usr/include/libnl3 -I/usr/include/swss -Werror -Wno-reorder -Wcast-align -Wcast-qual -Wconversion -Wdisabled-optimization -Wextra -Wfloat-equal -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wimport -Winit-self -Winvalid-pch -Wlong-long -Wmissing-field-initializers -Wmissing-format-attribute -Wno-aggregate-return -Wno-padded -Wno-switch-enum -Wno-unused-parameter -Wpacked -Wpointer-arith -Wredundant-decls -Wstack-protector -Wstrict-aliasing=3 -Wswitch -Wswitch-default -Wunreachable-code -Wunused …
```

Fix format string for size_t

---

mclagsyncd/mclaglink.cpp

**What I did**
Simply by auto iterator type
Because we will tune the return types of library functions
Build pass.

Simply by auto iterator type, because we will tune the return types of library functions

---

orchagent/orchdaemon.cpp
orchagent/switchorch.cpp
orchagent/switchorch.h
tests/mock_tests/aclorch_ut.cpp

**What I did**
1) ASICs have multiple internal thermal sensors.
2) With the help of configuration, a poller is introduced in Orchagent that will periodically retrieve values of these sensors with the help of SAI APIs (opencomputeproject/SAI#880).
3) These retrieved values are being populated to the state DB (In "ASIC_TEMPERATURE_INFO" table).
As part of ASIC Thermal Monitoring HLD.
Tested out in below platforms.
[asic_thermal_log.s6100.txt](https://github.com/Azure/sonic-swss/files/5582296/asic_thermal_log.s6100.txt)
[asic_thermal_log.z9264.txt](https://github.com/Azure/sonic-swss/files/5582297/asic_thermal_log.z9264.txt)
[asic_thermal_log.s5232.txt](https://github.com/Azure/sonic-swss/files/5582298/asic_thermal_log.s5232.txt) …

ASIC internal temperature sensors support

---

tests/test_mirror_port_erspan.py
tests/test_route.py

- Fix erspan test behavior to use valid alternate route for mirror session
- Skip route tests w/ FRR VRF bug
**What I did**
I updated/disabled DVS tests to account for new FRR 7.5 behavior.
To unblock the PR pipeline.
Re-ran both test files, all tests pass now.

[dvs] Update/disable DVS tests with new FRR 7.5 behavior

---

orchagent/fdborch.cpp
orchagent/portsorch.cpp

**What I did**
Flushed FDB entries for specific VLAN when trying to delete the VLAN
As flushing the FDB entries was not done, the VLAN had references in ASIC-DB and could not be removed.
Verified it by creating a VLAN, injecting traffic on the VLAN port and trying to remove the VLAN member port and then removed the VLAN. VLAN removal was successful.
Changes were in FDB orchagent and PORTS orchagent of SONIC-SWSS.

[201911] Flushing FDB entries per VLAN when deleting VLAN

---

gearsyncd/gearboxparser.cpp
gearsyncd/tests/configs/negative/gearbox_config_empty_ethernet_line_lanes.json
gearsyncd/tests/configs/negative/gearbox_config_empty_ethernet_system_lanes.json
gearsyncd/tests/configs/negative/gearbox_config_invalid_array.json
gearsyncd/tests/configs/negative/gearbox_config_invalid_json.json
gearsyncd/tests/configs/negative/gearbox_config_invalid_phy_config_file.json
gearsyncd/tests/configs/negative/gearbox_config_missing_ethernet_index.json
gearsyncd/tests/configs/negative/gearbox_config_missing_ethernet_line_lane_speed.json
gearsyncd/tests/configs/negative/gearbox_config_missing_ethernet_line_lanes.json
gearsyncd/tests/configs/negative/gearbox_config_missing_ethernet_phy_id.json
gearsyncd/tests/configs/negative/gearbox_config_missing_ethernet_system_lane_speed.json
gearsyncd/tests/configs/negative/gearbox_config_missing_ethernet_system_lanes.json
gearsyncd/tests/configs/negative/gearbox_config_missing_interfaces.json
gearsyncd/tests/configs/negative/gearbox_config_missing_phy_address.json
gearsyncd/tests/configs/negative/gearbox_config_missing_phy_bus_id.json
gearsyncd/tests/configs/negative/gearbox_config_missing_phy_config_file.json
gearsyncd/tests/configs/negative/gearbox_config_missing_phy_firmware_path.json
gearsyncd/tests/configs/negative/gearbox_config_missing_phy_hwinfo.json
gearsyncd/tests/configs/negative/gearbox_config_missing_phy_id.json
gearsyncd/tests/configs/negative/gearbox_config_missing_phy_lib_name.json
gearsyncd/tests/configs/negative/gearbox_config_missing_phy_name.json
gearsyncd/tests/configs/negative/gearbox_config_missing_phy_phy_access.json
gearsyncd/tests/configs/positive/gearbox_config_1.json
gearsyncd/tests/testgearparser.cpp
lib/gearboxutils.cpp
lib/gearboxutils.h
orchagent/saihelper.cpp

**What I did**
This PR adds support for a new "hwinfo" attribute in gearbox_config.json. The field is propagated by syncd to the SAI by setting SAI_SWITCH_ATTR_SWITCH_HARDWARE_INFO.
This is necessary to propagate the MDIO interface & phy_id that should be used by the SAI driver for a particular gearbox.
Verified on an internal Arista build that the field from the configuration was propagated all the way to the SAI.

[gearbox] Add support for "hwinfo" field

---

orchagent/fdborch.cpp

**What I did**
Fix for arm compilation caused as part of https://github.com/Azure/sonic-swss/pull/1275
Unblock PR build

[Fdborch] Fix for arm compilation

---

fpmsyncd/fpmlink.cpp
fpmsyncd/routesync.cpp
fpmsyncd/routesync.h

What I did
1) While extracting the RT Attribute from netlink message, If the message is NESTED msg remove the NESTED flag and extract the msg.
2) Get nexthop ifindex from Netlink msg RTA_OIF attribute and use the name based on the ifindex program in the APP_DB.
Why I did it
1) With FRR7.5 upgrade Netlink Msg from FRR has NLA_F_NESTED flag set in
RTA_TYPE while sending VNI and RMAC.
2) In the new patch to keep it in line with FRR upstreaming, we are not
sending the VLAN ID from FRR as it can be extracted from ifindex inside
the nexthop information.
Verified using vsonic
Signed-off-by: Kishore Kunal kishore.kunal@broadcom.com

[FPMSYNCD] Change done to support FRR7.5

---

orchagent/orchdaemon.cpp
orchagent/pfc_detect_mellanox.lua

* Use "PFC duration" counters in micro seconds instead of quanta
**What I did**
Updated PFCWD storm detection logic for Mellanox platforms in order to use "PFC duration" counters in micro seconds instead of quanta.
SONiC PFCWD logic requires "pfc duration" value in micro seconds but in SAI it was provided as quanta of time. So it required additional conversion which used speed value to do such conversion and it could cause PFCWD to detect storm on operationally down port in case of link flapping.
Now there are new SAI attributes that provide "pfc duration" in micro seconds so PCWD storm detection logic is updated in order to use this new "pfc duration" counters. Such algorithm change helps to avoid false PFC storm …

[201911] [pfcwd] Update PFC storm detection logic for Mellanox platforms

---

orchagent/fdborch.cpp

**What I did**
I modified Error log for FDB flush notification failure due to VLAN removal to WARN log.
I modified it because, the VLAN is already removed and we are receiving a FLUSH notification for the same, it should be treated as a warning and not an error.
I created a VLAN and added a member port to it and I learnt FDB entry on that port for the VLAN. Then removed the member port and removed the VLAN. Once, I remove the VLAN, there will be a log "Failed to locate vlan", it should be a warning log.
Code changes are in Sonic-swss fdb orchagent.

[201911-SWSS] Change Error log to WARN log for FDB flush notification failure

---

orchagent/main.cpp
orchagent/saihelper.cpp
orchagent/saihelper.h

**What I did**
Add new options to specify swss rec and sairedis rec file name.
Corresponding change in sairedis https://github.com/Azure/sonic-sairedis/pull/747
This option will be used in the multi asic system. The swss and sairedis record filename will be different for each asic and will be passed from the orchagent.sh 
- Check if swss.rec and sairedis.rec files are created when the new options are not used
```
admin@vlab-01:~$ ls /var/log/swss/
sairedis.rec  swss.rec
admin@vlab-01:~$ tail -10 /var/log/swss/sairedis.rec
2020-12-15.17:57:02.194381|s|SAI_OBJECT_TYPE_HOSTIF:oid:0xd00000000059e|SAI_HOSTIF_ATTR_OPER_STATUS=true
2020-12-15.17:57:02.195879|s|SAI_OBJECT_TYPE_HOSTIF:oid:0xd00000000059d|SAI_HOSTIF_ATTR_OPER_STATUS=true …
```

[logfile]: Add option to specify swss rec file name

---

cfgmgr/buffermgrdyn.cpp

**What I did**
Enhance dynamic buffer calculation and bug fixes
Run regression and vs test
- Remove make_pair when calling emplace_back.
- The pool size isn't recalculated when a port with headroom-override but without speed or cable length configured being shutdown.
- Remove the current PG from the old referenced profile only if its name isn't empty, otherwise, an entry with an empty name will be inserted into m_bufferProfileLookup
- Don't try removing statically configured profiles with dynamic headroom from the APPL_DB because they were not programmed to APPL_DB.
- Setting a buffer PG to the same profile as it was causes the referenced dynamic profile unable to be removed once …

Enhance dynamic buffer calculation and bug fixes

---

fpmsyncd/routesync.cpp

**What I did**
Skip routes to eth0 or docker0 in fpmsyncd.
Fix https://github.com/Azure/sonic-buildimage/issues/6483
An FRR behavior change from 7.2 to 7.5 makes FRR update the default route to eth0 in interface up/down events. Skipping routes to eth0 or docker0 to avoid such behavior.
Tested locally that the default route does not change in interface up/down events.

[fpmsyncd] Skip routes to eth0 or docker0

---

orchagent/crmorch.cpp

Signed-off-by: Prabhu Sreenivasan <prabhu.sreenivasan@broadcom.com>
Fix https://github.com/Azure/sonic-buildimage/issues/6563
**What I did**
Added checks for SAI_STATUS_ATTR_NOT_SUPPORTED_0  and SAI_STATUS_ATTR_NOT_IMPLEMENTED_0 to ignore unsupported CRM attributes.
Switch attributes SAI_SWITCH_ATTR_AVAILABLE_SNAT_ENTRY, SAI_SWITCH_ATTR_AVAILABLE_DNAT_ENTRY and SAI_SWITCH_ATTR_AVAILABLE_IPMC_ENTRY are currently unsupported by some SAI implementations and below logs were appearing on those switches.
```
Jan 26 07:08:51.743298 mts-sonic-dut ERR swss#orchagent: :- getResAvailableCounters: Failed to get switch attribute 60 , rv:-327680
Jan 26 07:08:51.745972 mts-sonic-dut ERR swss#orchagent: :- getResAvailableCounters: Failed to get switch attribute 61 , rv:-196608
Jan 26 …
```

[crm] Ignore unsupported switch attributes

---

orchagent/portsorch.cpp

What I did:
Use reference count for protect interface, If interface bind to ACL the reference will increase and vice versa.
Why I did it:
If interface bind to ACL and remove interface causes the ACL rule become global rule to match all interfaces.
How I verified it:
Run the pytest check ACL and Port test case passed.

[PortsOrch] Add reference counting to ports for ACL bindings

---

orchagent/portsorch.cpp

Signed-off-by: Vitaliy Senchyshyn <vsenchyshyn@barefootnetworks.com>
**What I did**
Configure SAI_HOSTIF_VLAN_TAG_KEEP for the parent port hostif when a first subport is added and restore it to SAI_HOSTIF_VLAN_TAG_STRIP when the last subport is removed.
As the parent port hostif tagging is not modified during subports creation the packets destined to the subport interfaces are forwarded as untagged by the packet driver and therefore never reaching the subport netdevs.
Created two subports using the config below and pinged their IPs with vlan 10 and 20 tagged packets respectively. The ping was successful.
```
{
"VLAN_SUB_INTERFACE": {
"Ethernet1.10": {
"admin_status" : "up"
},
"Ethernet1.10|11.0.10.1/24": {},
"Ethernet1.20": {
"admin_status" : "up"
}, …
```

[portsorch] Configure hostif tagging for subports

---

fpmsyncd/routesync.cpp

**What I did**
Reduce loglevel to DEBUG for eth0 route update. 
Ref: https://github.com/Azure/sonic-swss/pull/1606
Too many logs

[fpmsyncd] Reduce loglevel to DEBUG for eth0 route update

---

cfgmgr/macsecmgr.cpp
cfgmgr/macsecmgr.h
cfgmgr/macsecmgrd.cpp

**What I did**
1. Fix bug about the return value of `get_value`, it should return `true` if it's OK
2. Fix bug about the type of `MACsecProfile::priority`, the original `uint8_t` will cause a `lexical_convert` failure when the priority is a integer.
3. Polish log in `get_value`.
4. Change the predefined paths for sonic-buildimage integration
I want that the MACsecMgrd can automatically start, so these configuration should be changed to adapt the configuration in sonic-buildimage
Change the `/etc/sonic/config_db.json` as follow
```
{
"PORT": {
"Ethernet0": {
...
"macsec": "test"
}
}
...
"MACSEC_PROFILE": {
"test": {
"priority": 64,
"cipher_suite": "GCM-AES-128",
"primary_cak": "0123456789ABCDEF0123456789ABCDEF",
"primary_ckn": …
```

[cfgmgr]: Integrate MACsecMGR with sonic-buildimage

---

cfgmgr/tunnelmgr.cpp
cfgmgr/tunnelmgr.h
cfgmgr/tunnelmgrd.cpp
orchagent/muxorch.cpp
orchagent/muxorch.h
orchagent/neighorch.cpp
orchagent/neighorch.h
orchagent/routeorch.cpp
orchagent/routeorch.h

**What I did**
1. Program/Reprogram routes to hardware based on Mux status
2. Create tunnel interface (tun0) in kernel
3. Add/remove tunnel routes in kernel
Support dual-tor SLB scenarios

[Mux] Route handling based on mux status, kernel tunnel support

---

configure.ac
orchagent/orch.cpp

**What I did**
Fix the following error.
```
orch.cpp: In member function 'ref_resolve_status Orch::resolveFieldRefArray(type_map&, const string&, swss::KeyOpFieldsValuesTuple&, std::vector<long unsigned int>&, std::string&)':
orch.cpp:609:41: error: 'strlen' argument missing terminating nul [-Werror=stringop-overflow=]
609 |                     object_name_list += string(&list_item_delimiter);
|                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from orch.cpp:6:
orch.h:25:12: note: referenced argument declared here
25 | const char list_item_delimiter = ',';
|            ^~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```
**- …

Fix the compiling errors in gcc9

---

cfgmgr/buffer_headroom_mellanox.lua
cfgmgr/buffer_pool_mellanox.lua
cfgmgr/buffermgrdyn.cpp
cfgmgr/buffermgrdyn.h
tests/test_buffer_dynamic.py

**What I did**
Support shared headroom pool on top of dynamic buffer calculation.
Support shared headroom pool on top of dynamic buffer calculation:
- Feature is enabled/disabled on-the-fly by configuring over-subscribe-ration and shared headroom pool size.
If both are configured, the shared headroom pool size will take effect.
When turn on/off the feature, all the lossless profiles and buffer pool size will be recalculated.
- Support calculating shared headroom pool while ingress lossless pool is statically configured.
Run vs test and regression test.
**- Which release branch to backport (provide reason below if selected)**

Support shared headroom pool on top of dynamic buffer calculation

---

cfgmgr/buffer_check_headroom_mellanox.lua
orchagent/port.h
orchagent/portsorch.cpp
orchagent/portsorch.h

**What I did**
Check the accumulative port headroom against the port's maximum headroom
On Mellanox platform, this PR depends on PR [#6566](https://github.com/Azure/sonic-buildimage/pull/6566) to be merged. In that PR the required SAI attribute is supported.
On other platforms, there is no dependency.
On some platforms, the SAI will notify orchagent shut down if a headroom size that causes the accumulative port headroom to exceed its limit is programmed to SAI.
To avoid that, we need to check this before programming it to SAI.
Run the regression test.
- Fetch the maximum port headroom via fetching the port attribute `SAI_PORT_ATTR_QOS_MAXIMUM_HEADROOM_SIZE` when the orchagent …

[buffermgr] Support maximum port headroom checking

---

orchagent/portsorch.cpp
orchagent/portsorch.h

**What I did**
Migrating the port serdes programming from existing port attributes to port serdes object
This change is required for supporting 6 tap filters which cannot be supported through existing port attributes
Load the changes on existing platforms and verify the pre-emphasis settings are correctly programmed in the hardware
Load the changes on new platforms requiring 6tap filter and verified the settings are programmed correctly in the hardware

Port serdes changes

---

orchagent/portsorch.cpp

**What I did**
Fix: https://github.com/Azure/sonic-buildimage/issues/6727
SAI attribute `SAI_SWITCH_ATTR_NUMBER_OF_SYSTEM_PORTS` is not supported on many platforms, and the call to `getSystemPorts()` throws error.
This error is not harmful at this state, and therefore the log level is changed from `ERROR` to `INFO`.

Log level change from ERR to INFO for fetch systemports issue

---

orchagent/muxorch.cpp
orchagent/muxorch.h
orchagent/neighorch.cpp
orchagent/orchdaemon.cpp
tests/test_mux.py

**What I did**
1. Neighbor handling based on FDB entries. When a new neighbor is learnt, the code lookup FDB table to get the associated physical port and based on the mux status for the port, the neighbor is programmed as local or tunnel nexthop.
2. Log level/message revisited based on log observations from current deployments
_Ethernet96 mux status is - Standby_
```
show arp
Address       MacAddress         Iface            Vlan
------------  -----------------  ---------------  ------
192.168.0.101  00:00:11:22:33:45  Ethernet96       1000
Feb  6 02:48:21.931004 str2-7050cx3-acs-02 ERR swss#orchagent: :- getPort: Failed to get bridge port ID for FDB entry 00:00:11:22:33:55, rv:-5
Feb  6 02:48:21.931004 str2-7050cx3-acs-02 NOTICE swss#orchagent: :- …
```

[Mux] Neighbor handling based on FDB entry

---

orchagent/bufferorch.cpp

**What I did**
Set operations for some attributes of buffer pool and buffer profile may not be implemented by some vendors and they return SAI_STATUS_ATTR_NOT_IMPLEMENTED_0. Handle that status in the code and ignore that task
Reduce the noise in the logs due to these operations
With the code changes in place triggered a warm reboot where these were logged as errors and see them logged as NOTICE

[bufferorch] Handle NOT IMPLEMENTED status returned during set attr operation

---

tests/test_virtual_chassis.py

**What I did**
https://github.com/lguohan/sonic-swss/pull/new/vcha
pr 

[test_virtual_chassis]: use wait_for to make test more robust

---

orchagent/crmorch.cpp
orchagent/crmorch.h

Signed-off-by: Prabhu Sreenivasan <prabhu.sreenivasan@broadcom.com>
Fix Azure/sonic-buildimage#6563
**What I did**
Instead of erasing unsupported resource from m_resourcesMap, mark it as unsupported.
Erasing an entry while iterating using range based iterator makes the iterator invalid.
Also removing a resource from the m_resourcesMap impacts cross access while iterating other maps (eg crmUsedCntsTableMap).
Added a new unsupported resource for testing and verified the logs.

fixed unsupported resource issue

---

tests/test_sub_port_intf.py

**What I did**
vs test update to cover changes in https://github.com/Azure/sonic-swss/pull/1573
vs test:
Without https://github.com/Azure/sonic-swss/pull/1573, vs tests on sub interface creation and removal fail
```
====================================================================== test session starts ======================================================================
platform linux -- Python 3.6.9, pytest-6.1.2, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
rootdir: /var/wendani/src/sonic-buildimage/src/sonic-swss/tests
collected 1 item …
```

[sub intf] Update vs tests to validate physical port host interface vlan tag attribute

---

orchagent/saihelper.cpp

Increase orchagent SAI REDIS response timeout to support FW upgrade during init (Mellanox only).
This change should be merged after the following PRs were merged:
Azure/sonic-sairedis#774
Signed-off-by: liora <liora@nvidia.com>
**What I did**
Increase orchagent SAI REDIS response timeout during init in order for orchagent to wait enough time for response from syncd since in init, syncd startup script first calls FW upgrade script (that might take up to 7 minutes in systems with Gearbox) and only then launches syncd.
To support FW upgrade during init flow.
I manually changed ASIC and Gearbox FW followed by hard reset in order for FW upgrade to take place on init.
**Which release branch to backport**

[orchagent] Increase SAI REDIS response timeout to support FW upgrade during init (Mellanox only)

---

orchagent/aclorch.cpp
orchagent/aclorch.h
orchagent/pfcactionhandler.cpp
orchagent/pfcactionhandler.h
orchagent/pfcwdorch.cpp
tests/dvslib/dvs_acl.py
tests/mock_tests/aclorch_ut.cpp
tests/test_pfcwd.py

**What I did**
Allow PFCWD and MUX features to use single ACL table on ingress side.
It is done to save space and to allow new features to make use of ACL table.
Verified by running tests on TD3 platform.

Updated PFCWD to use single ACL table for PFCWD and MUX

---

orchagent/bufferorch.cpp

**What I did**
Used the platform string to skip the SET operation for buffer profile attributes that are not implemented in Broadcom platform
SET operations for some of the buffer profile attributes are not implemented on Broadcom platforms which leads to an orchagent crash when those attributes are pushed down
Changed the dynamic threshold setting for one of the buffer profiles using "mmuconfig" command. Verified from the sairedis.rec, only dynamic threshold value was seen for Broadcom and all the buffer profile attributes were seen 
for Mellanox

[201911] [bufferorch] Skip setting not implemented brcm attr in buffer profile

---

cfgmgr/Makefile.am
orchagent/neighorch.cpp
orchagent/orch.cpp
orchagent/orch.h
orchagent/routeorch.cpp

**What I did**
Add function to notify users in the presence of SAI failures by throwing exceptions and trigger swss restart in synchronous mode. And include this function in routeorch and neighorch. 
This is a part of the first step in the SAI failure handling in orchagent with synchronous mode:
1. Failure notification mechanism to ensure enough notifications in the presence of SAI failures and avoid running switches with unhandled failures. 
2. Add general failure handling logic by status.
3. Develop fine-grain failure handling mechanism for each orch to properly handle different SAI failures.
This function aims to ensure enough notifications in the presence of SAI failures and avoid running switches with unhandled failures (on-par with asynchronous mode). 
**How I …

[synchronous mode] Add failure notification for SAI failures in synchronous mode

---

orchagent/muxorch.cpp
orchagent/muxorch.h

**What I did**
If orchagent fails in state change, update StateDB with "error" state
Update APP_DB for every state change request from Linkmgr irrespective of internal handling in orchagent
As part of https://github.com/Azure/sonic-buildimage/issues/6761

[Muxorch] Handle StateDB state for error, update APP_DB for state changes

---

.azure-pipelines/docker-sonic-vs/Dockerfile

**What I did**
Observe persistent failure of newly added vs test on testing code change in intfmgrd after migrating to azure pipeline. https://github.com/Azure/sonic-swss/pull/1521 passed in legacy Jenkins pipeline.
What we found is that the code change in the swss compiled with PR change is not properly installed in vs docker for a direct installation using `dpkg -i`. This is confirmed by verifying pipeline artifacts that md5sum value of `/user/bin/intfmgrd` changes if we install swss deb aritfact into the docker vs artifact, while that of `/usr/bin/orchangent` stays unchanged.  
md5sum before swss install in vs docker
```
28307a7805ea6f3bc5057c0257bf46e6  /usr/bin/orchagent
fa2b06e20be683286adb47c55635a86d  /usr/bin/intfmgrd …
```

[ci] Purge installed swss before installing one

---

orchagent/intfsorch.cpp

redis APPL_DB has two entries for subport
8) "INTF_TABLE:Ethernet4.20"
9) "INTF_TABLE:Ethernet4.20:192.169.1.1/24"
sometimes, if the entry with ip key are execute first,
the syslog is like
Feb 23 02:20:43.650184 as7726-32x-3 NOTICE swss#orchagent: :- addRouterIntfs: Create router interface Ethernet4.20 MTU 32761
Feb 23 02:20:43.651383 as7726-32x-3 ERR syncd#syncd:[none] brcm_sai_create_router_interface:284 Invalid MTU size
the mtu value is not init and is too large. sai will return SAI_STATUS_INVALID_PARAMETER
Thus, mtu should be initialized to 0
**What I did**
initialize mtu to 0
sometimes gPortsOrch->addSubPort(port, alias, adminUp, mtu) is called and 
the mtu value is not init and is too large. sai will return SAI_STATUS_INVALID_PARAMETER
Thus, mtu should be …

[intfsorch] Create subport with the entry contains necessary attributes

---

orchagent/portsorch.cpp
tests/test_port_an.py

As part of PR in sonic-buildimage
**What I did**
Changed parsing `autoneg` from 1/0 to on/off

[portorch] parse on/off value from autoneg

---

portsyncd/linksync.cpp

Signed-off-by: vedganes <vedavinayagam.ganesan@nokia.com>
Changes in linksync to use IFF_RUNNING to determine netdev operational
status instead of using IFF_LOWER_UP.
**What I did**
Changed linksync.cpp to use IFF_RUNNING to determine the netdev operational status instead of using IFF_LOWER_UP.
The objective of this change is to make orchagent/linksync align with FRR/Zebra in handling interface states. Zebra uses IFF_RUNNING flag to determine interfaces' oper state while linksync uses IFF_LOWER_UP. Zebra rightly depends on IFF_RUNNING flag. As a routing daemon, zebra wants to know whether the interface is capable of passing packets or not. The flag IFF_RUNNING indicates exactly that (based on comment in if.h, this flag reflects the interface oper up state as defined in …

[linksync] Netdev oper status determination using IFF_RUNNING

---

tests/test_mux.py

**What I did**
VS test to cover:
1. IPv4 and V6 neighbor add and simulate mux state change.  Verify: _Active mux shall have host entry, Standby mux shall have tunnel route_
2. Route add and simulate mux state change. Verify: _Route should have next hop programmed based on mux state (Active shall have neighbor NH, standby shall have tunnel NH)_
3.  ECMP route add and simulate mux state change. Verify: _ECMP group shall be updated based on mux state change, active mux shall have regular nexthop member, standby shall have tunnel nexthop member_
3. Neighbor handing based on FDB learnt. Verify: _Neighbor with FDB learnt on active mux shall have host entry whereas on standby mux shall have tunnel route_
unit-test
Run `pytest test_mux.py --dvsname=vs …

[mux] VS test for neigh, route and fdb

---

orchagent/bulker.h
tests/mock_tests/Makefile.am
tests/mock_tests/bulker_ut.cpp

**What I did**
Keep attributes for the same entry in the order that the attributes are set in bulk mode.
Fix https://github.com/Azure/sonic-buildimage/issues/6881
Some attributes have a dependency on others in SAI operations (e.g., setting nexthop requires packet action to be forward in route set operation). Without keeping the order of the attributes, the configuration may not be successfully applied to hardware. Therefore, it is necessary to keep the order of attributes in bulk mode.
Verify that sairedis applys `SAI_ROUTE_ENTRY_ATTR_PACKET_ACTION` before `SAI_ROUTE_ENTRY_ATTR_NEXT_HOP_ID` when setting default routes.
```
2021-03-03.06:01:12.003330|S|SAI_OBJECT_TYPE_ROUTE_ENTRY||{"dest":"::/0","switch_id":"oid:0x21000000000000","vr":"oid:0x3000000000 …
```

Keep attribute order in bulk mode

---

orchagent/intfsorch.cpp
tests/test_sub_port_intf.py

**What I did**
Crafted a vs test case to validate the processing sequence of `VLAN_SUB_INTERFACE` keys---Key without ip prefix must be processed prior to those with ip prefix when Port object representing sub port interface has not yet been created. If not this case, user configuration other than `vrf_name` in CONFIG_DB, such as `admin_status`, will be ignored in later creating SAI sub port interface, a symptom observed and fixed in https://github.com/Azure/sonic-swss/pull/1650. 
Fix in https://github.com/Azure/sonic-swss/pull/1650 shall pass the vs test case added here.
vs test on `test_sub_port_intf_appl_db_proc_seq` fails without https://github.com/Azure/sonic-swss/pull/1650 fix.
```
================================================================= …
```

[vstest/subintf] Add vs test case to validate processing sequence of APPL DB keys

---

doc/Configuration.md
doc/swss-schema.md

**What I did**
Add table descriptions for dynamic buffer calculation to the documents.
To make the documents aligned with the code.
N/A.
N/A

[Dynamic buffer calc] Add table descriptions for dynamic buffer calculation to the documents

---

orchagent/lagid.cpp
orchagent/lagid.h
orchagent/lagids.lua

**What I did**
Defined class for lag id allocator and added lua script for allocating/freeing lag id in atomic fashion
For portchannels in VOQ based chassis systems we need unique lag id across
the system. The lag id (aka system port aggreggator id) is allocated during portchannel
creation. The changes are for a class for lag id allocation in atomic fashion. The LAG ID is allocated
from central chassis app db. A lua script loaded in the redis at the
time of lag id allocator instantiation ensures allocating unique lag id when
multiple clients requests for lag id simultaneously. 
Ref: VOQ LAG HLD PR: https://github.com/Azure/SONiC/pull/697
- In VOQ based chassis systems, make sure chassis app db is initialized with lag id start and lag id end data in …

[vog/systemlag] Voq lagid allocator

---

orchagent/aclorch.cpp
orchagent/aclorch.h
orchagent/muxorch.cpp
orchagent/muxorch.h
orchagent/pfcactionhandler.cpp
tests/test_mux.py

**What I did**
1. Use ACL_TABLE_DROP for both PFC_WD and MUX
2. Use MATCH_IN_PORTS instead of binding port to ACL table and program single ACL rule
3. Updated PFC_WD code for generic handling and use class data within member function. 
3. Update ACL rule by modifying IN_PORTS bitmap during mux transitions
4. VS test to cover the new changes
Optimize ACL TCAM use
Run test on DUT and validated the PBMP

[MUX/PFCWD] Use in_ports for acls instead of seperate ACL table

---

cfgmgr/nbrmgr.cpp
cfgmgr/nbrmgr.h
tests/test_neighbor.py

Signed-off-by: Vadym Hlushko <vadymh@nvidia.com>
**What I did**
Added specific function to parse keys from `APP_DB` which looks like:
`"NEIGH_RESOLVE_TABLE:Vlan2:2000:1::1"`
`"NEIGH_RESOLVE_TABLE:Vlan2:192.168.0.10"`
The fix for the [issues/7045](https://github.com/Azure/sonic-buildimage/issues/7045).
Provided the VS tests.
Also, it was verified manually, error messages and crash from the [issues/7045](https://github.com/Azure/sonic-buildimage/issues/7045) wasn't observed.

[nbrmgrd] added function to parse IP address from APP_DB

---

orchagent/aclorch.cpp
orchagent/aclorch.h
orchagent/acltable.h
tests/mock_tests/aclorch_ut.cpp

**What I did**
I moved all of the ACL table related constants over to acltable.h.
aclorch.h and aclorch.cpp are both huge files that have become hard to maintain/update to support new features. This is part of a bigger effort to try to refactor it to be more manageable.
Confirmed that the compiler doesn't throw any new errors, unit tests still work the same as before, and I ran `test_acl` and `test_everflow` from sonic-mgmt to confirm there is no traffic impact.

[acl] Move ACL table constants to acltable.h

---

cfgmgr/buffer_pool_mellanox.lua
cfgmgr/buffermgrdyn.cpp
cfgmgr/buffermgrdyn.h
tests/test_buffer_dynamic.py

**What I did**
Bug fixes: Remove PGs from an administratively down port.
To fix bugs
Run regression and vs test
**Which release branch to backport (provide reason below if selected)**
- Remove PGs from an administratively down port.
- Introduce a new state: `PORT_ADMIN_DOWN` which represents the port is administratively down.
- Remove all PGs when the port is shut down and re-add all configured PGs when port is started up
- Only record the new value but don't touch `BUFFER_PG_TABLE` if the following events come when a port is administratively down
- a port's MTU, speed, or cable length is updated
- a new PG is added to a port or an existing PG is removed from a port
- Optimize …

[Dynamic buffer calc] Bug fix: Remove PGs from an administratively down port.

---

cfgmgr/buffer_pool_mellanox.lua
cfgmgr/buffermgrdyn.cpp
cfgmgr/buffermgrdyn.h
tests/test_buffer_dynamic.py

Reverts Azure/sonic-swss#1652
Need to break this PR into smaller commits

Revert "[Dynamic buffer calc] Bug fix: Remove PGs from an administratively down port."

---

orchagent/fdborch.cpp

Signed-off-by: allas <allas@nvidia.com>
**What I did**
Reduced severity of log to info in case of flush on non-existing member.
There is a race in the infra which can cause the scenario: FDB FLUSH notification is received on port which was already removed.
>  sudo config vlan add 3
>  sudo config vlan member add 3 Ethernet8
>  sudo config vlan member del 3 Ethernet8

reduce severity of log to info in case of flush on non-existing member

---

cfgmgr/buffer_check_headroom_mellanox.lua
orchagent/port.h
orchagent/portsorch.cpp
orchagent/portsorch.h

Reverts Azure/sonic-swss#1607
Suspecting this for a test failure. Reverting to verify. 
Refer: https://github.com/Azure/sonic-buildimage/pull/6989. Failing when the PR is updated to this comment.

Revert "[buffermgr] Support maximum port headroom checking"

---

orchagent/mirrororch.cpp

**What I did**
Deactivate mirror session only when status is true in updateLagMember
Fix the issue when mirrororch tries to deactivate a session when it is not activated
```
Mar  7 18:22:03.125662 e07265d2546e NOTICE #orchagent: :- removeLagMember: Remove member Ethernet88 from LAG PortChannel008 lid:20000000005ff lmid:1b000000000600
Mar  7 18:22:03.125691 e07265d2546e ERR #orchagent: :- meta_sai_validate_oid: object key SAI_OBJECT_TYPE_MIRROR_SESSION:oid:0xe000000000603 doesn't exist
Mar  7 18:22:03.125695 e07265d2546e ERR #orchagent: :- deactivateSession: Failed to deactivate mirroring session TEST_SESSION
Mar  7 18:22:04.126757 e07265d2546e NOTICE #orchagent: :- removeLag: Remove LAG PortChannel008 lid:20000000005ff
```
Verified that the above …

Deactivate mirror session only when status is true in updateLagMember

---

orchagent/muxorch.cpp
tests/test_mux.py

**What I did**
Added safety check to handle one scenario of fdb ageout and mux state change. 
If no fdb exists, return the state of current mux port associated. 

[MuxOrch] FDB ageout safety check

---

orchagent/watermarkorch.cpp
orchagent/watermarkorch.h
tests/test_watermark.py

Signed-off-by: Petro Bratash <petrox.bratash@intel.com>
**What I did**
Add handling the clear request for 'Q_SHARED_ALL'
On this [PR](https://github.com/Azure/sonic-utilities/pull/1149) added new commands :
```
sonic-clear queue persistent-watermark all
sonic-clear queue watermark all
```
Without these changes, commands will result in
https://github.com/Azure/sonic-swss/blob/master/orchagent/watermarkorch.cpp#L221
Run:
```
sonic-clear queue persistent-watermark all
sonic-clear queue watermark all
```
PR in sonic-utilities:  https://github.com/Azure/sonic-utilities/pull/1149

Handle the clear request for 'Q_SHARED_ALL'

---

cfgmgr/buffermgrdyn.cpp
tests/test_buffer_dynamic.py

**What I did**
Enhance the field checking in table handling
- Fix a typo in vs test.
- Add field name-checking in `BUFFER_PG` handling.
- Use `else if` instead of `if` if the `field` matches one field of the table because in that case, it won't match others
Signed-off-by: Stephen Sun stephens@nvidia.com
Run vs test and regression test.

[Dynamic Buffer Calc] Enhance the field checking in table handling

---

orchagent/port.h

**What I did**
Initialize System port type variable to SAI_SYSTEM_PORT_TYPE_LOCAL
Fix PR builds failed with kvm-t1-lag tests on route_check script. 
Logs:
1. Route add failed for get nexthop:
`Mar 25 06:17:38.194329 vlab-03 INFO swss#orchagent: :- addRoute: Failed to get next hop 10.0.0.33@Ethernet64 for 100.1.0.17/32`
2.  During add Nexthop, the alias field got replaced due to incorrect return value returned as [True  ](https://github.com/Azure/sonic-swss/blob/master/orchagent/neighorch.cpp#L174)
3. Nexthop alias field became [empty ](https://github.com/Azure/sonic-swss/blob/master/orchagent/neighorch.cpp#L181)while adding to cache, which resulted in mismatch of route get
`Mar 25 20:32:44.180521 vlab-03 NOTICE swss#orchagent: …

[System Port] Initialize system port 'type' variable

---

cfgmgr/buffer_check_headroom_mellanox.lua
orchagent/port.h
orchagent/portsorch.cpp
orchagent/portsorch.h

Revert "Revert "[buffermgr] Support maximum port headroom checking""

---

tests/test_buffer_dynamic.py

**What I did**
Stabilize the vs test.
Stabilize the vs test.
Run the vs test.
One logic in the vs test is to check consistency between APPL_DB and ASIC_DB for buffer profiles. However, the mapping between are stored in the orchagent and can't be accessed from outside. The way we fetch that mapping is:
1. Get the SAI OID of all the buffer profiles in ASIC_DB at the beginning of the test, and store it to set `P1`
2. Get the SAI OID of all the buffer profiles in ASIC_DB after a new buffer profile has been created, and stored it to `P2`
3. The newly created buffer profile in ASIC_DB should be `P2 - P1`.
However, sometimes there can be more than one OIDs in `P2 - P1`. This is because …

[Dynamic Buffer Calc] Stabilize the vs test

---

orchagent/aclorch.cpp
orchagent/bufferorch.cpp
orchagent/copporch.cpp
orchagent/dtelorch.cpp
orchagent/fdborch.cpp
orchagent/fgnhgorch.cpp
orchagent/intfsorch.cpp
orchagent/macsecorch.cpp
orchagent/mirrororch.cpp
orchagent/natorch.cpp
orchagent/neighorch.cpp
orchagent/orch.cpp
orchagent/orch.h
orchagent/policerorch.cpp
orchagent/portsorch.cpp
orchagent/qosorch.cpp
orchagent/routeorch.cpp
orchagent/sfloworch.cpp
orchagent/switchorch.cpp
orchagent/tunneldecaporch.cpp
orchagent/vrforch.cpp

**What I did**
Add SAI failure handling functions in aclorch, bufferorch, copporch, dtelorch, fdborch, fgnhgorch, intfsorch, mirrororch, natorch, policerorch, macsecorch, portsorch, qosorch, sfloworch, switchorch, tunneldecaporch, vrforch.
Failure notification mechanism to ensure enough notifications in the presence of SAI failures and avoid running switches with unhandled failures.

Add failure notification for orchagent

---

orchagent/Makefile.am
orchagent/intfsorch.cpp
orchagent/main.cpp
orchagent/neighorch.cpp
orchagent/orchdaemon.cpp
orchagent/port.h
orchagent/portsorch.cpp
orchagent/portsorch.h
tests/mock_tests/Makefile.am
tests/mock_tests/aclorch_ut.cpp
tests/mock_tests/mock_orchagent_main.cpp
tests/mock_tests/portsorch_ut.cpp
tests/test_virtual_chassis.py
tests/virtual_chassis/1/default_config.json
tests/virtual_chassis/2/default_config.json
tests/virtual_chassis/3/default_config.json

**What I did**
System LAG (PortChannel for chassis system) support
In VOQ based chassis systems, to forward across different ASICs through Portchannels configured in different asics, a new attribute called "system port aggregator id" (spa) is defined for the LAG objects. The system lag implementation in this PR allocates unique ID for Portchannel ans the id is sent to SAI to create the LAG with spa. This chassis wide unique spa is sync-ed with chassis app db so that non-owner asics will create corresponding remote LAGs with the same spa.
For more detailed information refer: Distributed VOQ LAG HLD https://github.com/Azure/SONiC/pull/697
- test_virtual_chassis.py with system lag test case passes
This PR depends on the following …

[voq/systemlag] Voq system lag functionality

---

cfgmgr/buffermgrdyn.cpp

**What I did**
Bug:
The buffermgrd can keep adding suffix to the buffer pool reference if the buffer pool isn't found when it is being referenced. In most of the cases, it's caused by wrong configuration.
Cause:
In handleBufferProfileTable, the value of each field is designated by a (lvalue) reference to the object in the tuple, which means the object in the tuple will be changed if the value is changed in the function.
Fix:
Pass the value of each field by value instead of reference.
Fix bug.
Manually test.

[Dynamic Buffer Calc] Bug fix: A suffix keeps being added if a non-exist buffer pool is referenced.

---

cfgmgr/buffermgrdyn.cpp

**What I did**
Fix bug: Don't update pools when ingress_lossless_pool is created during initialization.
- This bug increases the converging time of fast reboot for ~5 seconds.
- It can also cause error logs during system startup:
```
Mar 29 11:57:32.640257 mtbc-sonic-03-2700 ERR swss#orchagent: message repeated 19408 times: [ :- resolveFieldRefArray: Failed to parse profile reference:[BUFFER_PROFILE_TABLE:ingress_lossy_profile]]
```
Fix the bug.
Run regression and vs test.
The buffer pools will be created after a short-timer and then won't be updated until the initialization has finished. The idea is to call `recalculateSharedBufferPool` from `checkSharedBufferPoolSize` only once …

[Dynamic Buffer Calc] Don't update pools when ingress_lossless_pool is created during initialization

---

orchagent/Makefile.am

This is possible workaround for cross compile issues with json.hpp
symbols generated on armhf architecture.
**What I did**
Changed libs order to change symbol resolve order in runtime for swsscommon
To workaround possible issue related to cross compile armhf arch
Build locally on marvell device
Main issue explained here: https://github.com/Azure/sonic-sairedis/issues/801

[Makefile] Reorder libsaimetadata and libswsscommon

---

.azure-pipelines/build-template.yml
azure-pipelines.yml

**What I did**
archive swss pytests to be used for other pipeline vstests
in other pipelines, they will download swss and pytests. this is make sure the swss.deb and pytests are matched.

[ci]: archive swss pytests

---

tests/test_macsec.py

What I did:
Skip DVS MACSEC test case till macsec orch code is made compatible with SAI v1.8.0
Why I did:
Without this sai-redis PR build fails because of DVS VS test. This change will resolve dead-lock between swss and sai-redis repo PR to get merged.
How I verify:
Verify test is skipped.

Skip Macsec test case till macsec orch code is made SAIv1.8.0 compatible

---

cfgmgr/buffermgrdyn.cpp
cfgmgr/buffermgrdyn.h
tests/test_buffer_dynamic.py
tests/test_buffer_mode.py

**What I did**
1. Improve coding style
2. Fix LGTM alerts
Run regression and vs test
- Always 1 space between `//` and the comments
- Always use the capital letter at the beginning of the sentence
- Rename function: `refreshPriorityGroupsForPort` => `refreshPgsForPort`
- Fix LGTM alerts

[Dynamic Buffer Calc] Enhancement: coding style and LGTM alerts

---

cfgmgr/intfmgr.cpp
cfgmgr/intfmgr.h
tests/test_warm_reboot.py

Signed-off-by: Stepan Blyschak <stepanb@nvidia.com>
**What I did**
If there is no pending configuration intfmgrd should reach reconciled state immediately. Same does for example vlanmgrd.
fdbsyncd waits till intfmgrd reaches reconciled state otherwise exits with exception about timeout. As a result sanity checkers complain about that.
I tested it on the switch by running warm-reboot and observed no fdbsyncd failure.
Also I wrote a simple test for intfmgrd warm restart when there are no interfaces in config_db.

[intfmgrd] reach reconciled state at start when there are no interfaces configuration to process

---

cfgmgr/vlanmgr.cpp
orchagent/port.h
orchagent/portsorch.cpp
orchagent/portsorch.h
tests/dvslib/dvs_vlan.py
tests/test_vlan.py

* Infrastructure needed for the VNET ping tool
**What I did**
Add support of VLAN host interface
It is infrastructure needed for the VNET ping tool
Configured new VLAN with "hostif_name" attribute and verified that it created in HW
N/A

[vlan] Add support of VLAN host interface

---

tests/test_virtual_chassis.py

**What I did**
In Virtual chassis test suite, time sleep for 1 second after creating and deleting system lag is replaced by
DVS's wait_for_n_keys() function.
Potential fix for issue https://github.com/Azure/sonic-swss/issues/1687.
Ran pytest on docker sonic vs image multiple times with this fix. 100% pass. 

[vstest] VOQ system lag vs test timing issue fix

---

orchagent/natorch.cpp
tests/test_nat.py

Issue : CRM used counters are not getting updated for SNAT and DNAT entries
Steps to recreate:
Add a static NAT entry and verify the CRM counters
```
root@sonic:/home/admin# config nat feature enable
root@sonic:/home/admin# config interface ip add Ethernet9 12.12.0.1/24
root@sonic:/home/admin# config interface ip add Ethernet11 125.56.90.12/24
root@sonic:/home/admin# config nat add interface Ethernet11 -nat_zone 1
root@sonic:/home/admin# 
root@sonic:/home/admin# config nat add static basic 125.56.90.8 12.12.0.2
root@sonic:/home/admin# show nat translations 
Static NAT Entries         ..................... 2
Static NAPT Entries        ..................... 0
Dynamic NAT Entries        ..................... 0
Dynamic NAPT Entries       ..................... 0
Static Twice NAT Entries …
```

NAT : Update the CRM used counters for SNAT and DNAT entries

---

orchagent/crmorch.cpp

**What I did**
Changes update switch statement in CrmOrch::getResAvailableCounters() to use CrmResourceType enum which guarantees the uniqueness of labels in the switch statement.
Previously, the switch statement in CrmOrch::getResAvailableCounters() used values from two different enums:  sai_switch_attr_t and sai_acl_table_attr_t.  There is no guarantee that the values from sai_switch_attr_t will not conflict with values from sai_acl_table_attr_t, so it is not good coding practice.  Any future development in this area should not be using values from multiple enums with overlapping values in a single switch statement.  
Additionally, future CRM development can use the new sai_object_type_get_availability() with sai_object_type_t instead of defining new SAI attrs per …

fix for CRM available bug

---

cfgmgr/intfmgr.cpp
cfgmgr/intfmgr.h
tests/test_warm_reboot.py

Signed-off-by: Stepan Blyschak stepanb@nvidia.com
**What I did**
If there is no pending configuration intfmgrd should reach reconciled state immediately. Same does for example vlanmgrd.
fdbsyncd waits till intfmgrd reaches reconciled state otherwise exits with exception about timeout. As a result sanity checkers complain about that.
I tested it on the switch by running warm-reboot and observed no fdbsyncd failure.
Also I wrote a simple test for intfmgrd warm restart when there are no interfaces in config_db.

[202012][intfmgrd] reach reconciled state at start when there are no interfaces configuration to process

---

cfgmgr/buffer_pool_mellanox.lua

**What I did**
Fix buffer over subscription in the buffer pool calculation.
Run regression and manual test
To calculate the buffer pool size, we need to accumulate all reserved memory and than subtract the sum from total available memory. In the current implementation, one part hasn’t been added to reserved memory, which causes the buffer pool size larger than it should be.
To fix it, we need to add it to reserved memory.

[Dynamic buffer calc][Mellanox] Fix bug: buffer over subscription in buffer pool size calculation

---

orchagent/port.h
orchagent/portsorch.cpp
tests/test_port.py
tests/test_port_an.py

**What I did**
Allowing the first time configuration for FEC and Autoneg to be pushed to SAI even if they are default.
In orchagent, the port struct is pre-initialized with fec = none and autoneg = false (Default SAI values). However in different hardware the underlying implementation might be different. There can also be requirement where the user values need to be forced. In current logic due to the port struct being initialized with default, fec = none or an = false configurations are not pushed from orchagent to SAI. In order to push it even in default case the conditional checks are modified.
Configure FEC as none and autoneg as false and check if ASIC DB is programmed.
This change will force the FEC and autoneg …

Allowing the first time FEC and AN configuration to be pushed to SAI

---

orchagent/port.h
orchagent/portsorch.cpp
tests/test_port.py
tests/test_port_an.py

**What I did**
Allowing the first time configuration for FEC and Autoneg to be pushed to SAI even if they are default.
In orchagent, the port struct is pre-initialized with fec = none and autoneg = false (Default SAI values). However in different hardware the underlying implementation might be different. There can also be requirement where the user values need to be forced. In current logic due to the port struct being initialized with default, fec = none or an = false configurations are not pushed from orchagent to SAI. In order to push it even in default case the conditional checks are modified.
Configure FEC as none and autoneg as false and check if ASIC DB is programmed.
This change will force the FEC and autoneg …

[202012] Allowing the first time FEC and AN configuration to be pushed to SAI

---

tests/test_acl_cli.py

Add a new test case to catch the bug where calling "config acl add table" multiple
times causes the "ports" field to be deleted from config DB.
**What I did/why I did it**
I added a test case to guard against regressions like the one described in https://github.com/Azure/sonic-utilities/pull/1519.
Ran the test case w/ and w/o the change from 1519.

[acl] Add regression test for `config acl` CLI command

---

cfgmgr/tunnelmgr.cpp
orchagent/muxorch.cpp
orchagent/neighorch.cpp
orchagent/routeorch.cpp
tests/test_mux.py

**What I did**
1. In case of standby mux, associated routes may come to orch with ifname of `tun0`. Handle the case when nexthop is non-zero
2. For ECMP, multiple nexthop IPs can have the same sai nexthop id (tunnel NH). Existing data structure is unable to handle such case. Added a secondary map if nexthops are shared
3. VS test to cover both cases. 
For dual tor SLB support

[Mux orch] Fix tunnel based NHs for IPv6 and ECMP routes

---

cfgmgr/nbrmgr.cpp
cfgmgr/nbrmgr.h
orchagent/neighorch.cpp
orchagent/portsorch.cpp
orchagent/routeorch.cpp
portsyncd/linksync.cpp
tests/conftest.py
tests/test_virtual_chassis.py
tests/virtual_chassis/1/default_config.json
tests/virtual_chassis/2/default_config.json
tests/virtual_chassis/3/default_config.json

**What I did**
Changes to support inband interface configuration
The VOQ chassis needs inband interface in the kernel for cpu to cpu communication across different asic instance and remote neighbor programming in the kernel. This PR adds support for configuring inband interface so that kernel interface can be created via sonic configuration.
swss vs test (test_virtual_chassis.py) to verify the remote neigh programming.
Reference: VOQ HLD: https://github.com/Azure/SONiC/blob/master/doc/voq/voq_hld.md

[voq/inbandif] Voq inbandif port

---

orchagent/macsecorch.cpp

**What I did**
In adapting to the MACsec driver for Arista 7280Cr3, we found it is necessary to set SAI_MACSEC_ATTR_PHYSICAL_BYPASS_ENABLE to True, to successfully change the MACsec status from enable to disable (expecting that the traffic can pass through without encryption thereafter). The reason behind is that the default value of the attribute is False, if it is False, the driver understands it as the user is not allowing to bypass MACsec, yielding the result of disabling MACsec not as expected.

[MACsec]: Set macsec to bypass by default

---

cfgmgr/sflowmgr.cpp
tests/test_sflow.py

**What I did**
1) Currently, the SflowMgr::sflowUpdatePortInfo method updates the sampling-rate only when adding a new-port. Updated the method to be active for speed change notifications all the time.
2) Added two new Unit Tests covering these use cases
```
config sflow enable
config interface speed Ethernet0  25000  (Let's suppose Original Speed for Ethernet0 is 100G)
show sflow interface | grep Ethernet0  
Expected:
Should see a sampling rate of 25000 
Observed:
Sampling rate is unaffected by speed change i.e is still 100000
```
1) All the Unit Tests passed
2) Manually Verified using the the steps given above
3) Community SFlow Test wasn't affected by the changes

[SflowMgr] SamplingRate Update by Speed Change Added

---

cfgmgr/buffermgrdyn.cpp
cfgmgr/buffermgrdyn.h

**What I did**
This is a supplement of Azure/sonic-swss#1685. In that PR, most of the cases in which the buffer pool updated during initialization have been avoided but there are still some rare cases not covered. Eg., it will try to recalculate the pool size because the lossless PSs are removed if one port is admin down.
In this PR, we will make sure that the buffer pools will be updated only once during initialization.
Run regression and manual test

[Dynamic buffer calc] Update pool sizes during initialization from timer only

---

orchagent/routeorch.cpp
tests/test_route.py

**What I did**
Allow route orch to add/remove routes blackhole routes and add dvs tests.
Verify that the blackhole route gets applied into ASIC_DB with `SAI_PACKET_ACTION_DROP`
```
admin@vlab-01:~$ vtysh -c "configure terminal" -c "ip route 3.3.3.0/24 blackhole"
admin@vlab-01:~$ sonic-db-cli APPL_DB hgetall "ROUTE_TABLE:3.3.3.0/24"
{'blackhole': 'true'}
admin@vlab-01:~$ sonic-db-cli ASIC_DB keys "*3.3.3.0/24*"
ASIC_STATE:SAI_OBJECT_TYPE_ROUTE_ENTRY:{"dest":"3.3.3.0/24","switch_id":"oid:0x21000000000000","vr":"oid:0x3000000000022"}
admin@vlab-01:~$ sonic-db-cli ASIC_DB hgetall "ASIC_STATE:SAI_OBJECT_TYPE_ROUTE_ENTRY:{\"dest\":\"3.3.3.0/24\",\"switch_id\":\"oid:0x21000000000000\",\"vr\":\"oid:0x3000000000022\"}"
{'SAI_ROUTE_ENTRY_ATTR_PACKET_ACTION': …
```

[routeorch] Add support for blackhole routes

---

orchagent/flexcounterorch.cpp
orchagent/flexcounterorch.h
orchagent/orchdaemon.cpp
orchagent/portsorch.cpp
orchagent/portsorch.h
tests/mock_tests/mock_orchagent_main.h
tests/mock_tests/portsorch_ut.cpp
tests/test_flex_counters.py
tests/test_pg_drop_counter.py

**What I did**
Update flex counters DB with counters stats only when counters are enabled.
As long as the polling counters are not enabled, flex counters information will stored internally on PortsOrch.
Creating flex counters objects on the DB will trigger 'SYNCD' to access the HW for query statistics capabilities.
This HW access takes time and will be better to finish boot before doing this (mainly for fast-reboot but good to have in general).
The flex counters are not crucial at boot time, we can delay it to the end of the boot process.
Reboot a switch and observer the flex counters DB populated after counters are enabled.

[flex-counters] Delay flex counters stats init for faster boot time

---

cfgmgr/sflowmgr.cpp
cfgmgr/sflowmgr.h
tests/test_sflow.py

Fixed incorrect interface admin-status when 'all' interface is disabled but there are local sampling-rate configurations.
The original changes are present in the [PR ](https://github.com/Azure/sonic-swss/pull/1224)
Signed-off-by: Venkatesan Mahalingam <venkatesan_mahalinga@dell.com>
**What I did**
Fixed a bug where the interface sFlow admin-status is not correct if the user configures a custom sFlow sampling-rate. (UT performed here)
As a side-effect of this fix, users can now restore the default sFlow sampling-rate with the default option using: config sflow interface sampling-rate Ethernet4 default
This is not tested here but will be tested when the config script update PR is submitted to sonic-utilities. The sFlow corresponding HLD and command-line reference will also be updated.
**Why …

Fix sFlow sampling-rate and admin-state

---

cfgmgr/vxlanmgr.cpp
cfgmgr/vxlanmgr.h

**What I did**
Rename m_stateTunnelVlanMapTable to m_stateNeighSuppressVlanTable.
I think rename state table can reduce the confusion.

Rename m_stateTunnelVlanMapTable to m_stateNeighSuppressVlanTable.

---

orchagent/routeorch.cpp
orchagent/routeorch.h

**What I did**
reference #1501 : remove overlay nexthop  after updating the reference counter for a bulk of routes
error log
~~~
Mar 16 06:35:48.090274 accton-leaf-demo-002-leaf1 NOTICE swss#orchagent: :- removeRoutePost: Remove overlay Nexthop 10.0.0.28@vniVlan1000@10000@04:f8:f8:6a:fa:91
Mar 16 06:35:48.090333 accton-leaf-demo-002-leaf1 NOTICE swss#orchagent: :- removeOverlayNextHops: Remove overlay Nexthop 10.0.0.28@vniVlan1000@10000@04:f8:f8:6a:fa:91
Mar 16 06:35:48.090333 accton-leaf-demo-002-leaf1 NOTICE swss#orchagent: :- removeNextHopTunnel: NH tunnel remove for vtep1, ip 10.0.0.28, mac 04:f8:f8:6a:fa:91, vni 10000
Mar 16 06:35:48.090376 accton-leaf-demo-002-leaf1 NOTICE swss#orchagent: :- removeNextHop: remove NH tunnel for ip 10.0.0.28, mac 04:f8:f8:6a:fa:91, …

Fix overlay nexthop ref_count is incorrect issue when add and delete route at same time.

---

orchagent/flexcounterorch.cpp
orchagent/flexcounterorch.h
orchagent/orchdaemon.cpp
orchagent/portsorch.cpp
orchagent/portsorch.h
tests/mock_tests/mock_orchagent_main.h
tests/mock_tests/portsorch_ut.cpp
tests/test_flex_counters.py
tests/test_pg_drop_counter.py

**What I did**
Update flex counters DB with counters stats only when counters are enabled.
As long as the polling counters are not enabled, flex counters information will stored internally on PortsOrch.
Creating flex counters objects on the DB will trigger 'SYNCD' to access the HW for query statistics capabilities.
This HW access takes time and will be better to finish boot before doing this (mainly for fast-reboot but good to have in general).
The flex counters are not crucial at boot time, we can delay it to the end of the boot process.
Reboot a switch and observer the flex counters DB populated after counters are enabled.

[flex-counters] Delay flex counters stats init for faster boot time [202012]

---

cfgmgr/teammgr.cpp
cfgmgr/teammgr.h
tests/test_portchannel.py

**What I did**
Fix https://github.com/Azure/sonic-buildimage/issues/4009
When a member port is added to port-channel, create a unique LACP key.
When adding a member port to port-channel set the LACP key to a unique number.
The number is extracted from the port-channel name and will be the number at the end of the port-channel name with an additional digit at the beginning in order to make sure that this number will be unique in the system.
If LACP key is not set, then the peer will not be able to distinguish the ports which are connected to different port-channels, as it will receive the LACP key as 0 for all the ports from different port-channels.
I configure a SONiC switch to have two port-channels and on a second switch, I created one port-channel …

[teammgrd]: Create unique LACP key for port-channel

---

orchagent/routeorch.cpp

**What I did**
Remove SAI failure handling related code in supporting blackhole routes.
SAI failure handling logic is not included in the 202012 branch. Removing the code to avoid build errors.

[202012] Fix build error in adding support for blackhole routes

---

orchagent/fdborch.cpp

Fdb entries can be deleted with user specifying vlan or port or vlan&&port.The secifying vlan or port can be configured by cli at another issue#565 in Azure / sonic-utilities.
**What I did**

[fdb]fdborch: fdb entries are deleted according to vlan or port or vlan&&port

---

orchagent/switchorch.cpp

**What I did**
1.  Add more conditions to capture SAI return code due to not supported SAI attributes. Original code only judge:
`status ==  SAI_STATUS_NOT_SUPPORTED || status == SAI_STATUS_NOT_IMPLEMENTED`
Add more conditions:
`SAI_STATUS_IS_ATTR_NOT_SUPPORTED(status) || SAI_STATUS_IS_ATTR_NOT_IMPLEMENTED(status)`
2.  Print the error code in hex instead of dec to make it more readable.
To eliminate below error msg on the platform which not support "SAI_SWITCH_ATTR_MAX_NUMBER_OF_TEMP_SENSORS"
`May 10 13:02:59.806194 sonic ERR swss#orchagent: :- initSensorsTable: ASIC sensors : failed to get SAI_SWITCH_ATTR_MAX_NUMBER_OF_TEMP_SENSORS: -196608`
On the Mellanox platform, in the reboot process, the above error msg will not be observed.
**Details if …

Fix error msg due to not supported "SAI_SWITCH_ATTR_MAX_NUMBER_OF_TEMP_SENSORS"  attributes

---

fpmsyncd/routesync.cpp
fpmsyncd/routesync.h
orchagent/nexthopgroupkey.h
orchagent/nexthopkey.h
orchagent/routeorch.cpp
tests/test_nhg.py

**What I did**
1. In fpmsyncd, parse weight field in netlink message, set APP_DB if weight is set.
2. In routeorch, collect weight and pass weight attribute to next hop group member object.
In order to set weight for next hop group members. To support weighted ECMP.
1. With cRPD as routing stack, configure bgp weight policy to different next hops. 
2. Bring up routes on both next hops. And send traffic to the BGP routes.
3. Verify traffic is distributed with the portion set by weight policy.

[nhg]: Add support for weight in nexthop group member.

---

orchagent/portsorch.cpp

**What I did**
Fix typo in PortsOrch::initPortSupportedSpeeds
It stop orchagent from getting supported port speed from SAI
Manual test

[orchagent] Fix typo in PortsOrch::initPortSupportedSpeeds

---

orchagent/tunneldecaporch.cpp

**What I did**
Set default MTU for the underlay loopback interface to 9100 in order to make it working with jumbo frames.
Overlay loopback is used for IP-in-IP tunnel and without setting MTU jumbo frames are trapped to CPU but they should be successfully routed to the appropriate destination.
With this change, all internal loopback interfaces are created with 9100 MTU size (both underlay and overlay) in continues to PR https://github.com/Azure/sonic-swss/pull/1299
* Configure IP-in-IP tunnel
* Send jumbo frames and verify that they are correctly routed
N/A

[tunneldecaporch] Set default MTU for the overlay loopback interface

---

doc/Configuration.md

Updated the Configuration Database documentation to include settings supported by the NTP daemon to globally configure its source port, which controls the port from which NTP requests are made (needs to be overridden in some cases) and also controls whether it runs within the mgmt vrf (which also needs to be set in some common configurations)

[doc] Update CONFIG_DB manual to include NTP global settings

---

orchagent/bulker.h
orchagent/main.cpp
orchagent/orchdaemon.cpp
orchagent/routeorch.cpp
tests/mock_tests/bulker_ut.cpp

**What I did**
This is to backport changes in https://github.com/Azure/sonic-swss/pull/1744 to 202012.
Limit the size of the bulker.
Without a constraint on the size of bulkers, the bulked operation may take longer than the SAI timeout to finish. Such behavior would result in errors and swss crash. This PR limits the bulk size and avoids SAI timeout in bulk mode.

[202012][Bulk mode] Limit the size of bulker

---

cfgmgr/nbrmgr.cpp
orchagent/neighorch.cpp
orchagent/neighorch.h
orchagent/routeorch.cpp
tests/test_route.py
tests/test_warm_reboot.py

**What I did**
This is to backport changes in https://github.com/Azure/sonic-swss/pull/1704 to 202012.
Resolve neighbor entries if nexthop does not exist when adding routes.
In some scenarios, such as adding static routes, the nexthop may not be available, this PR would trigger an attempt to resolve the neighbor. Note that routeorch would only trigger resolution of a neighbor once even if it fails. The arp_update script would find the unresolved neighbor and retry neighbor resolution.

[202012] Resolve neighbor when nexthop does not exist

---

orchagent/portsorch.cpp
tests/test_sub_port_intf.py

**What I did**
- Init sub port Port object reference count
- Increase parent port Port object reference count
- Check sub port Port object reference count drops to zero
- Decrease parent port Port object reference count
- Check physical port Port object reference count drops to zero
Enhancement
Issue parent port removal at APPL_DB level before removing sub port interface. Verify that parent port persists in ASIC_DB until sub interface is removed.
Without the change, extended vs test fails:
```
========================================================================== FAILURES ===========================================================================
_________________________________________________________ TestSubPortIntf.test_sub_port_intf_removal …
```

[sub intf] Port object reference count update
